// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= The {CE}
:revdate: draft
:title: The {CE}
:description: What makes the {CE} special, especially in comparison to the other {CMK} editions, can be found here.

{related-start}
xref:cse#[The {SE}]
xref:intro_setup#[Setting up {CMK}]
xref:update#[Updates and Upgrades]
{related-end}

include::include_draft.asciidoc[]


[#intro]
== Introduction

There is no perfect software solution for every user and every application.
What works for one person may be too much or too little, too simple or too complex for another.
That is why {CMK} is available in a number of different editions.
These differ above all in their range of features and suitability for specific areas of application.
In the following short article we would like to introduce the {CCE}.


[#editions]
== Overview of the {CE}

The {CE} is currently the most comprehensive edition of {CMK}.
Its content is based on the xref:cse#[{CSE}], but it additionally provides extensive cloud functions.
This makes the {CE} particularly valuable for users whose hosts are located in a cloud and who also want to set up their entire monitoring in a cloud.

Support when moving applications and processes to the cloud, i.e. in so-called _lift and shift_ scenarios, is already integrated in all editions 
-- which simplifies the implementation of a monitoring of Amazon Web Services (AWS), Microsoft Azure and Google Cloud Platform (GCP).
In addition, the {CE} provides also cloud-specific xref:glossar#check_plugin[check plug-ins].
This way, you can continue to use the {EE} when transitioning from a data center to a cloud.
If you would subsequently also like to use the SaaS and PaaS products that a cloud can additionally provide, you can upgrade to the {CE}.


[#functions]
== Additional functions with the {CE}

The key features of the {CE} that differentiate it from other editions:

* The {CE} is available through the AWS and Microsoft marketplaces.

* Cloud-specific dashboards +
// This block is new
// start translation
////
In der {CE} gibt es für AWS, Microsoft Azure und GCP spezifische Dashboards.

* Überwachung von OpenShift: +
Die xref:monitoring_openshift#[Überwachung von OpenShift] mit dem Spezialagenten für Kubernetes ist der {CE} vorbehalten.
////
// end translation

* Advanced check plug-ins: +
The {CE} includes additional cloud-specific check plug-ins for monitoring xref:monitoring_aws#[Amazon Web Services (AWS)], xref:monitoring_azure#[Microsoft Azure] and xref:monitoring_gcp#[Google Cloud Platform (GCP)].

* Configuration of a push agent: +
In all {CMK} editions, the {CMK} server initiates communication with a host and requests the data from the {CMK} agent -- in the so-called xref:glossar.html#pull_mode[pull mode].
With the {CE} you can additionally use the xref:glossar.html#push_mode[push mode].
You configure the push mode in the properties of a host, in the section on xref:hosts_setup#monitoring_agents[monitoring agents].

* Auto-registration of hosts: +
In the {CE}, you can have xref:hosts_autoregister#[hosts created automatically] that have a {CMK} agent installed.
This includes registering the agent with the {CMK} server, establishing a TLS-encrypted connection, creating the host, performing a service discovery and activating the changes,
so that the host is added to the monitoring environment -- all fully automatically.
Auto-registration works for pull and push agents.


[#upgrade]
== Upgrading to the {CE}

You can test the {CE} without obligation, because it is not limited in the first 30 days.
By entering a license key after 30 days at the latest, you can then use the {CE} without limitations.

To upgrade from one of the other editions to the {CE}, follow the xref:update#upgrade[upgrade description].


// This block is new
// start translation
////
[#details]
== Unterschiede der Komponenten im Detail

[#ui]
=== Monitoring-Oberfläche

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen

|Cloud-Dashboards |In der Cloud Edition von Checkmk finden Sie im Monitoring die spezifischen Dashboards für xref:monitoring_aws#dashboards[AWS,] xref:monitoring_azure#dashboards[Azure] und xref:monitoring_gcp##dashboards[GCP.]

|OpenShift-Dashboards |Die sechs eingebauten xref:monitoring_openshift#dashboards[Dashboards für Kubernetes] können in der {CE} zur Überwachung von OpenShift-Clustern genutzt werden.
|===


[#agents]
=== Monitoring-Agenten

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen

|Push-Modus |Nur in der {CE} kann der xref:wato_monitoringagents#agents[{CMK}-Agent] für Linux und für Windows im xref:glossar#push_mode[Push-Modus] konfiguriert und genutzt werden.
Den Modus (Push oder xref:glossar#pull_mode[Pull]) konfigurieren Sie in den Eigenschaften eines Hosts oder Ordners, im Abschnitt zu den xref:hosts_setup#monitoring_agents[Monitoring-Agenten.]
Der Push-Modus ist auf den Agent Controller angewiesen und daher im Legacy-Modus des Agenten nicht verfügbar.

|Autoregistrierung |Die {CE} bietet die Möglichkeit, Hosts automatisch bei der Registrierung anzulegen mit der sogenannten xref:hosts_autoregister#[Autoregistrierung.]
Zur Konfiguration der {CMK}-Instanz dient der Regelsatz xref:hosts_autoregister#rule_autoregister_site[[.guihint]#Agent registration.#]
Auch die Autoregistrierung setzt den Agent Controller voraus.

|Agentenbäckerei (_Agent Bakery_) |In der {CE} können Sie die Agentenbäckerei zusätzlich nutzen, um Agentenpakete mit einer Konfiguration für die Autoregistrierung zu versehen.
Die Regel für die Agentenbäckerei heißt xref:hosts_autoregister.html#rule_autoregister_bakery[[.guihint]#Agent controller auto-registration (Cloud Edition).#]
Diese Pakete führen die Registrierung automatisch nach der Installation durch.

|Berechtigung zur Agentenregistrierung | Die xref:wato_user#predefined_roles[vordefinierte Rolle] `agent_registration` enthält in der {CE} zusätzliche Berechtigungen, um Hosts automatisch zu erstellen.
|===


[#provision]
=== Bereitstellung

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen
|Test der Edition |Von den verfügbaren Enterprise xref:intro_setup#editions[Editionen], d.h. {SE}, {CE} und {ME}, können Sie die {CE} 30 Tage lang in vollem Funktionsumfang unverbindlich testen.
In kleinem Rahmen, d.h. mit einer Instanz und bis zu 750 Services, können Sie {CMK} mit der {CE} auch dauerhaft ohne Subskription betreiben.
|===


[#other]
=== Weitere Funktionen

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen

|Check-Plugins für AWS |In der {CE} gibt es zusätzlich Check-Plugins für die AWS Cloud-Produkte
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_lambda[AWS Lambda,^]
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_ecs[Elastic Container Service (ECS),^]
link:https://checkmk.com/de/integrations/aws_route53[Route 53,^]
link:https://checkmk.com/de/integrations/aws_cloudfront[CloudFront,^]
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=elasticache[ElastiCache for Redis^] und
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_sns[Simple Notification Service (SNS).^]

|Check-Plugins für Azure |In der {CE} gibt es zusätzlich Check-Plugins für die Azure-Produkte
link:https://checkmk.com/de/integrations/azure_app_gateway[Application Gateway^] und 
link:https://checkmk.com/de/integrations/azure_vault_backup_containers[Recovery Services vaults.^]

|Check-Plugins für GCP |In der {CE} gibt es zusätzlich Check-Plugins für die Goggle Cloud-Produkte
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_function[Cloud Functions,^]
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_run[Cloud Run^] und
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_redis[Memorystore for Redis.^]
|===
////
// end translation