// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= The {CE}
:revdate: draft
:title: The {CE}
:description: What makes the {CE} special, especially in comparison to the other {CMK} editions, can be found here.

{related-start}
xref:cse#[The {SE}]
xref:intro_setup#[Setting up {CMK}]
xref:update#[Updates and Upgrades]
{related-end}

include::include_draft.asciidoc[]


[#intro]
== Introduction

There is no perfect software solution for every user and every application.
What works for one person may be too much or too little, too simple or too complex for another.
That is why {CMK} is available in a number of different editions.
These differ above all in their range of features and suitability for specific areas of application.
In the following short article we would like to introduce the {CCE}.


[#editions]
== Overview of the {CE}

The {CE} is currently the most comprehensive edition of {CMK}.
Its content is based on the xref:cse#[{CSE}], but it additionally provides extensive cloud functions.
This makes the {CE} particularly valuable for users whose hosts are located in a cloud and who also want to set up their entire monitoring in a cloud.

Support when moving applications and processes to the cloud, i.e. in so-called _lift and shift_ scenarios, is already integrated in all editions 
-- which simplifies the implementation of a monitoring of Amazon Web Services (AWS), Microsoft Azure and Google Cloud Platform (GCP).
In addition, the {CE} provides also cloud-specific xref:glossar#check_plugin[check plug-ins].
This way, you can continue to use the {EE} when transitioning from a data center to a cloud.
If you would subsequently also like to use the SaaS and PaaS products that a cloud can additionally provide, you can upgrade to the {CE}.


[#functions]
== Additional functions with the {CE}

The key features of the {CE} that differentiate it from other editions:

* The {CE} is available through the AWS and Microsoft marketplaces.

* Cloud-specific dashboards +

* Advanced check plug-ins: +
The {CE} includes additional cloud-specific check plug-ins for monitoring xref:monitoring_aws#[Amazon Web Services (AWS)], xref:monitoring_azure#[Microsoft Azure] and xref:monitoring_gcp#[Google Cloud Platform (GCP)].

* Configuration of a push agent: +
In all {CMK} editions, the {CMK} server initiates communication with a host and requests the data from the {CMK} agent -- in the so-called xref:glossar.html#pull_mode[pull mode].
With the {CE} you can additionally use the xref:glossar.html#push_mode[push mode].
You configure the push mode in the properties of a host, in the section on xref:hosts_setup#monitoring_agents[monitoring agents].

* Auto-registration of hosts: +
In the {CE}, you can have xref:hosts_autoregister#[hosts created automatically] that have a {CMK} agent installed.
This includes registering the agent with the {CMK} server, establishing a TLS-encrypted connection, creating the host, performing a service discovery and activating the changes,
so that the host is added to the monitoring environment -- all fully automatically.
Auto-registration works for pull and push agents.


[#upgrade]
== Upgrading to the {CE}

You can test the {CE} without obligation, because it is not limited in the first 30 days.
By entering a license key after 30 days at the latest, you can then use the {CE} without limitations.

To upgrade from one of the other editions to the {CE}, follow the xref:update#upgrade[upgrade description].

