include::global_attr.adoc[]
= The {CMK} {CE}
:revdate: draft
:title: The {CMK} {CE}
:description: What makes the {CE} special, especially in comparison to the other {CMK} editions, can be found here.

{related-start}
xref:intro_setup#[Setting up {CMK}]
xref:update#[Updates and Upgrades]
{related-end}


include::include_draft.asciidoc[]


== Introduction

This article is currently being prepared for publication.
Please be patient. Thank you! +
By the way, the https://docs.checkmk.com/master/de/cce.html[German version] of this article has already been updated -- if that is an alternative for you.


////
[#intro]
== Einleitung

Die eine perfekte Software-Lösung für jeden Nutzer und jeden Anwendungsfall gibt es nicht.
Was dem einen gefällt, ist dem anderen zu viel oder zu wenig, zu simpel oder zu komplex.
Deshalb ist auch {CMK} in verschiedenen Editionen verfügbar.
Diese unterscheiden sich vor allem im Leistungsumfang und in den Einsatzmöglichkeiten.
Im Folgenden möchten wir Ihnen die {CCE} (CCE) vorstellen.


[#editions]
== Einordnung der {CE}

Die {CE} ist die derzeit umfangreichste Edition von {CMK}.
Inhaltlich baut sie auf die {CEE} auf, bietet aber zusätzlich umfangreiche Cloud-Funktionen.
Damit ist sie vor allem für die Nutzer von Wert, deren Hosts in einer Cloud beheimatet sind und die auch ihr gesamtes Monitoring in einer Cloud aufsetzen wollen.

Die Unterstützung bei der Verlagerung von Anwendungen und Prozessen in die Cloud, d.h. in sogenannten _Lift and Shift_-Szenarien, ist bereits in allen Editionen integriert 
-- bei der Überwachung von Amazon Web Services (AWS), Microsoft Azure und Google Cloud Platform (GCP).
Die {CE} bietet darüber hinaus auch Cloud-native xref:glossar#check_plugin[Check-Plugins.]
So können Sie beim Übergang aus dem Rechenzentrum in eine Cloud weiter die {EE} nutzen.
Möchten Sie danach auch die SaaS und PaaS Produkte, die eine Cloud Ihnen bietet, nutzen, können Sie auf die {CE} upgraden.


[#functions]
== Zusätzliche Funktionen der {CE}

Die wesentlichen Funktionen der {CE}, die diese von anderen Editionen unterscheiden:

* Die {CE} ist über die Marketplaces von AWS und Microsoft verfügbar.

* Cloud-spezifische Dashboards +

* Fortgeschrittene Check-Plugins: +
Bei der Überwachung von xref:monitoring_aws#[Amazon Web Services (AWS),] xref:monitoring_azure#[Microsoft Azure] und xref:monitoring_gcp#[Google Cloud Platform (GCP)] gibt es in der {CE} zusätzliche, Cloud-native Check-Plugins.

* Konfiguration eines Push-Agenten: +
In allen {CMK}-Editionen initiiert der {CMK}-Server die Kommunikation mit einem Host und fragt die Daten vom {CMK}-Agenten ab - im sogenannten xref:glossar.html#pull_mode[Pull-Modus.]
Mit der {CE} können Sie zusätzlich den xref:glossar.html#push_mode[Push-Modus] nutzen.
Den Push-Modus konfigurieren Sie in den Eigenschaften eines Hosts, im Abschnitt zu den xref:hosts_setup#monitoring_agents[Monitoring-Agenten.]

* Autoregistrierung von Hosts: +
In der {CE} können Sie xref:hosts_autoregister#[Hosts automatisch erstellen lassen], auf denen ein {CMK}-Agent installiert ist.
Dies beinhaltet die Registrierung des Agenten beim {CMK}-Server, den Aufbau einer TLS-verschlüsselte Verbindung, die Erstellung des Hosts, die Durchführung einer Service-Erkennung und die Aktivierung der Änderungen,
so dass der Host in die Monitoring-Umgebung aufgenommen wird — alles vollautomatisch.
Die Autoregistrierung funktioniert für Pull- und Push-Agenten.


[#upgrade]
== Upgrade zur {CE}

Mit einem gültigen Lizenzschlüssel können Sie Ihre Test, Free oder Standard Edition jederzeit auf eine {CE} upgraden.
Folgen Sie dafür der xref:update#updatedemo[Upgrade-Beschreibung für die verschiedenen Editionen.]
////
