include::global_attr.adoc[]
= Quick start guide for Checkmk rack1
:revdate: 2019-04-04
:title: 
:description: 


* Unpack the device and first of all check that your shipment is complete.
* Plug in the device. When installing for the first time, you should ensure the following connections as a minimum:
* Monitor-to-VGA connector
* USB-keyboard
* Network connection (connector: LAN1)
* Power supply
* During the launching procedure of the device, a dialogue box asking you to initialise the RAID will appear on the screen (*NOTE: All data on the hard drives will be deleted!*).
 Confirm the box. After a few minutes the launching procedure will resume.
* On completion of the launching procedure, the console status view will be displayed.
* So that the appliance can be used for monitoring, there are some settings that need to be made. Press the key `&lt;F1&gt;` and, using the configuration dialogue box, configure the following settings as a minimum:
* Network configuration
* Access to the web interface
* Once you have configured these settings, you can access the web interface from a computer connected to the network by entering the URL `http://&lt;ipaddress&gt;/` into the web browser. Log into the web interface using the password you just configured.
* Select the item link:appliance_usage.html#site_management[instance administration] on the menu now shown and click on _Create new instance_ on the following page.
* Now create a new monitoring instance using the current dialogue box. This instance will start automatically.
* You can now call up the URL `http://&lt;ipaddress&gt;/&lt;instanz-id&gt;/` in your browser,

where you can set up {CMK} in the usual manner.
* In order to make things such as name resolution and sending emails possible, you must make further settings in the web interface. You can read more about this in the article on link:appliance_usage.html[basic configuration on the web interface].

Find out what to do next in the article link:checkmk_getting_started.html[{CMK} Getting Started].

