include::global_attr.adoc[]
= Quick start guide for {CMK} rack1
:revdate: draft
:title: Quick start guide for {CMK} rack1
:description: Short set-up guide for the physical {CMK} appliance.
:no-toc:


. Unpack the device and first of all check that your shipment is complete.

. Plug in the device. 
When installing for the first time, you should ensure the following connections as a minimum: Monitor-to-VGA connector, USB keyboard, network connection (connector: LAN1) and power supply.

. During the device's launching procedure, the console will prompt you to initialise the RAID *(Attention: All data on the hard drives will be deleted!).* Confirm.

. On completion of the launching procedure, the console status view will be displayed.

. So that the appliance can be used for monitoring, there are some settings that need to be made: 
Press the `F1` key and, using the configuration menu, configure the following settings as a minimum: xref:appliance_usage#network_access_config[Network configuration and enabling the web interface.]

. After this has been done, you can access the appliance's web interface via its IP address: 
From a computer connected to the network, enter the URL `\http://&lt;ipaddress&gt;/` into the web browser and log in with the password you assigned in the previous step when enabling the web interface.

. Download the {CMK} software package for the appliance as a CMA file from our link:https://checkmk.com/download[download page.] 
Then select [.guihint]#Check_MK Versions# in the appliance's web interface. 
In one step, upload the software package you have just downloaded to the appliance and install it -- as described in detail in xref:appliance_usage#manage_cmk[administering {CMK} software versions.]

. Create a site with the {CMK} software version installed, again via the appliance's web interface, this time using the [.guihint]#Site Management# button. 
There are also detailed instructions for this in xref:appliance_usage#site_management[administering monitoring sites.]
The site will start automatically following the creation.

. Now you can log on to the {CMK} site by calling up the URL `\http://&lt;ipaddress&gt;/&lt;siteid&gt;/` and using the access data you defined when creating the site.

. To enable things like name resolution and sending of emails, you must make further settings in the appliance's web interface.
You can read more about this in the
xref:appliance_usage#basic_settings_webconf[basic settings on the web interface] and the xref:appliance_usage#cma_webconf_system_settings[device settings.]
+
You do not need this to get started however.

{CMK} is now ready for you! Find out how to proceed in the xref:checkmk_getting_started#[Getting started with monitoring.]
