include::global_attr.adoc[]
= Quick start guide for {CMK} virt1
:revdate: draft
:title: Quick start guide for {CMK} virt1
:description: Short set-up guide for the virtual {CMK} appliance.
:no-toc:


. Download the {CMK} virt1 as an OVA file from our link:https://checkmk.com/download[download page] and import this file into your hypervisor (VirtualBox or VMware ESXi). 
You can find detailed instructions on how to do this in the article on xref:introduction_virt1#[installing the virtual appliance.]

. Launch the imported virtual machine and open the local console.

. During xref:appliance_usage#init_start[initialisation at the first start,] at the console you will be prompted to partition the data volume. Confirm.

. On completion of the launching procedure, the console status view will be displayed.

. So that the appliance can be used for monitoring, there are some settings that need to be made: 
Press the `F1` key and, using the configuration menu, configure the following settings as a minimum: xref:appliance_usage#network_access_config[Network configuration and enabling the web interface.]

. After this has been done, you can access the appliance's web interface via its IP address: 
From a computer connected to the network, enter the URL `\http://&lt;ipaddress&gt;/` into the web browser and log in with the password you assigned in the previous step when enabling the web interface.

. Download the {CMK} software package for the appliance as a CMA file from our link:https://checkmk.com/download[download page.] 
Then select [.guihint]#Check_MK versions# in the web interface of the appliance. In one step, upload the software package you have just downloaded to the appliance and install it -- as described in detail in xref:appliance_usage#manage_cmk[administering {CMK} software versions.]

. Create a site with the {CMK} software version installed, again via the appliance's web interface, this time using the [.guihint]#Site Management# button. 
There are also detailed instructions for this in xref:appliance_usage#site_management[administrating monitoring sites.]
The site will start automatically following the creation.

. Now you can log on to the {CMK} site: 
by calling up the URL `\http://&lt;ipaddress&gt;/&lt;siteid&gt;/` and using the access data you defined when creating the site.

. To enable things like name resolution and sending of emails, you must make further settings in the appliance's web interface. 
You can read more about this in the
xref:appliance_usage#basic_settings_webconf[basic settings on the web interface] and the xref:appliance_usage#cma_webconf_system_settings[device settings.]
+
You do not need this to get started however.

{CMK} is now ready for you! Find out how to proceed in the xref:checkmk_getting_started#[Getting started with monitoring.]
