= Checkmk-Editions
:revdate: draft
:title: The four editions of Checkmk

Before you can install Checkmk, you first have to consider the question of
_which_ Checkmk you want.  There are four different _editions_:

The (CRE) is free and 100% open source, and contains Nagios as its core.
It can comprehensively monitor complex environments. You can receive support
in our <a href="https://forum.checkmk.com/">forum</a> from the Checkmk community
and in the future also in a community portal.

The (CSE) (*CEE*) is aimed primarily at professional users, and beyond the
scope of the (RE) it offers a number of interesting features,
such as a very high-performance core that replaces Nagios, a reporting
function, a sophisticated system for the visualization of measured
values, a flexible agent deployment function, and much more.  For the
(SE) you can get professional support from us and from our
<a href="https://checkmk.de/find-a-partner.html">partners</a>.
You can find a list of its most important differences compared to
the (RE) on our  <a href="https://checkmk.de/editions.html">homepage</a>.

The (CFE) (*CFE*) is the right solution for you if you want to test the (SE)
first without obligation, or if you want to install Checkmk in small
operations with up to two sites with 10 monitored hosts each.  The (FE) contains all of
the features of the (SE) and is supplied at no cost.  Both the
(FE) and the (RE) can be upgraded directly and easily to the
(SE) at a later date.

The (CME) (*CME*) is the right edition for you if you are a managed
service provider offering services to your customers. 
It is a multi-client-capable extension of the (SE).

[CEE] Whenever we discuss functions in this manual that only apply to one
of the (EE) -- i.e. for the CEE, CFE or CME -- we mark this accordingly here.