// -*- coding: utf-8 -*-
include::global_attr.adoc[]

// This block is new
// start translation
////
[#setup]
== Einrichtung

[#login]
=== Login auf der virtuellen Maschine

Das Root-Login ist auf den AWS-/Azure-Images deaktiviert.
Stattdessen kommt der Nutzer `ubuntu` zum Einsatz, der über die Berechtigung verfügt, `sudo` mit beliebigen Kommandos ohne Passwortabfrage auszuführen.
Wenn Sie ein separates Schlüsselpaar für das Login auf der virtuellen Maschine erstellt haben, müssen Sie mit dem Parameter `-i` den Pfad zu dessen privaten Teil angeben.
Die IP-Adresse ist natürlich auf die anzupassen, unter der die VM von außen erreichbar ist:

[{shell}]
----
{c-user} ssh -i /path/to/id_file.priv ubuntu@192.0.2.123
----

Sie finden sich nun am Prompt des Nutzers `ubuntu` wieder.
Der exakte Prompt kann als Host-Name den beim Anlegen der VM angegebenen Host-Namen oder eine IP-Adresse enthalten.
Wir verwenden im Laufe des weiteren Artikels den Host-Namen `cloud`:

[{shell}]
----
{c-ubuntu}
----

[#create_site]
=== Instanz aufsetzen

Eine {CMK}-Instanz muss eindeutig benannt sein und sollte darüber hinaus eine leichte Identifikation ermöglichen.
Hier, wie in den meisten anderen Stellen dieses Handbuches, verwenden wir als Instanznamen `mysite`.

Das Erstellen einer Instanz geschieht mit dem Verwaltungswerkzeug von {CMK}, xref:omd_basics#[`omd`].
Vorinstalliert ist immer die neueste Version von {CMK}:

[{shell}]
----
{c-ubuntu} sudo omd create mysite
Adding /opt/omd/sites/mysite/tmp to /etc/fstab.
Creating temporary filesystem /omd/sites/mysite/tmp...[green]#OK#
Updating core configuration...
Generating configuration for core (type cmc)...

Starting full compilation for all hosts Creating global helper config...[green]#OK#
 Creating cmc protobuf configuration...[green]#OK#
Executing post-create script "01_create-sample-config.py"...[green]#OK#
Restarting Apache...[green]#OK#
Created new site mysite with version 2.2.0p1.cce.

  The site can be started with omd start mysite.
  The default web UI is available at \http://cloud/mysite/

  The admin user for the web applications is cmkadmin with password: UbWeec9QuazIf
  For command line administration of the site, log in with 'omd su mysite'.
  After logging in, you can change the password for cmkadmin with 'cmk-passwd cmkadmin'.
----

Starten Sie jetzt die neu angelegte Instanz mit

[{shell}]
----
{c-ubuntu} sudo omd start mysite
----

Die in der obigen Kommandoausgabe gezeigte URL (`\http://cloud/mysite`) verwendet den intern genutzten Host-Namen Ihrer AWS- oder Azure-VM.
Da dieser in der Regel nicht extern aufgelöst wird, ist die URL von eingeschränktem Nutzen.
In der Regel werden Sie zunächst über die IP-Adresse oder einen im eigenen DNS-Server hinterlegten Host-Namen zugreifen.

[#ssl_certs]
=== Zertifikate hinterlegen

Damit der System-Apache überhaupt am HTTPS-Port 443 lauschen kann, benötigt er gültige Zertifikate.
Beim ersten Start der virtuellen Maschine werden hierfür die selbst signierten link:https://packages.ubuntu.com/jammy/all/ssl-cert/filelist[_Snakeoil Inc._ Zertifikate^] generiert.
Wir raten dringend zum baldigen Austausch gegen xref:omd_https#[eigene Zertifikate], bei denen die komplette Zertifikatskette leicht verifiziert werden kann.

Die Apache-Konfiguration hält sich dabei eng an die Ubuntu-Standards, geänderte Zertifikatspfade müssen in der Datei `/etc/apache2/sites-enabled/000-default.conf` eingetragen werden.

[#mta]
=== E-Mail-System einrichten

Da die Wege der xref:intro_notifications#[Benachrichtigungen] in {CMK} vielfältig sind und variieren können, ist kein E-Mail-System vorbereitet.

[#no_mta]
==== {CMK} ohne E-Mail-System

Auch der vollständige Verzicht auf ein lokales E-Mail-System ist möglich, falls Sie ausschließlich die xref:notifications#syncsmtp[nachvollziehbare Zustellung von HTML-E-Mails per SMTP] aktivieren wollen oder auf Benachrichtigungs-Plugins für Plattformen wie xref:notifications_teams#[Microsoft Teams] oder xref:notifications_slack#[Slack] setzen.

Beachten Sie aber, dass in dieser Konfiguration keine xref:notifications#bulk[Sammelbenachrichtigung] möglich ist.

[#simple_mta]
==== Relay-only oder vollwertiger Mail Transport Agent (MTA)

Im Regelfall werden Sie wegen der höheren Flexibilität ein E-Mail-System einrichten wollen.
Für kleinere Umgebungen hat sich der _relay-only MTA_ link:https://manpages.ubuntu.com/manpages/jammy/man7/nullmailer.7.html[Nullmailer^] bewährt.

Für größere Installationen, bei denen unvorhergesehene Ereignisse auch einige Hundert E-Mails zur Folge haben können, empfehlen wir die Installation eines vollwertigen MTAs wie Postfix.

[#add_hosts]
=== Host(s) ins Monitoring aufnehmen

[#pull]
==== Localhost im Pull-Modus

In den allermeisten Fällen dürfte der {CMK}-Server selbst der erste Host sein, den Sie xref:intro_setup_monitor#linux[ins Monitoring aufnehmen.]
Dazu müssen Sie den Linux-Agenten auf dem {CMK}-Server installieren.
Der Agent kommuniziert mit dem Server im xref:glossar#pull_mode[Pull-Modus].
Wenn Ihnen der Download des Agentenpaketes über die Weboberfläche mit anschließendem Transfer per `scp` zu umständlich erscheint, können Sie den Agenten in seiner Standardkonfiguration ("Vanilla") direkt aus dem Dateisystem installieren:

[{shell}]
----
{c-ubuntu} sudo apt install $(sudo find /opt/omd/versions/ -name 'check-mk-agent_*.deb' | tail -n1)
----

Unmittelbar nach der Installation lauscht der {CMK}-Agent im unverschlüsselten Legacy-Pull-Modus auf Port 6556.
Führen Sie daher zeitnah xref:intro_setup_monitor#register[die Registrierung] durch, damit keine unbefugten Dritten auf die Agentenausgabe zugreifen können:

[{shell}]
----
{c-ubuntu} sudo cmk-agent-ctl register --hostname localhost --server localhost --site mysite --user cmkadmin
----

[#push]
==== Hosts im Push-Modus

Sollen Hosts überwacht werden, die hinter einer Firewall nicht direkt vom {CMK}-Server erreicht werden können, ist oft der xref:glossar#push_mode[Push-Modus] der bevorzugte Kommunikationsweg.
Sie können den Push-Modus in den Eigenschaften des Hosts im Abschnitt xref:hosts_setup#monitoring_agents[Monitoring agents] mit der Option [.guihint]#Checkmk agent connection mode# auswählen. 
Alternativ können Sie den Push-Modus auch mit vorkonfigurierten Agentenpaketen für die xref:hosts_autoregister#[Autoregistrierung] kombinieren und so den Komfort weiter erhöhen.

[#update]
=== {CMK} aktualisieren

Prüfen Sie die link:https://checkmk.com/de/download?method=cmk&edition=cce&version=2.2.0&platform=ubuntu&os=jammy&type=cmk[Download-Seite^] regelmäßig auf Updates und laden sie das aktualisierte Paket mit dem dort angezeigten `wget` Kommando herunter.

Die xref:update#[Installation eines Updates] erfolgt in zwei Schritten, was darin begründet liegt, dass mit `omd` verschiedene Instanzen mit verschiedenen Versionen von {CMK} auf einem Server laufen können.

[#install_new]
==== Neue {CMK}-Version installieren und Instanz aktualisieren

Der erste Schritt ist die Installation des Paketes, im folgenden Beispiel die Version {v22}p2:

[{shell}]
----
{c-ubuntu} sudo apt install ./check-mk-cloud-2.2.0p2_0.jammy_amd64.deb
----

Der nächste Schritt ist das Update Ihrer Instanz(en):

[{shell}]
----
{c-ubuntu} sudo omd stop mysite
{c-ubuntu} sudo omd update mysite
{c-ubuntu} sudo omd start mysite
----

[#remove_old]
==== Nicht mehr benötigte Pakete entfernen

Falls Sie mehrere Instanzen auf dem Server nutzen (beispielsweise eine produktiv genutzte und eine für den Test von Erweiterungen), stellen Sie sicher, dass alle aktualisiert sind:

[{shell}]
----
{c-ubuntu} omd sites
SITE         VERSION       COMMENTS
mysite       2.2.0p2.cce   default version
mytestsite   2.2.0p2.cce   default version
----

Nicht mehr genutzte {CMK}-Versionen können Sie dann über das Ubuntu-Paketmanagement deinstallieren:

[{shell}]
----
{c-ubuntu} sudo apt purge check-mk-cloud-2.2.0p1
----
////
// end translation