include::global_attr.adoc[]
= Installation on Debian and Ubuntu
:revdate: 2020-06-23
:title: Details for an installation on Debian and Ubuntu
:description: Each distribution has its own special features which need to be considered during a software installation. Here we describe the requirements for Debian and Ubuntu in detail.

[{related-hint}]
{related-title}
--
* link:intro.html[A beginner’s guide to (CMK)]
* link:checkmk_getting_started.html[Getting Started with Monitoring]
* link:introduction_virt1.html[Installation of a virtual appliance]
* link:install_packages.html[Basic information on the installation of (CMK)]
--


== Download the appropriate packages

If you have a subscription, on your link:download/[subscription downloads page]
you will find a suitable RPM or DEB package for your distribution
for every available link:cmk_versionen.html[{CMK}-Version].  For a free test or
small installations of {CMK} you can use our link:download.php[free Editions].
These don't need in consequence any subscription. You are still
able to do an link:update.html#updatedemo[upgrade] any time to go to on of the {CEE}
on a later on.

Please consider when selecting a package:

* Firstly, choose a version of {CMK}, a distribution and the version of this distribution.
* We recommend the _latest stable version_. If you need an older version anyway, you can find these in link:download-archive.php[download archive] at the of the page.
* The name and version of your distribution must be strictly identical.
* Choose one of the Editions. If you're unsure, you can get an overview to the differences of the link:editions.html[editions].

After you downloaded the package to your machine, you need to copy the
file to the target Linux system where {CMK} needs to be installed. You can
do that for example with the program _WinSCP_ or -- if you are able
to use ssh connections -- with the command line tool `scp`.

To be able to copy files to your future {CMK}-server using `scp` the
package openssh-server needs to be installed. If that is not the case already,
you can set it up using the following command:

[{shell}]
----
{c-root} apt-get install openssh-server
----

Once this is done you can copy for example the package of the {CRE} for
_Ubuntu 20.04 (focal fossa)_ using the command below:

[{shell}]
----
{c-root} scp check-mk-raw-1.6.0p12_0.focal_amd64.deb root@mymonitoring.mydomain.org:
----


[#signed]
== Signed-package installation

All packages are signed using link:https://gnupg.org[GnuPG]. Through the
use of this signature, on the one hand it can be verified whether the package
really is from {CMK}, and on the other hand it can be verified that the package
is complete.

Depending on which optional packages were installed during the setup of your
distribution, you will have to install dpkg-sig including all its dependencies.
To do so, just enter the following command:

[{shell}]
----
{c-root} apt-get install dpkg-sig
----

So that these signed packages can be installed in the usual way, one time only
you will need to import our public key so that the signature will be trusted.
First, load the key directly from our website:

[{shell}]
----
{c-root} wget https://checkmk.com/support/Check_MK-pubkey.gpg
----

Alternatively, the key can also be obtained from
link:http://keys.gnupg.net[gnupg.net]:

[{shell}]
----
{c-root} gpg --keyserver keys.gnupg.net --recv-keys 434DAC48C4503261
{c-root} gpg --armor --export 434DAC48C4503261 > Check_MK-pubkey.gpg
----

Then import the key from the list of trusted signatures. Under Debian and Ubuntu the
following command is required:

[{shell}]
----
{c-root} apt-key add Check_MK-pubkey.gpg
----

Once the key has been added, you can verify the {CMK}-package using the
following command:

[{shell}]
----
{c-root} dpkg-sig --verify check-mk-enterprise-1.6.0p13_0.buster_amd64.deb
----

Next install the package `gdebi-core`. This tool ensures that not only
the package with the {CMK} Monitoring System, but also all of its dependencies
will be correctly installed:

[{shell}]
----
{c-root} apt-get install gdebi-core
----

Afterwards install the {CMK}-package using `gdebi`:

[{shell}]
----
{c-root} gdebi check-mk-enterprise-1.6.0p13_0.buster_amd64.deb
----


== Final test

After the successful installation of {CMK}, and all dependencies, you will
have access to the `omd` command. With this command you are able
to create and manage link:omd_basics.html[monitoring sites]. You can request the
installed version to verify your installation:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version 1.6.0p13.cee
----
