// -*- coding: utf-8 -*-
// IGNORE % p2 pre
include::global_attr.adoc[]
= Installation from AWS or Azure Marketplace
:revdate: draft
:title: Installation from AWS or Azure Marketplace
:description: Marketplace images that include {CMK} are available from 2.2.0 on.

{related-start}
xref:intro_setup#[Setting up {CMK}]
xref:install_packages#[Basic information on the installation of {CMK}]
xref:update#[Updates and Upgrades]
{related-end}


[#welcome]
== Using {CMK} on  AWS or Azure

Official pre-configured images from the AWS or Azure Marketplace are available for {CMK} Cloud Edition from 2.2.0 on.
We are aware of third party images on these marketplaces and trying to get them removed.
Please use the branch selector if you want to switch to the article describing the setup.

If you want to run earlier versions of {CMK} on such cloud infrastructure, we recommend using one of the official Ubuntu images (link:https://aws.amazon.com/marketplace/pp/prodview-o5bowpuwmx3ng?sr=0-10&ref_=beagle&applicationId=AWSMPContessa[Amazon^] and link:https://learn.microsoft.com/en-us/azure/virtual-machines/linux/quick-create-portal?tabs=ubuntu[Azure^]) and perform a xref:install_packages_debian#[regular installation from a DEB package] on it.
