// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Installation on Debian and Ubuntu
:revdate: 2022-05-17
:title: Installation on Debian and Ubuntu
:description: Learn how to install {CMK} on the Linux distribution of Debian and of Ubuntu.

{related-start}
xref:intro_welcome#[Beginner's guide]
xref:checkmk_getting_started#[Getting started with monitoring]
xref:introduction_virt1#[Installation of a virtual appliance]
xref:install_packages#[Basic information on the installation of {CMK}]
{related-end}


== Download the appropriate packages

If you have a subscription, you will find in the link:https://customer.checkmk.com/[customer portal^] a suitable RPM or DEB package for your distribution for every available xref:cmk_versions#[{CMK} version].
For a free test or small installations of {CMK} you can use our link:https://checkmk.com/de/download[free editions^].
These don't need in consequence any subscription.
You are still able to do an xref:update#updatedemo[upgrade] any time to one of the {CEE}.

Consider when selecting a package:

* Choose one of the editions.
If you're unsure, you can get an overview to the differences of the link:https://checkmk.com/product/editions[editions].
* Choose the {CMK} version, the distribution and finally the version of the selected distribution.
* We recommend the _latest stable {CMK} version_.
If you need an older version anyway, you can find these in the link:https://checkmk.com/download/archive[download archive].
* The name and version of your distribution must be strictly identical.

After you downloaded the package to your machine, you need to copy the file to the target Linux system where {CMK} needs to be installed.
You can do that for example with the programm _WinSCP_ or -- if you are able to use SSH connections -- with the commandline tool `scp`.

To be able to copy files to your future {CMK} server using `scp` the package `openssh-server` needs to be installed.
If that is not the case already, you can install it using the following command:

[{shell}]
----
{c-root} apt install openssh-server
----

Once this is done you can copy for example the package of the {CRE} for Ubuntu 20.04 _Focal Fossa_ using the command below:

[{shell}]
----
{c-root} scp check-mk-raw-2.1.0p1_0.focal_amd64.deb root@mymonitoring.mydomain.org:
----


[#signed]
== Signed-package installation

All packages are signed using link:https://gnupg.org[GnuPG^].
Through the use of this signature, on the one hand it can be verified whether the package really is from {CMK}, and on the other hand it can be verified that the package is complete.

Depending on which optional packages were installed during the setup of your distribution, you will have to install dpkg-sig` including all its dependencies.
To do so, just enter the following command:

[{shell}]
----
{c-root} apt install dpkg-sig
----

So that these signed packages can be installed in the usual way, one time only you will need to import our public key so that the signature will be trusted.
First, load the key directly from our website:

[{shell}]
----
{c-root} wget \https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

*Alternatively*, the key can also be obtained from link:https://keys.openpgp.org[keys.openpgp.org1^]:

[{shell}]
----
{c-root} gpg --keyserver keys.openpgp.org --recv-keys 434DAC48C4503261
{c-root} gpg --armor --export 434DAC48C4503261 > Check_MK-pubkey.gpg
----

Then import the key to the list of trusted signatures.
Under Debian and Ubuntu the following command is required:

[{shell}]
----
{c-root} gpg --import Check_MK-pubkey.gpg
----

Once the key has been added, you can verify the {CMK} package using the following command:

[{shell}]
----
{c-root} dpkg-sig --verify check-mk-raw-2.1.0p1_0.focal_amd64.deb
----

Afterwards you can install the {CMK} package using following command.
Be sure to pass the full path to the DEB file after `apt install`:

[{shell}]
----
{c-root} apt install /tmp/check-mk-raw-2.1.0p1_0.focal_amd64.deb
----


== Final test

After the successful installation of {CMK}, and all dependencies, you will have access to the `omd` command.
With this command you are able to create and manage xref:omd_basics#[monitoring sites].
You can request the installed version to verify your installation:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version 2.1.0p1.cre
----
