// -*- coding: utf-8 -*-
// IGNORE % p2 pre
include::global_attr.adoc[]
= Installation from AWS Marketplace
:revdate: 2023-07-18
:title: Installation from AWS Marketplace
:description: {CMK} provides an (almost) turnkey image in the AWS Marketplace. In this article, you will learn how to complete the setup.

{related-start}
xref:intro_setup#[Setting up {CMK}]
xref:install_packages#[Basic information on the installation of {CMK}]
xref:update#[Updates and Upgrades]
{related-end}


[#welcome]
== Welcome to {CMK} as AMI

Whether you are a long-time user of {CMK} or have only recently found us with the availability of ready-made images in the Amazon Web Services (AWS) Marketplace, in this article you will find all of the resources required to configure the prepared _Amazon Machine Image (AMI)_ into a monitoring suitable for your needs.

If you are new to {CMK}, we recommend reading our xref:intro_setup#[Beginner's Guide] in preparation.
Preconfigured VM images may shortcut many tasks during an installation, but some knowledge of fundamental concepts, such as xref:glossar#site[sites], will help during the setup process.


[#basics]
=== The basics

If you are an AWS user, you have always had the option of adding {CMK} to an link:https://aws.amazon.com/marketplace/pp/prodview-o5bowpuwmx3ng?sr=0-10&ref_=beagle&applicationId=AWSMPContessa[existing Ubuntu image^] available in the Marketplace, in order to set up a 'monitoring in the cloud'.
{CMK} {v22} takes this a step further and provides link:https://aws.amazon.com/marketplace/pp/prodview-gddkal2hfn7yo[a pre-installed image^] based on Ubuntu 22.04 _(Jammy Jellyfish)_ with all of the required dependencies already included.
Only the xref:cce#[{CE}] is used here.
This will be in a 30-day 'Trial' license state with no restrictions when the first site is set up.
After the trial period expires, {CMK} can continue to be used as a single site with up to 750 monitored services without requiring a subscription.
If more services need to be monitored, or more sites are required, you will need a xref:license#license_cce[license key].

In general, the setup is a bit more involved than, for example, xref:introduction_docker#[Docker image], after all, the image provided must cover various deployment scenarios:

* A _single site setup_ on a server at various scales
* Central site in a distributed monitoring
* Remote site in a distributed monitoring
* Mixed operations consisting of a production site and site(s) for running tests on a host

For this reason, the AM image does not include a ready-to-run site, an email or a firewall configuration.

In this article we will guide you through the complete setup.
Where additional background information would be useful, we link to detailed articles in our User Guide.


[#preparation]
== Preparation

As well as the dimensioning of RAM, processor and virtual hard drives, you should also think about the location for the storage of backups.
{CMK} natively supports Amazon's object stores, but backups can also be stored in file system paths, which allows backups to SMB or WebDAV mounts or regular transfers via `rsync`.


[#ssh_keys]
=== Creating SSH keys

AWS currently supports keys in the link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/create-key-pairs.html[ED25519 and RSA formats^]. 
You can create an ED25519 key pair for the first login to the virtual machine, whose _public key_ you upload when you create the VM.
Alternatively, you can let AWS create the key pair.
In this case, do not forget to save the private key immediately after creation, because it will next be automatically deleted for security reasons.


[#ports]
=== Determining the required ports

In a {CMK} configuration with a single site setup, in which hosts also send data to the {CMK} site in the push mode, the following {CMK} server ports must be accessible:

* From the hosts in monitoring: Port 80/443 (HTTP/HTTPS, during agent registration) and Port 8000 (the Agent Receiver, permanently).
* For management via the browser and the REST API: Port 80/443 (HTTP/HTTPS)

The sharing of these ports is predefined in our [.guihint]#Standard Security Groups#.
For best possible security, you should further restrict access to the IP address ranges you actually need.

Consult our xref:ports#[overview of all ports used] if you want to set up a distributed monitoring or, for example, make status queries via the xref:glossar#livestatus[Livestatus] interface.


[#book_vm]
=== Booking an image in the Marketplace

The following VM instances represent a recommendation for the dimensioning of the number of services to be monitored.

[cols="22,22,22,~",options="header"]
|===
|Type |CPU cores |RAM (GB) |{CMK} services
|`c6a.xlarge` |4 |8 |12 000
|`c6a.2xlarge` |8 |16 |30 000
|`c6a.4xlarge`  |16 |32 |60 000
|===

The basis for such calculations of dimensioning is approximately 15{nbsp}% of services by xref:glossar#special_agent[special agents] and xref:glossar#active_check[active checks], as well as 25 or more services per regular host delivered via an agent in xref:glossar#push_mode[push mode].
Under certain circumstances, significantly more services are possible in a purely synthetic monitoring (in which data is primarily delivered by special agents).
When using agents in xref:glossar#pull_mode[pull mode], the specified number of services may only be achievable through consistent optimization.

The dimensioning of the hard disk space is based on experience of typical Windows and Linux server environments.
If there are many services producing a large volume of metrics, a larger amount of storage space may be required.


[#book_backup]
=== Booking backup storage

Because of the favorable traffic costs, we advise the use of an _AWS S3 Bucket_.
For the calculation of the required storage space, read the xref:graphing#rrds[notes on the RRD data format].
As a rule of thumb for calculating a full backup, _Round Robin Databases_ will have reached just over a third of their maximum capacity after 10 days.
This means that after this time it makes sense to again review the size of the backup storage that has been booked.


// Common part 
include::include_common_aws_azure.asciidoc[]


[#aftermath]
== Post-processing

[#backup]
=== Configuring the backups

{CMK} provides a convenient xref:backup#[backup function], which is configured under [.guihint]#Setup > Maintenance > Backups > Backup targets#.
With [.guihint]#Add backup target# you add a storage location.
Here it is advisable to select a [.guihint]#AWS S3 bucket# as the [.guihint]#Destination# because of its fast and cheap data transfer. 

In addition to the credentials, you must also specify a folder path where the archive is temporarily stored before it is copied to the object store.
This can be under `/tmp`.
If your AWS instance provides a volatile _(ephemeral)_ drive, you can mount this and use it as a cache. 


[#restore]
==== Procedure for a restore

The xref:backup#backup_restore[restore of a backup] must always be done on exactly the same version of {CMK} as was used to create it.
If a backup is to be used to move to another type of virtual machine, to another cloud provider or from an _on premise installation_ to the cloud (or vice versa), always first upgrade to the highest available patch level of {CMK} _before_ the final backup and migration.

The following points apply to the restore of a backup:

. On the target system, install exactly the version of {CMK} that was used to create the backup.
. Create a monitoring site with `omd create` that uses the same site name as the source system.
. Specify the backup destination and upload the backup key.
. Perform the actual restore.


[#monitoring_azure]
== Monitoring AWS

{CMK} not only provides availability as an AMI, but also a comprehensive xref:monitoring_aws#[monitoring of your AWS infrastructure].
Even if {CMK} should be your first or only AWS project, it is already worth monitoring the performance of the site, the state of the backup buckets and the level of costs incurred.
