include::global_attr.adoc[]
= Installation on Red Hat and CentOS
:revdate: 2020-06-23
:title: Details for an installation on Red Hat and CentOS
:description: Each distribution has its own special features which need to be considered during a software installation. Here we describe the requirements for Red Hat and CentOS in detail.

[TIP]
.Related Articles:
====
link:introduction.html[]

link:check_mk_getting_started.html[]

link:introduction_virt1.html[]

link:install_packages.html[]

====



== Setting up the package sources

{CMK} requires a number of software packages from your Linux distribution.
Third-party software is not required. In order that all necessary packages can
be subsequently installed, a correct configuration of the software sources is
necessary. With Red Hat and CENTOS the _EPEL (Extra Packages for Enterprise
Linux)_ repository must be set up as a package source. You can do this with
the help of an RPM package, which can be installed with the `yum`
command:

[cols=10,options="header"]
|===
|Version
|Package link


|`6`
|`https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm`


|`7`
|`https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`


|`8`
|`https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`

|===


Here is an example of an installation on CentOS 8:

{c-start}
{RP}yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
{c-end}

In order to be able to use EPEL on RedHat and CentOS, the package sources for
optional RPMs are required if these haven’t already been installed during the
operating system installation. Without these sources the
`freeradius-utils`, `graphviz-gd`, and `php-mbstring`
package will be missing. As of version 8.x it will suffice to activate the
so-called PowerTools with the help of Dandified YUM in CentOS or the
`subscription-manager` in RHEL respectively. This can be done, eg., with
the following commands:

Red Hat/CentOS 6.X:

{c-start}
{RP}yum-config-manager --enable rhel-6-server-optional-rpms
{RP}subscription-manager repos --enable rhel-6-server-optional-rpms
{c-end}

Red Hat/CentOS 7.X:

{c-start}
{RP}yum-config-manager --enable rhel-7-server-optional-rpms
{RP}yum-config-manager --enable rhel-7-server-extras-rpms
{RP}subscription-manager repos --enable rhel-7-server-optional-rpms
{RP}subscription-manager repos --enable rhel-7-server-extras-rpms
{c-end}

CentOS 8.X:

{c-start}
{RP}dnf config-manager --set-enabled PowerTools
{c-end}

RedHat 8.X:

{c-start}
{RP}subscription-manager repos --enable "codeready-builder-for-rhel-8-x86_64-rpms"
{c-end}


//You can get a list of all available package repositories with:
//
//C+:
//RP:subscription-manager repos --list
//C-:


== Setup SELinux and Firewall

Since Red Hat and thus CentOS also deliver SELinux and a local firewall by
default, adjustments may have to be made here. As the first step you will need
to allow your web server to access the network interfaces:

{c-start}
{RP}setsebool -P httpd_can_network_connect 1
{c-end}

Secondly, you release the web server and activate the change:

{c-start}
{RP}firewall-cmd --zone=public --add-service=http --permanent
success
{RP}firewall-cmd --reload
success
{c-end}


== Download the appropriate packages

If you have a subscription, on your <a href="download/">subscription downloads
page</a> you will find a suitable RPM or DEB package for your distribution
for every available link:cmk_versionen.html[{CMK}-Version].  For a free test or
small installtions of {CMK} you can use our <a href="download.php">free
Editions</a>. These don't need in consequence any subscription. You are still
able to do an link:update.html#updatedemo[upgrade] any time to go to on of the {CEE}
on a later on.

Please consider when selecting a package:

* Firstly, choose a {CMK}-version, a distribution and a the version of this distribution.
* We recommend the _latest stable version_. If you need an older version anyway, you can find these in <a href="download-archive.php">download archive</a> at the of the page.
* The name and version of your distribution must be strictly identical.
* Choose one of the Editions. If you're unsure, you can get an overview to the differences of the <a href="editions.html">editions</a>.

After you downloaded the package to your machine, you need to copy the
file to the target Linux system where {CMK} needs to be installed. You can
do that for example with the programm _WinSCP_ or -- if you are able
to use ssh connections -- with the commandline tool `scp`. In the
following example for the {CRE} and _CentOS 8.x_:

{c-start}
{RP}scp check-mk-raw-1.6.0p12-el8-38.x86_64.rpm root@mymonitoring.mydomain.org:
{c-end}


== Signed-package installation#signed

All packages are signed using
<a href="https://gnupg.org">GnuPG</a>. Through the use of this signature, on the
one hand it can be verified whether the package really is from {CMK}, and on the
other hand it can be verified that the package is complete.

So that these signed packages can be installed in the usual way, one time only
you will need to import our public key so that the signature will be trusted.
First, load the key directly from our website:

{c-start}
{RP}wget https://checkmk.com/support/Check_MK-pubkey.gpg
{c-end}

Alternatively, the key can also be obtained from
<a href="http://keys.gnupg.net">gnupg.net</a>:

{c-start}
{RP}gpg --keyserver keys.gnupg.net --recv-keys 434DAC48C4503261
{RP}gpg --armor --export 434DAC48C4503261 > Check_MK-pubkey.gpg
{c-end}

Then import the key to the list of trusted signatures. On Red Hat and CentOS
this is yet another job for `rpm`:

{c-start}
{RP}rpm --import Check_MK-pubkey.gpg
{c-end}

Once the key has been imported, you can verify the package and install it the
usual way with `yum install` afterwards:

{c-start}
{RP}rpm -K check-mk-enterprise-1.6.0p12-el8-38.x86_64.rpm
check-mk-enterprise-1.6.0p12-el8-38.x86_64.rpm: digests signatures OK
{RP}yum install check-mk-enterprise-1.6.0p12-el8-38.x86_64.rpm
{c-end}


== Final test

After the successful installation of {CMK}, and all dependencies, you will
have access to the `omd` command. With this command you are able
to create and manage link:omd_basics.html[monitoring sites]. You can request the
installed version to verify your installation:

{c-start}
{RP}omd version
OMD - Open Monitoring Distribution Version 1.6.0p12.cee
{c-end}
