= Installation on SLES
:revdate: 2020-06-23
:title: Details for an installation on SUSE Linux Enterprise Server
:description: Each distribution has its own special features which need to be considered during a software installation. Here we describe the requirements for SLES in detail.


== Setting up the package sources

(CMK) requires a number of software packages from your Linux distribution.
Third-party software is not required. In order that all necessary packages can
be subsequently installed, a correct configuration of the software sources is
necessary. The setup procedure varies depending on the version of SLES being
used.


[#sles11]
=== SLES 11

Unfortunately SUSE has some of its important packages on a separate DVD. This is
labelled _SUSE Linux Enterprise SDK_. Install this with YaST as a second
package source. Please don't confuse the SDK with DVD 2 of the normal
installation DVD. This last contains the sofware's source codes and is not
required. If you have a valid SLES subscription you can download the ISO image
of the SDK directly from the <a href="https://download.suse.com/">SUSE</a>
website.


[#sles12]
=== SLES 12

With SLES 12 some software components, eg. PHP, which is required by OMD, are
stored in so-called Modules. In order to be able to access SLES 12's PHP
packages, the following steps need to be taken:

* <a href="https://documentation.suse.com/sles/12-SP4/html/SLES-all/cha-planning.html#sec-planning-registering">Register SLES 12</a>
* <a href="https://documentation.suse.com/sles/12-SP4/html/SLES-all/cha-add-ons.html#sec-add-ons-installation">Install the 'Web and Scripting Module'</a>


[#sles15]
=== SLES 15

With SLES 15, in addition to the
[install_packages_sles#sles12|Web and Scripting Module], you also have to install
the _Development Tools Module_ and the _SUSE Package Hub 15_.

* <a href="https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-register-sle.html">Register SLES 15 and Manage Modules</a>


== Download the appropriate packages

If you have a subscription, on your <a href="download/">subscription downloads
page</a> you will find a suitable RPM or DEB package for your distribution
for every available [cmk_versionen|Checkmk-Version].  For a free test or
small installtions of Checkmk you can use our <a href="download.php">free
Editions</a>. these don't need in consequence any subscription. You are still
able to do an [update#updatedemo|upgrade] any time to go to on of the (CEE)
on a later on.

Please consider when selecting a package:

* Firstly, choose a Checkmk-version, a distribution and a the version of this distribution.
* We recommend the _latest stable version_. If you need an older version anyway, you can find these in <a href="download-archive.php">download archive</a> at the of the page.
* The name and version of your distribution must be strictly identical.
* Choose one of the Editions. If you're unsure, you can get an overview to the differences of the <a href="editions.html">editions</a>.

After you downloaded the package to your machine, you need to copy the
file to the target Linux system where Checkmk needs to be installed. You can
do that for example with the programm _WinSCP_ or -- if you are able
to use ssh connections -- with the commandline tool `scp`. In the
following example for the (CRE) and _SLES 15_:

[source,bash]
----
root@linux:~$ scp check-mk-raw-1.6.0p12-sles15-38.x86_64.rpm root@mymonitoring.mydomain.org:
----


[#signed]
== Signed-package installation

All packages are signed using
<a href="https://gnupg.org">GnuPG</a>.
Through the use of this signature, on the one hand it can be verified whether the package
really is from Checkmk, and on the other hand it can be verified that the package is complete.

So that these signed packages can be installed in the usual way, one time only you will
need to import our public key so that the signature will be trusted.
First, load the key directly from our website:

[source,bash]
----
root@linux:~$ wget https://checkmk.com/support/Check_MK-pubkey.gpg
----

Alternatively, the key can also be obtained from
<a href="http://keys.gnupg.net">gnupg.net</a>:

[source,bash]
----
root@linux:~$ gpg --keyserver keys.gnupg.net --recv-keys 434DAC48C4503261
root@linux:~$ gpg --armor --export 434DAC48C4503261 > Check_MK-pubkey.gpg
----

For RPM-based systems (RHEL, CentOS, SLES) the `rpm` tool is required:

[source,bash]
----
root@linux:~$ rpm --import Check_MK-pubkey.gpg
----

Once the key has been imported, you can verify the package can install it the
usual way using `zypper install` afterwards:

[source,bash]
----
root@linux:~$ rpm -K check-mk-enterprise-1.6.0p12-sles15-38.x86_64.rpm
check-mk-enterprise-1.6.0p12-sles15-38.x86_64.rpm: digests signatures OK
root@linux:~$ zypper install check-mk-enterprise-1.6.0p12-sles15-38.x86_64.rpm
----

###*Important*: When using one of Checkmk’s signed packages,
###the `--no-gpg-checks` option should of course be omitted.
###Before an installation the signature can be verified as follows:


== Final test

After the successful installation of Checkmk, and all dependencies, you will
have access to the `omd` command. With this command you are able
to create and manage [omd_basics|monitoring sites]. You can request the
installed version to verify your installation:

[source,bash]
----
root@linux:~$ omd version
OMD - Open Monitoring Distribution Version 1.6.0p12.cee
----