include::global_attr.adoc[]
= Welcome to {CMK}
:revdate: 2022-04-06
:title: Welcome to {CMK}
:description: Here, the Beginner's guide is briefly presented, which compactly leads through the first steps to optimally set up IT monitoring with {CMK}.
:no-toc:

{related-start}
xref:intro_setup#[Setting up {CMK}]
{related-end}

*Dear readers,*

we are pleased that you have found your way to {CMK} -- and have visited the {CMK} User guide while doing so.

The problem-free operation of IT systems has always been a challenge.
Both the complexity of hardware and software and the demands of users continue to increase -- whether they are working with real hardware or with cloud solutions.
This is why detailed and comprehensive IT monitoring plays such a central role nowadays.

The requirements that users place on their monitoring are of course as complex as the IT world itself.
{CMK} was developed from the outset for large and heterogeneous IT landscapes, which is why it offers such a wealth of functions and options to meet all of the problems that result from this in practice.
For this reason, the comprehensiveness of {CMK} can be overwhelming for a beginner at first.

To make sure you can nevertheless start your first {CMK} monitoring quickly and more easily, we have divided the {CMK} User guide into two parts for you:

. A Beginner's guide, the introduction to which you are reading now, and which will guide you in the following chapters as you get to know {CMK};
. An introduction to the main tasks involved in using {CMK} and a comprehensive reference section for experts.

The Beginner's guide gives you a compact step-by-step introduction to {CMK} and it is structured in such a way that you can read it quickly from beginning to end and participate right away.

Therefore it is short and concise and does not dwell on unnecessary details.
By the end of the Beginner's guide you will have a functional {CMK} system.

In the xref:intro_bestpractise#[last chapter] we will show you some very useful tips and tricks from our experienced consultants, which have proven themselves in various {CMK} installations.

Of course, the Beginner's guide still leaves many questions unanswered.
These are answered in the rest of the User guide.
There you will find all of the background information and details on topics that we can only touch on in the Beginner's guide, so that you can delve deeper -- on your way from beginner to {CMK} expert.

xref:intro_setup#[We will continue with the setup of {CMK}]
