= Connecting Nagstamon to Multisite
:description: Nagstamon is a Nagios status monitor used on desktops. It show up as tray icon in the system tray or as floating statusbar.
:revdate: outdated
VS:1.1.9i8
== General Information

<a href="http://nagstamon.ifw-dresden.de/">Nagstamon</a> is a Nagios status
monitor used on desktops. It show up as tray icon in the system tray or as
floating statusbar.

Nagstamon uses the classic Nagios CGIs to fetch the status information
about Nagios hosts and services. This leads to a lot of load on the Nagios
system when several clients are running Nagstamon at the same time.

To reduce the load on the Nagios system Multisite provides a new JSON
based web service since version 1.1.9i8. This web service can be used by
clients like Nagstamon to fetch Nagios status information using a fast
and lightweight protocol.

To use the web service there is a server module included in Nagstamon since
0.9.5. It can connect directly to the Multisite web service to fetch status
information from one or multiple sites.

The web service in multisite is implemented as regular view which can be
shown with JSON output instead of regular HTML output. Mutlisite comes with
two default views named `nagstamon_hosts` and `nagstamon_svc`
which are used when connecting Nagstamon to Multisite.

== Configuring Nagstamon

To connect Nagstamon to multisite right click on the Nagstamon icon, open
the `settings` dialog and click on `New server...`.

<div align=center style="margin:10px;">
<img src=bilder/nagstamon-server.png alt="Nagstamon Checkmk Multisite" />
</div>

In the following dialog select `Checkmk Multisite` as server type,
insert a server name of your choice.
Then add the URL you use to open Multisite in your browser to as value for
the server url parameter. For example if you use
`http://192.168.0.70/check_mk/` to access Multisite just put
`http://192.168.0.70/check_mk/` into the input field.

The server cgi url parameter is not used by the backend. You can leave the
value at it's default value.

At last you need to enter a valid username of your choice and if you like
to store the users password enter the password.

Now confirm the new server dialog and the settings dialog. On next update
interval Nagstamon should connect to the new server.
