= Securing the web interface with HTTPS
:revdate: 2019-12-04
[.seealso][#web_api] [#kerberos] [#ldap]MT:Operating (CMK) with HTTPS
MD:There are many reasons for running web interfaces only over HTTPS. This article will show you how to enable encryption in checkmk.


== Prerequisites

If you wish to install (CMK) over HTTPS the following prerequisites must
be satisfied on your monitoring server – irrespective of your instances:

* You must have a valid server certificate.
* The server is reachable under HTTPS.
* The Rewrite-Module for the webserver is available or loaded.


== Configuring an HTTPS-connection for an instance

In the configuration file, amend the section for the `VirtualHost`:

./etc/apache2/sites-enabled/000-default

----RewriteEngine On
RewriteCond %{SERVER_PORT} !^443$
RewriteRule (.*) https://%{HTTP_HOST}/$1 [L]
RequestHeader set X-Forwarded-Proto "https"
----

The `VirtualHost`-configuration is found – depending on the
distribution being used – in these files:

[cols=, ]
|===


|Debian, Ubuntu
|`/etc/apache2/sites-enabled/000-default(.conf)`


|RHEL, CentOS
|`/etc/httpd/conf.d/welcome.conf`


|SLES
|`/etc/apache2/httpd.conf`

|===

Following a configuration change the webserver must be restarted – the
restart commands are different for each distribution:

[source,bash]
----
RP:service httpd restart
RP:service apache2 restart
RP:systemctl restart httpd
RP:systemctl restart apache2
----
