include::global_attr.adoc[]
= Securing the web interface with HTTPS
:revdate: 2019-12-04
:title: Operating {CMK} with HTTPS
:description: There are many reasons for running web interfaces only over HTTPS. This article will show you how to enable encryption in checkmk.

[{related-hint}]
{related-title}
--
* link:web_api.html[Configuration via HTTP-API]
* link:kerberos.html[Single Sign-On with Kerberos]
* link:ldap.html[User Management with LDAP/Active Directory]
--


== Prerequisites

If you wish to install {CMK} over HTTPS the following prerequisites must
be satisfied on your monitoring server -- irrespective of your instances:

* You must have a valid server certificate.
* The apache module mod_ssl is installed and activated.
* The server is reachable under HTTPS.
* The Rewrite-Module for the webserver is available and loaded.


== Configuring an HTTPS-connection for an instance

Add the following lines in the section for the `VirtualHost`:

./etc/apache2/sites-enabled/000-default
[{file}]
----
RewriteEngine On
RewriteCond %{SERVER_PORT} !^443$
RewriteRule (.*) https://%{HTTP_HOST}/$1 [L]
RequestHeader set X-Forwarded-Proto "https"
----

The `VirtualHost`-configuration is found in these files -- depending on the
distribution being used:

[cols=2]
|===

|Debian, Ubuntu |/etc/apache2/sites-enabled/000-default(.conf)
|RHEL, CentOS |/etc/httpd/conf.d/ssl.conf
|SLES |/etc/apache2/httpd.conf
|===


Following a configuration change the webserver must be restarted. The
restart commands are different for each distribution:

[{shell}]
----
{c-root} service httpd restart
{c-root} service apache2 restart
{c-root} systemctl restart httpd
{c-root} systemctl restart apache2
----
