// -*- coding: utf-8 -*-
// IGNORE ActiveDirectory Okta OpenLDAP SP2 UI macOS
include::global_attr.adoc[]
= Release notes
:revdate: 2023-05-16
:title: Release notes for {CMK} {v22}
:description: This document explains the supported platforms and integrations of Checkmk 2.2.0. Unless for very specific reasons (e.g. security), these platforms remain supported through the active maintenance of Checkmk 2.2.0 including all patch versions

{related-start}
xref:update_major#[Update to the current major release]
xref:install_packages#[Basic information on the installation of {CMK}]
xref:agent_linux#[Monitoring Linux]
xref:agent_windows#[Monitoring Windows]
{related-end}

== Intro

This document explains the supported platforms and integrations of {CMK} {v22}. Unless for very specific reasons (e.g. security), these platforms remain supported through the active maintenance of {CMK} {v22} including all patch versions.

== Supported server OS

{CMK} can be installed on the following Linux server OS distributions and versions running in x86_64 hardware. We will evaluate new releases of these distributions as well for support.

[cols="34,66",options=header]
|===
|Operating system |Supported versions
|*Ubuntu* |20.04
| |22.04
|*Debian* |10
| |11
|*RHEL* |7
| |8
| |9
|*SLES* | 12 SP5
| |15 SP1
| |15 SP2
| |15 SP3
| |15 SP4
|===

== Supported browsers and versions

The {CMK} UI is verified to run on the following desktop browsers and browser minimum versions:

* Chrome >= 100 on Windows, Linux and macOS
* Firefox >= 100 on Windows, Linux and macOS
* Edge >= 100 on Windows
* Safari >= 15.6.1 on macOS

The {CMK} Mobile UI is verified to run on the following mobile browsers:

* Safari on iOS (Current and last major OS release)
* Chrome on Android (Current and last major OS release)

== Supported Grafana Plugin versions
{CMK} {v22} supports the following Grafana Plug versions:

* >=3.0.0

== Supported {CMK} Appliance versions
{CMK} {v22} can run on the following versions of the {CMK} Appliance:

* >= 1.6.3

== LDAP Server integrations
{CMK} {v22} will support sync with LDAP of the following LDAP servers:

* Microsoft ActiveDirectory
* OpenLDAP
* 389 server

== SAML IdP support
The SAML integration supports the following IdPs:

* Microsoft Azure Active Directory
* Google Cloud IdP
* Okta

{CMK} may work with other SAML integrations as well, but no support can be given.

== ntopng integration
The ntopng integration supports the following versions of ntopng Pro and Enterprise:

* >= 5.6

== Nagvis
Nagvis depends on PHP and requires a minimum version to run. Please make sure to provide a matching version of PHP your installation to run Nagvis:

* >= 7.2

== InfluxDB
{CMK} supports export of data to the following versions of the InfluxDB Rest API:

* >= 2.0