include::global_attr.adoc[]
= Security
:revdate: draft
:title: Additional security for {CMK}
:description: Checkmk is already very safe by design. What you can do to make your monitoring even more secure is described in this article.

{related-start}
link:omd_https.html[Securing the web interface with HTTPS]
link:agent_linux.html[Monitoring Linux]
link:ldap.html[User Management with LDAP/Active Directory]
{related-end}

Here will be an overview article on how to set up {CMK} so that you have
optimal network security for your monitoring server, as well as for the
monitored systems.

First the good news: through its own agents, {CMK} has an architecture that
was designed from the beginning for maximum security. This manifests itself,
for example, in that the agents basically do not read data directly from the
network. It is therefore impossible for an attacker to inject code. That said,
the agents do not even trust the monitoring server itself.

At various points in {CMK} HTTP protocols are used - whether for internal
communication or for the connection of other systems. Use HTTPS wherever
possible. In other places there are optional encryption techniques. You can
also find instructions in this manual:

- link:omd_https.html[Securing the web interface with HTTPS]
- link:agent_linux.html#security[Securing a Linux-Agent]
- link:ldap.html#ssl[Securing an LDAP-connection with SSL]
- link:appliance_usage.html#ssl[Securing the appliance GUI per TLS]
- link:managing_docker.html#https[Securing Docker with HTTPS]

//IN:cma_backup#encryption Encrypting appliance backups
