include::global_attr.adoc[]
= Security
:revdate: draft
:title: Security - Additional safeguarding for {CMK}
:description: {CMK} is already very safe by design. What you can do to make your monitoring even more secure is described in this article.


{related-start}
xref:omd_https#[Securing the web interface with HTTPS]
xref:agent_linux#[Monitoring Linux]
xref:ldap#[User management with LDAP/Active Directory]
{related-end}

Here will be an overview article on how to set up {CMK} so that you have
optimal network security for your monitoring server, as well as for the
monitored systems.

First the good news. Through its own agents, {CMK} has an architecture that
was designed from the beginning for maximum security. This manifests itself,
for example, in that the agents fundamentally do not read data directly from the
network. It is therefore impossible for an attacker to inject code. That said,
the agents do not even trust the monitoring server itself.

HTTP protocols are used at various points in {CMK} -- whether for internal
communication or for the connection of other systems. Use HTTPS wherever
possible. In other situations there are additional optional encryption techniques. You can also find instructions in this User guide:

- xref:omd_https#[Securing the web interface with HTTPS]
- xref:wato_user#2fa[Two-factor Authentication for {CMK} Users]
- xref:agent_linux#security[Securing a Linux-Agent]
- xref:ldap#ssl[Securing an LDAP-connection with SSL]
- xref:appliance_usage#ssl[Securing the appliance GUI per TLS]
- xref:managing_docker#https[Securing Docker with HTTPS]

//IN:cma_backup#encryption Encrypting appliance backups
