= System Monitoring with Checkmk – Part 1: The Basics
<br>
### Ich berufe mich hier mal auf "ernste Layoutprobleme".
### siehe Artikel internal_syntax
### Das sieht zwar auf der Webseite seltsam aus, aber die alternative ist im 
### gedruckten ganz furchtbar.
<br>
Here you will find the content and the timing for the
‘_System Monitoring with (CMK) -- Part 1: The Basics_’ training course.
This corresponds to the content of the slides shown during the course. Wherever
there are relevant articles in this manual, you will find their page numbers
here so that you can find them quickly during the course.

== Day 1

=== Introduction

SB:tribe29_logo.png

=== An introduction to (CMK)

=== Installation

IN:intro#editions             The (CMK) editions
IN:install_packages           Installing (CMK)
IN:omd_basics                 Creating instances
IN:cmk_commandline            (CMK) in the command line
IN:intro#guioverview          An overview of the GUI

SB:filesystem.png

=== Adding Hosts

IN:intro#hosts                Hosts, services, agents
IN:intro#folders              Folder structures
IN:intro#linux                Monitoring Linux servers
IN:intro#services             Configuring services
IN:intro#activatechanges      Activating changes

=== Monitoring Windows

IN:agent_windows              The Windows agent

=== Monitoring via SNMP

IN:snmp#intro             SNMP basics
IN:snmp#snmphost          SNMP hosts in (CMK)

== Day 2

=== Customizing/Extending the (CMK) agent

IN:localchecks                        Local Checks
IN:fehlt                              MRPE
IN:fehlt                              MRPE
IN:wato_monitoringagents#bakery       Packaging agents
IN:agent_deployment                   Automatic agent updates

=== An overview of the graphic interface

IN:intro#tactical_overview     Sidebar-Snap-ins: The Tactical Overview, views, bookmarks, Quicksearch, Master-Control
IN:user_interface              The Main Dashboard

=== Customizing the GUI

IN:intro#sidebar_customizing   Customizing the sidebar
IN:views#edit                  Customizing views
IN:dashboards#new              Creating a dashboard

=== The Metrics system

IN:intro#metrics               Graphs and metrics
IN:graphing#graph_collections  Graph collections

== Day 3

=== Operation

IN:intro#hosts                 The Status in monitoring
IN:intro#ack                   Acknowledgements
IN:intro#downtimes             Scheduled Downtimes
IN:intro#rules                 Rules-based configuration
IN:intro#hosttags              Host tags
IN:labels                      Labels

=== Tuning the monitoring

IN:intro#filesystems           File systems
IN:intro#switchports           Switchports
IN:intro#reboothosts           Rebooting hosts
IN:fehlt                       Logwatch in Windows
IN:intro#avgvalues             Average values
IN:fehlt                       Predictive Monitoring
IN:fehlt                       Timespecific Parameters
IN:intro#sporadic              Sporadic Errors
IN:monitoring_basics#parents   Parent/Child relationships
IN:wato_services#processes     Processes and services

== Day 4

=== Advanced service management

IN:intro#disabled                Ignoring checks and services
IN:intro#discovery               Discovery Check
IN:wato_services#bulk_discovery  Bulk Discovery

=== Users in (CMK)

IN:intro#roles                 Permissions and Roles
IN:intro#contacts              Contacts and responsibility
IN:intro#hostcontacts          Assigning contact groups to hosts and services
IN:intro#users             	  Managing users

=== Notifications

IN:intro#notifications          The concept of notifications
IN:intro#notify_init            Implementing notifications
IN:timeperiods                  Timeperiods

=== Distributed Monitoring

IN:distributed_monitoring#livestatus  	The centralized status overview
IN:distributed_monitoring#distr_wato    The centralized configuration
IN:distributed_monitoring#livestatus_tls	Securing connections

SB:distributed_monitoring.png

== Day 5

=== The Hardware/Software (HW/SW) Inventory

IN:inventory#activate          Activation
IN:inventory#operating         The Inventory View
IN:inventory#plugin            The agent plug-in
IN:inventory#changes           Changes in the inventory

=== A recap of the configuration

=== Backup and Restore

IN:omd_basics#backup       Backup and restore on the command line
IN:fehlt                   Backup and restore in the GUI

=== Updating (CMK)

IN:update                       Updating (CMK)

=== Aggregating metric data

IN:graphing#adding_metrics    min/max/avg