= System Monitoring with Checkmk - Part 2: Advance Topics
<br>
<br>
### Zeilenumbruch fuer den Druck leider noetig
You can find here the topics and the course of the training "_System
Monitoring with (CMK) - Part 2: Advanced Topics_". This represents
content of the slides shown during the training. You will find the
corresponding site numbers if a proper article is present in the manual so
you can find these during the training.

== Day 1

=== Introduction

=== The omd command

IN:omd_basics#cpmv                      Copying and renaming instances
IN:omd_basics#diff                      Detect changed files
IN:omd_basics#backup                    Backup and restore of instances
IN:omd_basics#sshmigration              Live migration of Sites per `ssh`
IN:omd_basics#scripts                   Managing instaces through scripts

=== Command line

IN:cmk_commandline                      Working with the command `cmk` in a shell
IN:cmk_commandline#data                 Overview of the file system - what is where?
IN:cmk_commandline#logs                 Logfiles in Checkmk
IN:cmk_commandline#config               Editing configuration files manually
IN:livestatus                           Getting livestatus data manually and through scripts

### Thema fuer Andreas:
=== WATO Web-API

IN:web_api#automation                  The automation user
IN:web_api#url                         The structure of the URL
IN:web_api#format                      Format of the input and output
IN:web_api#test                        tsting the API locally
IN:web_api#requests                    Creating and using request queries

=== Advanced functionality

IN:simulation_mode                      Running Checkmk in the sumulation mode
IN:fehlt                                Monitoring of Clusters
### Monitoring von Clustern kommt mit KNW-225 (also wenn es hier um Clustered
### Services gehen soll wovon ich mal ausgehe)
IN:datasource_programs                  Datasourceprograms


== Day 2

=== Business Intelligence

IN:bi                                Introduction into the BI module
IN:bi#first                          The first aggregation
IN:bi#statusgui                      BI in the status view
IN:bi#multilevel                     Multi-level trees
IN:bi#displayoptions                 Alternative displays
IN:bi#config3                        Variables, Templates, Searches
IN:bi#hostaggr                       The predefined host aggregation
IN:bi#permissions                    Permissions and visibility
IN:bi#operating                      Maintenance times, acknowledgments
IN:bi#biasservice                    BI as a service

=== Notifications

IN:notifications#bulk                       Bulk notifications
IN:notifications#syncsmtp                   Traceable Devlivery per SMTP
IN:fehlt                                    Notification per SMS
IN:distributed_monitoring#notifications     Notification in distributed systems
IN:notifications#scripts                    notification scripts

### Thema fuer Mathias:
=== Alerthandler

IN:alert_handlers                       Introduction into the Checkmk alert handler
IN:alert_handlers#setup                 Configuring alert handler
IN:alert_handlers#execution             Execution of alert handler
IN:alert_handlers#linux_remote          remote execution in Linux
IN:alert_handlers#files                 Relevant files and directories

=== Extending (CMK)

IN:mkps                                 Using Checkmk packages (MKPs)
IN:mkps#exchange                        Using MKPs of the Checkmk exchange
IN:mkps#wato                            Creating own MKPs
IN:mkps#commandline                     MKP on the command line
IN:mkps#distr_wato                      Using MKPs in distributed systems


== Day 3

=== Event Console

IN:ec                                   Introduction into the Event Console
IN:ec#setup                             Configuring the Event Console
IN:ec#operating                         Working with the Event Console
IN:ec#rules                             The full power of the rules
IN:ec#actions                           Execution of actions
IN:ec#snmp                              Receiving SNMP traps
IN:ec#logwatch                          Monitoring log files
IN:distributed_monitoring#ec            The Event Console in distributed systems

### Thema fuer Simon:
=== Hardware-/Software Inventory

IN:fehlt                                The capabilities of the Hardware-/Software Inventory?
IN:fehlt                                Configuring the inventory
IN:fehlt                                Analysing the inventory data through the GUI
IN:fehlt                                Technical background: How does it work?
IN:fehlt                                Exporting data into other systems
IN:fehlt                                The inventory in distributed systems


== Day 4

=== Availability

IN:availability                         How does Checkmk calculate the availability?
IN:availability#options                 The different options
IN:availability#bi                      Availablity of Bi aggregations

=== Reporting

IN:reporting                            Introduction ino the reporting module
IN:fehlt                                Using the instant reports
IN:reporting#create_reports             Creating own reports
IN:fehlt                                The basics of contexts
IN:reporting#scheduler                  Creating regular reports automatically

### Thema fuer Sven P.:
=== The Micro Core

IN:cmc                                  The purpose of the monitoring core
IN:cmc_migration                        Migration from  Nagios to CMC
IN:cmc_differences                      Specific characteristics of the CMC
IN:cmc_differences#checkhelper          Purpose and tuning of the check helper
IN:cmc_differences#metrics              How the CMC records metrics
IN:cmc_files                            Files and directories - where are the files?

SB:cee_architecture.png

=== Metrics

IN:graphing#custom_graphs               Creating custom graphs
IN:graphing#rrds                        Tuning and converting RRDs
IN:graphing#rrdcached                   The RRD cache


== Day 5

=== Managing users with LDAP

IN:ldap#connect                         Create a connection to Active Directory and LDAP
IN:ldap#contact_groups                  Configuring contact groups and roles in LDAP
IN:ldap#other_attr                      Mapping of other attributes
IN:ldap#distr_wato                      LDAP in distributed systems

=== Plugins & Agents

IN:monitoring_oracle                    Monitoring ORACLE
IN:monitoring_vmware                    Monitoring VMWare ESX
IN:fehlt                                Monitoring Solaris, HP-UX and AIX

### Thema fuer Lars:
=== NagVis

IN:fehlt                                Introduction into NagVis
IN:fehlt                                Creating maps and putting objects into place