// -*- coding: utf-8 -*-
// IGNORE 
include::global_attr.adoc[]
= Update matrix for version {v22}
:revdate: draft
:title: Update matrix for version {v22}
:description: This article shows the Linux distribution versions supported by {CMK}. This will help you determine the order to update {CMK} on your Linux server.

{related-start}
xref:update#[Updates and Upgrades]
xref:update_major#[Update to version {v22}]
xref:release_upgrade#[Linux upgrade on the {CMK} server]
xref:install_packages#[Basic information on the installation of {CMK}]
{related-end}


== Introduction
This article is currently being prepared for publication.
Please be patient. Thank you! +
If you need it urgently, please head over to the link:https://docs.checkmk.com/latest/de/update_matrix.html[German version of the article] and pump it into your favorite web translator.


// This block is new
// start translation
////

[#intro]
== Einleitung

Mit jeder Version von {CMK} fallen bislang unterstützte Linux-Versionen weg und neue kommen hinzu.
Dies kann es erforderlich machen, vor einem Update von {CMK} ein oder mehrere xref:release_upgrade#[Upgrades Ihrer Linux-Distribution] vorzunehmen.
Die Grafiken in diesem Artikel helfen Ihnen bei der Ermittlung der geeigneten Reihenfolge.
Studieren Sie diese aufmerksam, bevor Sie im link:https://checkmk.com/download/archive[Download-Archiv^] suchen oder Anfragen nach alten Paketen stellen.
Sollten Sie auf eine ältere {CMK}-Version als {v22} aktualisieren wollen, lesen Sie diesen Artikel bitte für die {CMK}-Version, die _Ziel_ der Aktualisierung ist.


[#steps]
== Ermittlung der Update-Schritte

Die Aufgabe ist es nun, in der xref:matrix[Kompatibilitäts-Matrix] für Ihre Linux-Distribution tendenziell von links oben nach rechts unten zu gelangen.
Dabei sind die Vorgaben für das xref:update#[Update von {CMK}] zu berücksichtigen:

* Es darf keine Major-Version ausgelassen werden.

* Vor dem Update der Major-Version muss auf die höchste verfügbare Patch-Version aktualisiert werden.
Die Mindestanforderungen sind im xref:update_major#update_patch[Artikel zum Update auf {v22}] beschrieben.

* Beim Upgrade der Linux-Distribution muss auf der neuen Distributionsversion exakt dieselbe {CMK}-Version installiert werden, die auf der alten vorhanden war.

Auch Linux-Distributoren machen in der Regel eine Vorgabe:

* Upgrades dürfen keine Version auslassen.

Ubuntu ist an dieser Stelle etwas speziell:
LTS-Versionen (_Long Term Support_, fünf Jahre Updates) sollten immer nur auf die nächste LTS-Version aktualisiert werden,
STS-Versionen (_Short Term Support_, neun Monate Updates) müssen in Halbjahresschritten aktualisiert werden.

Aus diesen Anforderungen ergibt sich, dass Sie sich in der Grafik für Ihre Linux-Distribution nur zeilen- oder spaltenweise bewegen dürfen – jedoch niemals diagonal – und, dass Sprünge nur dann zulässig sind, wenn sie nicht gegen die oben genannten Vorgaben verstoßen.
Für ein Update von Debian 9 mit {CMK} {v21}p1 auf Debian 12 mit {CMK} {v22} ergibt sich so die folgende Update-Reihenfolge:

. Unter Debian 9 führen Sie das Update von {CMK} {v21}p1 xref:update#[auf die aktuelle Patch-Version] von {v21} durch.

. Führen Sie das Upgrade von Debian 9 auf 10, 11 und schließlich auf 12 durch, so wie es im Artikel zum xref:release_upgrade#[Linux-Upgrade auf dem {CMK}-Server] beschrieben ist.

. Unter Debian 12 aktualisieren Sie die aktuelle Patch-Version von {CMK} {v21} auf die xref:update_major#[aktuelle Patch-Version von {v22}].


[#matrix]
== Kompatibilitäts-Matrix

Die {CMK}-Versionsnummern am oberen Rand der Grafiken in den folgenden Abschnitten zeigen immer diejenigen an, _ab_ der eine Veränderung vorgenommen wurde, also eine Linux-Version neu unterstützt oder nicht mehr unterstützt wird.
Eine Pfeilspitze am Ende eines Balkens bedeutet, dass diese {CMK}-Version im Support ist, also weitere Patch-Versionen folgen werden.
Ein stumpfes Ende kennzeichnet dagegen eine Kombination aus {CMK}-Version und Distributionsversion, die Ihr Support-Ende erreicht hat.
Das kann an einer abgekündigten {CMK}-Version (alle Balken sind stumpf) oder vom Distributor nicht mehr unterstützten Distribution liegen (einzelne Balken gehen mit Pfeilspitze weiter).
Erstellt werden die Grafiken automatisch aus täglich aktualisierten Daten zu den verfügbaren Downloads, das Änderungsdatum dieses Artikels gibt folglich nicht die Aktualität der angezeigten Daten wieder.


[#debian]
=== Debian

Die Support-Zeiträume der Debian-Versionen entnehmen Sie dem link:https://wiki.debian.org/LTS[Debian-Wiki^] oder der link:https://endoflife.date/debian[Übersicht bei endoflife.date.^]

[#matrix_debian]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für Debian angezeigt zu bekommen.


[#redhat]
=== RedHat Enterprise Linux

RedHat stellt eine ausführliche link:https://access.redhat.com/support/policy/updates/errata[Übersicht der geplanten Support-Zeiträume^] bereit.
Bei endoflife.date finden Sie Informationen zu der Derivaten link:https://endoflife.date/almalinux[AlmaLinux^], link:https://endoflife.date/centos[CentOS^], link:https://endoflife.date/oracle-linux[Oracle Linux^] und link:https://endoflife.date/rocky-linux[Rocky Linux^].

[#matrix_redhat]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für RedHat Enterprise Linux angezeigt zu bekommen.


[#sles]
=== SUSE Linux Enterprise Server

Auf der Seite von SUSE finden Sie die link:https://www.suse.com/lifecycle/#product-suse-linux-enterprise-server[Lifecycle-Übersicht^].
Alternativ steht eine link:https://endoflife.date/sles[Übersicht bei endoflife.date^] zur Verfügung.

[#matrix_sles]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für SUSE Linux Enterprise Server angezeigt zu bekommen.


[#ubuntu]
=== Ubuntu

Beachten Sie, dass STS-Versionen von Ubuntu _zukünftig_ von {CMK} nicht mehr unterstützt werden.
Wir achten jedoch immer darauf, dass von jeder {CMK}-Version, die für eine STS-Version bereitgestellt wurde, ein Update bis zur nächsten LTS-Version möglich ist.
Ab {v22} schafft die xref:ossupport[OS Support Policy] klare Regeln.

Ubuntu selbst pflegt eine nach noch im Support befindlichen und abgekündigten Versionen sortierte link:https://wiki.ubuntu.com/Releases[Liste^].
Nach Erscheinungsdatum sortiert ist link:https://endoflife.date/ubuntu[die Liste bei endoflife.date^].

[#matrix_ubuntu]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für Ubuntu angezeigt zu bekommen.


[#ossupport]
== Richtlinie zur Betriebssystemunterstützung in {CMK} _(OS Support Policy)_

Um einen Ausblick auf die Unterstützung durch künftige {CMK}-Versionen zu ermöglichen und Updates von Distributionen und {CMK} besser planen zu können, hat die {comfull} sich einige Regeln gegeben:

* _Enterprise-Distributionen_ (SLES, RHEL) werden bis 10 Jahre nach deren Erscheinungsdatum oder bis zum offiziellen Support-Ende durch den Distributor unterstützt.
* _Community-Distributionen_ (Debian, Ubuntu) werden bis 5 Jahre nach deren Erscheinungsdatum oder bis zum offiziellen Support-Ende durch den Distributor unterstützt, sofern es sich um LTS-Releases handelt.

In beiden Fällen ist der frühere Zeitpunkt entscheidend.
Wir streben dabei an, jede beim Erscheinen einer neuen {CMK}-Version unterstützte Distributionsversion über den gesamten Produkt-Lifecycle dieser {CMK}-Version zu unterstützen, sofern dem nicht technische Gründe entgegenstehen oder die Zahl der gleichzeitig unterstützten Versionen einer Distribution vier übersteigt.
Ist dies der Fall, behalten wir uns vor, die Distributionsversion mit dem kürzesten Rest-Support nicht mehr zu unterstützen.
Bekanntgegeben wird dies beim Erscheinen einer neuer {CMK}-Version.

Ubuntu STS-Versionen werden künftig gar nicht mehr unterstützt.
Da bei Veröffentlichung dieser _OS Support Policy_ bereits {CMK} {v21} für Ubuntu 22.10 veröffentlicht war, haben wir beschlossen, zur Erleichterung von Updates die Unterstützung für Ubuntus STS-Versionen langsam auslaufen zu lassen.
Dies bedeutet, dass Ubuntu 23.10 die letzte von {CMK} unterstützte STS-Version sein wird.
Betroffene Benutzer können anschließend mit dem Update auf 24.04 nahtlos auf eine LTS-Version wechseln.
////
// end translation
