// -*- coding: utf-8 -*-
// IGNORE p1
include::global_attr.adoc[]
= Update matrix for version {v20}
:revdate: 2023-11-07
:title: Update matrix for version {v20}
:description: This article shows the Linux distribution versions supported by {CMK}. This will help you determine the order to update {CMK} on your Linux server.

{related-start}
xref:update#[Updates and Upgrades]
xref:update_20#[Update to version {v20}]
xref:release_upgrade#[Linux upgrade on the {CMK} server]
xref:install_packages#[Basic information on the installation of {CMK}]
{related-end}


[#intro]
== Introduction

With each version of {CMK}, previously-supported Linux versions are removed and new ones are added.
This may make it necessary to perform one or more xref:release_upgrade#[upgrades of your Linux distribution] before performing an update of {CMK}.
The graphics in this article will help you to determine the appropriate sequence.
Study these carefully before searching the link:https://checkmk.com/download/archive[download archive^] or requesting an older package.
If you want to update to a version of {CMK} older or newer than {v20}, please read this article for the {CMK} version that is to be the _target_ of the update.


[#steps]
== Determining the required update steps

The task is now to move from the top left to the bottom right in the xref:matrix[compatibility matrix] for your particular Linux distribution.
The specifications for the xref:update#[Update of {CMK}] must be taken into account:

* No major version may be omitted.

* Before updating the major version, you must update to the highest patch version available for the major version.
The minimum requirements are described in the xref:update_20#[article on updating to {v20}].

* When upgrading the Linux distribution, exactly the same {CMK} version must be installed on the new distribution version as was present on the old one.

Linux distributors also generally set a requirement:

* Upgrades must not skip any version.

Ubuntu is somewhat special in this respect:
LTS versions (_Long Term Support_, five years of updates) should only ever be updated to the next LTS version,
STS versions (_Short Term Support_, nine months of updates) must be updated in half-yearly steps.

These requirements mean that you may only move in the graphic for your Linux distribution line by line or column by column -- _never_ diagonally -- and that jumps are only permitted if they do not violate the above requirements.
For an update from Debian 8 with {CMK} {v16}p1 to Debian 11 with {CMK} {v20}, this will result in the following update sequence:

. Under Debian 8, update {CMK} {v16}p1 xref:update#[to the current patch version] of {v16}.

. Now upgrade from Debian 8 to 9 and finally to 10 as described in the xref:release_upgrade#[Linux upgrade on the {CMK} server] article.

. On Debian 10, update the current patch version of {CMK} {v16} to the xref:update_20#[current patch version of {v20}].

. Finally run the xref:release_upgrade#[upgrade from Debian 10 to 11].


[#matrix]
== Compatibility matrix

The {CMK} version numbers at the top of the graphics in the following sections always indicate the version _from_ which a change has been made, i.e. a Linux version is newly supported or no longer supported.
An arrowhead at the end of a bar means that this {CMK} version is currently supported, i.e. further patch versions will follow.
A blunt end, on the other hand, indicates a combination of {CMK} version and distribution version that has reached its end of support.
This may be due to a discontinued {CMK} version (all bars are blunt) or a distribution that is no longer supported by the distributor (individual bars continue with arrowheads).
// The graphics are created automatically from daily-updated data on the available downloads, so the publication date of this article does not necessarily reflect the actuality of the displayed data.
Since both {CMK} {v16} and {CMK} {v20} reached their end of support, the tables on this page will receive no further updates.

[#debian]
=== Debian

The support periods of the Debian versions can be found at link:https://wiki.debian.org/LTS[Debian-Wiki^] or an overview at link:https://endoflife.date/debian[endoflife.date^].

[#matrix_debian]
Activate JavaScript to display the compatibility matrix for Debian here.

[#redhat]
=== RedHat Enterprise Linux

RedHat provides a detailed overview of link:https://access.redhat.com/support/policy/updates/errata[planned support periods^].
At endoflife.date you will find information on the link:https://endoflife.date/almalinux[AlmaLinux^], link:https://endoflife.date/centos[CentOS^], link:https://endoflife.date/oracle-linux[Oracle Linux^] and link:https://endoflife.date/rocky-linux[Rocky Linux^] derivatives.

[#matrix_redhat]
Activate JavaScript to display the compatibility matrix for RedHat Enterprise Linux here.


[#sles]
=== SUSE Linux Enterprise Server

On the SUSE page you will find the link:https://www.suse.com/lifecycle/#product-suse-linux-enterprise-server[lifecycle overview^].
Alternatively, an overview is available at link:https://endoflife.date/sles[endoflife.date^].


[#matrix_sles]
Activate JavaScript to display the compatibility matrix for SUSE Linux Enterprise Server here.


[#ubuntu]
=== Ubuntu

Note that STS versions of Ubuntu will _in future_ no longer be supported by {CMK}.
However, we always make sure that an update is possible from every {CMK} version that was provided for an STS version up to the next LTS version.

Ubuntu itself maintains a link:https://wiki.ubuntu.com/Releases[list^] sorted by versions still in support as well as discontinued versions.
The list at link:https://endoflife.date/ubuntu[endoflife.date^] is sorted by version release date.

[#matrix_ubuntu]
Activate JavaScript to display the compatibility matrix for Ubuntu here.
