// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Die {CMK} {CE}
:revdate: draft
:title: Die {CMK} {CE}
:description: Was die {CE} ausmacht, vor allem auch im Vergleich zu den anderen {CMK}-Editionen, erfahren Sie hier.

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:update#[Updates und Upgrades]
xref:cse#[Die {CMK} Enterprise {SE}]
{related-end}

include::include_draft.asciidoc[]


[#intro]
== Einleitung

Die eine perfekte Software-Lösung für jeden Nutzer und jeden Anwendungsfall gibt es nicht.
Was dem einen gefällt, ist dem anderen zu viel oder zu wenig, zu simpel oder zu komplex.
Deshalb ist auch {CMK} in verschiedenen Editionen verfügbar.
Diese unterscheiden sich vor allem im Leistungsumfang und in den Einsatzmöglichkeiten.
Im Folgenden möchten wir Ihnen die {CCE} vorstellen.


[#editions]
== Einordnung der {CE}

Die {CE} ist die derzeit umfangreichste Edition von {CMK}.
Inhaltlich baut sie auf der xref:cse#[{CSE}] auf, bietet aber zusätzlich umfangreiche Cloud-Funktionen.
Damit ist sie vor allem für die Nutzer von Wert, deren Hosts in einer Cloud beheimatet sind und die auch ihr gesamtes Monitoring in einer Cloud aufsetzen wollen.

Die Unterstützung bei der Verlagerung von Anwendungen und Prozessen in die Cloud, d.h. in sogenannten _Lift and Shift_-Szenarien, ist bereits in allen Editionen integriert 
-- bei der Überwachung von Amazon Web Services (AWS), Microsoft Azure und Google Cloud Platform (GCP).
Darüber hinaus bietet die {CE} auch Cloud-spezifische xref:glossar#check_plugin[Check-Plugins.]
So können Sie beim Übergang aus dem Rechenzentrum in eine Cloud weiter die {EE} nutzen.
Möchten Sie danach auch die SaaS und PaaS Produkte, die eine Cloud Ihnen bietet, nutzen, können Sie auf die {CE} upgraden.


[#functions]
== Zusätzliche Funktionen der {CE}

Die wesentlichen Funktionen der {CE}, die diese von anderen Editionen unterscheiden:

* Die {CE} ist über die Marketplaces von AWS und Microsoft verfügbar.

* Cloud-spezifische Dashboards +
//SP: Hier fehlt noch Text. Eventuell auch Screenshots.

* Fortgeschrittene Check-Plugins: +
Bei der Überwachung von xref:monitoring_aws#[Amazon Web Services (AWS),] xref:monitoring_azure#[Microsoft Azure] und xref:monitoring_gcp#[Google Cloud Platform (GCP)] gibt es in der {CE} zusätzliche, Cloud-spezifische Check-Plugins.
////
SP: Es gibt die Artikel monitoring_aws und monitoring_azure. Darin sind Listen der jeweiligen Check-Plugins sowie ein Verweis auf den katalog der Check-Plugins (https://checkmk.com/de/integrations). Noch gibt es aber keine aktuelle und vollständige Liste der Checks, die vor allem auch die Unterschiede der Editionen aufzeigen würde. Müssen wir diese schaffen oder lässt sich das delegieren?
Am Google Cloud Artikel schreibt Sebastian derzeit.
////

* Konfiguration eines Push-Agenten: +
In allen {CMK}-Editionen initiiert der {CMK}-Server die Kommunikation mit einem Host und fragt die Daten vom {CMK}-Agenten ab - im sogenannten xref:glossar.html#pull_mode[Pull-Modus.]
Mit der {CE} können Sie zusätzlich den xref:glossar.html#push_mode[Push-Modus] nutzen.
Den Push-Modus konfigurieren Sie in den Eigenschaften eines Hosts, im Abschnitt zu den xref:hosts_setup#monitoring_agents[Monitoring-Agenten.]

* Autoregistrierung von Hosts: +
In der {CE} können Sie xref:hosts_autoregister#[Hosts automatisch erstellen lassen], auf denen ein {CMK}-Agent installiert ist.
Dies beinhaltet die Registrierung des Agenten beim {CMK}-Server, den Aufbau einer TLS-verschlüsselte Verbindung, die Erstellung des Hosts, die Durchführung einer Service-Erkennung und die Aktivierung der Änderungen,
so dass der Host in die Monitoring-Umgebung aufgenommen wird — alles vollautomatisch.
Die Autoregistrierung funktioniert für Pull- und Push-Agenten.


[#upgrade]
== Upgrade zur {CE}

Sie können die {CE} unverbindlich testen, denn sie ist in den ersten 30 Tagen nicht limitiert.
Durch Eingabe eines Lizenzschlüssels nach spätestens 30 Tagen können Sie die {CE} dann ohne Beschränkungen einsetzen.

Für den Wechsel von einer der anderen Editionen zur {CE} folgen Sie der xref:update#upgrade[Upgrade-Beschreibung.]

////
== Weiterführende Artikel
SP: Liste inkl. Verknüpfungen zu den neu erstellten Artikeln zur CCE. Kann erst erstellt werden, wenn die Artikel fertig sind.
////
