include::global_attr.adoc[]
= Schnellstart-Anleitung {CMK} rack1
:revdate: draft
:title: Schnellstart-Anleitung {CMK} rack1
:description: Kurzanleitung für die Inbetriebnahme der physischen {CMK}-Appliance.


. Packen Sie das Gerät aus und überprüfen Sie die Lieferung auf Vollständigkeit.

. Schließen Sie das Gerät an. 
Für die Erstinstallation sollten Sie mindestens folgende Anschlüsse sicherstellen: Monitor an VGA-Anschluss, USB-Tastatur, Netzwerkverbindung (Anschluss: LAN1) und  Stromversorgung.

. Während des Starts des Gerätes werden Sie an der Konsole zur Initialisierung des RAID auffordert (*Achtung: Alle Daten auf den Festplatten werden gelöscht!*). Bestätigen Sie.

. Zum Abschluss des Starts wird die Statusansicht der Konsole angezeigt.

. Damit die Appliance zum Monitoring genutzt werden kann, müssen nun noch einige Einstellungen vorgenommen werden: 
Drücken Sie die Taste `F1` und setzen Sie mit dem Konfigurationsmenü mindestens die folgenden Einstellungen: xref:appliance_usage#network_access_config[Netzwerkkonfiguration und Aktivierung der Web-Oberfläche]

. Nachdem dies erledigt ist, können Sie auf die Web-Oberfläche der Appliance über deren IP-Adresse zugreifen:
Geben Sie von einem an das Netzwerk angeschlossenen Computer über einen Webbrowser die URL `\http://&lt;ipaddress&gt;/` ein und melden Sie sich mit dem Passwort an, das Sie im vorherigen Schritt bei der Aktivierung der Web-Oberfläche vergeben haben..

. Laden Sie das {CMK} Software-Paket für die Appliance als CMA-Datei von unserer link:https://checkmk.com/de/download[Download-Seite] herunter. 
Anschließend wählen Sie in der Web-Oberfläche der Appliance [.guihint]#Check_MK Versions#. In einem Schritt laden Sie das soeben heruntergeladene Software-Paket in die Appliance hoch und installieren es -- wie es detailliert bei der xref:appliance_usage#manage_cmk[Verwaltung der {CMK} Software-Versionen] beschrieben ist.

. Erstellen Sie eine Instanz (_site_) mit der installierten {CMK} Software-Version: 
erneut über die Web-Oberfläche der Appliance, diesmal mit dem Knopf [.guihint]#Site Management#. 
Auch dafür gibt es eine ausführliche Anleitung bei der xref:appliance_usage#site_management[Verwaltung der Monitoring-Instanzen]. 
Die Instanz startet nach dem Erstellen automatisch.

. Nun können Sie sich an der {CMK}-Instanz anmelden: 
über die URL `\http://&lt;ipaddress&gt;/&lt;siteid&gt;/` und mit den Zugangsdaten, die Sie beim Erstellen der Instanz selbst festgelegt haben.

. Um Dinge wie Namensauflösung und Senden von E-Mails zu ermöglichen, müssen Sie in der Web-Oberfläche der Appliance noch weitere Einstellungen vornehmen. 
Mehr dazu finden Sie bei den
xref:appliance_usage#basic_settings_webconf[Grundeinstellungen in der Web-Oberfläche] und den xref:appliance_usage#cma_webconf_system_settings[Geräteeinstellungen].
+
Für einen ersten Start ist das aber noch nicht notwendig.

{CMK} steht nun für Sie bereit! Erfahren Sie im xref:checkmk_getting_started#[Schnelleinstieg ins Monitoring], wie es weiter geht.
