include::global_attr.adoc[]
= Schnellstart-Anleitung {CMK} rack1
:revdate: 2019-04-04
:title: Schnellstart-Anleitung {CMK} rack1
:description: Kurzanleitung für die Inbetriebnahme der physischen {CMK}-Appliance.


* Packen Sie das Gerät aus und überprüfen Sie zunächst die Lieferung auf Vollständigkeit.
* Schließen Sie das Gerät an. Für die erstmalige Installation sollten Sie mindestens folgende Anschlüsse sicherstellen:
* Monitor an VGA-Anschluss
* USB-Tastatur
* Netzwerkverbindung (Anschluss: LAN1)
* Stromversorgung
* Während des Starts des Gerätes erscheint am Bildschirm ein Dialog, der Sie zur Initialisierung des RAIDs auffordert (*Achtung: Alle Daten auf den Festplatten werden gelöscht!*). Bestätigen Sie diesen. Nach einigen Minuten setzt sich der Startvorgang fort.
* Zum Abschluss des Starts wird die Statusansicht der Konsole angezeigt.
* Damit die Appliance zum Monitoring genutzt werden kann, müssen nun noch einige Einstellungen vorgenommen werden. Drücken Sie nun die Taste `&lt;F1&gt;` und konfigurieren Sie mit Hilfe des Konfigurationsdialoges mindestens folgende Einstellungen:
* Netzwerkkonfiguration
* Zugriff auf die Weboberfläche
* Nachdem Sie diese Dinge konfiguriert haben, können Sie durch die Eingabe der URL `http://&lt;ipaddress&gt;/` über den Webbrowser von einem an das Netzwerk angeschlossenen Computer auf die Weboberfläche zugreifen. Loggen Sie sich hier mit dem soeben konfigurierten Passwort ein.
* Wählen Sie im nun sichtbaren Menü den Punkt link:appliance_usage.html#site_management[Instanzverwaltung] und klicken Sie auf der folgenden Seite auf _Neue Instanz anlegen_.
* Legen Sie nun mit Hilfe des aktuellen Dialogs eine neue Monitoring-Instanz an. Diese startet automatisch.
* Nun können Sie in Ihrem Browser die URL `http://&lt;ipaddress&gt;/&lt;instanz-id&gt;/` aufrufen.
* Dort können Sie {CMK} nun wie gewohnt einrichten.
* Um Dinge wie Namensauflösung und Senden von E-Mails zu ermöglichen, müssen Sie in der Weboberfläche noch weitere Einstellungen vornehmen. Mehr dazu finden Sie im Artikel zur link:appliance_usage.html[Grundkonfiguration in der Weboberfläche].

Erfahren Sie im weiterführenden Artikel link:checkmk_getting_started.html[{CMK} Getting Started], wie es weiter geht.
