// -*- coding: utf-8 -*-
// IGNORE Iconset Nuvola Vignoni
include::global_attr.adoc[]
= Copyright-Hinweise
:revdate: 2017-01-26
:title: Copyright-Hinweise
:description: Hinweise zu den Rechten an Texten und Grafiken im {CMK} Handbuch
:no-toc:

Dieses Handbuch ist urheberrechtlich geschützt. Die Rechte von allen Texten
und Grafiken liegen bei der {comfull}.

Einige der enthaltenen Bilder (Icons) stammen aus dem Nuvola-Iconset von
David Vignoni und stehen unter LGPL Version 2.1. Für diese gilt folgende
Lizenz:

_This library is free software; you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation; either version 2.1 of the License, or (at your option)
any later version. This library is distributed in the hope that it will
be useful, but without any warranty; without even the implied warranty of
merchantability or fitness for a particular purpose. See version 2.1 and
version 3 of the GNU Lesser General Public License for more details._

Einzelheiten zu den Icons von David Vignoni finden Sie
link:http://www.icon-king.com/projects/nuvola/[hier].

