// -*- coding: utf-8 -*-
// IGNORE Benachrichtigungs
include::global_attr.adoc[]
= Die {CMK} Enterprise {SE}
:revdate: draft
:title: Die {CMK} {SE}
:description: Die unterschiedlichen {CMK}-Editionen bieten einen unterschiedlichen Feature-Umfang. Dieser Artikel erklärt die {SE}.

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:update#[Updates und Upgrades]
xref:cce#[Die {CMK} {CE}]
{related-end}

////
TK:
- Komponenten: Puh, schwierig. Insbesondere, wenn man die Ablage "Sonstiges" vermeiden will.
Alternativer Vorschlag: Halte Dich nach dem Monitoring-Kern (most important!) ziemlich stumpf an unsere TOC-Struktur. 
- Tabellen: Ich würde in Spalte 1 nur die allgemeine Funktion benennen (Monitoring-Kern statt CMC, Berichte statt Vorgefertigte Berichte) und dann in Spalte 2 den Unterschied beschreiben.
- Generell sollten die Links tiefer in die Artikel gehen, in den Abschnitt, wo die CEE-Spezifika benannt werden.
- Bei der Beschreibung nutzt Du des öfteren den Komperativ ("effizientere und flexiblere") ohne dass die CRE als Basis erwähnt wird. Das liest sich, als ob was fehlt ("Phantomleseschmerz").
- Bei der Gelegenheit: Das TOC-Kapitel "Besonderheiten in den Editionen" sollte in "Die Editionen" umbenannt werden, nach oben rutschen und hinter "Willkommen bei Checkmk" einsortiert werden.
////
  
[#intro]
== Einleitung

Eine Lösung für alle kann es nicht geben und wer für Software-Subskriptionen Geld bezahlt, möchte möglichst nur Features bezahlen, die man auch nutzt.
{CMK} bietet aus diesem Grund verschiedene Editionen für verschiedene Einsatzbereiche.
In diesem Artikel stellen wir Ihnen die {CSE} vor, die im professionellen Umfeld die am häufigsten anzutreffende Edition ist.


[#editions]
== Einordnung der {SE}

Aufbauend auf der reinen Open Source Variante {CMK} {RE} bietet die {SE} vor allem Verbesserungen der Performance, umfangreichere Möglichkeiten von _Dashboards_ sowie _Reporting_ und Erleichterungen der _Automatisierung_.
Sie spricht damit vor allem professionelle Anwender an, die Subskriptionskosten gesparten Hardwarekosten und reduziertem Aufwand zur Erstellung eigener Erweiterungen entgegenstellen.
Daneben bietet die {SE} verschiedene Möglichkeiten, Support mit garantierter Reaktionszeit zu buchen.

Auf der {SE} baut wiederum die xref:cce#[{CCE}] auf.

Ergänzend zum link:https://checkmk.com/de/produkt/editionen[Editionsvergleich^] auf unserer Website zeigt dieser Artikel die Unterschiede auf technischer Ebene und versucht so, eine komplementäre Entscheidungshilfe bei der Wahl der Edition zu sein.

Daneben soll er helfen, abzuschätzen, welche Einstellungsänderungen beim xref:update#[Wechsel der Edition] – egal, ob Up- oder Downgrade – notwendig oder sinnvoll sind.


[#functions]
== Zusätzliche Funktionen der {SE}

Die wesentlichen Funktionen der {SE}, die diese von der {CRE} unterscheiden:

* Performance-Verbesserungen: +
Mit dem _Checkmk Micro Core (CMC)_ nutzt die {SE} einen Monitoring-Kern, der Speicher und CPU effizienter ausnutzt.

* Erleichtertes verteiltes Monitoring: +
Eine Vielzahl von Erweiterungen erleichtert verteiltes Monitoring.
Dazu gehört die Möglichkeit, die Konfiguration komplett zu zentralisieren, Benachrichtigungen komplett über die Zentralinstanz abzuwickeln und verschiedene Techniken, auch bei langsamen oder instabilen Netzen einen zuverlässigen Transfer von Monitoring-Daten zu gewährleisten.

* Business-Features: +
Wo IT geschäftskritisch ist, muss Monitoring helfen, Probleme zu dokumentieren, einzuordnen und zu verhindern.
Die {SE} bietet hierfür _proaktive_ Funktionen wie die Einrichtung von wiederkehrenden Wartungszeiten und _retrospektive_ wie die Erstellung von Verfügbarkeitsberichten – letzteres auch für komplexe Systeme, die aus einer Vielzahl an Komponenten bestehen.
// TK: proaktiv mag ich nicht (bin ich der Einzige?): Wie wärs mit vorausschauend? planende?


[#upgrade]
== Upgrade zur {SE}

// TK: Umgeschrieben, da es hier bisher nur um die CCE ging. 
////
Mit einem gültigen Lizenzschlüssel können Sie Ihre Raw oder Test Edition jederzeit auf eine {CE} upgraden.
Folgen Sie dafür der xref:update#updatedemo[Upgrade-Beschreibung für die verschiedenen Editionen.]

Da die bis maximal 750 Services kostenlos nutzbare {CMK}-Version auf der xref:cce#[{CE}] basiert, sind beim Wechsel möglicherweise xref:update#cce2cee[kleinere Konfigurationsänderungen] nötig. 
////

Sie können eine {RE} jederzeit auf eine {SE} upgraden.
Folgen Sie dafür der xref:update#updateraw[Upgrade-Beschreibung] zur {SE}.

Falls Sie {CMK} mit der in den ersten 30 Tagen nicht limitierten {CE} getestet haben, können Sie nach der Testphase auch dauerhaft zur {SE} wechseln.
Folgen Sie dafür der xref:update#cce2cee[Downgrade-Beschreibung] zur {SE}.


[#details]
== Unterschiede der Komponenten im Detail

[#core]
=== Monitoring-Kern

Dieser Abschnitt behandelt Unterschiede am Monitoring-Kern und der Übertragung von Monitoring-Daten in verteilten Umgebungen.
Nutzer, die von Nagios-Umgebungen zu {CMK} migrieren, sollten die Dokumentation zum xref:cmc#[{CMK} Micro Core] und den xref:cmc_differences#[Besonderheiten des CMC] aufmerksam lesen, um zu beurteilen, ob es für eine Übergangszeit sinnvoll sein kann, {CMK} mit dem Nagios-Kern zu betreiben.

////
cmc.asciidoc			Checkmk Micro Core
cmc_differences.asciidoc	grafische Darstellung der Daten durch die GUI von CMK <- ist PNP4Nagios noch aktuell?
cmc_migration.asciidoc		Alert handler nur in EE
analyze_configuration.asciidoc	Performance/Checkmk Hilfsprozesse <- erst einmal unterschlagen
distributed_monitoring.asciidoc	In EE automatische Synchronisierung von Inventardaten
distributed_monitoring.asciidoc Livestatus-Proxy
distributed_monitoring.asciidoc CMCDump
graphing.asciidoc		RRD-Speicherformat
livestatus.asciidoc		Unterschiedlicher Umfang der Kommandos
livestatus_references.asciidoc	CEE only Kommandos
wato_rules.asciidoc		Smart Ping nur in EE
////

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen
|CMC |Die {EE} verwenden standardmäßig den xref:cmc#[{CMK} Micro Core], welcher durch Reduzierung auf die wesentliche Funktionalität und Optimierung dieser performanter als andere Monitoring-Kerne ist.
|Alert Handler |Der CMC unterstützt keine _Nagios Event Handler_, bietet dafür aber flexiblere xref:alert_handlers#[Alert Handler].
|Smart Ping |Der xref:cmc_differences#smartping[Smart Ping] gewährleistet eine effizientere und schnellere Erkennung, ob Hosts erreichbar sind.
|CMCDump |Diese Übertragungstechnik vereinfacht xref:distributed_monitoring#livedump[verteiltes Monitoring] in Umgebungen mit unzuverlässiger Netzwerkanbindung. In Umgebungen mit Nagios-Kern steht stattdessen Livedump zur Verfügung.
|Livestatus-Proxy | Der xref:distributed_monitoring#livestatusproxy[Livestatus-Proxy] optimiert im verteilten Monitoring Performance und Latenzen. 
|RRD-Speicherformat |Bei Verwendung des CMC nutzt {CMK} ein auf Einsparung von Disk-I/O xref:cmc_differences#metrics[optimiertes Speicherformat] der Round Robin Databases (RRD).
|Parent Child Topology | Mit dem CMC kann {CMK} in Umgebungen mit Elter-Kind-Topologie präziser xref:monitoring_basics#parents[den Zustand von abhängigen Hosts] ermitteln.
// TK: Wording ist nicht so dolle. Das Thema gehört doch zum CMC?
|Unstetigkeitserkennung (_flap detection_) |In den {EE} ist eine xref:notifications#flapping[Feineinstellung der Unstetigkeitserkennung] möglich für Services, die längere Zeit um Schwellwerte pendeln.
// TK: Unstetigkeitserkennung gehört nicht zu Benachrichtigungen
|===

[#ui]
=== Monitoring-Oberfläche, Graphing, Dashboards

////
availability.asciidoc		PDF Export
basics_ackn.asciidoc		Expire acknowledgement after
basics_downtimes.asciidoc	Kommandos eine oder mehrere Downtimes entfernen/ändern
basics_downtimes.asciidoc	automatisch periodisch wiederholenden Wartungszeiten
dashboards.asciidoc		Einige der Dashlets gibt es exklusiv in den EE
dashboards.asciidoc		Anderes Default-Dashboard
graphing.asciidoc		PDF-Export, Graphensammlungen, benutzerdefinierte Graphen
graphing.asciidoc		einbetten in Berichte oder Dashboards, Graphensammlung
graphing.asciidoc		Graph Tunings
graphing.asciidoc		Custom Graphs
intro_extend.asciidoc		SLA Software-Modul nur in EE
intro_finetune.asciidoc		Wartungszeiten
intro_finetune.asciidoc		Recurring downtimes
monitoring_basics.asciidoc	Statuswechsel, Verhalten bei Parent/Child wenn UNREACH
monitoring_kubernetes.asciidoc	Kubernetes Dashboards
monitoring_kubernetes.asciidoc	Cluster Dashboards
reporting.asciidoc		Vorgefertigte Berichte
sla.asciidoc			SLA Software-Modul nur in EE
views.asciidoc			This view as PDF
////

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen
|Standard-Dashboard |Die {EE} verwenden als Standard ein xref:dashboards#usage[Dashboard], welches in der {RE} nicht verfügbar ist. Diese nutzt stattdessen das Problem-Dashboard.
// TK: Link geändert
|Messwerte und Graphing |Erweiterte xref:graphing#[Funktionen des Graphings] stehen ausschließlich in den {EE} zur Verfügung. Dazu gehören: Umfang der Dashlets, PDF-Export, Graphensammlungen, Anpassungen (_graph tunings_), Einbettung in Berichte oder Dashboards und benutzerdefinierte Graphen.
|Kubernetes-Dashboards |Die xref:monitoring_kubernetes#[Kubernetes-Dashboards] sind den {EE} vorbehalten.
// TK: Was meinst Du mit Cluster-Dashboards? In monitoring_kubernetes sollte ein Anker für 5.1. Kubernetes-Dashboards angelegt werden.
// MFS: Cluster entfernt, findet sich eher unspezifisch in Marketingmaterialien
|Wartungszeiten (_scheduled downtimes_) |Nur in den {EE} können regelmäßig wiederkehrende xref:intro_finetune#[Wartungszeiten] festgelegt werden. Zudem ist über _Kommandos_ eine komfortable xref:intro_finetune#[Änderung oder Entfernung einer oder mehrerer Wartungszeiten] möglich.
// TK: Das ganze Thema Wartungszeiten ist bei uns viel zu oft und dann auch noch unübersichtlich beschrieben (ich habs jedenfalls nicht verstanden). Die beiden Zeilen sollten zusammengefasst werden. Die Links sollten nach basics_downtimes gehen.
// |Parent Child Topology | Mit dem CMC kann {CMK} in Umgebungen mit Elter-Kind-Topologie präziser xref:monitoring_basics#parents[den Zustand von Kind Hosts] ermitteln.
// TK: Wording ist nicht so dolle. Das Thema gehört doch zum CMC?
|PDF-Export der Verfügbarkeit |In den {EE} können xref:availability#[Verfügbarkeitsdaten] auch als PDF exportiert werden.
|PDF-Export von Ansichten |Der direkte PDF-Export von xref:views#[Ansichten] im Monitoring ist den {EE} vorbehalten.
|Reporting |xref:reporting#[Reporting mit vorgefertigten Berichten] ist den {EE} vorbehalten.
// TK: Ich meine, dass es das *komplette* Reporting nicht in der CRE gibt.
|Erweiterte Verfügbarkeiten (SLAs) |Die nur in den {EE} enthaltenen xref:sla#[Erweiterte Verfügbarkeiten / Service Level Agreements] erleichtern die Kontrolle von vertraglichen Vereinbarungen betreffend der Verfügbarkeit von Diensten.
// TK: Erweiterte Verfügbarkeiten (SLAs) statt Service Level Agreements?
| Quittierung mit Gültigkeitsdauer | Die xref:basics_ackn#[Quittierung von Problemen] kann in den {EE} mit einer maximalen Gültigkeitsdauer versehen werden.
|===

[#notifications]
=== Benachrichtigungen
 
////
s.o. notifications.asciidoc		Statuswechsel, Verhalten bei Parent/Child wenn UNREACH
notifications.asciidoc		Tuning of flap detection
notifications.asciidoc		Benachrichtigungs-Spooler
notifications.asciidoc		Asynchrone Zustellung durch Benachrichtigungs-Spooler
notifications.asciidoc		nachvollziehbaren Zustellung per SMTP
notifications.asciidoc		Zentrale Benachrichtigungen
s.o. notifications.asciidoc		Alert Handler
distributed_monitoring.asciidoc	Zentrale Benachrichtigungen
////

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen
|Benachrichtigungs-Spooler (_notification spooler_) | Die {EE} enthalten mit dem xref:notifications#async[Benachrichtigungs-Spooler] eine Komponente, welche die effizientere und flexiblere Zustellung von Benachrichtigungen erlaubt.
|Nachvollziehbare Zustellung |Über xref:notifications#syncsmtp[Smarthost-Einstellungen] kann in den {EE} zuverlässiger sichergestellt werden, dass Benachrichtigungen ankommen als mit einer reinen Übergabe an das lokale Mailsystem der {RE}.
|Zentrale Benachrichtigungen | Im verteilten Monitoring kann der Benachrichtigungs-Spooler der {EE} so konfiguriert werden, dass er xref:distributed_monitoring#notifications[Benachrichtigungen von den Remote-Instanzen für alle Ziele] verschickt.
|===

[#agents]
=== Monitoring-Agenten, Verteilung und Registrierung
// TK: Warum hier Registrierung?

////
agent_deployment.asciidoc	Bakery
agent_deployment.asciidoc	Agent Updater
agent_linux.asciidoc		Bakery
agent_linux_legacy.asciidoc	Bakery
agent_windows.asciidoc		Bakery
bakery_api.asciidoc		Bakery
cmk_commandline.asciidoc	Bakery
snmp.asciidoc			Eigene SNMP-Engine statt snmpget/snmpbulkwalk
wato_monitoringagents.asciidoc	Unterscheidung Checkmk-Fetcher vs. Nagios
////

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen
|Agentenbäckerei (_Agent Bakery_) |Die {EE} verfügen mit der xref:wato_monitoringagents#bakery[Agentenbäckerei] über einen Mechanismus, automatisch individuelle Agentenpakete mit Plugins und Konfigurationsdateien zu erstellen. Einstellungen der Agenten-Konfiguration können mit der xref:bakery_api#[Bakery-API] in der Setup-GUI vorgenommen werden.
|Agenten-Update |Die xref:agent_deployment#[automatische Aktualisierung] von Agentenpaketen nach Konfigurationsänderungen ist nur in den {EE} möglich.
|SNMP-Monitoring |Dank einer eigenen xref:snmp#[SNMP-Engine] _(Inline SMTP)_ sind die {EE} performanter als die {RE} mit der Nutzung von `snmpget`/`snmpbulkwalk`.
// TK: Ach was? Hab ich ja noch nie davon gehört.
// MFS: Behaupten Marketing und Entwickler, kann mit Regeln für bestimmte Hosts deaktiviert werden, woil mit weniger Implementierungen kompatibel als snmpget
|{CMK}-Fetcher |In den {EE} sorgen die {CMK}-Fetcher für effizientes xref:wato_monitoringagents#[Einholen der Monitoring-Daten.]
|===

[#connectors]
=== Anbindungen

////
saml_new.asciidoc		SAML Konfiguration via Setup GUI
grafana.asciidoc		Filterkaskaden
metrics_exporter.asciidoc	Anbindung an externe Metrik-Datenbanken (Influx, Graphite)
graphing.asciidoc		Anbindung an externe Metrik-Datenbanken (Influx, Graphite)
notifications_jira.asciidoc	Nur in EE
notifications_servicenow.asciidoc Nur in EE
////

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen
|SAML |Seit {CMK} {v22} können die {EE} nativ gegen xref:saml#[SAML authentifizieren], bis {v21} und weiterhin in der {RE} ist dies nur auf Apache-Ebene möglich.
|Grafana |Das xref:grafana#[Grafana-Plugin] erlaubt bei Nutzung mit den {EE} Filterkaskaden.
|InfluxDB und Graphite |Nur die {EE} liefern eine Schnittstelle zur Anbindung an xref:metrics_exporter#[externe Metrik-Datenbanken] mit.
|Jira | Das xref:notifications_jira#[Benachrichtigungsmodul für Jira] ist den {EE} vorbehalten.
|ServiceNow | Das xref:notifications_servicenow#[Benachrichtigungsmodul für ServiceNow] gibt es nur in den {EE}.
|===

[#other]
=== Weitere Funktionen

////
dcd.asciidoc			Nur in EE
monitoring_docker.asciidoc	DCD
monitoring_gcp.asciidoc		DCD
inventory.asciidoc		HW/SW-Inventur in verteilten Umgebungen
mkps.asciidoc			MKPs über die GUI verwalten
predictive_monitoring.asciidoc	Nur in EE
////

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen
|DCD |Die dynamische Host-Konfiguration mit dem xref:dcd#[Distributed Configuration Daemon] ermöglicht die automatische Erstellung von Hosts und erleichtert damit die Überwachung von xref:monitoring_docker#[Docker] und der Cloud wie zum Beispiel xref:monitoring_aws#[Amazon Web Services (AWS)] oder xref:monitoring_gcp#[Google Cloud Platform (GCP).]
// TK: Auf Cloud verallgemeinert
// MFS: Haben wir einen Cloud-Artikel, auf den wir verlinken können?
|Verteilte HW/SW-Inventur |Die automatische Synchronisierung von Inventardaten im xref:distributed_monitoring#[verteilten Monitoring] macht Inventardaten zentral verfügbar.
// TK: Ist das nicht eine Anwendung des Livestatus-Proxys?
|MKP-Verwaltung |Die Verwaltung von xref:mkps#[{CMK}-Erweiterungspaketen] ist in der {RE} nur auf der Kommandozeile möglich, in den {EE} zusätzlich über die Setup-GUI.
|Prognosebasiertes Monitoring (_predictive monitoring_) |Auf Basis der ermittelten Werte über einen längeren Zeitraum kann in den {EE} ein xref:predictive_monitoring#[prognosebasiertes Monitoring] mit dynamischen Schwellwerten genutzt werden.
|===
