// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Schnellstart-Anleitung für {CMK}-Racks
:revdate: draft
:title: Schnellstart-Anleitung für {CMK}-Racks
:description: Kurzanleitung für die Inbetriebnahme der physischen {CMK}-Appliance.
:no-toc:

{related-start}
xref:appliance_usage#[Die Appliance]
xref:appliance_cmk_install#[Installation von {CMK} in der Appliance]
xref:cma_virt1_quick_start#[Schnellstart-Anleitung für virt1]
{related-end}

// ML: Angedacht war, dass die Anleitung bis zur Aktivierung der Weboberfläche der Appliance geht. Beim Durchspielen fand ich es zunehmend sinnvoller, das Ding bis zur Anmeldung an Checkmk zu erweitern - weil es bis dahin Appliance-spezifisch ist. rack1 und virt1 sind bis auf die ersten beiden Punkte identisch - daher vielleicht später via Include lösen, um einfacher aktualisieren zu können. Andere Meinungen?
// TK: Find ich gut, das zu erweitern.

// TK: Ich hab noch nie verstanden, warum es nur eine Schnellstart-Anleitung für rack1 gibt und keine für rack4 und rack4+. Die Anleitung ist doch für alle 3 identisch, oder?
// ML: 4+ ist etwas anders, da gibt es Glasfaseranschlüsse ... Aber der Grund ist simpel: Es gab früher nur rack1 (und rail1) und der Titel hat sich nie mit verändert ...

////
Einleitung für angedachte Version:
In dieser Schnellstart-Anleitung führen wir Sie vom Download der Appliance über deren Grundeinrichtung bis zur Aktivierung der Weboberfläche, über die Sie dann Ihre {CMK}-Installationen und -Instanzen verwalten können.
////

Diese Schnellstart-Anleitung führt Sie vom Aufstellen der Appliance über eine Minimalkonfiguration bis hin zum Anmeldebildschirm einer laufenden {CMK}-Instanz.

Ausführliche Informationen und Anleitungen finden Sie im xref:appliance_usage#[Hauptartikel zur Appliance.]


== Maschine einrichten (Konsole)

. Schließen Sie das Gerät an. Für die Inbetriebnahme benötigen Sie zumindest: Monitor (VGA), USB-Tastatur, Netzwerkverbindung (Anschluss: LAN1) und Stromversorgung (vorzugsweise beide Anschlüsse).

. Während der Initialisierung beim Erststart werden Sie zur Initialisierung des RAIDs aufgefordert, wobei natürlich alle Daten auf den Festplatten gelöscht werden.
xref:appliance_usage#init_start[Mehr ...]. +
Bestätigen Sie.

. Nach der Initialisierung sehen Sie die Statusansicht der Konsole, den Startbildschirm bei allen weiteren Starts.

. Damit die Appliance zum Monitoring genutzt werden kann, müssen Sie nun noch einige Einstellungen vornehmen. 
Drücken Sie die Taste `F1`, um das Konfigurationsmenü aufzurufen und setzen Sie mindestens die folgenden Einstellungen:

.. [.guihint]#Network Configuration:# IP-Adresse, Netzmaske und optional das Standard-Gateway.
xref:appliance_usage#network_config[Mehr ...]

.. [.guihint]#Device Password:# Passwort zur *Aktivierung* der Weboberfläche der Appliance.
xref:appliance_usage#network_access[Mehr ...]

. Starten Sie nun die Weboberfläche der Appliance über die oben vergebene IP-Adresse auf einem beliebigen Rechner im Netzwerk mit `\http://&lt;ipaddress&gt;/`.
Loggen Sie sich mit dem gesetzten Passwort ein.
Ein Benutzername wird nicht benötigt.

////
Wie genau Sie über die Weboberfläche {CMK}-Versionen und -Instanzen einrichten, das Gerät konfigurieren, Datensicherungen planen, Cluster aufbauen und so weiter, lesen Sie im xref:appliance_usage#[Hauptartikel zur Appliance.]
////


== Monitoring einrichten (Web-GUI)

. Laden Sie das {CMK}-Software-Paket für die Appliance von unserer link:https://checkmk.com/de/download[Download-Seite^] herunter.

. Navigieren Sie in der Weboberfläche der Appliance zu [.guihint]#Check_MK Versions# und installieren Sie das {CMK}-Paket über den Knopf [.guihint]#Upload & Install.#
xref:appliance_usage#manage_cmk[Mehr ...]

. Navigieren Sie nun zu [.guihint]#Site Management# und legen Sie mit [.guihint]#Create New Site# eine {CMK}-Instanz an.
xref:appliance_usage#create_site[Mehr ...] +
Geben Sie mindestens die folgenden Werte ein:

.. [.guihint]#Unique site ID:# Name der Instanz
.. [.guihint]#Version:# Version von {CMK}
.. [.guihint]#Login for the administrator:# Admin-Benutzername
.. [.guihint]#Password for administrator:# Admin-Passwort

. Nun können Sie sich an der {CMK}-Instanz anmelden -- einfach den Instanznamen an die URL von oben anhängen: `\http://&lt;ipaddress&gt;/&lt;siteid&gt;/`

{CMK} steht nun für Sie bereit!
Erfahren Sie im xref:checkmk_getting_started#[Schnelleinstieg ins Monitoring,] wie es weiter geht.

Für den produktiven Betrieb sollten Sie freilich weitere Einstellungen vornehmen, beispielsweise für Namensauflösungen, Kommunikation per E-Mail, Verschlüsselung etc.
Alles Weitere erfahren Sie im xref:appliance_usage#[Hauptartikel zur Appliance.]
