### ---Der Übersicht halber etwas Struktur:---

### ----------------------------------------------------------------------------------------------------------------
### ----------------------------------------------------------------------------------------------------------------
### ----------------------------------------------------------------------------------------------------------------
	TAG
### ----------------------------------------------------------------------------------------------------------------
### ----------------------------------------------------------------------------------------------------------------
	SLOT
### ----------------------------------------------------------------------------------------------------------------
	UNTERPUNKTE
	THEMEN


### ----------------------------------------------------------------------------------------------------------------
### ----------------------------------------------------------------------------------------------------------------
### ----------------------------------------------------------------------------------------------------------------
== Tag 1

SI:Übersicht Tag 1
SI:Vorstellung
SI:(CMK) im Überblick
SI:Einführung und Installation
SI:Der (CMK)-Agent Teil 1
SI:Arbeiten mit WATO Teil 1

### -------------------------------------------------------------------                                                                                                  ---------------------------------------------
### ----------------------------------------------------------------------------------------------------------------
=== Tag 1 - Slot 1: Vorstellung

IN:introduction                                Vorstellung
IN:introduction                                Das Checkmk-Handbuch
IN:training_cmk1                            Schulungsunterlagen

### ----------------------------------------------------------------------------------------------------------------
DO:Die Teilnehmer und der Dozent stellen sich vor.
DO:Alle tragen sich in die Teilnehmerliste ein bzw. unterschreiben
DO:den Eintrag, der schon für sie vorbereitet ist.
DO:

SI:Vorstellung

DO:Das (CMK)-Handbuch
DO:Kurze Erläuterung zum Handbuch: Was, Wo, Wie
DO:

SI:Tag 1 - Slot 1 - Unterpunkt 2: Das (CMK)-Handbuch
SI:Grundlagen in Kapiteln 1 bis 3
SI:Schritt-für-Schritt-Anleitungen

### ----------------------------------------------------------------------------------------------------------------
DO:Schulungsunterlagen
DO:Aufbau der Unterlagen
DO:Verknüpfung zum Handbuch
DO:

COMMENT[ML: Ich habe das mal als Prototyp aus Deiner Mail mitgenommen - für uns zur Orientierung, in der Praxis stirbt dieser Wunsch recht schnell ;)]
SI:Tag 1 - Slot 1 - Unterpunkt 3: Schulungsunterlagen
SI:Aufbau: Tag - Slot - Thema - Theorie - Praxis - Live
SI:Tag: 4 Slots à 90 Minuten
SI:Slot: ca. 3 Unterpunkte à 30 Minuten
SI:Unterpunkt: ca. 3 Themen à 10 Minuten


### ----------------------------------------------------------------------------------------------------------------
### ----------------------------------------------------------------------------------------------------------------
=== (CMK) im Überblick

IN:cmc						Vorhandene Komponenten
IN:monitoring_basics	Das Datenmodell: Hosts und Services, Zustände, Checks
IN:monitoring_basics#checkintervall	Check-Intervall, -Versuche und -Perioden	

### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 2 - Unterpunkt 1: Vorhandene Komponenten - Themen
SI:Monitoring-Kern
SI:(CMK) Micro Core

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 2 - Unterpunkt 1 - Thema 1 - Theorie: Monitoring-Kern
SI:Anstoßen von  Checks und Sammeln der Ergebnisse
SI:Daten für die GUI bereitstellen
SI: Erkennen Änderungen und Alarmierung

DO:Vorhandene Komponenten
DO:Grafischer Überblick über die Komponenten
DO:

###SI:Tag 1 - Slot 2 - Uterpunkt 1 - Thema 1 - Praxis:Monitoring-Kern
###SI:
###SI:

###Statt "schriftlicher Praxis" hier ein Bild.

SB:cee_architecture.png

DO:Vorhandene Komponenten
DO:Vorteile des CMS in Zahlen
DO:

SI:Tag 1 - Slot 2 - Unterpunkt 1 - Thema 2 - Theorie: (CMK) Micro Core
SI:Effizienz: 600.000 Checks pro Minute
SI:20.000 Hosts und 600.000 Services in 0,5 Sekunden
SI:Konfiguration im laufenden Betrieb
SI:Availability-Abfragen ohne Wartezeit
SI:Downtimes, Quittierungen und mehr

DO:Vorhandene Komponenten
DO:CPU Load Nagios vs. CMC
DO:Flughafen MUC: 730 Hosts, 18.000 Services
DO:

###SI:Tag 1 - Slot 2 - unterpunkt 1 - Thema 2 - Praxis: (CMK) Micro Core
###SI:
###SI:

###Statt "schriftlicher Praxis" hier ein Bild.

SB:cmc-migration-cpuload2.png

### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 2 - Unterpunkt 2: Das Datenmodell - Themen
SI:Zustände und Ereignisse
SI:Hosts, Services und Checks

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 2 - Unterpunkt 2 - Thema 1 - Theorie: Zustände und Ereignisse
SI:Ereignis/Event:  einmaliges Geschehen
SI:Beispiel: Timeout bei Zugriff auf Host X (Event Log)
SI:Zustand: anhaltende Situation
SI:Beispiel: Host X ist online (regelmäßiger Ping)
SI:(CMK) beherrscht beides, Standard sind Zustände

DO:Dummy
DO:Dummy
DO:

###SI:Tag 1 - Slot 2 - Unterpunkt 2 - Thema 1 - Praxis: Zustände und Ereignisse
###SI:Zustände: Tactical Overview/Hosts
###SI:Ereignisse: Tactical Overview/Events & Event Console

###Statt "schriftlicher Praxis" hier ein Bild - events neben zuständen.

SB:dummy.png


DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 2 - Unterpunkt 2 - Thema 2 - Theorie: Hosts, Services und Checks
SI:Hosts: Server, Netzwerkgerät, Cluster, alles mit IP
SI:Zustände: [UP], [DOWN], [UNREACH], [PEND]
SI:Services:Jede Eigenschaft eines Hosts --> Check -->
SI:Zustände: [OK], [WARN], [CRIT], [UNKNOWN], [PEND]


DO:Dummy
DO:Dummy
DO:

###SI:Tag 1 - Slot 2 - Unterpunkt 2 - Thema 2 - Praxis: Hosts und Services
###SI:foobar123

###Statt "schriftlicher Praxis" hier ein Bild - Hosts-/Services-Übersicht.

SB:dummy.png


### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

COMMENT[ML: Unterpunkt 3 kürze ich hier (testweise) auf eine einzige Folie - die Standardstruktur steht aber noch auskommentiert im Text.]
SI:Tag 1 - Slot 2 - Unterpunkt 3: Check-Intervall, -Versuch, -Periode - Themen
SI:Intervall: Wie regelmäßig? Standard: 1 Min.
SI:Versuche: Wie oft für eine Zustandsänderung?
SI:Periode: Wann? Standard: 24/7 

###DO:Dummy
###DO:Dummy
###DO:

###SI:Tag 1 - Slot 2 - Unterpunkt 3 - Thema 1 - Theorie: Check-Intervalle
###SI:foobar123

###DO:Dummy
###DO:Dummy
###DO:

###SI:Tag 1 - Slot 2 - Unterpunkt 3 - Thema 1 - Praxis: Check-Intervalle
###SI:foobar123

###DO:Dummy
###DO:Dummy
###DO:

###SI:Tag 1 - Slot 2 - Unterpunkt 3 - Thema 2 - Theorie: Check-Versuche
###SI:foobar123

###DO:Dummy
###DO:Dummy
###DO:

###SI:Tag 1 - Slot 2 - Unterpunkt 3 - Thema 2 - Praxis: Check-Versuche
###SI:foobar123

###DO:Dummy
###DO:Dummy
###DO:

###SI:Tag 1 - Slot 2 - Unterpunkt 3 - Thema 3 - Theorie: Check-Perioden
###SI:foobar123

###DO:Dummy
###DO:Dummy
###DO:

###SI:Tag 1 - Slot 2 - Unterpunkt 3 - Thema 3 - Praxis: Check-Perioden
###SI:foobar123

###DO:Dummy
###DO:Dummy
###DO:



### ----------------------------------------------------------------------------------------------------------------
### ----------------------------------------------------------------------------------------------------------------
=== Einführung und Installation

IN:install_packages                     Installation von Checkmk
IN:introduction_packages                Instanzen erzeugen und verwalten
IN:introduction_virt1                   Die virtuelle Appliance Checkmk virt1
IN:omd_basics#backup                    Backup und Restore
IN:update#detailed                      Softwareupdate von Checkmk

### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 1: Installation von (CMK) - Themen
SI:Die richtige Version
SI:Paket installieren

COMMENT[ML: Alle Themen-Folien auf zwei Folien zusammengefasst.]
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 1 - Thema 1 - Theorie: Die richtige Version
SI:Letzte stabile Version -- 	1.4.0p34
SI:Passende Distribution -- Debian 9.0 stretch
SI:Ältere Versionen: Architektur (32/64 Bit)

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 1 - Thema 1 - Praxis: Die richtige Version
SI:Download des Pakets mit *wget*
SI:Installation von *gdebi*
SI:Import (CMK)-Schlüssel mit *gpg* und *apt-key*
SI:Installation (CMK) mit *gdebi*

###DO:Dummy
###DO:Dummy
###DO:

###SI:Tag 1 - Slot 3 - Unterpunkt 1 - Thema 2 - Theorie: Paket installieren
###SI:foobar123

###DO:Dummy
###DO:Dummy
###DO:

###SI:Tag 1 - Slot 3 - Unterpunkt 1 - Thema 2 - Praxis: Paket installieren
###SI:foobar123

### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 2: Instanzen erzeugen und verwalten - Themen
SI:Monitoring-Instanz (Site) erzeugen und starten
SI:Anmeldung an der Web-Oberfläche

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 2 - Thema 1 - Theorie: Instanzen erzeugen und starten
SI:Instanz mit omd erzeugen
SI:Generiertes Passwort ändern
SI:Instanz starten

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 2 - Thema 1 - Praxis: Instanzen erzeugen und starten
SI:`omd create mysite`
SI:`su - mysite`
SI:`htpasswd -m ~/etc/htpasswd`
SI:`omd start mysite`

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 2 - Thema 2 - Theorie: Anmeldung an Weboberfläche
SI:Zweck der GUI: Ansicht und Konfiguration mit WATO
SI:URL: localhost/mysite
SI:Login: cmkadmin, gesetztes Passwort

DO:Dummy
DO:Dummy
DO:

##SI:Tag 1 - Slot 3 - Unterpunkt 2 - Thema 2 - Praxis: Anmeldung an Weboberfläche
##SI:foobar123

###Statt "schriftlicher Praxis" hier ein Bild - Screen von Login im Browser.

SB:login.png


### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 3: Die virtuelle Appliance - Themen
SI:Funktionen der (CMK) virt1
SI:(CMK) virt1 aufsetzen

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 3 - Thema 1 - Theorie: Funktionen der (CMK) virt1
SI:Plattformunabhängiges OVA-Format
SI:Import in VirtualBox und VMWare ESXi
SI:Sinnvoll ab ca. 1.500 Hosts/30.000 Services
SI:Verwaltung von Installationen/Instanzen

DO:Dummy
DO:Dummy
DO:

###SI:Tag 1 - Slot 3 - Unterpunkt 3 - Thema 1 - Praxis: Funktionen der (CMK) virt1
###SI:foobar123

###Statt "schriftlicher Praxis" hier ein Bild - Screen von Appliance-Web-Oberfläche.

SB:cma_webconf_index.png

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 3 - Thema 2 - Theorie: (CMK) virt1 aufsetzen
SI:Import in VM-Manager
SI:Einstellungen über virt1-Konsole
SI:Verwaltung über virt1-Weboberfläche

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 3 - Thema 2 - Praxis: (CMK) virt1 aufsetzen
SI:Anleitung für VirtualBox: Seite 123
SI:Anleitung für VMWare ESXi: Seite 321


### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 4: Backup und Restore - Themen
SI:Backup und Restore

DO:Dummy
DO:Dummy
DO:

SI: Tag 1 - Slot 3 - Unterpunkt 4 - Thema 1 - Theorie: Backup und Restore
SI:Sicherung ganzer Instanzen
SI:Über Kommandozeile/Skripte
SI:Ab Version 1.4.0 über WATO
SI:WATO-Backup-Modul ersetzt Snapshots

DO:Dummy
DO:Dummy
DO:

SI: Tag 1 - Slot 3 - Unterpunkt 4 - Thema 1 - Praxis: Backup und Restore
SI:{{WATO => Backup}}# 
SI:Schlüssel erzeugen
SI:Ziele anlegen
SI:Backup-Jobs anlegen


### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 5: Softwareupdate von (CMK) - Themen
SI:Installation neuer Versionen
SI:Durchführung des Updates

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 5 - Thema 1 - Theorie: Installation neuer Versionen
SI:(CMK) erlaubt mehrere Versionen parallel
SI:Jede Instanz mit eigener (CMK)-Version

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 5 - Thema 1 - Praxis: Installation neuer Versionen
SI:Neues (CMK)-Paket installieren
SI:(CMK)-Versionen listen: [.guihints]#omd versions}}# 
SI:Instanzen mit Versionen listen: [.guihints]#omd sites}}# 

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 3 - Unterpunkt 5 - Thema 2 - Theorie: Durchführung des Updates
SI:Update als Root oder Instanz-Benutzer
SI:Update an Instanz-Kopie testen
SI:Änderungen an Konfigurationsdateien bleiben erhalten

DO:Dummy
DO:Dummy
DO:

###SI:Tag 1 - Slot 3 - Unterpunkt 5 - Thema 2 - Praxis: Durchführung des Updates
###SI:foobar123

###Statt "schriftlicher Praxis" hier ein Bild - Screen von Update-Dialog.

SB:omd-update-2.png

DO:Dummy
DO:Dummy
DO:


### ----------------------------------------------------------------------------------------------------------------
### ----------------------------------------------------------------------------------------------------------------
=== Der (CMK)-Agent Teil 1

IN:wato_monitoringagents                Agententypen
IN:agent_linux                          Überwachen von Linux
IN:agent_windows                        Überwachen von Windows

### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 4 - Unterpunkt 1: Agententypen - Themen
SI:Verschiedene Agenten
SI:Der (CMK)-Agent

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 4 - Unterpunkt 1 - Thema 1 - Theorie: Verschiedene Agenten
SI:SNMP (Netzwerkgeräte)
SI:(CMK)-Agent (Server, Workstations)
SI:Spezial-Agent (Management-APIs)
SI:Active Checks (Netzwerkdienste über Plugins)

DO:Dummy
DO:Dummy
DO:

###SI: Tag 1 - Slot 4 - Unterpunkt 1 - Thema 1 - Praxis: Verschiedene Agenten
###SI:foobar123

###Statt "schriftlicher Praxis" hier ein Bild.

SB:agent_access.png

DO:Dummy
DO:Dummy
DO:

SI: Tag 1 - Slot 4 - Unterpunkt 1 - Thema 2 - Theorie: Der (CMK)-Agent
SI:Verfügbar für 11 Betriebssysteme
SI:Agent horcht passiv auf TCP Port 6556
SI:Verschickt erst auf Host-Anfrage Daten
SI:Liefert zum Beispiel CPU, Speicher, Prozesse, Dateisysteme, lokale Checks, Netzwerkdaten

DO:Dummy
DO:Dummy
DO:


COMMENT:[ML:Alternativ Bild von Agenten-Seite in GUI.]
SI: Tag 1 - Slot 4 - Unterpunkt 1 - Thema 2 - Praxis: Der (CMK)-Agent
SI:Formate: TGZ, DEB, RPM, MSI
SI:Per Browser: [.guihints]#WATO => Monitoring Agents}}# 
SI:Per HTTP: [.guihints]#.../mysite/check_mk/agents/...}}# 
SI:Manuelle Installation: Handbuch Seite 123




### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 4 - Unterpunkt 2: Der Linux-Agent - Themen
SI:Eigenschaften
SI:Standard-Installation und Test

DO:Dummy
DO:Dummy
DO:

SI: Tag 1 - Slot 4  - Unterpunkt 2 - Thema 1 - Theorie: Eigenschaften 
SI:Minimalistisch: Wenig RAM, CPU, Speicherplatz
SI:Transparent: Simples Shellskript
SI:Sicher: Keine Zugriffe aus Netzwerk
SI:Datentransport: xinetd, systemd, ssh
SI:Erweiterbar mit Plugins

DO:Dummy
DO:Dummy
DO:

###SI:Tag 1 - Slot 4  - Unterpunkt 2 - Thema 1 - Praxis: Eigenschaften
###SI:foobar123

###Statt "schriftlicher Praxis" hier ein Bild.

SB:agent_files.jpg

DO:Dummy
DO:Dummy
DO:

SI: Tag 1 - Slot 4  - Unterpunkt 2 - Thema 2 - Theorie: Standard-Installation und Test
SI:DEB-Paket über [.guihints]#WATO => Monitoring Agents# herunterladen
SI:DEB-Paket über lokalen Paketmanager installieren
SI:Agent und Zugriff vom Host testen

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 4  - Unterpunkt 2 - Thema 2 - Praxis: Standard-Installation und Test
SI:Test Agentenausgabe: `check_mk_agent`
SI:Test Host-Zugriff: `nc myhost 6556`
SI:Host-Diagnose über WATO: [.guihints]#WATO => Hosts => myhost => Diagnostic}}# 


### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 4 - Unterpunkt 3: Der Windows-Agent - Themen
SI:Eigenschaften
SI:Standard-Installation und Test

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 4 - Unterpunkt 3 - Thema 1 - Theorie: Eigenschaften
SI:Ausführbare Datei (EXE, portabel)
SI:Kompatibel zu MinGW
SI:Monitoring von Eventlogs
SI:Sicherheit: Kein Zugriff aus dem Netzwerk
SI:Erweiterbar mit Plugins

DO:Dummy
DO:Dummy
DO:

###SI:Tag 1 - Slot 4 - Unterpunkt 3 - Thema 1 - Praxis: Eigenschaften
###SI:foobar123

###Statt "schriftlicher Praxis" hier ein Bild - Windows-Agent-Files-Screen.

SB:dummy.png

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 4 - Unterpunkt 3 - Thema 2 - Theorie: Standard-Intallation und Test
SI:MSI-Paket über [.guihints]#WATO => Monitoring Agents# herunterladen
SI:MSI-Paket unter Windows installieren
SI:Agent und Zugriff vom Host testen

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 4 - Unterpunkt 3 - Thema 2 - Praxis: Standard-Installation und Test
SI:Test Agentenausgabe: `check_mk_agent test`
SI:Test Host-Zugriff: `nc myhost 6556`
SI:Host-Diagnose über WATO: [.guihints]#WATO => Hosts => myhost => Diagnostic}}# 


### ----------------------------------------------------------------------------------------------------------------
### ----------------------------------------------------------------------------------------------------------------
=== Arbeiten mit WATO Teil 1

IN:wato_hosts#create_hosts              Aufnehmen von Hosts und Services in das Monitoring
IN:wato_services#discovery              Automatische Erkennung der zu überwachenden Services

### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 5 - Unterpunkt 1: Aufnehmen von Hosts und Services - Themen
SI:Einzelnen Host hinzufügen
SI:Viele Hosts hinzufügen

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 5 - Unterpunkt 1 - Thema 1 - Theorie: Einzelnen Host hinzufügen 
SI:foobar123

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 5 - Unterpunkt 1 - Thema 1 - Praxis: Einzelnen Host hinzufügen 
SI:foobar123

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 5 - Unterpunkt 1 - Thema 2 - Theorie: Viele Hosts hinzufügen
SI:foobar123

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 5 - Unterpunkt 1 - Thema 2 - Praxis: Viele Hosts hinzufügen
SI:foobar123

### ----------------------------------------------------------------------------------------------------------------
DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 5 - Unterpunkt 2: Automatische Erkennung der zu überwachenden Services - Themen
SI:Services ins Monitoring aufnehmen
SI:Services automatisch erkennen
SI:Services für viele Hosts erkennen

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 5 - Unterpunkt 2 - Thema 1 - Theorie: Services ins Monitoring aufnhemen
SI:foobar123

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 5 - Unterpunkt 2 - Thema 1 - Praxis: Services ins Monitoring aufnehmen
SI:foobar123

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 5 - Unterpunkt 2 - Thema 2 - Theorie: Services automatisch erkennen
SI:foobar123

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 5 - Unterpunkt 2 - Thema 2 - Praxis: Services automatisch erkennen
SI:foobar123

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 5 - Unterpunkt 2 - Thema 3 - Theorie: Services für viele Hosts erkennen
SI:foobar123

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 - Slot 5 - Unterpunkt 2 - Thema 3 - Praxis: Services für viele Hosts erkennen
SI:foobar123

DO:Dummy
DO:Dummy
DO:

### ----------------------------------------------------------------------------------------------------------------
### ----------------------------------------------------------------------------------------------------------------
### ----------------------------------------------------------------------------------------------------------------
###H1: Tag 2







= Systemmonitoring mit Checkmk - Teil 1: Grundlagen