= (CMK)-Editionen
:revdate: draft
[.seealso][#install_packages]MT:Die vier Editionen von (CMK)

Bevor Sie beginnen, (CMK) zu installieren, haben Sie erst mal die Auswahl,
welche _Edition_ von (CMK) Sie einsetzen möchten. Davon gibt es
vier verschiedene:

Die (CRE) (*CRE*) ist kostenlos und zu 100&nbsp;%
Open Source und enthält Nagios als Kern.  Sie können damit komplexe
Umgebungen umfassend überwachen. Support erhalten Sie in unserem
<a href="https://forum.checkmk.com">Forum</a> von der (CMK)-Community.

Die (CSE) (*CEE*) richtet sich vor allem an professionelle
Anwender und bietet über den Umfang der (RE) hinaus eine Reihe
von interessanten Features, wie z.B. einen sehr performanten eigenen
Kern, der Nagios ersetzt, ein Reporting, ein ausgefeiltes System für die
Visualisierung von Messwerten, ein flexibles Agent-Deployment und vieles
mehr. Für die (SE) erhalten Sie von uns und unseren <a
href="https://checkmk.de/find-a-partner.html">Partnern</a> professionellen
Support.  Eine Aufstellung der wichtigsten Unterschiede zur (RE)
finden Sie auf unserer <a href="https://checkmk.de/editions.html">Homepage</a>.

Die (CFE) (*CFE*) ist für Sie die richtige, wenn Sie
die (SE) erst mal unverbindlich testen wollen oder wenn Sie (CMK)
im kleinen Rahmen mit bis zu zwei Instanzen mit je zehn überwachten Hosts
einsetzen möchten. Die (FE)
enthält alle Features der (SE) und ist kostenlos. Sowohl
die (FE) als auch die (RE) können Sie später ohne Umwege direkt
auf die (SE) upgraden.

Die (CME) (*CME*) ist für Sie die richtige Edition,
wenn Sie Dienste wie einen Managed-Service-Provider anbieten. Sie ist eine
mandantenfähige Erweiterung der (SE).

[CEE] Immer wenn wir in diesem Handbuch Funktionen besprechen, die nur für eine
der (EE) gelten -- also für die CEE, CFE oder CME -- kennenzeichnen wir dies
hier entsprechend.