// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Willkommen bei {CMK}
:revdate: draft
:title: Willkommen bei {CMK}
:description: Jedes Handbuch erfodert eine bestimmte Nutzung. Hier wird erklärt, wie das Handbuch zu {CMK} aufgebaut ist, damit Sie die relevanten Inhalte schnell finden.
:no-toc:

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
{related-end}

////
TK:
    Problem der Überschriften in diesem Artikel: Diese "neue" Gliederung ist wieder eine andere, als die der Handbuchkapitel. Und es werden auch nicht alle Handbuchkapitel vorgestellt.
    Ich kann verstehen, wieso Du das so machst, finde es aber schwierig statt der bisherigen Struktur 2 neue anzubieten. Ich hab jetzt aber nix verändert. 
    Eine (auch nicht schöne) Möglichkeit wäre es, in den Kapiteln 2-4 die Handbuchkapitel namentlich zu nennen, damit man sich besser zurechtfindet.
MA:
    Wie ist der jetzige Ansatz?
////
// TK: Wäre schön, am Ende den Bogen zurück in den Leitfaden zu schlagen und diesen zu verlinken, damit man gleich loslegen kann.
// MA: Ich hab das mal direkt in den Teil für den Leitfaden hinzugefügt. Am Ende wäre es doch etwas aus dem Kontext gerissen.

*Liebe Leserinnen und Leser,*

wir freuen uns, dass Sie den Weg zu {CMK} gefunden haben.

{CMK} bietet als Monitoring-Software umfassende und spezialisierte Möglichkeiten,
mit den sehr unterschiedlichen Rahmenbedingungen von IT-Infrastrukturen umzugehen.
Das erfordert zwangsläufig auch eine sehr umfassende Dokumentation,
die über die reine Beschreibung des Offensichtlichen hinausgeht.
Dieses Handbuch soll Sie so gut wie möglich dabei unterstützen,
{CMK} besser zu verstehen, mit {CMK} Ihre Anforderungen umzusetzen, aber auch neue Lösungswege zu entdecken.

Um den Umgang mit {CMK} so einfach wie möglich zu gestalten,
verfolgen die Artikel dieses Handbuchs an vielen Stellen eher ungewöhnliche Herangehensweisen.
Es geht dabei fast nie nur darum, eine vorgefertigte Abfolge von Einzelnschritten nachzumachen.
Vielmehr soll es Ihnen als Leser oder Leserin ein tieferes Verständnis eines Features in {CMK} zu vermitteln.

Wenn man es kurz zusammenfasst, ist unsere wichtigste Prämisse: Das Handbuch soll hilfreich sein.
Und hilfreich ist es dann, wenn man die Beschreibung in die Lösung eines eigenen Problems übersetzen kann.
// TK: Das "ungewöhnlich" gefällt mir noch nicht: Sind wir wirklich so ungewöhnlich?
// MA: Hab die Vorschläge in abgewandelter Form weitgehend übernommen. Wegen der Frage: Ist unsere Form der Dokumentation denn so üblich?

Unter anderem auch aus diesem Grund ist das Handbuch in mehrere Bereiche unterteilt,
obwohl sie fließend ineinander übergehen.
Mit dieser Unterteilung wollen wir es einfacher machen,
die von Ihnen gesuchten Inhalte schneller zu finden.
Die folgenden Themen finden Sie in den Kapiteln des Handbuchs wieder.


[discrete]
== Leitfaden für Einsteiger

Jeder fängt einmal mit {CMK} an.
Da Sie sehr viele Möglichkeiten und Funktionen geboten bekommen,
fällt es am Anfang manchmal schwer, sich in den ersten Schritten zurechtzufinden.
Wir wollen daher den Einstieg in die Welt von {CMK} einfach machen,
indem wir Sie direkt am Anfang Schritt für Schritt bei Ihrer ersten Instanz unterstützen und
in die wichtigstens Konzepte erführen.

Dieser Teil des Handbuchs eignet also sich sehr gut,
um ihn linear von Anfang bis Ende durchzulesen.
Sollten Sie das erste Mal dieses Handbuch lesen,
können Sie auch direkt mit xref:intro_setup#[dem ersten Artikel aus dem Leitfaden] einsteigen und
gegebenenfalls später zu der Beschreibung der weiterführenden Kapitel zurückkehren.


[discrete]
== Aufgaben für Administratoren und Benutzer

Der Hauptteil erklärt von Kapitel 3 bis 10 dann die Funktionen und deren Nutzung in {CMK}.
Sei es, dass Sie {CMK} erstmalig installieren wollen, Fragen zur Konfiguration haben oder
wissen möchten, wie man die Daten effizient und nützlich anzeigt.

Aus diesem Grund eignen sich diese Kapitel weniger, um sie von oben nach unten durchzulesen.
Vielmehr sind sie thematisch geordnet und widmen sich unterschiedlichen Aspekten einer jeweiligen Aufgabe.
Innerhalb der Kapitel finden Sie dann wichtige, einleitende oder anderweiteitig priorisierte Artikel immer am Anfang.

// TK: Wo haben wir denn alphabetisch sortiert? Und selbst wenn, würde ich das nicht erwähnen.
// MA: Die einzelnen Benachrichtigungs-Artikel wollten wir alphabetisch sortieren, da die einzelnen Artikel sonst schwer zu finden sind. Ich bin aber heute leicht zu überzeugen und habe es daher rausgenommen.


[discrete]
== Automatisierung und Programmierung

{CMK} lässt sich nicht nur mit einer Web-Oberfläche verwalten, sondern auch über APIs.
Dazu ermöglicht die modulare Softwarearchitektur auch eine umfangreiche Palette an Erweiterungsmöglichkeiten.

Mit den Artikeln, die sich in diesem Kapitel befinden,
liefern wir nach und nach Tipps, Hinweise und Einstiegspunkte,
um {CMK} an die eigene Infrastruktur anzupassen oder die Konfiguration zu automatisieren.
// TK: Vorsicht mit Versprechungen ;-)
// MA: Das Versprechen steht eh schon im Raum... wir haben hier langfristig eh keine andere Wahl.


[discrete]
== Konzepte

Dieses Kapitel ist noch recht neu -- auch wenn die darin enthaltenen Artikel bereits lange im Handbuch vorhanden sind.
Wenn Sie mehr darüber erfahren wollen, wie {CMK} eigentlich funktioniert,
ohne eine direkte Anforderung oder Aufgabe zu verfolgen,
dann sind Sie hier genau richtig.

////
Im Lauf der Zeit werden hier mehr und mehr Artikel entstehen, die das Verständnis um {CMK} erhöhen und
auch eher theoretische Konzepte tiefer beleuchten.
////
// TK: Vorsicht mit Versprechungen, zum 2.
// MA: Da wir hier keinen Druck von außen bekommen, stimme ich da zu.


[discrete]
== Die {CMK}-Appliance

// MA: Da ich die Formulierung von Thomas eleganter finde, habe ich sie 1:1 übernommen.
////
Alle Themen, die die Einrichtung und Nutzung der Appliance betreffen, sind im letzten Kapitel des Handbuchs zu finden.
Eigentlich ein eigenes Handbuch, gibt es doch so viele Überschneidungen mit den anderen Kapiteln,
dass es immer im Kontext von {CMK} zu betrachten ist.

Auch wenn hier also gebündelt alle spezifischen Themen zur Appliance zu finden sind, sollten
Leser und Leserinnen dieses Teils daher auch immer einen Blick in die anderen Kapitel und Artikel
des restlichen Handbuchs werfen.
////

Alle Themen, die die Einrichtung und Nutzung der Appliance betreffen, sind im letzten Kapitel des Handbuchs zu finden.
Eigentlich ist das Appliance-Kapitel ein eigenes Handbuch.
Da die Konzepte von {CMK} aber auch in der Appliance gelten,
sollten Leserinnen und Leser dieses Teils immer auch einen Blick in die anderen Artikel des Handbuchs werfen.
