// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Willkommen bei {CMK}
:revdate: draft
:title: Willkommen bei {CMK}
:description: Jedes Handbuch erfodert eine bestimmte Nutzung. Hier wird erklärt, wie das Handbuch zu {CMK} aufgebaut ist, damit Sie die relevanten Inhalte schnell finden.
:no-toc:

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
{related-end}

////
TK: Grundsätzliches: 
- Ich würde keine nummerierten Überschriften nehmen, sondern alle Überschriften [discrete] voranstellen: Liebe Leserinnen als Level 1 (==) und den die folgenden als Level 2 (===)
- Statt an Deinen Texten rumzukritteln, hab ich ein paarmal einfach meine Version als Kommentar druntergeschrieben.
- Problem der Überschriften in diesem Artikel: Diese "neue" Gliederung ist wieder eine andere, als die der Handbuchkapitel. Und es werden auch nicht alle Handbuchkapitel vorgestellt.
Ich kann verstehen, wieso Du das so machst, finde es aber schwierig statt der bisherigen Struktur 2 neue anzubieten. Ich hab jetzt aber nix verändert. 
Eine (auch nicht schöne) Möglichkeit wäre es, in den Kapiteln 2-4 die Handbuchkapitel namentlich zu nennen, damit man sich besser zurechtfindet.
- Wäre schön, am Ende den Bogen zurück in den Leitfaden zu schlagen und diesen zu verlinken, damit man gleich loslegen kann.
////

// MA: Das wirkt mir immer noch zu ausufernd und nicht auf den Punkt. Auch die Anrede nimmt
// MA: (auf der Startseite) sehr viel Raum ein, den man besser nutzen könnte.
// MA: Daher noch einmal eine zweite Fassung als Kommentar hintenangestellt.
*Liebe Leserinnen und Leser,*

wir freuen uns, dass Sie den Weg zu {CMK} gefunden haben.

Die Rolle des Monitorings wird in der komplexer werdenen Welt der IT-Systeme immer größer.
Gleichzeitig werden die Anforderungen und damit auch die Softwarelösungen immer umfangreicher.
{CMK} bietet hier eine umfassende und detailierte Möglichkeit,
mit den sehr unterschiedlichen Rahmenbedingungen der Infrastrukturen eines Unternehmens umzugehen.
Das erfordert zwangsläufig auch eine sehr umfassende Dokumentation.
Ein Handbuch gehört daher immer dazu und dieses hier soll Sie so gut wie möglich dabei unterstützen,
{CMK} besser zu verstehen, Anforderungen umzusetzen, aber auch neue Lösungswege zu entdecken.

// MA: Zweite, wesentlich kürzere Fassung
////
{CMK} bietet umfassende und detaillierte Möglichkeiten,
als Monitoring-Software mit den sehr unterschiedlichen Rahmenbedingungen von Unternehmens-Infrastrukturen umzugehen.
Das erfordert zwangsläufig auch eine sehr umfassende Dokumentation,
die über die reine Beschreibung des Offensichtlichen hinausgeht.
Dieses Handbuch soll Sie so gut wie möglich dabei unterstützen,
{CMK} besser zu verstehen, Anforderungen umzusetzen, aber auch neue Lösungswege zu entdecken.
////
// TK: 2. Fassung viel besser! Ich würde es noch leicht umschreiben:
////
{CMK} bietet als Monitoring-Software umfassende und spezialisierte Möglichkeiten, mit den sehr unterschiedlichen Rahmenbedingungen von IT-Infrastrukturen umzugehen.
Das erfordert zwangsläufig auch eine sehr umfassende Dokumentation, die über die reine Beschreibung des Offensichtlichen hinausgeht.
Dieses Handbuch soll Sie so gut wie möglich dabei unterstützen, {CMK} besser zu verstehen, mit {CMK} Ihre Anforderungen umzusetzen, aber auch neue Lösungswege zu entdecken.
////
// TK: Unternehmen hab ich rausgenommen: Hat jeder (Raw) User ein Unternehmen?

Um den Umgang mit {CMK} so einfach wie möglich zu gestalten,
verfolgen die Artikel dieses Handbuchs an vielen Stellen eher ungewöhnliche Konzepte und Herangehensweisen.
Immer mit der Absicht, dass Sie als Leser oder Leserin ein tieferes Verständnis eines Features in {CMK} bekommen.
Schließlich kann eine Dokumentation immer nur eine begrenzte Menge an Beispielen liefern.
Gleichzeitig soll aber die Individualität Ihrer Infrastruktur anerkannt und beachtet werden.
Wenn man es kurz zusammenfasst, ist unsere wichtigste Prämisse: Das Handbuch soll hilfreich sein.
Und hilfreich ist etwas immer dann, wenn man es auf die eigenen Fälle übersetzen kann.
////
Um Ihnen den Umgang mit {CMK} so einfach wie möglich zu machen, verfolgen viele Artikel dieses Handbuchs eher ungewöhnliche Herangehensweisen.
Dabei geht fast nie darum, eine vorgefertigte Abfolge von Einzelschritten nachzumachen, sondern darum zu verstehen, wie etwas funktioniert
-- immer mit der Absicht, dass Sie als Leser oder Leserin ein tieferes Verständnis eines Features in {CMK} bekommen.
Wenn man es kurz zusammenfasst, ist unsere wichtigste Prämisse: Das Handbuch soll hilfreich sein.
Hilfreich ist es dann, wenn man die Beschreibung in die Lösung eines eigenen Problems übersetzen kann.
////
// TK: Das "ungewöhnlich" gefällt mir noch nicht: Sind wir wirklich so ungewöhnlich?

Unter anderem auch aus diesem Grund ist das Handbuch in mehrere Bereiche unterteilt,
obwohl sie fließend ineinander übergehen.
Die Unterteilung dient dabei der erweiterten Strukturierung, um es Ihnen einfacher zu machen,
die Inhalte schneller zu finden, die Sie suchen.
Die angesprochene Bereiche sind im Folgenden beschrieben.
////
Auch aus diesem Grund ist das Handbuch in mehrere Bereiche unterteilt, obwohl diese fließend ineinander übergehen.
Mit dieser Unterteilung hoffen wir, dass Sie die Inhalte, die Sie suchen, auch schnell finden.
Die folgenden Themen finden Sie in den Kapiteln des Handbuchs wieder.
////


== Leitfaden für Einsteiger

Jeder fängt einmal mit {CMK} an.
Da Sie sehr viele Möglichkeiten und Funktionen geboten bekommen,
fällt es manchmal auch schwerer, sich in den ersten Schritten zurechtzufinden.
// TK: fallt es am Anfang oft schwer, ...
Wir wollen daher den Einstieg in die Welt von {CMK} einfach machen,
indem wir direkt am Anfang die wichtigstens Konzepte erklären und
praxisorientiert bei der ersten Instanz Schritt für Schritt unterstützen.
// TK: indem wir Sie direkt am Anfang Schritt für Schritt beim Erstellen und Konfigurieren Ihrer ersten {CMK}-Instanz unterstützen -- und dabei nebenbei die wichtigstens Konzepte erklären.

Dieser Teil des Handbuchs eignet also sich sehr gut,
um ihn linear von Anfang bis Ende durchzulesen und durchzuarbeiten.
// TK: um ihn linear von Anfang bis Ende durchzulesen.


== Das umfassende Handbuch für Nutzer und Administratoren
// TK: Aufgaben für Administratoren und Benutzer

Der Hauptteil erklärt dann die Funktionen, Konzepte in {CMK}.
Sei es, dass Sie {CMK} erstmalig installieren wollen, Fragen zur Konfiguration haben oder
wissen möchten, wie man die Daten effizient und nützlich anzeigt.

Aus diesem Grund eignen sich die Kapitel nicht durchgehend, um es von oben nach unten durchzulesen.
Vielmehr sind die Artikel thematisch geordnet. Innerhalb der Kapitel finden Sie wiederum zwei Sortierungen:

* Wichtige, einleitende oder anderweitig priorisierte Artikel befinden sich immer am Anfang.
* Ist eine solche Sortierung nicht sinnvoll, sind die Artikel schlicht alphabetisch gelistet.
////
Im anschließenden Hauptteil erhalten Sie die Informationen, die Sie bennötigen, um Ihre Aufgabe mit {CMK} umzusetzen
-- sei es, dass Sie {CMK} erstmalig installieren wollen, Fragen zur Konfiguration haben oder wissen möchten, wie man die Daten effizient und nützlich anzeigt.

Die einzelnen Artikel widmen sich unterschiedlichen Aspekten der jeweiligen Aufgabe.
Aus diesem Grund eignen sie sich weniger, um sie von oben nach unten durchzulesen.
Innerhalb der Kapitel finden Sie wichtige, einleitende oder anderweitig priorisierte Artikel immer am Anfang.
////
// TK: Wo haben wir denn alphabetisch sortiert? Und selbst wenn, würde ich das nicht erwähnen.


== Dokumentation, wie {CMK} erweitert werden kann
// TK: Mehr aus {CMK} machen

{CMK} lässt sich nicht nur mit einer Web-Oberfläche verwalten, sondern auch über APIs.
Dazu ermöglicht die modulare Softwarearchitektur auch eine umfangreiche Palette an Erweiterungsmöglichkeiten.

Mit den Artikeln, die sich unter _Automatisierung und Programmierung_ befinden,
liefern wir nach und nach immer mehr Tipps, Hinweise und Einstiegspunkte,
um {CMK} an die eigene Infrastruktur anzupassen oder die Konfiguration zu automatisieren.
// TK: Vorsicht mit Versprechungen ;-)


== Wie funktioniert eigentlich {CMK}?
// TK: Wie auch bei der nächsten Überschrift hier besser den Kapitelnamen "Konzepte" verwenden und das "Wie funktioniert eigentlich {CMK}?" in den Text ziehen.

Dieses Kapitel ist noch recht neu -- auch wenn die darin enthaltenen Artikel bereits lange im Handbuch vorhanden sind.
Wenn Sie mehr über {CMK} erfahren wollen, ohne eine direkte Anforderung oder Aufgabe zu verfolgen,
dann sind Sie hier genau richtig.

Im Lauf der Zeit werden hier mehr und mehr Artikel entstehen, die das Verständnis um {CMK} erhöhen und
auch eher theoretische Konzepte tiefer beleuchten.
// TK: Vorsicht mit Versprechungen, zum 2.


== Das Handbuch für Nutzer der Appliance
// TK: Die {CMK}-Appliance
// TK: Wenn es schon ein 1:1 Mapping gibt, das auch den Titel des Handbuchkapitels verwenden.

Alle Themen, die die Einrichtung und Nutzung der Appliance betreffen, sind im letzten Kapitel des Handbuchs zu finden.
Eigentlich ein eigenes Handbuch, gibt es doch so viele Überschneidungen mit den anderen Kapiteln,
dass es immer im Kontext von {CMK} zu betrachten ist.

Auch wenn hier also gebündelt alle spezifischen Themen zur Appliance zu finden sind, sollten
Leser und Leserinnen dieses Teils daher auch immer einen Blick in die anderen Kapitel und Artikel
des restlichen Handbuchs werfen.
////
Alle Themen, die die Einrichtung und Nutzung der Appliance betreffen, sind im letzten Kapitel des Handbuchs zu finden.
Eigentlich ist das Appliance-Kapitel ein eigenes Handbuch.
Da die Konzepte von {CMK} aber auch in der Appliance gelten, sollten Leserinnen und Leser dieses Teils auch immer einen Blick in die anderen Artikel des Handbuchs werfen.
////
