// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Willkommen bei {CMK}
:revdate: 2022-04-06
:title: Willkommen bei {CMK}
:description: Jedes Handbuch erfodert eine bestimmte Nutzung. Hier wird erklärt, wie das Handbuch zu {CMK} aufgebaut ist, damit Sie die relevanten Inhalte schnell finden.
:no-toc:

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
{related-end}


// MA: Das wirkt mir immer noch zu ausufernd und nicht auf den Punkt. Auch die Anrede nimmt
// MA: (auf der Startseite) sehr viel Raum ein, den man besser nutzen könnte.
// MA: Daher noch einmal eine zweite Fassung als Kommentar hintenangestellt.
*Liebe Leserinnen und Leser,*

wir freuen uns, dass Sie den Weg zu {CMK} gefunden haben.

Die Rolle des Monitorings wird in der komplexer werdenen Welt der IT-Systeme immer größer.
Gleichzeitig werden die Anforderungen und damit auch die Softwarelösungen immer umfangreicher.
{CMK} bietet hier eine umfassende und detailierte Möglichkeit,
mit den sehr unterschiedlichen Rahmenbedingungen der Infrastrukturen eines Unternehmens umzugehen.
Das erfordert zwangsläufig auch eine sehr umfassende Dokumentation.
Ein Handbuch gehört daher immer dazu und dieses hier soll Sie so gut wie möglich dabei unterstützen,
{CMK} besser zu verstehen, Anforderungen umzusetzen, aber auch neue Lösungswege zu entdecken.

// MA: Zweite, wesentlich kürzere Fassung
////
{CMK} bietet umfassende und detailierte Möglichkeiten,
als Montioring-Software mit den sehr unterschiedlichen Rahmenbedingungen von Unternehmens-Infrastrukturen umzugehen.
Das erfordert zwangsläufig auch eine sehr umfassende Dokumentation,
die über die reine Beschreibung des offensichtlichen hinausgeht.
Dieses Handbuch soll Sie so gut wie möglich dabei unterstützen,
{CMK} besser zu verstehen, Anforderungen umzusetzen, aber auch neue Lösungswege zu entdecken.
////

Um den Umgang mit {CMK} so einfach, wie möglich zu gestalten,
verfolgen die Artikel dieses Handbuchs an vielen Stellen eher ungewöhnliche Konzepte und Herangehensweisen.
Immer mit der Absicht, dass Sie als Leser oder Leserin ein tieferes Verständnis eines Features in {CMK} bekommen.
Schließlich kann eine Dokumentation immer nur eine begrenzte Menge an Beispielen liefern.
Gleichzeitig soll aber die Individualität Ihrer Infrastruktur anerkannt und beachtet werden.
Wenn man es kurz zusammenfasst, ist unsere wichtigste Prämisse: Das Handbuch soll hilfreich sein.
Und hilfreich ist etwas immer dann, wenn man es auf die eigenen Fälle übersetzen kann.

Unter anderem auch aus diesem Grund ist das Handbuch in mehrere Bereiche unterteilt,
obwohl sie fließend ineinander übergeben.
Die Unterteilung dient dabei der erweiterten Strukturierung, um es Ihnen einfacher zu machen,
die Inhalte schneller zu finden, die Sie suchen.
Die angesprochene Bereiche sind im Folgenden beschrieben.


== Leitfaden für Einsteiger

Jeder fängt einmal mit {CMK} an.
Da Sie sehr viele Möglichkeiten und Funktionen geboten bekommen,
fällt es manchmal auch schwerer, sich in den ersten Schritten zurechtzufinden.
Wir wollen daher den Einstieg in die Welt von {CMK} einfach machen,
indem wir direkt am Anfang die wichtigstens Konzepte erklären und
praxisorientiert bei der ersten Instanz Schritt für Schritt unterstützen.

Dieser Teil des Handbuchs eignet also sich sehr gut,
um ihn linear von Anfang bis Ende durchzulesen und durchzuarbeiten.


== Das umfassende Handbuch für Nutzer und Administratoren

Der Hauptteil erklärt dann die Funktionen, Konzepte in {CMK}.
Sei es, dass Sie {CMK} erstmalig installieren wollen, Fragen zur Konfiguration haben oder
wissen möchten, wie man die Daten effizient und nützlich anzeigt.

Aus diesem Grund eignen sich die Kapitel nicht durchgehend, um es von oben nach unten durchzulesen.
Vielmehr sind die Artikel thematisch geordnet. Innerhalb der Kapitel finden Sie wiederum zwei Sortierungen:
* Wichtige, einleitende oder anderweitig priorisierte Artikel befinden sich immer am Anfang.
* Ist eine solche Sortierung nicht sinnvoll, sind die Artikel schlicht alphabetisch gelistet.


== Dokumentation, wie {CMK} erweitert werden kann

{CMK} lässt sich nicht nur einer Web-Oberfläche verwalten, sondern auch über APIs.
Dazu ermöglichst die modulare Softwarearchitektur auch eine umfangreiche Palette an Erweiterungsmöglichkeiten.

Mit den Artikeln, die sich unter _"Automatisierung und Programmierung_ befinden,
liefern wir nach und nach immer mehr Tipps, Hinweise und Einstiegspunkte,
um {CMK} an die eigene Infrastruktur anzupassen oder die Konfiguration zu automatisieren.

== Wie funktioniert eigentlich {CMK}?

Dieser Abschnitt ist noch recht neu -- auch wenn die Artikel bereits lange im Handbuch vorhanden sind.
Wenn Sie mehr über {CMK} erfahren wollen, ohne eine direkte Anforderung oder Aufgabe zu verfolgen,
dann sind Sie hier genau richtig.

Im Lauf der Zeit, werden hier mehr und mehr Artikel entstehen, die das Verständnis um {CMK} erhöhen und
auch eher theoretische Konzepte tiefer beleuchten.


== Das Handbuch für Nutzer der Appliance

Alle Themen, die konkret die Einrichtung und Nutzung der Appliance betreffen, sind in diesem, letzten Kapitel zu finden.
Eigentlich ein eigenes Handbuch, gibt es doch so viele Überschneidungen mit den anderen Kapiteln,
dass es immer im Kontext von {CMK} zu betrachten ist.

Auch wenn hier also gebündelt alle spezifischen Themen zur Appliance zu finden sind, sollten
Leser und Leserinnen dieses Teils daher auch immer einen Blick in die anderen Kapitel und Artikel
des restlichen Handbuchs werfen.