include::global_attr.adoc[]
= Release-Upgrade von Linux auf dem {CMK}-Server
:revdate: draft
:title: Release-Upgrade von Linux auf dem {CMK}-Server
:description: Was es beim Upgrade der Linux-Distribution auf dem {CMK}-Server zu beachten gibt, erfahren Sie in diesem Artikel.

{related-start}
link:update.html[Updates und Upgrades]
link:install_packages.html[Grundsätzliches zur Installation von {CMK}]
{related-end}

[#intro]
== Einleitung
Für das Upgrade der Linux-Distribution auf einem {CMK}-Server, gibt es verschiedene empfohlene Methoden. Welche davon für Sie die richtige ist, hängt von den Möglichkeiten Ihrer IT-Landschaft ab. Die unterschiedliche Methoden mit Ihren jeweiligen Voraussetzungen stellen wir hier vor.

== Methode 1

// Die Methode 'Alex'

1. Stoppen Sie zunächst Ihre {CMK}-Site:

[{shell}]
----
{c-root} omd stop mysite
----

2. Hängen Sie das tmp-Verzeichnis der Site aus:

[{shell}]
----
{c-root} umount /opt/omd/sites/mysite/tmp
----

3. Verschieben Sie das gesamte omd-Verzeichnis, damit hieran im nächsten Schritt keine ungewollten Änderungen auftreten können. Bei einem Release-Upgrade werden im Regelfall alle Pakete deren Abhängigkeiten nicht mehr erfüllt werden können entfernt. Zu diesen Paketen würde auch {CMK} gehören. Um hier einen Datenverlust zu verhindern ist dieser Schritt notwendig und kann ein per mv durchgeführt werden.

[{shell}]
----
{c-root} mv /opt/omd /opt/omd.bak
----

//Vor 4 ggf. noch apt purge alter {CMK}-Versionen

4. Führen Sie das Upgrade von Linux entsprechend der Anleitung des jeweiligen Distributors durch.

5. Nach dem erfolgreichen Upgrade Ihrer Linux-Distribution, müssen Sie nun das in Sicherheit gebrachte omd-Verzeichnis wieder an Ort und Stelle verschieben:

[{shell}]
----
{c-root} mv /opt/omd.bak /opt/omd
----

6. Installieren Sie nun ein das zur neuen Version der verwendeten Distribution passendendes Paket von {CMK}.
*Wichtig:* Die Versionsnummer von {CMK} muss exakt der vorher verwendeten entsprechen. Wenn Sie also vor dem Upgrade der Distribution {CMK} 1.6.0p22 verwendet haben, so installieren nun die 1.6.0p22, die zu Ihrer neuen Linux-Version passt.

Im Falle von Ubuntu würde an dieser Stelle der folgende Befehl genügen:

[{shell}]
----
{c-root} apt install /tmp/check-mk-enterprise-1.6.0p22_0.focal_amd64.deb
----

Halten Sie sich bei der Neu-Installation von {CMK} an die jeweilige link:https://docs.checkmk.com/latest/en/install_packages.html#_installation_instructions[detailierte Installationsanleitung] für Ihre jeweilige Distribution.


== Methode 2

// Die Methode 'Manni'

. {CMK} auf höchst-mögliches Patchlevel bringen
. omd backup
. neuen Server mit selber IP aufsetzen
. gleiche Version mit gleichem Patchlevel von {CMK} installieren
. omd restore auf der neuen Kiste



