// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Suche in docs.checkmk.com
:revdate: draft
:title: Die Suche auf docs.checkmk.com optimal nutzen
:description: docs.checkmk.com nutzt eine lunr basierte Suche, die schnell ist und viele Konfigurationsmöglichkeiten bietet

// IGNORE Asciidoctor js lunr Lunr mitgeladen Exklusion Tippens

{related-start}
xref:glossar#[Glossar]
{related-end}

== Einleitung

Diese Website – docs.checkmk.com – nutzt täglich statisch mit link:https://asciidoctor.org/[Asciidoctor^] gebaute HTML-Seiten.
Solch eine Lösung ist performant und sie wird noch viele Jahre die effizienteste Möglichkeit sein, Ihnen das Handbuch auszuliefern.
Ein weiterer Vorteil ist, dass das Vorhandensein jedes Artikels als Einzeldatei im Dateisystem den Aufbau eines Indexes ohne den Umweg über das Netzwerk zulässt.
Aus diesem Grund wurde die Suche im September 2022 von einer Crawler-Lösung auf das JavaScript-Programm link:https://lunrjs.com/[lunr.js^] umgestellt.

Lunr verwendet einen Index, der als JavaScript-Objekt beim ersten Seitenaufruf komplett mitgeladen wird. Das Objekt ist komprimiert weniger als ein Megabyte groß und verbleibt im Cache ihres Browsers bis ein nächtlich neu gebauter Index vorliegt.
Das Bauen des Index zusammen mit der Dokumentation erlaubt es uns, Seitenelemente wie das Inhaltsverzeichnis auszublenden, so dass der Index nur relevante Begriffe enthält.

== Suche im Index

Prinzipiell funktioniert die Suche wie bei jeder anderen Suchmaschine auch: Sie geben Suchbegriffe ein und erhalten eine gewichtete Liste von Ergebnissen.

=== Suche ohne Operatoren

Bei der Suche ohne Operatoren ist die Ergebnisliste wie folgt gewichtet:

. Ganz oben stehen Seiten, die alle Suchbegriffe in großer Nähe zueinander enthalten.
. Es folgen Seiten, die alle Suchbegriffe, aber in größerer Distanz enthalten.
. Schließlich folgen Seiten, welche weniger und schließlich nur einen der eingegebenen Suchbegriffe enthalten.

Das Vorkommen im Seitentitel und der Meta-Beschreibung wird hierbei höher gewichtet als im Fließtext.

=== Inklusion und Exklusion

Mit den Operatoren `+` und `-` können Sie Suchbegriffe voraussetzen oder explizit ausschließen. Beispiele:

- `+katze -hund` findet alle Seiten, welche `katze` enthalten, `hund` aber nicht.
- `+kaffee -tee rum` findet Seiten, die `kaffee`, aber nicht `tee` enthaltet und zeigt die Ergebnisse höher gewichtet, die zudem noch `rum` enthalten.
- `-windows -linux` zeigt alle Seiten, die weder `windows` noch `linux` enthalten.

=== Wildcards

Der Asterisk `*` ersetzt eine beliebige Zeichenkette an einer beliebigen Stelle eines Strings. Während des Tippens fügen wir im Hintergrund automatisch den Asterisk hinzu, um die Vorschau erzeugen zu können. Schließen Sie Ihre Suche mit einem Leerzeichen ab, um einen exakten String zu finden.

=== Gewichtung

Hängen Sie eine Ganzzahl mit einem Zirkumflex an einen Suchbegriff an, um ihn um diesen Faktor höher als der Standard zu gewichten:

- `katze^10 hund^3 ratte` gewichtet `katze` zehnfach höher als `ratte` und `hund` dreifach höher als `ratte`. 

== Verlinkung auf die Suche

Sie können der Suche auch Parameter übergeben. Das JavaScript überträgt den Suchbegriff dann ins Suchfeld und startet die Suche. Folgende Parameter sind möglich:

- `find=suchbegriff` erforderlich, der Begriff, nach dem gesucht werden soll
- `fulloverlay=1`  öffnet nicht die Vorschau mit fünf Treffern, sondern das größere Overlay mit allen
- `imlucky=1`  wechselt sofort zum ersten Suchergebnis
- `origin=bookmarks` Geben Sie diesen Parameter mit an, wenn Sie bspw. aus dem Forum verlinken oder sich die Suche im Handbuch als Suchmaschine anlegen, wird von uns nur statistisch ausgewertet (derzeit definiert: `bookmarks, forum, support, checkmk`).

Prinzipiell funktioniert die Suche auf jeder Seite.
Sie können beispielsweise die Seite des Linux-Agenten mit geöffneter Suche nach dem Begriff `linux` aufrufen: `https://docs.checkmk.com/latest/de/agent_linux.html?find=linux&origin=bookmarks`.

