// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Die Checkmk Plus Edition (CPE)
:revdate: draft
:title: Die Checkmk Plus Edition (CPE)
:description: Was die {CPE} ausmacht, vor allem auch im Vergleich zu den anderen {CMK}-Editionen, erfahren Sie hier.

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:update#[Updates und Upgrades]
xref:cmc#[Der {CMK} Micro Core (CMC)]
{related-end}


[#intro]
== Einleitung

Die eine perfekte Softwarelösung für jeden Nutzer und jeden Anwendungsfall gibt es nicht. Was dem einen gefällt, ist dem anderen zu viel oder zu wenig, zu simpel oder zu komplex. Deshalb ist auch {CMK} in verschiedenen Editionen verfügbar. Diese unterscheiden sich vor allem im Leistungsumfang und in den Einsatzmöglichkeiten. Im Folgenden möchten wir Ihnen die {CPE} vorstellen.

[#editions]
== Einordnung der {CPE}

Die {PE} ist die derzeit umfangreichste Edition von {CMK}. Inhaltlich baut sie auf die {CEE} auf, bietet aber zusätzlich umfangreiche Cloud-Funktionen. Damit ist sie vor allem für die Nutzer von Wert, deren Hosts in einer Cloud beheimatet sind und die auch ihr gesamtes Monitoring in einer Cloud aufsetzen wollen.

Die „lift and shift“ Services, die Sie benötigen, wenn Sie Ihre Apps in eine Cloud bringen wollen, sind bereits in die {EE} integriert. Die {PE} bietet darüber hinaus auch Cloudnative Services. So können Sie beim Übergang aus dem Rechenzentrum in eine Cloud weiter die {EE} nutzen. Möchten Sie danach auch die SaaS und PaaS Produkte, die eine Cloud Ihnen bietet, nutzen, können Sie auf die {PE} upgraden.


[#functions]
== Zusätzliche Funktionen der {CPE}

Die wesentlichen Funktionen der {PE}, die diese von anderen Editionen unterscheiden:

* Die {PE} ist über den Microsoft Azure Marketplace und den AWS Marketplace verfügbar

* Konfiguration eines Push-Agenten: +
In allen Editionen initiiert der {CMK}-Server die Kommunikation mit einem Host und fragt die Daten vom {CMK}-Agenten ab - im sogenannten Pull-Modus. Mit der {PE} können Sie zusätzlich den xref:wato_monitoringagents#[Push-Modus] nutzen, bei dem die Initiative vom Agenten ausgeht. Der Agent sendet von sich aus regelmäßig die Daten an den Checkmk-Server.

* Cloud-spezifische Dashboards: +
//SP: Hier fehlt noch Text. Eventuell auch Screenshots.

* Fortgeschrittene Checks für Clouds: +
////
SP: Es gibt die Artikel monitoring_aws und monitoring_azure. Darin sind Listen der jeweiligen Check-Plugins sowie ein Verweis auf den katalog der Check-Plugins (https://checkmk.com/de/integrations). Noch gibt es aber keine aktuelle und vollständige Liste der Checks, die vor allem auch die Unterschiede der Editionen aufzeigen würde. Müssen wir diese schaffen oder lässt sich das delegieren?
Am Google Cloud Artikel schreibt Sebastian derzeit.

////

* Autoregistrierung von Hosts: +
In der {PE} können Sie die xref:hosts_autoregister#[Autoregistrierung von Hosts] inklusive deren zugehörigen Services nutzen. Damit müssen Sie die Hosts und Services nicht mehr manuell einpflegen.



[#upgrade]
== Upgrade von anderen Editionen zur {CPE}

Mit einem gültigen Lizenzschlüssel können Sie Ihre Test-, Free- oder Standard Edition jederzeit auf eine {PE} upgraden. Folgen Sie dafür der xref:update#updatedemo[Upgrade-Beschreibung für die verschiedenen Editionen.]


== Weiterführende Artikel

//SP: Liste inkl. Verknüpfungen zu den neu erstellten Artikeln zur CPE. Kann erst erstellt werden, wenn die Artikel fertig sind.

