
Hier mal das Grundgerüst in zwei Hierarchie-Ausbauten nach Deinem ODT-Dokument: Tag-Slot-Unterpunkt-Theorie/Praxis und Tag-Slot-Unterpunkt-Thema-Theorie/Praxis. Letzteres würde genauer auf Deine Struktur passen und mehr Spielraum bieten. Sind aber mehr Folien und passt nicht immer. 
Ich habe das jetzt erstmal mit Dummy-Begriffen gemacht, damit klar ist, worüber wir sprechen.

### --------------------------------------------------------
== Tag 1

SI:Übersicht Tag 1
SI:Slot 1
SI:Slot 2

=== Tag 1 Slot 1

link:introduction                                  Unterpunkt 1 mit Seite.html[]
link:introduction                                  Unterpunkt 2 mit Seite.html[]

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 Slot 1 Unterpunkt 1
SI:Theorie zu Unterpunkt 1

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 Slot 1 Unterpunkt 1
SI:Praxis  zu Unterpunkt 1
SI:Überleitung zu Live

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 Slot 1 Unterpunkt 2 - Themen
SI:Thema 1
SI:Thema 2

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 Slot 1 Unterpunkt 2 - Thema 1
SI:Theorie zu Thema 1

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 Slot 1 Unterpunkt 2 - Thema 1
SI:Praxis zu Thema 1
SI:Überleitung zu Live

DO:Dummy
DO:Dummy
DO:


SI:Tag 1 Slot 1 Unterpunkt 2 - Thema 2
SI:Theorie zu Thema 2

DO:Dummy
DO:Dummy
DO:

SI:Tag 1 Slot 1 Unterpunkt 2 - Thema 2
SI:Praxis zu Thema 2
SI:Überleitung zu Live

= Systemmonitoring mit Checkmk - Teil 1: Grundlagen

=== Tag 1 Slot 2 ...