// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Suche in docs.checkmk.com
:revdate: draft
:title: Die Suche auf docs.checkmk.com optimal nutzen
:description: docs.checkmk.com nutzt eine lunr basierte Suche, die schnell ist und viele Konfigurationsmöglichkeiten bietet

// IGNORE Asciidoctor js lunr Lunr mitgeladen Exklusion Tippens

{related-start}
xref:glossar#[Glossar]
{related-end}

== Einleitung

Diese Website – docs.checkmk.com – nutzt täglich statisch mit link:https://asciidoctor.org/[Asciidoctor^] gebaute HTML-Seiten.
Solch eine Lösung ist performant und sie wird noch viele Jahre die effizienteste Möglichkeit sein, Ihnen das Handbuch auszuliefern.
Ein weiterer Vorteil ist, dass jeder Artikel als Einzeldatei vorhanden ist. Damit kann der Index im Dateisystem ohne den Umweg über das Netzwerk aufgebaut werden.
Um dies zu nutzen, wurde die Suche im September 2022 von einer Crawler-Lösung auf das JavaScript-Programm link:https://lunrjs.com/[lunr.js^] umgestellt.

Lunr verwendet einen Index, der als JavaScript-Objekt beim ersten Seitenaufruf komplett mitgeladen wird. Das Objekt ist komprimiert weniger als ein Megabyte groß und verbleibt im Cache Ihres Browsers bis ein nächtlich neu gebauter Index vorliegt.
Das Bauen des Index zusammen mit der Dokumentation erlaubt es uns, Seitenelemente wie das Inhaltsverzeichnis auszublenden, so dass der Index nur relevante Begriffe enthält.

== Suche im Index

Prinzipiell funktioniert die Suche wie bei jeder anderen Suchmaschine auch: Sie geben Suchbegriffe ein und erhalten eine gewichtete Liste von Ergebnissen.

=== Suche ohne Operatoren

Bei der Suche ohne Operatoren ist die Ergebnisliste wie folgt gewichtet:
//SP: Ich würde hier und in den folgenden Abschnitten eher davon reden, dass Seiten asortiert werden, weiter oben in der Liste aufgeführt oder vor anderen Seiten aufgelistet werden. Die Gewichtung ist für mich eher ein internes Phänomen, was man aus meiner Sicht von außen stattdessen sieht, ist die Reihenfolge der Einträge.

. Ganz oben stehen Seiten, die alle Suchbegriffe in direkter Nähe zueinander enthalten.
. Es folgen Seiten, die alle Suchbegriffe, aber in größerer Distanz, enthalten.
. Schließlich folgen Seiten, welche weniger und schließlich nur einen der eingegebenen Suchbegriffe enthalten.

Das Vorkommen im Seitentitel und in der Meta-Beschreibung wird hierbei höher gewichtet als im Fließtext.

=== Inklusion und Exklusion

Mit den Operatoren `+` und `-` können Sie Suchbegriffe explizit ein- oder ausschließen. Beispiele:

- `+katze -hund` findet alle Seiten, welche `katze` enthalten, `hund` aber nicht.
- `+kaffee -tee rum` findet Seiten, die `kaffee`, aber nicht `tee` enthalten und zeigt diejenigen Ergebnisse höher gewichtet, die zudem noch `rum` enthalten.
- `-windows -linux` findet alle Seiten, die weder `windows` noch `linux` enthalten.
//SP: Ich habe zuerst das letzte "zeigt" zu "findet" vereinheitlicht. Dann aber angefangen zu grübeln: findet die jeweilige Suche die Seiten oder zeigt/ergibt die Suche die Seiten?

=== Wildcards

Der Asterisk `*` ersetzt eine beliebige Zeichenkette an einer beliebigen Stelle eines Strings. Während Sie tippen fügen wir im Hintergrund automatisch den Asterisk am Ende des eingegebenen Textes hinzu, um die Vorschau erzeugen zu können. Schließen Sie Ihre Suche mit einem Leerzeichen ab, um einen exakten String zu finden.

=== Gewichtung

Hängen Sie eine Ganzzahl mit einem Zirkumflex an einen Suchbegriff an, um ihn um diesen Faktor höher als den Standard zu gewichten:

- `katze^10 hund^3 ratte` gewichtet `katze` zehnfach höher als `ratte` und `hund` dreifach höher als `ratte`. 
//SP: Warum sollte ich gewichten? Ich kann doch über die Inklusion bereits festlegen, was ich UNBEDINGT und was ich vielleicht sehen will. Sind mir verschiedene Suchbegriffe tatsächlich unterschiedlich wichtig?

== Verlinkung auf die Suche

Sie können der Suche auch Parameter übergeben. Das JavaScript überträgt den Suchbegriff dann ins Suchfeld und startet die Suche. Folgende Parameter sind möglich:

- `find=suchbegriff` erforderlich, der Begriff, nach dem gesucht werden soll
//SP: Der Punkt klingt irgendwie seltsam, aber ich wüßte aktuell nicht, wie er lauten müsste
- `fulloverlay=1`  öffnet nicht die Vorschau mit fünf Treffern, sondern das größere Overlay mit allen Treffern
- `imlucky=1`  wechselt die Ansicht sofort zum ersten Suchergebnis
- `origin=bookmarks` Geben Sie diesen Parameter mit an, wenn Sie bspw. aus dem Forum verlinken oder sich die Suche im Handbuch als Suchmaschine anlegen. Wird von uns nur statistisch ausgewertet (derzeit definiert: `bookmarks, forum, support, checkmk`).
//SP: Den Hinweis auf die statistische Auswertung verstehe ich nicht.
//SP: Vielleicht wäre hier eine Tabellenform, die Eingabe und Erklärung sichtbar voneinander absetzt übersichtlicher?

Prinzipiell funktioniert die Suche auf jeder Seite.
Sie können beispielsweise die Beschreibung des Linux-Agenten mit geöffneter Suche nach dem Begriff `linux` aufrufen: `https://docs.checkmk.com/latest/de/agent_linux.html?find=linux&origin=bookmarks`.

