// -*- coding: utf-8 -*-
// IGNORE %
include::global_attr.adoc[]
= Anmerkungen (Custom notes)
:revdate: 2023-08-18
:title: Anmerkungen zu Hosts und Services (Custom notes)
:description: In den Ansichten zu Hosts und Services können Anmerkungen hinterlegt werden. Lernen Sie hier, wie Sie diese Anmerkungen in {CMK} einrichten.

{related-start}
xref:notifications#[Benachrichtigungen]
xref:views#[Ansichten von Hosts und Services]
{related-end}

// SK: Ich habe hier im Deutschen das Wort Anmerkungen gewählt, weil es aktuell in der deutsche GUI so heißt. Ich würde hier gerne auf den Begriff Notizen wechseln.
// Host-Notizen und Service-Notizen ist meines Erachtens halbwegs erträglich.

////
// aus legacy_multisite_notes
TI:Multisite - Custom Notes
MD:Nagios allows you to configure a noter_url for each host and service, which can be used to link to custom web pages showing more information.
DT:outdated
VS:1.1.7i5
H1:Custom host and service notes
////

== Einleitung

In {CMK} können Sie für alle Hosts und Services einzeln und spezifisch oder für ganze Gruppen Anmerkungen (sogenannte _Custom notes_) hinterlegen.
Diese Anmerkungen werden in jeweils eigenen Spalten namens [.guihint]#Custom services notes# und [.guihint]#Custom host notes# angezeigt.
Standardmäßig werden diese Spalten bereits in den detaillierten Ansichten zu Hosts ([.guihint]#Status of Host myhost#) und Services ([.guihint]#Service myservice, myhost#) angezeigt.
Weil es sich hierbei um reguläre Spalten handelt, können diese auch in viele andere xref:views#edit[Ansichten in {CMK} eingefügt] werden.

////
// aus legacy_multisite_notes
Nagios allows you to configure a noter_url for each host
and service. This can be used to link to custom web pages
showing more information about that specific item. It is
not possible - however - to configure notes or in general
text to be displayed in the GUI directly.

As of version 1.1.7i5 Multisite allows you to do exactly
this in an easy and flexible way: It allows you to attach
arbitrary HTML text to a service or a host. That text
will be displayed in the detailed view of the host or
service. That text is available as a new column named
<i>Custom host notes</i> or <i>Custom service notes</i>
and thus can be added to each view as you prefer.

You are not limited in the amount or complexity of text.
You can embed hyperlinks and other HTML code, even iframes.
////

== Anmerkungen erstellen

Anmerkungen erstellen Sie direkt im Konfigurationsverzeichnis Ihrer {CMK}-Instanz.
Erzeugen Sie dazu zuerst das Verzeichnis `notes` unterhalb von `~/etc/check_mk`.
// SK: Hier der originale Satz aus der alten Anleitung. M.E. ist der Verweis auf den Aufenthaltsort der multisite.mk überflüssig, weil ich nicht wüsste, wo die sonst sein soll.
// First create a subdirectory <tt>notes</tt> in the same directory where <tt>multisite.mk</tt> is present - usually <tt>/etc/check_mk</tt>:

[{shell}]
----
{c-omd} mkdir ~/etc/check_mk/notes
----

=== Anmerkungen für Hosts

Um nun Anmerkungen zu Hosts zu erstellen, erzeugen Sie unterhalb des Verzeichnisses `notes` das Verzeichnis `hosts`.

[{shell}]
----
{c-omd} mkdir ~/etc/check_mk/notes/hosts
----

Wollen Sie nun eine Anmerkung für einen bestimmten Host erstellen, so erzeugen Sie eine Datei deren Namen exakt dem Hostnamen in {CMK} entspricht.
Nutzen Sie dazu den Editor Ihrer Wahl oder die Shell Redirection, wie im folgenden Beispiel:

[{shell}]
----
{c-omd} echo "My custom host note for myhost" > ~/etc/check_mk/notes/hosts/myhost
----

////
// aus legacy_multisite_notes
H1:How to add custom notes
Adding your own notes is easy. No configuration is needed.
First create a subdirectory <tt>notes</tt> in the same directory
where <tt>multisite.mk</tt> is present - usually <tt>/etc/check_mk</tt>:

C+:
RP:cd /etc/check_mk
RP:mkdir notes
C-:

H2:Notes for hosts
You can add notes for hosts and/or services. Let's start with
hosts. Make a subdirectory called <tt>hosts</tt>:

C+:
RP:cd notes
RP:mkdir hosts
C-:

Now let's make a note for the host <tt>b02nag01</tt>. This is
done by creating a file with that name and writing HTML code
into it:

F+:/etc/check_mk/notes/hosts/b02nag01
This is a note for <tt>b02nag02</tt>
F-:
////

// Statt "Shell Patterns" vielleicht auch hier "Suchmuster für Dateinamen"?!?
Wenn Sie möchten, dass sich eine einzelne solche Datei gleich auf mehrere Hosts bezieht und dort angezeigt wird, können Sie mit Shell Patterns wie dem Stern, dem Fragezeichen und auch Zeichenklassen arbeiten.
Dazu muss dann tatsächlich der Dateiname im jeweiligen Verzeichnis diese Zeichen enthalten.
Eine Datei namens pass:['*'] im Verzeichnis `~/etc/check_notes/hosts/` würde sich also auf alle Host beziehen.
Der Inhalt der Datei pass:['*'] würde folgerichtig bei jedem einzelnen Host Ihrer Instanz angezeigt.

Möchten Sie - aus Gründen - bei allen Hosts deren Name auf 'e' endet eine bestimmte Anmerkung anzeigen, dann erstellen Sie dazu eine Datei namens '*e'.

[{shell}]
----
{c-omd} echo "Name dieses Hosts endet auf e" > ~/etc/check_mk/notes/hosts/'*e'
----

Sollten mehrere Dateien zum Namen eines Hosts passen, werden im Feld [.guihint]#Custom host notes# auch alle passenden Anmerkungen angezeigt.
//SK: Hier gibt es noch ein Unschönheit in Checkmk. Wenn mehrere Notes-Dateien passen, wird zwischen die Notes ein <hr> eingefügt, welches derzeit leider nicht erlaubt ist und deshalb nicht interpretiert wird.

*Wichtig:* Wie Sie in den Beispielen bereits gesehen haben, *müssen* die Namen solcher Dateien in einfache Anführungsstriche eingefasst werden.

////
//SK: Vielleicht fallen mir ja noch ein paar sinnvolle Beispiele ein.
=== Weitere Beispiele für Suchmuster

[cols=2]
|===
| `'?????'` | Alle Hosts, deren Name genau 5 Zeichen lang ist.
| `'*linux*'` | Alle Hosts, die irgendwo den String `linux` im Namen tragen.
|===
////

////
// aus legacy_multisite_notes
You can use one file for more hosts by making use of
shell patterns like <tt>*</tt> and <tt>?</tt>. Please
note that here the filename aktually contains the <tt>*</tt>.
While this concept is very unusual it is not at all
impossible nor inconvenient. You just have to make sure
that you use quotes in order to escape the patterns from
the shell. The following example creates a description
for all hosts containing <tt>nag</tt>:

C+:
RP:cd /etc/check_mk/notes/hosts
RP:vim '*nag*'
C-:

If more than one file matches then all matching files will
be used and several notes will be attached to the host.
////

=== Anmerkungen für Services

Um auch für Services solche Anmerkungen einrichten zu können, benötigen Sie unterhalb von `~/etc/check_mk/notes` noch das Verzeichnis `services`.

[{shell}]
----
{c-omd} mkdir ~/etc/check_mk/notes/services
----

Im Gegensatz zu den Hosts können Sie nicht gleich in diesem Verzeichnis mit den Dateien für Ihre Anmerkungen loslegen.
Hier Bedarf es noch einer weiteren Verzeichnisebene, die festlegt, bei welchen Hosts eine Service-Anmerkung angezeigt werden soll.

Erzeugen Sie also als nächstes ein Verzeichnis, welches einen - oder nach den Mustern oben - mehrere Hosts bezeichnet.

Ein Verzeichnis namens '*' würde sich also wieder auf alle Hosts beziehen.

[{shell}]
----
{c-omd} mkdir ~/etc/check_mk/notes/services/'*'
----

In einem Verzeichnis, welches exakt einem Hostnamen entspricht, können Sie anschließend somit nur die Services dieses einen Hosts mit Anmerkungen versehen.

[{shell}]
----
{c-omd} mkdir ~/etc/check_mk/notes/services/myhost
----

Möchten Sie Services bei allen Hosts die mit `my` beginnen, müssen Sie also ein Verzeichnis namens `'my*'` anlegen.

[{shell}]
----
{c-omd} mkdir ~/etc/check_mk/notes/services/'my*'
----

Achten Sie auch hier wieder darauf, die Verzeichnisnamen in einfache Anführungsstriche einzufassen.

Sobald Sie jetzt die Host-Ebene nach Ihren Wünschen erstellt haben, können Sie - analog zu den Host-Anmerkungen - wieder Dateien anlegen, die diesmal der gewünschten [.guihint]#Service description# entsprechen muss.
Auch hier können Sie wieder mit Sternen, Fragezeichen und Zeichenklassen arbeiten.

Das folgende Beispiel erzeugt eine Anmerkung für den Service [.guihint]#Check_MK# auf jedem Host Ihrer Instanz.

[{shell}]
----
{c-omd} echo "Anmerkung zum Service Check_MK" > ~/etc/check_mk/notes/services/'*'/Check_MK
----




////
// aus legacy_multisite_notes
H2:Notes for services
Making notes for services is just as easy as for hosts but
with one extra directory level. First you have to create
a subdirectory <tt>services</tt>:

C+:
RP:cd /etc/check_mk/notes
RP:mkdir services
RP:cd services
C-:

Service notes can be specific to hosts. Therefore you first
have to create directories for your hosts. Here exactly the
same rules apply as for host notes with the only difference
that we now create <i>directories</i> instead of files.
In the following example we create the three directories
<tt>b02nag02</tt>, <tt>b02*</tt> and <tt>*</tt>. They will
be used for the host <tt>b02nag02</tt>, all hosts beginning
with <tt>b02*</tt> (including <tt>b02nag02</tt> and all of your
host.

Just as with the host notes all matching directories will
be used and scanned for matching notes. This allows you to
make general notes for a specific type of services by
using the directory <tt>*</tt> and at the same time additional
notes for that service on one ore more specific hosts.

Within the directories spoken of you now create files matching
the service descriptions the notes should be displayed at.
Again those files may contain arbitrary HTML code. Here are
some examples:

Make a note for service <tt>CPU Load</tt> on all hosts:
C+:
RP:cd /etc/check_mk/notes/services
RP:mkdir '*'
RP:vim '*/CPU Load'
C-:

Make an additional note for <tt>CPU Load</tt> just on
<tt>b02nag02</tt>:
C+:
RP:mkdir 'b02nag02'
RP:vim 'b02nag02/CPU Load'
C-:

Make notes for services containing <tt>eth0</tt> on hosts
beginning with <tt>srv</tt>:
C+:
RP:mkdir 'srv*'
RP:vim 'srv*/*eth0*'
C-:

H1:Replacing tags
You are for sure not the first one having the idea to
add hyper links into your host or service notes. If your
link contains host specific information (such as the host
name or its ip address) you probably do not want to
copy and paste your host notes file for each host.

Therefore, Multisite is so kind as to replace the following
macros in your HTML code with the actual values:
////

== Verwendbare Makros

Innerhalb der Anmerkungen können Sie Makro verwenden, welche dann in der Ansicht passend ersetzt werden.
Folgende Makro stehen Ihnen hier zu Verfügung:

[cols="30,~"]
|===
| `$HOSTNAME$` | Host-Name
| `$HOSTNAME_LOWER$` | Host-Name in Kleinbuchstaben
| `$HOSTNAME_UPPER$` | Host-Name in Großbuchstaben
| `$HOSTNAME_TITLE$` | Host-Name mit dem ersten Buchstaben als Großbuchstaben und dem Rest klein
| `$HOSTADDRESS$` | Diejenige IP-Adresse des Hosts, über die er überwacht wird.
| `$SERVICEDESC$` | Service-Beschreibung (nur bei Service-Anmerkungen)
| `$SITE$` | ID der {CMK}-Instanz
| `$URL_PREFIX$` | URL-Präfix der Instanz
| `$HOSTOUTPUT$` | Ausgabe des Host-Check-Plugins (nur für Host-Anmerkungen)
| `$SERVICEOUTPUT$` | Ausgabe des Check-Plugins (nur für Service-Anmerkungen)
</table>
|===

So könnten Sie beispielsweise mit einer einzigen Datei auf unterschiedliche Einträge in Ihrem firmeneigenen Wiki verweisen, welche immer zu dem gerade geöffneten Host passen.

.~etc/check_mk/notes/hosts/'*'
[{file}]
----
Weitere Informationen <a href="http://mywiki.local/page.php?host=$HOSTNAME$" target=_blank>zu diesem Host</a> in unserem Wiki.
----

== Erlaubte HTML-Tags

Beachten Sie, dass in den Anmerkungen aus Sicherheitsgründen nur eine kleine Menge an HTML-Tags zugelassen ist.
Diese sind:

`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/h1[h1^]`,
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/h2[h2^]`,
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b[b^]`,
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt[tt^]`,
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i[i^]`,
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u[u^]`,
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br[br^]`,
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nobr[nobr^]`,
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre[pre^]`,
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup[sup^]`,
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p[p^]`,
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li[li^]`,
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul[ul^]` und
`link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol[ol^]`.

Daneben ist `link:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a[a^]` zugelassen, wenn es mit dem Attribut `href` und `target` kombiniert ist. Dieses Target muss außerhalb des {CMK}-Tabs liegen.