// -*- coding: utf-8 -*-

[#register_agent]
=== Agenten registrieren

Registrieren Sie im nächsten Schritt die zu überwachenden Hosts am {CMK}-Server.
Da ein neuer Host dem {CMK}-Server bisher noch nicht vertraut und dieser auch noch nicht weiß, dass der Host automatisch aktualisiert werden soll, muss der Agent auf dem Host einmalig von Hand installiert werden.
//TK: Verwirrend beschrieben mit "die zu überwachenden Hosts" und "neuer Host". Hier geht es doch um die Hosts, für die der Agent Updater funktionieren soll und auf denen daher das gebackene Paket installiert werden muss.

Laden Sie dafür zunächst unter [.guihint]#Setup > Agents > Windows, Linux, Solaris, AIX# das für den Host passende Paket aus der xref:wato_monitoringagents#bakery_download[Agentenbäckerei] herunter.
Achten Sie darauf, dass das Paket auch wirklich das Agent-Updater-Plugin enthält.

Kopieren Sie nun das Agentenpaket auf den Host und installieren Sie es mit `rpm` bzw. `dpkg` unter xref:agent_linux#install_package[Linux] oder mit `msiexec` unter xref:agent_windows#install_package[Windows.]
//SP: Hier fehlt noch ein Abschnitt, der darauf hinweist, dass das gebackene Paket auf den zugehörigen Host kopiert werden muss. Das Thema wird nur so nebenbei gestreift.
//TK: Jede Option wird kilometerlang beschrieben, aber Download, Copy und Install geht huschhusch. 
//TK: Ich hab jetzt die Links auf Linux und Windows in die richtigen Kapitel geschickt, aber ein Beispiel eines Installationskommandos sollte schon gezeigt werden.

Nach der Installation finden Sie das Agent-Updater-Plugin -- abhängig vom Betriebssystem des Hosts -- in den folgenden Verzeichnissen:

* Unter unixoiden Systemen als `/usr/lib/check_mk_agent/plugins/3600/cmk-update-agent`.
Das Unterverzeichnis `3600` steht dabei für das xref:interval_for_update_check[Intervall für den Update-Check] in Sekunden (hier für den Standardwert von einer Stunde).
Ein gleichnamiges Skript wird auch unter `/usr/bin/` abgelegt, daher steht `cmk-update-agent` auch als Kommando zur Verfügung.

* Unter Windows: Der Agent Updater ist in den Windows-Agenten `C:\Program Files (x86)\checkmk\service\check_mk_agent.exe` integriert.
Dem Updater selbst können Sie dann immer mit `check_mk_agent.exe updater` Befehle erteilen.

Rufen Sie nun den Agent Updater mit dem Argument `register` auf.
Unter Windows muss dies in einer Eingabeaufforderung mit Administratorrechten geschehen.
Geben Sie dann der Reihe nach die erforderlichen Angaben ein.
Wenn Sie bisher dieser Anleitung von Beginn an gefolgt sind und einen gebackenen Agenten installiert haben, werden nicht alle der folgenden Einstellungen abgefragt.
Diese sind hier nur zu Referenzzwecken angegeben.
//TK: Wer braucht Referenzzwecke? Es sollten nur die Zeilen zu sehen sein, die nach dem bisherigen Vorgehen abgefragt werden, also ab "Our host name in the monitoring:"

Mit dem folgenden Kommando registrieren Sie den Agent Updater von einem *Linux-Host* aus:

[{shell}]
----
{c-root} cmk-update-agent register -v
+-------------------------------------------------------------------+
|                                                                   |
|  Check_MK Agent Updater v2.1.0 - Registration                     |
|                                                                   |
|  Activation of automatic agent updates. Your first step is to     |
|  register this host at your deployment server for agent updates.  |
|  For this step you need a user with the permission                |
|  "Register all hosts" on that Checkmk site.                       |
|                                                                   |
+-------------------------------------------------------------------+
Deployment server to connect to:
*myserver.example.com*

Protocol to use for connection [http/https]:
*https*

Check_MK site on deployment server:
*mysite*

Our host name in the monitoring:
*myhost*

User with registration permissions: 
*cmkadmin*

Password:

Going to register agent at deployment server
Successfully registered agent of host "myhost" for deployment.
You can now update your agent by running 'cmk-update-agent -v'
Saved your registration settings to /etc/cmk-update-agent.state.

Hint: you can do this in scripts with the command:

cmk-update-agent register -s myserver.example.com -i mysite -H myhost -p https -U cmkadmin -P *** -v
----
//TK: Hier gibt es die Kommandoausgabe: "You can now update your agent by running 'cmk-update-agent -v'". Ist das nötig? Wenn nicht, warum steht es da?

Da der Agent Updater für *Windows-Hosts* direkt durch den Agenten selbst ausgeführt wird, sieht der Befehl für die Registrierung hier ein wenig anders aus:

[{shell}]
----
C:\WINDOWS\system32> "C:\Program Files (x86)\checkmk\service\check_mk_agent.exe" updater register
Using previous settings from C:\ProgramData\checkmk\agent\config\cmk-update-agent.state.
Our host name in the monitoring:
*mywindowshost*

User with registration permissions:
*cmkadmin*

Password:

Successfully registered agent of host "mywindowshost" for deployment.
----
//TK: Bei Windows mangels Kenntnis nur die abgespeckten Abfragen.

Alternativ können Sie die Registrierung auch im nicht-interaktiven Modus durchführen, indem die benötigten Daten per Kommandozeilenoptionen übergeben werden.
Unter Linux zeigt ein Aufruf von `cmk-update-agent register --help` hier die setzbaren Optionen an.

Unter Windows sieht der komplette Befehl zur Registrierung wie folgt aus:

[{shell}]
----
C:\WINDOWS\system32> "C:\Program Files (x86)\checkmk\service\check_mk_agent.exe" ^
updater register -s myserver.example.com -i mysite -H mywindowshost -p https -U cmkadmin -P mycmkadminpassword -v
----
//TK: Hier gibt es die Kommandoausgabe: "You can now update your agent by running 'check_mk_agent.exe updater -v'". Ist das nötig? Wenn nicht, warum steht es da?

Erwähnenswert hierbei ist, dass die einmalige Registrierung auch über einen xref:glossar#automation_user[Automationsbenutzer] erfolgen kann.
Dafür wird auf der Kommandozeile der Benutzer per `-U/--user` und das Automationspasswort per `-S/--secret` übergeben.

Einige Hinweise zur Registrierung:

* Bei der Registrierung benötigt das Plugin auch den Namen des Hosts, wie er im Monitoring bekannt ist.
Dieser ist nicht unbedingt mit dem Host-Namen des Rechners identisch.
Der Host-Name wird dann zusammen mit dem Schlüssel lokal gespeichert.

* Um HTTPS zu verwenden, muss auf Ihrem Monitoring-Server HTTPS eingerichtet sein.
HTTP ist hier deutlich einfacher, bietet aber keine Verschlüsselung der Übertragung.
Da der Agent in Skripten und Konfigurationsdateien Passwörter enthalten kann, ist HTTPS der empfohlene Weg.
Die Authentizität des Agenten wird aber durch die Signatur unabhängig davon sichergestellt.

* Der Login als {CMK}-Administrator ist nur einmal erforderlich.
Agent und Server vereinbaren bei der Registrierung einen geheimen Schlüssel (_Host Secret_), der nur diesem Host bekannt ist.
Das Passwort des {CMK}-Administrators wird nirgendwo gespeichert.

* Während der interaktive Modus nur Felder abfragt, die in noch keiner Konfiguration vorhanden sind, lassen sich durch den nicht-interaktiven Modus alle in der Hilfe angezeigten Felder setzen und haben für diesen Aufruf die höchste Priorität.
Optionen, die nur in der Datei `cmk-update-agent.state` gespeichert sind, werden so überschrieben -- Optionen aus `cmk-update-agent.cfg` jedoch nicht. Mehr Details dazu gibt es weiter unten unter xref:agent_deployment#show_config[Einsehen der lokalen Konfiguration.]
//TK: Ungünstig, dass die beiden Dateien *.state und *.cfg schon hier erwähnt werden, bevor sie im nächsten Absatz erklärt werden.

Nach einer erfolgreichen Registrierung wird das Host Secret beim Agenten in der Datei `/etc/cmk-update-agent.state` gespeichert.
Auf dem Server liegt er dann in `~/var/check_mk/agent_deployment/myhost`.
Das Host Secret erlaubt von nun an dem Host *seinen eigenen* Agenten ohne Passwort vom Server herunterzuladen.
Ein Herunterladen von Agenten anderer Hosts ist nicht möglich (da diese vertrauliche Daten enthalten könnten).