// -*- coding: utf-8 -*-
include::global_attr.adoc[]


[#architecture]
== Der neue Agent

////
Die Überwachung von Windows-Servern war von Anfang an eine der wichtigsten Aufgaben von {CMK}.
Wie für alle anderen Server-Betriebssysteme liefert {CMK} daher auch für Windows einen eigenen Agenten aus.
Dieser hat gegenüber einer Überwachung mit WMI oder SNMP etliche Vorteile, denn er ist:

* *minimalistisch*, denn er begnügt sich mit minimalen Ressourcen an RAM, CPU und Netzwerk.
* *sicher*: denn er liest keine Daten aus dem Netzwerk.
Dadurch wird jeglicher externe Zugriff auf das System unterbunden.
* *umfassend*, denn er hat Zugriff auf wichtige Daten, die per WMI oder SNMP nicht erreichbar sind.
* *leicht erweiterbar*, denn Sie können Erweiterungen in einer beliebigen Programmier- oder Skriptsprache schreiben.
* *offen*, denn obwohl der Agent als ausführbare Datei ausgeliefert wird, haben Sie jederzeit Zugriff auf den Quellcode und können den Agenten daher prinzipiell auch selbst kompilieren und haben jederzeit Einsicht in die Funktionalität.
Es wird kein unbekannter Code verwendet.

In einigen Fällen kann allerdings die Überwachung per SNMP *zusätzlich* zum {CMK}-Agenten sinnvoll sein.
Im Artikel zur xref:snmp#snmp_cmk_agent[Überwachung mit SNMP] finden Sie mehr zu diesem Thema.

Die Installation und Einrichtung des Agenten ist sehr einfach und mit wenigen Schritten erledigt, denn dieser braucht für seine Funktion zum Beispiel keine zusätzlichen Bibliotheken.
Zudem wird er mit einer Grundkonfiguration ausgeliefert, welche für die meisten Anwendungsfälle ausreicht.

Im Betrieb besteht der Agent aus einem Windows-Dienst, welcher das mitgelieferte Programm -- den Agenten -- startet.
Dieser sammelt bei einem Aufruf Daten zu dem lokalen System und stellt diese dem Monitoring, wie bei anderen Agenten auch, über Port 6556 zur Verfügung.

In den {CEE} können Sie den Agenten mithilfe der xref:agent_deployment#[automatischen Agenten-Updates] automatisch zentral aktualisieren und konfigurieren.
Alternativ können Sie das MSI-Paket auch über andere Wege, wie zum Beispiel das Microsoft Active Directory verteilen.
Die Installation kann hier durch das MSI-Format komplett automatisiert werden.

Aus Kompatibilitätsgründen werden nur die Hauptversionen von Windows unterstützt.
Die folgende Tabelle listet diese explizit auf:

[cols=2]
|===
|Version |Edition

|NT 6.0 |Windows Vista
|NT 6.0 |Windows Server 2008
|NT 6.1 |Windows 7
|NT 6.1 |Windows 2008 R2
|NT 6.2 |Windows 8
|NT 6.2 |Windows Server 2012
|NT 6.3 |Windows 8.1
|NT 6.3 |Windows 2012 R2
|NT 6.4 / NT 10.0 |Windows 10
|NT 6.4 / NT 10.0 |Windows Server 2016
|NT 6.4 / NT 10.0 |Windows Server 2019
|===

*Wichtig*: Editionen, die in der Tabelle nicht erwähnt werden, werden nicht offiziell unterstützt.
Dazu gehört zum Beispiel auch _Windows Embedded_.
////
