// -*- coding: utf-8 -*-
include::global_attr.adoc[]

[#hw_monitoring]
== Hardware überwachen

Die Hardware-Überwachung von Windows-Hosts wird vom {CMK}-Agenten, mitgelieferten Plugins und in der href:https://exchange.checkmk.com/[{CMK} Exchange^] erhältlichen Erweiterungen gut abgedeckt.
Dennoch gibt es Situationen, in denen weder fertige Plugins noch Programmierschnittstellen zur Erstellung eigener Plugins erhältlich sind, aber entweder eine Anwendungssoftware oder ein Hardwareüberwachungstool eines Hardwareherstellers Überwachungsdaten per SNMP liefern kann.

Setzen Sie in so einem Fall in den Eigenschaften des Hosts im Setup im Kasten Monitoring agents die Einstellung SNMP auf die geeignete Verbindungsart (SNMP v2 or v3 oder SNMP v1). Services, die sowohl per SNMP als auch per Checkmk-Agent verfügbar sind (z.B. CPU-Auslastung, Dateisysteme, Netzwerkkarten), werden dann automatisch vom Checkmk-Agenten geholt und nicht per SNMP. Damit wird eine Doppelübertragung automatisch vermieden.

Weitere Informationen entnehmen Sie dem Handbuchartikel xref:snmp#snmp_cmk_agent["Überwachung mit SNMP"].