// -*- coding: utf-8 -*-
include::global_attr.adoc[]


[#uninstall]
== Deinstallation

Für die Deinstallation des Agenten haben Sie in Windows mehrere Möglichkeiten.
In allen Versionen von Windows finden Sie einen Eintrag in der Systemsteuerung unter [.guihint]#Control Panel > Programs and Features > Uninstall a program.#
In neueren Versionen finden Sie den Eintrag für den {CMK}-Agenten zudem in den Einstellungen unter [.guihint]#Settings > Apps > Apps & features.#

Über die Kommandozeile für Administratoren haben Sie mehrere Möglichkeiten den Agenten zu entfernen.
Sollte Ihnen das zuletzt installierte MSI-Paket noch vorliegen, können Sie dieses wie folgt für die Deinstallation nutzen:

[{shell}]
----
C:\Users\hhirsch\Downloads\> msiexec /x check_mk_agent.msi /qn
----

Alternativ können Sie auch das Windows Management Instrumentation Command (WMIC) für die Deinstallation verwenden:

[{shell}]
----
C:\> wmic product where name="Check MK Agent 2.1" call uninstall /nointeractive
----

War die Deinstallation erfolgreich, erhalten Sie als Bestätigung die Meldung `Method execution successful.`

*Hinweis:* Der String hinter `name=` muss exakt stimmen.
Wenn Sie hier eine andere Version des Agenten deinstallieren wollen, finden Sie eine Auflistung aller installierten Produkte mit folgendem Aufruf:

[{shell}]
----
C:\> wmic product get name
----

Der Vorgang kann bisweilen recht lange dauern und gibt derweil keinerlei Statusmeldungen aus, dafür dann aber sehr lange Listen.
Zum Filtern können Sie den Befehl zur Pipe ausbauen:
// ML: Ausführungszeit hier: 59 Sekunden, ohne Fortschrittsanzeige - keine gute Lösung.

[{shell}]
----
C:\> wmic product get name | findstr Check
Check MK Agent 2.1
----

Da die verschiedenen Routinen von Windows nur Dateien entfernen, welche auch durch den Installationsprozess dorthin gekommen sind, ist es vollkommen normal, dass in den xref:files[Verzeichnissen des Agenten] noch Dateien übrig bleiben.
Diese können manuell gelöscht werden.
