// -*- coding: utf-8 -*-
include::global_attr.adoc[]

[#folder]
== Ordner und Vererbung

////
http://docs.dev.tribe29.com/master/de/draft_hosts_setup.html#folder
http://docs.dev.tribe29.com/master/de/intro_setup_monitor.html#folders
Ordner für Hosts sind ein bekanntes Prinzip zur Strukturierung, denn jeder, der mit Computern arbeitet, kennt das Prinzip von Dateien und Ordnern.
Oft genutzte Kriterien für den Aufbau des Host-Baums sind Standort, Technologie und Organisationsstruktur.
Über Ordner können Attribute an Unterordner und enthaltene Hosts vererbt werden.
Das ist nützlich für Attribute, die bei vielen Hosts gleich sind, z.B. ob der Host per {CMK}-Agent oder per SNMP überwacht werden soll.
Mit Ordnerattributen können Sie die Aufnahme von Hosts vorbereiten, die erst in Zukunft hinzukommen werden, sofern Sie die Hosts im vorkonfigurierten Ordner erstellen.
Für die Konfiguration großer Umgebungen ist es elementar, von Beginn an eine wohlüberlegte Ordnerstruktur aufzusetzen.
Vererbt werden können alle in den Ordnereigenschaften festgelegten Attribute, wie z.B. Monitoring-Agenten, Permissions, Management board -- aber auch andere Strukturierungselemente wie Host-Merkmale, Labels oder Parents.
Eine Ordnerstruktur alleine kann nur in seltenen Fällen die Komplexität der Wirklichkeit abbilden.
////