// -*- coding: utf-8 -*-
include::global_attr.adoc[]

[#intro]
== Einleitung

Die wichtigste Aufgabe beim Einrichten des Monitorings ist das Verwalten der zu überwachenden Systeme -- der xref:glossar#host[_Hosts_.]
Dabei geht es nicht nur darum, dass diese mit den richtigen Stammdaten (z.B. Host-Name, IP-Adresse) eingetragen sind.
Auch Einstellungen für das Monitoring (z.B. Benachrichtigungen, Schwellwerte, usw.) wollen gepflegt werden.

{CMK} wurde von Anfang an für Umgebungen mit sehr vielen Hosts entworfen.
Um hier die Konfiguration für den Nutzer beherrschbar zu machen, verfolgt {CMK} einen anderen Ansatz als alle anderen Systeme,
die aus dem Ökosystem von Nagios heraus entstanden sind.
Die wichtigsten Prinzipien sind:

* Eine xref:folder[Hierarchie von Ordnern], in denen Hosts abgelegt werden.
* xref:glossar#host_tag[Host-Merkmale] (englisch: _host tags_) und eine darauf aufbauende xref:wato_rules#[regelbasierte] Konfiguration.
* Automatische Erkennung der zu überwachenden xref:wato_services#[Services.]

Generell hat es sich bewährt, sich als erstes ein Ordnungssystem zu überlegen und dieses danach mit Inhalt zu füllen.
Konkret bedeutet das also, sich erst mit dem Aufbau der Ordner und ihrer Hierarchie zu befassen und danach die Hosts "einzusortieren".
