// -*- coding: utf-8 -*-
include::global_attr.adoc[]


[#architecture]
[#agent_architecture]
== Architektur des Agenten

////
=== Verzeichnisse des Agenten

Der Agent gliedert sich in zwei Bereiche des Dateisystems auf:

* `C:\Program Files (x86)\checkmk\service\` - Hier werden programmspezifische Dateien installiert.
Anpassungen sind hier nicht nötig. In das Verzeichnis `Program Files *(x86)*` wird der Agent aus Gründen der Kompatibilität installiert.
Dies ist unabhängig davon, ob der Agent auf ein 32- oder 64-Bit Betriebssystem installiert wird.
Die Installationsroutine wählt automatisch den richtigen Agenten aus.
* `C:\ProgramData\checkmk\agent\` - Hier werden host-spezifische Dateien gespeichert.
Das Verhalten des Agenten wird hier konfiguriert und Plugins, Logs, etc. werden ebenfalls unterhalb dieses Verzeichnisses abgelegt. +
*Hinweis*: Normalerweise ist dieses Verzeichnis vom System als unsichtbar markiert.


=== Die Konfigurationsdateien des Agenten

Für die Konfiguration des Agenten liest dieser nacheinander und hierarchisch drei Dateien ein:

. `C:\Program Files (x86)\checkmk\service\check_mk.yml` - Hier ist die Standardkonfiguration hinterlegt. Diese dürfen Sie nicht ändern.
. `C:\ProgramData\checkmk\agent\bakery\check_mk.bakery.yml` - Diese Datei wird von der Agentenbäckerei erstellt und überschreibt gegebenfalls einen Standardwert aus der vorherigen Datei.
. `C:\ProgramData\checkmk\agent\check_mk.user.yml` - In dieser Datei können Sie von Hand individuelle Anpassungen vornehmen, um eine Einstellung oder eine Erweiterung auf einem Host zu testen.
Diese Datei wird nach der Konfiguration aus der Agentenbäckerei eingelesen und überschreibt diese gegebenenfalls.

Wie Sie vielleicht schon an der Dateiendung der Konfigurationsdateien erkannt haben, wird als Konfigurationsformat link:https://yaml.org[YAML^] verwendet.
Wir haben uns entschieden, ab Version {v16} dieses Format zu verwenden, da es damit einfacher möglich ist, strukturierte Daten zu konfigurieren, als mit dem klassischen INI-Format.

Für das manuelle Arbeiten mit dem Agenten ist also lediglich die letzte Konfigurationsdatei (`check_mk.user.yaml`) relevant, weil sie als letzte eingelesen wird und damit _das letzte Wort hat_.
Wenn die Agentenbäckerei nicht genutzt wird, ist sie sogar die einzige Datei, in der Anpassungen an der Konfiguration des Agenten vorgenommen werden dürfen.
////
