// -*- coding: utf-8 -*-

[#register_agent]
=== Agenten registrieren

Registrieren Sie im nächsten Schritt die Hosts, für die Sie den Agent Updater einrichten wollen, am {CMK}-Server.
Da ein neuer Host dem {CMK}-Server bisher noch nicht vertraut und dieser auch noch nicht weiß, dass der Host automatisch aktualisiert werden soll, muss der Agent auf dem Host einmalig von Hand installiert werden.

Laden Sie dafür zunächst unter [.guihint]#Setup > Agents > Windows, Linux, Solaris, AIX# das für den Host passende Paket aus der xref:wato_monitoringagents#bakery_download[Agentenbäckerei] herunter.
Achten Sie darauf, dass das Paket auch wirklich das Agent-Updater-Plugin enthält.

==== Agenten unter Linux registrieren

Kopieren Sie nun das Agentenpaket auf den zugehörigen Host und installieren Sie es mit `rpm` bzw. `dpkg` (xref:agent_linux#install_package[Paketinstallation unter Linux].)

Nach der Installation finden Sie das Agent-Updater-Plugin im Verzeichnis `/usr/lib/check_mk_agent/plugins/3600/cmk-update-agent`.
Das Unterverzeichnis `3600` steht dabei für das xref:interval_for_update_check[Intervall für den Update-Check] in Sekunden (hier für den Standardwert von einer Stunde).
Ein gleichnamiges Skript wird auch unter `/usr/bin/` abgelegt, daher steht `cmk-update-agent` auch als Kommando zur Verfügung.

Rufen Sie nun den Agent Updater mit dem Argument `register` auf.
Geben Sie dann der Reihe nach die erforderlichen Angaben ein.

Mit dem folgenden Kommando registrieren Sie den Agent Updater von einem *Linux-Host* aus:

[{shell}]
----
{c-root} cmk-update-agent register -v
+-------------------------------------------------------------------+
|                                                                   |
|  Check_MK Agent Updater v2.1.0 - Registration                     |
|                                                                   |
|  Activation of automatic agent updates. Your first step is to     |
|  register this host at your deployment server for agent updates.  |
|  For this step you need a user with the permission                |
|  "Register all hosts" on that Checkmk site.                       |
|                                                                   |
+-------------------------------------------------------------------+
Our host name in the monitoring:
*myhost*

User with registration permissions: 
*cmkadmin*

Password:

Going to register agent at deployment server
Successfully registered agent of host "myhost" for deployment.
You can now update your agent by running 'cmk-update-agent -v'
Saved your registration settings to /etc/cmk-update-agent.state.

Hint: you can do this in scripts with the command:

cmk-update-agent register -s myserver.example.com -i mysite -H myhost -p https -U cmkadmin -P *** -v
----
//TK: Hier gibt es die Kommandoausgabe: "You can now update your agent by running 'cmk-update-agent -v'". Ist das nötig? Wenn nicht, warum steht es da?

Alternativ können Sie die Registrierung auch im nicht-interaktiven Modus durchführen, indem die benötigten Daten per Kommandozeilenoptionen übergeben werden.
Ein Aufruf von `cmk-update-agent register --help` zeigt die setzbaren Optionen an.


==== Agenten unter Windows registrieren

Kopieren Sie nun das Agentenpaket auf den zugehörigen Host und installieren Sie es mit msiexec` (xref:agent_windows#install_package[Paketinstallation unter Windows.])

//TK: Jede Option wird kilometerlang beschrieben, aber Download, Copy und Install geht huschhusch. 
//TK: Ein Beispiel eines Installationskommandos sollte schon gezeigt werden.

Nach der Installation ist der Agent Updater in den Windows-Agenten `C:\Program Files (x86)\checkmk\service\check_mk_agent.exe` integriert.
Dem Updater selbst können Sie dann immer mit `check_mk_agent.exe updater` Befehle erteilen.

Rufen Sie nun den Agent Updater mit dem Argument `register` auf.
Unter Windows muss dies in einer Eingabeaufforderung mit Administratorrechten geschehen.
Geben Sie dann der Reihe nach die erforderlichen Angaben ein.

Da der Agent Updater für *Windows-Hosts* direkt durch den Agenten selbst ausgeführt wird, sieht der Befehl für die Registrierung so aus:

[{shell}]
----
C:\WINDOWS\system32> "C:\Program Files (x86)\checkmk\service\check_mk_agent.exe" updater register
Using previous settings from C:\ProgramData\checkmk\agent\config\cmk-update-agent.state.
Our host name in the monitoring:
*mywindowshost*

User with registration permissions:
*cmkadmin*

Password:

Successfully registered agent of host "mywindowshost" for deployment.
----
//TK: Bei Windows mangels Kenntnis nur die abgespeckten Abfragen.

Alternativ können Sie die Registrierung auch im nicht-interaktiven Modus durchführen, indem die benötigten Daten per Kommandozeilenoptionen übergeben werden.
Der komplette Befehl zur Registrierung sieht wie folgt aus:

[{shell}]
----
C:\WINDOWS\system32> "C:\Program Files (x86)\checkmk\service\check_mk_agent.exe" ^
updater register -s myserver.example.com -i mysite -H mywindowshost -p https -U cmkadmin -P mycmkadminpassword -v
----

==== Einmalige Registrierung und generelle Hinweise
Die einmalige Registrierung kann auch über einen xref:glossar#automation_user[Automationsbenutzer] erfolgen.
Dafür wird auf der Kommandozeile der Benutzer per `-U/--user` und das Automationspasswort per `-S/--secret` übergeben.

Einige Hinweise zur Registrierung:

* Bei der Registrierung benötigt das Plugin auch den Namen des Hosts, wie er im Monitoring bekannt ist.
Dieser ist nicht unbedingt mit dem Host-Namen des Rechners identisch.
Der Host-Name wird dann zusammen mit dem Schlüssel lokal gespeichert.

* Um HTTPS zu verwenden, muss auf Ihrem Monitoring-Server HTTPS eingerichtet sein.
HTTP ist hier deutlich einfacher, bietet aber keine Verschlüsselung der Übertragung.
Da der Agent in Skripten und Konfigurationsdateien Passwörter enthalten kann, ist HTTPS der empfohlene Weg.
Die Authentizität des Agenten wird aber durch die Signatur unabhängig davon sichergestellt.

* Der Login als {CMK}-Administrator ist nur einmal erforderlich.
Agent und Server vereinbaren bei der Registrierung einen geheimen Schlüssel (_Host Secret_), der nur diesem Host bekannt ist.
Das Passwort des {CMK}-Administrators wird nirgendwo gespeichert.

* Während der interaktive Modus nur Felder abfragt, die in noch keiner Konfiguration vorhanden sind, lassen sich durch den nicht-interaktiven Modus alle in der Hilfe angezeigten Felder setzen und haben für diesen Aufruf die höchste Priorität.
Optionen, die nur in der Datei `cmk-update-agent.state` gespeichert sind, werden so überschrieben -- Optionen aus `cmk-update-agent.cfg` jedoch nicht. Mehr Details dazu gibt es weiter unten unter xref:agent_deployment#show_config[Einsehen der lokalen Konfiguration.]
//TK: Ungünstig, dass die beiden Dateien *.state und *.cfg schon hier erwähnt werden, bevor sie im nächsten Absatz erklärt werden.

Nach einer erfolgreichen Registrierung wird das Host Secret beim Agenten in der Datei `/etc/cmk-update-agent.state` gespeichert.
Auf dem Server liegt er dann in `~/var/check_mk/agent_deployment/myhost`.
Das Host Secret erlaubt von nun an dem Host *seinen eigenen* Agenten ohne Passwort vom Server herunterzuladen.
Ein Herunterladen von Agenten anderer Hosts ist nicht möglich (da diese vertrauliche Daten enthalten könnten).