// -*- coding: utf-8 -*-
include::global_attr.adoc[]

[#rest_api]
== REST-API-Anfragen für Hosts und Ordner

Viele der Aktionen, die in diesem Artikel beschrieben sind, können Sie auch mit der {CMK} REST-API ausführen.
Mit der REST-API statt der GUI zu arbeiten bietet sich an, um Anfragen per Kommandozeile oder Skript an den {CMK}-Server zu senden und von diesem auszuführen zu lassen.
Dies ist besonders dann interessant, wenn Sie viele Objekte in Ihrer Instanz zu verwalten haben und Aktionen automatisieren wollen, z.B. viele Hosts erstellen.

Wenn Kommandozeile, Skripte und APIs nicht Ihre Werkzeuge der 1. Wahl sind, reicht es an dieser Stelle aus zu wissen, dass es diese API gibt -- und damit ein mächtiges Hilfsmittel als Alternative zur Verwaltung über die GUI, auf das Sie bei Bedarf zurückgreifen können.

Im Artikel zur xref:rest_api#[REST-API] erhalten Sie eine Einführung zur Anwendung dieser API.
Zugriff auf die API-Dokumentation *und* auf eine xref:rest_api#rest_api_gui[REST-API GUI] haben Sie automatisch in Ihrer {CMK}-Instanz.
Mit der REST-API GUI können Sie sich mit der Syntax der Anfragen und der Struktur der Antworten vertraut machen.
Auf alle wichtigen Einträge zur REST-API können Sie in der {CMK}-GUI zugreifen über die Navigationsleiste im Menü [.guihint]#Help > Developer resources.#

Schließlich finden Sie im Artikel zur REST-API xref:rest_api.html#examples[Beispiele], wie Sie auf der Kommandozeile Aktionen für Hosts und Ordner ausführen können, z.B. die Ordnerstruktur und die Hosts eines Ordners anzeigen, einen Host in einem bestimmten Ordner erstellen und vieles mehr.
