// -*- coding: utf-8 -*-
include::global_attr.adoc[]

[#rest_api]
== REST-API-Anfragen für Hosts und Ordner

Viele der Aktionen, die in diesem Artikel beschrieben sind,
können Sie auch mit der {CMK} REST-API ausführen.
Dies ist besonders dann interessant, wenn Sie viele Objekte in Ihrer Instanz zu verwalten haben und
Aktionen automatisieren wollen, z.B. viele Hosts erstellen,
um die Fehleranfälligkeit oder den manuellen Wartungsaufwand zu reduzieren.

Wenn Kommandozeile, Skripte und APIs nicht Ihre Werkzeuge der 1. Wahl sind,
reicht es an dieser Stelle aus zu wissen, dass es diese API gibt -- und
damit ein mächtiges Hilfsmittel als Alternative zur Verwaltung über die Weboberfläche,
auf das Sie bei Bedarf zurückgreifen können.

Im Artikel zur xref:rest_api#[REST-API] erhalten Sie eine Einführung zur Anwendung dieser API und
die Referenz-Dokumentation finden Sie in der xref:rest_api#rest_api_gui[Weboberfläche] Ihrer {CMK}-Instanz.
Dort können Sie sich mit der Syntax der Anfragen und der Struktur der Antworten vertraut machen.
Auf alle wichtigen Einträge zur REST-API können Sie in der {CMK}-Weboberfläche über die Navigationsleiste im Menü [.guihint]#Help > Developer resources# zugreifen.

Schließlich finden Sie im Artikel zur REST-API xref:rest_api.html#examples[Beispiele],
wie Sie auf der Kommandozeile Aktionen für Hosts und Ordner ausführen können,
z.B. die Ordnerstruktur und die Hosts eines Ordners anzeigen,
einen Host in einem bestimmten Ordner erstellen und vieles mehr.
