// -*- coding: utf-8 -*-
include::global_attr.adoc[]


[#intro]
== Der neue Agent

Die Überwachung von Windows-Servern war von Anfang an eine der wichtigsten Aufgaben von {CMK}.
Wie für alle anderen Server-Betriebssysteme liefert {CMK} daher auch für Windows einen eigenen Agenten aus.

In der {CMK}-Version {v21} gibt es nun einen neuen Windows-Agenten.
Präziser gesagt, wird dem *Agentenprogramm* `check_mk_agent.exe` eine neue Komponente zur Seite gestellt: der *Agent Controller*.
Der Agent Controller ist dem Agentenprogramm vorgeschaltet, fragt dieses ab und kommuniziert an dessen Stelle mit dem {CMK}-Server.
Dazu registriert er sich am *Agent Receiver*, einem ebenfalls neuen Prozess, der auf dem {CMK}-Server läuft.

Der neue Windows-Agent übernimmt also zum einen das Agentenprogramm, und damit dessen Vorteile.
Zum anderen ergänzt er das Programm so, dass neue Funktionen hinzugefügt werden können wie die TLS-Verschlüsselung der Kommunikation, Datenkomprimierung -- und auch die Umkehrung der Kommunikationsrichtung.

Der registrierte, verschlüsselte und komprimierte *Pull-Modus* mit dem Agent Controller ist ab Version {v21} für alle {CMK}-Editionen verfügbar -- sofern sowohl {CMK}-Server als auch Agent Version mindestens {v21} haben.

Der Agent Controller ist nur auf bestimmten (neueren) Windows Versionen ausführbar.
Welche das sind, können Sie aus der nachfolgenden Tabelle ablesen.

Allerdings beherrscht der Agent auch einen sogenannten *Legacy-Modus*, um ältere Windows-Versionen zu unterstützen.
In diesem Modus arbeitet der neue wie der alte Agent, d.h. ohne Agent Controller und damit auch ohne Registrierung am {CMK}-Server.
Für den Legacy-Modus sind einige Besonderheiten zu beachten, die im xref:post_install[Installationskapitel] zusammengefasst sind.

Aus Kompatibilitätsgründen unterstützt der Agent nur die aktuellen Versionen der link:https://de.wikipedia.org/wiki/Microsoft_Windows_NT[Microsoft Windows NT^] Produktlinie (Edition).
Die folgende Tabelle listet diese explizit auf.
In der Spalte Version finden Sie den Anfang der Versionsnummer, die Sie sich mit den Kommandos `ver` und `systeminfo` auf dem Windows-System ausgeben lassen können.

[#windows_versions]
[cols="50,25,~",options="header"]
|===
|Edition |Version |Agent Controller
|Windows Vista |6.0 |ohne
|Windows Server 2008 (R1) |6.0 |ohne
|Windows 7 |6.1 |mit
|Windows Server 2008 R2 |6.1 |mit
|Windows 8 |6.2 |mit
|Windows Server 2012 (R1) |6.2 |mit
|Windows 8.1 |6.3 |mit
|Windows Server 2012 R2 |6.3 |mit
// TK: 6.4 statt 10.0 wurde nur bei Windows 10 Technical Preview 1-3 ausgegeben, das sollte für uns keine Rolle spielen
|Windows 10 |10.0  |mit
|Windows Server 2016 |10.0 |mit
|Windows Server 2019 |10.0 |mit
|Windows 11 |10.0  |mit
|Windows Server 2022 |10.0 |mit
|===

*Wichtig*: Editionen, die in der Tabelle nicht erwähnt werden, werden nicht offiziell unterstützt.
Dazu gehört zum Beispiel auch _Windows Embedded_.

Die Installation, Registrierung und Einrichtung des Agenten ist mit wenigen Schritten erledigt, denn dieser braucht für seine Funktion zum Beispiel keine zusätzlichen Bibliotheken.
Zudem wird der Agent mit einer Grundkonfiguration ausgeliefert, die für die meisten Anwendungsfälle ausreicht.
