// -*- coding: utf-8 -*-
include::global_attr.adoc[]


[#intro]
== Der neue Agent

Die Überwachung von Windows-Servern war von Anfang an eine der wichtigsten Aufgaben von {CMK}.
Wie für alle andere Server-Betriebssysteme liefert {CMK} daher auch für Windows einen eigenen Agenten aus.

In der {CMK} Version {v21} gibt es nun einen neuen Windows-Agenten.
Präziser gesagt, wird dem *Agentenprogramm* `check_mk_agent.exe` eine neue Komponente zur Seite gestellt: der *Agent Controller*.
Der Agent Controller ist dem Agentenprogramm vorgeschaltet, fragt dieses ab und kommuniziert an dessen Stelle mit dem {CMK} Server.
Dazu registriert er sich am *Agent Receiver*, einem ebenfalls neuen Prozess, der auf dem {CMK} Server läuft.

Der neue Windows-Agent übernimmt also zum einen das Agentenprogramm, und damit dessen Vorteile.
Zum anderen ergänzt er das Programm so, dass neue Funktionen hinzugefügt werden können wie die TLS-Verschlüsselung der Kommunikation, Datenkomprimierung -- und auch die Umkehrung der Kommunikationsrichtung.
Das bedeutet, dass zusätzlich zum registrierten, verschlüsselten und komprimierten *Pull-Modus* ein ebensolcher *Push-Modus* möglich ist.
Mehr dazu im nächsten Kapitel.

Während der Push-Modus ein Feature der nächsten {CMK} Version für die neue {CMK} Plus Edition (CPE) sein wird, ist TLS-Verschlüsselung und Komprimierung ab Version {v21} für alle {CMK} Editionen verfügbar -- sofern sowohl {CMK} Server als auch Agent Version {v21} haben.

// Der Agent Controller ist an den Superserver `systemd` gekoppelt, daher setzt er für die Registrierung am Agent Receiver eine Linux-Distribution mit `systemd` voraus.
Der Agent Controller setzt für die Registrierung am Agent Receiver bestimmte (neuere) Windows Versionen voraus.
// Wie Sie herausfinden, ob die Voraussetzung bei Ihrer Linux-Distribution erfüllt ist, erfahren sie im Kapitel xref:install[Installation.]
Welche das sind, können Sie aus der nachfolgenden Tabelle ablesen.

Allerdings unterstützt der neue Agent auch einen sogenannten *Legacy-Modus*, um auch unter älteren Windows-Versionen lauffähig zu sein.
In diesem Modus arbeitet der neue wie der alte Agent, d.h. ohne Agent Controller und damit auch ohne Registrierung am {CMK} Server.
// Zusatzinfo, dass man im Legacy-Modus die Registrierung auslassen kann und sonst wie bisher arbeiten kann?

// Aus Kompatibilitätsgründen werden nur die Hauptversionen von Windows unterstützt.
// Was ist mit Hauptversionen gemeint?
Aus Kompatibilitätsgründen unterstützt der Agent nur die Hauptversionen der link:https://de.wikipedia.org/wiki/Microsoft_Windows_NT[Microsoft Windows NT^] Produktlinie (Edition).
Die folgende Tabelle listet diese explizit auf.
In der Spalte Version finden Sie den Anfang der Versionsnummer, die Sie sich mit den Kommandos `ver` und `systeminfo` auf dem Windows-System ausgeben lassen können.

////
[cols=2]
|===
|Version |Edition

|NT 6.0 |Windows Vista
|NT 6.0 |Windows Server 2008
|NT 6.1 |Windows 7
|NT 6.1 |Windows 2008 R2
|NT 6.2 |Windows 8
|NT 6.2 |Windows Server 2012
|NT 6.3 |Windows 8.1
|NT 6.3 |Windows 2012 R2
|NT 6.4 / NT 10.0 |Windows 10
|NT 6.4 / NT 10.0 |Windows Server 2016
|NT 6.4 / NT 10.0 |Windows Server 2019
|===
////

[cols="50,25,~",options="header"]
|===
|Edition |Version |Agent Controller
|Windows Vista |6.0 |ohne
|Windows Server 2008 (R1) |6.0 |ohne
|Windows 7 |6.1 |ohne
|Windows Server 2008 R2 |6.1 |ohne
// TK: Bis hierhin ohne Agent Controller
|Windows 8 |6.2 |mit
|Windows Server 2012 (R1) |6.2 |mit
|Windows 8.1 |6.3 |mit
|Windows Server 2012 R2 |6.3 |mit
// TK: 6.4 statt 10.0 wurde nur bei Windows 10 Technical Preview 1-3 ausgegeben, das sollte für uns keine Rolle spielen
|Windows 10 |10.0  |mit
|Windows Server 2016 |10.0 |mit
|Windows Server 2019 |10.0 |mit
// TK: Was ist mit Windows Server 2022 (10.0) und Windows 11 (10.0)?
|===

*Wichtig*: Editionen, die in der Tabelle nicht erwähnt werden, werden nicht offiziell unterstützt.
Dazu gehört zum Beispiel auch _Windows Embedded_.

Die Installation, Registrierung und Einrichtung des Agenten ist mit wenigen Schritten erledigt, denn dieser braucht für seine Funktion zum Beispiel keine zusätzlichen Bibliotheken.
Zudem wird der Agent mit einer Grundkonfiguration ausgeliefert, die für die meisten Anwendungsfälle ausreicht.

// Explizite Ansage fehlt (noch), welche Kapitel für den Pull-Modus und welche für den Legacy-Modus relevant sind.
// Der Artikel, den Sie gerade lesen, behandelt Installation, Konfiguration und Erweiterungen des neuen Linux-Agenten *mit* Agent Controller.
