// -*- coding: utf-8 -*-
include::global_attr.adoc[]


[#registration]
== Registrierung

=== Voraussetzungen und Übersicht

Bei einer Neuinstallation des {CMK}-Agenten ist der Client, der ins Monitoring aufgenommen werden soll, noch nicht vom {CMK}-Server erreichbar. Der Grund ist, dass ein gegenseitiges Vertrauensverhältnis fehlt – Vertrauen und Verschlüsselung ist mit {CMK} {v21} Pflicht. Wie Sie das herstellen, zeigt dieser Abschnitt. Bei einem Update ist die Vorgehensweise prinzipiell gleich, auch wenn hier zunächst die unverschlüsselte Kommunikation zwischen {CMK} und dem Host ihm Monitoring möglich ist. In dem Fall zeigt Ihnen eine Warnung in der Diensteliste, dass eine Umstellung auf verschlüsselte Kommunikation angeraten ist.

Voraussetzung für Herstellung des gegenseitigen Vertrauensverhältnisses ist ein User für das Automatisierungs-API. Bei jeder {CMK}-Installation wird automatisch einer angelegt. Sie können diesen je nach organisatorischen Anforderungen entweder dauerhaft mit einem Passwort ausstatten oder Einmal-Tokens generieren.

=== Einen Host im Monitoring anlegen

Nehmen Sie zunächst den neuen Host über [.guihint]#Setup > Hosts > Add Host# ins Monitoring auf. Klicken Sie dann auf [.guihint]#1 Pending Change#, um dies mit [.guihint]#Activate on selected sites# zu aktivieren.

=== Vom Host eine Verbindung zum Server aufbauen

Nun begeben Sie sich zum Host, der ins Monitoring aufgenommen werden soll. Hier ist mit Root-Rechten eine Anfrage an die {CMK}-Site zu stellen. Wird der Hostnamen :

[{shell}]
----
{c-root} cmk-agent-ctl register --host-name mynewhost \
    --site-address cmkserver/mysite \
    --user automation --password test23
----

Dabei ist der Hostname hinter dem Parameter --host-name exakt so anzugeben, wie zuvor beim Aufnehmen ins Monitoring. Der Parameter --site-address gibt den Servernamen und den Site-Namen des {CMK}-Servers an. Servername darf auch die IP-Adresse sein, der Site-Name (hier "mysite") entspricht dem im URL-Pfad des Webinterfaces angegebenen. Waren die angegebenen Parameter korrekt, werden Sie aufgefordert, die Identität der {CMK}-Site, zu der Sie Verbindung aufnehmen wollen, zu bestätigen. Das zu bestätigende Server-Zertifikat haben wir aus Gründen der Übersichtlichkeit stark verkürzt:

[{shell-raw}]
----
Attempting to register at cmkserver:8000/mysite. Server certificate details:

PEM-encoded certificate:
---BEGIN CERTIFICATE---
MIIC6zCCAdOgAwIBAgIUXbSE8FXQfmFqoRNhG9NpHhlRJ40wDQYJKoZIhvcNAQEL
[...]
nS+9hN5ILfRI+wkdrQLC0vkHVYY8hGIEq+xTpG/Pxw==
---END CERTIFICATE---

Issued by:
	Site 'mysite' local CA
Issued to:
	localhost
Validity:
	From Thu, 10 Feb 2022 15:13:22 +0000
	To   Tue, 13 Jun 3020 15:13:22 +0000

Do you want to establish this connection? [Y/n]
> Y
----

Bestätigen Sie mit `Y`, um den Vorgang abzuschließen.

=== Überprüfung des Vertrauensverhältnisses

Der Befehl `cmk-agent-ctl status` zeigt nun genau ein Vertrauensverhältnis zum Server.

[{shell-raw}]
----
{c-root} cmk-agent-ctl status
Connection: 12.34.56.78:8000/mysite
	UUID: d38e7e53-9f0b-4f11-bbcf-d19617971595
	Local:
		Connection type: pull-agent
		Certificate issuer: Site 'mysite' local CA
		Certificate validity: Mon, 21 Feb 2022 11:23:57 +0000 - Sat, 24 Jun 3020 11:23:57 +0000
	Remote:
		Connection type: pull-agent
		Registration state: operational
		Host name: mynewhost
----

Anschließend können Sie am {CMK}-Server einen Service-Scan durchführen, die gefundenen Dienste ins Monitoring aufnehmen und schließlich erneut die Änderungen aktivieren.

=== Deregistrierung

Auf einem Host, der sich im Monitoring befindet, können Sie das Vertrauensverhältnis mit diesem Befehl widerrufen:


[{shell}]
----
{c-root} cmk-agent-ctl delete d38e7e53-9f0b-4f11-bbcf-d19617971595
----

Die anzugebende UUID ist dabei die von `cmk-agent-ctl status` ausgegebene. 

Auf dem {CMK}-Server existiert für jede Verbindung eines Hosts, der sich im Monitoring befindet, ein Softlink mit der UUID, welcher auf den Ordner mit dem Agenten-Output zeigt

[{shell-raw}]
----
{c-omd} cd ./var/agent-receiver/received-outputs
{c-omd} ls -l d38e7e53-9f0b-4f11-bbcf-d19617971595
lrwxrwxrwx 1 mysite mysite 67 Feb 23 07:18 d38e7e53-9f0b-4f11-bbcf-d19617971595 -> /omd/sites/mysite/tmp/check_mk/data_source_cache/push-agent/mynewhost
----

// REMOVE-AFTER-BETA
Wenn Sie diesen Softlink löschen, ist eine erneute Registrierung des Hosts im Monitoring erforderlich. Hier können Sie auch unbenutzte Softlinks löschen, die beispielsweise von mehreren Registrierungen desselben Hosts herrühren.

=== Registrierung im Auftrag

Zur leichteren Registrierung mehrerer Hosts im Monitoring kann ein beliebiger Host, auf dem `cmk-agent-ctl` installiert ist, eine Registrierung im Auftrag anderer durchführen.
Dabei wird eine JSON-Datei exportiert, die dann auf den Zielhost übertragen und dort importiert werden kann. 
Die Reihenfolge ist wie bei der Registrierung vom zu überwachenden Host aus: Es muss immer zuerst der Host im Monitoring angelegt werden.

Zunächst wir auf einem im Monitoring befindlichen Host die Registrierung stellvertretend durchgeführt, die JSON-Ausgabe leiten wir dabei in eine Datei um:

[{shell}]
----
{c-root} cmk-agent-ctl register-surrogate-pull \
    --host-name mynewhost3  \
    --site-address cmkserver/mysite \
    --user automation --password test23 \
    > /tmp/mynewhost3.json
----

Nun wird die Datei `/tmp/mynewhost3.json` auf den Host übertragen, für den wir die Registrierung durchgeführt haben und dort einfach importiert:

[{shell}]
----
{c-root} cmk-agent-ctl import /tmp/mynewhost3.json
----

