// -*- coding: utf-8 -*-
// IGNORE Downloadseite Monitoringdaten Nullmailer SMB Snakeoil TBD WebDAV Benachrichtigungs ED25519 p2 B12MS B2S B4MS B8MS 15% burstable
include::global_attr.adoc[]
= Installation aus dem Azure Marketplace
:revdate: draft
:title: Installation aus dem Azure Marketplace
:description: {CMK} bietet ein (fast) schlüsselfertiges Image im Azure Marketplace. In diesem Artikel erfahren Sie, wie Sie die Einrichtung abschließen.

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:install_packages#[{CMK}-Server installieren]
xref:update#[{CMK} aktualisieren]
{related-end}

== Willkommen bei {CMK} für Azure

Egal, ob Sie bereits langjähriger Nutzer von {CMK} sind, oder erst mit der Verfügbarkeit fertiger Images im Marketplace von Azure zu uns gefunden haben, Sie finden in diesem Handbuchartikel alle Ressourcen, um das vorbereitete VM Image zum für Ihre Bedürfnisse passenden Monitoring zu vervollständigen.

Wenn Sie neu bei {CMK} sind, empfehlen wir die vorbereitende Lektüre unseres xref:intro_setup#[Leitfadens für Einsteiger].
Vorkonfigurierte VM Images kürzen zwar viele Punkte bei der Installation ab, doch Kenntnis fundamentaler Konzepte, wie das der xref:glossar#site[Instanzen], hilft bei der Einrichtung.

=== Grundsätzliches

Falls Sie Nutzer des Azure Marketplaces sind, hatten Sie schon immer die Möglichkeit, ein im Marketplace link:https://learn.microsoft.com/en-us/azure/virtual-machines/linux/quick-create-portal?tabs=ubuntu[vorhandenes Ubuntu-Image^] mit {CMK} zu versehen und so "Monitoring in der Cloud" einzurichten.
{CMK} {v22} geht den nächsten Schritt und bietet link:https://azuremarketplace.microsoft.com/de-de/marketplace/apps/tribe29gmbh1665582614827.checkmk003?tab=Overview[vorinstallierte Images^] auf Basis von Ubuntu 22.04 (_Jammy Jellyfish_), bei denen alle Abhängigkeiten bereits erfüllt sind.
Hierbei kommt ausschließlich die xref:cce#[{CE}] zum Einsatz.
Diese befindet sich mit dem Einrichten der ersten Instanz im 30 Tage währenden Lizenzstatus "Trial", in dem keine Einschränkungen gelten.
Nach Ablauf des Testzeitraums kann {CMK} mit bis zu 750 überwachten Services auf einer einzigen Instanz ohne Subskription weiter genutzt werden.
Sollen mehr Services überwacht werden, benötigen Sie einen xref:license#license_cce[Lizenzschlüssel].

Generell ist die Einrichtung ein wenig aufwendiger als beispielsweise beim xref:introduction_docker#[Docker-Image], schließlich muss das bereitgestellte Image verschiedene Einsatzszenarien abdecken:

* Setup mit einer einzigen Instanz (_single site setup_) auf einem Server in verschiedenster Skalierung
* Zentralinstanz im verteilten Monitoring
* Remote-Instanz im verteilten Monitoring
* Mischbetrieb von produktiver Instanz und Instanz(en) zum Testen auf einem Host

Aus diesem Grund enthält das Azure Image weder eine vorbereitete Site, noch Mail- oder Firewall-Konfiguration.
In diesem Artikel führen wir Sie durch das komplette Setup.
Wo Hintergrundinformationen sinnvoll sind, verlinken wir in detaillierte Artikel des Handbuchs.

== Vorbereitung

Neben der Dimensionierung von RAM, Prozessor und virtueller Festplatte sollten Sie sich Gedanken um den Speicherort von Backups machen.
{CMK} unterstützt von Haus aus die Objektspeicher von Azure, daneben können Backups in Dateisystempfaden abgelegt werden, was Sicherungen auf SMB- oder WebDAV-Mounts ermöglicht oder den regelmäßigen Transfer per `rsync` erlaubt.

=== SSH-Schlüssel erstellen

Da Azure derzeit link:https://learn.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys[keine ED25519 oder ECDSA Schlüssel unterstützt^], werden Sie für das erste Login auf der virtuellen Maschine ein RSA-Schlüsselpärchen erstellen, dessen Public Key Sie beim Anlegen der VM hochladen.
Alternativ können Sie Azure das Schlüsselpaar erstellen lassen.
Vergessen Sie in diesem Fall nicht, den privaten Schlüssel im Laufe des Bestellverfahrens herunterzuladen. 

=== Benötigte Ports ermitteln

// Standardmäßig öffnet {CMK} Ports nur sparsam und nach expliziter Aktivierung benötigter Komponenten.
// Dennoch kann es sinnvoll sein, die verwendeten Ports weiter – zum Beispiel auf bestimmte IP-Adressen – einzuschränken.

In einer {CMK}-Konfiguration mit einer einzigen Instanz (_single site setup_), in der Hosts auch im Push-Modus Daten zur {CMK}-Instanz schicken, müssen die folgenden Ports des {CMK}-Servers erreichbar sein:

* Von den Hosts im Monitoring aus: Port 80/443 (HTTP/HTTPS, während der Agentenregistrierung) und Port 8000 (Agent Receiver, dauerhaft)
* Für die Verwaltung per Browser und REST-API: Port 80/443 (HTTP/HTTPS)

Die Freigaben dieser Ports sind in unseren _Inbound port rules_ bereits vorbereitet.
Für bestmögliche Sicherheit sollten Sie den Zugriff im Reiter _Networking_ weiter einschränken.

Konsultieren Sie unsere Übersicht xref:ports#[aller verwendeten Ports], falls Sie ein verteiltes Monitoring aufsetzen oder beispielsweise Statusabfragen über die xref:glossar#livestatus[Livestatus-Schnittstelle] vornehmen wollen.

=== Image im Marketplace buchen

_TBD:_ Was kann wie konfiguriert werden?

// Die vorgeschlagenen Parameter der kleinsten empfohlenen virtuellen Maschinen sind in typischen Einsatzszenarien für eine hohe dreistellige Zahl überwachter Hosts ausreichend.
//Diese Zahl kann höher ausfallen, wenn auf sehr effiziente Checks und Agentenplugins geachtet wird oder niedriger, wenn aufwendige Spezialagenten genutzt werden.
// Steht von vornherein fest, dass eine deutlich höhere Zahl an Services überwacht werden soll, können Sie die virtuelle Hardware entsprechend großzügiger dimensionieren.

Die folgenden VM-Instanzen stellen eine Empfehlung für die Dimensionierung dar.
Bitte beachten Sie beim Ordern der Instanz, die Option _burstable_ zu deaktivieren.

[cols="17,17,17,17,~",options="header"]
|===
|Typ |CPU Cores |RAM (GB) |SSD (GB) |{CMK} Services Empfehlung
| B2S | 2 | 4 | 8 | 3.000
| B4MS | 4 | 16 | 32 | 12.000
| B8MS | 8 | 32 | 64 | 30.000
| B12MS  | 12 | 48 | 96 | 60.000
|===

Kalkulationsgrundlage für die Dimensionierung waren ca. 15% der Services durch Spezialagenten und aktive Checks, sowie 25 oder mehr Services pro regulärem Host, der Daten per Agent im Push-Modus liefert.
Unter Umständen sind deutlich mehr Services in einem rein synthetischen Monitoring (primär Spezialagenten liefern Daten) möglich.
Bei Verwendung von Agenten im Pull-Modus ist die angegebene Zahl an Services möglicherweise nur durch konsequente Optimierung zu erreichen.

Die Dimensionierung des Festplattenplatzes basiert auf Erfahrungen typischer Windows- und Linux-Serverumgebungen.
Bringen viele Dienste eine große Zahl an Metriken mit, kann ein größerer xref:graphing#rrds[Speicherplatzbedarf] entstehen.

=== Backup-Speicher besorgen

_TBD:_ Details!

Wegen der günstigen Traffic-Kosten raten wir zur Nutzung der Azure Objektspeicher.
Für die Kalkulation des benötigten Speicherplatzes lesen Sie bitte die xref:graphing#rrds[Hinweise zum RRD Datenformat].


// MFS: Gemeinsamer Teil
include::include_common_aws_azure.asciidoc[]

== Nachbereitung

=== Backup

{CMK} bietet eine komfortable xref:backup#[Backup-Funktion], die Sie direkt im Setup konfigurieren können.

==== Einrichtung des Backups

_TBD:_ Details, Screenshot.

Bei der Nutzung innerhalb der Azure-Infrastruktur bietet sich natürlich die Nutzung des Azure-Objektspeichers als Backup-Ziel an.

==== Vorgehen beim Restore

Das xref:backup#backup_restore[Restore eines Backups] muss immer auf exakt derselben Version von {CMK} erfolgen wie dessen Erstellung.
Soll ein Backup dazu dienen, auf einen anderen Typ der virtuellen Maschine, zu einem anderen Cloud-Anbieter oder von einer _On Premise Installation_ in die Cloud (oder andersherum) umzuziehen, aktualisieren Sie _vor_ dem Umzug auf das höchste verfügbare Patchlevel von {CMK}.

Für das Restore eines Backups gilt damit:

. Installieren Sie auf dem Zielsystem exakt die Version von {CMK}, mit der das Backup erstellt wurde.
. Erstellen Sie mit `omd create` eine Monitoring-Site, die denselben Site-Namen wie das Ursprungssystem nutzt.
. Geben Sie das Backup-Ziel an und laden Sie den Backup-Schlüssel hoch.
. Führen Sie das eigentliche Restore durch.

== Azure überwachen

{CMK} bietet nicht nur die Verfügbarkeit als Azure-Image, sondern auch umfangreiche Möglichkeiten der xref:monitoring_azure#[Überwachung Ihrer Azure-Infrastruktur].
Selbst wenn {CMK} Ihr erstes oder einziges Azure-Projekt sein sollte, lohnt bereits Überwachung der Leistung der virtuellen Maschine, Zustand der Backup-Vaults und Höhe der anfallenden Kosten.


