= Installation unter Debian und Ubuntu
:revdate: 2020-06-03
:title: Details zur Installation auf Debian und Ubuntu
:description: Jede Distribution hat ihre Besondernheiten, die bei einer Softwareinstallation zu beachten sind. Hier wird im Detail beschrieben, was bei Debian und Ubuntu benötigt wird.

### SK: "Einrichten der Paketquellen" komplett weglassen oder doch kurz darauf hinweisen, dass Debian und Ubuntu einfach 1337 sind und deshalb keine weiteren Paketquellen eingerichtet werden müssen?!?
### SK: Ich bin für ganz weglassen.

###H1:Einrichten der Paketquellen

###Checkmk benötigt etliche Softwarepakete von Ihrer
###Linux-Distribution. Software aus dritten Quellen wird nicht benötigt. Damit
###alle benötigten Pakete korrekt nachinstalliert werden können, benötigen
###Sie eine korrekte Konfiguration der Softwarequellen. Das Vorgehen zum
###Einrichten unterscheidet sich je nach verwendeter Distribution:

###H2:Debian und Ubuntu

###Hier sind alle Paketquellen bereits eingerichtet und keine weiteren Schritte
###notwendig.

###SK: H1:Zusätzliche Sicherheitsmechanismen gemäß KNW-86 beschreiben
###SK: Hab ich leider zu spät gesehen diesen Hinweis. Muss ich nachliefern.


== Herunterladen des passenden Pakets

Wenn Sie eine Subskription besitzen, dann finden Sie in Ihrem
<a href="download.php">Subskriptionsbereich</a> zu jeder verfügbaren
[cmk_versionen|Checkmk-Version] ein passendes DEB-Paket für Ihre Distribution. Zum
kostenlosen Testen oder für kleinere Installationen von Checkmk können Sie auf
unsere <a href="download.php">kostenlosen Editionen</a> zurückgreifen. Diese
benötigen dann entsprechend auch keine Subskription, können jedoch jederzeit
problemlos durch ein [update#updatedemo|Upgrade] auf eine der (CEE) überführt
werden.

Bitte beachten Sie bei der Auswahl des Pakets:

* Wählen Sie die Version, die Distribution und zuletzt die Version der gewählten Distribution.
* Wir empfehlen den Einsatz der _letzten stabilen Version._ Falls Sie eine ältere Version benötigen, finden Sie diese im <a href="download-archive.php">Download-Archiv.</a>
* Name und Version Ihrer Distribution müssen exakt übereinstimmen.
* Wählen Sie die für Sie passende Edition aus. Falls Sie unsicher sind, verschaffen Sie sich zuerst einen Überblick über die Unterschiede zwischen den <a href="editions.html">Editionen.</a>

Nach dem Sie das Paket heruntergeladen haben, bringen Sie es auf das
Linux-System, auf dem Checkmk installiert werden soll. Das kann zum Beispiel über
das Programm _WinSCP_ geschehen, oder -- wenn Sie direkt ssh-Verbindungen
öffnen können -- über das Kommandozeilentool `scp`.

Für eine Übertragung mithilfe von `scp` muss auf dem zukünftigen
(CMK)-Server das Paket openssh-server installiert sein. Sollte dies noch nicht
der Fall, so führen Sie bitte den folgenden Befehl aus, um openssh-server
einzurichten:

[source,bash]
----
root@linux:~$ apt-get install openssh-server
----

Anschließend können Sie beispielsweise die (CRE) für
_Ubuntu 20.04 (focal fossa)_ wie folgt übertragen:

[source,bash]
----
root@linux:~$ scp check-mk-raw-1.6.0p13_0.focal_amd64.deb root@mymonitoring.mydomain.org:
----


[#signed]
== Installation des signierten Pakets

Alle Pakete werden mittels <a href="https://gnupg.org">GnuPG</a> signiert. Durch
diese Signatur können Sie zum einen prüfen, ob das Paket auch wirklich von uns
stammt und zum anderen, ob das Paket insgesamt vollständig ist.

Je nachdem mit welchen optionalen Paketen Ihre Distribution installiert wurde,
muss für eine erfolgreiche Verifikation noch das Paket dpkg-sig inklusive seiner
Abhängigkeiten installiert werden. Führen Sie dazu den folgenden Befehl aus:

[source,bash]
----
root@linux:~$ apt-get install dpkg-sig
----

Damit diese signierten Pakete wie gewohnt installiert werden können,
müssen Sie einmalig unseren öffentlichen Schlüssel importieren, damit
der Signatur vertraut wird. Laden Sie dazu zuerst den Schlüssel entweder
direkt von unserer Internetseite:

[source,bash]
----
root@linux:~$ wget https://checkmk.com/support/Check_MK-pubkey.gpg
----

Alternativ können Sie den Key aber auch über <a
href="http://keys.gnupg.net">keys.gnupg.net</a> beziehen:

[source,bash]
----
root@linux:~$ gpg --keyserver keys.gnupg.net --recv-keys 434DAC48C4503261
root@linux:~$ gpg --armor --export 434DAC48C4503261 > Check_MK-pubkey.gpg
----

Danach importieren Sie den Schlüssel in die Liste der vertrauenswürdigen
Signaturen. Unter Debian und Ubuntu benötigen Sie dafür den folgenden Befehl:

[source,bash]
----
root@linux:~$ gpg --import Check_MK-pubkey.gpg
----

Sobald Sie den Schlüssel importiert haben, verifizieren Sie das Checkmk-Paket mit
dem folgenden Befehl:

[source,bash]
----
root@linux:~$ dpkg-sig --verify check-mk-enterprise-1.6.0p13_0.buster_amd64.deb
----

Installieren Sie nun zunächst das Paket `gdebi-core`. Dieses Tool stellt
sicher, dass nicht nur das Paket mit dem Checkmk Monitoring System, sondern auch
alle Abhängigkeiten korrekt installiert werden:

[source,bash]
----
root@linux:~$ apt-get install gdebi-core
----

Installieren Sie anschließend das Checkmk-Paket mittels `gdebi`:

[source,bash]
----
root@linux:~$ gdebi check-mk-enterprise-1.6.0p13_0.buster_amd64.deb
----


== Abschlusstest

Nach der erfolgreichen Installation von Checkmk und allen Abhängigkeiten
steht Ihnen der Befehl `omd` zur Verfügung, mit dem Sie
[omd_basics|Monitoring-Instanzen] anlegen und verwalten können. Zur Kontrolle
können Sie die installierte Version ausgeben lassen:

[source,bash]
----
root@linux:~$ omd version
OMD - Open Monitoring Distribution Version 1.6.0p13.cee
----