include::global_attr.adoc[]
= Installation unter SUSE Linux Enterprise Server
:revdate: 2020-06-03
:title: Details zur Installation auf SLES
:description: Jede Distribution hat ihre Besondernheiten, die bei einer Softwareinstallation zu beachten sind. Hier wird im Detail beschrieben, was bei SLES dafür benötigt wird.

{related-start}
link:intro.html[Das offizielle Handbuch zu {CMK}]
link:checkmk_getting_started.html[Schnelleinstieg ins Monitoring]
link:introduction_virt1.html[Installation der virtuellen Appliance]
{related-end}


== Einrichten der Paketquellen

{CMK} benötigt etliche Softwarepakete von Ihrer Linux-Distribution. Software aus
Drittquellen wird nicht benötigt. Damit alle benötigten Pakete korrekt
nachinstalliert werden können, benötigen Sie eine korrekte Konfiguration der
Softwarequellen. Das Vorgehen zum Einrichten unterscheidet sich je nach
verwendeter Version von SLES ein wenig.

// SK: Den SLES 11 Abschnitt lasse ich vorerst mal zähneknirschend drin...

[#sles11]
=== SLES 11

Leider hat SUSE einige wichtige Pakete auf eine separate DVD ausgelagert. Diese
trägt den Namen _SUSE Linux Enterprise SDK._ Richten Sie diese mit
YaST als zweite Paketquelle ein. Bitte verwechseln Sie das SDK nicht mit der
DVD 2 der normalen Installations-DVD. Letztere enthält die Quellcodes der
Software und wird nicht benötigt. Wenn Sie eine gültige Subskription für SLES
haben, dann können Sie das ISO-Image des SDK direkt auf der Webseite von
link:https://download.suse.com/[SUSE] herunterladen.

[#sles12]
=== SLES 12

Mit SLES 12 wurden einige Softwarekomponenten, wie z.B. PHP, das von OMD
benötigt wird, in sogenannte Module ausgelagert. Damit Sie Zugriff auf die
PHP-Pakete von SLES 12 bekommen, müssen Sie folgende Schritte ausführen:

* link:https://documentation.suse.com/de-de/sles/12-SP4/html/SLES-all/cha-planning.html#sec-planning-registering[SLES 12 registrieren]
* link:https://documentation.suse.com/de-de/sles/12-SP4/html/SLES-all/cha-add-ons.html#sec-add-ons-installation[Das Modul „Web and Scripting“ installieren]


[#sles15]
=== SLES 15

Unter SLES 15 müssen Sie zusätzlich zu _Web and Scripting_ noch die Module
_Development Tools_ und _SUSE Package Hub 15_ installieren.

* link:https://documentation.suse.com/de-de/sles/15-SP1/html/SLES-all/cha-register-sle.html[Registrieren von SLES 15 und Verwalten von Modulen]


== Herunterladen des passenden Pakets

Wenn Sie eine Subskription besitzen, dann finden Sie in Ihrem
link:https://checkmk.de/download.php[Subskriptionsbereich] zu jeder verfügbaren
link:cmk_versions.html[{CMK}-Version] ein passendes RPM- bzw. DEB-Paket für Ihre
Distribution. Zum kostenlosen Testen oder für kleinere Installationen von
{CMK} können Sie auf unsere link:https://checkmk.de/download.php[kostenlosen Editionen]
zurückgreifen. Diese benötigen dann entsprechend auch keine Subskription,
können jedoch jederzeit problemlos durch ein link:update.html#updatedemo[Upgrade]
auf eine der {CEE} überführt werden.

Bitte beachten Sie bei der Auswahl des Pakets:

* Wählen Sie die {CMK}-Version, die Distribution und zuletzt die Version der gewählten Distribution.
* Wir empfehlen den Einsatz der _letzten stabilen Version._ Falls Sie eine ältere Version benötigen, finden Sie diese im link:https://checkmk.de/download-archive.php[Download-Archiv.]
* Name und Version Ihrer Distribution müssen exakt übereinstimmen.
* Wählen Sie die für Sie passende Edition aus. Falls Sie unsicher sind, verschaffen Sie sich zuerst einen Überblick über die Unterschiede zwischen den link:https://checkmk.de/editions.html[Editionen.]

Nach dem Sie das Paket heruntergeladen haben, bringen Sie es auf das
Linux-System, auf dem {CMK} installiert werden soll. Das kann zum Beispiel über
das Programm _WinSCP_ geschehen, oder -- wenn Sie direkt ssh-Verbindungen
öffen können -- über das Kommandozeilentool `scp`. Hier an dem Beispiel
der {CRE} für _SLES 15:_

[{shell}]
----
{c-root} scp check-mk-raw-1.6.0p12-sles15-38.x86_64.rpm root@mymonitoring.mydomain.org:
----


[#signed]
== Installation des signierten Pakets

Alle Pakete werden mittels link:https://gnupg.org[GnuPG] signiert.
Durch diese Signatur können
Sie zum einen prüfen, ob das Paket auch wirklich von uns stammt. Und zum anderen,
ob das Paket insgesamt vollständig ist.

Damit diese signierten Pakete wie gewohnt installiert werden können,
müssen Sie einmalig unseren öffentlichen Schlüssel importieren, damit
der Signatur vertraut wird. Laden Sie dazu zuerst den Schlüssel entweder
direkt von unserer Internetseite:

[{shell}]
----
{c-root} wget \https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

Alternativ können Sie den Key aber auch über
link:http://keys.gnupg.net[gnupg.net] beziehen:

[{shell}]
----
{c-root} gpg --keyserver keys.gnupg.net --recv-keys 434DAC48C4503261
{c-root} gpg --armor --export 434DAC48C4503261 > Check_MK-pubkey.gpg
----

Danach importieren Sie den Schlüssel in die Liste der vertrauenswürdigen
Signaturen. Unter SUSE Linux Enterprise Server ist dafür das Tool `rpm`
zuständig:

[{shell}]
----
{c-root} rpm --import Check_MK-pubkey.gpg
----

Sobald Sie den Schlüssel importiert haben, können Sie das {CMK}-Paket nun noch
einmal verifizieren und anschließend mit dem Tool `zypper` installieren:

[{shell}]
----
{c-root} rpm -K check-mk-enterprise-1.6.0p12-sles15-38.x86_64.rpm
check-mk-enterprise-1.6.0p12-sles15-38.x86_64.rpm: digests signatures OK
{c-root} zypper install check-mk-enterprise-1.6.0p12-sles15-38.x86_64.rpm
----

//SK: Wenn wir die Pakete schon signieren und auch beschreiben, wie man unseren PublicKey importiert und die Signatur dann prüft, möchte ich eigentlich gar nicht beschreiben, wie man das dann ohne gpg-check installieren kann.
//RP:zypper install --no-gpg-checks check-mk-enterprise-1.6.0p12-sles15-38.x86_64.rpm
//*Wichtig*: Wenn Sie ein signiertes Paket von uns benutzen, sollten
//Sie die Option `--no-gpg-checks` natürlich weglassen.

== Abschlusstest

Nach der erfolgreichen Installation von {CMK} und allen Abhängigkeiten
steht Ihnen der Befehl `omd` zur Verfügung, mit dem Sie
link:omd_basics.html[Monitoring-Instanzen] anlegen und verwalten können. Zur Kontrolle
können Sie die installierte Version ausgeben lassen:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version 1.6.0p12.cee
----

