= Installation unter Red Hat und CentOS
:revdate: 2020-06-03
:title: Details zur Installation auf Red Hat und CentOS
:description: Jede Distribution hat ihre Besondernheiten, die bei einer Softwareinstallation zu beachten sind. Hier wird im Detail beschrieben, was bei Red Hat und CentOS dafür benötigt wird.

### SK: Was macht eigentlich MD? Steht gar nichts im internal_syntax...

== Einrichten der Paketquellen

(CMK) benötigt etliche Softwarepakete von Ihrer Linux-Distribution. Software aus
Drittquellen wird nicht benötigt. Damit alle benötigten Pakete korrekt
nachinstalliert werden können, benötigen Sie eine korrekte Konfiguration der
Softwarequellen. Bei Red Hat und CentOS muss das _EPEL (Extra Packages for
Enterprise Linux)_-Repository als Paketquelle eingerichtet werden. Dies
geschieht mit Hilfe eines RPM-Pakets, welches mit dem Befehl `yum`
installiert wird:

[cols=10, options="header"]
|===

|Version
|Paketlink


|`6`
|`https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm`


|`7`
|`https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`


|`8`
|`https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`

|===

Hier ein Beispiel für die Installation unter CentOS 8:

[source,bash]
----
root@linux:~$ yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----

Damit Sie EPEL auf Red Hat und CentOS nutzen können, benötigen Sie noch die
Paketquelle für optionale RPMs, sofern diese nicht bereits bei der Installation
des Betriebssystems eingerichtet worden ist. Ohne diese Quelle werden Ihnen die
Pakete `freeradius-utils`, `graphviz-gd` und
`php-mbstring` fehlen. Ab Version 8.x genügt hier die Aktivierung der
sogenannten PowerTools mithilfe des Dandified YUM in CentOS bzw. dem
`subscription-manager` in RHEL. Dies geht z.B. mit folgenden Befehlen:

Red Hat/CentOS 6.X:

[source,bash]
----
root@linux:~$ yum-config-manager --enable rhel-6-server-optional-rpms
root@linux:~$ subscription-manager repos --enable rhel-6-server-optional-rpms
----

Red Hat/CentOS 7.X

[source,bash]
----
root@linux:~$ yum-config-manager --enable rhel-7-server-optional-rpms
root@linux:~$ yum-config-manager --enable rhel-7-server-extras-rpms
root@linux:~$ subscription-manager repos --enable rhel-7-server-optional-rpms
root@linux:~$ subscription-manager repos --enable rhel-7-server-extras-rpms
----

CentOS 8.X:

[source,bash]
----
root@linux:~$ dnf config-manager --set-enabled PowerTools
----

Red Hat 8.x:

[source,bash]
----
root@linux:~$ subscription-manager repos --enable "codeready-builder-for-rhel-8-x86_64-rpms"
----

### SK: Auflistung der Paketquellen?!? Warum? Ist das für die Installation wichtig oder ist es interessant?
### SK: Plus: Das funktioniert unter 8.x ohne die vorherige Installation von subscription-manager ohnehin nicht.
###Eine Auflistung aller verfügbaren Paketquellen erhalten Sie mit:
###
###C+:
###RP:subscription-manager repos --list
###C-:


== Einrichten von SELinux und Firewall

Da Red Hat und damit auch CentOS standardmäßig SELinux und eine lokale Firewall
mitliefern, müssen hier gegebenenfalls noch Anpassungen vorgenommen werden.
Erlauben Sie zunächst, dass der Webserver auf die Netzwerkschnittstellen
zugreifen darf:

[source,bash]
----
root@linux:~$ setsebool -P httpd_can_network_connect 1
----

Als Zweites geben Sie den Webserver frei und aktivieren die Änderung:

[source,bash]
----
root@linux:~$ firewall-cmd --zone=public --add-service=http --permanent
success
root@linux:~$ firewall-cmd --reload
success
----


== Herunterladen des passenden Pakets

Wenn Sie eine Subskription besitzen, dann finden Sie in Ihrem <a
href="download.php">Subskriptionsbereich</a> zu jeder verfügbaren
[cmk_versionen|Checkmk-Version] ein passendes RPM- bzw. DEB-Paket für Ihre
Distribution. Zum kostenlosen Testen oder für kleinere Installationen von
(CMK) können Sie auf unsere <a href="download.php">kostenlosen Editionen</a>
zurückgreifen. Diese benötigen dann entsprechend auch keine Subskription,
können jedoch jederzeit problemlos durch ein [update#updatedemo|Upgrade]
auf eine der (CEE) überführt werden.

Bitte beachten Sie bei der Auswahl des Pakets:

* Wählen Sie die Checkmk-Version, die Distribution und zuletzt die Version der gewählten Distribution.
* Wir empfehlen den Einsatz der _letzten stabilen Version._ Falls Sie eine ältere Version benötigen, finden Sie diese im <a href="download-archive.php">Download-Archiv.</a>
* Name und Version Ihrer Distribution müssen exakt übereinstimmen.
* Wählen Sie die für Sie passende Edition aus. Falls Sie unsicher sind, verschaffen Sie sich zuerst einen Überblick über die Unterschiede zwischen den <a href="editions.html">Editionen.</a>

Nachdem Sie das Paket heruntergeladen haben, bringen Sie es auf das
Linux-System, auf dem Checkmk installiert werden soll. Das kann zum Beispiel über
das Programm _WinSCP_ geschehen, oder -- wenn Sie direkt ssh-Verbindungen
öffen können -- über das Kommandozeilentool `scp`. Hier an dem Beispiel
der (CRE) für _CentOS 8.x:_

[source,bash]
----
root@linux:~$ scp check-mk-raw-1.6.0p12-el8-38.x86_64.rpm root@mymonitoring.mydomain.org:
----


[#signed]
== Installation des signierten Pakets

Alle Pakete werden mittels <a href="https://gnupg.org">GnuPG</a> signiert.
Durch diese Signatur können Sie zum einen prüfen, ob das Paket auch wirklich von uns stammt.
Und zum anderen, ob es insgesamt vollständig ist.

Damit diese signierten Pakete wie gewohnt installiert werden können,
müssen Sie einmalig unseren öffentlichen Schlüssel importieren, damit
der Signatur vertraut wird. Laden Sie dazu zuerst den Schlüssel
direkt von unserer Internetseite:

[source,bash]
----
root@linux:~$ wget https://checkmk.com/support/Check_MK-pubkey.gpg
----

Alternativ können Sie den Key aber auch über <a href="http://keys.gnupg.net">gnupg.net</a>
beziehen:

[source,bash]
----
root@linux:~$ gpg --keyserver keys.gnupg.net --recv-keys 434DAC48C4503261
root@linux:~$ gpg --armor --export 434DAC48C4503261 > Check_MK-pubkey.gpg
----

Danach importieren Sie den Schlüssel in die Liste der vertrauenswürdigen
Signaturen. Unter Red Hat und CentOS ist auch dafür das Tool `rpm`
zuständig:

[source,bash]
----
root@linux:~$ rpm --import Check_MK-pubkey.gpg
----

Sobald Sie den Schlüssel importiert haben, können Sie das Paket noch einmal
verifizieren und anschließend wie gewohnt mit `yum install` installieren:

[source,bash]
----
root@linux:~$ rpm -K check-mk-enterprise-1.6.0p12-el8-38.x86_64.rpm
check-mk-enterprise-1.6.0p12-el8-38.x86_64.rpm: digests signatures OK
root@linux:~$ yum install check-mk-enterprise-1.6.0p12-el8-38.x86_64.rpm
----


== Abschlusstest

Nach der erfolgreichen Installation von Checkmk und allen Abhängigkeiten
steht Ihnen der Befehl `omd` zur Verfügung, mit dem Sie
[omd_basics|Monitoring-Instanzen] anlegen und verwalten können. Zur Kontrolle
können Sie die installierte Version ausgeben lassen:

[source,bash]
----
root@linux:~$ omd version
OMD - Open Monitoring Distribution Version 1.6.0p12.cee
----