// -*- coding: utf-8 -*-
// IGNORE Downloadseite Monitoringdaten Nullmailer SMB Snakeoil TBD WebDAV Benachrichtigungs
include::global_attr.adoc[]
= Installation als Azure-Image
:revdate: draft
:title: Installation als Azure-Image
:description: {CMK} bietet (fast) schlüsselfertige Images im Azure Marketplace. In diesem Artikel erfahren Sie, wie Sie die Einrichtung abschließen.

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:install_packages#[{CMK}-Server installieren]
xref:update#[{CMK} aktualisieren]
{related-end}

== Willkommen bei {CMK} für Azure

Egal, ob Sie bereits langjähriger Nutzer von {CMK} sind, oder erst mit der Verfügbarkeit fertiger Images im Marketplace von Azure zu uns gefunden haben, Sie finden in diesem Handbuchartikel alle Ressourcen, um das vorbereitete VM Image zum für Ihre Bedürfnisse passenden Monitoring zu vervollständigen.

Wenn Sie neu bei {CMK} sind, empfehlen wir die vorbereitende Lektüre unseres xref:intro_setup#[Leitfadens für Einsteiger].
Vorkonfigurierte VM Images kürzen zwar viele Punkte bei der Installation ab, doch Kenntnis fundamentaler Konzepte, wie das der xref:glossar#site[Sites], hilft bei der Einrichtung.

=== Grundsätzliches

Falls Sie Nutzer des Azure Marketplaces sind, hatten Sie schon immer die Möglichkeit, ein im Marktplatz vorhandenes Ubuntu-Image mit {CMK} zu versehen und so "Monitoring in der Cloud" einzurichten.
{CMK} {v22} geht den nächsten Schritt und bietet vorinstallierte Images, bei denen alle Abhängigkeiten bereits erfüllt sind.
Hierbei kommt ausschließlich die xref:cce#[{CE}] zum Einsatz.
Diese befindet sich mit dem Einrichten der ersten Site in einem 30 Tage währenden Testmodus, in dem keine Einschränkungen gelten.
Nach Ablauf der Testphase kann {CMK} mit bis zu 750 überwachten Diensten (als Single Site) ohne Subskription weiter genutzt werden.
Sollen mehr Dienste überwacht werden, benötigen Sie einen xref:license#license_cce[Lizenzschlüssel].

Generell ist die Einrichtung ein wenig aufwendiger als beispielsweise beim xref:introduction_docker#[Docker-Image], schließlich muss das bereitgestellte Image verschiedene Einsatzszenarien abdecken:

* Single Site Setup auf einem Host in verschiedenster Skalierung
* Central Site im Distributed Monitoring
* Remote Site im Distributed Monitoring
* Mischbetrieb von produktiver Site und Site(s) zum Testen auf einem Host

Aus diesem Grund enthält das Azure Image weder eine vorbereitete Site, noch Mail- oder Firewall-Konfiguration.
In diesem Artikel führen wir Sie durch das komplette Setup.
Wo Hintergrundinformationen sinnvoll sind, verlinken wir in detaillierte Artikel des Handbuchs.

== Vorbereitung

Neben der Dimensionierung von RAM, Prozessor und virtueller Festplatte sollten Sie sich Gedanken um den Speicherort von Backups machen.
{CMK} unterstützt von Haus aus die Objektspeicher von Azure, daneben können Backups in Dateisystempfaden abgelegt werden, was Sicherungen auf SMB- oder WebDAV-Mounts ermöglicht oder den regelmäßigen Transfer per `rsync` erlaubt.

=== Image im Marketplace buchen

_TBD_

Die vorgeschlagenen Parameter der kleinsten empfohlenen virtuellen Maschinen sind in typischen Einsatzszenarien für eine hohe dreistellige Zahl überwachter Hosts ausreichend.
Natürlich kann diese Zahl höher ausfallen, wenn auf sehr effiziente Checks und Agentenplugins geachtet wird oder niedriger, wenn aufwendige Spezialagenten genutzt werden.
Steht von vornherein fest, dass eine deutlich höhere Zahl an Services überwacht werden soll, können Sie die virtuelle Hardware entsprechend großzügiger dimensionieren.

=== Backup-Speicher besorgen

_TBD:_ Details!

Wegen der günstigen Traffic-Kosten raten wir zur Nutzung der Azure Objektspeicher.
Für die Kalkulation des benötigten Speicherplatzes lesen Sie bitte die xref:graphing#rrds[Hinweise zum RRD Datenformat].


// MFS: Gemeinsamer Teil
include::include_common_aws_azure.asciidoc[]

== Nachbereitung

=== Backup

{CMK} bietet eine komfortable xref:backup#[Backup-Funktion], die Sie direkt im Setup konfigurieren können.

==== Einrichtung des Backups

_TBD:_ Details, Screenshot.

Bei der Nutzung innerhalb der Azure-Infrastruktur bietet sich natürlich die Nutzung des Azure-Objektspeichers als Backup-Ziel an.

==== Vorgehen beim Restore

Das xref:backup#backup_restore[Restore eines Backups] muss immer auf exakt derselben Version von {CMK} erfolgen wie dessen Erstellung.
Soll ein Backup dazu dienen, auf einen anderen Typ der virtuellen Maschine, zu einem anderen Cloud-Anbieter oder von einer _On Premise Installation_ in die Cloud (oder andersherum) umzuziehen, aktualisieren Sie _vor_ dem Umzug auf das höchste verfügbare Patchlevel von {CMK}.

Für das Restore eines Backups gilt damit:

. Installieren Sie auf dem Zielsystem exakt die Version von {CMK}, mit der das Backup erstellt wurde.
. Erstellen Sie mit `omd create` eine Monitoring-Site, die denselben Site-Namen wie das Ursprungssystem nutzt.
. Geben Sie das Backup-Ziel an und laden Sie den Backup-Schlüssel hoch.
. Führen Sie das eigentliche Restore durch.

=== Azure überwachen

{CMK} bietet nicht nur die Verfügbarkeit als Azure-Image, sondern auch umfangreiche Möglichkeiten der xref:monitoring_azure#[Überwachung Ihrer Azure-Infrastruktur].
Selbst wenn {CMK} Ihr erstes oder einziges Azure-Projekt sein sollte, lohnt bereits Überwachung der Leistung der virtuellen Maschine, Zustand der Backup-Vaults und Höhe der anfallenden Kosten.


