// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Installation unter SUSE Linux Enterprise Server
:revdate: 2022-05-17
:title: Installation unter SUSE Linux Enterprise Server
:description: Hier erfahren Sie, wie Sie {CMK} unter der Linux-Distribution von SUSE Linux Enterprise Server (SLES) installieren.

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:appliance_install_virt1#[Virtuelle Appliance installieren]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
{related-end}


== Einrichten der Paketquellen

{CMK} benötigt etliche Software-Pakete Ihrer Linux-Distribution.
Software aus Drittquellen wird nicht benötigt.
Damit alle benötigten Pakete korrekt nachinstalliert werden können, benötigen Sie eine korrekte Konfiguration der Software-Quellen.

Das Vorgehen zum Einrichten unterscheidet sich je nach verwendeter Version von SUSE Linux Enterprise Server (SLES) ein wenig.


[#sles12]
=== SLES 12

Mit SLES 12 wurden einige Software-Komponenten, wie z.B. PHP, das von OMD benötigt wird, in sogenannte Module ausgelagert.
Damit Sie Zugriff auf die PHP-Pakete von SLES 12 bekommen, müssen Sie folgende Schritte ausführen:

* link:https://documentation.suse.com/de-de/sles/12-SP4/html/SLES-all/cha-planning.html#sec-planning-registering[SLES 12 registrieren^]
* link:https://documentation.suse.com/de-de/sles/12-SP4/html/SLES-all/cha-add-ons.html#sec-add-ons-installation[Das Modul „Web and Scripting“ installieren^]


[#sles15]
=== SLES 15

Unter SLES 15 müssen Sie zusätzlich zum Modul „Web and Scripting“ noch die Module „Development Tools“ und „SUSE Package Hub 15“ installieren:

* link:https://documentation.suse.com/de-de/sles/15-SP1/html/SLES-all/cha-register-sle.html[Registrieren von SLES 15 und Verwalten von Modulen^]


== Herunterladen des passenden Pakets

Wenn Sie eine Subskription besitzen, dann finden Sie im link:https://portal.checkmk.com/de/[Kundenportal^] zu jeder verfügbaren xref:cmk_versions#[{CMK}-Version] ein passendes RPM- bzw. DEB-Paket für Ihre
Distribution.
Zum kostenlosen Testen oder für kleinere Installationen von {CMK} können Sie auf unsere link:https://checkmk.com/de/download[kostenlosen Editionen^] zurückgreifen.
Diese benötigen dann entsprechend auch keine Subskription, können jedoch jederzeit problemlos durch ein xref:update#updatedemo[Upgrade] auf eine der {CEE} überführt werden.

Beachten Sie bei der Auswahl des Pakets:

* Wählen Sie die für Sie passende Edition aus.
Falls Sie unsicher sind, verschaffen Sie sich zuerst einen Überblick über die Unterschiede zwischen den link:https://checkmk.com/de/produkt/editionen[Editionen.^]
* Wählen Sie die {CMK}-Version, die Distribution und zuletzt die Version der gewählten Distribution.
* Wir empfehlen den Einsatz der _letzten stabilen {CMK}-Version._
Falls Sie eine ältere Version benötigen, finden Sie diese im link:https://checkmk.com/de/download/archive/[Download-Archiv.^]
* Name und Version Ihrer Distribution müssen exakt übereinstimmen.
// TK: Versteh ich nicht: Was muss hier exakt übereinstimmen?

Nachdem Sie das Paket heruntergeladen haben, bringen Sie es auf das Linux-System, auf dem {CMK} installiert werden soll.
Das kann zum Beispiel über das Programm _WinSCP_ geschehen, oder -- wenn Sie direkt SSH-Verbindungen öffnen können -- über das Kommandozeilentool `scp`,
im folgenden Beispiel für die {CRE} auf SLES 15:

[{shell}]
----
{c-root} scp check-mk-raw-2.1.0p1-sles15-38.x86_64.rpm root@mymonitoring.mydomain.org:
----


[#signed]
== Installation des signierten Pakets

Alle Pakete werden mittels link:https://gnupg.org[GnuPG^] signiert.
Durch diese Signatur können Sie zum einen prüfen, ob das Paket auch wirklich von uns stammt, und zum anderen, ob es insgesamt vollständig ist.

Damit diese signierten Pakete wie gewohnt installiert werden können, müssen Sie einmalig unseren öffentlichen Schlüssel importieren, damit der Signatur vertraut wird.
Laden Sie dazu zuerst den Schlüssel direkt von unserer Website:

[{shell-raw}]
----
{c-root} wget https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

////
Alternativ können Sie den Schlüssel aber auch über link:http://keys.gnupg.net[gnupg.net^] beziehen:

[{shell}]
----
{c-root} gpg --keyserver keys.gnupg.net --recv-keys 434DAC48C4503261
{c-root} gpg --armor --export 434DAC48C4503261 > Check_MK-pubkey.gpg
----
////

Danach importieren Sie den Schlüssel in die Liste der vertrauenswürdigen Signaturen.
Unter SLES ist dafür das Tool `rpm` zuständig:

[{shell}]
----
{c-root} rpm --import Check_MK-pubkey.gpg
----

Sobald Sie den Schlüssel importiert haben, können Sie das {CMK}-Paket nun noch einmal verifizieren und anschließend mit dem Tool `zypper` installieren:

[{shell}]
----
{c-root} rpm -K check-mk-raw-2.1.0p1-sles15-38.x86_64.rpm
check-mk-raw-2.1.0p1-sles15-38.x86_64.rpm: digests signatures OK
{c-root} zypper install check-mk-raw-2.1.0p1-sles15-38.x86_64.rpm
----

//SK: Wenn wir die Pakete schon signieren und auch beschreiben, wie man unseren PublicKey importiert und die Signatur dann prüft, möchte ich eigentlich gar nicht beschreiben, wie man das dann ohne gpg-check installieren kann.
//RP: zypper install --no-gpg-checks check-mk-enterprise-1.6.0p12-sles15-38.x86_64.rpm
//*Wichtig*: Wenn Sie ein signiertes Paket von uns benutzen, sollten Sie die Option `--no-gpg-checks` natürlich weglassen.


== Abschlusstest

Nach der erfolgreichen Installation von {CMK} und allen Abhängigkeiten steht Ihnen der Befehl `omd` zur Verfügung, mit dem Sie xref:omd_basics#[Monitoring-Instanzen] anlegen und verwalten können.
Zur Kontrolle können Sie die installierte Version ausgeben lassen:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version 2.1.0p1.cre
----
