// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Installation unter Red Hat und Derivaten
:revdate: draft
:title: Installation unter Red Hat und Derivaten
:description: Hier erfahren Sie, wie Sie {CMK} unter der Linux-Distribution Red Hat Enterprise Linux (RHEL) und ihren Derivaten installieren.

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:appliance_install_virt1#[Virtuelle Appliance installieren]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
{related-end}


== Einrichten der Paketquellen

{CMK} benötigt etliche Software-Pakete Ihrer Linux-Distribution.
Software aus Drittquellen wird nicht benötigt.
Damit alle benötigten Pakete fehlerfrei nachinstalliert werden können, benötigen Sie eine korrekte Konfiguration der Software-Quellen.

Bei Red Hat, CentOS, AlmaLinux und Rocky Linux (und allen anderen Derivaten) muss das _EPEL (Extra Packages for Enterprise Linux)_-Repository als Paketquelle eingerichtet werden.
Dies geschieht mit Hilfe eines RPM-Pakets, welches mit dem Befehl `yum` installiert wird:

[cols="10,~",options="header"]
|===
|Version |Paketlink 
|7 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`
|8 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`
|9 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm`
|===

Hier ein Beispiel für die Installation unter AlmaLinux 8:

[{shell-raw}]
----
{c-root} yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----

Damit Sie EPEL auf Red Hat und Derivaten nutzen können, benötigen Sie noch die Paketquelle für optionale RPMs, sofern diese nicht bereits bei der Installation des Betriebssystems eingerichtet worden ist.
Ohne diese Quelle werden Ihnen die Pakete `freeradius-utils`, `graphviz-gd` und `php-mbstring` fehlen.
Ab Version 8.x genügt hier die Aktivierung der sogenannten PowerTools mithilfe des Dandified YUM in den freien Derivaten bzw. dem `subscription-manager` in RHEL.
Dies geht z.B. mit folgenden Befehlen:

// Red Hat/CentOS 6.X:
// 
// [{shell}]
// ----
// {c-root} yum-config-manager --enable rhel-6-server-optional-rpms
// {c-root} subscription-manager repos --enable rhel-6-server-optional-rpms
// ----

Red Hat/CentOS 7.x:

[{shell}]
----
{c-root} yum-config-manager --enable rhel-7-server-optional-rpms
{c-root} yum-config-manager --enable rhel-7-server-extras-rpms
{c-root} subscription-manager repos --enable rhel-7-server-optional-rpms
{c-root} subscription-manager repos --enable rhel-7-server-extras-rpms
----

// MFS: 8.3 ist als STS Version seit Mitte 2021 EOL,das erlaubt vereinfachungen https://access.redhat.com/support/policy/updates/errata
CentOS 8.2 und früher:

[{shell}]
----
{c-root} dnf config-manager --set-enabled PowerTools
----

CentOS 8.4 und später, AlmaLinux und Rocky Linux:

[{shell}]
----
{c-root} dnf config-manager --set-enabled powertools
----

Red Hat 8.x:

[{shell}]
----
{c-root} subscription-manager repos --enable "codeready-builder-for-rhel-8-x86_64-rpms"
----

// SK: Auflistung der Paketquellen?!? Warum? Ist das für die Installation wichtig oder ist es interessant?
// SK: Plus: Das funktioniert unter 8.x ohne die vorherige Installation von subscription-manager ohnehin nicht.
//Eine Auflistung aller verfügbaren Paketquellen erhalten Sie mit:
//
//C+:
//RP:subscription-manager repos --list
//C-:


== Einrichten von SELinux und Firewall

Da Red Hat und damit auch die Derivate standardmäßig SELinux und eine lokale Firewall mitliefern, müssen hier gegebenenfalls noch Anpassungen vorgenommen werden.
Erlauben Sie zunächst, dass der Webserver auf die Netzwerkschnittstellen zugreifen darf:

[{shell}]
----
{c-root} setsebool -P httpd_can_network_connect 1
----

Als Zweites geben Sie den Webserver frei und aktivieren die Änderung:

[{shell}]
----
{c-root} firewall-cmd --zone=public --add-service=http --permanent
success
{c-root} firewall-cmd --reload
success
----


== Herunterladen des passenden Pakets

Wenn Sie eine Subskription besitzen, dann finden Sie im link:https://portal.checkmk.com/de/[Kundenportal^] zu jeder verfügbaren xref:cmk_versions#[{CMK}-Version] ein passendes RPM- bzw. DEB-Paket für Ihre
Distribution.
Zum Testen oder für kleinere Installationen von {CMK} können Sie auf unsere link:https://checkmk.com/de/download[kostenlosen Editionen^] zurückgreifen.
Diese benötigen dann entsprechend auch keine Subskription, können jedoch jederzeit problemlos durch ein xref:update#updatedemo[Upgrade] auf eine der {CEE} überführt werden.

Beachten Sie bei der Auswahl des Pakets:

* Wählen Sie die für Sie passende Edition aus.
Falls Sie unsicher sind, verschaffen Sie sich zuerst einen Überblick über die Unterschiede zwischen den link:https://checkmk.com/de/produkt/editionen[Editionen.^]
* Wählen Sie die {CMK}-Version, die Distribution und zuletzt die Version der gewählten Distribution.
* Wir empfehlen den Einsatz der _letzten stabilen {CMK}-Version._
Falls Sie eine ältere Version benötigen, finden Sie diese im link:https://checkmk.com/de/download/archive/[Download-Archiv.^]
* Name und Version Ihrer Distribution müssen exakt übereinstimmen.
// TK: Versteh ich nicht: Was muss hier exakt übereinstimmen?

Nachdem Sie das Paket heruntergeladen haben, bringen Sie es auf das Linux-System, auf dem {CMK} installiert werden soll.
Das kann zum Beispiel über das Kommandozeilentool `scp` geschehen, welches jedes moderne System mitbringt – und auch bei Windows 10 
in der PowerShell verfügbar ist.
Zusätzliche Programme wie _WinSCP_ sind meist nicht erforderlich.
Das Beispiel zeigt die Übertragung eines {CRE} Paketes auf AlmaLinux 8.x:

[{shell}]
----
{c-root} scp check-mk-raw-2.2.0p1-el8-38.x86_64.rpm root@mymonitoring.mydomain.org:
----


[#signed]
== Installation des signierten Pakets

Alle Pakete werden mittels link:https://gnupg.org[GnuPG^] signiert.
Durch diese Signatur können Sie zum einen prüfen, ob das Paket auch wirklich von uns stammt, und zum anderen, ob es insgesamt vollständig ist.

Damit diese signierten Pakete wie gewohnt installiert werden können, müssen Sie einmalig unseren öffentlichen Schlüssel importieren, damit der Signatur vertraut wird.
Laden Sie dazu zuerst den Schlüssel direkt von unserer Website:

[{shell-raw}]
----
{c-root} wget https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

////
Alternativ können Sie den Schlüssel aber auch über link:http://keys.gnupg.net[gnupg.net^] beziehen:

[{shell}]
----
{c-root} gpg --keyserver keys.gnupg.net --recv-keys 434DAC48C4503261
{c-root} gpg --armor --export 434DAC48C4503261 > Check_MK-pubkey.gpg
----
////

Danach importieren Sie den Schlüssel in die Liste der vertrauenswürdigen Signaturen.
Unter Red Hat und CentOS ist auch dafür das Tool `rpm` zuständig:

[{shell}]
----
{c-root} rpm --import Check_MK-pubkey.gpg
----

Sobald Sie den Schlüssel importiert haben, können Sie das Paket noch einmal verifizieren und anschließend wie gewohnt mit `yum install` installieren:

[{shell}]
----
{c-root} rpm -K check-mk-raw-2.2.0p1-el8-38.x86_64.rpm
check-mk-raw-2.2.0p1-el8-38.x86_64.rpm: digests signatures OK
{c-root} yum install check-mk-raw-2.2.0p1-el8-38.x86_64.rpm
----


== Abschlusstest

Nach der erfolgreichen Installation von {CMK} und allen Abhängigkeiten steht Ihnen der Befehl `omd` zur Verfügung, mit dem Sie xref:omd_basics#[Monitoring-Instanzen] anlegen und verwalten können.
Zur Kontrolle können Sie die installierte Version ausgeben lassen:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version 2.2.0p1.cre
----
