// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Installation unter Debian und Ubuntu
:revdate: 2021-02-25
:title: Installation unter Debian und Ubuntu
:description: Hier erfahren Sie, wie Sie {CMK} unter der Linux-Distribution von Debian und von Ubuntu installieren.

{related-start}
link:intro_welcome.html[Leitfaden für Einsteiger]
link:checkmk_getting_started.html[Schnelleinstieg ins Monitoring]
link:introduction_virt1.html[Installation der virtuellen Appliance]
link:install_packages.html[Grundsätzliches zur Installation von {CMK}]
{related-end}

//SK: H1:Zusätzliche Sicherheitsmechanismen gemäß KNW-86 beschreiben
//SK: Hab ich leider zu spät gesehen diesen Hinweis. Muss ich nachliefern.


== Herunterladen des passenden Pakets

Wenn Sie eine Subskription besitzen, dann finden Sie in Ihrem
link:https://checkmk.de/download.php[Subskriptionsbereich] zu jeder verfügbaren
xref:cmk_versions#[{CMK}-Version] ein passendes DEB-Paket für Ihre Distribution. Zum
kostenlosen Testen oder für kleinere Installationen von {CMK} können Sie auf
unsere link:https://checkmk.de/download.php[kostenlosen Editionen] zurückgreifen. Diese
benötigen dann entsprechend auch keine Subskription, können jedoch jederzeit
problemlos durch ein xref:update#updatedemo[Upgrade] auf eine der {CEE} überführt
werden.

Bitte beachten Sie bei der Auswahl des Pakets:

* Wählen Sie die Version, die Distribution und zuletzt die Version der gewählten Distribution.
* Wir empfehlen den Einsatz der _letzten stabilen Version._ Falls Sie eine ältere Version benötigen, finden Sie diese im link:https://checkmk.de/download-archive.php[Download-Archiv.]
* Name und Version Ihrer Distribution müssen exakt übereinstimmen.
* Wählen Sie die für Sie passende Edition aus. Falls Sie unsicher sind, verschaffen Sie sich zuerst einen Überblick über die Unterschiede zwischen den link:https://checkmk.de/editions.html[Editionen.]

Nach dem Sie das Paket heruntergeladen haben, bringen Sie es auf das
Linux-System, auf dem {CMK} installiert werden soll. Das kann zum Beispiel über
das Programm _WinSCP_ geschehen, oder -- wenn Sie direkt ssh-Verbindungen
öffnen können -- über das Kommandozeilentool `scp`.

Für eine Übertragung mithilfe von `scp` muss auf dem zukünftigen
{CMK}-Server das Paket openssh-server installiert sein. Sollte dies noch nicht
der Fall, so führen Sie bitte den folgenden Befehl aus, um openssh-server
einzurichten:

[{shell}]
----
{c-root} apt install openssh-server
----

Anschließend können Sie beispielsweise die {CRE} für _Ubuntu 20.04 (focal fossa)_ wie folgt übertragen:

[{shell}]
----
{c-root} scp check-mk-raw-2.0.0p3_0.focal_amd64.deb root@mymonitoring.mydomain.org:
----

[#signed]
== Installation des signierten Pakets

Alle Pakete werden mittels link:https://gnupg.org[GnuPG] signiert. Durch
diese Signatur können Sie zum einen prüfen, ob das Paket auch wirklich von uns
stammt und zum anderen, ob das Paket insgesamt vollständig ist.

Je nachdem mit welchen optionalen Paketen Ihre Distribution installiert wurde,
muss für eine erfolgreiche Verifikation noch das Paket dpkg-sig inklusive seiner
Abhängigkeiten installiert werden. Führen Sie dazu den folgenden Befehl aus:

[{shell}]
----
{c-root} apt install dpkg-sig
----

Damit diese signierten Pakete wie gewohnt installiert werden können,
müssen Sie einmalig unseren öffentlichen Schlüssel importieren, damit
der Signatur vertraut wird. Laden Sie dazu zuerst den Schlüssel entweder
direkt von unserer Internetseite:

[{shell}]
----
{c-root} wget \https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

*Alternativ* können Sie den Key aber auch über link:https://keys.openpgp.org[keys.openpgp.org] beziehen:

[{shell}]
----
{c-root} gpg --keyserver keys.openpgp.org --recv-keys 434DAC48C4503261
{c-root} gpg --armor --export 434DAC48C4503261 > Check_MK-pubkey.gpg
----

Danach importieren Sie den Schlüssel in die Liste der vertrauenswürdigen Signaturen.
Unter Debian und Ubuntu benötigen Sie dafür den folgenden Befehl:

[{shell}]
----
{c-root} gpg --import Check_MK-pubkey.gpg
----

Sobald Sie den Schlüssel importiert haben, verifizieren Sie das {CMK}-Paket mit
dem folgenden Befehl:

[{shell}]
----
{c-root} dpkg-sig --verify check-mk-raw-2.0.0p3_0.focal_amd64.deb
----

Anschließend können Sie das {CMK}-Paket mit dem folgendem Befehl installieren. Achten Sie dabei darauf den vollständigen Pfad zu der .deb-Datei an `apt install` zu übergeben:

[{shell}]
----
{c-root} apt install /tmp/check-mk-raw-2.0.0p3_0.focal_amd64.deb
----


== Abschlusstest

Nach der erfolgreichen Installation von {CMK} und allen Abhängigkeiten
steht Ihnen der Befehl `omd` zur Verfügung, mit dem Sie
xref:omd_basics#[Monitoring-Instanzen] anlegen und verwalten können. Zur Kontrolle
können Sie die installierte Version ausgeben lassen:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version 2.0.0p3.cre
----

