// -*- coding: utf-8 -*-
// IGNORE % p2 pre Dropdown
include::global_attr.adoc[]
= Installation aus dem AWS oder Azure Marketplace
:revdate: draft
:title: Installation aus dem AWS oder Azure Marketplace
:description: Marketplace images, die {CMK} enthalten, sind ab Version 2.2.0 erhältlich.

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
xref:update#[Updates und Upgrades]
{related-end}


[#welcome]
== {CMK} unter AWS oder Azure nutzen

Offizielle, vorkonfigurierte Images sind im AWS oder Azure Marketplace für {CMK} Cloud Edition ab 2.2.0 erhältlich.
Uns ist bekannt, dass Images von Dritten existieren und versuchen diese entfernen zu lassen.
Bitte nutzen Sie das Dropdown-Menü zur Branch-Auswahl, wenn Sie zum Artikel wechseln wollen, der die Einrichtung beschreibt.

Falls Sie ältere Versionen von {CMK} in derartiger Cloud-Infrastruktur betreiben mögen, empfehlen wir die Verwendung eines der offiziellen Ubuntu Images (link:https://aws.amazon.com/marketplace/pp/prodview-o5bowpuwmx3ng?sr=0-10&ref_=beagle&applicationId=AWSMPContessa[Amazon^] and link:https://learn.microsoft.com/en-us/azure/virtual-machines/linux/quick-create-portal?tabs=ubuntu[Azure^]) und darauf eine xref:install_packages_debian#[reguläre Installation aus DEB-Paketen] vorzunehmen.
