// -*- coding: utf-8 -*-
// IGNORE 
include::global_attr.adoc[]
= Installation als Azure-Image
:revdate: draft
:title: Installation als Azure-Image
:description: {CMK} bietet (fast) schlüsselfertige Images im Azure Marketplace. In diesem Artikel erfahren Sie, wie Sie die Einrichtung abschließen.

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:install_packages#[{CMK}-Server installieren]
xref:update#[{CMK} aktualisieren]
{related-end}


== Grundsätzliches

Falls Sie Nutzer des Azure Marketplaces sind, hatten Sie schon immer die Möglichkeit, ein im Marktplatz vorhandenes Ubuntu-Image mit {CMK} zu versehen und so "Monitoring in der Cloud" einzurichten.
{CMK} {v22} geht den nächsten Schritt und bietet vorinstallierte Images, bei denen alle Abhängigkeiten bereits erfüllt sind.
Hierbei kommt ausschließlich die {CE} zum Einsatz, welche Sie nach dem 30 Tage laufenden Testzeitraum mit bis zu 750 überwachten Diensten ohne Subskription benutzen können, oder darüber mit einem Lizenzschlüssel versehen können.

Generell ist die Einrichtung ein wenig aufwendiger als beispielsweise beim xref:introduction_docker#[Docker-Image], schließlich muss das bereitgestellte Image verschiedene Einsatzszenarien abdecken:

* Single Site Setup auf einem Host in verschiedenster Skalierung
* Central Site im Distributed Monitoring
* Remote Site im Distributed Monitoring
* Mischbetrieb von produktiver Site und Site(s) zum Testen auf einem Host

Aus diesem Grund enthält das Azure Image weder eine vorbereitete Site, noch Mail- oder Firewall-Konfiguration.
In diesem Artikel führen wir Sie durch das komplette Setup.
Wo Hintergrundinformationen sinnvoll sind, verlinken wir in detaillierte Artikel des Handbuchs.

== Image im Marketplace buchen

_TBD_

Die vorgeschlagenen Parameter der virtuellen Maschine sind in typischen Einsatzszenarien für eine niedrige vierstellige Zahl von Hosts ausreichend.
Natürlich kann diese Zahl höher ausfallen, wenn auf sehr effiziente Checks und Agentenplugins geachtet wird oder niedriger, wenn aufwendige Spezialagenten genutzt werden.
Steht von vornherein fest, dass eine deutlich höhere Zahl an Services überwacht werden soll, können Sie die virtuelle Hardware entsprechend großzügiger dimensionieren.

// MFS: Gemeinsamer Teil
include::include_common_aws_azure.asciidoc[]

== Nachbereitung Backup
