// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Willkommen bei {CMK}
:revdate: 2022-04-06
:title: Willkommen bei {CMK}
:description: Hier wird der Leitfaden für Einsteiger vorgestellt, der kompakt durch die ersten Schritte führt, um das IT-Monitoring mit {CMK} optimal einzurichten.
:no-toc:

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
{related-end}


*Liebe Leserinnen und Leser,*

wir freuen uns, dass Sie den Weg zu {CMK} gefunden haben -- und dabei auch im {CMK}-Handbuch vorbeischauen.

Der reibungslose Betrieb von IT-Systemen war schon immer eine Herausforderung.
Sowohl die Komplexität von Hardware und Software als auch die Ansprüche der Anwender nehmen immer weiter zu -- egal, ob sie mit echter Hardware oder mit Cloud-Lösungen arbeiten.
So kommt einem detaillierten und umfassenden IT-Monitoring heute eine zentrale Rolle zu.

So komplex wie die IT-Welt sind natürlich auch die Anforderungen, die Anwender an ihr Monitoring stellen.
{CMK} wurde von Anfang an für große und heterogene IT-Landschaften entwickelt.
Deswegen bietet es eine Fülle von Funktionen und Möglichkeiten, um all den Problemstellungen gerecht zu werden, die daraus in der Praxis folgen.
Daher ist der Umfang von {CMK} für einen Einsteiger erst mal überwältigend.

Damit Sie trotzdem schnell und bequem zu Ihrem ersten {CMK}-Monitoring kommen, haben wir das {CMK}-Handbuch für Sie in zwei Teile untergliedert:

. einen Leitfaden für Einsteiger, dessen Einleitung Sie gerade lesen, und der Sie in den folgenden Kapiteln beim Kennenlernen von {CMK} begleitet;

. eine Einführung in die wichtigsten Aufgaben beim Einsatz von {CMK} und einen umfassenden Referenzteil für Experten.

Der Leitfaden für Einsteiger führt Sie kompakt Schritt für Schritt in {CMK} ein und ist so aufgebaut, dass Sie ihn zügig von Anfang bis Ende lesen und dabei gleich mitmachen können.
Deswegen ist er auch kurz und knapp und hält sich nicht mit unnötigen Details auf.
Am Ende des Leitfadens haben Sie ein praxisgerechtes {CMK}-System.

Im xref:intro_bestpractise#[letzten Kapitel] zeigen wir Ihnen dann noch ein paar sehr nützliche Tipps und Tricks unserer erfahrenen Consultants, die sich in verschiedenen {CMK}-Installationen bewährt haben.

Natürlich lässt der Leitfaden für Einsteiger noch viele Fragen offen.
Diese werden im Rest des Handbuchs beantwortet.
Dort finden Sie zu Themen, die wir im Leitfaden nur anreißen können, alle Hintergründe und Details um tiefer einzusteigen -- auf Ihrem Weg vom Einsteiger zum {CMK}-Experten.

xref:intro_setup#[Weiter geht es mit dem Aufsetzen von {CMK}]
