= Blessed Checks
:description: When writing your own checks, it is a good practice to have a look at existing code as an example.
:revdate: outdated
== Blessed Checks

When writing your own checks, it is a good practice to have a look at existing
code as an example. In this case you might want to look at one of the following
checks. They have passed a special review process and are known to be of
excellent quality.

[cols=, ]
|===
<th>Check</th><th>Type</th><th>Note</th>
<td class=tt>viprinet_serial</td><td>SNMP</td>
    <td>Simple SNMP check fetching one value, always OK</tr>

<td class=tt>cisco_fantray</td><td>SNMP</td>
    <td>Simple SNMP check with items, no parameters, no performance data</tr>

<td class=tt>cisco_fru_power</td><td>SNMP</td>
    <td>Check computing its outcome from two aspects, both of which can trigger warn or crit</tr>

<td class=tt>solaris_multipath</td><td>Agent</td>
    <td>Simple check with items, without parameters</tr>

<td class=tt>uptime</td><td>Agent</td>
    <td>Simple check using an empty dict parameter and an include file</tr>

<td class=tt>timemachine</td><td>Agent</td>
    <td>Simple check with time arithmetics and dictionary based parameters</tr>

<td class=tt><a href="https://github.com/tribe29/checkmk/blob/b5faa8436afb727384f2a76b013e028d56b98fa4/checks/hitachi_hnas_fan">hitachi_hnas_fan</a></td><td>SNMP</td>
    <td>Check with items that combines two aspects into one result status</tr>
|===
