= Multisite Modularized User Management
:revdate: outdated
VS:1.2.1i4
[.seealso][#multisite]KW:multisite,web,user,management,userdb

== Introduction

Prior to this release it was only possible to let the users authenticate
with Apaches htpasswd file based authentication. There was no official
way to implement any type of imports of users from external sources into
Multisite / WATO.

With this release Multisite and WATO have been improved by the userdb
API which provides the option to modularize the user authentication and
management in a flexible way. Such modules are called _connectors_.

There are two connectors available by default, the htpasswd connector and
the [multisite_ldap_integration|LDAP connector], which can be used to 
integrate Multisite with a LDAP server.

== Connector Plugins

The API is realized like other existing plugin structures of Multisite.
There is one directory `plugins/userdb` where plugin files can
placed into. All `*.py` files in this directory are loaded into
the `userdb` module.

Each plugin has to register with the `multisite_user_connectors`
list to make it loadable. Each connector must add it's dictionary to this
list, as example we take a look at the LDAP connector registration:

.plugins/userdb/ldap.py

----multisite_user_connectors.append({
    'id':          'ldap',
    'title':       _('LDAP (Active Directory, OpenLDAP)'),
    'short_title': _('LDAP'),

    'login':             ldap_login,
    'sync':              ldap_sync,
    'page':              ldap_page,
    'locked':            user_locked, # no ldap check, just check the WATO
                                      # attribute. This handles setups where
                                      # the locked attribute is not 
                                      # synchronized and the user is enabled
                                      # in LDAP and disabled in Checkmk. When
                                      # the user is locked in LDAP a login is
                                      # not possible.
    'locked_attributes':      ldap_locked_attributes,
    'multisite_attributes':   ldap_multisite_attributes,
    'non_contact_attributes': ldap_multisite_attributes,
})
----

[cols=, ]
|===

<td class="tt" <b class=hilite>style="width:20%"*>Updated
|Eine Datei hat sich in der neuen Version geändert. Da Sie keine Änderungen
an der Datei gemacht haben, setzt Check_MK einfach die neue Defaultversion der Datei ein.
F-:

Das `nwbook` kann diese Format erkennen und korrekt parsen - allerdings nicht
genau diesen einzigen `style`. Andere Angaben sind hier nicht erlaubt.


H3:Anführungszeichen

Alle Anführungszeichen *müssen* wie oben beschrieben mit den speziellen
Unicodezeichen gesetzt werden. Beispiel:

F+:
„Hallo Welt!“
F-:

`nwbook` erzeugt für Deutsch und Englisch daraus jeweils unterschiedliche
passende Anführungszeichen.


H2:Sonderfälle für die Trainings-Artikel#presentation

Die Trainingsartikel haben gleich mehrere Funktionen, welche alle
zusammenhängend in der gleichen Datei gepflegt werden. Hier fließen sowohl
die Überschriften ein, welche in der Online- und Buch-Version zu sehen sind,
als auch die Folien für die Schulungspräsentation und Notizen für die
Schulungsleiter ein. Die Elemente der einzelnen Bereiche sind jweils nur in
den entsprechenden Dateien sichtbar! Daraus ergeben sich einige Sonderfälle:

H3:Aufbau des Artikels

Jeder Tag stellt eine *H1:*-Überschrift dar und ist damit die oberste Ebene. Die
jeweiligen Oberthemen für eine Schulungseinheit ist eine *H2:*-Überschrift.

Jedes Oberthema beginnt mit den Unterthemen, welche mit dem Indexmarker
*IN:* versehen werden. Danach beginnt die Beschreibung der Unterthemen.

Jede Beschreibung fängt mit dem Dozentenmarker *DO:*an und bezieht sich
immer nur auf eine konkrete Folie. In der ersten Zeile steht der Titel des
Unterthemas. Danach können Notizen zu diesem Thema hinterlegt werden. Die
Notizen werden mit einer Zeile beendet, in der sich lediglich Dozentenmarker
ohne weiteren Text befindet.

Nach den Notizen werden die Folien definiert. Das können entweder Stichpunkte,
welche die Erläuterungen des Dozenten ergänzen und den Teilnehmern eine
Orientierung zu den Themeninhalten geben, oder eine Grafik sein.

Der erste Stichpunktmarker *SI:* enthält die Überschrift für
die jeweilige Folie und sollte ein Unterthema spiegeln. Sollen später
noch mehr Folien zu diesem Unterthema hinzugefügt werden, sollten alle
Folien-Überschriften gleich sein. Alle weiteren Stichpunktmarker sind dann
die Stichpunkte der Folie.

Mit dem Grafikmarker *SB:* können Bilder in die Folien eingebunden
werden. Diese sollten ebenfalls in dem Handbuch vorkommen oder  --
in Ausnahmefällen  --  nur für die Folien erstellte Bilder sein.

Nachdem eine solche Folie abgeschlossen ist (Und sowohl Notizen, als
auch Stichpunkte/ein Bild enthält), kann die nächste Folie angefangen
werden. Diese beginnt wieder mit der Notizen-Überschrift für den
Schulungsleiter.


Nachfolgend ein Beispiel. Der doppelte Backslash verhindert die Interpretation
in diesem Artikel und wir im Original natürlich weggelassen:

F+:training_cmk_beispiel
\\TI:Beispieltraining für die Syntax
\\
\\Hier ist ein Text, wie er in dem Artikel online und im Buch vorkommen wird.
\\
\\H1:Tag 1
\\
\\H2:Wie funktioniert der Aufbau dieses Artikels
\\
\\IN:internal_syntax#introduction              Einführung in den Aufbau unseres Handbuchs
\\IN:internal_syntax#special_characters        Erlaubte Sonderzeichen in den Texten
\\IN:internal_syntax#presentation              Wie wird ein Schulungsartikel aufgebaut?
\\IN:regexes                          Wie man sich das Leben leichter macht
\\
\\DO:Einführung in den Aufbau unseres Handbuchs - Folie 1
\\DO:Hier steht Text dazu, was der Schulungsleiter so alles
\\DO:erzählen kann. Die nächste Zeile ist leer, damit in der
\\DO:Notes-Datei eindeutig ist, wo die Notizen zu einer Folie
\\DO:aufhören.
\\DO:
\\SI:Einführung in den Aufbau unseres Handbuchs
\\SI:erster Stichpunkt
\\SI:Mehr als drei Stichpunkte nur in Ausnahmefällen
\\SI:Nach dem letzten Stichpunkt eine Leerzeile
\\
\\DO:Einführung in den Aufbau unseres Handbuchs - Folie 2
\\DO:Noch mehr Text.
\\DO:
\\SI:Einführung in den Aufbau unseres Handbuchs
\\SI:Überschrift immer gleich halten
\\SI:drei Stichpunkte sind übersichtlich und ergänzen
\\SI:mehr Stichpunkte lenken eher vom Schulungsleiter ab
\\
\\DO:Erlaubte Sonderzeichen in den Texten - Folie 1
\\DO:
\\SB:eine_schoene_grafik.png
F-:

H1:Workflow, Arbeit mit Jira

H2:Arbeit mit Tickets

H3:Erzeugen eines Tickets

Wir arbeiten nur mit drei verschiedenen *Issue Types*:

NL:Epic: Große Aufgabe, die fortwährend andauert (z.B. Legacy-Dokumentation loswerden). So ein Ticket beinhaltet normalerweise Subtickets.
NL:Story: Normale Aufgabe, z.B. einen Artikel schreiben. Oder etwas anderes, was eher Tage als Stunden Zeit braucht.
NL:Task: Kleine Aufgabe oder Bug, etwas, das man in kurzer Zeit erledigen kann.

Wir verwenden folgende *Components*:

LI:Artikel
LI:Buchlayout
LI:HTML-Layout
LI:Schulungen
LI:Appliance

H2:Übersetzung

Wenn ein Artikel bereit ist für die Übersetzung ins Englische, übergibt man das Ticket an Marcel und
setzt den Status auf {{Ready for Translation}}.

H2:Reviews

Per Default arbeiten wir bei Reviews ohne Gerrit sondern mit Kommentaren --
entweder im Artikelquelltext oder mündlich (Telefon, etc.). Zwei können
untereinander vereinbaren, dass sie miteinander Gerrit einsetzen wollen.

Wenn wir im Quelltext kommentieren, machen wir das mit COMMENT[...].

Wann machen wir überhaupt Reviews?

LI:Neue Artikel
LI:Substanzielle inhaltliche Änderungen in bestehenden Artikeln
LI:Zeugs was Anfänger gemacht haben
LI:Wenn man sich selbst unsicher ist
|===
    <tr><th>Attribute</th><th>Description</th></tr>
    <tr>
        <td>`id`
        <td>This is the identifier of the connector. It has to be unique
        compared to all other connectors.
        
    </tr>
    <tr>
        <td>`title`
        <td>The human readable title of the connector. It is shown to the
        user in WATO to identify the connector.
        
    </tr>
    <tr>
        <td>`short_title`
        <td>The title of the connector in short. It is shown e.g. in the
        users and contancts table to identify the connector.
        
    </tr>
    <tr>
        <td>`login`
        <td><p>Takes the reference to a hook function as value. This is called
        when a user likes to authenticate with Multisite (filled and submitted
        the login form). The functions task is to verify the user credentials.</p>
        <p>The function must take two parameters, the `username` and the
        `password`.</p>
        <p>The function must return one of the three values:
        <ul>
        <li>`True`: The user has entered valid credentials.</li>
        <li>`False`: The user has entered invalid credentials.</li>
        <li>`None`: Unknown user for this connector. Try next connector.</li>
        </ul>
        </p>
        
    </tr>
    <tr>
        <td>`sync`
        <td><p>Takes the reference to a hook function as value. This is called
        in several situations:
        <ul>
        <li>When opening the &quot;Users & Contacts&quot; page of WATO</li>
        <li>Before activating the pending changes in WATO</li>
        <li>Distributed WATO: After receiving a new snapshot on slave sites</li>
        <li>Only for a single user, when a user is created during first login</li>
        <li>_LDAP_: On page rendering, when the LDAP cache needs to be renewed (`ldap_cache_livetime`)</li>
        </ul></p>
        <p>The return value of this function is not processed. If an exception occurs,
        the connectors sync function is terminated and the sync function of the next
        connector is processed.</p>
        <p>The function must deal with the two parameters `add_to_changelog` 
        to create a changelog entry or none and `only_username` to only synchronize
        the given user or all users.</p>
        
    </tr>
    <tr>
        <td>`page`
        <td><p>Takes the reference to a hook function as value. This is called on each
        http request to the multisite code. This are not only the pages requested by
        the user, but also the ajax requests which are used to update the contents
        shown to the user. So be careful when implementing things in this hook, it
        will be called often.</p>
        <p>The hook function is called without arguments. The returned value is ignored.
        If an exception occurs, the connectors sync function is terminated and the sync
        function of the next connector is processed.</p>
        
    </tr>
    <tr>
        <td>`locked`
        <td><p>Takes the reference to a hook function as value. This is called after a
        successfull login (and optional user account creation). It checks whether or not 
        the user is locked and therefor not allowed to login. In htpasswd connector the
        function checks whether or not there is a "!" in front of the password. But when
        using other conectors it might be neccessary to validate the users `locked`
        attribute.</p>
        <p>The hook function is called with the `username` to be checked as argument.
        It must return `True` if the user is locked and `False` if the user
        is allowed to login.</p>
        
    </tr>
    <tr>
        <td>`locked_attributes`
        <td><p>Takes the reference to a hook function as value. It is called by WATO when
        a user assigned to this connector is being edited. It is called to gather the list of WATO
        attributes which should be read only in the editing dialog.</p>
        <p>The function is called without arguments and must return a list of WATO attribute
        names to be locked.</p>
        
    </tr>
    <tr>
        <td>`multisite_attributes`
        <td><p>Takes the reference to a hook function as value. It is called by WATO when
        a user assigned to this connector is saved. It is called to gather the list of WATO
        attributes which should be saved in the Multisite configuration (`users.mk`).</p>
        <p>The function is called without arguments and must return a list of WATO attribute names.</p>
    </tr>
    <tr>
        <td>`non_contact_attributes`
        <td><p>Takes the reference to a hook function as value. It is called by WATO when
        a user assigned to this connector is saved. It is called to gather the list of WATO
        attributes which should _not_ be saved in the Check_MKs contact config (`contacts.mk`).</p>
        <p>The function is called without arguments and must return a list of WATO attribute names.</p>
    </tr>
|===

== Authentication with Multiple Connectors

The authentication of users is done after the user entered the credentials into the login dialog
and submitted the form. Multisite is calling the `login` hook functions of all connectors
in the order the connectors are registered. Each connector has the option to validate the credentials
of the user or simply skip validation and let the next connectors validate the user.

When a connector rates the credentials of the user to be correct, all other connectors are skipped
and the user is logged in. When a connector comes to the result that the credentials belong to an
existing user but are wrong, the user is sent back to the login form for a retry.

== The Default User Profile

All users created by the synchronization function should be initialized with the function
`new_user_template(&lt;connector_id&gt;)`. It uses the default user profile to e.g. assign
the user a default role.

The default user profile can be customized using the "Global Settings" dialog of WATO. You can find
this option in the "User Management" section. Currently you can configure the roles and contactgroups
which should be assigned to new users.
