= Checkmk Hardware/Software-Inventory
MD:The Checkmk hardware/software inventory system collects information about hardware and installed software of your hosts.
:revdate: outdated
VS:1.2.5i1

== Introduction

The new Checkmk HW/SW-Inventory System, which is available since version
<b class=new>1.2.5i1* of Checkmk, collects information about hardware
and installed software of your hosts. _What does this have to do with
monitoring?_ - you might ask. Well: from a technical point of view a lot,
as we will show!

If you monitor your Linux and Windows (and possibly other) hosts with Checkmk
then you've deployed the Checkmk Agent on these. The agent provides easy
access to _status_ data of the hosts.  It does this by collecting
all of this into one large dump that is fetched every monitoring cycle by
the Checkmk server.  It turns out that the special nature of this agent
perfectly fits the requirements of an inventory system: just replace this
_status_ with _inventory_. So using the _existing_ Checkmk
Agent for hardware/software inventory is a quite obvious idea.

The Checkmk Inventory can answer questions like:

<ul>
<li>Which of my servers have installed the software Foo in versions between 1.2.3 and 1.2.5?</li>
<li>Which exact type of RAM module is installed in server ABC?</li>
<li>Do we have any ORACLE server running on SLES?</li>
</ul>

If you are already using Checkmk then this approach has some great advantages
as opposed to a stand-alone inventory system:
<ul>
<li>You can use your existing agents, no further deployment, maintainance and ressources needed</li>
<li>You can use your existing configuration of hosts with names, IP addresses, permissions etc.</li>
<li>You can use your existing user interface with it's user management etc.</li>
<li>You can _Combine information from monitoring and inventory_
</ul>

All you need to do is to deploy the new agent plugin `mk_inventory` on your
existing Checkmk agents and enable the inventory via a new rule set in WATO.

== How It Works

<ol>
<li>Install the `mk_inventory` agent plugin on your target systems. This
will add a couple of new sections to your agent's output.</li>
<li>You enable the Inventory via WATO. This will create a new active check `Checkmk HW/SW Inventory` for each selected host.</li>
<li>This active check will extract the new and also several classical agent sections about hardware and software and
 constructs a structured tree of hardware and software for each host.</li>
<li>The Multisite GUI has a couple of new views for browsing through the inventory data, searching for
certain software packages, etc. You also can add inventory data to your custom views.</li>
<li>Via custom _export hooks_ you can have the data exported to third party systems like
licence managements or CMDBs</li>
<li>The data is also exposed via HTTP in JSON and Python format.</li>
</ol>

== Windows 2003

A note for users of Windows 2003: In Windows 2003 Server,
`Win32_Product` is not enabled by default, and must be enabled
as follows:

<ol>
<li>In _Add or Remove Programs_, click Add/Remove Windows Components.</li>
<li>In the _Windows Components Wizard_, select _Management and Monitoring Tools_ and then click _Details_.</li>
<li>In the _Management and Monitoring Tools_ dialog box, select _WMI Windows Installer Provider_ and then click OK.</li>
<li>Click Next</li>
</ol>

###WK:1479
