include::global_attr.adoc[]
= Weboberfläche mit HTTPS absichern
:revdate: 2019-12-04
:title: (CMK) mit HTTPS betreiben
:description: Es gibt viele Gründe Weboberflächen nur über HTTPS zu betreiben. In diesem Artikel finden Sie alles dazu, wie Sie die Verschlüsselung in checkmk aktivieren.

[TIP]
.Related Articles:
====
link:web_api.html[]
link:kerberos.html[]
link:ldap.html[]
====


== Voraussetzungen

Wenn Sie die Weboberfläche von {CMK} über HTTPS einsetzen möchten, dann
müssen Sie auf Ihrem Monitoring-Server -- unabhängig von Ihren Instanzen --
folgende Voraussetzungen schaffen:

* Sie besitzen ein gültiges Serverzertifikat.
* Das Apache-Modul mod_ssl ist installiert und aktiviert.
* Der Server ist über HTTPS erreichbar.
* Das Rewrite-Modul für den Webserver ist vorhanden und geladen.


== Konfiguration der HTTPS-Verbindung für eine Instanz

Ergänzen Sie im Abschnitt für den `VirtualHost` folgende Zeilen:

./etc/apache2/sites-enabled/000-default
....
RewriteEngine On
RewriteCond %{SERVER_PORT} !^443$
RewriteRule (.*) https://%{HTTP_HOST}/$1 [L]
RequestHeader set X-Forwarded-Proto "https"
....

Die `VirtualHost`-Konfiguration befindet sich -- je nach
eingesetzter Distribution -- in diesen Dateien:


|===

|Debian, Ubuntu

|`/etc/apache2/sites-enabled/000-default(.conf)`

|RHEL, CentOS

|`/etc/httpd/conf.d/ssl.conf`

|SLES

|`/etc/apache2/httpd.conf`

|===


Nach der Konfigurationsänderung muss der Webserver durchgestartet werden.
Je nach eingesetzter Distribution sind die Befehle dafür unterschiedlich:

{c-start}
{RP}service httpd restart
{RP}service apache2 restart
{RP}systemctl restart httpd
{RP}systemctl restart apache2
{c-end}
