include::global_attr.adoc[]
= Weboberfläche mit HTTPS absichern
:revdate: 2019-12-04
:title: {CMK} mit HTTPS betreiben
:description: Es gibt viele Gründe Weboberflächen nur über HTTPS zu betreiben. In diesem Artikel finden Sie alles dazu, wie Sie die Verschlüsselung in checkmk aktivieren.

{related-start}
link:web_api.html[Konfiguration via HTTP-API]
link:kerberos.html[Single Sign-On mit Kerberos]
link:ldap.html[Benutzerverwaltung mit LDAP/Active Directory]
{related-end}


== Voraussetzungen

Wenn Sie die Weboberfläche von {CMK} über HTTPS einsetzen möchten, dann
müssen Sie auf Ihrem Monitoring-Server -- unabhängig von Ihren Instanzen --
folgende Voraussetzungen schaffen:

* Sie besitzen ein gültiges Serverzertifikat.
* Das Apache-Modul mod_ssl ist installiert und aktiviert.
* Der Server ist über HTTPS erreichbar.
* Das Rewrite-Modul für den Webserver ist vorhanden und geladen.


== Konfiguration der HTTPS-Verbindung für eine Instanz

Ergänzen Sie im Abschnitt für den `VirtualHost` folgende Zeilen:

./etc/apache2/sites-enabled/000-default
[{file}]
----
RewriteEngine On
RewriteCond %{SERVER_PORT} !^443$
RewriteRule (.*) https://%{HTTP_HOST}/$1 [L]
RequestHeader set X-Forwarded-Proto "https"
----

Die `VirtualHost`-Konfiguration befindet sich -- je nach
eingesetzter Distribution -- in diesen Dateien:

[cols=2]
|===

|Debian, Ubuntu |/etc/apache2/sites-enabled/000-default(.conf)
|RHEL, CentOS |/etc/httpd/conf.d/ssl.conf
|SLES |/etc/apache2/httpd.conf
|===


Nach der Konfigurationsänderung muss der Webserver durchgestartet werden.
Je nach eingesetzter Distribution sind die Befehle dafür unterschiedlich:

[{shell}]
----
{c-root} service httpd restart
{c-root} service apache2 restart
{c-root} systemctl restart httpd
{c-root} systemctl restart apache2
----
