// -*- coding: utf-8 -*-
// IGNORE TBD p22 p23 pN BTRFS Unmount Netzwerkshare Herkopieren Hinkopieren Paläontologie
include::global_attr.adoc[]
= Linux-Upgrade auf dem {CMK}-Server
// TK: Bei CMK heißt der Versionswechsel Update, bei Linux Upgrade. Wenns um Linux geht, müssen wir wohl beim Begriff Upgrade bleiben. Dann aber konsequent. Im Artikel ist noch oft von Update die Rede.
// TK: Evtl. am Anfang des Artikels den Unterschied klarmachen?
:revdate: draft
:title: Linux-Upgrade auf dem {CMK}-Server
:description: Was es beim Release-Upgrade der Linux-Distribution auf dem {CMK}-Server zu beachten gibt, erfahren Sie in diesem Artikel.

{related-start}
link:update.html[Updates und Upgrades]
link:install_packages.html[Grundsätzliches zur Installation von {CMK}]
{related-end}


[#intro]
== Einleitung

Für das Release-Upgrade der Linux-Distribution auf einem {CMK}-Server gibt es verschiedene empfohlene Methoden.
Welche davon für Sie die richtige ist, hängt von den Möglichkeiten Ihrer IT-Landschaft, dem Datenbestand der {CMK}-Installation und der angestrebten Ausfallzeit ab.
Die unterschiedlichen Methoden mit Ihren jeweiligen Voraussetzungen stellen wir hier vor.
// TK: Das tust Du nicht wirklich. Zumindest 1-3 Sätze zum Unterschied sollten hier stehen, damit man nicht alles durchlesen muss, um die unterschiedlichen Prinzipien verstanden zu haben.
// TK: Insbesondere interessant, dass Methode 2 gar kein Upgrade ist.
// TK: Dabei könntest Du auch schön bytheway in situ und ex situ einführen :-)

Im wesentlichen ist das zum einen die Aktualisierung an Ort und Stelle – in der Archäologie oder Paläontologie wird die Arbeit am Fundort auf Lateinisch _in situ_ genannt.
Und zum anderen die Sicherung als Archiv, auf welche die Neuinstallation des Grundsystems und schließlich Wiederherstellung eben jenen Archivs erfolgt – nicht unähnlich zur Arbeit im Labor _ex situ_.
Englisch wird für die beiden Verfahren mitunter analog _in-place_ oder _out-of-place_ verwendet.
Auch Kombinationen der vorgestellten Methoden sind möglich, zum Beispiel, wenn Sie `/opt/omd` oder `/opt/omd/sites` auf einem eigenen Mount-Punkt abgelegt haben.
// TK: Selbstverständlich? Naja ;-)
// MFS: Satzbau geändert, Wertung entfernt.

Das Release-Upgrade spielen wir hier exemplarisch anhand des Wechsels von Ubuntu 20.04 (Focal) auf 22.04 (Jammy) durch.
// MFS: exemplarisch am Beispiel – Alder!
Bei anderen Distributionen weichen die Befehle für Upgrade und Paketmanagement hiervon mehr oder weniger stark ab.
// TK: So schlimm ists doch gar nicht. Die einzigen Befehle, die Distrospezifisch sind, sind doch apt install und apt-get remove. Vielleicht so:
// Bei anderen Distributionen weichen die Befehle für das Paketmanagement, d.h. zum Installieren und Deinstallieren, von den gezeigten mehr oder weniger stark ab.


Unser Beispielsystem nutzt nur eine einzige xref:glossar#site[Instanz.]
Falls Sie mehrere Instanzen auf dem zu aktualisierenden System betreiben (beispielsweise eine produktive und eine zum Testen), sind die instanzspezifischen Befehle für jede zu wiederholen.

[#getyourbackupdone]
== Hinweise zum Backup

Die Wichtigkeit einer Datensicherung ausreichenden Umfangs, welche auf Konsistenz geprüft ist, müssen wir IT-Profis nicht wirklich erklären.
Im Idealfall – beispielsweise beim Betrieb von {CMK} in einer virtuellen Maschine – ist eine Vollsicherung leicht durch Kopieren von Festplatten-Images möglich.

Wir empfehlen mindestens:

* Eine Sicherung mit den von {CMK} bereitgestellten Tools, entweder auf der Kommandozeile mit dem xref:omd_basics#omd_backup_restore[Befehl `omd`] oder im xref:backup#[Setup] erstellt.
Dies kann vorbereitend im laufenden Betrieb erledigt werden.

* Eine Sicherung des Inhaltes von `/opt/omd/sites` mit Werkzeugen des Betriebssystems nach Stoppen der Instanz und Unmount des instanzspezifischen `/tmp` Dateisystems.
// TK: Geändert auf Singular. Den Plural hast Du ja oben schon wegdiskutiert.
Dies kann im Zuge des Updates durchgeführt werden.

Bewahren Sie die Sicherung _separat_ von der zu aktualisierenden Maschine auf und testen Sie das Backup _vor_ den ersten Änderungen am Produktivsystem.

Falls Sie sich bei der Installation des {CMK}-Servers für ein _Copy-on-Write-Dateisystem_ wie ZFS oder BTRFS entschieden haben, sollten Sie vor dem Update _Snapshots_ erstellen.
Diese ersetzen kein separat gelagertes Backup, können aber bei Wiederherstellung des Ursprungszustandes nach einem fehlgeschlagenen Update helfen, Ausfallzeiten erheblich zu reduzieren.

[#insitu]
== Upgrade an Ort und Stelle _(in situ)_
// TK: in situ? Super! Das ist eins der am häufigsten gebrauchten Begriffe in archäologischen Texten. Und jetzt endlich auch im Handbuch.
// MFS: Ich hatte im Gymnasium einen Grundkurs Geologie/Paläontologie...
// TK: Ich würde hier von Ugrade statt Aktualisierung schreiben

// Die Methode 'Alex'
// MFS: Alex ist der Beste!
// MFS: Dreifache Verwendung desselben Begriffs für Suchmaschinen.
Diese Methode ist oft beim Einsatz von {CMK} auf dedizierter Hardware mit großen Datenbeständen sinnvoll, wo das Hinkopieren eines Archivs und das Herkopieren für dessen Wiederherstellung die Ausfallzeit deutlich erhöhen würde.
// TK: Wie, jetzt doch kein Backup mehr nötig? Im vorherigen Kapitel war das doch soooooooooooooooo wichtig.
// MFS: Haha! Geschickt umschifft!

=== Vorbereitung

Die Vorbereitung besteht vor allem aus der Entfernung _aller_ bereits jetzt nicht mehr benötigter {CMK}-Pakete.
So vermeiden Sie beim eigentlichen Upgrade Probleme im Paketmanagement.
Daneben sollten Sie bereits jetzt das richtige {CMK}-Installationspaket für die neue Distributionsversion herunterladen.

. Verschaffen Sie sich zuerst einen Überblick über installierte {CMK}-Versionen...

+
[{shell}]
----
{c-root} omd versions
2.1.0p25.cre
2.2.0p1.cee
2.2.0p2.cee (default)
----

. ...und dann, welche davon tatsächlich im Einsatz sind:

+
[{shell}]
----
{c-root} omd sites
SITE      VERSION        COMMENTS
mysite    2.2.0p2.cee    default version
----

+
Von diesen müssen sie die Installationspakete für die neue Betriebssystemversion herunterladen.
*Wichtig:* Die Edition und die Versionsnummer von {CMK} müssen exakt der bisher verwendeten entsprechen.

. Deinstallieren Sie jetzt alle nicht benutzten {CMK}-Versionen.
Im folgenden Befehl sorgt der Parameter `--purge` dafür, auch alte Konfigurationsdateien zu tilgen.

+
[{shell}]
----
{c-root} apt-get remove --purge -y check-mk-enterprise-2.2.0p1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  check-mk-enterprise-2.2.0p1*
0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
After this operation, 884 MB disk space will be freed.
(Reading database ... 125980 files and directories currently installed.)
Removing check-mk-enterprise-2.2.0p1 (0.focal) ...
(Reading database ... 89444 files and directories currently installed.)
Purging configuration files for check-mk-enterprise-2.2.0p1 (0.focal) ...
Processing triggers for systemd (245.4-4ubuntu3.21) ...
----

=== Durchführung

Und nun zur heißen Phase, in welcher der {CMK}-Server nicht zur Verfügung steht.

. Stoppen Sie Ihre {CMK}-Instanz:

+
[{shell}]
----
{c-root} omd stop mysite
----

. Benennen Sie den Softlink um, welcher auf die verwendete {CMK}-Installation zeigt:

+
[{shell}]
----
{c-root} mv -v /opt/omd/sites/mysite/{,_}version
----
// TK: Du Kommandohexer: Schlag mich, aber ich verstehs nicht: Was macht der Befehl?
// MFS: Expandiert zu
// mv -v /opt/omd/sites/mysite/version /opt/omd/sites/mysite/_version
// häufiger gesehen:
// mv x.doc x.bak
// abgekürzt durch
// mv x.{doc,bak}

. Jetzt können Sie {CMK} deinstallieren.
In diesem Fall behalten Sie vorhandene Konfigurationsdateien:

+
[{shell}]
----
{c-root} apt-get remove -y check-mk-enterprise-2.2.0p2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  check-mk-enterprise-2.2.0p2*
...
----

. Führen Sie das Upgrade von Linux entsprechend der Anleitung des jeweiligen Distributors durch.
// TK: Da Du ja oben sagst, exemplarisch gehts um Ubuntu 20.04>22.04, könnte man ja hier die zugehörige Anleitung verlinken. Nur welche? Die hier? https://ubuntu.com/tutorials/upgrading-ubuntu-desktop#1-before-you-start
Im Fall von Ubuntu wäre das:

+
[{shell}]
----
{c-root} do-release-upgrade
----

+
Wird ein Neustart empfohlen, folgen Sie der Empfehlung bevor Sie zum nächsten Schritt gehen.

. Machen Sie die Umbenennung des Softlinks rückgängig, welcher auf die verwendete {CMK}-Installation zeigt:

+
[{shell}]
----
{c-root} mv -v /opt/omd/sites/mysite/{_,}version
----

. Installieren Sie nun das zur neuen Version der verwendeten Distribution passendes Paket von {CMK}.
Im Falle von Ubuntu genügt an dieser Stelle der folgende Befehl:

+
[{shell}]
----
{c-root} apt install /tmp/check-mk-enterprise-2.2.0p2_0.jammy_amd64.deb
----

+
Halten Sie sich bei der Neuinstallation von {CMK} an die jeweilige xref:install_packages#[detaillierte Installationsanleitung] für Ihre jeweilige Distribution.

. Starten Sie Ihre {CMK}-Instanz:

+
[{shell}]
----
{c-root} omd start mysite
----

// MFS: 2. und 5. sind eher Workaround, um auf nicht ganz Debian typisches Verhalten zu reagieren, siehe CMK-13090

////
MFS: Einschub nach 3?
. Hängen Sie dann das `tmp`-Verzeichnis der Site aus:

+
[{shell}]
----
{c-root} umount /opt/omd/sites/mysite/tmp
----

+
Sollte das Aushängen fehlschlagen, führen Sie bitte einen Neustart durch und machen Sie danach an diesem Punkt weiter.

. An dieser Stelle ist es sinnvoll, eine lokale Sicherung per _Snapshot_ oder `rsync` durchzuführen.
Die Trailing Slashes im Pfadnamen sind wichtig, damit `rsync` Verzeichnisinhalte kopiert.

+
[{shell}]
----
{c-root} rsync -avSP /opt/omd/ /opt/omd.bak/
----
////

[#exsitu]
== Archivierung, Neuinstallation und Wiederherstellung _(ex situ)_

Diese Methode bietet sich häufig beim Einsatz von {CMK} in virtualisierten Umgebungen an, wo es möglich ist, einen zweiten Server mit der neuen Distributionsversion vorbereitend "hochzuziehen" und mit diesem im Parallelbetrieb bereits erste Tests durchzuführen.
Zudem ist die Flexibilität größer, weil auch ein Wechsel der Linux-Distribution möglich ist.
Technisch entspricht das der Vorgehensweise in einem Schadensfall als _Backup, Reinstall and Restore_.

=== Vorbereitung

Wesentlicher Vorbereitungsschritt ist, das passende {CMK}-Installationspaket für die neue Distributionsversion herunterzuladen.

// . {CMK} auf höchst-mögliches Patchlevel bringen
// TK: Listen mit nur einem Eintrag sind überflüssig: Liste aufgelöst.

Verschaffen Sie sich einen Überblick über die von den Instanzen genutzten {CMK}-Versionen:

[{shell}]
----
{c-root} omd sites
SITE      VERSION        COMMENTS
mysite    2.2.0p2.cee    default version
----

Von diesen müssen sie die Installationspakete für die neue Betriebssystemversion herunterladen.
*Wichtig:* Die Edition und die Versionsnummer von {CMK} müssen exakt der bisher verwendeten entsprechen.

=== Durchführung

// Die Methode 'Manni'
// MFS: Manni ist natürlich auch der Beste!

Die Schritte, welche hier seriell dargestellt werden, können Sie oft teilweise parallelisieren, was die Ausfallzeit minimieren hilft.
So zum Beispiel bei Verwendung virtueller Maschinen oder wenn sowieso eine Hardware-Neuanschaffung ansteht.

. Stoppen Sie Ihre {CMK}-Instanz – hier ist dieser Schritt nicht zwingend, aber aus Gründen der Konsistenz der Daten empfohlen:

+
[{shell}]
----
{c-root} omd stop mysite
----

. Erstellen Sie ein xref:omd_basics#omd_backup_restore[Archiv] (in anderen Kontexten Backup) der Instanz.
// TK: unter der alten Distributionsversion ist überflüssig
Unser Beispiel verwendet als Ziel ein Netzwerk-Share, welches später auch auf der neuen Installation bereitstehen wird.


+
[{shell}]
----
{c-omd} omd backup /mnt/someshare/mysite.tgz
----

. Bereiten Sie nun das Zielsystem vor und konfigurieren Sie dort die für {CMK} benötigte Software, beispielsweise das E-Mail-System.
Verwenden Sie denselben Host-Namen und dieselbe IP-Adresse wie beim Ausgangssystem.

// . xref:install_packages#[Installieren] Sie die gleiche {CMK}-Version mit exakt identischem Patchlevel.
// TK: Das hast Du oben schon als Wichtig betont. Hier reicht:
. xref:install_packages#[Installieren] Sie die zuvor heruntergeladene {CMK}-Version. passend für die neue Distribution.

+
Im Falle von Ubuntu genügt an dieser Stelle der folgende Befehl:

+
[{shell}]
----
{c-root} apt install /tmp/check-mk-enterprise-2.2.0p2_0.jammy_amd64.deb
----

. Erstellen Sie eine neue Instanz mit demselben Namen wie die gesicherte Instanz:

+
[{shell}]
----
{c-root} omd create mysite
----

. Führen Sie nun als Instanzbenutzer die Wiederherstellung aus dem Archiv durch:

+
[{shell}]
----
{c-omd} omd restore /mnt/someshare/mysite.tgz
----

. Starten Sie Ihre {CMK}-Instanz:

+
[{shell}]
----
{c-omd} omd start
----

// MFS: omd create mysite und omd restore /mnt/someshare/mysite.tgz könnten zusammengefasst werden, indem man omd restore als root durchführt, das kann bei älteren CMK-Versionen allerdings manuelle Nacharbeit erfordern, daher würde ich gerne die Methode mit zwei Schritten belassen.

////
[#mixed]
== Mischform Sites auf eigener Partition
MFS: Rücksprache mit Consulting, wie groß der Bedarf ist.
////
