// -*- coding: utf-8 -*-
// IGNORE ActiveDirectory Okta OpenLDAP SP2 UI macOS
include::global_attr.adoc[]
= Release notes
:revdate: 2023-05-16
:title: Versionshinweise für {CMK} {v22}
:description: Checkmk 2.2.0 funktioniert mit einer Reihe von unterstützten Plattformen und Integrationen, die, außer aus besonderen Gründen (z.B. Sicherheit), während der aktiven Wartung inkl. aller Patch-Versionen unterstützt werden.

{related-start}
xref:update_major#[Update auf Version 2.2.0]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
xref:agent_linux#[Linux überwachen]
xref:agent_windows#[Windows überwachen]
{related-end}

== Einleitung

Dieses Dokument listet die unterstützten Plattformen und Integrationen von {CMK} {v22} auf. Sofern keine besonderen Gründe vorliegen (z. B. Sicherheit), werden diese Plattformen während der aktiven Wartung von {CMK} {v22} einschließlich aller Patch-Versionen unterstützt.

== Unterstützte OS-Server

{CMK} kann auf den folgenden Linux-Server-Betriebssystemdistributionen und -versionen installiert werden, die auf x86_64-Hardware laufen. Wir werden auch neue Versionen dieser Distributionen für die Unterstützung evaluieren.

[cols="20,~",options=header]
|===
|Betriebssystem |Unterstützte Versionen
|*Ubuntu* |20.04
| |22.04
|*Debian* |10
| |11
|*RHEL* |7
| |8
| |9
|*SLES* | 12 SP5
| |15 SP1
| |15 SP2
| |15 SP3
| |15 SP4
|===

== Unterstützte Browser und Versionen

Die {CMK}-Benutzeroberfläche ist für die folgenden Desktop-Browser und Browser-Mindestversionen geprüft:

* Google Chrome >= 100 unter Windows, Linux und macOS
* Firefox >= 100 unter Windows, Linux und macOS
* Microsoft Edge >= 100 unter Windows
* Safari >= 15.6.1 unter macOS

Die mobile {CMK}-Benutzeroberfläche ist für die folgenden mobilen Browser geprüft:

* Safari unter iOS (aktuelle und letzte Hauptversion des Betriebssystems)
* Google Chrome unter Android (aktuelle und letzte Hauptversion des Betriebssystems)

== Unterstützte Grafana Plugin Versionen
{CMK} {v22} unterstützt die folgenden Grafana Plugin Versionen:

* >= 3.0.0

== Unterstützte {CMK} Appliance Versionen
{CMK} {v22} kann auf den folgenden Versionen der {CMK} Appliance ausgeführt werden:

* >= 1.6.3

== LDAP Server Integrationen
{CMK} {v22} unterstützt die Synchronisierung mit LDAP der folgenden LDAP-Server:

* Microsoft Active Directory
* OpenLDAP
* 389 Directory Server

== SAML IdP Unterstützung
Die SAML-Integration unterstützt die folgenden IdPs:

* Microsoft Azure Active Directory
* Google Cloud
* Okta

{CMK} arbeitet möglicherweise auch mit anderen SAML-Integrationen zusammen, aber für diese kann keine Unterstützung gegeben werden.

== ntopng Integration
Die ntopng-Integration unterstützt die folgenden Versionen von ntopng Pro und Enterprise:

* >= 5.6

== Nagvis
Nagvis hängt von PHP ab und benötigt eine Mindestversion, um zu laufen. Bitte stellen Sie sicher, dass Sie eine passende PHP-Version in Ihrer Installation haben, um Nagvis auszuführen:

* >= 7.2

== InfluxDB
{CMK} unterstützt den Export von Daten an die folgenden Versionen der InfluxDB API:

* >= 2.0