//encoding: utf-8
// IGNORE TBD p22 p23 pN BTRFS Unmount Netzwerkshare 
include::global_attr.adoc[]
= Linux-Update auf dem {CMK}-Server
:revdate: draft
:title: Linux-Update auf dem {CMK}-Server
:description: Was es beim Release-Upgrade der Linux-Distribution auf dem {CMK}-Server zu beachten gibt, erfahren Sie in diesem Artikel.

{related-start}
link:update.html[Updates und Upgrades]
link:install_packages.html[Grundsätzliches zur Installation von {CMK}]
{related-end}

[#intro]
== Einleitung

Für das Release-Upgrade der Linux-Distribution auf einem {CMK}-Server gibt es verschiedene empfohlene Methoden.
Welche davon für Sie die richtige ist, hängt von den Möglichkeiten Ihrer IT-Landschaft, dem Datenbestand der {CMK}-Installation und der angestrebten Downtime ab. Die unterschiedliche Methoden mit Ihren jeweiligen Voraussetzungen stellen wir hier vor.
Selbstverständlich sind auch Kombinationen der vorgestellten Methoden möglich, zum Beispiel, wenn Sie `/opt/omd` oder `/opt/omd/sites` auf einem eigenen Mountpoint verwenden.

Das Release-Upgrade spielen wir hier exemplarisch am Beispiel des Wechsels von Ubuntu 20.04 (Focal) auf 22.04 (Jammy) durch.
Bei anderen Distributionen weichen die Befehle für Update und Paketmanagement hiervon mehr oder weniger stark ab.

Unser Beispielsystem nutzt nur eine einzige Site.
Falls Sie mehrere Sites auf dem zu aktualisierenden System betreiben (beispielsweise eine produktive und eine zum Testen), sind die Site spezifischen Befehle für jede zu wiederholen.

[#getyourbackupdone]
== Hinweise zum Backup

Die Wichtigkeit einer Datensicherung ausreichenden Umfangs, welche auf Konsistenz geprüft ist, müssen wir IT-Profis nicht wirklich erklären.
Im Idealfall – beispielsweise beim Betrieb von {CMK} in einer virtuellen Maschine – ist eine Vollsicherung leicht durch Kopieren von Festplattenimages möglich.

Wir empfehlen mindestens:

* Eine Sicherung mit den von {CMK} bereitgestellten Tools, entweder auf der Kommandozeile mit dem xref:omd_basics#omd_backup_restore[Befehl `omd`] oder im xref:backup#[Setup] erstellt. Dies kann vorbereitend im laufenden Betrieb erledigt werden.
* Eine Sicherung des Inhaltes von `/opt/omd/sites` mit Werkzeugen des Betriebssystems nach Stoppen aller Instanzen und Unmount der instanzspezifischen `/tmp` Dateisysteme. Dies kann im Zuge des Updates durchgeführt werden.

Bewahren Sie die Sicherung _separat_ von der zu aktualisierenden Maschine auf und testen Sie das Backup _vor_ den ersten Änderungen am Produktivsystem.

Falls Sie sich bei der Installation des {CMK}-Servers für ein _Copy-on-Write-Dateisystem_ wie ZFS oder BTRFS entschieden haben, sollten Sie vor dem Update _Snapshots_ erstellen.
Diese ersetzen kein separat gelagertes Backup, können aber bei Wiederherstellung des Ursprungszustandes nach einem fehlgeschlagenen Update helfen, Downtimes erheblich zu reduzieren.

[#insitu]
== Aktualisierung an Ort und Stelle _(in situ)_

// Die Methode 'Alex'
// MFS: Alex ist der Beste!
// MFS: Dreifache Verwendung desselben Begriffs für Suchmaschinen.
Diese Methode (englisch _in-place_ oder lateinisch _in situ_) ist oft beim Einsatz von {CMK} auf dedizierter Hardware mit großen Datenbeständen sinnvoll, wo Backup und Restore die Downtime deutlich erhöhen würde.

=== Vorbereitung

Die Vorbereitung besteht vor allem aus der Entfernung _aller_ bereits jetzt nicht mehr benötigter {CMK}-Pakete.
So vermeiden Sie beim eigentlichen Upgrade Probleme im Paketmanagement.
Daneben sollten Sie bereits jetzt das richtige {CMK}-Installationspaket für die neue Distributionsversion herunterladen.

. Verschaffen Sie sich zuerst einen Überblick über installierte {CMK}-Versionen...

+
[{shell}]
----
{c-root} omd versions
2.1.0p25.cre
2.2.0p1.cee
2.2.0p2.cee (default)
----

. ...und dann, welche davon tatsächlich im Einsatz sind. 
Von diesen müssen sie die Installationspakete für die neue Betriebssystemversion herunterladen.
*Wichtig:* Die Versionsnummer von {CMK} und die Edition muss exakt der vorher verwendeten entsprechen.

+
[{shell}]
----
{c-root} omd sites
SITE      VERSION        COMMENTS
mysite    2.2.0p2.cee    default version
----

. Deinstallieren Sie jetzt alle nicht benutzten {CMK}-Versionen.
Im folgenden Befehl sorgt der Parameter `--purge` dafür, auch alte Konfigurationsdateien zu tilgen.

+
[{shell}]
----
{c-root} apt-get remove --purge -y check-mk-enterprise-2.2.0p1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  check-mk-enterprise-2.2.0p1*
0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
After this operation, 884 MB disk space will be freed.
(Reading database ... 125980 files and directories currently installed.)
Removing check-mk-enterprise-2.2.0p1 (0.focal) ...
(Reading database ... 89444 files and directories currently installed.)
Purging configuration files for check-mk-enterprise-2.2.0p1 (0.focal) ...
Processing triggers for systemd (245.4-4ubuntu3.21) ...
----

=== Durchführung

Und nun zur heißen Phase, in welcher der {CMK}-Server nicht zur Verfügung steht.

. Stoppen Sie Ihre {CMK}-Site:

+
[{shell}]
----
{c-root} omd stop mysite
----

. Benennen Sie den Softlink um, welcher auf die verwendete {CMK}-Installation zeigt:

+
[{shell}]
----
{c-root} mv -v /opt/omd/sites/mysite/{,_}version
----

. Jetzt können Sie {CMK} deinstallieren.
In diesem Fall behalten Sie vorhandene Konfigurationsdateien:

+
[{shell}]
----
{c-root} apt-get remove -y check-mk-enterprise-2.2.0p2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  check-mk-enterprise-2.2.0p2*
...
----

. Führen Sie das Upgrade von Linux entsprechend der Anleitung des jeweiligen Distributors durch.
Wird ein Neustart empfohlen, folgen Sie der Empfehlung bevor Sie zum nächsten Schritt gehen.

. Machen Sie die Umbenennung des Softlinks rückgängig, welcher auf die verwendete {CMK}-Installation zeigt:

+
[{shell}]
----
{c-root} mv -v /opt/omd/sites/mysite/{_,}version
----

. Installieren Sie nun das zur neuen Version der verwendeten Distribution passendes Paket von {CMK}.
Im Falle von Ubuntu würde an dieser Stelle der folgende Befehl genügen:

+
[{shell}]
----
{c-root} apt install /tmp/check-mk-enterprise-2.2.0p2_0.jammy_amd64.deb
----

+
Halten Sie sich bei der Neu-Installation von {CMK} an die jeweilige xref:install_packages#[detaillierte Installationsanleitung] für Ihre jeweilige Distribution.

. Starten Sie Ihre {CMK}-Site:

+
[{shell}]
----
{c-root} omd start mysite
----

// MFS: 2. und 5. sind eher Workaround, um auf nicht ganz Debian typisches Verhalten zu reagieren, siehe CMK-13090

////
MFS: Einschub nach 3?
. Hängen Sie dann das `tmp`-Verzeichnis der Site aus:

+
[{shell}]
----
{c-root} umount /opt/omd/sites/mysite/tmp
----

+
Sollte das Aushängen fehlschlagen, führen Sie bitte einen Neustart durch und machen Sie danach an diesem Punkt weiter.

. An dieser Stelle ist es sinnvoll, eine lokale Sicherung per _Snapshot_ oder `rsync` durchzuführen.
Die Trailing Slashes im Pfadnamen sind wichtig, damit `rsync` Verzeichnisinhalte kopiert.

+
[{shell}]
----
{c-root} rsync -avSP /opt/omd/ /opt/omd.bak/
----
////

[#exsitu]
== Sicherung, Neuinstallation, Wiederherstellung _(ex situ)_

Diese Methode bietet sich häufig beim Einsatz von {CMK} auf in virtualisierten Umgebungen an, wo es möglich ist, einen zweiten Server mit der neuen Distributionsversion vorbereitend "hochzuziehen" und mit diesem im Parallelbetrieb bereits erste Tests durchzuführen.
Zudem ist die Flexibilität größer, weil auch ein Wechsel der Linux-Distribution möglich ist.

=== Vorbereitung

Wesentlicher Vorbereitungsschritt ist, das passende {CMK}-Installationspaket für die neue Distributionsversion herunterzuladen.

// . {CMK} auf höchst-mögliches Patchlevel bringen
* Verschaffen Sie sich einen Überblick über die von den Instanzen genutzten {CMK}-Versionen.
Von diesen müssen sie die Installationspakete für die neue Betriebssystemversion herunterladen.
*Wichtig:* Die Versionsnummer von {CMK} und die Edition muss exakt der vorher verwendeten entsprechen.

+
[{shell}]
----
{c-root} omd sites
SITE      VERSION        COMMENTS
mysite    2.2.0p2.cee    default version
----

=== Durchführung

// Die Methode 'Manni'
// MFS: Manni ist natürlich auch der Beste!

Die Schritte, welche hier seriell dargestellt werden, können Sie oft teilweise parallelisieren, was die Downtime minimieren hilft.
So zum Beispiel bei Verwendung virtueller Maschinen oder wenn sowieso eine Hardware-Neuanschaffung ansteht.

. Stoppen Sie Ihre {CMK}-Site – hier ist dieser Schritt nicht zwingend, aber aus Gründen der Konsistenz der Daten empfohlen:

+
[{shell}]
----
{c-root} omd stop mysite
----

. Führen Sie unter der alten Distributionsversion ein xref:omd_basics#omd_backup_restore[Backup] der Site durch. Unser Beispiel verwendet als Ziel ein Netzwerkshare, welches später auch auf der neuen Installation bereitstehen wird.

+
[{shell}]
----
{c-omd} omd backup /mnt/someshare/mysite.tgz
----

. Bereiten Sie nun das Zielsystem vor und konfigurieren Sie dort benötigte Software, beispielsweise das Mailsystem.
Verwenden Sie denselben Hostnamen und dieselbe IP-Adresse wie das Ausgangssystem.

. xref:install_packages#[Installieren] Sie die gleiche {CMK}-Version mit exakt identischem Patchlevel.
Im Falle von Ubuntu würde an dieser Stelle der folgende Befehl genügen:

+
[{shell}]
----
{c-root} apt install /tmp/check-mk-enterprise-2.2.0p2_0.jammy_amd64.deb
----

. Erstellen Sie eine neue Site mit demselben Namen wie die gesicherte Site:

+
[{shell}]
----
{c-root} omd create mysite
----

. Führen Sie nun als Site-User die Wiederherstellung der Sicherung durch:

+
[{shell}]
----
{c-omd} omd restore /mnt/someshare/mysite.tgz
----

. Starten Sie Ihre {CMK}-Site:

+
[{shell}]
----
{c-omd} omd start
----

// MFS: omd create mysite und omd restore /mnt/someshare/mysite.tgz könnten zusammengefasst werden, indem man omd restore als root durchführt, das kann bei älteren CMK-Versionen allerdings manuelle Nacharbeit erfordern, daher würde ich gerne die Methode mit zwei Schritten belassen.

////
[#mixed]
== Mischform Sites auf eigener Partition
MFS: Rücksprache mit Consulting, wie groß der Bedarf ist.
////
