include::global_attr.adoc[]
= Sicherheit (Security)
:revdate: draft
:title: {CMK} zusätzlich absichern
:description: Checkmk ist bereits per Design sehr sicher. Welche Maßnahmen Sie ergreifen können, um ihr Monitoring noch sicherer zu machen, erfahren Sie in diesem Artikel.

{related-start}
link:omd_https.html[Weboberfläche mit HTTPS absichern]
link:agent_linux.html[Linux überwachen]
link:ldap.html[Benutzerverwaltung mit LDAP/Active Directory]
{related-end}


Hier wird ein Übersichtsartikel darüber entstehen, wie Sie {CMK} so aufsetzen,
dass Sie eine optimale Netzwerksicherheit für Ihren Monitoringserver aber auch
für die überwachten Systeme haben.

Die gute Nachricht schonmal vorab: {CMK} hat eine durch seine eigenen Agenten
eine Architektur, die von Anfang an für höchste Sicherheit entworfen wurde. Das
äußert sich z.B. daran, dass die Agenten grundsätzlich keine Daten vom Netzwerk
lesen. Einem Angreifer ist es daher unmöglich, Befehle einzuschleusen. Die Agenten
vertrauen somit nicht einmal dem Monitoringserver.

An verschiedenen Stellen im {CMK} werden HTTP-Protokolle eingesetzt - sei es
für eine interne Kommunikation oder die Anbindung von anderen Systemen. Setzen
Sie hier HTTPS ein wo immer möglich. Auch an anderen Stellen gibt es optional
Verschlüsselungstechniken. Dazu finden Sie auch Anleitungen in diesem
Handbuch:

- link:omd_https.html[Weboberfläche mit HTTPS absichern]
- link:agent_linux.html#security[Linux-Agent absichern]
- link:ldap.html#ssl[LDAP-Anbindung mit SSL absichern]
- link:appliance_usage.html#ssl[Appliance-GUI per TLS absichern]
- link:managing_docker.html#https[ Docker mit HTTPs absichern]

//IN:cma_backup#encryption Appliance-Datensicherung verschlüsseln
