= Sicherheit (Security)
:revdate: draft
[.seealso][#omd_https] [#agent_linux] [#ldap]MT:(CMK) zusätzlich absichern
MD:Checkmk ist bereits per Design sehr sicher. Welche Maßnahmen Sie ergreifen können, um ihr Monitoring noch sicherer zu machen, erfahren Sie in diesem Artikel.

Hier wird ein Übersichtsartikel darüber entstehen, wie Sie (CMK) so aufsetzen,
dass Sie eine optimale Netzwerksicherheit für Ihren Monitoringserver aber auch
für die überwachten Systeme haben.

Die gute Nachricht schonmal vorab: (CMK) hat eine durch seine eigenen Agenten
eine Architektur, die von Anfang an für höchste Sicherheit entworfen wurde. Das
äußert sich z.B. daran, dass die Agenten grundsätzlich keine Daten vom Netzwerk
lesen. Einem Angreifer ist es daher unmöglich, Befehle einzuschleusen. Die Agenten
vertrauen somit nicht einmal dem Monitoringserver.

An verschiedenen Stellen im (CMK) werden HTTP-Protokolle eingesetzt - sei es
für eine interne Kommunikation oder die Anbindung von anderen Systemen. Setzen
Sie hier HTTPS ein wo immer möglich. Auch an anderen Stellen gibt es optional
Verschlüsselungstechniken. Dazu finden Sie auch Anleitungen in diesem
Handbuch:

IN:omd_https
IN:agent_linux#security Linux-Agent absichern
IN:ldap#ssl LDAP-Anbindung mit SSL absichern
IN:cma_ssl
IN:cma_backup#encryption Appliance-Datensicherung verschlüsseln
IN:managing_docker#https  Docker mit HTTPs absichern
