= Systemmonitoring mit Checkmk - Teil 1: Grundlagen
<br>
### Ich berufe mich hier mal auf "ernste Layoutprobleme".
### siehe Artikel internal_syntax
### Das sieht zwar auf der Webseite seltsam aus, aber die alternative ist im
### gedruckten ganz furchtbar.
<br>
Hier finden Sie die Schulungsinhalte und den Ablauf der
Schulung „_Systemmonitoring mit (CMK) - Teil 1: Grundlagen_“.
Dies entspricht den Inhalten der während der Schulung gezeigten
Folien. Überall wo es schon passende Artikel in diesem Handbuch
gibt, finden Sie hier die Seitenzahlen, so dass Sie diese während
der Schulung schnell finden können.

== Tag 1

=== Vorstellung

SB:tribe29_logo.png

=== Vorstellung von (CMK)

=== Installation

IN:intro#editions              Die Editionen
IN:install_packages            Installation von (CMK)
IN:omd_basics                  Anlegen von Instanzen
IN:cmk_commandline             (CMK) auf der Kommandozeile
IN:intro#guioverview           Überblick über die GUI

SB:filesystem.png

=== Hosts aufnehmen

IN:intro#hosts                Hosts, Services, Agenten
IN:intro#folders              Ordnerstruktur
IN:intro#linux                Linux-Server überwachen
IN:intro#services             Konfiguration der Services
IN:intro#activatechanges      Änderungen aktivieren

=== Überwachung von Windows

IN:agent_windows              Der Windows-Agent

=== Überwachen via SNMP

IN:snmp#intro                 Grundlagen von SNMP
IN:snmp#snmphost              SNMP-Hosts in (CMK)

== Tag 2

=== Anpassen/Erweitern des (CMK) Agenten

IN:localchecks                        Local Checks
IN:agent_linux#mrpe                   MRPE
IN:wato_monitoringagents#bakery       Agenten paketieren
IN:agent_deployment                   Automatische Agenten-Updates

=== Die grafische Oberfläche im Überblick

IN:intro#tactical_overview     Sidebar-Snapins: Tactical Overview, Views, Bookmarks, Quicksearch, Master Control
IN:user_interface              Das Haupt-Dashboard

=== Anpassungen der GUI

IN:intro#sidebar_customizing   Die Sidebar anpassen
IN:views#edit                  Views anpassen
IN:dashboards#new              Ein Dashboard erstellen

=== Das Metriksystem

IN:intro#metrics               Graphen und Metriken
IN:graphing#graph_collections  Graphensammlungen

== Tag 3

=== Operating

IN:intro#hosts                 Die Status im Monitoring
IN:intro#ack                   Quittierungen (Acknowledgements)
IN:intro#downtimes             Wartungszeiten (Scheduled Downtimes)
IN:intro#rules                 Regelbasierte Konfiguration
IN:intro#hosttags              Hosttags
IN:labels                      Labels

=== Tuning des Monitorings

IN:intro#filesystems           Dateisysteme
IN:intro#switchports           Switchports
IN:intro#reboothosts           Hosts, die rebooten
IN:fehlt                       Logwatch bei Windows
IN:intro#avgvalues             Mittelwerte
IN:fehlt                       Predictive Monitoring
IN:fehlt                       Timespecific Parameters
IN:intro#sporadic              Sporadische Fehler
IN:monitoring_basics#parents   Parent/Child-Beziehungen
IN:wato_services#processes     Prozesse und Services

== Tag 4

=== Fortgeschrittene Serviceverwaltung

IN:intro#disabled                Checks und Services ignorieren
IN:intro#discovery               Discovery Check
IN:wato_services#bulk_discovery  Bulk Discovery

=== Benutzer in (CMK)

IN:intro#roles                 Rechte und Rollen
IN:intro#contacts              Kontakte und Zuständigkeiten
IN:intro#hostcontacts          Zuweisen von Kontaktgruppen zu Hosts und Services
IN:intro#users                 Benutzerverwaltung

=== Alarmierung

IN:intro#notifications         Konzept von Alarmen
IN:intro#notify_init           Alarmierung aufsetzen
IN:timeperiods                 Zeitperioden

=== Verteiltes Monitoring

IN:distributed_monitoring#livestatus        Zentrale Statusansicht
IN:distributed_monitoring#distr_wato        Zentrale Konfiguration
IN:distributed_monitoring#livestatus_tls    Absicherung der Verbindungen

SB:distributed_monitoring.png

== Tag 5

=== HW/SW-Inventur

IN:inventory#activate          Aktivierung
IN:inventory#operating         Die Inventur-View
IN:inventory#plugin            Das Agenten-Plugin
IN:inventory#changes           Änderungen in der Inventur

=== Rekapitulation der Konfiguration

=== Backup & Restore

IN:omd_basics#backup           B/R auf der Kommandozeile
IN:fehlt                       B/R in der GUI

=== Update von (CMK)

IN:update                      Aktualisierung von (CMK)

=== Aggregation der Metrikdaten

IN:graphing#adding_metrics  min/max/avg
### Ich bin mir nicht ganz sicher, was hier mit "min/max/avg" gemeint war.
### In dem nun verlinkten Abschnitt kommen die drei Begriffe jedenfalls vor.
