// -*- coding: utf-8 -*-
// IGNORE 0p1 0p11 0p13 0p16 0p29 0p31 0p7 Kompatibilitäts p1 zeilen Almalinux endoflife
include::global_attr.adoc[]
= Update-Matrix für Version {v22}
:revdate: draft
:title: Update-Matrix für Version {v22}
:description: Dieser Artikel zeigt die von {CMK} unterstützten Linux-Distributionsversionen, damit Sie die Reihenfolge ermitteln können, um Updates von {CMK} auf Ihrem Linux-Server durchzuführen.
// TK: Die description war zu lang. Ist jetzt kürzer, aber immer noch zu lang (länger als 160 Zeichen).

{related-start}
xref:update#[Updates und Upgrades]
xref:update_major#[Update auf Version 2.2.0]
xref:release_upgrade#[Linux-Upgrade auf dem {CMK}-Server]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
{related-end}


////
TK: Allgemein:
- Ich würde das Teil als eigenen Artikel stehen lassen und aus anderen Artikeln verlinken. Allerdings hab ich zu meinem Erstauen gar nicht *die* Stelle gefunden, aus der heraus der Link in diesen Artikel wirklich passen würde: Sicher aus release_upgrade, evtl. auch aus update_major.html#linux_versions, update.html#update_major_version, install_packages.
- Ich hab ja schon gesagt, dass ich über die Lücken in den Zeilen gestolpert bin. Müssen/Sollten wir darüber ein Wort verlieren?
- includes: Header Spalte 1 ändern: Distribution > Distributionsversion
- Die Tabellenspalten 2 bis letzte haben nicht die gleiche Breite.
////

[#intro]
== Einleitung

Mit jeder Version von {CMK} fallen bislang unterstützte Linux-Versionen weg und neue kommen hinzu.
Dies kann es erforderlich machen, vor einem Update von {CMK} ein oder mehrere xref:release_upgrade#[Upgrades Ihrer Linux-Distribution] vorzunehmen.
Die Infografiken in diesem Artikel helfen Ihnen bei der Ermittlung der geeigneten Reihenfolge.
Studieren Sie diese aufmerksam, bevor Sie im link:https://checkmk.com/download/archive[Download-Archiv^] suchen oder Anfragen nach alten Paketen stellen.

Sollten Sie auf eine ältere {CMK}-Version als {v22} aktualisieren wollen, wählen Sie im Versions-Auswahlmenü bitte die Version, die _Ziel_ der Aktualisierung ist.

Die {CMK}-Versionsnummern am Beginn eines grünen Balkens oder einer leeren Fläche zeigen immer diejenigen an, _ab_ der eine Veränderung vorgenommen wurde, also eine Linux-Version neu unterstützt oder nicht mehr unterstützt wird.
Eine Pfeilspitze ab Ende bedeutet, dass diese {CMK}-Version im Support ist, also weitere Patch-Releases folgen werden.
Ein stumpfes Ende kennzeichnet eine {CMK}-Version, die Ihr Support-Ende erreicht hat.
// Aktualisierungen der Tabellen erfolgen entsprechend nur, wenn Änderungen in der Distributionsunterstützung erfolgt ist.
// Gegebenenfalls wird das Änderungsdatum nach erfolgter Kontrolle angepasst, ohne dass Änderungen an den Tabellen erfolgt sind.
// TK: Die beiden Sätze finde ich überflüssig. Wir halten unsere Inhalte doch immer aktuell ;-) Das klingt so, als ob das hier die Ausnahme wäre.
// TK: Vielleicht stattdessen schreiben, dass sich die Tabelleninhalte aus den Daten zu den verfügbaren Downloads aus dem Download-Archiv generiert werden (d.h. nicht manuell gepflegt werden). Erhöht das Vertrauen.
Erstellt werden die Tabellen automatisch aus den Daten zu den verfügbaren Downloads, das Änderungsdatum des Artikels gibt folglich nicht die Aktualität der angezeigten Daten wieder.



[#steps]
== Ermittlung der Update-Schritte
// TK: Das würde ich zu einem Hauptkapitel machen, also:
// TK: == Ermittlung der Update-Schritte

Die Aufgabe ist es nun, im Schaubild für Ihre Linux-Distribution tendenziell von links oben nach rechts unten zu gelangen.
// TK: Nunja: Man fängt ja nicht immer links oben an. Vielleicht so?:
// TK: Die Aufgabe ist es nun, in der Tabelle für Ihre Linux-Distribution tendenziell von links oben nach rechts unten zu gelangen.
Dabei sind die Vorgaben für das xref:update#[Update von {CMK}] zu berücksichtigen:

* Es darf keine Major-Version ausgelassen werden.
// TK Nebenbei: Wäre schön, wenn wir in cmk_versions mal schreiben würden, was Major-, Minor- und Patch-Versionen sind...

* Vor dem Update der Major-Version muss auf die höchste verfügbare Patch-Version aktualisiert werden, Mindestanforderungen sind im xref:update_major#update_patch[Artikel zum Update auf {v22}] beschrieben.

* Beim Upgrade der Linux-Distribution muss auf der neuen Distributionsversion exakt dieselbe {CMK}-Version installiert werden, die auf der alten vorhanden war.
// TK: Puh: Diese 3 Voraussetzungen sind bei uns leider nicht an einer zentralen Stelle zu finden. Warum nicht?
// TK: Nr.1 finde ich in update.html#update_major_version
// TK: Nr.2 finde ich auf die Schnelle gar nicht, obwohl ich weiss, dass das irgendwo steht...
// MFS: http://localhost:8088/latest/de/update_major.html#update_patch
// TK: Nr.3 steckt mitten in der Prozedur von release_upgrade.html#_durchführung versteckt.

Auch Linux-Distributoren machen in der Regel eine Vorgabe:

* Upgrades dürfen keine Version auslassen.

Ubuntu ist an dieser Stelle etwas speziell:
LTS-Versionen (_Long Term Support_, fünf Jahre Updates) sollten immer nur auf die nächste LTS-Version aktualisiert werden,
STS-Versionen (_Short Term Support_, sieben bis neun Monate Updates) müssen in Halbjahresschritten aktualisiert werden.

Aus diesen Anforderungen ergibt sich, dass Sie sich in der Infografik für Ihre Linux-Distribution nur zeilen- oder spaltenweise bewegen dürfen – jedoch niemals diagonal – und, dass Sprünge nur dann zulässig sind, wenn sie nicht gegen die oben genannten Vorgaben verstoßen.
// TK: Unklar, was beliebig meint. Vielleicht so:
// TK: ... dass Sprünge nur dann zulässig sind, wenn sie nicht gegen die oben genannten Vorgaben verstossen.
Für ein Update von Debian 9 mit {CMK} {v21}p1 auf Debian 12 mit {CMK} {v22} ergibt sich so die folgende Update-Reihenfolge:

. Unter Debian 9 führen Sie das Update von {CMK} {v21}p1 xref:update#[auf die aktuelle Patch-Version] von {v21} durch.

. Führen Sie das Upgrade von Debian 9 auf 10, 11 und schließlich auf 12 durch, so wie es im Artikel zum xref:release_upgrade#[Linux-Upgrade auf dem {CMK}-Server] beschrieben ist.

. Unter Debian 12 aktualisieren Sie die aktuelle Patch-Version von {CMK} {v21} auf die aktuelle Patch-Version von {v22}.


[#matrix]
== Kompatibilitäts-Matrix

// Da für den Wechsel einer Distribution in der Regel xref:backup#[Backup und Restore] verwendet wird, haben wir die Tabellen nach Distributionen aufgeteilt.
// TK: Den Satz versteh ich nicht, insbesondere den Verweis auf Backup und Restore. Dass Du die Distros in unterschiedliche Tabellen steckst, ist doch naheliegend, da mich als Leser doch nur eine interessiert.
// Die Reihenfolge ist alphabetisch.
// TK: Den Satz kannst Du streichen.

[#debian]
=== Debian

Die Support-Zeiträume der Debian-Versionen entnehmen Sie bitte dem link:https://wiki.debian.org/LTS[Debian-Wiki^] oder der link:https://endoflife.date/debian[Übersicht bei endoflife.date^]. 

[#matrix_debian]
Bitte aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für Debian angezeigt zu bekommen.


[#redhat]
=== RedHat Enterprise Linux

RedHat stellt eine ausführliche link:https://access.redhat.com/support/policy/updates/errata[Übersicht der geplanten Support-Zeiträume^] bereit.
Bei endoflife.date finden Sie Informationen zu der Derivaten link:https://endoflife.date/almalinux[AlmaLinux^], link:https://endoflife.date/centos[CentOS^], link:https://endoflife.date/oracle-linux[Oracle Linux^] und link:https://endoflife.date/rocky-linux[Rocky Linux^].

[#matrix_redhat]
Bitte aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für RedHat Enterprise Linux angezeigt zu bekommen.


[#sles]
=== SUSE Linux Enterprise Server

Auf der Seite von SUSE finden Sie die link:https://www.suse.com/lifecycle/#product-suse-linux-enterprise-server[Lifecycle-Übersicht^].
Alternativ steht eine link:https://endoflife.date/sles[Übersicht bei endoflife.date^] zur Verfügung.

[#matrix_sles]
Bitte aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für SUSE Linux Enterprise Server angezeigt zu bekommen.

[#ubuntu]
=== Ubuntu

Beachten Sie, dass nicht jede STS-Version von Ubuntu durchgängig von {CMK} unterstützt wird.
Wir achten jedoch immer darauf, dass von jeder {CMK}-Version, die für eine STS-Version bereitgestellt wurde, ein Update bis zur nächsten LTS-Version möglich ist.

Ubuntu selbst pflegt eine nach noch im Support befindlichen und abgekündigten Versionen gepflegte link:https://wiki.ubuntu.com/Releases[Liste^].
Nach Erscheinungsdatum sortiert ist link:https://endoflife.date/ubuntu[die Liste bei endoflife.date^].

[#matrix_ubuntu]
Bitte aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für Ubuntu Linux angezeigt zu bekommen.

// include::include_matrix_ubuntu.asciidoc[]
// TK: In der Tabelle würde ich auch STS vermerken, so wie Du dass für LTS getan hast.
