// -*- coding: utf-8 -*-
// IGNORE p1 0p31 0p7 Kompatibilitäts 0p1 0p29 Xerus 0p13 0p11 0p16 zeilen 0p25 0p3 0p37 0p4 Indri LTS Patchlevel SP1 SP2 SP4 SP5 STS Xenial
include::global_attr.adoc[]
= Update-Matrix für Version 2.1.0
:revdate: 2023-10-20
:title: Update-Matrix für Version 2.1.0
:description: Dieser Artikel enthält Tabellen der von Version 2.0.0 und 2.1.0 unterstützten Distributionen anhand derer Sie ermitteln können, in welcher Reihenfolge Sie am besten Updates von {CMK} und Ihrem Linux-Server durchführen.


{related-start}
xref:update#[Updates und Upgrades]
xref:update_major#[Update auf Version 2.1.0]
xref:release_upgrade#[Linux-Upgrade auf dem Checkmk-Server]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
{related-end}


[#intro]
== Einleitung

Mit jeder Version von {CMK} fallen bislang unterstützte Linux-Distributionen weg und neue kommen hinzu.
Dies kann es erforderlich machen, vor einem {CMK} ein oder mehrere xref:release_upgrade#[Upgrades Ihrer Linux-Distribution] vorzunehmen.
Die hier vorhandenen Tabellen helfen bei der Ermittlung der geeigneten Reihenfolge.

Versionsnummern im Kopf der Tabellenspalte zeigen immer diejenigen an, _ab_ der eine Veränderung vorgenommen wurde, also Unterstützung einer Distribution hinzugekommen oder weggefallen ist.
Aktualisierungen der Tabellen erfolgen entsprechend nur, wenn Änderungen in der Distributionsunterstützung erfolgt ist.
Gegebenenfalls wird das Änderungsdatum nach erfolgter Kontrolle angepasst, ohne dass Änderungen an den Tabellen erfolgt sind.

Bitte studieren Sie die Tabellen auf dieser Seite aufmerksam, bevor Sie im link:https://checkmk.com/download/archive[Download-Archiv^] suchen oder Anfragen nach alten Paketen stellen. 

[#steps]
=== Ermittlung der Update-Schritte

Die Aufgabe ist es, in den Tabellen von links oben nach rechts unten zu gelangen.
Dabei sind Vorgaben für das xref:update#[Update von {CMK}] zu berücksichtigen:

* Es darf keine Major-Version ausgelassen werden
* Vor dem Update der Major-Version muss auf das höchste Patchlevel aktualisiert werden
* Beim Upgrade der Linux-Distribution muss auf der neuen Distributionsversion exakt dieselbe {CMK}-Version installiert wie auf der alten vorhanden war.

Auch Linux-Distributoren machen in der Regel eine Vorgabe:

* Upgrades dürfen keine Version auslassen

Ubuntu ist an dieser Stelle etwas speziell: LTS-Versionen sollten immer nur auf die nächste LTS (_Long Term Support_, fünf Jahre Updates) aktualisiert werden, STS-Versionen (_Short Term Support_, sieben Monate Updates) müssen in Halbjahresschritten aktualisiert werden.

Aus diesen Anforderungen ergibt sich, dass Sie sich nur zeilen- oder spaltenweise bewegen dürfen – jedoch niemals diagonal – und, dass keine beliebigen Sprünge zulässig sind.

////
Für ein Update von Debian 9 mit {CMK} {v21}p1 auf Debian 12 mit {CMK} {v22} ergibt sich so die folgende Update-Reihenfolge:

. Unter Debian 9 das Update von {CMK} {v21}p1 auf das neueste Patchlevel von {v21} durchführen
. Gemäß xref:release_upgrade#[_Linux-Upgrade auf dem Checkmk-Server_] Debian auf 10, 11 und schließlich 12 aktualisieren
. Unter Debian 12 das Update des neuesten {CMK} {v21} auf das neueste Patchlevel von {v22} durchführen
////

[#matrix]
== Kompatibilitäts-Matrix

[#debian]
=== Debian

Die Support-Zeiträume der Debian-Versionen entnehmen Sie dem link:https://wiki.debian.org/LTS[Debian-Wiki^] oder der link:https://endoflife.date/debian[Übersicht bei endoflife.date.^]

[#matrix_debian]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für Debian angezeigt zu bekommen.


[#redhat]
=== RedHat Enterprise Linux

RedHat stellt eine ausführliche link:https://access.redhat.com/support/policy/updates/errata[Übersicht der geplanten Support-Zeiträume^] bereit.
Bei endoflife.date finden Sie Informationen zu der Derivaten link:https://endoflife.date/almalinux[AlmaLinux^], link:https://endoflife.date/centos[CentOS^], link:https://endoflife.date/oracle-linux[Oracle Linux^] und link:https://endoflife.date/rocky-linux[Rocky Linux^].

[#matrix_redhat]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für RedHat Enterprise Linux angezeigt zu bekommen.


[#sles]
=== SUSE Linux Enterprise Server

Auf der Seite von SUSE finden Sie die link:https://www.suse.com/lifecycle/#product-suse-linux-enterprise-server[Lifecycle-Übersicht^].
Alternativ steht eine link:https://endoflife.date/sles[Übersicht bei endoflife.date^] zur Verfügung.

[#matrix_sles]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für SUSE Linux Enterprise Server angezeigt zu bekommen.


[#ubuntu]
=== Ubuntu

// Beachten Sie, dass nicht jede STS-Version von Ubuntu durchgängig von {CMK} unterstützt wird.
Beachten Sie, dass vor {v22} nicht jede STS-Version von Ubuntu durchgängig von {CMK} unterstützt wurde.
Wir achteten und achten jedoch immer darauf, dass von jeder {CMK}-Version, die für eine STS-Version bereitgestellt wurde, ein Update bis zur nächsten LTS-Version möglich ist.
Ab {v22} schafft die xref:ossupport[OS Support Policy] klare Regeln.

Ubuntu selbst pflegt eine nach noch im Support befindlichen und abgekündigten Versionen sortierte link:https://wiki.ubuntu.com/Releases[Liste^].
Nach Erscheinungsdatum sortiert ist link:https://endoflife.date/ubuntu[die Liste bei endoflife.date^].

[#matrix_ubuntu]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für Ubuntu angezeigt zu bekommen.