// -*- coding: utf-8 -*-
// IGNORE Kompatibilitäts p1 zeilen endoflife
include::global_attr.adoc[]
= Update-Matrix für Version {v22}
:revdate: draft
:title: Update-Matrix für Version {v22}
:description: Dieser Artikel zeigt die von {CMK} unterstützten Linux-Distributionsversionen, damit Sie die Reihenfolge ermitteln können, um Updates von {CMK} auf Ihrem Linux-Server durchzuführen.
// TK: Die description war zu lang. Ist jetzt kürzer, aber immer noch zu lang (länger als 160 Zeichen).

{related-start}
xref:update#[Updates und Upgrades]
xref:update_major#[Update auf Version 2.2.0]
xref:release_upgrade#[Linux-Upgrade auf dem {CMK}-Server]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
{related-end}


[#intro]
== Einleitung

Mit jeder Version von {CMK} fallen bislang unterstützte Linux-Versionen weg und neue kommen hinzu.
Dies kann es erforderlich machen, vor einem Update von {CMK} ein oder mehrere xref:release_upgrade#[Upgrades Ihrer Linux-Distribution] vorzunehmen.
Die Grafiken in diesem Artikel helfen Ihnen bei der Ermittlung der geeigneten Reihenfolge.
Studieren Sie diese aufmerksam, bevor Sie im link:https://checkmk.com/download/archive[Download-Archiv^] suchen oder Anfragen nach alten Paketen stellen.
// Sollten Sie auf eine ältere {CMK}-Version als {v22} aktualisieren wollen, wählen Sie im Versions-Auswahlmenü die Version aus, die _Ziel_ der Aktualisierung ist.
// TK: Was meinst Du denn damit? Bist du jetzt im Download-Archiv? Und was mach ich dann, wenn ich diese Version ausgewählt habe?
// TK: Wenn ich auf eine ältere {CMK}-Version als {v22} aktualisieren will, sollte ich doch besser diesen Artikel in den Docs für {v21} oder {v20} lesen, oder?
// TK: Wenn der Satz wirklich nötig ist, dann sollte er ans Ende der Einleitung, weil er den Lesefluss zum Thema Grafiken zerreisst.
// MFS: So?
Sollten Sie auf eine ältere {CMK}-Version als {v22} aktualisieren wollen, lesen Sie diesen Artikel bitte für die {CMK}-Version, die _Ziel_ der Aktualisierung ist.

// Die {CMK}-Versionsnummern am Beginn eines grünen Balkens oder einer leeren Fläche zeigen immer diejenigen an, _ab_ der eine Veränderung vorgenommen wurde, also eine Linux-Version neu unterstützt oder nicht mehr unterstützt wird.
// TK: Eher wie folgt, inklusive eines Links, weil die Erklärung zu den Grafiken sehr weit weg ist von den angezeigten Grafiken:
// TK: 
Die {CMK}-Versionsnummern am oberen Rand der Grafiken im Kapitel xref:matrix[Kompatibilitäts-Matrix] zeigen immer diejenigen an, _ab_ der eine Veränderung vorgenommen wurde, also eine Linux-Version neu unterstützt oder nicht mehr unterstützt wird.
Eine Pfeilspitze am Ende eines Balkens bedeutet, dass diese {CMK}-Version im Support ist, also weitere Patch-Versionen folgen werden.
Ein stumpfes Ende kennzeichnet dagegen eine Kombination aus {CMK}-Version und Distributionsversion, die Ihr Support-Ende erreicht hat.
Das kann in einer abgekündigten {CMK}-Version (alle Balken sind stumpf) oder vom Distributor nicht mehr unterstützten Distribution liegen (einzelne Balken gehen mit Pfeilspitze weiter).
// TK: Hm, die Balken/Pfeilspitzen gehören ja zu den Distributionen und eher nicht zu den {CMK}-Versionen ... aber egal.
// MFS: Besser?
Erstellt werden die Grafiken automatisch aus täglich aktualisierten Daten zu den verfügbaren Downloads, das Änderungsdatum dieses Artikels gibt folglich nicht die Aktualität der angezeigten Daten wieder.


[#steps]
== Ermittlung der Update-Schritte
// TK: Wie wäre es denn, dieses Kapitel hinter die Kompatibilitäts-Matrix zu stecken? Dann werden zuerst die Grafiken gezeigt und dann erklärt, was damit zu tun ist.
// TK: Und der von mir oben vorgeschlagene Link xref:matrix[Kompatibilitäts-Matrix] wäre auch überflüssig.
// MFS: Hmmm, die Erläuterung hätte ich gerne weiter vorne, ich habe schon extra das Debian-Beispiel genommen.

Die Aufgabe ist es nun, in der xref:matrix[Kompatibilitäts-Matrix] für Ihre Linux-Distribution tendenziell von links oben nach rechts unten zu gelangen.
Dabei sind die Vorgaben für das xref:update#[Update von {CMK}] zu berücksichtigen:

* Es darf keine Major-Version ausgelassen werden.
// TK: Nebenbei: Wäre schön, wenn wir in cmk_versions mal schreiben würden, was Major-, Minor- und Patch-Versionen sind...

* Vor dem Update der Major-Version muss auf die höchste verfügbare Patch-Version aktualisiert werden.
Die Mindestanforderungen sind im xref:update_major#update_patch[Artikel zum Update auf {v22}] beschrieben.

* Beim Upgrade der Linux-Distribution muss auf der neuen Distributionsversion exakt dieselbe {CMK}-Version installiert werden, die auf der alten vorhanden war.

Auch Linux-Distributoren machen in der Regel eine Vorgabe:

* Upgrades dürfen keine Version auslassen.

Ubuntu ist an dieser Stelle etwas speziell:
LTS-Versionen (_Long Term Support_, fünf Jahre Updates) sollten immer nur auf die nächste LTS-Version aktualisiert werden,
STS-Versionen (_Short Term Support_, neun Monate Updates) müssen in Halbjahresschritten aktualisiert werden.

Aus diesen Anforderungen ergibt sich, dass Sie sich in der Grafik für Ihre Linux-Distribution nur zeilen- oder spaltenweise bewegen dürfen – jedoch niemals diagonal – und, dass Sprünge nur dann zulässig sind, wenn sie nicht gegen die oben genannten Vorgaben verstoßen.
Für ein Update von Debian 9 mit {CMK} {v21}p1 auf Debian 12 mit {CMK} {v22} ergibt sich so die folgende Update-Reihenfolge:

. Unter Debian 9 führen Sie das Update von {CMK} {v21}p1 xref:update#[auf die aktuelle Patch-Version] von {v21} durch.

. Führen Sie das Upgrade von Debian 9 auf 10, 11 und schließlich auf 12 durch, so wie es im Artikel zum xref:release_upgrade#[Linux-Upgrade auf dem {CMK}-Server] beschrieben ist.

. Unter Debian 12 aktualisieren Sie die aktuelle Patch-Version von {CMK} {v21} auf die xref:update_major#[aktuelle Patch-Version von {v22}].


[#matrix]
== Kompatibilitäts-Matrix

[#debian]
=== Debian

Die Support-Zeiträume der Debian-Versionen entnehmen Sie dem link:https://wiki.debian.org/LTS[Debian-Wiki^] oder der link:https://endoflife.date/debian[Übersicht bei endoflife.date.^]

[#matrix_debian]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für Debian angezeigt zu bekommen.


[#redhat]
=== RedHat Enterprise Linux

RedHat stellt eine ausführliche link:https://access.redhat.com/support/policy/updates/errata[Übersicht der geplanten Support-Zeiträume^] bereit.
Bei endoflife.date finden Sie Informationen zu der Derivaten link:https://endoflife.date/almalinux[AlmaLinux^], link:https://endoflife.date/centos[CentOS^], link:https://endoflife.date/oracle-linux[Oracle Linux^] und link:https://endoflife.date/rocky-linux[Rocky Linux^].

[#matrix_redhat]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für RedHat Enterprise Linux angezeigt zu bekommen.


[#sles]
=== SUSE Linux Enterprise Server

Auf der Seite von SUSE finden Sie die link:https://www.suse.com/lifecycle/#product-suse-linux-enterprise-server[Lifecycle-Übersicht^].
Alternativ steht eine link:https://endoflife.date/sles[Übersicht bei endoflife.date^] zur Verfügung.

[#matrix_sles]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für SUSE Linux Enterprise Server angezeigt zu bekommen.


[#ubuntu]
=== Ubuntu

// Beachten Sie, dass nicht jede STS-Version von Ubuntu durchgängig von {CMK} unterstützt wird.
// TK: Der vorherige Satz passt nicht mehr so recht zur neuen OS Support Policy: Entweder weg oder vielleicht so:
// TK: Beachten Sie, dass STS-Versionen von Ubuntu _zukünftig_ von {CMK} nicht mehr unterstützt werden.
Beachten Sie, dass vor {v22} nicht jede STS-Version von Ubuntu durchgängig von {CMK} unterstützt wurde.
Wir achteten und achten jedoch immer darauf, dass von jeder {CMK}-Version, die für eine STS-Version bereitgestellt wurde, ein Update bis zur nächsten LTS-Version möglich ist.
Ab {v22} schafft die xref:ossupport[OS Support Policy] klare Regeln.

Ubuntu selbst pflegt eine nach noch im Support befindlichen und abgekündigten Versionen sortierte link:https://wiki.ubuntu.com/Releases[Liste^].
Nach Erscheinungsdatum sortiert ist link:https://endoflife.date/ubuntu[die Liste bei endoflife.date^].

[#matrix_ubuntu]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für Ubuntu angezeigt zu bekommen.


[#ossupport]
== Richtlinie zur Betriebssystemunterstützung in {CMK} _(OS Support Policy)_
// TK: Richtlinie zur OS-Unterstützung in {CMK}? Ich weiß, liest sich holprig...

Um einen Ausblick auf die Unterstützung durch künftige {CMK}-Versionen zu ermöglichen und Updates von Distributionen und {CMK} besser planen zu können, hat die {comfull} sich einige Regeln gegeben:

* _Enterprise-Distributionen_ (SLES, RHEL) werden bis 10 Jahre nach deren Erscheinungsdatum oder bis zum offiziellen Support-Ende durch den Distributor unterstützt.
* _Community-Distributionen_ (Debian, Ubuntu) werden bis 5 Jahre nach deren Erscheinungsdatum oder bis zum offiziellen Support-Ende durch den Distributor unterstützt, sofern es sich um LTS-Releases handelt.

In beiden Fällen ist der frühere Zeitpunkt entscheidend.
// Für die Unterstützung ist dabei relevant, ob das so errechnete Support-Ende innerhalb eines Drei-Monats-Zeitraumes nach Erscheinungsdatum einer neuen {CMK}-Version liegt.
// TK: Obacht: Nach Google Doc gilt der Drei-Monats-Zeitraum nur für Community-Distributionen. Für die Enterprise-Distributionen gilt "the end of the expected active maintenance of a new Checkmk release"
// TK: Ich würde die Details hier weglassen. Die Regel soll man sich merken können. Welches Datum jetzt genau genommen wird, versteht doch eh kein Mensch ... zumindest ich nicht.
Wir streben dabei an, jede beim Erscheinen von {CMK} unterstützte Distributionsversion über den gesamten Produkt-Lifecycle von {CMK} zu unterstützen, sofern dem nicht technische Gründe entgegenstehen oder die Zahl der gleichzeitig unterstützten Versionen einer Distribution vier übersteigt.
Ist dies der Fall, behalten wir uns vor, die mit dem kürzesten Rest-Support ab {CMK}-Veröffentlichungsdatum oder Support-Ende durch den Distributor nicht mehr zu unterstützen.
Bekanntgegeben wird dies beim Erscheinen einer neuer {CMK}-Version.
// TK: ... jede beim Erscheinen einer {CMK}-Version (Major-Version?) unterstützte Distributionsversion über den gesamten Produkt-Lifecycle dieser {CMK}-Version zu unterstützen ...

Ubuntu STS-Versionen werden künftig gar nicht mehr unterstützt.
Da bei Veröffentlichung dieser _OS Support Policy_ bereits {CMK} {v21} für Ubuntu 22.10 veröffentlicht war, hat die {comfull} beschlossen, zur Erleichterung von Updates die Unterstützung für Ubuntus STS-Versionen langsam auslaufen zu lassen.
Dies bedeutet, dass Ubuntu 23.10 die letzte von {CMK} unterstützte STS-Version sein wird.
Betroffene Benutzer können anschließend mit dem Update auf 24.04 nahtlos auf eine LTS-Version wechseln.
