// -*- coding: utf-8 -*-
// IGNORE Kompatibilitäts p1 zeilen endoflife AlmaLinux LTS Lifecycle STS abgekündigten AlmaLinux Lifecycle abgekündigten endoflife Checkmk RedHat Supportende checkmk localdev
include::global_attr.adoc[]
= Update-Matrix für Version {v20}
:revdate: 2023-11-02
:title: Update-Matrix für Version {v20}
:description: Dieser Artikel zeigt die von {CMK} unterstützten Linux-Distributionsversionen. So können Sie die Reihenfolge ermitteln, um {CMK} auf Ihrem Linux-Server zu aktualisieren.

{related-start}
xref:update#[Updates und Upgrades]
xref:update_20#[Update auf Version {v20}]
xref:release_upgrade#[Linux-Upgrade auf dem {CMK}-Server]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
{related-end}


[#intro]
== Einleitung

Mit jeder Version von {CMK} fallen bislang unterstützte Linux-Versionen weg und neue kommen hinzu.
Dies kann es erforderlich machen, vor einem Update von {CMK} ein oder mehrere xref:release_upgrade#[Upgrades Ihrer Linux-Distribution] vorzunehmen.
Die Grafiken in diesem Artikel helfen Ihnen bei der Ermittlung der geeigneten Reihenfolge.
Studieren Sie diese aufmerksam, bevor Sie im link:https://checkmk.com/download/archive[Download-Archiv^] suchen oder Anfragen nach alten Paketen stellen.
// MFS: Hinweis auch auf neuere.
Sollten Sie auf eine ältere oder neuere {CMK}-Version als {v20} aktualisieren wollen, lesen Sie diesen Artikel bitte für die {CMK}-Version, die _Ziel_ der Aktualisierung ist.


[#steps]
== Ermittlung der Update-Schritte

Die Aufgabe ist es nun, in der xref:matrix[Kompatibilitäts-Matrix] für Ihre Linux-Distribution tendenziell von links oben nach rechts unten zu gelangen.
Dabei sind die Vorgaben für das xref:update#[Update von {CMK}] zu berücksichtigen:

* Es darf keine Major-Version ausgelassen werden.

* Vor dem Update der Major-Version muss auf die höchste verfügbare Patch-Version aktualisiert werden.
Die Mindestanforderungen sind im xref:update_20#[Artikel zum Update auf {v20}] beschrieben.

* Beim Upgrade der Linux-Distribution muss auf der neuen Distributionsversion exakt dieselbe {CMK}-Version installiert werden, die auf der alten vorhanden war.

Auch Linux-Distributoren machen in der Regel eine Vorgabe:

* Upgrades dürfen keine Version auslassen.

Ubuntu ist an dieser Stelle etwas speziell:
LTS-Versionen (_Long Term Support_, fünf Jahre Updates) sollten immer nur auf die nächste LTS-Version aktualisiert werden,
STS-Versionen (_Short Term Support_, neun Monate Updates) müssen in Halbjahresschritten aktualisiert werden.

Aus diesen Anforderungen ergibt sich, dass Sie sich in der Grafik für Ihre Linux-Distribution nur zeilen- oder spaltenweise bewegen dürfen – jedoch niemals diagonal – und, dass Sprünge nur dann zulässig sind, wenn sie nicht gegen die oben genannten Vorgaben verstoßen.
Für ein Update von Debian 8 mit {CMK} {v16}p1 auf Debian 11 mit {CMK} {v20} ergibt sich so die folgende Update-Reihenfolge:

. Unter Debian 8 führen Sie das Update von {CMK} {v16}p1 xref:update#[auf die aktuelle Patch-Version] von {v16} durch.

. Führen Sie nun das Upgrade von Debian 8 auf 9 und schließlich auf 10 durch, so wie es im Artikel zum xref:release_upgrade#[Linux-Upgrade auf dem {CMK}-Server] beschrieben ist.

. Unter Debian 10 aktualisieren Sie die aktuelle Patch-Version von {CMK} {v16} auf die xref:update_20#[aktuelle Patch-Version von {v20}].

. Führen Sie abschließend das xref:release_upgrade#[Upgrade von Debian 10 auf 11] durch.

[#matrix]
== Kompatibilitäts-Matrix

Die {CMK}-Versionsnummern am oberen Rand der Grafiken in den folgenden Abschnitten zeigen immer diejenigen an, _ab_ der eine Veränderung vorgenommen wurde, also eine Linux-Version neu unterstützt oder nicht mehr unterstützt wird.
Eine Pfeilspitze am Ende eines Balkens bedeutet, dass diese {CMK}-Version im Support ist, also weitere Patch-Versionen folgen werden.
Ein stumpfes Ende kennzeichnet dagegen eine Kombination aus {CMK}-Version und Distributionsversion, die Ihr Support-Ende erreicht hat.
Das kann an einer abgekündigten {CMK}-Version (alle Balken sind stumpf) oder vom Distributor nicht mehr unterstützten Distribution liegen (einzelne Balken gehen mit Pfeilspitze weiter).
// Erstellt werden die Grafiken automatisch aus täglich aktualisierten Daten zu den verfügbaren Downloads, das Änderungsdatum dieses Artikels gibt folglich nicht die Aktualität der angezeigten Daten wieder.
Da sowohl Checkmk {v16} als auch {v20} das Supportende erreicht haben, werden die Tabellen hier keine Aktualisierungen mehr erhalten.

[#debian]
=== Debian

Die Support-Zeiträume der Debian-Versionen entnehmen Sie dem link:https://wiki.debian.org/LTS[Debian-Wiki^] oder der link:https://endoflife.date/debian[Übersicht bei endoflife.date.^]

[#matrix_debian]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für Debian angezeigt zu bekommen.


[#redhat]
=== RedHat Enterprise Linux

RedHat stellt eine ausführliche link:https://access.redhat.com/support/policy/updates/errata[Übersicht der geplanten Support-Zeiträume^] bereit.
Bei endoflife.date finden Sie Informationen zu der Derivaten link:https://endoflife.date/almalinux[AlmaLinux^], link:https://endoflife.date/centos[CentOS^], link:https://endoflife.date/oracle-linux[Oracle Linux^] und link:https://endoflife.date/rocky-linux[Rocky Linux^].

[#matrix_redhat]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für RedHat Enterprise Linux angezeigt zu bekommen.


[#sles]
=== SUSE Linux Enterprise Server

Auf der Seite von SUSE finden Sie die link:https://www.suse.com/lifecycle/#product-suse-linux-enterprise-server[Lifecycle-Übersicht^].
Alternativ steht eine link:https://endoflife.date/sles[Übersicht bei endoflife.date^] zur Verfügung.

[#matrix_sles]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für SUSE Linux Enterprise Server angezeigt zu bekommen.


[#ubuntu]
=== Ubuntu

Ubuntu selbst pflegt eine nach noch im Support befindlichen und abgekündigten Versionen sortierte link:https://wiki.ubuntu.com/Releases[Liste^].
Nach Erscheinungsdatum sortiert ist link:https://endoflife.date/ubuntu[die Liste bei endoflife.date^].

[#matrix_ubuntu]
Aktivieren Sie Javascript, um an dieser Stelle die Kompatibilitätsmatrix für Ubuntu angezeigt zu bekommen.
