= Leitfaden zum effizienten Schreiben der Dokumentation

== Mit Visual Studio Code (vscode)

=== Grundlegendes Setup

Um vscode optimal für das Schreiben in Asciidoc vorzubereiten, lohnt es sich, als erstes die entsprechende Erweiterung zu installieren: link:https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[asciidoctor.asciidoctor-vscode]
Diese Erweiterung liefert die Basis, direkt in den Dateien zu schreiben und in Fast-Echtzeit das Ergebnis in eine Vorschau geliefert zu bekommen.

Optional, aber emnpfohlen sind auch die Erweiterungen für git, sofern man git nicht eh auf der Kommandozeile nutzt sind link:https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens[GitLens] und link:https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github[GitHub Pull Requests and Issues]

Daneben gibt es natürlich noch viele weitere kleine Helfer, die einem das Leben erleichtern können. erwähnt sich daher nur die beiden wichtigsten für den Einstieg.

=== Empfohlene Einstellung für die Asciidoctor-Erweiterung

Um alle Vorteile zu nutzen, sind die folgenden Einstellungen empfohlen. Das folgende ist ein Auszug aus den Einstellungen, wie sie in der Datei abgelegt werden:

----
{
    "asciidoc.preview.style": "checkmk.css",
    "asciidoc.preview.useEditorStyle": false,
    "asciidoc.previewFrontMatter": "show",
    "asciidoc.preview.attributes": {
        "global": "../attributes/global_attr.adoc",
        "chapter": "../../attributes/chapter_attr.adoc",
    },
}
----

Die beiden direkt abgelegten Attribute können zukünftig genutzt werden und sind derzeit noch nicht direkt relevant.
