= Hilfe zur Entwicklungsumgebung

:shell: source,shell,subs="quotes,macros,attributes"
:c-user: user@host:~$

== Schreiben mit Visual Studio Code (vscode)

=== Grundlegendes Setup

Um vscode optimal für das Schreiben in Asciidoc vorzubereiten, lohnt es sich, als erstes die entsprechende Erweiterung zu installieren: link:https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[asciidoctor.asciidoctor-vscode]
Diese Erweiterung liefert die Basis, direkt in den Dateien zu schreiben und in Fast-Echtzeit das Ergebnis in eine Vorschau geliefert zu bekommen.

Optional, aber emnpfohlen sind auch die Erweiterungen für git, sofern man git nicht eh auf der Kommandozeile nutzt sind link:https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens[GitLens] und link:https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github[GitHub Pull Requests and Issues]

Daneben gibt es natürlich noch viele weitere kleine Helfer, die einem das Leben erleichtern können. erwähnt sich daher nur die beiden wichtigsten für den Einstieg.

=== Empfohlene Einstellung für die Asciidoctor-Erweiterung

Um alle Vorteile zu nutzen, sind die folgenden Einstellungen empfohlen. Das folgende ist ein Auszug aus den Einstellungen, wie sie in der Datei abgelegt werden:

----
{
    "asciidoc.preview.style": "checkmk.css",
    "asciidoc.preview.useEditorStyle": false,
    "asciidoc.previewFrontMatter": "show",
    "asciidoc.preview.attributes": {
        "global": "../attributes/global_attr.adoc",
        "chapter": "../../attributes/chapter_attr.adoc",
    },
}
----

Die beiden direkt abgelegten Attribute können zukünftig genutzt werden und sind derzeit noch nicht direkt relevant.

== Schreiben mit vim

tbd

== HTML-Dateien lokal erstellen

Um aus den Asciidoc-Dateien eine HTML-Datei zu machen, braucht es - neben `make` selbst - zwei Programme:

[horizontal]
*make*:: Hier gelten keine besonderen Versionsvoraussetzungen
*Asciidoctor*:: Mindestens in der Version 2.0.0
*Ruby*:: Ruby sollte mindestens in der Version 2.3 installiert sein, wenn die Templates der offiziellen Seite benutzt werden
*slimrb*:: Diese Erweiterung wird benötigt, um die Slim-Templates der offiziellen Seite nutzen zu können

Um ein HTML nun lokal zu erstellen, wird einfach `make html` aufgerufen und der Artikelname angegeben, welcher konvertiert werden soll. Hier bei wird - je nach Entwicklungsumgebung - geschaut, ob das interne Repository für die Templates und dem Styling verfügbar ist und ansonsten eine Minimal-Version ausgegeben. Bei der Angabe des Artikels muss kein Pfad oder Dateiendung mitgegeben werden:

[{shell}]
----
{c-user} make html ARTICLE=my_article
----

Danach werden die generierten Dateien unterhalb des Verzeichnisses `localbuild` verfügbar sein:

[{shell}]
----
{c-user} ls -R localbuild/
localbuild/:
de  en

localbuild/de:
my_article.html

localbuild/en:
my_article.html
----