= Aufbau und Umgang mit diesem Repository

:cmk: Checkmk
:v16: 1.6.0
:v20: 2.0.0
:v21: 2.1.0
:imagesdir: ../images
:CEE: pass:q,m[image:CEE.svg[CEE,title=Checkmk Enterprise Editions,width=20] *Checkmk Enterprise Editions*]
:CRE: pass:q,m[image:CRE.svg[CRE,title=Checkmk Raw Edition,width=20] *Checkmk Raw Edition*]

Bei der Erstellung von Artikel und dazugehörigen Materialien gibt es verschiedene Mechanismen und Verzeichnisse. Die wichtigsten sind hier erklärt.

== Grundstruktur

Auf der obersten Ebene gibt es im wesentlichen die folgenden Verzeichnisse:

[horizontal]
*de*:: Der Ort für alle Artikel in deutscher Sprache. Derzeit werden alle Artikel zuerst in deutsch verfasst und danach auf englisch übersetzt.
*en*:: Der Ort für alle Artikel in englischer Sprache, sobald die deutsche Fassung fertig ist
*images*:: Screenshots und Icons werden hier in einer flachen Hierarchie abgelegt.
*attributes*:: Um das Schreiben zu erleichtern und um bestimmte Begrifflichkeiten oder Formatierungen zu standardisieren, werden allgemeine Attribute hier definiert und angepasst.
*contrib*:: Beinhaltet die Dokumentation zur Nutzung dieses Repositories.

Zusätzlich gibt es ein paar mehr oder weniger hilfreiche Dateien, welche die Nutzung vereinfachen sollen:

[horizontal]
*checkmk.css*:: Das Style-Sheet kann benutzt werden, um beim Schreiben eine live-Vorschau zu generieren, die der Dokumentationsseite möglichst nahe kommt.
*Makefile*:: Wenn einzelne Dokumente lokal zu HTML konvertiert werden sollen, kann das mit make passieren. Die Hilfe ist über `make help` erreichbar.

== Branches

Die Dokumentation von {CMK} erfolgt versionsbasiert, aber nicht editionsbasiert. Das bedeutet im wesentlichen, dass es für {CMK} {v16} keine unterschiedlichen Versionen der Dokumentation für die {CRE} und {CEE} gibt. Für jede stabile, veröffentlichte Version gibt es einen eigenen Branch. Dieser ist zu nutzen, wenn der Artikel oder die Korrektur für eine bereits erschienene Version von {CMK} gilt.

Umgekehrt wird im Master immer für die Version von {CMK} geschrieben, die sich gerade in Entwicklung befindet und noch nicht offiziell erschienen ist.

[IMPORTANT]
Derzeit gilt eine Ausnahme für den Release der {v20}. Hier wird bereits in einem eigenen Branch geschrieben, so dass der _master_ bereits für Version {v21} reserviert ist.


== Commit-Nachricht

Unabhängig, ob es sich um reguläre Arbeiten der _tribe29_ oder um _Pull Requests_ (PRs) handelt, sollte eine Commit-Nachricht immer hilfreich sein, um zu verstehen, was in dem Commit gemacht wurde. Dazu kann es manchmal auch notwendig sein, eine ausführlichere Beschreibung zu hinterlegen, um die Änderung inhaltlich zu begründen. Vor allem bei einem PR erleichtert es den Mitarbeitern von _tribe29_ erheblich, wenn Sie den Grund für eine Änderung schnell verstehen.

Zusätzlich sollten auch die Hinweise zum Schreiben aus dem link:guide.adoc[Leitfaden] beachtet werden, da dort die verfügbaren Stichwörter für die Commit-Nachrichten beschrieben sind. Hier noch einmal die Kurzform:

[horizontal]
*translate*:: Markiert die betroffenen Artikel als inhaltlich synchron in allen Sprachen. Die Inhalte sind nicht zwangsläufig übersetzt, aber mindestens auskommentiert in einer Sprache vorhanden.
*only-de*:: Markiert den Commit zu den den betroffenen deutschen Versionen eines Artikels als redaktionelle Ánderung, die nicht übersetzt werden muss.
*only-en*:: Das Pendant zu *only-de*
