= Leitfaden zum Schreiben

:cmk: Checkmk

== Grundsätzliches

=== Neue Artikel

==== Schreiben

Artikel, welche komplett neu geschrieben werden, sollten immer auf dem Stand der zukünftigen Version von {CMK} geschrieben werden. Falls die Inhalte auch für eine bereits veröffentlichte Version relevant ist, kann er danach entsprechend in den jeweiligen Branch portiert werden. *Wichtig*: Eventuell muss dieser Artikel dann angepasst und umgeschrieben werden, damit er für die jeweilige Version korrekt ist! Grundsätzlich besteht keine Pflicht einen neuen Artikel in frühere Versionen der Dokumentation zu portieren - gern gesehen ist es jedoch immer.

Sobald eine erste Version eines Artikels fertig ist und mindestens die Grundstruktur steht, kann ein Artikel grundsätzlich auch bereits in den jeweiligen Branch veröffentlicht werden. Dabei gibt es zwei Phasen, die ein Artikel beim initialen Schreiben haben kann:

[horizontal]
*draft*:: Der Artikel ist begonnen und hat bereits erste (hilfreiche) Inhalte. Er ist aber noch nicht fertig oder korrigiert. Es können Inhalte fehlen oder unvollständig sein. Der Artikel wird entsprechend mit `draft` im `revdate` markiert.
*final*:: Der Artikel ist fertig, wurde gegengelesen und auf Vollständigkeit/Korrektheit und Tippfehler geprüft. Der Artikel kann mit einem Datum in `revdate` versehen werden. Es gilt das Datum der Fertigstellung, nicht das, wann der Commit ins git kam.

==== Übersetzen

Um den Übersetzungsstatus zu verfolgen, benutzen wir git Historie. Dazu werden bestimmte Schlagwörter in den Commits benutzt, um die Verfolgung zu vereinfachen:

[horizontal]
*translate*:: Sobald ein Artikel fertig ist, wird eine Kopie in die anderen Sprachen geschoben. Der Inhalt wird dann auskommentiert und die Änderung/neuen Dateien mit diesem Stichwort gespeichert:

[{shell}]
----
{c-user} git commit en/my_new_article.asciidoc -m "translate: wrote new helpful article"
----

Das Stichwort markiert den Zeitpunkt, an dem ein Artikel in allen Sprachen inhaltlich vollständig synchron ist. *Wichtig*: Die Inhalte sind zwar synchron, aber nicht zwingend bereits übersetzt!

=== Artikel überarbeiten

==== Schreiben

Man kennt es: Man hat einen Artikel zu einer Komponente fertiggestellt und schon nach 2 Tagen ist er entweder nicht mehr vollständig oder gar falsch. Nach dem Schreiben ist also vor dem Schreiben. Wenn man einen bestehenden Artikel überarbeitet, ist das Schreiben im Idealfall schnell getan. Hier gilt es nur die allgemeinen Hinweise zu beachten.

==== Übersetzen

Damit die Änderungen auch korrekt erfasst werden und gegebenenfalls inhaltliche Unterschiede auffallen, die übersetzt werden müssen, gibt es andere Dinge zu beachten, als wenn man auf einer grünen Wiese anfängt und den gesamten Artikel in einem übersetzen muss. Es kann daher mindestens folgende Situationen geben:

* Der Artikel ist zwar schon geschrieben und wurde zur Übersetzung gegeben. Die Übersetzung ist allerdings noch nicht fertig.
* Der Artikel ist geschrieben und wurde auch schon übersetzt.

Als wenn das noch nicht genug ist, wird er verschiedene Arten von Anpassungen geben:

* Es handelt sich nur um einen Tippfehler
* Es handelt sich um inhaltliche Änderungen kleinerer Art
* Es gibt größere Erweiterungen/Änderungen inhaltlicher Art

Um diese Situationen und Fälle abzudecken, muss man grundsätzliche nichts weiter tun, sobald es inhaltliche Änderungen gibt. Diese Commits werden automatisch erfasst, wenn geprüft wird, welche noch nicht übersetzt wurden. In bestimmten Fällen ist aber gar keine Übersetzung nötig, weil es nur redaktionelle Änderungen sind (Tippfehler, Formulierung geändert). Für diese Änderungen gibt es zum einen das Stichwort *only-de* oder *only-en*, die eine Änderung von der Prüfung ausschließen:

[{shell}]
----
{c-user} git commit de/my_article -m "Tippfehler behoben"
----

Mit diesen Stichwörtern haben wir also den klaren Vorteil, dass wir zum einen bei Änderungen erst einmal nichts falsch machen können und zum anderen die Möglichkeit haben, kleine Änderungen zu machen, ohne zuviele False-Positive-Meldungen zu erzeugen.

[IMPORTANT]
Der aufmerksame Leser wird gemerkt haben, dass nicht alle Fälle, die oben genannt wurden auch mit der Beschreibung abgedeckt sind. Um den Aufwand für alle Beteiligten so niedrig wie möglich zu halten, kann man kleinere inhaltliche Änderungen auch gerne direkt übersetzen. Auf diese Weise gehen die Artikel in den unterschiedlichen Sprachen nicht zu weit auseinander und zum anderen erspart es den Mitarbeitern von _tribe29_ viel Zeit und Arbeit. Wichtig ist es dann, die Änderungen von *beiden* Sprachversionen eines Artikels in denselben Commit zu übergeben:

[{shell}]
----
{c-user} git commit de/my_article en/my_article -m "added example for ..."
----


== Verwendung von Asciidoctor

In der Dokumentation von {CMK} werden derzeit nicht alle Features von Asciidoctor verwendet. Um ein homogenes Bild zu erleichtern/ermöglichen, gibt es hier eine (nicht erschöpfende) Liste an Funktionalitäten und wie sie verwendet werden sollten:

=== Kopfzeilen in jedem Dokument

Jeder Artikel verwendet ein Grundset an Metadaten und Kopfzeilen, die bei der Konvertierung zu HTML benötigt werden. Hier eine Liste an Headern und ob diese verpflichtend oder optional sind:

[cols=3]
|===
|Attribut|Beschreibung|verpflichtend?

|include::global_attr.adoc[]|Importiert vordefinierte Attribute, die im Text verwendet werden können und setzt grundlegende Attribute, wie den Pfad zu den Bildern und Icons|ja
|= Titel|Der Titel, wie er am Anfang des Artikels angezeigt werden soll|ja
|:revdate:|Beschreibt die letzte inhaltliche Bearbeitung eines Artikels. Wenn der Artikel noch nicht fertig ist, wird das mit `draft` markiert|ja
|:title:|Ein beschreibender Titel des Artikels in den Metadatan des HTML-Dokuments|ja
|:description:|Eine Kurzbeschreibung, worum es in dem Artikel geht|ja
|\{related-start} & \{related-end}|Links zu anderen Artikeln, die hilfreich für das Verständnis sind, oder den Kontext erweitern|nein
|===

So eine Kopfzeile eines Dokuments könnte also so aussehen:

----
\include::global_attr.adoc[]
= Mein Artikel zu Feature X
:title: Alles über Feature X
:description: Lernen Sie, wie sie Feature X einrichten und effizient in {CMK} nutzen können, um Ihre Monitoring-Umgebung optimal im Blick zu haben.

{related-start}
link:dashboards.html[Dashboards]
link:basics_downtimes.html[Wartungszeiten]
{related-end}
----

=== Überschriften

Überschriften sollte maximal auf drei Ebenen zusätzlich zu der ersten benutzt werden. Daraus ergibt sich, folgendes Bild:

----
= Dokumententitel (H0)

== H1-Überschrift

=== H2-Überschrift

==== H3-Überschrift
----

=== Textformatierungen

Grundsätzlich gilt, dass Formatierungen sparsam eingesetzt werden sollten. Ein Auszeichung in *fett* oder _kursiv_ sollte daher einen klaren Zweck verfolgen, der nicht regelmäßig vorkommt. Grundsätzlich gibt es für verschiedene Zwecke bereits unterschiedliche Definitionen, die benutzt werden sollten:

tbd
// Erlauben wollen wir ja * & _ & `. Dazu kommen dann noch kleinere Sachen, wie z.B. das Highlighting von Pfaden in der GUI.

=== Listen

Listen können entweder ungeordnet oder geordnet sein und sollten nicht mehr als zwei Ebenen haben:

----
* Punkt eins
** Unterpunkt zu eins
* Punkt zwei

. Mach erst A
.. Bedenke A2, wenn Du A machst
. Danach kommt B
----

Für kleine Tabellen, die nur zwei Spalten haben, kann es sich anbieten, stattdessen eine "Description list" zu schreiben:

----
Stichwort:: Hier kommt eine Beschreibung zu diesem Stichwort
----

// TODO: Entscheiden, ob wir horizontale und basic erlauben oder nur eins von beidem

=== Tabellen

Tabellen können unter Asciidoc unterschiedlich ausgezeichnet werden. Um ein gemeinsames Bild zu haben, werden Tabellen basierend auf folgender Syntax aufgebaut:

----
[cols=3] <1>
|===
|Spalte 1 |Spalte 2| Spalte3 <2>

|Zeile 1.1| Zeile1.2 | Zeile 1.3 <3>
|Noch eine Zeile||
|===
----
<1> Hier wird die Anzahl der Spalten angegeben. Syntaktisch nicht notwendig, aber es vereinfacht das Lesen.
<2> Titel der Spalten in der Tabelle
<3> Jede Zeile bekommt eine eigene Zeile und jede Spalte beginnt mit einem | (Pipe)

Als Alternative kann auch die Spaltenbreite in Prozent angegeben werden. Die ~ (Tilde) dient hier als Marker, dass man für diese Spalte keine feste Breite angeben möchte:

----
[cols="10,~,~,20"] <1>
----
<1> Diese Tabelle würde demnach vier Spalten haben, bei denen die erste eine Breite von 10% haben und die letzte 20% haben würde. Die Breite der beiden mittleren Spalten wird demnach automatisch berechnet.

=== Kommandozeilenauszüge

Kommandozeilen sind in Checkmk noch immer sehr wichtig und haben daher einen besonderen Stellenwert. Gleichzeitig sind sie auch die größte Hürde, wenn es um ein einheitliches und funktionierendes Syntaxbild geht. Um die meisten Fälle abzudecken, gibt es ein vordefiniertes Attribut, welches Sie nutzen können (und auch sollten). Es wird genutzt, um eine Kommandozeilenausgabe einzuleiten:

----
 [{shell}] <1>
 ----
 {c-user} cat /etc/hosts <2>
 127.0.0.1      localhost localhost.local
 ----
----
<1> Mit diesem Attribut werden die wichtigsten Optionen für die Kommandozeile gesetzt und gleichzeitig auch Formatierungen, Attribute und Makros erlaubt. Sollen nur Attribute erlaubt sein, so kann man auch `\{shell-raw}` nutzen.
<2> Hier ist ein Beispiel für eine Abkürzung, um eine Shell zu simulieren. Weitere finden Sie unten.

In Einzelfällen kann ein Kommandozeilenauszug natürlich auch manuell mit Optionen versehen werden. Das sollte jedoch der Ausnahmefall bleiben. Hier noch einmal alle Attribute, die derzeit definitiert sind und was deren Wert ist:

[horizontal]
*\{shell}*:: `{shell}`
*\{shell-raw}*:: `{shell-raw}`
*\{c-user}*:: `{c-user}`
*\{c-root}*:: `{c-root}`
*\{c-omd}*:: `{c-omd}`
*\{c-local}*:: `{c-local}`
*\{c-remote1}*:: `{c-remote1}`
*\{c-remote2}*:: `{c-remote2}`

=== Dateiauszüge

Dateiauszüge sind in Asciidoc ähnlich, wie Kommandozeilenauszüge und daher nicht sehr viel anders. Derzeit unterstützen wir lediglich eine kleine Anzahl, deren Syntax dann auch hervorgehoben dargestellt wird. Es empfiehlt sich daher das Standard-Attribute zu nutzen:

----
 [{file}] <1>
 ----
 Hier steht ein Textauszug aus einer Datei
 ----
----
<1> Statt einer shell wird hier schlicht angegeben, dass es sich bei dem Inhalt um eine Datei handelt.

=== Screenshots

tbd
// Hier gibt es noch viel zu erzählen. U.a. die Handhabung von Bildern mit Rahmen und Bildern, die rechts vom Text umrandet werden sollen.
// Weiter die Prinzipien, wie Schriftgröße im Bild, Bildgröße, etc. Das wird noch etwas Arbeit...
