= Grundprinzipien beim Schreiben der Dokumentation

:cmk-basics: https://chekcmk.com/de/monitoring
:cmk-blog: https://blog.checkmk.com/de
:CMK: Checkmk
:CEE: pass:q,m[image:CEE.svg[CEE,title=Checkmk Enterprise Editions,width=20] *Checkmk Enterprise Editions*]
:CRE: pass:q,m[image:CRE.svg[CRE,title=Checkmk Raw Edition,width=20] *Checkmk Raw Edition*]

Wenn man ein Handbuch oder eine Dokumentation zu einer Software liest, dann verfolgt man in der Regel einen bestimmten Zweck dabei. In den seltensten Fällen wird man einen Artikel aus dem Handbuch zu {cmk} aus purem Zufall öffnen. Aus diesem Grund gibt es auch bestimmte Grundprinzipien, nach denen der Inhalt für die Dokumentation erstellt wird.

Auch und vor allem beinhaltet das, was das Handbuch *nicht* leisten möchte, wie z.b. _Best Practices_ oder _How To's_ an die Hand zu geben, was bereits durch den Bereich link:{cmk-blog}[Blog]oder die allgemeinen Artikel zum link:{cmk-basics}[Monitoring] abgedeckt wird.

== Von welcher Art Leser und in welchen Situationen soll das Handbuch gelesen werden?

* Ich suche nach einem geeignetem Monitoringtool. Dabei ist mir wichtig, dass dieses umfangreich ORACLE überwachen kann. Ist {CMK} dafür geeignet?
* Ich soll in meiner Firma {CMK} übernehmen und will mich gründlich in das Thema einarbeiten. Ich habe vor allem auch die Zeit dafür.
* Ich verwende {CMK}, habe eine bestimmte Anforderung und weiß nicht, wie ich diese umsetzen soll.
* Ich verwende {CMK} und möchte tiefer in das Thema "Verarbeitung von Events" einsteigen, bzw. mich das Thema in Ruhe einlesen
* Ich verwende seit längerem die {CRE} und möchte beim Lesen erkennen, ob und wann sich eine {CEE} lohnen würde, oder wann dort Dinge anders funktionieren.
* Ich bin der Superexperte für {CMK} und möchte Erweiterungen dafür bauen, oder bestimmte Dinge in {CMK} automatisieren, {CMK} um Skripte erweitern, o.ä.
* Ich Berater für {CMK} und möchte bestimmte Aspekte in {CMK} *genau* verstehen.

== Welche Erlebnisse/Gefühle soll ein Leser bei der Lektüre des Handbuchs haben?

[horizontal]
*vollständig*:: Ich finde, was ich suche
*angenehm*:: Das Lesen ist nicht trocken und anstrengend
*schnell*:: Ich finde die Information *schnell* und kann sie auch schnell lesen
*hilfreich*:: Ich habe nicht nur verstanden, was ich gelesen habe, sondern kann es auch auf andere Situationen übertragen
*korrekt*:: Was ich gelesen habe, ist präzise und richtig
*neues*:: Ich habe (zufällig?) etwas neues entdeckt, was ich vorher nicht wusste

Immer dann, wenn neue Inhalte schreibt, sollten diese Aspekte im Hinterkopf behalten werden, um nicht nur die Software zu dokumentieren, sondern lebendig zu beschreiben. Nicht zuletzt soll das Handbuch zu {CMK begeistern und den Umgang mit der doch sehr umfangreichen und mächtigen Software Spaß machen und Erfolgserlebnisse schaffen.
