= Das offizielle Checkmk Handbuch

:cmk-docs: https://docs.checkmk.com
:cmk-website: https://checkmk.com/de
:cmk-download: https://checkmk.com/de/download
:cmk-basics: https://checkmk.com/de/monitoring
:cmk-blog: https://checkmk.com/de/blog
:cmk: Checkmk

ifdef::lang-en[]
Here is some text
endif::lang-en[]


== Willkommen

Unser Handbuch basiert auf link:https://asciidoctor.org[Asciidoctor], wird mit der Auszeichnungssprache (_markup language_) link:https://asciidoc.org/[AsciiDoc] formatiert, in diesem GitHub Repository abgelegt und automatisiert als HTML auf link:{cmk-docs}[docs.checkmk.com] bereitgestellt.
Über dieses GitHub Repository ist es möglich, an der Erstellung der Dokumentation mitzuwirken.


== Nützliche Links

* link:{cmk-docs}[{CMK} Dokumentation]
* link:{cmk-basics}[Einstieg ins Monitoring]
* link:{cmk-blog}[{CMK} Blog]
* link:{cmk-website}[{CMK} Website]
* link:{cmk-download}[{CMK} herunterladen]


== Zur Dokumentation beitragen

Auch bei sorgfältigster Arbeit schleichen sich immer wieder kleinere Fehler ein, oder es werden Themen nicht in dem Umfang behandelt, wie es vielleicht angebracht wäre.
Wenn du also daran interessiert bist, die Dokumentation von {CMK} zu verbessern, dann freuen wir uns über rege Beteiligung und versuchen Deine Anregungen zeitnah zu behandeln.


=== GitHub-Issue

Ein link:https://docs.github.com/de/issues/tracking-your-work-with-issues/about-issues[GitHub-Issue] ist der von uns bevorzugte Weg.
Füge einen Link auf den betroffenen Abschnitt im Artikel des {CMK}-Handbuchs hinzu, zitiere gegebenenfalls die Textstelle und beschreibe das Problem möglichst konkret.
Mit diesem link:https://github.com/Checkmk/checkmk-docs/issues/new/choose[Link] kannst du ein neues GitHub-Issue erstellen.

Du kannst auf GitHub auch einen Pull Request (PR) stellen.
Allerdings hat sich in der Vergangenheit gezeigt, dass ein PR in den meisten Fällen von uns nicht einfach übernommen werden konnte, da z.B. auch eine andere Sprache oder ein anderer Branch von der Korrektur betroffen waren.
Außerdem verwenden wir seit einiger Zeit in vielen Artikeln spezielle AsciiDoc-Makros, die es für Außenstehende schwierig machen, den Quelltext zu lesen und einen alternativen Text vorzuschlagen.


=== Feedback

Du hast ein Problem entdeckt, aber keine Lust, keine Zeit oder du traust Dir es schlicht nicht zu, hier selbst mitzuwirken?
Dann schreib uns ein Feedback an feedback@checkmk.com.
