= Die offizielle Dokumentation zu Checkmk

:cmk-docs: https://docs.checkmk.com
:cmk-website: https://checkmk.com/de
:cmk-download: https://checkmk.com/de/download
:cmk-basics: https://chekcmk.com/de/monitoring
:cmk-blog: https://blog.checkmk.com/de
:cmk: Checkmk

== Willkommen
Diese Dokumentation basiert auf link:https://asciidoctor.org[Asciidoctor] und wird automatisiert als HTML auf link:{cmk-docs}[docs.checkmk.com] bereitgestellt.
Über dieses Repository ist es zum einen möglich, die Dokumentation in ein anderes Format zu konvertieren (z.B. über das Makefile) und zum anderen an der Erstellung der Dokumentation teilzuhaben.
Wie es möglich ist hier mit mitzuwirken, wird nachfolgend erläutert.

== Wichtige Links
* link:{cmk-docs}[{CMK} Dokumentation]
* link:{cmk-website}[{CMK} Webseite]
* link:{cmk-download}[{CMK} herunterladen]
* link:{cmk-basics}[Einsteigerartikel zu Monitoring]
* link:{cmk-blog}[{CMK} Blog]

== Beiträge zu der Dokumentation über Pull-Requests (PR) leisten

Auch bei sorgfältigster Arbeit schleichen sich immer wieder kleinere Fehler ein, oder es werden Themen nicht in dem Umfang behandelt, wie es vielleicht angebracht wäre.
Wenn Du also daran interessiert bist, die Dokumentation von {CMK} zu verbessern, dann freuen wir uns über rege Beteiligung und versuchen entsprechend auch die PRs zeitnahe zu behandeln.
Natürlich hat jedes Projekt auch seine Ansprüche und Anforderungen. Wie sie in diesem Projekt aussehen, kann man hier nachlesen:

[horizontal]
*Einleitung*:: Eine link:contrib/intro.adoc[Einleitung] wie wir uns eine gute Dokumention vorstellen.
*Aufbau des Git*:: Hier wird beschrieben, wie der Aufbau des link:contrib/git.adoc[git] gedacht ist.
*Leitfaden zum Schreiben*:: Ein link:contrib/guide.adoc[Leitfaden], um selbst an der Dokumentation mitzuwirken.
*Entwicklungsumgebung aufsetzen*:: Tools zum selbst bauen und Hilfsmittel, um das Schreiben möglichst einfach zu machen (in Arbeit)

== Feedback

Du hast ein Problem entdeckt, aber keine Lust, keine Zeit oder Du traust Dir es schlicht nicht zu, hier selbst mitzuwirken?
Dann schreib uns ein Feedback an feedback@checkmk.com.
