= The official documentation for Checkmk

:cmk-docs: https://docs.checkmk.com
:cmk-website: https://checkmk.com/
:cmk-download: https://checkmk.com/download
:cmk-basics: https://chekcmk.com/monitoring
:cmk-blog: https://blog.checkmk.com/en
:cmk: Checkmk

== Welcome
This documentan is based on link:https://asciidoctor.org[Asciidoctor] and is automatically provided as HTML on link:{cmk-docs}[docs.checkmk.com].
On the one hand it is possible through this repository to convert the documentation into another file format (e.g. through the Makefile) and gives you the opportunity on the other hand to contribute on the content.
We will provide more information about how this is done in the next sections.

== Useful Links
* link:{cmk-docs}[{CMK} Documentation]
* link:{cmk-basics}[Monitoring basics]
* link:{cmk-blog}[{CMK} Blog]
* link:{cmk-website}[{CMK} website]
* link:{cmk-download}[{CMK} Downloads]

== How to contribute per pull request (PR)

There are bugs and typos even in the best work or a topic is not explained in a dimension that would be sufficient.
So if you are interested in making the documentation of {CMK} even more better, we are happy to welcome you and of course try to work on corresponding PRs as soon as possible.
But every project has it's requirements and demands and this is no exception. What to consider if you want to contribute and also guides for making your contribution as easy as possible, will be described in the following sections:

[horizontal]
link:contrib/en/intro.adoc[*Introduction*]:: Basic principles about what a good documentation looks like in our point of view.
link:contrib/en/git.adoc[*Structure of this git*]:: Here is explained how we think the repository is structured.
link:contrib/en/guide.adoc[*Guidance for writing*]:: Best-Practices and guidance for writing articles in this documentation itself.
link:contrib/en/dev.adoc[*How to setup your development*]:: Instructions to setup the most common code editors and for converting adoc files to HTML locally.


== Feedback

You discovered a problem, bug or typo but you are willing, do not have time or even are not confident enough to contribute directly on this project?
Please write us a feedback to feedback@checkmk.com.