= Checkmk - The Official User Guide

:cmk-docs: https://docs.checkmk.com
:cmk-website: https://checkmk.com/
:cmk-download: https://checkmk.com/download
:cmk-basics: https://checkmk.com/monitoring
:cmk-blog: https://blog.checkmk.com/en
:cmk: Checkmk


== Welcome

Our User Guide is based on link:https://asciidoctor.org[Asciidoctor], formatted with the link:https://asciidoc.org/[AsciiDoc] markup language, deposited in this GitHub repository and automatically deployed as HTML on link:{cmk-docs}[docs.checkmk.com].
Through this GitHub repository, it is possible to contribute to the creation of the documentation.
How this is possible is explained below.


== Useful links

* link:{cmk-docs}[{CMK} docs]
* link:{cmk-basics}[Monitoring basics]
* link:{cmk-blog}[{CMK} blog]
* link:{cmk-website}[{CMK} website]
* link:{cmk-download}[Download {CMK}]


== How to contribute per pull request (PR)

There are bugs and typos even in the best work or a topic is not explained in a dimension that would be sufficient.
So if you are interested in making the documentation of {CMK} even more better, we are happy to welcome you and of course try to work on corresponding PRs as soon as possible.

But every project has it's requirements and demands and this is no exception. What to consider if you want to contribute and also guides for making your contribution as easy as possible, will be described in the following sections:

[horizontal]
link:contrib/en/intro.adoc[*Introduction*]:: Basic principles about what a good documentation looks like in our point of view.
link:contrib/en/git.adoc[*Structure and handling of this repository*]:: Here is described how you deal with the repository.
link:contrib/en/guide.adoc[*Writing guide*]:: Best practices and writing assistance to contribute to the documentation yourself
link:contrib/en/dev.adoc[*How to setup your development environment*]:: Instructions to setup code editors
// and for converting adoc files to HTML locally.


== Feedback

You discovered a problem, bug or typo but you are willing, do not have time or even are not confident enough to contribute directly on this project?
Please write us a feedback to feedback@checkmk.com.
