= The Official Checkmk User Guide

:cmk-docs: https://docs.checkmk.com
:cmk-website: https://checkmk.com/
:cmk-download: https://checkmk.com/download
:cmk-basics: https://checkmk.com/monitoring
:cmk-blog: hhttps://checkmk.com/blog
:cmk: Checkmk


== Welcome

Our User Guide is based on link:https://asciidoctor.org[Asciidoctor], formatted with the link:https://asciidoc.org/[AsciiDoc] markup language, deposited in this GitHub repository and automatically deployed as HTML on link:{cmk-docs}[docs.checkmk.com].
Through this GitHub repository, it is possible to contribute to the creation of the documentation.


== Useful links

* link:{cmk-docs}[{CMK} docs]
* link:{cmk-basics}[Monitoring basics]
* link:{cmk-blog}[{CMK} blog]
* link:{cmk-website}[{CMK} website]
* link:{cmk-download}[Download {CMK}]


== Contributing to the documentation

Even with the most careful work, minor errors creep in from time to time, or topics are not dealt with to the extent that might be appropriate.
Therefore, if you are interested in making a contribution to improving {CMK}'s documentation, we would welcome your active participation and will try to address your suggestions promptly.


=== GitHub issue

A link:https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues[GitHub issue] is our preferred method for reporting.
Add a link to the affected section in the article of the {CMK} User Guide, quote the text passage if appropriate and describe the problem in as much detail as possible.
You can create a new GitHub issue with this link:https://github.com/Checkmk/checkmk-docs/issues/new/choose[link].

You can also submit a pull request (PR) on GitHub.
However, in the past, we have found that in most cases, a PR could not simply be taken over by us, e.g. because another language or another branch was affected by the correction.
In addition, for some time now we have been using special AsciiDoc macros in many articles, which make it difficult for outsiders to read the source text and suggest an alternative text.


=== Feedback

You discovered a problem, bug or typo but you are not willing, do not have time or even are not confident enough to contribute directly on this project?
Please write us a feedback to feedback@checkmk.com.
