= How to setup your development environment

:shell: source,shell,subs="quotes,macros,attributes"
:c-user: user@host:~$


== Writing with Visual Studio Code (vscode)


=== Basic setup

To prepare vscode optimally for writing in Asciidoc, it is useful to first install the corresponding link:https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[AsciiDoc] extension.
This extension provides the basis to write directly in the files and to get in near-real time the result delivered in a preview in the editor.

Optional, but recommended are also the extensions for git (if you don't use git on the command line anyway): 
link:https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens[GitLens] and link:https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github[GitHub Pull Requests and Issues]

In addition, there are of course many other little helpers that can make your life easier.
Mentioned therefore only the two most important for the start.


=== Recommended settings for the AsciiDoc extension

In order to take full advantage, there are a few basic settings for a comfortable start.
The following excerpt is from the settings as seen in the `settings.json` file:

----
{
    "asciidoc.preview.style": "checkmk.css",
    "asciidoc.preview.useEditorStyle": false,
    "asciidoc.previewFrontMatter": "show",
    "asciidoc.preview.attributes": {
        "global": "../attributes/global_attr.adoc",
    },
}
----

With the directly specified setting to the `global_attr.adoc` file, the global attributes defined by the project itself can be conveniently used.


////
== Writing with atom

tbd

== Writing with vim

tbd
////

////
== building HTML files locally

You just need two programs -- beside `make` itself -- to convert a asciidoc file into a html file:

[horizontal]
*make*:: There are now specific requirements on the used version
*Asciidoctor*:: At least version 2.0.0
*Ruby*:: Ruby should be available at least in version 2.3 if you intend to use the (internal) templates
*slimrb*:: This extension to ruby is needed if you intend to use the (internal) templates

To build a html version of an article use just call `make html` together with the article name that should be converted.
During the process `make` will do a check if the internal repository for the templates and the styling is available.
Depending on this result the HTML files will be created.
The result will be analogously look more or less like the article on the official website.
To have a fallback for the styling, there is a -- slightly adjusted -- version of the style sheet in this repository.
Be aware that you don't need to provide neither the path nor the file extension:

[{shell}]
----
{c-user} make html ARTICLE=my_article
----

After that the convertes files will be available below the directory `localbuild`:

[{shell}]
----
{c-user} ls -R localbuild/
localbuild/:
de  en

localbuild/de:
my_article.html

localbuild/en:
my_article.html
----
////