= How to setup your development

:shell: source,shell,subs="quotes,macros,attributes"
:c-user: user@host:~$

== Writing with Visual Studio Code (vscode)

=== Basic setup

To prepare vscode for writing easily asciidoc files, it's useful to install the official extension at first: link:https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[asciidoctor.asciidoctor-vscode]
This extension provides the base, to directly write in the files and see the result in semi-live in preview.

Optionally but recommend are also the extensions for git. At least as long as you do not work on the command line for git anyway. These extensions are link:https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens[GitLens] and link:https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github[GitHub Pull Requests and Issues].

Beside these there are of course a lot more little helper, that will make your life more easy on vscode. We mentioned only the most important for the beginning.

=== Recommended settings for you asciidoctor extension

To profit from all benefits that are maintained in this repo, there are some basic settings that are a good starting point. The following are an example of these how they are displayed in the settings.json directly:

----
{
    "asciidoc.preview.style": "checkmk.css",
    "asciidoc.preview.useEditorStyle": false,
    "asciidoc.previewFrontMatter": "show",
    "asciidoc.preview.attributes": {
        "global": "../attributes/global_attr.adoc",
        "chapter": "../../attributes/chapter_attr.adoc",
    },
}
----

These directly provided attributes may be used in the future to include the global custom attributes provided by the project itself. They are not relevant at the moment anyway and just a preparation.

== Writing with atom

tbd

== Writing with vim

tbd
////
== building HTML files locally

You just need two programs -- beside `make` itself -- to convert a asciidoc file into a html file:

[horizontal]
*make*:: There are now specific requirements on the used version
*Asciidoctor*:: At least version 2.0.0
*Ruby*:: Ruby should be available at least in version 2.3 if you intend to use the (internal) templates
*slimrb*:: This extension to ruby is needed if you intend to use the (internal) templates

To build a html version of an article use just call `make html` together with the article name that should be converted.
During the process `make` will do a check if the internal repository for the templates and the styling is available.
Depending on this result the HTML files will be created.
The result will be analogously look more or less like the article on the official website.
To have a fallback for the styling, there is a -- slightly adjusted -- version of the style sheet in this repository.
Be aware that you don't need to provide neither the path nor the file extension:

[{shell}]
----
{c-user} make html ARTICLE=my_article
----

After that the convertes files will be available below the directory `localbuild`:

[{shell}]
----
{c-user} ls -R localbuild/
localbuild/:
de  en

localbuild/de:
my_article.html

localbuild/en:
my_article.html
----
 ////