= Structure of this repository

:cmk: Checkmk
:v16: 1.6.0
:v20: 2.0.0
:v21: 2.1.0
:imagesdir: ../images
:CEE: pass:q,m[image:CEE.svg[CEE,title=Checkmk Enterprise Editions,width=20] *Checkmk Enterprise Editions*]
:CRE: pass:q,m[image:CRE.svg[CRE,title=Checkmk Raw Edition,width=20] *Checkmk Raw Edition*]

There are different directories to be used during the creating of articles and the according content.
The most important are explained here.

== Basic structure

There are the following directories on the main level:

[horizontal]
*de*:: The place for all articles in german. At the moment all articles are written in german and then later translated to english.
*en*:: The place for all articles in english as soon as the german version is written.
*images*:: Screenshots and Icons will be located in this directory. It has a flat hierarchy beside the subfolder `icons`.
*attributes*:: To make the writing more easy and to provide a way to standardize specific terms or text formatting we provide a set of custom attributes in this directory.
*contrib*:: Here all the documentation on how to work in this repository is located.

Additionally there are more files that may be more or less usefull and should simplify the writing:

[horizontal]
*checkmk.css*:: This style sheet may be used to generate a live preview during the writing to get as close as possible to the official content on the website.
*Makefile*:: If you want to convert a single document to html locally, you may do that with `make`. You will find more help if you cann `make help`.

== Branches

The documentation of {CMK} is diveded by it's versions but not by it's editions.
That means basically, that there a no differnt version for {CMK} {v16} in case of the {CRE} or {CEE}.
On the other side, there is a branch for each version.
So for a new article or a revision that affects only a specific released version of {CMK} you should use the appropiate branch.

The master is in reverse always the work in progress for the version of {CMK} which is currently in development and not released yet.

[IMPORTANT]
At the moment we do live a parallel world for the release of {v20}.
We do actually already write in a separate branch for this version and the _master_ is already used for version {v21}.


== Commit-Nachricht

Regardless if you are working officially in the name of _tribe29_ or as a contributor with _pull requests_ (PRs), a commit message should always be helpful to understand what is done in a commit.
That may require a more verbose description, if a change needs more content argumentation.
Especially in PRs are more easy to work on, if the officials of _tribe29_ are able to understand the reasons for a change fast.

You should additionally consider the link:guide.adoc[guide for writing] as there are some available markers for commit messages described.
Here again in shortly:

[horizontal]
*translate*:: Marks the affected article as synchroniously content wise. This does not necessarily mean, that everything is translated. but every content is in any language in every version available.
*only-de*:: Marks a commit for the affected german version of articles as an editorial change that does not need a translation.
*only-en*:: the pendant to *only-de*
