= Structure and handling of this repository

:cmk: Checkmk
:v16: 1.6.0
:v20: 2.0.0
:v21: 2.1.0
:imagesdir: ../../images
:CRE: pass:q,m[image:CRE.svg[CRE,title=Checkmk Raw Edition,width=20] *Checkmk Raw Edition*]


There are several directories and some rules for creating articles and related materials.
The most important ones are explained here.


== Directories

On the top level there are the following directories:

[horizontal]
*de*:: The place for all articles in German language. Currently all articles are first written in German and then translated to English.
*en*:: The place for all articles in English language, as soon as the German version is ready.
*images*:: The images used in the articles (graphics, screenshots, icons) are stored here: Graphics and screenshots in a flat hierarchy and the icons used in the body text in a height of 20 pixels in the subdirectory `icons`.
*attributes*:: To make writing easier and to standardize certain terminology and formatting, general attributes are defined and adjusted here.
*contrib*:: Contains the documentation for using the repository.


== Files

[horizontal]
*checkmk.css* :: This stylesheet file is an adapted version of the file used for publishing.
It can be used to generate a live _preview_ when writing in the editor, which is as close as possible to the published page in the target format.
// *Makefile*:: If individual documents are to be converted to HTML locally, this can be done with `make`. The help is available via `make help`.


== Branches

The documentation of {CMK} is version-based, but not edition-based. 
On the one hand, this means that the differences between {CRE} and the commercial editions are described in the same manual. 

There is a separate branch for each stable, published version. This is to be used if the article or correction applies to an already published version of {CMK}.
Conversely, the master is always used for the version of {CMK} that is currently under development and has not yet been officially released.


[#gitcommitmessages]
== git commit messages

Regardless of whether it is regular _tribe29_ work or _pull requests_ (PRs), a commit message should always be helpful to understand what was done in the commit.
For this purpose, it may also sometimes be necessary to provide a more detailed description to justify the content of the change.
Especially in the case of a PR, it makes tribe29's work much easier if they can quickly understand the reason for a change.

Some keywords in the commit messages are used to track the translation status.
If one of the following keywords is used at the beginning of a commit, it has the following effect:

[horizontal]
*only-de*:: This commit only affects German, does not need to be translated to English, and is not considered for translation status.
*only-en*:: The counterpart to *only-de*.
*content-sync*:: The committed article is completely synchronous in content in both languages.
Any commits made before this date in either language will be automatically acknowledged and ignored in the future.
This keyword is also used to indicate the commit of an article for translation, i.e.: The content is in sync, but not necessarily already translated.

For examples on how to use these git commit messages, see the link:guide.adoc#translate[translation] topic.
