= Guidance for writing the docs

:cmk: Checkmk
:shell: source,shell,subs="quotes,macros,attributes"
:shell-raw: source,shell,subs="verbatim,attributes"
:c-user: user@host:~$
:c-omd: pass:q[[hljs-meta]#OMD[mysite]:~$#]
:c-local: pass:q[[hljs-meta]OMD[central]:~$#]
:c-remote1: pass:q[[hljs-meta]OMD[remote1]:~$#]
:c-remote2: pass:q[[hljs-meta]#>OMD[remote2]:~$#]
:c-root: root@linux#
:file: source

== Basics

=== New articles

==== Writing

Articles, which are written completely new, should always be written on the upcoming version of {CMK}. If the content is also relevant for already published version, a backport into the affected branch may be done later. *Important*: An article needs to be adjusted or partially rewritten to be correct for the affected version of {CMK}. Basically is is not mandatory to backport an article into earlier/released versions, but it is a welcome thing if done.

As soon as the first version of an article is finished and at least a basic structure is present, the article may be published into the respective branch. With this said, there are two stages that an article could be in during the writing:

[horizontal]
*draft*:: The writing has been started and there is already initial (hepful) content. The article itself is not finished yet nor reviewed. Also the content may be only partially available or completely missing. In this case the article must be marked as `draft` in the `revdate` attribute.
*final*:: The article is finished, all reviews have been done and it is checked, if the article is complete, correct and without typos. In this case the article attribute `revdate` must contain a correct date. Usually this is the date when the article actually has been finished and not the commit date.

==== Translations

We do use the history of git to track the status of translations, respectivley if the content of the same article in different languages is in sync. For that we have specific labels in the commits to make the tracking more easy:

[horizontal]
*content-sync*:: An articles is copied into the other languages as soon as it is finished. The content must then be commented and the changes committed with this label. To minimize typos there also the alias `content_sync` as alternative label.


[{shell}]
----
{c-user} git commit en/my_new_article.asciidoc -m "content-sync: wrote new helpful article"
----

The label is an indicator for the time as an article is content wise in sync with all languages. *Important*: The content must be in sync if you use this label, but the content does not have to be in the correct language!


=== Revise articles

==== Writing

You know that: You finished an article to a component and after 2 days it's already wrong or not up to date anymore. The end of the writing is the beginning of the writing. In best case you are finishing fast if you revise an existing article. So in this case you should only consider the regular hints for writing an article.

==== Translations

You need to consider different things if you want to track the content changes on an existing article as if you would need to do if you starting from scratch and just the whole article needs to be translated. So there are at least one of these situations where you can find yourself in:

* The article is written and has been committed for translaten. But the initial translation is not yet finished.
* The article is written and already translated

And as if this would not be enough, there are also different kind of changes, you may want to do:

* You want to handle a simple typo
* You want to add minor contentual changes
* You want to add major contentual changes

To cover such situations you do not need to anything in the case you are adding new content or change existing content. These commits are automatically tracked if we run a check, which articles do have commits that have not yet been translated. But in some cases there is no need for a translation, as you just made editorial changes (Typos, phrasing, etc). For such changes we do have the labels *only-de* or *only-en* to exclude these from the tracking:

[{shell}]
----
{c-user} git commit de/my_article -m "only-de: just fixed a typo"
----

With these labels we do have the advantage, that we do not miss any translation and do have on the other hand the opportunity to make changes without producing a lot of false-positives during the tracking.

[IMPORTANT]
If you read the previous lines carefully, you may noticed, that not all situations mentioned in the beginning are handled with the current description. To reduce the effort for all contributors, you may translate minor contentual changes directly. This will reduce the list of untranslated parts in an article and reduces the effort for employees of _tribe29_ a lot to take care that all translations are made. But it is important in such cases, that you submit the changes in *both* languages of an article in the very same commit:

[{shell}]
----
{c-user} git commit de/my_article en/my_article -m "added example for ..."
----


== Usage of Asciidoctor

The documentation of {CMK} does currently not use all the features that asciidoctor provides. To get a homogeneous picture of the articles, we made a (not exhausting) list of features and how you should use them.


=== Kopfzeilen in jedem Dokument

Jeder Artikel verwendet ein Grundset an Metadaten und Kopfzeilen, die bei der Konvertierung zu HTML benötigt werden. Hier eine Liste an Headern und ob diese verpflichtend oder optional sind:

[cols=3]
|===
|Attribut|Beschreibung|verpflichtend?

|include::global_attr.adoc[]|Importiert vordefinierte Attribute, die im Text verwendet werden können und setzt grundlegende Attribute, wie den Pfad zu den Bildern und Icons|ja
|= Titel|Der Titel, wie er am Anfang des Artikels angezeigt werden soll|ja
|:revdate:|Beschreibt die letzte inhaltliche Bearbeitung eines Artikels. Wenn der Artikel noch nicht fertig ist, wird das mit `draft` markiert|ja
|:title:|Ein beschreibender Titel des Artikels in den Metadatan des HTML-Dokuments|ja
|:description:|Eine Kurzbeschreibung, worum es in dem Artikel geht|ja
|\{related-start} & \{related-end}|Links zu anderen Artikeln, die hilfreich für das Verständnis sind, oder den Kontext erweitern|nein
|===

So eine Kopfzeile eines Dokuments könnte also so aussehen:

----
\include::global_attr.adoc[]
= Mein Artikel zu Feature X
:title: Alles über Feature X
:description: Lernen Sie, wie sie Feature X einrichten und effizient in {CMK} nutzen können, um Ihre Monitoring-Umgebung optimal im Blick zu haben.

{related-start}
link:dashboards.html[Dashboards]
link:basics_downtimes.html[Wartungszeiten]
{related-end}
----

=== Überschriften

Überschriften sollte maximal auf drei Ebenen zusätzlich zu der ersten benutzt werden. Daraus ergibt sich, folgendes Bild:

----
= Dokumententitel (H0)

== H1-Überschrift

=== H2-Überschrift

==== H3-Überschrift
----

=== Textformatierungen

Grundsätzlich gilt, dass Formatierungen sparsam eingesetzt werden sollten. Ein Auszeichung in *fett* oder _kursiv_ sollte daher einen klaren Zweck verfolgen, der nicht regelmäßig vorkommt. Grundsätzlich gibt es für verschiedene Zwecke bereits unterschiedliche Definitionen, die benutzt werden sollten:

tbd
// Erlauben wollen wir ja * & _ & `. Dazu kommen dann noch kleinere Sachen, wie z.B. das Highlighting von Pfaden in der GUI.

=== Listen

Listen können entweder ungeordnet oder geordnet sein und sollten nicht mehr als zwei Ebenen haben:

----
* Punkt eins
** Unterpunkt zu eins
* Punkt zwei

. Mach erst A
.. Bedenke A2, wenn Du A machst
. Danach kommt B
----

Für kleine Tabellen, die nur zwei Spalten haben, kann es sich anbieten, stattdessen eine "Description list" zu schreiben:

----
Stichwort:: Hier kommt eine Beschreibung zu diesem Stichwort
----

// TODO: Entscheiden, ob wir horizontale und basic erlauben oder nur eins von beidem

=== Tabellen

Tabellen können unter Asciidoc unterschiedlich ausgezeichnet werden. Um ein gemeinsames Bild zu haben, werden Tabellen basierend auf folgender Syntax aufgebaut:

----
[cols=3] <1>
|===
|Spalte 1 |Spalte 2| Spalte3 <2>

|Zeile 1.1| Zeile1.2 | Zeile 1.3 <3>
|Noch eine Zeile||
|===
----
<1> Hier wird die Anzahl der Spalten angegeben. Syntaktisch nicht notwendig, aber es vereinfacht das Lesen.
<2> Titel der Spalten in der Tabelle
<3> Jede Zeile bekommt eine eigene Zeile und jede Spalte beginnt mit einem | (Pipe)

Als Alternative kann auch die Spaltenbreite in Prozent angegeben werden. Die ~ (Tilde) dient hier als Marker, dass man für diese Spalte keine feste Breite angeben möchte:

----
[cols="10,~,~,20"] <1>
----
<1> Diese Tabelle würde demnach vier Spalten haben, bei denen die erste eine Breite von 10% haben und die letzte 20% haben würde. Die Breite der beiden mittleren Spalten wird demnach automatisch berechnet.

=== Kommandozeilenauszüge

Kommandozeilen sind in Checkmk noch immer sehr wichtig und haben daher einen besonderen Stellenwert. Gleichzeitig sind sie auch die größte Hürde, wenn es um ein einheitliches und funktionierendes Syntaxbild geht. Um die meisten Fälle abzudecken, gibt es ein vordefiniertes Attribut, welches Sie nutzen können (und auch sollten). Es wird genutzt, um eine Kommandozeilenausgabe einzuleiten:

----
 [{shell}] <1>
 ----
 {c-user} cat /etc/hosts <2>
 127.0.0.1      localhost localhost.local
 ----
----
<1> Mit diesem Attribut werden die wichtigsten Optionen für die Kommandozeile gesetzt und gleichzeitig auch Formatierungen, Attribute und Makros erlaubt. Sollen nur Attribute erlaubt sein, so kann man auch `\{shell-raw}` nutzen.
<2> Hier ist ein Beispiel für eine Abkürzung, um eine Shell zu simulieren. Weitere finden Sie unten.

In Einzelfällen kann ein Kommandozeilenauszug natürlich auch manuell mit Optionen versehen werden. Das sollte jedoch der Ausnahmefall bleiben. Hier noch einmal alle Attribute, die derzeit definitiert sind und was deren Wert ist:

[horizontal]
*\{shell}*:: `{shell}`
*\{shell-raw}*:: `{shell-raw}`
*\{c-user}*:: `{c-user}`
*\{c-root}*:: `{c-root}`
*\{c-omd}*:: `{c-omd}`
*\{c-local}*:: `{c-local}`
*\{c-remote1}*:: `{c-remote1}`
*\{c-remote2}*:: `{c-remote2}`

=== Dateiauszüge

Dateiauszüge sind in Asciidoc ähnlich, wie Kommandozeilenauszüge und daher nicht sehr viel anders. Derzeit unterstützen wir lediglich eine kleine Anzahl, deren Syntax dann auch hervorgehoben dargestellt wird. Es empfiehlt sich daher das Standard-Attribute zu nutzen:

----
 [{file}] <1>
 ----
 Hier steht ein Textauszug aus einer Datei
 ----
----
<1> Statt einer shell wird hier schlicht angegeben, dass es sich bei dem Inhalt um eine Datei handelt.

Derzeit gibt es nur eine vordefiniertes Attribut:

[horizontal]
*\{file}*:: `{file}`

=== Screenshots

tbd
// Hier gibt es noch viel zu erzählen. U.a. die Handhabung von Bildern mit Rahmen und Bildern, die rechts vom Text umrandet werden sollen.
// Weiter die Prinzipien, wie Schriftgröße im Bild, Bildgröße, etc. Das wird noch etwas Arbeit...
