= Guidance for writing the docs

:cmk: Checkmk
:shell: source,shell,subs="quotes,macros,attributes"
:shell-raw: source,shell,subs="verbatim,attributes"
:c-user: user@host:~$
:c-omd: pass:q[[hljs-meta]#OMD[mysite]:~$#]
:c-local: pass:q[[hljs-meta]OMD[central]:~$#]
:c-remote1: pass:q[[hljs-meta]OMD[remote1]:~$#]
:c-remote2: pass:q[[hljs-meta]#>OMD[remote2]:~$#]
:c-root: root@linux#
:file: source

== Basics

=== New articles

==== Writing

Articles, which are written completely new, should always be written on the upcoming version of {CMK}. If the content is also relevant for already published version, a backport into the affected branch may be done later. *Important*: An article needs to be adjusted or partially rewritten to be correct for the affected version of {CMK}. Basically is is not mandatory to backport an article into earlier/released versions, but it is a welcome thing if done.

As soon as the first version of an article is finished and at least a basic structure is present, the article may be published into the respective branch. With this said, there are two stages that an article could be in during the writing:

[horizontal]
*draft*:: The writing has been started and there is already initial (hepful) content. The article itself is not finished yet nor reviewed. Also the content may be only partially available or completely missing. In this case the article must be marked as `draft` in the `revdate` attribute.
*final*:: The article is finished, all reviews have been done and it is checked, if the article is complete, correct and without typos. In this case the article attribute `revdate` must contain a correct date. Usually this is the date when the article actually has been finished and not the commit date.

==== Translations

We do use the history of git to track the status of translations, respectivley if the content of the same article in different languages is in sync. For that we have specific labels in the commits to make the tracking more easy:

[horizontal]
*content-sync*:: An articles is copied into the other languages as soon as it is finished. The content must then be commented and the changes committed with this label. To minimize typos there also the alias `content_sync` as alternative label.


[{shell}]
----
{c-user} git commit en/my_new_article.asciidoc -m "content-sync: wrote new helpful article"
----

The label is an indicator for the time as an article is content wise in sync with all languages. *Important*: The content must be in sync if you use this label, but the content does not have to be in the correct language!


=== Revise articles

==== Writing

You know that: You finished an article to a component and after 2 days it's already wrong or not up to date anymore. The end of the writing is the beginning of the writing. In best case you are finishing fast if you revise an existing article. So in this case you should only consider the regular hints for writing an article.

==== Translations

You need to consider different things if you want to track the content changes on an existing article as if you would need to do if you starting from scratch and just the whole article needs to be translated. So there are at least one of these situations where you can find yourself in:

* The article is written and has been committed for translaten. But the initial translation is not yet finished.
* The article is written and already translated

And as if this would not be enough, there are also different kind of changes, you may want to do:

* You want to handle a simple typo
* You want to add minor contentual changes
* You want to add major contentual changes

To cover such situations you do not need to anything in the case you are adding new content or change existing content. These commits are automatically tracked if we run a check, which articles do have commits that have not yet been translated. But in some cases there is no need for a translation, as you just made editorial changes (Typos, phrasing, etc). For such changes we do have the labels *only-de* or *only-en* to exclude these from the tracking:

[{shell}]
----
{c-user} git commit de/my_article -m "only-de: just fixed a typo"
----

With these labels we do have the advantage, that we do not miss any translation and do have on the other hand the opportunity to make changes without producing a lot of false-positives during the tracking.

[IMPORTANT]
If you read the previous lines carefully, you may noticed, that not all situations mentioned in the beginning are handled with the current description. To reduce the effort for all contributors, you may translate minor contentual changes directly. This will reduce the list of untranslated parts in an article and reduces the effort for employees of _tribe29_ a lot to take care that all translations are made. But it is important in such cases, that you submit the changes in *both* languages of an article in the very same commit:

[{shell}]
----
{c-user} git commit de/my_article en/my_article -m "added example for ..."
----


== Usage of Asciidoctor

The documentation of {CMK} does currently not use all the features that asciidoctor provides. To get a homogeneous picture of the articles, we made a (not exhausting) list of features and how you should use them.


=== Headings in each document

Every article does make use of a basic set of meta data and the first headings. These are needed during the conversion to HTML. The following is a list of meta data and headings and an entry is mandatory or optional:

[cols=3]
|===
|Attribute|Description|mandatory?

|include::global_attr.adoc[] |Does import predefined custom attributes that may be used during the writing and also defines builtin attributes like paths to images or icons. |yes
|= title |The title that should be displayed in the beginning. Should ideally not contain more than 30 characters. |yes
|:revdate: | Describes the last content change of an article. IF an article is not yet finished, the placeholder `draft` is used. |yes
|:title: |A more descriptive title for the meta data of the HTML document. Should not contain more than 60 characters and may a copy of the title (=) header if there is no meaningful longer descriptive title. |yes
|:description: |A short description of the content in the article. Should not contain more than 150 characters. |yes
|\{related-start} & \{related-end} |Links to other articles, that may be useful for the understanding or to extend the context. |no
|===

So the meta data content of a document could look like this:

----
\include::global_attr.adoc[]
= Feature X
:title: Everything about feature X
:description: You will learn in this chapter, how to configure and use feature X efficiently in {CMK} to get a perfect understanding of you monitoring environment.

{related-start}
link:dashboards.html[Dashboards]
link:basics_downtimes.html[Downtimes]
{related-end}
----

=== Headings

Headings should be used at three layers max additionally to the first heading in the meta data. So that results in the following:

----
= document title (H0)

== H1 heading

=== H2 heading

==== H3 heading
----

=== basic text formatting

There is a rule of thumb, that basically formatting text should used carefully. A *bold* or _italic_ formatting should have a specific use that does not occur regularly. There are already definitions for regular cases, that should be used consitently:

tbd

// Erlauben wollen wir ja * & _ & `. Dazu kommen dann noch kleinere Sachen, wie z.B. das Highlighting von Pfaden in der GUI.

=== Lists

Lists may be unordered or ordered and should not contain more than one layer:

----
* Point one
* Point two

. At first do A
. After that do B
----

For smaller tables, that do only contain to columns, asciidoc provides the "description list", which you may want to use:

----
Keyphrase/-word:: Here is a description to the keyword/keyphrase
----

// TODO: Entscheiden, ob wir horizontale und basic erlauben oder nur eins von beidem

=== tables

Asciidoc provides different possibilities to create tables. To get a homogenous text picture, table must be created with the following syntax:


----
[cols=3] <1>
|===
|Column 1 |Column 2 |Column 3 <2>

|line 1.1 |line 1.2 |line 1.3 <3>
|another line||
|===
----
<1> Here you provide the amount of columns. This is syntactical not necessary but make the reading more easy.
<2> This line provides the column titles of the table.
<3> Every line in the table gets it's own line in the document and each column starts with a | (pipe).

Alternativly you may set the width of a column in percent. The character ~ (tild) is used, if you do not want to set the width for a particular column:

----
[cols="10,~,~,20"] <1>
----
<1> This table will contain four columns. The first one will have a width of 10% and the last one of 20%. The two column in the middle will be calculated automatically.

=== command line examples

Command lines are still important in {CMK} and do have a special place in the documentation. At the same time, these are quite hard to handle if we do want a homogenous text picture and presentation. To handle the most cases, there is a predefined custom attribute, that you may (and for regular cases should) use. It is being used, to introduce a command line example block:


----
 [{shell}] <1>
 ----
 {c-user} cat /etc/hosts <2>
 127.0.0.1      localhost localhost.local
 ----
----
<1> The most important options will be set with this attribute and at the same time the usage of formattings, attributes and macros. If you need to restrict this to allow only attributes, you may use `\{shell-raw}`.
<2> Here an example to simulate a shell. You will find more examples below.

In some cases you may of course set the options manually. But this should always be an exception. The following are all attributes, that are currently defined together with a description:

[horizontal]
*\{shell}*:: `{shell}`
*\{shell-raw}*:: `{shell-raw}`
*\{c-user}*:: `{c-user}`
*\{c-root}*:: `{c-root}`
*\{c-omd}*:: `{c-omd}`
*\{c-local}*:: `{c-local}`
*\{c-remote1}*:: `{c-remote1}`
*\{c-remote2}*:: `{c-remote2}`

=== file examples

As it is the case that file examples in asciidoc are quite similar to command line examples, there is no big difference here. At the moment we do support only a small amount of cases for automatic syntax highilighting. So you may want to use the predefined custom attribute for file examples:

----
 [{file}] <1>
 ----
 Here is the text content of a file
 ----
----
<1> Just use the file attribute to mark a code block as an example that provides content of a file.

At the moment there is only one predefined custom attribut:

[horizontal]
*\{file}*:: `{file}`

=== Screenshots

tbd
// Hier gibt es noch viel zu erzählen. U.a. die Handhabung von Bildern mit Rahmen und Bildern, die rechts vom Text umrandet werden sollen.
// Weiter die Prinzipien, wie Schriftgröße im Bild, Bildgröße, etc. Das wird noch etwas Arbeit...
