= Introduction

:imagesdir: ../../images
:cmk-basics: https://checkmk.com/monitoring
:cmk-blog: https://blog.checkmk.com
:CMK: Checkmk
:CRE: pass:q,m[image:CRE.svg[CRE,title=Checkmk Raw Edition,width=20] *Checkmk Raw Edition*]


When you read a manual or documentation for a piece of software, you usually have a specific purpose in mind.
In the rarest cases one will open an article from the {CMK} User Guide out of pure coincidence.
For this reason, there are also certain basic principles according to which the content for the documentation is created.

Also, and most importantly, this includes what the manual *does not* want to do, such as provide _best practices_ or procedures (_how to's_), which is already covered by the link:{cmk-blog}[blog] section or the general link:{cmk-basics}[introduction to monitoring].


== Who reads the User Guide and why?

* I am looking for a suitable monitoring tool.
It is important to me that this can meet my requirements.
Is {CMK} suitable for this and does the User Guide convey this to me?
* I am to adopt {CMK} in my company and want to thoroughly familiarize myself with the subject.
Above all, I have the time to do so.
* I use {CMK}, have a specific requirement and do not know how to accomplish that.
* I use {CMK} and would like to get deeper into the topic of "processing events", or read up on the topic at my leisure.
* I have been using {CRE} for a while and would like to see if and when one of the commercial editions would be worthwhile, or which things work differently there.
* I am the {CMK} super expert and would like to build extensions for it, or automate certain things in {CMK}, add scripts to {CMK}, or similar.
* I am a consultant for {CMK} and want to understand certain aspects in {CMK} *exactly*.


== What experience or feeling should a reader have?

[horizontal]
*complete*:: I find what I am looking for.
*pleasant*:: Reading is not dry and exhausting.
*efficiency*:: I find the information *quickly* and can also read it quickly.
*useful*:: Not only do I understand what I read, but I can apply it to other situations.
*accurate*:: What I have read is precise and correct.
*new*:: I discovered (by accident?) something new that I didn't know before.

Whenever writing new content, these aspects should be kept in mind, not only to document the software, but to describe it in a lively way.
Last but not least, the {CMK} User Guide should inspire, and the handling of the nevertheless very extensive and powerful software should be fun and bring a sense of achievement.
