// -*- coding: utf-8 -*-

=== Darf ausführbare Dateien hinzufügen oder anpassen (_Can add or modify executables_)

Diese Berechtigung ist überall dort notwendig, wo ausführbare Dateien hinzugefügt oder geändert werden sollen.
Sie bezieht sich sowohl auf die {CMK}-Instanz als auch auf Hosts im Monitoring und betrifft daher:

* Die Installation von xref:mkps#[{CMK} Erweiterungspaketen]
* Die Konfiguration xref:active_checks.html#[aktiver Checks] über die Regel [.guihint]#Integrate Nagios plugins#
* Die Konfiguration individueller Programme mit der Einstellung [.guihint]#Use a custom check plugin# über die Regel [.guihint]#Host check command#
* Die Bereitstellung von Legacy Nagios Plugins in Agentenpaketen via xref:agent_linux#e2e_monitoring[MRPE] über die Regel [.guihint]#Execute MRPE checks#
* Die Bereitstellung beliebiger Dateien in Agentenpaketen über die Regel [.guihint]#Deploy custom files with agent#
* Die Ausführung von xref:datasource_programs#[Datenquellprogrammen]
* Die Ausführung individueller xref:ec#actions[Aktionen in der Event Console]

Zudem ist diese Berechtigung erforderlich, damit die Funktion [.guihint]#Bake and sign agents# zur Verfügung steht.
