// -*- coding: utf-8 -*-
include::global_attr.adoc[]
// Verwendung in install_azure und install_aws

[#setup]
== Einrichtung

[#login]
=== Login auf der virtuellen Maschine

Das Root-Login ist auf den AWS-/Azure-Images deaktiviert.
Stattdessen kommt der Nutzer `ubuntu` zum Einsatz, der über die Berechtigung verfügt, `sudo` mit beliebigen Kommandos ohne Passwortabfrage auszuführen.
Wenn Sie ein separates Schlüsselpaar für das Login auf der virtuellen Maschine erstellt haben, müssen Sie mit dem Parameter `-i` den Pfad zu dessen privaten Teil angeben.
Die IP-Adresse ist natürlich auf die anzupassen, unter der die VM von außen erreichbar ist:

[{shell}]
----
{c-user} ssh -i /path/to/id_file.priv ubuntu@192.0.2.123
----

Sie finden sich nun am Prompt des Nutzers `ubuntu` wieder.
Der exakte Prompt kann als Host-Name den beim Anlegen der VM angegebenen Host-Namen oder eine IP-Adresse enthalten.
Wir verwenden im Laufe des weiteren Artikels den Host-Namen `cloud`:

[{shell}]
----
{c-ubuntu}
----

[#create_site]
=== Instanz aufsetzen

Eine {CMK}-Instanz muss eindeutig benannt sein und sollte darüber hinaus eine leichte Identifikation ermöglichen.
Hier, wie an den meisten anderen Stellen dieses Handbuches, verwenden wir als Instanznamen `mysite`.
Im Beispiel wird das Passwort `t0p53cr3t` für den Instanz-Administrator `cmkadmin` vergeben.

Das Erstellen einer Instanz geschieht mit dem Verwaltungswerkzeug von {CMK}, xref:omd_basics#[`omd`].
Vorinstalliert ist immer die neueste Version von {CMK}:

[{shell}]
----
{c-ubuntu} sudo omd create --admin-password t0p53cr3t mysite
Adding /opt/omd/sites/mysite/tmp to /etc/fstab.
Creating temporary filesystem /omd/sites/mysite/tmp...[green]#OK#
Updating core configuration...
Generating configuration for core (type cmc)...
Starting full compilation for all hosts 
 Creating global helper config...[green]#OK#
 Creating cmc protobuf configuration...[green]#OK#
Executing post-create script "01_create-sample-config.py"...[green]#OK#
Executing post-create script "02_cmk-compute-api-spec"...[green]#OK#
Executing post-create script "03_message-broker-certs"...[green]#OK#
Restarting Apache...[green]#OK#
Created new site mysite with version {current}.cce.

  The site can be started with omd start mysite.
  The default web UI is available at \http://cloud/mysite/

  The admin user for the web applications is cmkadmin with password: t0p53cr3t
  For command line administration of the site, log in with 'omd su mysite'.
  After logging in, you can change the password for cmkadmin with 'cmk-passwd cmkadmin'.
----

Starten Sie jetzt die neu angelegte Instanz mit

[{shell}]
----
{c-ubuntu} sudo omd start mysite
----

Die in der obigen Kommandoausgabe gezeigte URL (`\http://cloud/mysite`) verwendet den intern genutzten Host-Namen Ihrer AWS- oder Azure-VM.
Da dieser in der Regel nicht extern aufgelöst wird, ist die URL von eingeschränktem Nutzen.
In der Regel werden Sie zunächst über die IP-Adresse oder einen im eigenen DNS-Server hinterlegten Host-Namen zugreifen.

[#ssl_certs]
=== Zertifikate hinterlegen

Damit der System-Apache überhaupt am HTTPS-Port 443 lauschen kann, benötigt er gültige Zertifikate.
Beim ersten Start der virtuellen Maschine werden hierfür die selbst signierten link:https://packages.ubuntu.com/de/jammy/all/ssl-cert/filelist[_Snakeoil Inc._ Zertifikate^] generiert.
Wir raten dringend zum baldigen Austausch gegen xref:omd_https#[eigene Zertifikate], bei denen die komplette Zertifikatskette leicht verifiziert werden kann.

Die Apache-Konfiguration hält sich dabei eng an die Ubuntu-Standards, geänderte Zertifikatspfade müssen in der Datei `/etc/apache2/sites-enabled/000-default.conf` eingetragen werden.

////
MFS: Dürfte obsolet sein, weil man im Regelfall keine kompletten Hosts exponiert, sondern einzelne Ports.
=== Firewall einrichten

Standardmäßig öffnet {CMK} Ports nur sparsam und nach expliziter Aktivierung benötigter Komponenten.
Dennoch kann es sinnvoll sein, die verwendeten Ports weiter – zum Beispiel auf bestimmte IP-Adressen – einzuschränken.

In einem Single Site Setup, in dem Hosts im Monitoring auch per Push Monitoringdaten zur {CMK}-Instanz schicken, müssen die folgenden Ports des {CMK}-Servers erreichbar sein:
// TK: Single Site Setup: ungünstig, da die Site in deutsch Instanz heisst. Vielleicht: In einer {CMK}-Konfiguration mit einer Instanz (_single site setup_) ...
// TK: in dem Hosts im Monitoring auch per Push zur {CMK}-Instanz schicken > in dem Hosts auch im Push-Modus Daten zur {CMK}-Instanz schicken

* Von den Hosts im Monitoring aus: Port 80/443 (HTTP/HTTPS, während der Agentenregistrierung) und Port 8000 (Agent Receiver, dauerhaft)
* Für die Verwaltung per Browser und REST-API: Port 80/443 (HTTP/HTTPS)

Konsultieren Sie unsere Übersicht xref:ports#[aller verwendeten Ports], falls Sie ein verteiltes Monitoring aufsetzen oder beispielsweise Statusabfragen über die xref:glossar#livestatus[Livestatus-Schnittstelle] vornehmen wollen.
////

[#mta]
=== E-Mail-System einrichten

Da die Wege der xref:intro_notifications#[Benachrichtigungen] in {CMK} vielfältig sind und variieren können, ist kein E-Mail-System vorbereitet.

[#no_mta]
==== {CMK} ohne E-Mail-System

Auch der vollständige Verzicht auf ein lokales E-Mail-System ist möglich, falls Sie ausschließlich die xref:notifications#syncsmtp[nachvollziehbare Zustellung von HTML-E-Mails per SMTP] aktivieren wollen oder auf Benachrichtigungs-Plugins für Plattformen wie xref:notifications_teams#[Microsoft Teams] oder xref:notifications_slack#[Slack] setzen.

Beachten Sie aber, dass in dieser Konfiguration keine xref:notification_rules#bulk[Bulk-Benachrichtigungen] möglich sind.

[#simple_mta]
==== Relay-only oder vollwertiger Mail Transport Agent (MTA)

Im Regelfall werden Sie wegen der höheren Flexibilität ein E-Mail-System einrichten wollen.
Für kleinere Umgebungen hat sich der _relay-only MTA_ link:https://manpages.ubuntu.com/manpages/jammy/man7/nullmailer.7.html[Nullmailer^] bewährt.

////
MFS: Weitere Recherche nötig. Nullmailer verschluckt sich gerne mal und stellt die Arbeit komplett ein. Dafür ist mutmaßlich GnuTLS in Verbindung mit Nebenläufigkeiten verantwortlich.
Eine typische Nullmailer-Installation und -Konfiguration ist in wenigen Zeilen in der Shell erledigt:

[{shell}]
----
{c-ubuntu} sudo apt install nullmailer
{c-ubuntu} echo "smtp.myprovider.xyz smtp --auth-login --user='checkmk@example.com' --pass='mypassword' --port=587 --starttls" | sudo tee /etc/nullmailer/remotes
{c-ubuntu} echo "example.com" | sudo tee /etc/nullmailer/defaultdomain
{c-ubuntu} sudo chmod 600 /etc/nullmailer/remotes
{c-ubuntu} sudo systemctl restart nullmailer
----
////

Für größere Installationen, bei denen unvorhergesehene Ereignisse auch einige Hundert E-Mails zur Folge haben können, empfehlen wir die Installation eines vollwertigen MTAs wie Postfix.

[#add_hosts]
=== Hosts ins Monitoring aufnehmen

[#pull]
==== Localhost im Pull-Modus
// TK: oder: Hosts (localhost) im Pull-Modus?

In den allermeisten Fällen dürfte der {CMK}-Server selbst der erste Host sein, den Sie xref:intro_setup_monitor#linux[ins Monitoring aufnehmen.]
Dazu müssen Sie den Linux-Agenten auf dem {CMK}-Server installieren.
Der Agent kommuniziert mit dem Server im xref:glossar#pull_mode[Pull-Modus].
Wenn Ihnen der Download des Agentenpaketes über die Weboberfläche mit anschließendem Transfer per `scp` zu umständlich erscheint, können Sie den Agenten in seiner Standardkonfiguration ("Vanilla") direkt aus dem Dateisystem installieren:

[{shell}]
----
{c-ubuntu} sudo apt install $(sudo find /opt/omd/versions/ -name 'check-mk-agent_*.deb' | tail -n1)
----

Unmittelbar nach der Installation lauscht der {CMK}-Agent im unverschlüsselten Legacy-Pull-Modus auf Port 6556.
Führen Sie daher zeitnah xref:intro_setup_monitor#register[die Registrierung] durch, damit keine unbefugten Dritten auf die Agentenausgabe zugreifen können:

[{shell}]
----
{c-ubuntu} sudo cmk-agent-ctl register --hostname localhost --server localhost --site mysite --user cmkadmin
----

[#push]
==== Hosts im Push-Modus

Sollen Hosts überwacht werden, die hinter einer Firewall nicht direkt vom {CMK}-Server erreicht werden können, ist oft der xref:glossar#push_mode[Push-Modus] der bevorzugte Kommunikationsweg.
Sie können den Push-Modus in den Eigenschaften des Hosts im Abschnitt xref:hosts_setup#monitoring_agents[Monitoring agents] mit der Option [.guihint]#{CMK} agent connection mode# auswählen. 
Alternativ können Sie den Push-Modus auch mit vorkonfigurierten Agentenpaketen für die xref:hosts_autoregister#[Autoregistrierung] kombinieren und so den Komfort weiter erhöhen.

[#update]
=== {CMK} aktualisieren

Prüfen Sie die link:https://checkmk.com/de/download?method=cmk&edition=cce&version=2.2.0&platform=ubuntu&os=jammy&type=cmk[Download-Seite^] regelmäßig auf Updates und laden Sie das aktualisierte Paket mit dem dort angezeigten `wget` Kommando herunter.

Die xref:update#[Installation eines Updates] erfolgt in zwei Schritten, was darin begründet liegt, dass mit `omd` verschiedene Instanzen mit verschiedenen Versionen von {CMK} auf einem Server laufen können.

[#install_new]
==== Neue {CMK}-Version installieren und Instanz aktualisieren

Der erste Schritt ist die Installation des Paketes, im folgenden Beispiel die Version {v22}p2:

[{shell}]
----
{c-ubuntu} sudo apt install ./{pkg-cce}-2.2.0p2_0.jammy_amd64.deb
----

Der nächste Schritt ist das Update Ihrer Instanz(en):

[{shell}]
----
{c-ubuntu} sudo omd stop mysite
{c-ubuntu} sudo omd update mysite
{c-ubuntu} sudo omd start mysite
----

[#remove_old]
==== Nicht mehr benötigte Pakete entfernen

Falls Sie mehrere Instanzen auf dem Server nutzen (beispielsweise eine produktiv genutzte und eine für den Test von Erweiterungen), stellen Sie sicher, dass alle aktualisiert sind:

[{shell}]
----
{c-ubuntu} omd sites
SITE         VERSION       COMMENTS
mysite       2.2.0p2.cce   default version
mytestsite   2.2.0p2.cce   default version
----

Nicht mehr genutzte {CMK}-Versionen können Sie dann über das Ubuntu-Paketmanagement deinstallieren:

[{shell}]
----
{c-ubuntu} sudo apt purge {pkg-cce}-2.2.0p1
----
