// -*- coding: utf-8 -*-
// IGNORE
include::global_attr.adoc[]
= Monitor a server
:revdate: 2024-07-18
:title: Monitor a server
:description: To monitor servers and workstations, Checkmk provides for several operating systems its own agents which you can easily install on your hosts.


[#download]
== Download the agent

++++1. In the navigation bar on the left click *Setup > Agents > link:/pass:[$$SITE_NAME$$]/check_mk/index.py?start_url=%2Fpass:[$$SITE_NAME$$]%2Fcheck_mk%2Fwato.py%3Fmode%3Dagents[Windows, Linux, Solaris, AIX]*.

You find the agent packages prepared for _auto-registration_ to your Checkmk Cloud site in the *Agent controller auto-registration* row.
The Checkmk agent is available for Windows and the Unix-like operating systems Linux, Solaris and AIX.

++++2. In the *Agent controller auto-registration* row click the appropriate package for your host's operating system to download the file.


[#install]
== Install the agent

++++1. Install the agent package on the host you want to monitor.

Agent installation instructions for link:https://docs.checkmk.com/saas/en/agent_linux.html#install_package[Linux^] and link:https://docs.checkmk.com/saas/en/agent_windows.html#install_package[Windows^] are available in the Checkmk Cloud User Guide.

After installation the agent will automatically register itself at your Checkmk Cloud site.

++++2. Click *Setup > General > link:/pass:[$$SITE_NAME$$]/check_mk/index.py?start_url=%2Fpass:[$$SITE_NAME$$]%2Fcheck_mk%2Fwato.py%3Fmode%3Dauditlog[Audit log]* and select the *wato_audit.log* file to keep track of the incoming auto-registration messages.

After a couple of minutes the new host is present in the _configuration environment_ in the *link:/pass:[$$SITE_NAME$$]/check_mk/index.py?start_url=%2Fpass:[$$SITE_NAME$$]%2Fcheck_mk%2Fwato.py%3Ffolder%3Dpreconfigured_agent%26mode%3Dfolder[preconfigured_agent]* folder - and already in the _monitoring environment_ in *Monitor > Overview > link:/pass:[$$SITE_NAME$$]/check_mk/index.py?start_url=%2Fpass:[$$SITE_NAME$$]%2Fcheck_mk%2Fview.py%3Fview_name%3Dallhosts[All hosts]*.

This step concludes the Monitor a server topic.
If you would like to have the auto-registration topic described in more detail and with background information refer to the link:https://docs.checkmk.com/saas/en/hosts_autoregister.html[Checkmk Cloud User Guide^].
However, nearly all the individual steps described in the User Guide have been automatically applied for your convenience in Checkmk Cloud.
