// -*- coding: utf-8 -*-
// IGNORE
include::global_attr.adoc[]
= Server (Windows, Linux)
:revdate: 2024-08-29
:title: Monitor a server
:description: For monitoring servers and workstations, Checkmk provides its own agents, tailored for a range of operating systems, which you can easily install on your hosts.


[#download]
== Download the agent

++++1. In the navigation bar on the left click *Setup > Agents > link:wato.py?mode=agents["Windows, Linux, Solaris, AIX", window=main]*.

You can find the agent packages prepared for _auto-registration_ to your Checkmk Cloud site in the *Agent controller auto-registration* row.
The Checkmk agent is available for Windows and the Unix-like operating systems Linux, Solaris and AIX.

++++2. In the *Agent controller auto-registration* row click the appropriate package for your host's operating system to download the file.


[#install]
== Install the agent

++++1. Install the agent package on the host you want to monitor.

Agent installation instructions for link:https://docs.checkmk.com/saas/en/agent_linux.html#install_package[Linux^] and link:https://docs.checkmk.com/saas/en/agent_windows.html#install_package[Windows^] are available in the Checkmk Cloud User Guide.

Following installation the agent will automatically register itself at your Checkmk Cloud site.

++++2. Click *Setup > General > link:wato.py?mode=auditlog["Audit log", window=main]* and select the *wato_audit.log* file to keep track of the incoming auto-registration messages.

After a couple of minutes the new host will be present in the _configuration environment_ in the *link:wato.py?folder=preconfigured_agent&mode=folder["preconfigured_agent", window=main]* folder - and already in the _monitoring environment_ in *Monitor > Overview > link:view.py?view_name=allhosts["All hosts", window=main]*.

This step concludes the Monitor a server topic.
If you would like to have the auto-registration topic described in more detail and with background information refer to the link:https://docs.checkmk.com/saas/en/hosts_autoregister.html[Checkmk Cloud User Guide^].
However, nearly all of the individual steps described in the User Guide have been automatically applied for your convenience in Checkmk Cloud.
