// -*- coding: utf-8 -*-
// IGNORE
include::global_attr.adoc[]
= Virtualization platforms, Kubernetes, and storage solutions
:revdate: 2025-04-11
:title: Monitor virtualization platforms and storage solutions
:description: Systems that are not accessible from outside your network and are being monitored via a special agent, including virtualization platforms and storage solutions cannot currently be monitored in this version of our product. We are working on a solution to make these features available in Checkmk Cloud (SaaS).


[#monitoring_systems_in_private_networks_via_special_agent_is_not_rcommended]
== Monitoring systems in private networks via special agent is only possible by exposing them to the internet.

Systems that are not accessible from outside your network and are being monitored via a special agent, including virtualization platforms, storage solutions, cannot currently be monitored in this version of our product.

Exposing virtualization and storage solutions directly to the internet is not recommended because it makes them vulnerable to attacks like brute-force logins, ransomware, and exploits of unpatched vulnerabilities.

We are working on a solution to make these features available in Checkmk Cloud (SaaS).

Thank you for your understanding and patience as we enhance our product.
