// -*- coding: utf-8 -*-
// IGNORE
include::global_attr.adoc[]
= Configure check parameters for a service
:revdate: 2024-07-16
:title: Configure check parameters for a service
:description: To monitor services correctly, they require their parameters to be well-defined. How to set parameters for services is therefore explained here.


[#prerequisites]
== Prerequisites

You have already created the hosts and discovered their services.
The related check plug-ins should now be set to meet your needs.
Many of the check plug-ins can be configured using parameters.
The most common practice is the setting of thresholds for WARN and CRIT.
For detailed information consult the link:https://docs.checkmk.com/master/en/wato_services.html#[Checkmk User Manual].  


[#set_parameters]
== Set parameters

As the available services depend on the hosts you are working with, we will be using an exmaple to decribe the general approach.
If we assume that you monitor a Unix system, you should have the _CPU load_ service in most cases.
 
The exact parameters a service eventually has can be found in the service's parameters page:

++++1. Open *Setup > Hosts > Hosts* from the menu on the left.

++++2. Click on the name of the desired host to open the _Properties of host_.

++++3. Choose the option *Save & run service discovery*.

++++4. Select the desired service, e.g. _CPU load_ and click on the bar chart symbol to open the next menu.

++++4. Click on *Add rule**.

++++5. Modify the *Value* to fit your needs. In our example, we decrease the _Levels on CPU load_ from the default settings.


SCREENSHOT

++++6. Click *Save*.

++++7. Don't forget to activate the changes.


[#priorities]
== Parameter priorities

Every plug-in has a *_Default value_* for the parameter.
Parameters from rules have priority over those set by a discovery, and these in turn have priority over default values.
For complex parameters in which individual sub-parameters are set using check boxes (as with temperature for example), these priority-rules apply separately for each sub-parameter.
So, if you set only one sub-parameter via rules, the others retain their respective default values.
In this way you can, for example, activate the trend calculation of the temperatures with one rule, and with another rule set the temperature threshold value for a physical sensor device.
The complete parameter set will then be composed from both rules.


[#show_parameters]
== Make the parameters visible

To see the parameters from all services directly in the service table, click *Display > Details > Show check parameters* in the menu bar.
