// -*- coding: utf-8 -*-
// IGNORE
include::global_attr_onboarding.adoc[]
= Adding your first host
:revdate: 2024-10-14
:title: Adding your first host
:description: Add your first host to Checkmk.


[#register]
== Your agent registers with your site

The auto-registration of the installed agent might take a few minutes.

Once the registration is finished the host will automatically appear on the *All hosts* page that you are currently on.

In case you installed the agent on a Linux workstation you can check the status of the registration with this command `sudo cmk-agent-ctl status`.

In case you installed the agent on a Windows workstation you can check the status of the registration with this command in PowerShell `& 'C:\Program Files (x86)\checkmk\service\cmk-agent-ctl.exe' status`.
You can check the status of the registration with the  command  the workstation you installed the agent on.


[#configure]
== Configure a notification for your host

Congratulations you have successfully set up your first host!

In a next step you might want to set up a notification for your host. In Checkmk, notification means that users are actively informed in the case of problems or other events in the monitoring.