// -*- coding: utf-8 -*-
// IGNORE 
// NONASCII 
include::global_attr.adoc[]
= The AI policy for the {CMK} User Guide 
:title: The AI policy for the {CMK} User Guide
:description: The official {CMK} User Guide is written and maintained by skilled human technical writers. Read here how AI/LLMs are used to maintain the User Guide.

[#introduction]
== Introduction

The purpose of this policy is to describe the extent to which AI ("artificial intelligence") or LLM ("large language model") tools are used to maintain the official {CMK} User Guide.

The team responsible for keeping the User Guide up to date is committed to providing accurate, concise, relevant, and comprehensive information to readers, and will always prioritize this goal.

[#quality]
== Fully-human quality control

The {CMK} User Guide is authored and maintained by a team of highly-skilled technical writers with qualifications in various subject areas, including computer science, journalism, interdisciplinary communication, information science, linguistics, natural language processing, software engineering, information technology, didactics, pedagogy, and storytelling.
All User Guide article updates, including translations between German and English, go through a review process with at least one team member.
We only publish texts that we believe to be accurate, relevant, and readable for our audience of human readers.

The production of User Guide text follows a "human-first" process, and only involves AI text generation sparingly and experimentally.
When an article update is drafted with the help of AI, we strictly apply our established review process to prevent subpar texts from being published.
We do not mark any texts as being "AI-generated", because we never allow AI-generated text to be published without a quality control step performed by at least one human.

User Guide articles in languages other than German and English are translated automatically, using tools that may rely on LLMs.
We explicitly label all automatically-translated texts.
If you are unsure about the accuracy of an automatic translation, we recommend consulting the German or English version of that article.

[#tools]
== Tool use
=== Deterministic quality checks

We use a set of automated, rule-based, deterministic checks to ensure adherence to certain structural and stylistic guidelines.
We do not use AI tools in this part of our workflow, nor do we plan to introduce them in this context.

=== Fact-checking with AI/LLMs

We may employ state-of-the-art AI/LLM tools in the research process that precedes changes to text passages on specific topics in the User Guide.
In this context, the purpose of the AI tool is to verify items against multiple internal and external sources and to identify gaps and mismatches.
Our writers personally investigate the relevant sources and determine how to present the topic at hand in the User Guide.
Decisions on which details to include or exclude in an article are never made by an AI tool without human verification.

[#access]
== Accessing the User Guide via AI/LLM tools

If you use AI/LLM tools in your workflow, those tools may present quoted or synthesized information from the official {CMK} User Guide to you.
The User Guide team has no control over the accuracy or quality of such extracts and summaries, and takes no responsibility whatsoever for claims made by such third-party applications.
We recommend to always check the referenced articles as the primary sources.

{CMK} provides its own AI chatbot at link:https://chat.checkmk.com/[chat.checkmk.com^].
Feedback can be provided directly on the chatbot page.

[#summary]
== Summary

The full responsibility for the contents of the official {CMK} User Guide lies strictly with our team of human technical writers.
We may use state-of-the-art AI/LLM tools to aid specific steps of our process.
We do not publish unchecked AI-generated text in the User Guide.
