// -*- coding: utf-8 -*-
// IGNORE Nuvola Vignoni
include::global_attr.adoc[]
= Copyright information
:revdate: 2017-06-22
:title: Copyright information
:description: Notes to the rights of texts and graphics in the {CMK} User guide
:no-toc:

This User Guide is copyright protected.
The rights to all texts and graphics remain the property of {comfull}.

The source of some of the included icons is the link:https://en.wikipedia.org/wiki/Nuvola[Nuvola^] icon set from David Vignoni which are provided under the link:https://www.gnu.org/licenses/old-licenses/lgpl-2.1.de.html[LGPL Version 2.1^].
For these the following license is valid:

_This library is free software;
you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation;
either version 2.1 of the License, or (at your option) any later version. +
This library is distributed in the hope that it will be useful, but without any warranty;
without even the implied warranty of merchantability or fitness for a particular purpose.
See the GNU Lesser General Public License for more details._

// Details concerning the icons from David Vignoni can be found link:http://www.icon-king.com/projects/nuvola/[here^].
