// -*- coding: utf-8 -*-
// IGNORE TNSALIASes oic OIC
// NONASCII │ ├ └ ─  …​
include::global_attr.adoc[]
= Monitoring Oracle databases
:title: Monitoring Oracle databases
:description: With the agent plug-in for Windows, Linux, Solaris and AIX you can fully monitor Oracle databases. Details about the configuration can be found here.

{related-start}
xref:wato_monitoringagents#[Monitoring agents]
xref:agent_linux#[Monitoring Linux]
xref:agent_windows#[Monitoring Windows]
link:https://checkmk.com/integrations[Catalog of check plug-ins]
{related-end}

[#introduction]
== Introduction

In this article, you will learn how to monitor Oracle databases using the new agent plug-in `mk-oracle`.

If you are looking for information about the old agent plug-in `mk_oracle`, please see link:https://docs.checkmk.com/2.4.0/de/monitoring_oracle.html[article in the 2.4.0 branch of the User Guide].

[#how]
== How does Oracle monitoring work with {CMK}?

To monitor Oracle instances and databases with {CMK}, you must install the {CMK} agent and the `mk-oracle` agent plug-in on the respective host.
The agent plug-in requires a configuration file, which you must save as `mk-oracle.yml` in the xref:glossar#dir_conf[configuration directory].
In addition, the agent plug-in relies on libraries from the Oracle Instant Client (OIC).
Therefore, the OIC must also be available on the host.

You will find instructions for all these requirements in this article and throughout the rest of the User Guide.

To learn how to install the Oracle Instant Client (OIC) in various scenarios, see chapter the xref:install_oic[install oic].

We explain how {CRE} users can install an agent plug-in in the chapters xref:agent_linux#plug-ins[Extending the agent with plug-ins (Linux)] and xref:agent_windows#plug-ins[Extending the agent with plug-ins (Windows)].

Users of the commercial editions of {CMK} will find an explanation of the most important options in the chapter xref:bakery[Creating a Configuration for the Agent plug-in].
In the chapter xref:reference[reference] of this article, we will go over all the xref:options_ruleset[all options of the rule set [.guihint]#Unified Oracle plug-in#] again and also show which entries each option corresponds to in the `mk-oracle.yml` configuration file.

For anyone who wants to try out the new agent plug-in in an Oracle test instance, we offer this short tutorial: xref:tutorial_monitoring_oracle_01[Monitor All Oracle Databases on a Single Host].

[#prerequisites]
== Setting Up prerequisites on the Oracle host

On each host where you want to monitor Oracle databases or instances, you must set up two prerequisites.

. The Oracle Instant Client must be made available to the agent plug-in.
For instructions on how to do this, see the xref:install_oic[relevant chapter].
. The agent plug-in must be granted access to your Oracle instances or databases.

There are several ways to grant the `mk-oracle` agent plug-in access to the instances and databases.

You can create a user and password on the host that is used exclusively for monitoring by {CMK}.
We explain this method in the chapter xref:create_user[Create a database user].

Alternatively, you can use the xref:oracle_wallet[Oracle Wallet].

[#install_oic]
=== Deploying Oracle Instant Client (OIC)
The `mk-oracle` agent plug-in requires the Oracle Instant Client (OIC) libraries to function.
You have three options for making OIC available.

You can install OIC xref:#install_oic_exclusively[exclusively for the agent plug-in].
This is the method we recommend.

Alternatively, you can install OIC xref:#install_oic_globally[globally on the host].

If OIC is already installed on the host and you want to use this installation for monitoring via {CMK}, you can simply tell the agent plug-in where to find OIC.


[#install_oic_exclusively]
==== Install OIC exclusively for the agent (recommended)

//SK: A sentence explaining why this chapter is necessary needs to be added here.

First, download the package appropriate for your host from the page link:https://www.oracle.com/de/database/technologies/instant-client/downloads.html[Oracle Instant Client Downloads] in ZIP format.


[.tabs]
====
[#tab_linux]#Linux#::
+
--
For a Linux x86-64 system, for example, use the link:https://download.oracle.com/otn_software/linux/instantclient/2326200v2/instantclient-basiclite-linux.x64-23.26.2.0.0.zip[Basic Light Package (ZIP)].

Check the name of the {CMK} agent's plug-in directory on your host:

[{shell}]
----
{c-local} sudo check_mk_agent | grep "^pluginsdir " | head -1
pluginsdir /usr/lib/check_mk_agent/plugins
----

Unzip the archive file into that very plug-in directory:

[{shell}]
----
{c-local} sudo unzip -j instantclient-basiclite-linux.x64-23.26.2.0.0 -d /path/to/agent/plugins/packages/mk-oracle
----

////
Please install Oracle Instant Client so that only the admin user has write access.
SK: Figure out what the above means.

Something like this?
sudo chmod go-w /path/to/agent/plugins/packages/mk-oracle/*
////


--
////
[#tab_windows]#Windows#::
+
--
For Windows...


--
////
====


[#install_oic_globally]
==== Install OIC globally

Instructions to follow.


[#create_user]
=== Create a database user

First, connect to your Oracle host and switch to the `oracle` user.

[{shell}]
----
{c-root} su - oracle
----

Finally, specify the instance to which `sqlplus` should connect:

[{shell}]
----
oracle@linux$ export ORACLE_SID=MYINST1
----

Start `sqlplus`.
Specify the role with which `sqlplus` should start.

[{shell}]
----
oracle@linux$ sqlplus / as sysdba
----

Now create a user that will be used exclusively for monitoring Oracle.
The prefix `C##` ensures that the user can view all databases in the instance.
The privileges apply to all existing and future databases.

[{sql}]
----
sqlplus> create user C##checkmk identified by myPassword;
sqlplus> alter user C##checkmk set container_data=all container=current;
sqlplus> grant select_catalog_role to C##checkmk container=all;
sqlplus> grant create session to C##checkmk container=all;
sqlplus> exit
----


[#oracle_wallet]
=== Using the Oracle Wallet

As an alternative to specifying the user directly and with a password in a configuration file, you can also use the _Oracle Wallet_.
This has the advantage that you no longer need to store the access data in an unencrypted form on the {CMK} server and on the Oracle host.
So even if you have defined the configuration file's access rights on the Oracle host to suit, the access data has nevertheless left the server and is located on the {CMK} server as long as you use the xref:bakery[Agent Bakery].

The Oracle Wallet in turn stores the encrypted access data on the host to be monitored so that they can only be used, but no login data has to be made known explicitly.
{CMK} can thus use this wallet so that the access data needs only be known to the database administrator (DBA).
To do this, you--or the DBA--create a wallet on the relevant server and store it in the xref:glossar#dir_conf [configuration directory] in a file named `oracle_wallet`.

[{shell}]
----
{c-root} mkstore -wrl /etc/check_mk/oracle_wallet -create
----

The agent plug-in will access this file later whenever a connection to an instance is to be established.
So that the necessary user data can also be found, you must enter this once in the wallet.
In the following example you thus add the user `checkmk` for the instance `MYINST1`:

[{shell}]
----
{c-root} mkstore -wrl /etc/check_mk/oracle_wallet -createCredential MYINST1 checkmk myPassword
----

For the agent plug-in to know where to look for the wallet, it must find two files.
The first file is `sqlnet.ora` in which the info for the wallet's location can be found. 
The second file -- `tnsnames.ora` -- defines the address of the instance so that it can also be addressed via its xref:tns_config[alias].
So that the agent plug-in can access these files you can specify the path under Linux, Solaris and AIX using the environment variable xref:tns_config[`TNS_ADMIN`].
This is especially useful if the files already exist.
Alternatively, you can create them explicitly.
Windows even requires that you specify them manually.

First create the `sqlnet.ora` file.
The agent plug-in alternatively searches in this file for the login data, so the correct file path to the wallet file you just created must be entered here.
Make sure that you set the `SQLNET.WALLET_OVERRIDE` parameter to `TRUE`:

./etc/check_mk/sqlnet.ora
[{file}]
----
LOG_DIRECTORY_CLIENT = /var/log/check_mk/oracle_client
DIAG_ADR_ENABLED = OFF

SQLNET.WALLET_OVERRIDE = TRUE
WALLET_LOCATION =
 (SOURCE=
   (METHOD = FILE)
   (METHOD_DATA = (DIRECTORY=/etc/check_mk/oracle_wallet))
 )
----

Now the plug-in knows which credentials should be used.
So that it also accesses the correct address, create `tnsnames.ora` as the second file.
The exact syntax can be found in the Oracle documentation, but as an example the file could look like this:

./etc/check_mk/tnsnames.ora
[{file}]
----
MYINST1
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = MYINST1_ALIAS)
    )
  )
----

With this step you have created the prerequisites for removing the access data from the xref:user_config[agent plug-in's configuration file].
Instead of the access data, you simply enter a `/` (slash):

./etc/check_mk/mk_oracle.cfg
[{file}]
----
DBUSER='/:'
----

You can of course add further access data to the wallet at a later date.
The `tnsnames.ora` file must then simply be amended as necessary.

Finally, change the permissions of the files and directories created manually in this section so that xref:access[access rights on execution] are correctly set.
The agent plug-in executed as `root` will switch to the owner of the Oracle binaries (such as `$ORACLE_HOME/bin/sqlplus`) before executing them.
As a minimum, the group of the owner of the Oracle binaries therefore needs read access to the manually created files in `/etc/check_mk/`.
In the following example, we assume that the group is `oinstall`.

The following commands change the group to `oinstall`:

[{shell}]
----
{c-root} chgrp oinstall /etc/check_mk/sqlnet.ora /etc/check_mk/tnsnames.ora
{c-root} chgrp -R oinstall /etc/check_mk/oracle_wallet
----

These commands then ensure that the group can read the `oracle_wallet` directory and its contents:

[{shell}]
----
{c-root} chmod g+x /etc/check_mk/oracle_wallet
{c-root} chmod -R g+r /etc/check_mk/oracle_wallet
----

The permissions should then look something like this:

[{shell}]
----
{c-root} tree -ugpR /etc/check_mk
[drwxr-xr-x root     root    ]  /etc/check_mk
├── [drwxr-x--- root   oinstall ]  oracle_wallet
│   └── [-rw-r----- root   oinstall ]  cwallet.sso
│   └── [-rw-r----- root   oinstall ]  cwallet.sso.lck
│   └── [-rw-r----- root   oinstall ]  ewallet.p12
│   └── [-rw-r----- root   oinstall ]  ewallet.p12.lck
├── [-rw-r--r-- root   oinstall ]  sqlnet.ora
├── [-rw-r--r-- root   oinstall ]  tnsnames.ora
----

The command output only shows the files and directories in question.


[#configuration_bakery]
== Create a rule for the minimum configuration of the agent plug-in
{cee-only}

If you are using a commercial edition of {CMK}, search for the rule set [.guihint]#Unified Oracle Plugin (Experimental)# and create a new rule there.

Depending on which approach you chose in the chapter xref:prerequisites[Setting Up Prerequisites on the Oracle Host], select the appropriate option under [.guihint]#Authentication type# and enter the relevant data.

In the [.guihint]#Conditions# section, use [.guihint]#Explicit hosts# to restrict the rule to the host on which Oracle is running.

Now save the rule, xref:wato_monitoringagents#bakery[build the new agent package], and install it on the Oracle host.

The configuration file generated by this minimal configuration can be found in the section xref:minimal_configuration[References].

All other options for the rule [.guihint]#Unified Oracle Plugin (Experimental)# are currently described exclusively in the chapter xref:reference[References].


//SK: I would like to create a how-to guide for the manual setup.
[#manual_configuration]
== Setting Up Oracle Monitoring Manually

Instructions to follow.
//SK In this how-to, we describe how to set up Oracle databases without using agents.



[#reference]
== References

[#options_ruleset]
=== Options in the [.guihint]#Unified Oracle Plugin# ruleset

In this chapter, we explain all the options that users of a commercial edition will find in the [.guihint]#Unified Oracle Plugin (Beta)# ruleset.
The explanations in this manual sometimes go beyond the content of the inline help, for example, when there is interesting background information about an option or when a more detailed explanation is appropriate for specific use cases.

We also specify which entry is created in the `mk-oracle.yml` configuration file as a result of a selected option.

Users of {CRE} and anyone else interested can find a description of all options in `mk-oracle.yml` in our link:https://github.com/Checkmk/checkmk/tree/master/packages/mk-oracle#yaml-configuration[description on GitHub].

// Explanations of the options are still to follow here. Why, for example, would users want to limit `max_connections`, etc.?


