// -*- coding: utf-8 -*-
// IGNORE Codec Logfile Precompile logfile logfiles pre
// NONASCII
include::global_attr.adoc[]
= Monitoring log files
:title: Monitoring log files
:description: In {CMK} you can monitor log files using the agent plug-in logwatch. Here you will learn how to set up the monitoring.

{related-start}
xref:mk_filestats#[Monitoring files]
ifdef::onprem[]
xref:ec#[The Event Console]
endif::[]
{related-end}


[#basics]
== Essentials for monitoring log files

The history of log file monitoring is a history full of misunderstandings.
The misunderstandings already begin when we look at what log entries are and what, on the other hand, the services running under {CMK} display.
Lines or entries in log files are 'by nature' event based. {CMK}, on the other hand, displays states.
Read more about the difference between events and states in the xref:monitoring_basics#states_events[Basic principles of monitoring with {CMK}] article.

In {CMK} we circumvent this problem by defining when a service that maps one or more log files assumes a critical state.
As a rule, we define 'become critical' when the log file contains messages that are

* new,

* not acknowledged, and

* critical.

In {CMK}, our agent plug-in `mk_logwatch.py` (commonly referred to as "logwatch") is responsible for this task.

You should generally use moderation when using logwatch.
Logwatch is suitable for limited use and not for processing gigabytes or terabytes of log files.
There are certainly more suitable tools for this.
We strongly recommend using logwatch only on an ad hoc basis and not routinely.
As you will see later in this article, it is easy to carry out an major part of the pre-filtering on the monitored host.


[#prerequisites]
== Prerequisites

Logwatch is a Python program and therefore requires a Python environment on the host.
Python will already be installed in most Linux distributions and Solaris has also included Python 3.x for some time.
// This block is new
// start translation
////
Auf AIX-Systemen ist Python ab Version 7.3 vorinstalliert -- wenn die Installation in Ihrer spezifischen Umgebung fehlt, können Sie sie mit dem Paketmanager Ihrer Wahl selbst durchführen.
////
// end translation
If you want to monitor log files on a Windows host, there are various ways of achieving this.

ifdef::onprem[]
{cee-only}
Users of our commercial editions
endif::[]
ifdef::saas[]
Users of {CE}
endif::[]
can configure logwatch conveniently via the GUI and, using the Agent Bakery, have the plug-in inserted into the agent package.
As soon as {CMK} notices that you are configuring a Python-based agent plug-in for a Windows host, the agent will also be given a virtual Python environment (`venv`).

ifdef::onprem[]
If you are using one of our commercial editions but not the Agent Bakery, consult the following section for your Windows hosts.


[#python_windows]
=== Python for Windows in {RE}

[#install_python_venv]
==== Installing {CMK} Python (`venv`)

The installation package for the Windows agent from {RE} does not contain a Python environment.
However, a corresponding cabinet file is already available on your {CMK} server.
You can find this file called `python-3.cab` in the directory `~/share/check_mk/agents/windows` or in {CMK} via [.guihint]#Setup > Agents > Windows > Windows agent#.
Copy this file to your Windows host in the directory `C:\Program Files (x86)\checkmk\service\install`.
There is already a file with this name and a file size of 0 byte.
You must overwrite this file with the version from the {CMK} server.
Then restart the {CMK} agent service.
In Windows PowerShell with administrator rights, you can do this with the following command:

[{shell}]
----
net stop checkmkservice; net start checkmkservice
----

Once the Windows service has been restarted, the virtual Python environment will have been automatically installed.


[#install_full_python]
==== Installing a complete Python

Alternatively, you can also download and install a current Python package from link:https://www.python.org/[python.org^].
Make sure to activate the following options during installation:

* [.guihint]#Install Python 3.x for all users#. This will also automatically activate the [.guihint]#Precompile standard library# option, which is a good thing.
* [.guihint]#Add Python to environment variables#

If you want to start testing immediately after installing Python, it is essential to restart the `checkmkservice` either via the Windows Task Manager or with the commands specified above, otherwise the service will not know about the new environment variables.
endif::[]


[#monitor_logfiles]
== Monitoring log files

[#installation]
=== Installation on the host

Start by installing the agent plug-in.
ifdef::onprem[]
To do this, copy the file `~/share/check_mk/agents/plugins/mk_logwatch.py` from your {CMK} server to the host in the directory `/usr/lib/check_mk_agent/plugins/` (Linux) or `C:\ProgramData\checkmk\agent\plugins` (Windows).
endif::[]
ifdef::saas[]
To do so, first download the plug-in `mk_logwatch.py` from [.guihint]#Setup > Agents > Windows, Linux, Solaris, AIX > Related#.
Copy this file to the host into the directory `/usr/lib/check_mk_agent/plugins/` (Linux) or `C:\ProgramData\checkmk\agent\plugins` (Windows).
endif::[]
Make sure that the file is executable on the host.
Further information on this step can be found in the section "Manual installation" in the articles xref:agent_linux#manualplugins[Monitoring Linux] and xref:agent_windows#manual_installation_of_plugins[Monitoring Windows].

ifdef::onprem[]
{cee-only}
Users of our commercial editions
endif::[]
ifdef::saas[]
Users of {CE}
endif::[]
can select [.guihint]#Text log files (Windows, Linux, Solaris, AIX)# during xref:configuration[Configuration of the rule] [.guihint]#Deploy the Logwatch plug-in and its configuration# to automatically deploy the agent plug-in with the agent.


[#configuration]
=== Configuring logwatch

In line with the initial considerations, logwatch will not monitor anything without being configured.
Therefore, after installing the agent plug-in, it is essential to create a configuration file for the host to be monitored.


[#configuration_bakery]
==== Configuration via the Agent Bakery

ifdef::onprem[]
{cee-only}
In the commercial editions, first
endif::[]
ifdef::saas[]
First
endif::[]
call up the rule for the agent plug-in [.guihint]#Setup > Agents > Windows, Linux, Solaris, AIX > Agent rules > Text log files (Windows, Linux, Solaris, AIX)#.
The default setting [.guihint]#Deploy the Logwatch plug-in and its configuration# should normally be left as it is.
However, if you want or need to transfer the configuration file `logwatch.cfg` to the host in a different way, the [.guihint]#Deploy the Logwatch plug-in without configuration# option is still available here.

Continue with the option [.guihint]#Retention period#.
The default setting here is one minute, which also corresponds to the preset check interval in {CMK}.
This value should always be at least equal to the check interval.
This option is primarily responsible for ensuring that no log messages are lost due to a service detection or the manual execution of `cmk -d myhost`.
Further details can be found in the inline help for the option and in the link:https://checkmk.com/werk/14451[Werk #14451^] with which this option was introduced.

Now comes the section of the rule where things really get going -- [.guihint]#Configure a log file section#.
We will start directly with the biggest stumbling block of recent years.
In the [.guihint]#Patterns for log files to monitor (allowing * and ?)# field, you will need to specify the log files that you want to monitor.
You can do this individually and explicitly or with so-called glob patterns (glob for short).
We are using the Python module `glob` here, for which there is a link:https://docs.python.org/3/library/glob.html[detailed documentation^] on docs.python.org.
However, we would like to provide you with a few helpful examples right here.

For example, if you enter `/var/log/my.log` here, logwatch will monitor just this single log file.
If you instead enter `pass:[/var/log/*log]` here, logwatch will monitor all files that end with the character string `log` and which are located *directly* in the `/var/log` directory.
If you want to monitor log files in all direct subdirectories of `/var/`, you can do this with the following glob, for example: `pass:[/var/*/*log]`.
We explicitly *do not* offer the glob `pass:[**]` for recursively searching a directory structure here, because we would end up with far too large a hit list far too quickly and leave the actual purpose of logwatch behind us.

The following table gives you a few more helpful examples of how you can use globs to actually monitor the files that require monitoring without having to specify them all individually:

[cols=3,options="header"]
|===
|Glob Pattern |Explanation |Example
|`/var/log/*` | All files in `/var/log`. | `/var/log/mylog` `/var/log/my.log`
|`pass:[/var/log/*/*]`| All files in all direct subdirectories of `/var/log/`. | `/var/log/foo/mylog` `/var/log/bar/mylog`
|`/var/log/mylog?.log` | All files in `/var/log` where the name begins with `mylog`, followed by a singe character and ending in `.log`. | `/var/log/mylog1.log` `/var/log/mylog9.log`
|`/var/log/mylog[123].log`| All files in `/var/log` where the name begins with `mylog`, followed by either a `1`, `2` or `3` and ending in `.log`. | `/var/log/mylog1.log` `/var/log/mylog3.log`
|===

So when it comes to which files are 'matched' in the *first* step, we use *no* regular expressions and this may be enough for you to reach all the files you want.

However, if you now need to filter further, you can use the [.guihint]#Regular expression for log file filtering# option to apply regular expressions to the hits from *step 1* in a second step.

If you have collected all files `/var/log/*` and its direct subdirectories in the first step with `/var/log/*` and `pass:[/var/log/*/*]`, you could use the regular expression `error.log$|err$` to reduce the hit list to all files that end with `err.log` or `err`.
Caution: The 'dot' (.) is again now an arbitrary character.
This could, for example, leave the files `/var/log/apache2/error.log`, `/var/log/mail.err` and `/var/log/cups/error_log`.

As you can see, we have already provided you with two good and powerful tools for selecting the files to be monitored, so that logwatch can also check the other parameters and contents very quickly in the next step using a manageable file list.
You can deepen your knowledge of the latter in the xref:regexes#[Regular expressions in {CMK}] article.

With the [.guihint]#Restrict the length of the lines# option you can instruct logwatch to truncate excessively long lines after the specified number of characters.

The following option [.guihint]#Watch the total size of the log file# is useful for recognizing a defective log rotation.
If you set 100 MiB here, you will receive a warning each time a particular log file has exceeded the specified size again.

The maximum number of lines that logwatch checks per run and file can be restricted with [.guihint]#Restrict number of processed messages per cycle# and with [.guihint]#Restrict runtime of log file parsing# you can ensure that logwatch does not spend too long on a single file that may have been flooded with thousands and thousands of new entries since the last check.

If you activate one of the latter two options, you must also specify what should happen if the specified limit is exceeded.
With our default setting, the associated service becomes critical and you receive a message that lines have been skipped or that the maximum runtime has been exceeded.

[.guihint]#Handling of context messages# is an option with which the volume of transferred data *can* become very large very quickly.
So think carefully about whether only the log message that you think should generate a {CRIT} or {WARN} is important to you, or whether *all* lines that have been added since the last run of logwatch should be transferred to the {CMK} server.
For small log files that only grow by a few lines every minute, the setting [.guihint]#Do transfer context# is certainly unproblematic.
However, if 50 log files are monitored on a host, which suddenly contain 100,000 new lines with a length of 500 characters, we are already in the gigabyte range.
In such an event, it may be enough to see that a large number of new messages have been added since the last check in order to initiate a check directly on the host concerned.

If you do need the context -- i.e. the lines before and after the log message that is important to you -- you can limit this to a certain number of lines before and after with the option [.guihint]#Limit the amount of context data sent to the monitoring server#.

With [.guihint]#Limit the amount of data sent to the monitoring server# you can limit the size of the transferred data in general.

[.guihint]#Process new log files from the beginning# is switched off by default.
This sometimes leads to astonishment, because logwatch does not 'recognize' problems that are in log files and pass these on to the {CMK} server.
In our opinion, nothing is older than yesterday's newspaper and so are the log messages that were already in a log file *before the first run* of logwatch.
During this very first run, logwatch does nothing more than note how many lines are already contained in the respective log.
Only during the second run are the files checked for their content -- i.e. the newly added lines.

Logwatch relies on actually being able to read the log files.
Under the hood, logwatch goes to great lengths to recognize the coding of each log file.
However, character encodings that are too exotic can lead to problems.
If you can specify the character encoding of the monitored log files, UTF-8 is a very good choice.
Otherwise, you can use the option [.guihint]#Character encoding that should be used to decode the matching files# to explicitly inform logwatch about the encoding that is expected in the given log files.
The _output_ of logwatch is always encoded in UTF-8--if a conversion is necessary, logwatch will perform it with reference to the encoding you specified.

With [.guihint]#Duplicated messages management#, if you activate this option, you can again save a bit of bandwidth, and the subsequent output in {CMK} will also be more readable.
If you activate [.guihint]#Filter out consecutive duplicated messages in the agent output#, logwatch counts how often a line was repeated and writes this accordingly in the output instead of repeating the lines.

Finally, the lines in the log files that are of interest to you are now described using one or more regular expressions, and assigned a state.
Each line of a log file that is being evaluated will be checked against each of the given regular expressions in order from top to bottom until a match is found.
When a match is found, the corresponding state is assigned and the evaluation continues with the next line.

If you want every line containing the word `panic` to lead to a {CRIT} in {CMK}, it is sufficient to enter `panic` in the [.guihint]#Pattern(Regex)# field after clicking on [.guihint]#Add message pattern# below [.guihint]#Regular expressions for message classification#.
// This block is new
// start translation
////
Die Zuweisung zum Zustand {CRIT} ist beim Anlegen eines neuen Eintrags vorausgewählt.
Um die Zeilen, die den von Ihnen angegebenen regulären Ausdrücken entsprechen, anders zuzuordnen, stehen hier noch weitere Auswahlmöglichkeiten zur Verfügung:

* [.guihint]#WARNING#: Statt {CRIT} können die betroffenen Zeilen den Zustand {WARN} auslösen.
* [.guihint]#OK#: Diese Option mag auf den ersten Blick verwirren.
Sie dient dazu, Zeilen aus einer Log-Datei erstmal an den {CMK}-Server zu übertragen, um dann dort erst die endgültige Klassifizierung vorzunehmen.
* [.guihint]#IGNORE#: Die betroffenen Zeilen werden sofort verworfen.
Diese Option können Sie verwenden, um bestimmte Zeilen, die ansonsten auf einen anderen regulären Ausdruck weiter unten in der Liste passen würden, auszusortieren.

Zusätzlich zu den Zuständen, die für einzelne Zeilen ausgelöst werden können, gibt es noch Optionen, um Zeilen umzuschreiben oder zusammenzufassen.
Diese Optionen erscheinen ebenfalls im Drop-down-Menü [.guihint]#State#.

* [.guihint]#REWRITE#: Diese Option lässt Sie eine Zeile umschreiben, die auf einen in der Liste direkt davor stehenden regulären Ausdruck mit Zustandszuweisung passt.
Für einen solchen Umbau einer Zeile bietet es sich an, mit xref:regexes#matchgroups[Match-Gruppen] zu arbeiten.
* [.guihint]#APPEND#: Hiermit können Sie mehrere aufeinanderfolgende Zeilen zu einer einzigen Meldung zusammenfassen -- etwa um mehrzeilige Stack-Traces als eine zusammenhängende Meldung zu behandeln.
Achten Sie hierbei darauf, dass der eingegebene reguläre Ausdruck eines [.guihint]#APPEND#-Eintrags wirklich alle logisch zu einem Block gehörenden Zeilen beschreibt.

Bei Bedarf können Sie auch mehrere Einträge vom Typ [.guihint]#APPEND# oder [.guihint]#REWRITE# in Reihe schalten.
Diejenigen Zeilen, die zusammengefasst oder umgeschrieben wurden, werden von den regulären Ausdrücken anschließend nicht noch einmal separat verarbeitet.
Es geht also nach dem Zusammenkleben und/oder Umschreiben mit der nächsten Zeile weiter, die _nicht_ zum zuletzt gematchten Muster passt.

Die Option, Zeilen mit dem Zustand {OK} zur weiteren Verarbeitung an den {CMK}-Server weiterzuleiten, bringt uns zu einem wichtigen Punkt, der zeigt, wie flexibel Logwatch -- bei richtigem Einsatz -- sein kann.
////
// end translation

All of the options explained in this section become entries in the configuration file already mentioned, which is stored on the respective host.
If you now want to make changes to the classification of certain messages, you may first have to edit the rule, then bake the agent and install it.

Alternatively, you can first transfer all of the interesting messages to the {CMK} server (for example with the {OK} state), and then on the {CMK} server (re-)classify them with the [.guihint]#Log file patterns# rule.
In this way you can save yourself the trouble of baking and rolling out the new agent, and after customizing the above-mentioned rule accordingly, will need to -- onetime only -- quickly activate the changes.
You can find out exactly how to do this below in the chapter xref:logfile_patterns[Reclassifying with log file patterns].


[#configuration_manual]
==== Manual configuration

ifdef::onprem[]
{cre-only}
In the {CRE} you configure the agent plug-in as usual via a text file.
endif::[]
ifdef::saas[]
Alternatively you can configure the agent plug-in as usual via a text file.
This is for example helpful when testing various settings.
endif::[]
As a rule, logwatch searches for a file called `logwatch.cfg` in the directories `/etc/check_mk` (Linux) or `c:\ProgramData\checkmk\agent\config\` (Windows).
An (almost) minimal configuration could look like this:

./etc/check_mk/logwatch.cfg
[{file}]
----
"/var/log/my.log" overflow=C nocontext=True
 C a critical message
 W something that should only trigger a warning
----

First, always enter a glob pattern here, followed by all the options to be applied.
This is followed -- with an indentation of one space -- by a letter representing the desired state or function, and finally a regular expression that is compared with each line of the log file.
// This block replaces the following text
// start translation
////
Mit obiger Konfiguration würden alle neuen Zeilen, die seit dem letzten Durchlauf von Logwatch in die Datei `/var/log/my.log` hinzugefügt wurden, auf die beiden Muster `a critical message` und `something that should only trigger a warning` geprüft.
Wenn eine Zeile auf einen der regulären Ausdrücke passt, wird die gesamte Zeile zusammen mit dem definierten Zustand (z.B. {CRIT} für Zeilen, die mit `C` beginnen, und {WARN} für Zeilen, die mit `W` beginnen), an den {CMK}-Server übergeben.

Eine sehr umfangreiche Beispielkonfiguration finden Sie als Instanzbenutzer in der Datei `~/share/check_mk/agents/cfg_examples/logwatch.cfg`.
Diese Datei enthält auch Kommentare, die die Syntax und die Bedeutung der verschiedenen Buchstabenkürzel erklären.
////
// end translation
// delete from here
With the above configuration, all new lines that have been added to the file `/var/log/my.log` since the last run of logwatch would be checked for the two patterns, `a critical message` and `something that should only trigger a warning`.

You can find a very comprehensive example configuration applicable for a site user in the `~/share/check_mk/agents/cfg_examples/logwatch.cfg` file.
// delete to here

As all of the options that you can specify in such a configuration file have already been explained in the section xref:configuration_bakery[Configuration via the Agent Bakery], only a list and brief description follows here.
Refer to the above section for a detailed explanation.

[cols=4,options="header"]
|===
|Option in `logwatch.cfg` | Counterpart | Example | Remark
|`regex` |[.guihint]#Regular expression for log file filtering# |`regex='error.log$\|err$'` |
|`encoding` |[.guihint]#Character encoding that should be used to decode the matching files# |`encoding=utf-8` |
|`maxlines` |[.guihint]#Restrict number of processed messages per cycle# |`maxlines=500` |
|`maxtime` |[.guihint]#Restrict runtime of log file parsing# |`maxtime=23` |
|`overflow` |[.guihint]#In the case of an overflow...# |`overflow=W` | Case-insensitive processing of the given value
|`maxlinesize` |[.guihint]#Restrict the length of the lines# |`maxlinesize=123` |
|`maxoutputsize` |[.guihint]#Limit the amount of data sent to the monitoring server# |`maxoutputsize=10485760` |Size given in bytes
|`skipconsecutiveduplicated` |[.guihint]#Duplicated messages management# |`skipconsecutiveduplicated=True` |
|`nocontext` | [.guihint]#Handling of context messages# |`nocontext=True`|
|`maxcontextlines` |[.guihint]#Limit the amount of context data sent to the monitoring server# |`maxcontextlines=55,66` |
|===


[#logfile_grouping]
== Grouping of log files

The `logwatch` check belonging to the agent plug-in normally creates a separate service for each log file.
By defining groupings using the [.guihint]#Log file grouping# rule, you can switch to the `logwatch_groups` check.

Instructions for the usage of this rule can be found in the inline help.


[#logfile_patterns]
== Reclassifying with log file patterns

// This block replaces the following text
// start translation
////
Mit der Regel [.guihint]#Log file patterns# können Sie diejenigen Zeilen aus Log-Dateien, die Sie nicht vorher schon aussortiert haben, bei Bedarf umklassifizieren.
Auch diese Regel arbeitet mit regulären Ausdrücken.
Sie erlaubt eine beliebige Zuordnung von Zuständen, die Sie jeweils mit Bezug auf den Inhalt der Zeile und den ursprünglich von Logwatch gelieferten Zustand festlegen können.
Auch ein Kommentarfeld steht Ihnen hier zur Verfügung, damit Sie Hinweise oder Notizen zu den jeweiligen Meldungen hinterlegen können.

Hinweise zur Nutzung dieser Regel finden Sie in der Inline-Hilfe.
////
// end translation
// delete from here
This section will be added soon. Until then, consult the inline help of the rule [.guihint]#Logfile patterns#.
// delete to here


ifdef::onprem[]
[#ec]
== Forwarding to the Event Console

In addition to the direct processing of log messages in {CMK} and a possible reclassification with the [.guihint]#Log file patterns# rule, there is also the option of forwarding log lines obtained by logwatch to the xref:glossar#ec[Event Console].
This is done using the [.guihint]#Logwatch Event Console forwarding# rule, and is described in the xref:ec#logwatch[The Event Console] article.
endif::[]


[#monitoring]
== Logwatch in monitoring

In monitoring, the display differs depending on the check plug-in used.

If you use either `logwatch` or `logwatch_groups`, you will find - after the necessary service detection - one service per log file or per grouping of log files (see xref:logfile_grouping[Grouping of log files]) that begins with `Log`.
This is followed by the full path of the file or the group name.

If you forward your log messages to the Event Console, you will see one service per forwarding, depending on the setting of the rule [.guihint]#logwatch Event Console forwarding#, which informs you about the number of forwarded log messages.
In the case of bundled forwarding by the `logwatch_ec` plugin, this service is called [.guihint]#Log Forwarding#.
If you use the [.guihint]#Separate check# option and thus the `logwatch_ec_single` plugin, the service name also starts with `Log` followed by the path of the log file.
This service also informs you of the number of messages forwarded and if a log file cannot be read.

// This block is new
// start translation
////
Kann eine überwachte Log-Datei zwar gefunden, aber nicht gelesen werden (etwa wegen fehlender Berechtigungen), dann behandeln die Check-Plugins `logwatch` und `logwatch_ec` dies nicht wie eine fehlende Datei, sondern melden den betroffenen Service als {CRIT}.
ifdef::onprem[]
Für die Weiterleitung an die Event Console können Sie den Zustand bei nicht lesbaren Dateien über die Option [.guihint]#State if a log file cannot be read# in der Regel [.guihint]#Logwatch Event Console forwarding# festlegen.
endif::[]
////
// end translation

[#files]
== Files and directories

ifdef::onprem[]
All paths for the {CMK} server are specified relative to the instance directory (e.g. `/omd/sites/mysite`).
endif::[]

[cols="15,39,~",options="header"]
|===
|Location |Path |Meaning
ifdef::onprem[]
|{CMK} server |`~/share/check_mk/agents/cfg_examples/logwatch.cfg` |example configuration file
|{CMK} server |`~/share/check_mk/agents/plugins/mk_logwatch.py` |Python 3 agent plugin including explanations
|{CMK} server |`~/share/check_mk/agents/plugins/mk_logwatch_2.py` |Python 2 agent plugin including explanations
endif::[]
|Linux host |`/etc/check_mk/logwatch.cfg` |Configuration file - created by the Agent Bakery or manually
|Linux host |`/var/lib/check_mk_agent/logwatch.state.*` | State files of mk_logwatch
|Linux host |`/var/lib/check_mk_agent/logwatch-batches/*` | Location of the individual batches that mk_logwatch creates per query
|Windows host |`c:\ProgramData\checkmk\agent\config\logwatch.cfg` |Configuration file - created by the Agent Bakery or manually
|Windows host | `c:\ProgramData\checkmk\agent\state` | Storage location for the state files of mk_logwatch
|Windows host | `c:\ProgramData\checkmk\agent\state\logwatch-batches` | Storage location of the individual batches that mk_logwatch creates per query
|===
