// -*- coding: utf-8 -*-
// IGNORE SP7 Trixie
// SKIPCOMMITS 2025-09-19
include::global_attr.adoc[]
ifdef::onprem[]
= Release notes
:revdate: 2025-05-12
:title: Release notes - for {CMK} {current-major}
:description: {CMK} {current-major} works with a range of platforms and integrations supported during the product lifecycle's active maintenance.
endif::[]
ifdef::saas[]
= System requirements for {CE}
:revdate: 2025-02-17
:title: System requirements for {CE}
:description: {CE} works with a range of system environments supported during the product lifecycle. Read here which minimum requirements apply.
endif::[]

{related-start}
ifdef::onprem[]
xref:update_major#[Update to version {current-major}]
xref:update_matrix#[Update matrix for version {current-major}]
xref:install_packages#[Basic information on the installation of {CMK}]
endif::[]
xref:agent_linux#[Monitoring Linux]
xref:agent_windows#[Monitoring Windows]
{related-end}


== Introduction

ifdef::onprem[]
This document lists the platforms and integrations supported by {CMK} {current-major}.
Except for very specific reasons (e.g. security), these platforms, including all patch versions will remain supported through active maintenance during the {CMK} {current-major} product lifecycle.
endif::[]
ifdef::saas[]
This document lists the system environments supported by {CE}.
endif::[]


ifdef::onprem[]
[#os]
== Server OS

{CMK} can be installed on the following Linux server operating system distributions and versions, that run on x86_64 hardware.
To get a rough estimate of the hardware requirements, please visit link:https://checkmk.com/product/checkmk-system-requirements[the similarly named page within the {CMK} website^].
In this article you will find a complete list of supported operating systems and their versions.
Entries may contain the following additions:

* _Deprecated:_ LTS/LTSS versions marked in this way are still supported for the entire life cycle of version {current-major}. Support will be ceased afterwards.
* _Once released:_ Support for these versions is planned. {CMK} {current-major} packages will be made available shortly after the release of the new distribution version.

We will additionally evaluate any new versions of these distributions as a part of our ongoing support process.
These will be covered in the xref:update_matrix#[update matrix].

[cols="33,~,~",options=header]
|===
|Operating system |Supported versions | Supported since {CMK} version
|Debian |11 Bullseye (deprecated) | {v24}
| |12 Bookworm | {v24}
| |13 Trixie | {v24}p16
|Red Hat Enterprise Linux |8 | {v24}
| |9 | {v24}
| |10 | {v24}p16
|SUSE Linux Enterprise Server |15 SP3 (deprecated) | {v24}
| |15 SP4 (deprecated) |{v24}
| |15 SP5 | {v24}
| |15 SP6 | {v24}
| |15 SP7 | {v24}p16
| |16 | (once released)
|Ubuntu |22.04 LTS Jammy Jellyfish | {v24}
| |24.04 LTS Noble Numbat | {v24}
| |26.04 LTS Resolute Raccoon | (once released)
|===
endif::[]


[#browser]
== Browser

The {CMK} user interface has been verified as able to be run on the following desktop browsers and minimum versions:

ifdef::onprem[]
* Google Chrome >= 125 on Windows, Linux and macOS
* Firefox >= 133 on Windows, Linux and macOS
* Microsoft Edge >= 131 on Windows
* Safari >= 18.1 on macOS
endif::[]
ifdef::saas[]
* Google Chrome >= 130 on Windows, Linux and macOS
* Firefox >= 128 on Windows, Linux and macOS
* Microsoft Edge >= 130 on Windows
* Safari >= 17.2 on macOS
endif::[]


The {CMK} mobile user interface has been verified to run on the following mobile browsers:

* Safari on iPadOS/iPhoneOS (current and last major OS release)
* Google Chrome on Android (current and last major OS release)


[#agent]
== OS for the {CMK} agent

The {CMK} agent can be installed and run on the following operating systems if the OS meets some basic requirements.

// MFS: Should be splitted for 2.4 to "Linux with Agent Controller" and "Linux/Unix legacy mode"
ifdef::onprem[]
=== Linux/Unix

All Linux distributions and various Unix operating systems such as _Solaris_ and _AIX_ are supported, provided they have at least the following technical components in the minimum version:

* Bash >= 4.2
* ksh >= 93
* Perl >= 5.14.0

Additionally, one of the following components needs to be present:

* systemd >= 219
* xinetd (no minimal version)

Be aware: Plug-ins may require a specific version of additional components to be functional.
Python plug-ins require version 2.7 or > 3.5.
endif::[]


ifdef::saas[]
=== Linux

All xref:agent_linux#[Linux distributions on `x86/64`] are supported, provided they have at least the following technical components in the minimum version:

* Bash >= 4.2
* ksh >= 93
* Perl >= 5.14.0

Additionally, the following component needs to be present:

* systemd >= 219

Be aware: Plug-ins may require a specific version of additional components to be functional.
Python plug-ins require versions > 3.5.
endif::[]


[#windows]
=== Windows

All 64-bit versions of the following xref:agent_windows#[Windows operating system] releases are supported:

* 2016
* 2019
* 2022
* 2025

ifdef::onprem[]
For older releases, we provide a link:https://download.checkmk.com/legacy-agents/[legacy agent^] with a limited feature set and without official support.
endif::[]


ifdef::onprem[]
[#grafana]
== Grafana plug-in

{CMK} {current-major} supports the following Grafana plug-in versions:

* >= 3.0.0
endif::[]


ifdef::onprem[]
[#appliance]
== {CMK} Appliance

{CMK} {current-major} can run on the following versions of the {CMK} Appliance:

* >= 1.7.0
endif::[]


ifdef::onprem[]
[#ldap]
== LDAP server

With LDAP {CMK} {current-major} supports synchronization of the following LDAP servers:

* Microsoft Active Directory
* OpenLDAP
* 389 Directory Server


[#saml]
== SAML IdP

The SAML integration supports the following Identity Providers (IdPs):

* Microsoft Entra ID (called Azure Active Directory until 2023)
* Google Cloud
* Okta

{CMK} may work with other SAML integrations as well, but no support can be given for these.
endif::[]


ifdef::onprem[]
[#ntopng]
== ntopng

The ntopng integration supports the following versions of ntopng Professional and Enterprise:

* >= 6.0
endif::[]


ifdef::onprem[]
[#nagvis]
== Nagvis

Nagvis depends on PHP and requires a minimum version to run.
To run Nagvis, make sure to have a matching version of PHP in your installation:

* >= 7.2

Depending on the Linux distribution used, the version defined as a dependency of the {CMK} installation package may be higher.
endif::[]


ifdef::onprem[]
[#influxdb]
== InfluxDB

{CMK} supports the export of data to the following versions of the InfluxDB API:

// MFS: Check back with devs 
* >= 2.0
endif::[]


ifdef::saas[]
== Change log

=== Corrections

==== 17-Feb-2025 

* After testing, Windows 2025 was added to the list of supported operating systems for agents.
endif::[]

== Change log

=== Corrections

==== 26-Nov-2025

The list of supported Linux operating systems has been updated and the table column "Supported since {CMK} version" has been added:

* Ubuntu 24.04 LTS _Noble Numbat_ is supported since {CMK} version {v24}.

* SUSE Linux Enterprise Server (SLES) 15 SP6 is supported since {CMK} version {v24}.

* SUSE Linux Enterprise Server (SLES) 15 SP7 is supported since {CMK} version {v24}p16.

* Debian 13 _Trixie_ is supported since {CMK} version {v24}p16.

* Red Hat Enterprise Linux 10 (RHEL 10) is supported since {CMK} version {v24}p16.