// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Security
:revdate: 2022-07-12
:title: Security - Additional safeguarding for {CMK}
:description: {CMK} is already very safe by design. This article describes what you can do to make your monitoring even more secure.


This article will be completed in the near future to provide a central overview on all aspects of security measures implemented in {CMK} and aids on further improving security.

First the Good News: Since its beginning {CMK} has used an architecture that considers security needs and -- wherever possible -- applies these to its standard settings.
There are however aspects where user intervention is required, for example when keys or certificates have to be generated or imported.


== Agent output

Since version {v21}, {CMK} offers TLS encryption for communication between the server and the agents on Linux and Windows hosts.
Detailed information on this communication are covered in the following articles:

- xref:agent_linux#[Monitoring Linux]
- xref:agent_windows#[Monitoring Windows]

However there are some environments where TLS encryptions for Linux or Unix clients cannot be setup.
In such cases you might use encrypted tunnels, for example with SSH:

- xref:agent_linux_legacy#ssh[Monitoring and securing Linux in legacy mode]
- xref:datasource_programs#[Datasource programs]


== HTTP(S) communication

On many places within {CMK} communication is realized over HTTP.
This applies to internal communication and configurations such as distributed monitoring.
Switch to HTTPS where possible:

- xref:omd_https#[Securing the web interface with HTTPS]
- xref:ldap#ssl[Securing LDAP with SSL]
- xref:appliance_usage#ssl[Protecting the appliance-GUI via TLS]
- xref:managing_docker#https[Securing Docker with HTTPS]


== Access control

{CMK} supports connections to various authentication protocols and is also able to enforce two-factor authentication for even higher security:

- xref:ldap#[User management with LDAP/Active Directory]
- xref:wato_user#2fa[Two-factor authentication of {CMK} users]
- xref:kerberos#[Single sign-on with Kerberos]
- xref:saml#[Authentication with SAML]
