// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Security
:revdate: 2022-07-12
:title: Security - Additional safeguarding for {CMK}
:description: {CMK} is already very safe by design. This article describes what you can do to make your monitoring even more secure.


This article will be completed in the near future to provide a central overview on all aspects of security measures implemented in {CMK} and aids on further improving security.

First the Good News: Since its beginning {CMK} has used an architecture that considers security needs and -- wherever possible -- applies these to its standard settings.
There are however aspects where user intervention is required, for example when keys or certificates have to be generated or imported.


[#agent_output]
== Agent output

Since version {v21}, {CMK} has used TLS encryption for communication between the server and the agents on Linux and Windows hosts.
Detailed information on this communication are covered in the following articles:

- xref:agent_linux#[Monitoring Linux]
- xref:agent_windows#[Monitoring Windows]

However there are some environments where TLS encryptions for Linux or Unix clients cannot be setup.
In such cases you might use encrypted tunnels, for example with SSH:

- xref:agent_linux_legacy#ssh[Monitoring and securing Linux in legacy mode]
- xref:datasource_programs#[Datasource programs]


[#https]
== HTTP(S) communication

On many places within {CMK} communication is realized over HTTP.
This applies to internal communication and configurations such as distributed monitoring.
Switch to HTTPS where possible:

- xref:omd_https#[Securing the web interface with HTTPS]
- xref:ldap#ssl[Securing LDAP with SSL]
- xref:appliance_usage#ssl[Protecting the appliance-GUI via TLS]
- xref:managing_docker#https[Securing Docker with HTTPS]


[#access_control]
== Access control

{CMK} supports connections to various authentication protocols and is also able to enforce two-factor authentication for even higher security:

- xref:ldap#[User management with LDAP/Active Directory]
- xref:wato_user#2fa[Two-factor authentication of {CMK} users]
- xref:kerberos#[Single sign-on with Kerberos]
- xref:saml#[Authentication with SAML]


// This block is new
// start translation
////
[#logging]
== Logging

Die Erkennung sicherheitsrelevanter Ereignisse erleichtert die Log-Datei `security.log`.
Hier werden Ereignisse beispielsweise aus den Bereichen Authentifizierung, Benutzerverwaltung, Service (z. B. Start und Stopp der xref:glossar#site[Instanz]) und Anwendungsfehler protokolliert.
Sie finden diese Log-Datei im Instanzverzeichnis, im folgenden mit einigen beispielhaften Einträgen als Inhalt:

.~/var/log/security.log
[{file}]
----
2024-04-02 19:12:33,891 [cmk_security.service 269382] {"summary": "site stopped", "details": {}}
2024-04-03 08:55:46,480 [cmk_security.service 5652] {"summary": "site started", "details": {}}
2024-04-03 09:21:18,830 [cmk_security.auth 8798] {"summary": "authentication succeeded", "details": {"method": "login_form", "user": "cmkadmin", "remote_ip": "127.0.0.1"}}
2024-04-03 15:41:20,499 [cmk_security.user_management 8798] {"summary": "user created", "details": {"affected_user": "myuser", "acting_user": "cmkadmin"}}
2024-04-03 16:36:04,099 [cmk_security.auth 1882076] {"summary": "authentication failed", "details": {"user_error": "Incorrect username or password. Please try again.", "method": "login_form", "user": "myuser", "remote_ip": "127.0.0.1"}}
2024-04-03 18:19:05,640 [cmk_security.application_errors 1882076] {"summary": "CSRF token validation failed", "details": {"user": "cmkadmin", "remote_ip": "127.0.0.1"}}
----

Jede Zeile ist so aufgebaut:

* Datum und Uhrzeit (Ortszeit) der Erstellung des Log-Eintrags.
* Sicherheitsdomäne (z. B. `cmk_security.auth` ) und Prozess-ID.
* Die Meldung selbst als Zusammenfassung (`summary`) und detailliert (`details`), jeweils im JSON-Format.
Der Inhalt der Details variiert je nach Sicherheitsdomäne.

Beachten Sie, dass sich die Inhalte der Log-Datei in Zukunft ändern können, z. B. durch Hinzufügen weiterer Sicherheitsdomänen, protokollierter Ereignisse oder der in den Details bereitgestellten Informationen.
////
// end translation
