// -*- coding: utf-8 -*-
// IGNORE 
// SKIPCOMMITS 
include::global_attr.adoc[]
= Monitoring your own system
:revdate: 2025-12-16
:title: Monitoring your own system
:description: {CMK} can not only monitor other systems, but also its own health. Read more about this here.

{related-start}
xref:monitoring_basics#[Basic principles of monitoring with {CMK}]
xref:hosts_setup#[Host administration]
xref:wato_rules#[Rules]
{related-end}


== Introduction

In our xref:intro_setup_monitor.html#linux[Guide for Beginners], we showed you how to lay the groundwork for monitoring the {CMK} server.
The following article is now about filling this monitoring with meaningful content.
After all, {CMK} can not only check whether the {CMK} server is running, but there are many more parameters that can be checked—and subsequently optimized.


== Process detection

In process detection, for example, there are predefined rules for specific services for self-monitoring.
You can access these via [.guihint]#Setup > Services > Discovery rules > Discovery of individual services > Process discovery#.

For each host that has the `cmk/check_mk_server:yes` host feature, the following services will be automatically found thanks to the rules provided:

[multicol]
* [.guihint]#Process myhost active check helpers#
* [.guihint]#Process myhost agent receiver#
* [.guihint]#Process myhost alert helper#
* [.guihint]#Process myhost apache#
* [.guihint]#Process myhost automation helpers#
* [.guihint]#Process myhost checker helpers#
* [.guihint]#Process myhost cmc#
* [.guihint]#Process myhost dcd#
* [.guihint]#Process myhost event console#
* [.guihint]#Process myhost fetcher helpers#
* [.guihint]#Process myhost jaeger# + 
(not permanently visible)
* [.guihint]#Process myhost livestatus proxy#
* [.guihint]#Process myhost notification spooler#
* [.guihint]#Process myhost notify helper#
* [.guihint]#Process myhost piggyback hub# +
(not permanently visible)
* [.guihint]#Process myhost rabbitmq# +
(only when piggyback hub is enabled)
* [.guihint]#Process myhost real-time helper# +
(only when real-time checks are enabled)
* [.guihint]#Process myhost redis-server#
* [.guihint]#Process myhost rrd helper#
* [.guihint]#Process myhost rrdcached#

You can either deactivate or delete any rules that you do not need.
We recommend deactivating rules that you do not need, especially if you do not want to use any of those rules.
This is because if you delete all rules instead of just deactivating them, all rules will be recreated the next time you import a {CMK} patch.

To learn what you can do with these services, read the article xref:wato_services#[Understanding and configuring services].
To find out exactly what the processes included in monitoring as services do, read the article on xref:cmk_processes#[Site services].


== Self-monitoring of the system (plugs-ins)

The link:https://checkmk.com/integrations[{CMK} Plug-ins Catalog] also offers various options for self-monitoring your system.
Some of these may already be activated in your system by default, meaning you do not need any additional plug-ins.
The following table provides a comprehensive overview:

[cols=4,options=“header”]
|====
|Plug-in name / +
Manual page title | Function | Parameters | Output
|bi_aggregation / +
Checkmk: State of BI Aggregation |Outputs the status of a xref:bi#[BI aggregation]. Also indicates whether the aggregation is currently in maintenance mode or has been acknowledged. |Name of Aggregation |One service per BI aggregation
|bi_aggregation_connection / +
Checkmk: Status Information for BI Aggregation Connection |Status information for the special agent agent_bi. Includes connection errors, missing site data, and missing aggregations due to missing data. | n/a |One service per connection
|check-mk / +
Checkmk: Retrieval of Information |Retrieves status information from the configured data sources, e.g., from configured agents, special agents, SNMP, piggyback data, and management boards. The overall status of the service, which depends on the results, can be configured with the rule set [.guihint]#Status of the {CMK} services#. Also updates all passive services and any piggyback data received from the host. |n/a |n/a
|check-mk-inventory / +
Checkmk: Discovery Procedure |Created automatically on new sites. Automatically goes to {WARN} as soon as a service of the host tags changes. Configuration is possible via the rule set [.guihint]#Periodic service discovery#. An automatic update of the {CMK} configuration with the services found can also be activated here. |n/a |one service for each host that supports this check
|checkmk_agent / +
Checkmk Agent: Deployment properties |Ensures the proper functioning of the {CMK} agent deployment mechanism (if used). Checks the time of the last successful connection to the deployment server and the presence of error messages, displays the number of deployed agent plug-ins and local checks. Further settings are possible, see link:https://checkmk.com/integrations/checkmk_agent[Plug-in description] |n/a |one service
|cmk_site_statistics / +
Number of hosts and services per state of Checkmk sites | Monitors the number of hosts and services at {CMK} sites, reporting the total number of hosts, the number of hosts that are not {UP}, and the number of hosts that are {UP}, {DOWN}, in maintenance mode, and {UNREACH}. Reports the total number of services, the number of services that are not {OK}, and the number of services that are {OK}, in maintenance mode, running on failed hosts, {WARN}, {UNKNOWN}, and {CRIT}. The check is always {OK} and cannot be configured by the user. |Name of the {CMK} site |One service per running {CMK} site on a {CMK} server
|livestatus_status / +
Checkmk: Performance and Settings |Receives various performance data from an OMD monitoring core via xref:livestatus#[Livestatus]. Provides information about the performance of the core, the number of checks executed per second, etc. Determines whether certain settings have been disabled (e.g., notifications). States can be configured via check parameters. |Name of the OMD instance |One service per running OMD site.
|mkbackup / +
Checkmk Appliance: Backup Job State |Checks the status of backup jobs on a {CMK} appliance. Reports {CRIT} if the job fails or its next execution is overdue. |ID of the job |one service per backup job
|mkbackup_site / +
Checkmk Site: Backup Job State |Checks the status of the xref:backup#[Backup] jobs of a {CMK} site. Reports {CRIT} if the job fails or its next execution is overdue. |ID of the site, followed by `{{backup}}` and the ID of the job |one service per site and backup job
|mkeventd_status / +
Checkmk Event Console: Status and Performance |Receives various performance values of a site of the type xref:ec#[{CMK} Event Console]. Warning for active event limits, recording of performance metrics related to the Event Console. The check is not configurable by the user. |Name of the {CMK} site |One service per running {CMK} site
|mknotifyd_connection_v2 / +
Checkmk Notification Spooler: Connection |Checks the status of individual TCP connections from the {CMK} Notification Spooler to a remote spooler. A service is created for each incoming and outgoing TCP connection. The status changes to {CRIT} if the connection is not established. |Name of the site followed by the name of the connected remote site, separated by a hyphen. If there is more than one incoming connection from the same remote host, an index is appended. This check is not user-configurable. |One service per site and connection
|mknotifyd / +
Checkmk Notification Spooler: Status |Checks the status of the xref:notifications#[{CMK} Notification Spooler]. {WARN} if deferred spool files remain too long or damaged spool files are found. {CRIT} if spooler is not running. This check is not user-configurable. |Name of the site | one service per site
|omd_apache / +
Checkmk Sites: Apache Access Statistics |Creates statistics about the requests processed by the xref:rest_api#[Apache Web Server] on OMD sites. It records the number of requests, the bytes sent, and the time required to process the requests. It is grouped by request type, e.g., {CMK} table views, NagVis AJAX calls, but also by type, e.g., for images, style sheets, etc. The check uses a specific log file, which must be located under `var/log/apache/stats`, to collect the access statistics. This file is truncated with each check. This check is always {OK}, and cannot be configured by the user. |Name of the site |one service per site
|omd_broker_queues / +
Checkmk: Site Broker Queues |Monitors the number of notifications in broker queues for each site application. Service name contains the site and application name. This check is always {OK}. |site and application name |One service per site application
|omd_broker_status / +
Checkmk: Site Broker Status |Monitors the general status of the message broker on each site. Shows the memory used by the broker, the number of queues, and the number of shovels in _running_ status. This check is always {OK}. |site name |One service per site on which a broker is installed and running
|omd_diskusage / +
Checkmk: Site disk usage |Monitors the disk usage of a site to facilitate the search for anomalies if necessary. A list of the directories currently being monitored can be found in the link:https://checkmk.com/integrations/omd_diskusage[Plug-in description.] This check is always {OK}, and cannot be configured by the user. |Name of the site |one service per site
|omd_status / +
Checkmk: Site Status |Checks the status of the OMD sites found on the system using `omd status --bare --auto`. If all services are running, the site is {OK}, otherwise {CRIT}. If the site is only partially running, the check output contains the names of the stopped services. In clustered environments, the check lists all nodes on which sites are running and their status. The overall status of the service is {CRIT} if a site on a node is only partially running or if all sites on all nodes are stopped. This check is not user-configurable. | Name of the site |one service per site on which the option [.guihint]#Autostart# is set to `ON`, regardless of the current site status
|site_object_counts / +
Checkmk: Site Objects |Collects information about the number of different host types or check commands used on the {CMK} sites. The settings and functionality of the check are extensive. For more information, see the link:https://checkmk.com/integrations/site_object_counts[Plug-in description.] The check is always in {OK} status. |n/a |one service
|====