// -*- coding: utf-8 -*-
include::global_attr.adoc[]
ifdef::onprem[]
= Welcome to the {CMK} User Guide
:revdate: 2022-12-06
:title: Welcome to the {CMK} User Guide
:description: Each manual requires a specific usage. Here we explain how the {CMK} User Guide is structured so that you can quickly find the relevant content.
:no-toc:

{related-start}
xref:intro_setup#[Setting up {CMK}]
{related-end}
endif::[]

ifdef::saas[]
= Welcome to the {CE} User Guide
:revdate: 2024-12-19
:title: Welcome to the {CE} User Guide
:description: Each manual requires a specific usage. Here we explain how the {CE} User Guide is structured so that you can quickly find the relevant content.
:no-toc:

{related-start}
xref:intro_setup#[Getting {CE}]
{related-end}
endif::[]


*Dear reader*

ifdef::onprem[]
We are pleased that you have found to {CMK}.
endif::[]
ifdef::saas[]
We are pleased that you have found to {CE}.
{CE} provides you with {CMK} as _Software as a Service (SaaS)_ in the cloud.
You can find out what characterizes {CE} (SaaS), also in comparison to its self-hosted siblings such as {CE} (Self-hosted), in an xref:cce#[own article].
endif::[]

As a monitoring software, {CMK} offers comprehensive and specialized solutions for dealing with the very diverse environments of IT infrastructures.
This inevitably requires a very comprehensive documentation which goes beyond the mere description of the obvious.
Our User Guide will help you as much as possible to better understand {CMK}, to implement solutions for your requirements with {CMK}, as well as helping you to discover new approaches of solving problems.

To make the handling of {CMK} as easy as possible, the articles in this User Guide follow rather unusual approaches in many places.
It is almost never a matter of simply copying a prefabricated sequence of individual steps.
Rather, it is intended to give you, the reader, a deeper understanding of a feature in {CMK}.

To briefly summarize, our most important premise is that the User Guide should be helpful.
And it is most helpful when you can translate our description as a blueprint into a solution for your own problem.

[#landing_page_continue]
For this reason, among others, the User Guide is divided into several chapters which flow smoothly into each other.
With this subdivision we want to enable you to easily and quickly find the contents you are looking for.
The following topics can be found in the User Guide's chapters.


[discrete]
== Beginner's Guide

There's a first time for everything, even with {CMK}.
Since you will be exposed to a large number of options and functions, sometimes it can be difficult to set the right steps on this journey.
We therefore want to make it easy for you to enter the world of {CMK} by supporting you step by step at the beginning with the creation of your first {CMK} site and by introducing the most important concepts.

This part of the User Guide is therefore very well suited for being read through from start to finish in a linear fashion.
If you are reading this User Guide for the first time you can also start directly with xref:intro_setup#[the first article from the Beginner's Guide], 
and if necessary, later return to the descriptions in the more advanced chapters.


[discrete]
== Tasks for administrators and users  

ifdef::onprem[]
The main part from chapter 3 to 10 explain the functions and their use in {CMK}:
when you are installing {CMK} for the first time, want to customize the configuration or want to learn how to display the data in an efficient, understandable and useful way.
endif::[]
ifdef::saas[]
The main part from chapter 3 to 8 explain the functions and their use in {CMK}:
when you are setting up {CMK} for the first time, want to customize the configuration or want to learn how to display the data in an efficient, understandable and useful way.
endif::[]

For this reason, these chapters are less suited to reading through from start to finish.
Rather, they are organized thematically and devoted to the various aspects of a given task.
Within the chapters you will then find important, introductory or otherwise prioritized articles, always at the beginning of the chapters.


[discrete]
== Automation and development

ifdef::onprem[]
{CMK} can be managed not only using a web interface, but also via APIs.
In addition, {CMK}'s modular software architecture also allows for an extensive range of enhancement options.

With the articles in this chapter we will gradually introduce tips, hints and starting points for adapting {CMK} to your own infrastructure or automating its configuration.
endif::[]

ifdef::saas[]
{CMK} can be managed not only with a web interface, but also with a REST API.
In addition, {CMK}'s modular software architecture also offers in the cloud enhancement options for adapting {CMK} to your own infrastructure.
endif::[]


[discrete]
== Concepts

This chapter is still quite new -- even though the articles it contains have been in the User Guide for a long time already.
If you want to learn more about how {CMK} actually works without pursuing a direct requirement or task, then you are in the right place here.


ifdef::onprem[]
[discrete]
== The {CMK} appliance

All topics concerning the setup and use of the appliance can be found in the last chapter of the User Guide.
The appliance chapter is actually a separate manual.
However, since the concepts of {CMK} also apply for the appliance, readers of this chapter should always refer to the other articles in the User Guide as well.
endif::[]
