// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Welcome to the {CMK} User Guide
:revdate: 2022-12-06
:title: Welcome to the {CMK} User Guide
:description: Each manual requires a specific usage. Here we explain how the {CMK} User Guide is structured so that you can quickly find the relevant content.
:no-toc:

{related-start}
xref:intro_setup#[Setting up {CMK}]
{related-end}


*Dear reader*

// MFS: Remove "your way" since this often gets literally translated to "path" or "street":
// We are pleased that you have found your way to {CMK}.
We are pleased that you have found {CMK}.

As a monitoring software, {CMK} offers comprehensive and specialized solutions 
for dealing with the very diverse environments of IT infrastructures.
This inevitably requires a very comprehensive documentation 
which goes beyond the mere description of the obvious.
// MFS: Just tinkering with stuff that makes LLM translation easier: The verb "to implement" needs to be accompagnied by nouns given context.
// Our User Guide will help you as much as possible to better understand {CMK}, use {CMK} to implement your requirements, as well as helping you to discover new ways of solving problems.
Our User Guide will help you as much as possible to better understand {CMK}, use {CMK} to implement solutions for your requirements, as well as helping you to discover new approaches of solving problems.

To make the handling of {CMK} as easy as possible, 
the articles in this User Guide follow rather unusual approaches in many places.
It is almost never a matter of simply copying a prefabricated sequence of individual steps.
Rather, it is intended to give you, the reader, a deeper understanding of a feature in {CMK}.

To briefly summarize, our most important premise is that the User Guide should be helpful.
// MFS: Just tinkering with stuff that makes LLM translation easier: The verb "to implement" needs to be accompagnied by nouns given context.
// And it is most helpful when you can implement our description as a solution for your own problem.
And it is most helpful when you can use our description as a direct blueprint for the solution for your own problem.

[#landing_page_continue]
For this reason, among others, the User Guide is divided into several chapters which flow smoothly into each other.
// MFS: Comparitive used twice almost guarantees LLMs to make funny things or ignore one:
// MFS: Only passive without specifying the acting person does not work for LLMs.
// With this subdivision we want to make it easier to find the contents you are looking for more quickly.
With this subdivision we want to enable you to easily and quickly find the contents you are looking for.
The following topics can be found in the User Guide's chapters.


[discrete]
== Beginner's Guide

There's a first time for everything, even with {CMK}.
// MFS: Two idioms using the picture of starting a journey in one sentence, literally translated to some languages, move to broader scope:
// MFS: Note, this not badly translated, just tinkering with best outcome. More problematic in Italian than in Spanish.
// Since you are presented with a large number of options and functions, sometimes it can be difficult to find your way through the first steps.
Since you will be exposed to a large number of options and functions, sometimes it can be difficult to set the right steps on this journey.
We therefore want to make it easy for you to enter the world of {CMK}
by supporting you step by step in the installation of your first {CMK} site and 
by introducing the most important concepts.

This part of the User Guide is therefore very well suited 
for being read through from start to finish in a linear fashion.
If you are reading this User Guide for the first time 
you can also start directly with xref:intro_setup#[the first article from the Beginner's Guide], and
if necessary, later return to the descriptions in the more advanced chapters.


[discrete]
== Tasks for administrators and users  

// MFS: Questions gets literally translated. This is unsuitable for languages where a question is limited to something you really ask.
// The main parts from chapter 3 to 10 explain the functions and their use in {CMK} when you are planning to install {CMK} for the first time, have questions about its configurations or want to know how to display the data in an efficient, understandable and useful way.
The main parts from chapter 3 to 10 explain the functions and their use in {CMK} when you are planning to install {CMK} for the first time, have doubts about its configurations or want to learn how to display the data in an efficient, understandable and useful way.

For this reason, these chapters are less suited to reading through from start to finish.
Rather, they are organized thematically and devoted to the various aspects of a given task.
Within the chapters you will then find important, introductory or otherwise prioritized articles, always at the beginning of the chapters.


[discrete]
== Automation and development

{CMK} can be managed not only using a web interface, but also via APIs.
In addition, {CMK}'s modular software architecture also allows for an extensive range of enhancement options.

// MFS: Entry points gets literally translated, starting points works better.
// With the articles in this chapter we will gradually introduce tips, hints and entry points for adapting {CMK} to your own infrastructure or automating its configuration.
With the articles in this chapter we will gradually introduce tips, hints and starting points for adapting {CMK} to your own infrastructure or automating its configuration.


[discrete]
== Concepts

This chapter is still quite new -- even though the articles it contains have been in the User Guide for a long time already.
// MFS: Another verb of motion that does not work everywhere litarally translated:
// If you want to learn more about how {CMK} actually works, without following a direct requirement or task, then you are in the right place here.
If you want to learn more about how {CMK} actually works, without pursuing a direct requirement or task, then you are in the right place here.

[discrete]
== The {CMK} appliance

All topics concerning the setup and use of the appliance can be found in the last chapter of the User Guide.
The appliance chapter is actually a separate manual.
However, since the concepts of {CMK} also apply for the appliance, 
readers of this chapter should always refer to the other articles in the User Guide as well.
