// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Welcome to the {CMK} User Guide
:revdate: 2022-12-06
:title: Welcome to the {CMK} User Guide
:description: Each manual requires a specific usage. Here we explain how the {CMK} User Guide is structured so that you can quickly find the relevant content.
:no-toc:

{related-start}
xref:intro_setup#[Setting up {CMK}]
{related-end}


*Dear reader*

We are pleased that you have found your way to {CMK}.

As a monitoring software, {CMK} offers comprehensive and specialized solutions 
for dealing with the very diverse environments of IT infrastructures.
This inevitably requires a very comprehensive documentation 
which goes beyond the mere description of the obvious.
Our User Guide will help you as much as possible to
better understand {CMK}, use {CMK} to implement your requirements, as well as helping you to discover new ways of solving problems.

To make the handling of {CMK} as easy as possible, 
the articles in this User Guide follow rather unusual approaches in many places.
It is almost never a matter of simply copying a prefabricated sequence of individual steps.
Rather, it is intended to give you, the reader, a deeper understanding of a feature in {CMK}.

To briefly summarize, our most important premise is 
that the User Guide should be helpful.
And it is most helpful when you can implement our description as a solution for your own problem.

[#landing_page_continue]
For this reason, among others, the User Guide is divided into several chapters 
which flow smoothly into each other.
With this subdivision we want to make it easier 
to find the contents you are looking for more quickly.
The following topics can be found in the User Guide's chapters.


[discrete]
== Beginner's Guide

There's a first time for everything, even with {CMK}.
Since you are presented with a large number of options and functions, 
sometimes it can be difficult to find your way through the first steps.
We therefore want to make it easy for you to enter the world of {CMK}
by supporting you step by step in the installation of your first {CMK} site and 
by introducing the most important concepts.

This part of the User Guide is therefore very well suited 
for being read through from start to finish in a linear fashion.
If you are reading this User Guide for the first time 
you can also start directly with xref:intro_setup#[the first article from the Beginner's Guide], and
if necessary, later return to the descriptions in the more advanced chapters.


[discrete]
== Tasks for administrators and users  

The main parts from chapter 3 to 10 explain the functions and their use in {CMK} 
when you are planning to install {CMK} for the first time, have questions about its configurations or
want to know how to display the data in an efficient, understandable and useful way.

For this reason, these chapters are less suited to reading through from start to finish.
Rather, they are organized thematically and devoted to the various aspects of a given task.
Within the chapters you will then find important, introductory or otherwise prioritized articles, always at the beginning of the chapters.


[discrete]
== Automation and development

{CMK} can be managed not only using a web interface, but also via APIs.
In addition, {CMK}'s modular software architecture also allows for an extensive range of enhancement options.

With the articles in this chapter 
we will gradually introduce tips, hints and entry points 
for adapting {CMK} to your own infrastructure or automating its configuration.


[discrete]
== Concepts

This chapter is still quite new -- even though the articles it contains have been in the User Guide for a long time already.
If you want to learn more about how {CMK} actually works,
without following a direct requirement or task,
then you are in the right place here.


[discrete]
== The {CMK} appliance

All topics concerning the setup and use of the appliance can be found in the last chapter of the User Guide.
The appliance chapter is actually a separate manual.
However, since the concepts of {CMK} also apply for the appliance, 
readers of this chapter should always refer to the other articles in the User Guide as well.
