#!/bin/bash

COLUMNS="name members num_hosts num_hosts_up num_services num_services_ok"
SITE="mysite"

echo "<<<myhostgroups:sep(59)>>>"
echo -e "GET hostgroups\nColumns: $COLUMNS" | /omd/sites/$SITE/bin/unixcat /omd/sites/$SITE/tmp/run/live
