// -*- coding: utf-8 -*-
// IGNORE 
// NONASCII 
include::global_attr.adoc[]
= Die KI-Richtlinie des {CMK} Handbuchs 
:title: Die KI-Richtlinie des {CMK} Handbuchs 
:description: Das {CMK} Handbuch wird von qualifizierten menschlichen Redakteuren gepflegt. Lesen Sie hier, wie KI/LLMs bei der Arbeit am Handbuch genutzt werden.

[#introduction]
== Einleitung

Diese Richtlinie beschreibt, auf welche Weise KI-/LLM-Werkzeuge („künstliche Intelligenz“/_Large Language Models_) bei der Arbeit am offiziellen {CMK} Handbuch zum Einsatz kommen.

Das Team, das für die Pflege des Handbuchs verantwortlich ist, verpflichtet sich dazu, den Lesenden jederzeit korrekte, präzise, relevante und vollständige Informationen zur Verfügung zu stellen, und wird dieses Ziel stets priorisieren.

[#quality]
== Menschliche Qualitätskontrolle

Das {CMK} Handbuch wird geschrieben und gepflegt von einem Team aus hochqualifizierten technischen Redakteurinnen und Redakteuren mit Kompetenzen in zahlreichen Bereichen, unter anderem Informatik, Journalismus, interdisziplinäre Kommunikation, Informationswissenschaft, Linguistik, Natural Language Processing, Softwareentwicklung, Informationstechnik, Didaktik, Pädagogik und Storytelling.
Alle Änderungen im Handbuch, einschließlich Übersetzungen zwischen Deutsch und Englisch, durchlaufen einen Review-Prozess mit mindestens einem Team-Mitglied.
Wir veröffentlichen ausschließlich Texte, die wir für korrekt, relevant und lesbar für unsere menschlichen Lesenden halten.

Die Texterstellung für das Handbuch liegt in menschlicher Hand und wird nur punktuell und experimentell durch KI-basierte Textgenerierung unterstützt.
Bei KI-unterstützten Artikelentwürfen wenden wir unseren bestehenden Review-Prozess an, um die Veröffentlichung minderwertiger Texte zu verhindern.
Wir markieren keine Texte als „KI-generiert“, da wir nie zulassen, dass KI-generierte Texte ohne eine durch Menschen durchgeführte Qualitätskontrolle ins Handbuch gelangen.

Wir nutzen für die automatische Übersetzung von Handbuchartikeln in andere Sprachen als Deutsch oder Englisch LLM-basierte Werkzeuge.
Alle automatisch übersetzten Texte markieren wir explizit.
Falls Sie Bedenken zur Qualität einer automatischen Übersetzung haben, empfehlen wir einen Blick in die deutsche oder englische Version des Artikels.


[#tools]
== Eingesetzte Werkzeuge
=== Deterministische Qualitätsprüfungen

Wir nutzen eine Reihe von automatischen, regelbasierten und daher deterministischen Prüfungen, um die Einhaltung bestimmter struktureller und stilistischer Richtlinien sicherzustellen.
KI-Werkzeuge kommen an dieser Stelle unserer Arbeit nicht zum Einsatz und wir planen auch nicht, sie hier einzuführen.


=== Faktenchecks mit KI/LLMs

Wir behalten uns vor, bei der vorbereitenden Recherche für Änderungen von Handbuchtexten KI- oder LLM-Werkzeuge auf dem neuesten Stand der Technik zu nutzen.
Der Zweck des KI-Werkzeugs in diesem Kontext ist es, einzelne Punkte anhand mehrerer interner und externer Quellen zu verifizieren und dabei Lücken oder Unstimmigkeiten zu identifizieren.
Unsere Redakteurinnen und Redakteure prüfen die relevanten Quellen selbst und entscheiden, wie das jeweilige Thema im Handbuch präsentiert wird.
Entscheidungen darüber, welche Details in einem Artikel enthalten sein sollen und welche nicht, werden nie von einem KI-Werkzeug ohne menschliche Beaufsichtigung getroffen.


[#access]
== Zugriff auf das Handbuch mit KI-/LLM-Werkzeugen

Wenn Sie für Ihre Arbeit KI- oder LLM-Werkzeuge nutzen, kann es passieren, dass diese Werkzeuge Zitate oder zusammengefasste Passagen aus dem offiziellen {CMK} Handbuch ausgeben.
Das Handbuchteam hat keine Kontrolle über die Korrektheit oder Qualität solcher Auszüge und Zusammenfassungen und übernimmt keine Verantwortung für Behauptungen von Drittanwendungen.
Wir empfehlen, grundsätzlich die referenzierten Artikel als primäre Quellen zu konsultieren.

{CMK} stellt unter link:https://chat.checkmk.com/[chat.checkmk.com^] einen eigenen Chatbot zur Verfügung.
Auf der Chatbot-Seite gibt es die Möglichkeit, direkt Feedback zu geben.


[#summary]
== Zusammenfassung

Die Verantwortung für die Inhalte im {CMK} Handbuch liegt vollständig bei den menschlichen technischen Redakteurinnen und Redakteuren unseres Teams.
Wir behalten uns vor, moderne KI- oder LLM-Werkzeuge für bestimmte Teilaufgaben einzusetzen.
Wir veröffentlichen niemals ungeprüfte KI-generierte Texte im Handbuch.