// -*- coding: utf-8 -*-
// IGNORE Nuvola Vignoni
include::global_attr.adoc[]
= Copyright-Hinweise
:revdate: 2017-01-26
:title: Copyright-Hinweise
:description: Hinweise zu den Rechten an Texten und Grafiken im {CMK} Handbuch
:no-toc:

Dieses Handbuch ist urheberrechtlich geschützt.
Die Rechte von allen Texten und Grafiken liegen bei der {comfull}.

Einige der enthaltenen Bilder (Icons) stammen aus dem Icon-Set link:https://de.wikipedia.org/wiki/Nuvola[Nuvola^] von David Vignoni und stehen unter link:https://www.gnu.org/licenses/old-licenses/lgpl-2.1.de.html[LGPL Version 2.1.^] 
Für diese gilt folgende Lizenz:

_This library is free software;
you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation;
either version 2.1 of the License, or (at your option) any later version. +
This library is distributed in the hope that it will be useful, but without any warranty;
without even the implied warranty of merchantability or fitness for a particular purpose.
See the GNU Lesser General Public License for more details._

// TK: Linkziel gibts nicht mehr. Ersetzt durch Wikipedia-Link oben, in dem die alten Seiten via web.archive.org verlinkt sind.
// Einzelheiten zu den Icons von David Vignoni finden Sie link:http://www.icon-king.com/projects/nuvola/[hier.^]
