// -*- coding: utf-8 -*-
// IGNORE tos 0er OIC
// NONASCII │ ├ └ ─ …​
include::global_attr.adoc[]
= Oracle-Datenbanken überwachen
:title: Oracle-Datenbanken überwachen
:description: Mit dem Agentenplugin für Windows und Linux überwachen Sie vollumfänglich Oracle-Datenbanken. Details zur Konfiguration erfahren Sie hier.

{related-start}
xref:wato_monitoringagents#[Monitoring-Agenten]
xref:agent_linux#[Linux überwachen]
xref:agent_windows#[Windows überwachen]
link:https://checkmk.com/de/integrations[Katalog der Check-Plugins^]
{related-end}

[#introduction]
== Einleitung

In diesem Artikel erfahren Sie, wie Sie mit dem neuen Agentenplugin `mk-oracle` Oracle-Datenbanken überwachen können.

Wenn Sie Informationen zum alten Agentenplugin `mk_oracle` suchen, schauen Sie bitte in den link:https://docs.checkmk.com/2.4.0/de/monitoring_oracle.html[Artikel im 2.4.0er-Zweig des Handbuchs].

[#how]
== Wie funktioniert das Oracle-Monitoring mit {CMK}?

Um Oracle-Instanzen und -Datenbanken mit {CMK} zu überwachen, müssen of den jeweiligen Host der {CMK}-Agent und das Agentenplugin `mk-oracle` installiert werden.
Das Agentenplugin benötigt eine Konfiguration, welche Sie unter dem Namen `mk-oracle.yml` im xref:glossar#dir_conf[Konfigurationsverzeichnis] ablegen müssen.
Außerdem ist das Agentenplugin auf Bibliotheken des Oracle Instant Client (OIC) angewiesen.
Dieser muss also ebenfalls auf dem Host verfügbar sein.

Für all diese Voraussetzungen finden Sie Anleitungen in diesem Artikel und im Rest des Handbuchs.

Wie Sie den Oracle Instant Client (OIC) in verschiedenen Szenarien installieren erfahren Sie im Kapitel den xref:install_oic[Oracle Instant Client (OIC) bereitstellen].

Wie Nutzer von {CRE} ein Agentenplugin installieren erklären wir bereits in den Kapiteln xref:agent_linux#plugins[Agent um Plugins erweitern (Linux)] und xref:agent_windows#plugins[Agent um Plugins erweitern (Windows)].

Nutzende der kommerziellen Editionen von {CMK} bekommen im Kapitel xref:configuration_bakery[Konfiguration für das Agentenplugin erstellen] eine Erklärung der wichtigsten Optionen.
Im xref:reference[Referenzteil] dieses Artikels gehen wir dann nochmal auf alle xref:options_ruleset[Optionen im Regelsatz [.guihint]#Unified Oracle Plugin#] ein und zeigen an dieser Stelle auch, zu welchen Einträgen die jeweilige Option in der Konfigurationsdatei `mk-oracle.yml` führt.

Für alle, die das neue Agentenplugin in einer Testinstanz von Oracle ausprobieren wollen, bieten wir das kurze Tutorial xref:tutorial_monitoring_oracle_01[Alle Oracle-Datenbanken auf einem Host überwachen].


[#prerequisites]
== Voraussetzungen auf dem Oracle-Host schaffen

Auf jedem Host auf dem sie Oracle-Datenbanken bzw. -Instanzen überwachen möchten müssen Sie zwei Voraussetzungen schaffen.

. Der Oracle Instant Client muss für das Agentenplugin bereitgestellt werden.
Wie Sie das erledigen können, lesen Sie im xref:install_oic[entsprechenden Kapitel].
. Dem Agentenplugin muss Zugriff auf Ihre Oracle-Instanzen bzw. -Datenbanken gewährt werden.

Sie haben mehrere Möglichkeiten dem Agentenplugin `mk-oracle` Zugriff auf die Instanzen und Datenbanken zu gewähren.

Sie können auf dem Host einen Benutzer samt Passwort erzeugen, der ausschließlich für das Monitoring durch {CMK} verwendet wird.
Diesen Weg erklären wir im Kapitel xref:create_user[Datenbankbenutzer erstellen].

Stattdessen können Sie die xref:oracle_wallet[Oracle-Wallet nutzen].


//SK: Die Kapitel zur Installation des OIC verstehe ich als How-tos
[#install_oic]
=== Oracle Instant Client (OIC) bereitstellen
Das Agentenplugin `mk-oracle` benötigt die Bibliotheken des Oracle Instant Client (OIC) um zu funktionieren.
Sie haben drei Möglichkeiten, dass OIC zur Verfügung zu stellen.

Sie können OIC xref:#install_oic_exclusively[exklusiv für das Agentenplugin installieren].
Dies ist die von uns empfohlene Methode.

Alternativ können Sie OIC xref:#install_oic_globally[global auf dem Host installieren].

Falls OIC bereits auf dem Host installiert ist, und Sie diese Installation für die Überwachung durch {CMK} verwenden wollen, können Sie dem Agentenplugin einfach mitteilen, wo OIC zu finden ist.


[#install_oic_exclusively]
==== OIC exklusiv für den Agenten installieren (empfohlen)

//SK: Hier muss ein Satz hin, der erklärt, warum es dieses Kapitel braucht.

Laden Sie zuerst das für Ihren Host passende Paket von der Seite link:https://www.oracle.com/de/database/technologies/instant-client/downloads.html[Oracle Instant Client Downloads] im ZIP-Format herunter.

[.tabs]
====
[#tab_linux]#Linux#::
+
--
Für ein Linux x86-64 nehmen Sie beispielsweise das link:https://download.oracle.com/otn_software/linux/instantclient/2326200v2/instantclient-basiclite-linux.x64-23.26.2.0.0.zip[Basic Light Package (ZIP)]. 

Prüfen Sie, wie das Plugin-Verzeichnis des {CMK}-Agenten auf Ihren Host lautet:

[{shell}]
----
{c-local} sudo check_mk_agent | grep "^pluginsdir " | head -1
pluginsdir /usr/lib/check_mk_agent/plugins
----

Entpacken Sie die Archivdatei in eben jenes Plugin-Verzeichnis:

[{shell}]
----
{c-local} sudo unzip -j instantclient-basiclite-linux.x64-23.26.2.0.0 -d /path/to/agent/plugins/packages/mk-oracle
----

////
Please install Oracle Instant Client to be write-accessible only by the admin user.
SK: Rausfinden, was obiges bedeuet.

Das hier etwa?
sudo chmod go-w /path/to/agent/plugins/packages/mk-oracle/*
////


--
////
[#tab_windows]#Windows#::
+
--
Für Windows...


--
////
====


[#install_oic_globally]
==== OIC global installieren

Anleitung folgt.


[#create_user]
=== Datenbankbenutzer erstellen

Verbinden Sie sich als erstes mit Ihren Oracle-Host und wechseln Sie zum `oracle`-Benutzer.

[{shell}]
----
{c-root} su - oracle
----

Geben Sie abschließend die Instanz bekannt, mit der sich `sqlplus` verbinden soll:

[{shell}]
----
oracle@linux$ export ORACLE_SID=MYINST1
----

Starten Sie `sqlplus`.
Geben Sie dabei an, mit welcher Rolle `sqlplus` starten soll.

[{shell}]
----
oracle@linux$ sqlplus / as sysdba
----

Erzeugen Sie jetzt einen Benutzer, welcher ausschließlich für die Überwachung von Oracle verwendet werden soll.
Das Präfix `C##` sorgt dafür, dass der Nutzer alle Datenbanken der Instanz sehen kann.
Die Berechtigungen gelten für alle existierenden und zukünftigen Datenbanken.

[{sql}]
----
sqlplus> create user C##checkmk identified by myPassword;
sqlplus> alter user C##checkmk set container_data=all container=current;
sqlplus> grant select_catalog_role to C##checkmk container=all;
sqlplus> grant create session to C##checkmk container=all;
sqlplus> exit
----

[#oracle_wallet]
=== Oracle-Wallet nutzen

Alternativ dazu, den Benutzer direkt und mit Passwort in einer Konfigurationsdatei anzugeben, können Sie auch das _Oracle-Wallet_ nutzen.
Das hat den Vorteil, dass Sie nicht mehr die Zugangsdaten unverschlüsselt sowohl auf dem {CMK}-Server als auch auf dem Oracle-Host ablegen müssen.
Denn selbst wenn Sie die Rechte der Konfigurationsdatei auf dem Oracle-Host entsprechend angepasst haben, haben die Zugangsdaten dennoch den Server verlassen und befinden sich auf dem {CMK}-Server,
sofern Sie die Agentenbäckerei nutzen.

Das Oracle-Wallet wiederum legt die Zugangsdaten verschlüsselt auf dem zu überwachenden Host ab, sodass sie benutzt werden können, aber keine Login-Daten explizit bekannt gemacht werden müssen.
{CMK} kann dieses Wallet nutzen, sodass die Zugangsdaten prinzipiell nur dem Datenbankadministrator (DBA) bekannt sein müssen.
Dazu legen Sie -- oder der DBA -- ein Wallet auf dem entsprechenden Server an und legen diese im xref:glossar#dir_conf[Konfigurationsverzeichnis] in einer Datei namens `oracle_wallet` ab.

[{shell}]
----
{c-root} mkstore -wrl /etc/check_mk/oracle_wallet -create
----

Auf diese Datei wird das Agentenplugin später immer dann zugreifen, wenn eine Verbindung zu einer Instanz hergestellt werden soll.
Damit die nötigen Benutzerdaten auch gefunden werden, müssen Sie diese einmalig in das Wallet eintragen.
In dem folgenden Beispiel fügen Sie also den Benutzer `checkmk` für die Instanz `MYINST1` hinzu:

[{shell}]
----
{c-root} mkstore -wrl /etc/check_mk/oracle_wallet -createCredential MYINST1 checkmk myPassword
----

Damit das Agentenplugin weiß, wo es nach dem Wallet suchen muss, muss es zwei Dateien finden.
Die erste Datei ist `sqlnet.ora` in welcher hinterlegt wird, wo das Wallet zu finden ist.
Die zweite Datei -- `tnsnames.ora` -- bestimmt die Adresse der Instanz, sodass diese auch über ihren xref:tns_config[Alias] angesprochen werden kann.
Damit das Agentenplugin diese Dateien findet, können Sie den Pfad unter Linux, Solaris und AIX über die Umgebungsvariable xref:tns_config[`TNS_ADMIN`] setzen.
Das ist vor allem dann von Vorteil, wenn die Dateien bereits existieren.
Alternativ können Sie sie auch explizit anlegen.
Unter Windows ist es sogar erforderlich, dass Sie diese manuell bestimmen.

Legen Sie zunächst die Datei `sqlnet.ora` an.
In dieser Datei sucht das Agentenplugin alternativ nach den Zugangsdaten, sodass hier also der korrekte Pfad zu der eben erstellten Wallet-Datei angegeben werden muss.
Achten Sie dabei darauf, dass Sie den Parameter `SQLNET.WALLET_OVERRIDE` auf `TRUE` setzen:

./etc/check_mk/sqlnet.ora
[{file}]
----
LOG_DIRECTORY_CLIENT = /var/log/check_mk/oracle_client
DIAG_ADR_ENABLED = OFF

SQLNET.WALLET_OVERRIDE = TRUE
WALLET_LOCATION =
 (SOURCE=
   (METHOD = FILE)
   (METHOD_DATA = (DIRECTORY=/etc/check_mk/oracle_wallet))
 )
----

Jetzt weiß das Plugin, welche Zugangsdaten benutzt werden sollen.
Damit es auch die korrekte Adresse ansteuert, legen Sie als Datei die `tnsnames.ora` an.
Die genaue Syntax können Sie der Oracle-Dokumentation entnehmen, aber als Beispiel könnte die Datei so aussehen:

./etc/check_mk/tnsnames.ora
[{file}]
----
MYINST1
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = MYINST1_ALIAS)
    )
  )
----

Mit diesem Schritt haben Sie die Voraussetzungen geschaffen, um die Zugangsdaten aus der xref:user_config[Konfigurationsdatei des Agentenplugins] herauszunehmen.
Statt den Zugangsdaten tragen Sie lediglich ein `/` (Schrägstrich) ein:

./etc/check_mk/mk_oracle.cfg
[{file}]
----
DBUSER='/:'
----

Sie können dem Wallet natürlich zu einem späteren Zeitpunkt weitere Zugangsdaten hinzufügen.
Lediglich die Datei `tnsnames.ora` muss dann gegebenenfalls erweitert werden.

Zum Abschluss ändern Sie die Berechtigungen der in diesem Abschnitt manuell erstellten Dateien und Verzeichnisse, damit die xref:access[Zugriffsrechte bei der Ausführung] richtig gesetzt sind.
Das Agentenplugin, das als `root` ausgeführt wird, wechselt zum Eigentümer der Oracle-Binärdateien (z.B. `$ORACLE_HOME/bin/sqlplus`), bevor es diese ausführt.
Zumindest die Gruppe des Eigentümers der Oracle-Binärdateien benötigt daher lesenden Zugriff auf die manuell erstellten Dateien in `/etc/check_mk/`.
Im folgenden Beispiel nehmen wir an, dass es sich bei der Gruppe um `oinstall` handelt.

Die folgenden Befehle ändern die Gruppe zu `oinstall`:

[{shell}]
----
{c-root} chgrp oinstall /etc/check_mk/sqlnet.ora /etc/check_mk/tnsnames.ora
{c-root} chgrp -R oinstall /etc/check_mk/oracle_wallet
----

Diese Befehle stellen dann sicher, dass die Gruppe das Verzeichnis `oracle_wallet` samt Inhalt lesen kann:

[{shell}]
----
{c-root} chmod g+x /etc/check_mk/oracle_wallet
{c-root} chmod -R g+r /etc/check_mk/oracle_wallet
----

Anschließend sollten die Berechtigungen etwa wie folgt aussehen:

[{shell}]
----
{c-root} tree -ugpR /etc/check_mk
[drwxr-xr-x root     root    ]  /etc/check_mk
├── [drwxr-x--- root   oinstall ]  oracle_wallet
│   └── [-rw-r----- root   oinstall ]  cwallet.sso
│   └── [-rw-r----- root   oinstall ]  cwallet.sso.lck
│   └── [-rw-r----- root   oinstall ]  ewallet.p12
│   └── [-rw-r----- root   oinstall ]  ewallet.p12.lck
├── [-rw-r--r-- root   oinstall ]  sqlnet.ora
├── [-rw-r--r-- root   oinstall ]  tnsnames.ora
----

Die Befehlsausgabe zeigt nur die Dateien und Verzeichnisse, um die es geht.

Nachdem Sie auf dem Oracle-Host die Voraussetzungen für das Monitoring mit {CMK} geschaffen haben, müssen Sie nun eine Konfiguration für das Agentenplugin erstellen.
Nutzer unserer kommerziellen Editionen erfahren wie das machen können im Kapitel xref:configuration_bakery[Konfiguration für das Agentenplugin per Regel erstellen].

Falls Sie Ihre Oracle-Instanzen mit {CRE} überwachen möchten, lesen Sie jetzt bitte das Kapitel xref:manual_configuration[Überwachung von Oracle manuell einrichten].


[#configuration_bakery]
== Minimale Konfiguration für das Agentenplugin per Regel erstellen
{cee-only}

Als Nutzer einer kommerziellen Edition von {CMK} suchen Sie nun nach dem Regelsatz [.guihint]#Unified Oracle Plugin (Experimental)# und erstellen dort eine neue Regel.

Je nachdem für welchen Weg Sie sich im Kapitel xref:prerequisites[Voraussetzungen auf dem Oracle-Host schaffen] entschieden haben, wählen Sie unter [.guihint]#Authentication type# die passende Option aus und tragen die zugehörigen Daten ein.

Beschränken Sie die Regel im Abschnitt [.guihint]#Conditions# per [.guihint]#Explicit hosts# auf den Host, auf dem Oracle läuft.

Speichern Sie nun die Regel, xref:wato_monitoringagents#bakery[backen Sie das neue Agentenpaket] und installieren Sie dieses auf dem Oracle-Host.

Die Konfigurationsdatei, welche durch diese minimale Konfiguration erzeugt wird, finden Sie im Abschnitt xref:minimal_configuration[Referenzen].

Alle weiteren Optionen der Regel [.guihint]#Unified Oracle Plugin (Experimental)# werden vorerst ausschließlich im Kapitel xref:reference[Referenzen] beschrieben.


//SK: Die manuelle Einrichtung möchte ich als How-to anlegen.
[#manual_configuration]
== Überwachung von Oracle manuell einrichten

Anleitung folgt.
//SK In diesem How-to beschreiben wir, wie Sie Oracle-Datenbanken ohne die Agentenbäckerei einrichten.


[#reference]
== Referenzen

[#options_ruleset]
=== Optionen im Regelsatz [.guihint]#Unified Oracle Plugin#

Im diesem Kapitel erklären wir alle Optionen, die Nutzer einer kommerziellen Edition im Regelsatz [.guihint]#Unified Oracle Plugin (Beta)# finden.
Die Erklärungen hier im Handbuch gehen mitunter über den Inhalt der Inline-Hilfe hinaus, wenn es beispielsweise interessante Hintergrundinformationen zu einer Option gibt und eine längere Erklärung für bestimmte Anwendungsfälle angebracht sind.

Dazu geben wir jeweils auch an, welche Eintragung durch eine gewählte Option in der Konfigurationsdatei `mk-oracle.yml` entsteht.

Nutzer von {CRE} und alle Interessierten finden die Beschreibung aller Optionen der `mk-oracle.yml` in unserer link:https://github.com/Checkmk/checkmk/tree/master/packages/mk-oracle#yaml-configuration[Beschreibung auf GitHub].

// Hier müssen noch Ausführungen zu den Optionen folgen. Warum würden Nutzende bspw. die max_connections limitieren wollen etc pp?

[discrete]
==== Additional Options > Maximum connections

Maximale Anzahl der zu öffnenden Datenbankverbindungen.

.Konfigurationsdatei (Beispiel)
[%collapsible]
====
[#max_connections]
.mk-oracle.yml
[{yaml}]
----
---
oracle:
  main:
    options:
      max_connections: <int>
----
====

[discrete]
==== Additional Options > Maximum queries

Maximale Anzahl der Abfragen, die pro Verbindung ausgeführt werden dürfen.

.Konfigurationsdatei (Beispiel)
[%collapsible]
====
[#max_queries]
.mk-oracle.yml
[{yaml}]
----
---
oracle:
  main:
    options:
      max_queries: <int>
----
====


[discrete]
==== Additional Options > Ignore database name

.Konfigurationsdatei (Beispiel)
[%collapsible]
====
[#ignore_db_name]
.mk-oracle.yml
[{yaml}]
----
---
oracle:
  main:
    options:
      IGNORE_DB_NAME: "0|1"
----
====

[discrete]
==== Additional Options > Oracle Instant Client options

.Konfigurationsdatei (Beispiel)
[%collapsible]
====
[#use_host_client]
.mk-oracle.yml
[{yaml}]
----
---
oracle:
  main:
    options:
      use_host_client: "auto|never"
----
====


[discrete]
==== Authentication > Authentication type > Oracle Wallet

Oracle Wallet bietet eine sichere Möglichkeit, sich bei Oracle-Datenbanken zu authentifizieren, ohne Passwörter im Klartext in Konfigurationsdateien zu speichern.

.Konfigurationsdatei (Beispiel)
[%collapsible]
====
[#authentication_type_wallet]
.mk-oracle.yml
[{yaml}]
----
---
oracle:
  main:
    authentication:
      type: wallet
----
====


[discrete]
==== Authentication > Authentication type > User & password > Username

.Konfigurationsdatei (Beispiel)
[%collapsible]
====
[#authentication_username]
.mk-oracle.yml
[{yaml}]
----
---
oracle:
  main:
    authentication:
      username: 'myuser'
----
====


[discrete]
==== Authentication > Authentication type > User & password > Password

.Konfigurationsdatei (Beispiel)
[%collapsible]
====
[#authentication_password]
.mk-oracle.yml
[{yaml}]
----
---
oracle:
  main:
    authentication:
      password: 'myuser'
----
====

[discrete]
==== Authentication > Role 

.Konfigurationsdatei (Beispiel)
[%collapsible]
====
[#authentication_role]
.mk-oracle.yml
[{yaml}]
----
---
oracle:
  main:
    authentication:
      role: "sysdba|sysasm"
----
====


[discrete]
==== Authentication > Type

.Konfigurationsdatei (Beispiel)
[%collapsible]
====
[#authentication_type]
.mk-oracle.yml
[{yaml}]
----
---
oracle:
  main:
    authentication:
      type: 'standard'
----
====

[#example_configuration]
=== Beispielkonfigurationen

[#minimal_configuration]
==== Minimal 

Die folgende Konfigurationsdatei entsteht, wenn Sie eine Regel wie im Tutorial xref:tutorial_monitoring_oracle01#[Alle Datenbanken auf einem Host überwachen] erstellen.
Nutzer von {CRE} können dieses 

.mk-oracle.yml
[{yaml}]
----
---
oracle:
  main:
    authentication:
      password: diebels
      type: standard
      username: C##checkmk
    cache_age: 600
    connection:
      hostname: localhost
    custom_metrics_cache_age: 600
    instances: []
----
