// -*- coding: utf-8 -*-
include::global_attr.adoc[]

= Analyse der Produktnutzung
:title: Analyse der Produktnutzung
:description: TODO

[#intro]
== Einleitung

{CMK} bietet eine Vielzahl von Features, die kontinuierlich xref:cmk_versions.html[weiterentwickelt und verbessert] werden.
Für die Entwicklungsarbeit an der Software birgt Ihr Nutzungsverhalten wertvolle Informationen:
Welche Features nutzen Sie oft?
Wie viele Objekte überwachen Sie?
Nutzen Sie das Grafana-Plugin, und falls ja, in welcher Version?
// ES: prüfen, ob auch andere Plugin-Informationen gesammelt werden bzw. ob wirklich das Grafana-Plugin eine Sonderstellung hat

Diese und ähnliche Informationen über Ihre Nutzung von {CMK} können uns helfen, die wichtigsten Features bei der Entwicklung besonders hoch zu priorisieren.
Kaum genutzte Features oder Plugins dagegen können eine niedrigere Priorität erhalten oder nach einer gewissen Zeit ganz abgekündigt werden.
// ES: andersrum formulieren: "avoid deprecations for used features"

Ab Version {v25} kann {CMK} Daten über Ihre Produktnutzung automatisch in regelmäßigen Abständen an die {comfull} übermitteln.
// ES: Ist {comfull} hier die sinnvollste Formulierung?
ifdef::onprem[]
Als Admin von {CMK}-Instanzen entscheiden Sie selbst, ob Sie diese Datenübermittlung zulassen, um die Weiterentwicklung der Software auf diese Weise mit zu beeinflussen.
endif::[]

// ES: Laut "Brain Dump" wird Produkttelemetrie auch in 2.4.0 und 2.3.0 verfügbar sein. Vor Fertigstellung des Artikels nachhaken, was der exakte Zeitpunkt ist, ab dem dieser Artikel für Lesende relevant ist.

ifdef::onprem[]
[#consent]
== Datenübermittlung erlauben oder ablehnen

{CMK} wird Sie selbständig darum bitten, eine Entscheidung zur Übermittlung von Nutzungsdaten zu treffen.
Ein Dialog dazu wird Ihnen 30 Tage nach dem Update auf Version {v25} beziehungsweise 30 Tage nach dem Anlegen einer neuen Instanz mit Version {v25} in der GUI angezeigt.

=== Einstellungen in der GUI

Die Entscheidung über die Übermittlung von Nutzungsdaten obliegt denjenigen Benutzern Ihrer Instanz, die Administratorrechte haben.
Das trifft auf Ihren Instanzbenutzer zu, der typischerweise `cmkadmin` heißt, sowie auf alle anderen Benutzer, die zur xref:wato_user#roles[Rolle] [.guihint]#Administrator# gehören.

Sobald ein solcher Benutzer sich nach Ablauf von 30 Tagen in der Weboberfläche Ihrer {CMK}-Instanz anmeldet, erscheint ein Pop-up zur Analyse der Produktnutzungsdaten.

(Screenshot hier)
// ES: Screenshot einfügen

Klicken Sie auf [.guihint]#Configure in global settings#, um festzulegen, ob Ihre Instanz Nutzungsdaten übermitteln darf.
Falls Sie noch nicht bereit sind, diese Entscheidung zu treffen, verbleibt die Einstellung automatisch auf [.guihint]#Disabled. Reminder scheduled#.
In diesem Fall wird das Pop-up bei jedem Login eines Admin-Benutzers angezeigt, bis die Einstellung geändert wird.

Um die Übermittlung von Nutzungsdaten zu erlauben, wählen Sie die Einstellung [.guihint]#Allow collection and transmission of telemetry data#.
Sie können dann noch Details zum [.guihint]#HTTP proxy# hinterlegen, der verwendet werden soll.
Diese Informationen werden benötigt, falls von Ihrem {CMK}-Server aus keine direkte Verbindung nach außen möglich oder gewünscht ist.
// ES: konkreter beschreiben oder auf andere Quellen verweisen, in denen über Proxy settings gesprochen wird

Selbstverständlich können Sie die Übermittlung auch ablehnen.
In diesem Fall sind keine weiteren Einstellungen notwendig.
Nachdem Sie die Option [.guihint]#Do not collect and transmit telemetry data# ausgewählt haben, werden Sie keine weiteren Aufforderungen zum Übermitteln von Daten erhalten.


=== Einstellungen in Ihrer Systemumgebung

Möglicherweise sind noch zusätzliche Einstellungen in Ihrer Systemumgebung nötig, bevor die Daten an die {comfull} gesendet werden können.
Erlauben Sie in Ihren Firewall-Einstellungen Verbindungen vom {CMK}-Server zu `\https://analytics.checkmk.com/upload` beziehungsweise zur IP-Adresse `10.10.10.10` über Port 443.
// ES: alles hier korrigieren, sobald endgültige Informationen bereitgestellt wurden

// ES: wie kann man verifizieren, ob es klappt

endif::[]

[#usage_data]
== Ihre Nutzungsdaten
ifdef::onprem[]
Damit Sie entscheiden können, ob Sie mit der Übermittlung von Nutzungsdaten einverstanden sind, geben wir Ihnen hier einen Überblick darüber, welche Nutzungsdaten gemeint sind und wie sie gesammelt und verarbeitet werden.
endif::[]
ifdef::saas[]
Hier geben wir Ihnen einen Überblick darüber, welche Nutzungsdaten gemeint sind und wie sie gesammelt und verarbeitet werden.
endif::[]

[#manifest]
=== Welche Daten werden übermittelt?

Selbstverständlich werden nur anonymisierte Daten gesammelt und übermittelt.
Sensible Daten über Sie oder über die Inhalte Ihrer Instanz werden weder erhoben noch an {com} gesendet.

ifdef::onprem[]
Klicken Sie beim Konfigurieren Ihrer Einstellungen für die Analyse der Produktnutzung auf [.guihint]#Show product usage analytics manifest#, um die vollständige Liste aller zu sammelnden Daten anzuzeigen.
// ES: Sicherstellen, dass ein solcher Knopf und das vollständige Manifest tatsächlich in der Software existiert

(Screenshot hier)

Ihre Nutzungsdaten werden in Form eines JSON-Objekts dargestellt.

Um zu erfahren, welche Daten Ihre Instanz zum aktuellen Zeitpunkt übermitteln würde, können Sie als Instanzbenutzer den Befehl `cmk-telemetry --dry-run` ausführen.
// ES: sicherstellen, ob der Befehl weiterhin so heißt oder umbenannt wurde

[{shell}]
----
{c-omd} cmk-telemetry --dry-run
{
  "metadata": {
    "version": "v1",
    "namespace": "checkmk",
    "name": "telemetry"
  },
  "data": {
    "id": "e35dc748-a63e-4c99-8d8a-70a5ec38f1fc",
    "count_hosts": 0,
    "count_services": 0,
    "count_folders": 0,
    "edition": "pro",
    "cmk_version": "2.6.0-2026.01.26",
    "timestamp": 1769594052,
    "checks": {},
    "grafana": null
  }
}
----
// ES: Vor Veröffentlichung aktualisieren, sinnvolle cmk_version einfügen
// ES: sinnvolle Beispieldaten generieren, damit das JSON aussagekräftig wird

Wie Sie in der Beispielausgabe sehen, werden vor allem quantitative Daten gesammelt.

Der Befehl `cmk-telemetry --dry-run` führt im Hintergrund alle Aktionen zum Sammeln der Daten aus, sendet aber keine Daten nach außen.
Er dient allein zu Ihrer Information.
Sie können ihn jederzeit ausführen, unabhängig von Ihren Einstellungen für die Analyse der Produktnutzung.
Übrigens wird die Sammlung von Nutzungsdaten mithilfe einer Reihe von xref:livestatus#[Livestatus-Abfragen] umgesetzt.
endif::[]


[#processing]
=== Was passiert mit den Daten?

ifdef::onprem[]
Falls Sie sich entschieden haben, Ihre Produktnutzungsdaten an die {comfull} übermitteln zu lassen, läuft ab jetzt alles im Hintergrund.
Es ist vorstellbar, dass dabei gelegentlich Probleme auftauchen, zum Beispiel wenn Ihr Server zum Zeitpunkt der Übermittlung nicht in der Lage ist, eine Verbindung zum Server der {comfull} aufzubauen.
In diesem Fall schlägt der Vorgang fehl, ohne dass Sie darüber informiert werden.
endif::[]
ifdef::saas[]
Die Sammlung und Übertragung Ihrer Produktnutzungsdaten läuft vollständig im Hintergrund ab.
Es ist vorstellbar, dass dabei gelegentlich technische Probleme auftauchen.
In diesem Fall schlägt der Vorgang fehl, ohne dass Sie darüber informiert werden.
endif::[]
// ES: in CMK-27997 nachgefragt, ob "fail silently" tatsächlich implementiert ist und ob irgendwelche Log messages geschrieben werden


[#transmission]
==== Übermittlung an die {comfull}

ifdef::onprem[]
Zu einem zufälligen Zeitpunkt in den ersten 30 Tagen nach dem Erteilen Ihrer Zustimmung wird der erste Datensatz zusammengestellt und versendet.
Ab diesem Zeitpunkt wird die Sammlung und Übermittlung immer im Abstand von 30 Tagen wieder ausgeführt.

Ihre Instanz übermittelt die gesammelten Daten mit einer POST-Anfrage an `\https://analytics.checkmk.com/upload` beziehungsweise an die IP-Adresse `10.10.10.10` über Port 443.
// ES: korrigieren, nachdem endgültige Infos hierüber bereitgestellt wurden
endif::[]

ifdef::saas[]
Ihre Nutzungsdaten werden jeweils im Abstand von 30 Tagen gesammelt und übermittelt.
Die erste Übermittlung findet zu einem zufälligen Zeitpunkt innerhalb der ersten 30 Tage nach dem Anlegen Ihrer Instanz statt.
// ES: sicherstellen, ob das wirklich so ist
endif::[]

// ES: encryption?


[#storage_and_analysis]
==== Speicherung und Auswertung

ifdef::onprem[]
Unabhängig davon, wo Sie Ihre {CMK}-Instanz betreiben, werden Ihre Nutzungsdaten immer an einen Server der {comfull} in der AWS-Region Europe (Frankfurt) übermittelt (`eu-central-1`).
endif::[]
ifdef::saas[]
Ihre Nutzungsdaten werden immer an einen Server der {comfull} in der AWS-Region Europe (Frankfurt) übermittelt (`eu-central-1`).
endif::[]
Die Datensätze, die Ihre Instanz an diesen Server schickt, werden nicht mit Ihren persönlichen Daten verknüpft.
Sie werden anonym ausgewertet.

ifdef::onprem[]
// ES: Stimmt es, dass in saas kein verteiltes Monitoring möglich ist?
[#distributed]
== Nutzungsdaten im verteilten Monitoring
TODO
// ES: pop-up only on central site; central site will push configuration to remote sites; same with multi-tenancy
// ES: no special data about multi-tenancy setups will be collected
endif::[]