// -*- coding: utf-8 -*-
// IGNORE SP7 Trixie versionen
include::global_attr.adoc[]
:current: pass:q[[.new]#2.4.0#]
ifdef::onprem[]
= Release notes
:revdate: 2025-02-26
:title: Release notes - Versionshinweise für {CMK} {current}
:description: Checkmk 2.4.0 funktioniert mit einer Reihe von Plattformen und Integrationen, die während der aktiven Pflege im Produkt-Lifecycle unterstützt werden.
endif::[]
ifdef::saas[]
= Systemvoraussetzungen für {CE}
:revdate: 2025-02-17
:title: Systemvoraussetzungen für die Nutzung {CE}
:description: {CE} funktioniert mit einer Reihe von Plattformen und Integrationen, die während des Produkt-Lifecycle unterstützt werden.
endif::[]

{related-start}
ifdef::onprem[]
xref:update_major#[Update auf Version 2.4.0]
xref:update_matrix#[Update-Matrix für Version 2.4.0]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
endif::[]
xref:agent_linux#[Linux überwachen]
xref:agent_windows#[Windows überwachen]
{related-end}


== Einleitung

ifdef::onprem[]
Dieses Dokument listet die unterstützten Plattformen und Integrationen von {CMK} {current} auf.
Sofern keine besonderen Gründe vorliegen (z. B. Sicherheit), werden diese Plattformen während der aktiven Pflege im {CMK} {current} Produkt-Lifecycle einschließlich aller Patch-Versionen unterstützt.
endif::[]
ifdef::saas[]
Dieses Dokument listet die unterstützten Plattformen und Integrationen von {CE} auf.
endif::[]

ifdef::onprem[]
[#os]
== OS für den Server

{CMK} kann auf den folgenden Linux-Server-Betriebssystemdistributionen und -versionen installiert werden, die auf x86_64-Hardware laufen.
Dazu geben wir eine Liste der unterstützen Versionen heraus.
Einträge können folgende Zusätze enthalten:

* _Deprecated:_ So gekennzeichnete LTS/LTSS Versionen werden noch während des gesamten Lebenszyklus von Version {current} unterstützt und fallen danach aus dem Support heraus.
* _Once released:_ Die Unterstützung für diese Versionen ist geplant. Die Bereitstellung von {CMK} {current} Paketen erfolgt zeitnah nach Erscheinen der neuen Distributionsversion.

Wir werden auch neue Versionen dieser Distributionen für die Unterstützung evaluieren.
Diese entnehmen Sie der xref:update_matrix#[Update-Matrix.]

[cols="33,~",options=header]
|===
|Betriebssystem |Unterstützte Versionen
|Debian |11 Bullseye (deprecated)
| |12 Bookworm
| |13 Trixie (once released)
|Red Hat Enterprise Linux |8
| |9
| |10 (once released)
|SUSE Linux Enterprise Server |15 SP3 (deprecated)
| |15 SP4 (deprecated)
| |15 SP5
| |15 SP6
| |15 SP7 (once released)
| |16 (once released)
|Ubuntu |22.04 LTS Jammy Jellyfish
| |24.04 LTS Noble Numbat
| |26.04 LTS _Some cute animal starting with 'R'_ (once released)
|===
endif::[]

[#browser]
== Browser

Die {CMK}-Benutzeroberfläche ist für die folgenden Desktop-Browser und Mindestversionen geprüft:

// MFS: Should be in sync for 2.4 again!
ifdef::onprem[]
* Google Chrome >= 125 unter Windows, Linux und macOS
* Firefox >= 133 unter Windows, Linux und macOS
* Microsoft Edge >= 131 unter Windows
* Safari >= 17.2 unter macOS
endif::[]
ifdef::saas[]
* Google Chrome >= 130 unter Windows, Linux und macOS
* Firefox >= 128 unter Windows, Linux und macOS
* Microsoft Edge >= 130 unter Windows
* Safari >= 18.1 unter macOS
endif::[]


Die mobile {CMK}-Benutzeroberfläche ist für die folgenden mobilen Browser geprüft:

* Safari unter iPadOS/iPhoneOS (aktuelle und letzte Hauptversion des Betriebssystems)
* Google Chrome unter Android (aktuelle und letzte Hauptversion des Betriebssystems)

[#agent]
== OS für den {CMK}-Agenten

Der {CMK}-Agent kann auf den folgenden Betriebssystemen installiert und betrieben werden, wenn grundlegende Anforderungen erfüllt sind.

// MFS: Should be splitted for 2.4 to "Linux with Agent Controller" and "Linux/Unix legacy mode"
ifdef::onprem[]
=== Linux/Unix

Alle Linux-Distributionen und diverse Unix-Betriebssysteme wie _Solaris_ und _AIX_ werden unterstützt, sofern sie mindestens die folgenden technischen Komponenten in der minimalen Version mitbringen:

* Bash >= 4.2
* ksh >= 93
* Perl >= 5.14.0

Zusätzlich muss eine der folgenden Komponenten vorhanden sein:

* systemd >= 219
* xinetd (keine Mindestversion)

Beachten Sie: Es kann sein, dass Plugins für ihre Funktion zusätzliche Komponenten benötigen.
Python-Plugins erfordern Version 2.7 oder > 3.5.
endif::[]

ifdef::saas[]
=== Linux

Alle xref:agent_linux#[Linux-Distributionen auf `x86/64`] werden unterstützt, sofern sie mindestens die folgenden technischen Komponenten in der minimalen Version mitbringen:

* Bash >= 4.2
* ksh >= 93
* Perl >= 5.14.0

Zusätzlich muss die folgende Komponente vorhanden sein:

* systemd >= 219

Beachten Sie: Es kann sein, dass Plugins für ihre Funktion zusätzliche Komponenten benötigen.
Python-Plugins erfordern Versionen > 3.5.
endif::[]


[#windows]
=== Windows

Alle folgenden 64-Bit-Versionen der xref:agent_windows#[Windows Betriebssysteme] werden unterstützt:

* 2016
* 2019
* 2022
* 2025

ifdef::onprem[]
Für ältere Systeme stellen wir einen link:https://download.checkmk.com/legacy-agents/[Legacy Agenten^] bereit. Dieser hat ein geringeres Feature-Set und wird nicht offiziell unterstützt.
endif::[]


ifdef::onprem[]
[#grafana]
== Grafana Plugin

{CMK} {current} unterstützt die folgenden Grafana Plugin Versionen:

* >= 3.0.0
endif::[]


ifdef::onprem[]
[#appliance]
== {CMK} Appliance

{CMK} {current} kann auf den folgenden Versionen der {CMK} Appliance ausgeführt werden:

* >= 1.7.0
endif::[]


ifdef::onprem[]
[#ldap]
== LDAP-Server

{CMK} {current} unterstützt die Synchronisierung mit LDAP der folgenden LDAP-Server:

* Microsoft Active Directory
* OpenLDAP
* 389 Directory Server


[#saml]
== SAML IdP

Die SAML-Integration unterstützt die folgenden Identity Provider (IdPs):

* Microsoft Entra ID (hieß bis 2023 Azure Active Directory)
* Google Cloud
* Okta

{CMK} arbeitet möglicherweise auch mit anderen SAML-Integrationen zusammen, aber für diese kann keine Unterstützung gegeben werden.
endif::[]


ifdef::onprem[]
[#ntopng]
== ntopng

Die ntopng-Integration unterstützt die folgenden Versionen von ntopng Professional und Enterprise:

* >= 6.0
endif::[]


ifdef::onprem[]
[#nagvis]
== Nagvis

Nagvis hängt von PHP ab und benötigt eine Mindestversion, um zu laufen.
Stellen Sie sicher, dass Sie eine passende PHP-Version in Ihrer Installation haben, um Nagvis auszuführen:

* >= 7.2

Je nach verwendeter Linux-Distribution kann die als Abhängigkeit des {CMK}-Installationspaketes definierte Version höher sein.
endif::[]


ifdef::onprem[]
[#influxdb]
== InfluxDB

{CMK} unterstützt den Export von Daten an die folgenden Versionen der InfluxDB API:

// MFS: Check back with devs 
* >= 2.0
endif::[]

ifdef::saas[]
== Änderungsprotokoll

=== Korrekturen

==== 17. Februar 2025

* Windows 2025 wurde nach Tests zur Liste der unterstützten Betriebssysteme für Agenten hinzugefügt.
endif::[]

