// -*- coding: utf-8 -*-
// IGNORE
// NONASCII
include::global_attr.adoc[]
= Das eigene System überwachen
:title: Das eigene System überwachen
:description: {CMK} kann nicht nur andere Systeme überwachen, auch das Monitoring der eigenen Gesundheit ist möglich. Lesen Sie hier mehr dazu.

{related-start}
xref:monitoring_basics#[Grundlagen des Monitorings mit {CMK}]
xref:hosts_setup#[Verwaltung der Hosts]
xref:wato_rules#[Regeln]
{related-end}


[#intro]
== Einleitung

Im xref:intro_setup_monitor.html#linux[Leitfaden für Einsteiger] haben wir Ihnen gezeigt, wie man die Basis schafft, um den {CMK}-Server zu überwachen.
Im folgenden Artikel geht es nun darum, diese Überwachung sinnvoll mit Leben zu füllen.
Schließlich kann {CMK} nicht nur prüfen, ob der {CMK}-Server läuft, sondern es gibt noch weitaus mehr Parameter, die geprüft -- und in der Folge auch optimiert -- werden können.


[#discovery]
== Prozesserkennung

In der Prozesserkennung beispielsweise existieren vorgefertigte Regeln für spezifische Services zur Selbstüberwachung.
Dorthin gelangen Sie über [.guihint]#Setup > Services > Discovery rules > Discovery of individual services > Process discovery#.

Für jeden Host, der das Host-Merkmal `cmk/check_mk_server:yes` trägt, werden dank den mitgelieferten Regeln automatisch folgende Services gefunden:

[multicol]
* [.guihint]#Process myhost active check helpers#
* [.guihint]#Process myhost agent receiver#
* [.guihint]#Process myhost alert helper#
* [.guihint]#Process myhost apache#
* [.guihint]#Process myhost automation helpers#
* [.guihint]#Process myhost checker helpers#
* [.guihint]#Process myhost cmc#
* [.guihint]#Process myhost dcd#
* [.guihint]#Process myhost event console#
* [.guihint]#Process myhost fetcher helpers#
* [.guihint]#Process myhost jaeger# + 
(nicht permanent sichtbar)
* [.guihint]#Process myhost livestatus proxy#
* [.guihint]#Process myhost notification spooler#
* [.guihint]#Process myhost notify helper#
* [.guihint]#Process myhost piggyback hub# +
(nicht permanent sichtbar)
* [.guihint]#Process myhost rabbitmq# +
(nur bei aktiviertem Piggyback-Hub)
* [.guihint]#Process myhost real-time helper# +
(nur bei aktivierten Realtime-Checks)
* [.guihint]#Process myhost redis-server#
* [.guihint]#Process myhost rrd helper#
* [.guihint]#Process myhost rrdcached#

Jede Regel, die Sie nicht benötigen, können Sie sowohl deaktivieren als auch löschen.
Wir empfehlen, nicht benötigte Regeln zu deaktivieren, insbesondere, wenn Sie keine der Regeln nutzen wollen.
Denn wenn Sie alle Regeln löschen -- anstatt sie nur zu deaktivieren -- , dann werden beim nächsten Einspielen eines {CMK}-Patches alle Regeln erneut erstellt.

Was Sie nun mit diesen Services anfangen können, lesen Sie im Artikel xref:wato_services#[Services verstehen und konfigurieren].
Was genau die Prozesse leisten, die hier als Services ins Monitoring aufgenommen werden, finden Sie im Artikel über die xref:cmk_processes#[Instanzdienste] beschrieben.


[#plug-ins]
== Selbstüberwachung des Systems (Plugins)

Auch im link:https://checkmk.com/integrations[Katalog der Check-Plugins^] gibt es diverse Möglichkeiten zur Selbstüberwachung Ihres Systems.
Teilweise sind diese bereits standardmäßig in Ihrem System aktiviert, so dass Sie kein zusätzliches Plugin benötigen.
Die folgende Tabelle gibt dennoch eine Gesamtübersicht:

[cols=4,options="header"]
|====
|Plugin-Name / +
Manual Page Titel | Funktion | Parameter | Ausgabe
|bi_aggregation / +
Checkmk: State of BI Aggregation |Gibt den Status eines xref:bi#[BI-Aggregats] aus. Zeigt auch an, ob sich das Aggregat derzeit in einer Wartungszeit befindet oder quittiert wurde. |Name des Aggregats |ein Service pro BI-Aggregat
|bi_aggregation_connection / +
Checkmk: Status Information for BI Aggregation Connection |Status-Informationen zum Spezialagenten agent_bi. Beinhaltet Verbindungsfehler, fehlende Instanz-Daten und fehlende Aggregate aufgrund fehlender Daten. | n/a |ein Service pro Verbindung
|check-mk / +
Checkmk: Retrieval of Information |Ruft Statusinformationen aus den konfigurierten Datenquellen ab, z.B. von konfigurierten Agenten, Spezialagenten, SNMP, Piggyback-Daten und Management-Boards. Der von den Ergebnissen abhängige Gesamtstatus des Services kann mit dem Regelsatz [.guihint]#Status of the {CMK} services# konfiguriert werden. Aktualisiert auch alle passiven Services und eventuelle Piggyback-Daten des Hosts. |n/a |n/a
|check-mk-inventory / +
Checkmk: Discovery Procedure |Wird auf neuen Instanzen automatisch erstellt. Geht automatisch auf {WARN}, sobald sich ein Service der Host-Merkmale ändert. Eine Konfiguration ist über den Regelsatz [.guihint]#Periodic service discovery# möglich. Hier kann auch ein automatisches Update der {CMK}-Konfiguration mit den gefundenen Services aktiviert werden. |n/a |ein Service für jeden Host, der diesen Check unterstützt
|checkmk_agent / +
Checkmk Agent: Deployment properties |Stellt die ordnungsgemäße Funktion des {CMK}-Agent-Bereitstellungsmechanismus (falls verwendet) sicher. Überprüft den Zeitpunkt der letzten erfolgreichen Verbindung zum Bereitstellungsserver und das Vorliegen von Fehlermeldungen, zeigt die Anzahl der bereitgestellten Agentenplugins und lokalen Checks. Weitere Einstellungen sind möglich, siehe die link:https://checkmk.com/integrations/checkmk_agent[Plugin-Beschreibung^] |n/a |ein Service
|cmk_site_statistics / +
Number of hosts and services per state of Checkmk sites | Überwacht die Anzahl der Hosts und Services von {CMK}-Standorten, meldet die Gesamtzahl der Hosts, die Anzahl der Hosts, die nicht {UP} sind, sowie die Anzahl der Hosts, die {UP}, {DOWN}, in Wartungszeit und {UNREACH} sind. Meldet die Gesamtzahl der Services, die Anzahl der Services, die nicht {OK} sind, sowie die Anzahl der Services, die {OK} sind, sich in Wartungszeit befinden, auf ausgefallenen Hosts laufen, {WARN}, {UNKNOWN} und {CRIT} sind. Der Check ist immer {OK} und nicht vom Benutzer konfigurierbar. |Name der {CMK}-Instanz |ein Service pro laufender {CMK}-Instanz auf einem {CMK}-Server
|livestatus_status / +
Checkmk: Performance and Settings |Erhält über xref:glossar#livestatus[Livestatus] verschiedene Performance-Daten eines OMD Monitoring-Kerns. Gibt damit Auskunft über die Leistung des Kerns, die Anzahl der pro Sekunde ausgeführten Checks usw. Stellt fest, ob bestimmte Einstellungen deaktiviert wurden (z. B. Benachrichtigungen). Zustände können über Check-Parameter konfiguriert werden. |Name der OMD-Instanz |ein Service pro laufender OMD-Instanz.
|mkbackup / +
Checkmk Appliance: Backup Job State |Prüft den Status von Backup-Aufträgen auf einer {CMK} Appliance. Meldet {CRIT}, wenn der Auftrag fehlschlägt oder seine nächste Ausführung überfällig ist. |ID des Auftrags |ein Service pro Backup-Auftrag
|mkbackup_site / +
Checkmk Site: Backup Job State |Prüft den Status der xref:backup#[Backup]-Aufträge einer {CMK}-Instanz. Meldet {CRIT}, wenn der Auftrag fehlschlägt oder seine nächste Ausführung überfällig ist. |ID der Instanz, gefolgt von `{{backup}}`` und der ID des Auftrags |ein Service pro Instanz und Backup-Auftrag
|mkeventd_status / +
Checkmk Event Console: Status and Performance |Erhält diverse Performancewerte einer Instanz vom Typ {CMK} xref:glossar#ec[Event Console]. Warnung bei aktiven Ereignislimits, Aufzeichnung von Performance-Metriken bzgl. der Event Console. Der Check ist nicht vom Benutzer konfigurierbar. |Name der {CMK}-Instanz |ein Service pro laufender {CMK}-Instanz
|mknotifyd_connection_v2 / +
Checkmk Notification Spooler: Connection |Prüft den Status einzelner TCP-Verbindungen vom {CMK}-Benachrichtigungs-Spooler zu einem Remote-Spooler. Für jede ein- und ausgehende TCP-Verbindung wird ein Service erstellt. Der Status geht auf {CRIT}, wenn die Verbindung nicht aufgebaut ist. |Name der Instanz, gefolgt vom Namen der verbundenen Remote-Instanz, getrennt durch einen Strich. Gibt es mehr als eine eingehende Verbindung vom gleichen Remote-Host, wird ein Index angehängt. Der Check ist nicht vom Benutzer konfigurierbar. |ein Service pro Instanz und Verbindung
|mknotifyd / +
Checkmk Notification Spooler: Status |Prüft den Status des {CMK}-xref:notifications#async[Benachrichtigungs-Spooler]. {WARN}, wenn zurückgestellte Spool-Dateien zu lange liegen bleiben oder beschädigte Spool-Dateien gefunden werden. {CRIT}, wenn Spooler nicht läuft. Der Check ist nicht vom Benutzer konfigurierbar. |Name der Instanz | ein Service pro Instanz
|omd_apache / +
Checkmk Sites: Apache Access Statistics |Erstellt Statistiken über die Anfragen, die vom Apache Webserver auf OMD-Instanzen bearbeitet werden. Er zeichnet die Anzahl der Anfragen, die gesendeten Bytes und die für die Bearbeitung der Anfragen benötigte Zeit auf. Es wird gruppiert nach Art der Anfrage, z. B. {CMK}-Tabellenansichten, NagVis-AJAX-Aufrufe, aber auch nach Typ, z. B. für Bilder, Stylesheets usw. Der Check verwendet eine bestimmte Logdatei, die sich unter `~/var/log/apache/stats` befinden muss, um die Zugriffsstatistiken zu erfassen. Diese Datei wird bei jeder Überprüfung gekürzt. Der Check ist immer {OK} und nicht vom Benutzer konfigurierbar. |Name der Instanz |ein Service pro Instanz
|omd_broker_queues / +
Checkmk: Site Broker Queues |Überwacht die Anzahl der Benachrichtigungen in Broker-Warteschlangen jeder Instanz-Applikation. Service-Name enthält die Instanz und den Applikationsnamen. Der Check ist immer {OK}. |Instanz und Applikationsname |ein Service pro Instanz-Applikation
|omd_broker_status / +
Checkmk: Site Broker Status |Überwacht den allgemeinen Status des Message Brokers auf jeder Instanz. Zeigt den vom Broker belegten Speicher, die Zahl der Warteschlangen und die Zahl der Shovels im Status _running_. Der Check ist immer {OK}. |Name der Instanz |ein Service pro Instanz, auf der ein Broker installiert ist und läuft
|omd_diskusage / +
Checkmk: Site disk usage |Überwacht die Festplattenauslastung einer Instanz, um bei Bedarf die Suche nach Anomalien zu erleichtern. Eine Liste der aktuell überwachten Verzeichnisse finden Sie in der link:https://checkmk.com/integrations/omd_diskusage[Plugin-Beschreibung^]. Der Check ist immer {OK} und nicht vom Benutzer konfigurierbar. |Name der Instanz |ein Service pro Instanz
|omd_status / +
Checkmk: Site Status |Prüft den Status der OMD-Instanzen, die auf dem System gefunden wurden, mithilfe von `omd status --bare --auto`. Wenn alle Services laufen, ist die Instanz {OK}, andernfalls {CRIT}. Wenn die Instanz nur teilweise läuft, enthält die Check-Ausgabe die Namen der gestoppten Services. In geclusterten Umgebungen listet der Check alle Knoten, auf denen Instanzen laufen, sowie deren Status auf. Der Gesamtstatus des Services ist {CRIT}, wenn eine Instanz auf einem Knoten nur partiell läuft oder alle Instanzen auf allen Knoten gestoppt sind. Der Check ist nicht vom Benutzer konfigurierbar. | Name der Instanz |ein Service je Instanz, auf der die Option [.guihint]#Autostart# auf `ON` gesetzt ist, unabhängig vom aktuellen Instanz-Status
|site_object_counts / +
Checkmk: Site Objects |Sammelt Informationen über die Anzahl unterschiedlicher Host-Typen oder genutzter Check-Kommandos auf den {CMK}-Instanzen. Einstellung und Funktionalität des Checks sind umfangreich, weitere Informationen hierzu finden Sie in der link:https://checkmk.com/integrations/site_object_counts[Plugin-Beschreibung^]. Der Check ist immer im Status {OK}. |n/a |ein Service

|====


