// -*- coding: utf-8 -*-
// IGNORE tos 0er OIC
// NONASCII │ ├ └ ─ …​
include::global_attr.adoc[]
= Tutorial: Alle Oracle-Datenbanken auf einem Host überwachen
:title: Tutorial: Alle Oracle-Datenbanken auf einem Host überwachen
:description: In diesem Tutorial zeigen wir, wie Sie eine einfache Oracle-Instanz auf einem Host in wenigen Schritten in ihr Monitoring aufnehmen können.

In diesem Tutorials erklären wir, wie Sie mit dem neuen Agentenplugin `mk-oracle` eine einfache Oracle-Instanz in ihr Monitoring aufnehmen können.

Die vollständige Erklärung finden Sie im Artikel xref:monitoring_oracle[Oracle-Datenbanken überwachen].

[#tutorial_all_databases]
== Alle Oracle-Datenbanken auf einem Host überwachen

In der Standardeinstellung versucht das Agentenplugin `mk-oracle` alle Instanzen auf einem Host zu finden und alle Datenbanken darin zu überwachen.
In diesem Fall müssen Sie also kaum Einstellungen für das Agentenplugin vornehmen.
Wir gehen hier davon aus, dass die Überwachung mit einem zentralen User erfolgen kann.

=== Voraussetzungen

In diesem Tutorial gehen wir davon aus, dass der Host, auf dem Oracle Database läuft, bereits mit dem {CMK}-Agenten überwacht wird.
Außerdem setzen wir voraus, dass der xref:monitoring_oracle#install_oic[Oracle Instant Client bereits auf dem Host installiert] ist.

=== Datenbankbenutzer erstellen

Verbinden Sie sich als erstes mit Ihren Oracle-Host und wechseln Sie zum `oracle`-Benutzer.

[{shell}]
----
{c-root} su - oracle
----

Geben Sie abschließend die Instanz bekannt, mit der sich `sqlplus` verbinden soll:

[{shell}]
----
oracle@linux$ export ORACLE_SID=MYINST1
----

Starten Sie `sqlplus`.
Geben Sie dabei an, mit welcher Rolle `sqlplus` starten soll.

[{shell}]
----
oracle@linux$ sqlplus / as sysdba
----

Erzeugen Sie jetzt einen Benutzer, welcher ausschließlich für die Überwachung von Oracle verwendet werden soll.
Das Präfix `C##` sorgt dafür, dass der Nutzer alle Datenbanken der Instanz sehen kann.
Die Berechtigungen gelten für alle existierenden und zukünftigen Datenbanken.

[{sql}]
----
sqlplus> create user C##checkmk identified by myPassword;
sqlplus> alter user C##checkmk set container_data=all container=current;
sqlplus> grant select_catalog_role to C##checkmk container=all;
sqlplus> grant create session to C##checkmk container=all;
sqlplus> exit
----

=== Konfiguration für das Agentenplugin erstellen

Als Nutzer einer kommerziellen Edition von {CMK} suchen Sie nun nach dem Regelsatz [.guihint]#Unified Oracle Plugin# und erstellen dort eine neue Regel.

Füllen Sie dort nur die Felder [.guihint]#Username# und [.guihint]#Password# mit den Daten aus, die Sie im Schritt zuvor bei `create user` angegeben haben.

Beschränken Sie die Regel im Abschnitt [.guihint]#Conditions# per [.guihint]#Explicit hosts# auf den Host, auf dem Oracle läuft.

Speichern Sie nun die Regel, xref:wato_monitoringagents#bakery[backen Sie das neue Agentenpaket] und installieren Sie dieses auf dem Oracle-Host.

Die Konfigurationsdatei, welche durch diese minimale Konfiguration erzeugt wird, finden Sie im Abschnitt xref:#minimal_configuration[Referenzen]

=== Service-Erkennung durchführen

Klicken Sie in {CMK} auf [.guihint]#Setup# und geben Sie den Namen des Oracle-Hosts ein.
Klicken Sie den Namen des Hosts an und klicken Sie anschließend auf [.guihint]#Save & run service discovery#.

Die Service-Erkennung findet nun eine ganze Reihe Services.
Mit einem Klick auf [.guihint]#Accept all# nehmen Sie die ganzen neues Services ins Monitoring auf.

Damit haben Sie Ihre erste Oracle-Instanz ins Monitoring aufgenommen.

Für weitere Informationen können Sie nun den Artikel xref:monitoring_oracle[Oracle-Datenbanken überwachen] durchforsten.

