// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Willkommen im {CMK} Handbuch
:revdate: 2022-12-06
:title: Willkommen im {CMK} Handbuch
:description: Jedes Handbuch erfodert eine bestimmte Nutzung. Hier wird erklärt, wie das Handbuch zu {CMK} aufgebaut ist, damit Sie die relevanten Inhalte schnell finden.
:no-toc:

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
{related-end}


*Liebe Leserinnen und Leser,*

wir freuen uns, dass Sie den Weg zu {CMK} gefunden haben.

{CMK} bietet als Monitoring-Software umfassende und spezialisierte Möglichkeiten,
mit den sehr unterschiedlichen Rahmenbedingungen von IT-Infrastrukturen umzugehen.
Das erfordert zwangsläufig auch eine sehr umfassende Dokumentation,
die über die reine Beschreibung des Offensichtlichen hinausgeht.
Dieses Handbuch soll Sie so gut wie möglich dabei unterstützen,
{CMK} besser zu verstehen, mit {CMK} Ihre Anforderungen umzusetzen, aber auch neue Lösungswege zu entdecken.

Um den Umgang mit {CMK} so einfach wie möglich zu gestalten,
verfolgen die Artikel dieses Handbuchs an vielen Stellen eher ungewöhnliche Herangehensweisen.
Es geht dabei fast nie nur darum, eine vorgefertigte Abfolge von Einzelschritten nachzumachen.
Vielmehr soll Ihnen als Leser oder Leserin ein tieferes Verständnis eines Features in {CMK} vermittelt werden.

Wenn man es kurz zusammenfasst, ist unsere wichtigste Prämisse:
Das Handbuch soll hilfreich sein.
Und hilfreich ist es dann, wenn man die Beschreibung in die Lösung eines eigenen Problems übersetzen kann.

[#landing_page_continue]
Unter anderem auch aus diesem Grund ist das Handbuch in mehrere Bereiche unterteilt,
obwohl sie fließend ineinander übergehen.
Mit dieser Unterteilung wollen wir es einfacher machen,
die von Ihnen gesuchten Inhalte schneller zu finden.
Die folgenden Themen finden Sie in den Kapiteln des Handbuchs wieder.


[discrete]
== Leitfaden für Einsteiger

Jeder fängt einmal mit {CMK} an.
Da Sie sehr viele Möglichkeiten und Funktionen geboten bekommen,
fällt es am Anfang manchmal schwer, sich in den ersten Schritten zurechtzufinden.
Wir wollen daher den Einstieg in die Welt von {CMK} einfach machen,
indem wir Sie direkt am Anfang Schritt für Schritt bei Ihrer ersten {CMK}-Instanz unterstützen und 
in die wichtigsten Konzepte einführen.

Dieser Teil des Handbuchs eignet sich also sehr gut,
um ihn linear von Anfang bis Ende durchzulesen.
Sollten Sie das erste Mal dieses Handbuch lesen,
können Sie auch direkt mit xref:intro_setup#[dem ersten Artikel aus dem Leitfaden] einsteigen und
gegebenenfalls später zu der Beschreibung der weiterführenden Kapitel zurückkehren.


[discrete]
== Aufgaben für Administratoren und Benutzer

Der Hauptteil erklärt von Kapitel 3 bis 10 dann die Funktionen und deren Nutzung in {CMK}.
Sei es, dass Sie {CMK} erstmalig installieren wollen, Fragen zur Konfiguration haben oder
wissen möchten, wie man die Daten effizient und nützlich anzeigt.

Aus diesem Grund eignen sich diese Kapitel weniger, um sie von oben nach unten durchzulesen.
Vielmehr sind sie thematisch geordnet und widmen sich unterschiedlichen Aspekten einer jeweiligen Aufgabe.
Innerhalb der Kapitel finden Sie dann wichtige, einleitende oder anderweitig priorisierte Artikel immer am Anfang.


[discrete]
== Automatisierung und Programmierung

{CMK} lässt sich nicht nur mit einer Web-Oberfläche verwalten, sondern auch über APIs.
Dazu ermöglicht die modulare Softwarearchitektur auch eine umfangreiche Palette an Erweiterungsmöglichkeiten.

Mit den Artikeln, die sich in diesem Kapitel befinden,
liefern wir nach und nach Tipps, Hinweise und Einstiegspunkte,
um {CMK} an die eigene Infrastruktur anzupassen oder die Konfiguration zu automatisieren.


[discrete]
== Konzepte

Dieses Kapitel ist noch recht neu -- auch wenn die darin enthaltenen Artikel bereits lange im Handbuch vorhanden sind.
Wenn Sie mehr darüber erfahren wollen, wie {CMK} eigentlich funktioniert,
ohne eine direkte Anforderung oder Aufgabe zu verfolgen,
dann sind Sie hier genau richtig.


[discrete]
== Die {CMK}-Appliance

Alle Themen, die die Einrichtung und Nutzung der Appliance betreffen, sind im letzten Kapitel des Handbuchs zu finden.
Eigentlich ist das Appliance-Kapitel ein eigenes Handbuch.
Da die Konzepte von {CMK} aber auch in der Appliance gelten,
sollten Leserinnen und Leser dieses Teils immer auch einen Blick in die anderen Artikel des Handbuchs werfen.
