// -*- coding: utf-8 -*-
// SKIPCOMMITS 2025-08-28
include::global_attr.adoc[]
ifdef::onprem[]
= Willkommen im {CMK} Handbuch
:revdate: 2022-12-06
:title: Willkommen im {CMK} Handbuch
:description: Jedes Handbuch erfordert eine bestimmte Nutzung. Hier wird erklärt, wie das {CMK} Handbuch aufgebaut ist, damit Sie die relevanten Inhalte leicht finden.
:no-toc:

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
{related-end}
endif::[]

ifdef::saas[]
= Willkommen im {CE} Handbuch
:revdate: 2024-12-19
:title: Willkommen im {CE} Handbuch
:description: Jedes Handbuch erfordert eine bestimmte Nutzung. Hier wird erklärt, wie das {CE} Handbuch aufgebaut ist, damit Sie die relevanten Inhalte finden.
:no-toc:

{related-start}
xref:intro_setup#[Mit {CE} loslegen]
{related-end}
endif::[]


*Liebe Leserinnen und Leser,*

ifdef::onprem[]
wir freuen uns, dass Sie den Weg zu {CMK} gefunden haben.
endif::[]
ifdef::saas[]
wir freuen uns, dass Sie den Weg zu {CE} gefunden haben.

{CE} stellt Ihnen {CMK} als _Software as a Service (SaaS)_ in der Cloud zur Verfügung.
Was {CE-saas} auszeichnet, auch im Vergleich zu dessen selbst gehosteten Geschwistern wie {CE-onprem}, erfahren Sie in einem xref:cce#[eigenen Artikel.]
endif::[]

{CMK} bietet als Monitoring-Software umfassende und spezialisierte Möglichkeiten, mit den sehr unterschiedlichen Rahmenbedingungen von IT-Infrastrukturen umzugehen.
Das erfordert zwangsläufig auch eine sehr umfassende Dokumentation, die über die reine Beschreibung des Offensichtlichen hinausgeht.
Dieses Handbuch soll Sie so gut wie möglich dabei unterstützen, {CMK} besser zu verstehen, mit {CMK} Lösungen für Ihre Anforderungen zu implementieren, aber auch neue Lösungswege zu entdecken.

Um den Umgang mit {CMK} so einfach wie möglich zu gestalten, verfolgen die Artikel dieses Handbuchs an vielen Stellen eher ungewöhnliche Herangehensweisen.
Es geht dabei fast nie nur darum, eine vorgefertigte Abfolge von Einzelschritten nachzumachen.
Vielmehr soll Ihnen als Leser oder Leserin ein tieferes Verständnis eines Features in {CMK} vermittelt werden.

Wenn man es kurz zusammenfasst, ist unsere wichtigste Prämisse: Das Handbuch soll hilfreich sein.
Und hilfreich ist es dann, wenn Sie unsere Beschreibung als Vorlage in die Lösung eines eigenen Problems übersetzen können.

[#landing_page_continue]
Unter anderem auch aus diesem Grund ist das Handbuch in mehrere Bereiche unterteilt, obwohl sie fließend ineinander übergehen.
Mit dieser Unterteilung wollen wir Ihnen ermöglichen, die gesuchten Inhalte einfach und schnell zu finden.
Die folgenden Themen finden Sie in den Kapiteln des Handbuchs wieder.


[discrete]
== Leitfaden für Einsteiger

Jeder fängt einmal mit {CMK} an.
Da Ihnen sehr viele Optionen und Funktionen angeboten werden, fällt es am Anfang manchmal schwer, sich in den ersten Schritten zurechtzufinden.
Wir wollen daher den Einstieg in die Welt von {CMK} einfach machen, indem wir Sie direkt am Anfang Schritt für Schritt bei der Erstellung Ihrer ersten {CMK}-Instanz unterstützen und in die wichtigsten Konzepte einführen.

Dieser Teil des Handbuchs eignet sich also sehr gut, um ihn linear von Anfang bis Ende durchzulesen.
Sollten Sie das erste Mal dieses Handbuch lesen, können Sie auch direkt mit xref:intro_setup#[dem ersten Artikel aus dem Leitfaden] einsteigen
und gegebenenfalls später zu der Beschreibung der weiterführenden Kapitel zurückkehren.


[discrete]
== Aufgaben für Administratoren und Benutzer

ifdef::onprem[]
Der Hauptteil erklärt von Kapitel 3 bis 10 dann die Funktionen und deren Nutzung in {CMK}:
Sei es, dass Sie {CMK} erstmalig installieren, die Konfiguration anpassen wollen oder wissen möchten, wie man die Daten effizient, nützlich und verständlich anzeigt.
endif::[]
ifdef::saas[]
Der Hauptteil erklärt von Kapitel 3 bis 9 dann die Funktionen und deren Nutzung in {CMK}:
Sei es, dass Sie {CMK} erstmalig einrichten, die Konfiguration anpassen wollen oder wissen möchten, wie man die Daten effizient, nützlich und verständlich anzeigt.
endif::[]

Aus diesem Grund eignen sich diese Kapitel weniger, um sie von oben nach unten durchzulesen.
Vielmehr sind sie thematisch geordnet und widmen sich unterschiedlichen Aspekten einer jeweiligen Aufgabe.
Innerhalb der Kapitel finden Sie dann wichtige, einleitende oder anderweitig priorisierte Artikel immer am Anfang.


[discrete]
== Automatisierung und Programmierung

ifdef::onprem[]
{CMK} lässt sich nicht nur mit einer Web-Oberfläche verwalten, sondern auch über APIs.
Zusätzlich ermöglicht die modulare Softwarearchitektur auch eine umfangreiche Palette an Erweiterungsmöglichkeiten.

Mit den Artikeln, die sich in diesem Kapitel befinden, liefern wir nach und nach Tipps, Hinweise und Startpunkte, um {CMK} an die eigene Infrastruktur anzupassen oder die Konfiguration zu automatisieren.
endif::[]

ifdef::saas[]
{CMK} lässt sich nicht nur mit einer Web-Oberfläche verwalten, sondern auch mit einer REST-API.
Zusätzlich bietet die modulare Softwarearchitektur von {CMK} auch in der Cloud Erweiterungsmöglichkeiten, um {CMK} an die eigene Infrastruktur anzupassen.
endif::[]


[discrete]
== Konzepte

Dieses Kapitel ist noch recht neu -- auch wenn die darin enthaltenen Artikel bereits lange im Handbuch vorhanden sind.
Wenn Sie mehr darüber erfahren wollen, wie {CMK} eigentlich funktioniert, ohne eine direkte Anforderung oder Aufgabe zu verfolgen, dann sind Sie hier genau richtig.


ifdef::onprem[]
[discrete]
== Die {CMK} Appliance

Alle Themen, die die Einrichtung und Nutzung der Appliance betreffen, sind im letzten Kapitel des Handbuchs zu finden.
Eigentlich ist das Appliance-Kapitel ein eigenes Handbuch.
Da die Konzepte von {CMK} aber auch in der Appliance gelten, sollten Leserinnen und Leser dieses Teils immer auch einen Blick in die anderen Artikel des Handbuchs werfen.
endif::[]
