// -*- coding: utf-8 -*-
// IGNORE LLMs
// NONASCII
include::global_attr.adoc[]
= Das KI-System _Explain with AI_
:title: Das KI-System Explain with AI
:description: 

{related-start}
xref:user_interface#[Die Benutzeroberfläche]
{related-end}

//SK: Ich habe vorerst - aus Gründen - keine Screenshots in den Artikel eingebaut.

[#intro]
== Einleitung

In {CE} ermöglicht es Ihnen das integrierte KI-System [.guihint]#Explain with AI#, zusätzliche Informationen zu Hosts und Services zu bekommen.
Diese KI-gestützte Analysefunktion unterstützt Sie dabei, Fehlern in Ihrer Cloud-Infrastruktur auf den Grund zu gehen und vermittelt Ihnen allgemeines Wissen zur Handhabung von {CE}.


=== Technische Basis

Dieses KI-System basiert auf einem Large Language Model (LLM).
Die genaue Version und Generation des verwendeten LLMs, wird in der Funktion [.guihint]#Explain with AI# in der Benutzeroberfläche von {CE} angezeigt.
Das LLM ist über eine gesicherte Anwendungsprogrammierschnittstelle (API) an {CE} angebunden ist.

Das zugehörige _Data Manifest_ finden Sie in seiner aktuellen Fassung jederzeit unter link:https://checkmk.com/explain-with-ai/manifest[https://checkmk.com/explain-with-ai/manifest].


=== Zielsetzung

Dieses KI-System [.guihint]#Explain with AI# verfolgt primär die folgenden Ziele:

* Allgemeinverständliche Aufbereitung von Zuständen Ihrer Hosts und Services.
* Handreichung für {CMK}-Neulinge.
* Zusammenfassung von Vorfällen (Incidents) für nicht-technische Benutzer.


=== Funktionsübersicht

Die KI-gestützte Analysefunktion [.guihint]#Explain with AI# erfolgt ohne manuelle Nutzereingaben.
Dieses KI-System extrahiert gezielt technische Metadaten (z. B. Log-Einträge, Alarm-Metadaten) direkt aus Ihrer {CE} Umgebung. 


=== Nutzungsbeschränkung

Dieses KI-System ist ausschließlich für die Analyse und Erläuterung von Monitoring-Daten konzipiert (z. B. durch Hilfe bei der Erstellung von Dashboards, Erläuterung von Alarmen, Zusammenfassung von Logs oder Identifizierung relevanter Benutzerhandbücher).
Die Nutzung dieses KI-Systems für das direkte Eingreifen in kritische Prozesse oder die autonome Steuerung kritischer Infrastrukturen ist untersagt, da das System nicht für diese Hochrisiko Anwendungen zertifiziert ist. 

[IMPORTANT]
====
*Hinweis zur Nutzung von KI durch {CMK}*

Die Funktion [.guihint]#Explain with AI# verwendet ein Large Language Model (LLM), um Inhalte zu generieren.
Generierte Inhalte (Ausgaben) können Fehler oder Ungenauigkeiten enthalten.
Stellen Sie sicher, dass alle Ausgaben sorgfältig von einer natürlichen Person überprüft und auf inhaltliche Richtigkeit kontrolliert werden, bevor sie weiterverwendet werden.
Weitere Informationen finden Sie in unserer link:https://checkmk.com/privacy-policy[Datenschutzerklärung^].
====


== _Explain with AI_ verwenden

In jeder Ansicht [.guihint]#Services of host# finden Sie in der Spalte [.guihints]#Icons# das folgende Symbol: icon:icon_sparkle[alt="Symbol des KI-Systems _Explain with AI_."]

Sobald Sie diese Symbol anklicken, startet [.guihint]#Explain with AI#.
Zusätzlich finden Sie den Knopf [.guihint]#Explain with AI# in der Aktionsleiste jeder Ansicht, die einen einzelnen Service zeigt.

Nach dem Klick erscheint [.guihint]#Explain with AI# auf der rechten Seite des Bildschirms in einem Slideout.

Wenn Sie das KI-System [.guihint]#Explain with AI# erstmalig öffnen, müssen Sie zuerst bestätigen, dass Sie die „{CMK} AI feature usage notice“ zur Kenntnis genommen haben und diese auch akzeptieren.
Nachdem Sie dies getan haben, wird unmittelbar an einer Erklärung für den aktuellen Status des jeweiligen Service gearbeitet.
Zuoberst sehen Sie hier eine Auflistung der Kontextinformationen, die an das KI-System [.guihint]#Explain with AI# übergeben wurden.
////
SK: Diese ganzen Fragen wurden entfernt. Ich lasse den Text aber mal drin, weil ich den auch nicht neu schreiben möchte, sobald die Fragen zurückkommen.

Daneben finden Sie wiederum die Anfragen, die Sie an das KI-System [.guihint]#Explain with AI# stellen können.
Die genauen Prompts sind vorformuliert und werden für eine leichtere und schnellere Bedienbarkeit über die Knöpfe unter What would you like the AI to do? bereitgestellt.

Nach einem Klick auf einer der Optionen läuft das KI-System Explain with AIder Assistent los und erzeugt einen kontextbezogenen KI-Output.e, zu den Kontextinformationen passenden, Antwort.

So wird die Aufforderung Explain this host immer versuchen den Host im Gesamtgefüge ihrer Checkmk Cloud Infrastruktur einzuordnen.
Hinzu kommt eine Umschreibung des aktuellen Host-Zustands.
Sollte der Host aktuell beispielsweise im Zustand DOWN sein, folgt im Abschnitt “What is this” eine Einordnung des Zustands und eine Auflistung von Gründen, warum sich der Host in diesem Zustand befinden könnte.
////
Nach wenigen Sekunden erhalten Sie die angeforderten Informationen.
Mit diesen Informationen können Sie versuchen, die Ursache für einen nicht gewünschten Zustand zu beheben.
Das KI-System [.guihint]#Explain with AI# selbst wird nichts am Monitoring und der Konfiguration ändern.