= Hilfe zur Entwicklungsumgebung

:shell: source,shell,subs="quotes,macros,attributes"
:c-user: user@host:~$

== Schreiben mit Visual Studio Code (vscode)

=== Grundlegendes Setup

Um vscode optimal für das Schreiben in Asciidoc vorzubereiten, lohnt es sich, als erstes die entsprechende Erweiterung zu installieren: link:https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[asciidoctor.asciidoctor-vscode]
Diese Erweiterung liefert die Basis, direkt in den Dateien zu schreiben und in Fast-Echtzeit das Ergebnis in eine Vorschau geliefert zu bekommen.

Optional, aber emnpfohlen sind auch die Erweiterungen für git, sofern man git nicht eh auf der Kommandozeile nutzt sind link:https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens[GitLens] und link:https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github[GitHub Pull Requests and Issues].

Daneben gibt es natürlich noch viele weitere kleine Helfer, die einem das Leben erleichtern können. Erwähnt sich daher nur die beiden wichtigsten für den Einstieg.

=== Empfohlene Einstellung für die Asciidoctor-Erweiterung

Um alle Vorteile zu nutzen, gibt es ein paar Basiseinstellungen für einen bequemen Start. Der folgende Auszug ist aus den Einstellungen, wie sie in der Datei `settings.json` zu sehen sind:

----
{
    "asciidoc.preview.style": "checkmk.css",
    "asciidoc.preview.useEditorStyle": false,
    "asciidoc.previewFrontMatter": "show",
    "asciidoc.preview.attributes": {
        "global": "../attributes/global_attr.adoc",
        "chapter": "../../attributes/chapter_attr.adoc",
    },
}
----

Die beiden direkt angegebenen Attribute können zukünftig genutzt werden, um die globalen, vom Projekt selbst definierten Attribute bequem nutzen zu können. Derzeit sind sie aber noch nicht direkt relevant und eher eine Vorbereitung für die Zukunft.

== Writing with atom

tbd

== Schreiben mit vim

tbd
////
== HTML-Dateien lokal erstellen

Um aus den Asciidoc-Dateien eine HTML-Datei zu machen, braucht es -- neben `make` selbst -- zwei Programme:

[horizontal]
*make*:: Hier gelten keine besonderen Versionsvoraussetzungen
*Asciidoctor*:: Mindestens in der Version 2.0.0
*Ruby*:: Ruby sollte mindestens in der Version 2.3 installiert sein, wenn die (internen) Templates benutzt werden
*slimrb*:: Diese Erweiterung wird benötigt, um die (internen) Templates nutzen zu können

Um eine HTML-Version eines Artikels nun lokal zu erstellen, wird einfach `make html` aufgerufen und der Artikelname angegeben, welcher konvertiert werden soll.
Hierbei wird während des Prozesses geschaut, ob das interne Repository verfügbar ist, welches die Templates und Stylings zur Verfügung stellt.
Basierend auf diesem Ergebnis werden danach die HTML-Dateien erstellt.
Sie sehen dann entsprechend mehr oder weniger so aus, wie sie auch auf der offiziellen Webseite zu sehen sind.
Um eine Alternative für das Styling zu haben, gibt es eine -- leicht angepasste -- Version des Style-Sheet auch in diesem Repository.
Bitte beachten Sie, dass bei der Angabe des Artikels weder Pfad noch Dateiendung angegegeben wird:

[{shell}]
----
{c-user} make html ARTICLE=my_article
----

Danach werden die generierten Dateien unterhalb des Verzeichnisses `localbuild` verfügbar sein:

[{shell}]
----
{c-user} ls -R localbuild/
localbuild/:
de  en

localbuild/de:
my_article.html

localbuild/en:
my_article.html
----
 ////