= Einleitung

:imagesdir: ../../images
:cmk-basics: https://checkmk.com/de/monitoring
:cmk-blog: https://blog.checkmk.com/de
:CMK: Checkmk
:CRE: pass:q,m[image:CRE.svg[CRE,title=Checkmk Raw Edition,width=20] *Checkmk Raw Edition*]


Wenn man ein Handbuch oder eine Dokumentation zu einer Software liest, dann verfolgt man in der Regel einen bestimmten Zweck damit.
In den seltensten Fällen wird man einen Artikel aus dem Handbuch zu {CMK} aus purem Zufall öffnen.
Aus diesem Grund gibt es auch bestimmte Grundprinzipien, nach denen der Inhalt für die Dokumentation erstellt wird.

Auch und vor allem beinhaltet das, was das Handbuch *nicht* leisten möchte, wie z.B. _Best Practices_ oder Prozeduren (_How To’s_) an die Hand zu geben, was bereits durch den Bereich link:{cmk-blog}[Blog] oder die allgemeine link:{cmk-basics}[Einführung zum Monitoring] abgedeckt wird.


== Wer liest das Handbuch und warum?

* Ich suche nach einem geeigneten Monitoring-Tool.
Dabei ist mir wichtig, dass dieses meine Anforderungen erfüllen kann.
Ist {CMK} dafür geeignet und vermittelt mir das Handbuch das?
* Ich soll in meiner Firma {CMK} übernehmen und will mich gründlich in das Thema einarbeiten.
Ich habe vor allem auch die Zeit dafür.
* Ich verwende {CMK}, habe eine bestimmte Anforderung und weiß nicht, wie ich diese umsetzen soll.
* Ich verwende {CMK} und möchte tiefer in das Thema "Verarbeitung von Events" einsteigen, bzw. mich in das Thema in Ruhe einlesen.
* Ich verwende seit längerem {CRE} und möchte beim Lesen erkennen, ob und wann sich eine der kommerziellen Editionen lohnen würde, oder welche Dinge dort anders funktionieren.
* Ich bin der {CMK} Superexperte und möchte Erweiterungen dafür bauen, oder bestimmte Dinge in {CMK} automatisieren, {CMK} um Skripte erweitern, o.ä.
* Ich bin Berater für {CMK} und möchte bestimmte Aspekte in {CMK} *genau* verstehen.


== Welche Erlebnisse/Gefühle soll ein Leser haben?

[horizontal]
*vollständig*:: Ich finde, was ich suche
*angenehm*:: Das Lesen ist nicht trocken und anstrengend
*schnell*:: Ich finde die Information *schnell* und kann sie auch schnell lesen
*hilfreich*:: Ich habe nicht nur verstanden, was ich gelesen habe, sondern kann es auch auf andere Situationen übertragen.
*korrekt*:: Was ich gelesen habe, ist präzise und richtig.
*neues*:: Ich habe (zufällig?) etwas neues entdeckt, was ich vorher nicht wusste.

Immer dann, wenn man neue Inhalte schreibt, sollten diese Aspekte im Hinterkopf behalten werden, um nicht nur die Software zu dokumentieren, sondern lebendig zu beschreiben.
Nicht zuletzt soll das {CMK} Handbuch begeistern, und der Umgang mit der doch sehr umfangreichen und mächtigen Software soll Spaß machen und Erfolgserlebnisse bringen.
