// -*- coding: utf-8 -*-
// IGNORE
// NONASCII

// MFS: Full translation necessary
////
[#uninstall]
== Deinstallation von {CMK}

Voraussetzung für die Deinstallation eines {CMK}-Paketes ist, dass dieses von keiner Instanz mehr verwendet wird.
Nicht mehr benötigte Instanzen löschen Sie mit xref:omd_basics#omd_rm[`omd rm`].
Auch Instanzen, die schon einmal auf höhere {CMK}-Versionen aktualisiert wurden hinterlassen ungenutzte {CMK}-Pakete.

Für die Deinstallation bringt `omd` einen Wrapper mit, der unbenutzte {CMK}-Pakete xref:omd_basics#cleanup[findet und nur diese deinstalliert].

Falls Sie mehr Kontrolle über die Deinstallation haben wollen, können Sie auch den Paketmanager direkt verwenden.
Hier müssen Sie selbst sicherstellen, dass das zu deinstallierende Paket von keiner Instanz mehr benutzt wird.
Vergleichen Sie hierfür die Ausgabe von xref:omd_basics#omd_update[`omd sites`] mit der von `omd versions`.

So finden Sie heraus, welchen Paketen die installierten {CMK}-Versionen entsprechen:

[{shell}]
----
{c-root} rpm -qa | grep check-mk
{pkg-cee}-{current}-el9-38.x86_64.rpm
{pkg-cre}-{current}-el9-38.x86_64.rpm
check-mk-raw-{oldstable-patch}-el9-38.x86_64.rpm
----

Die Deinstallation geschieht mit `rpm -e`:

[{shell}]
----
{c-root} rpm -e check-mk-raw-{oldstable-patch}-el9-38.x86_64.rpm
----
////
