// -*- coding: utf-8 -*-

=== _Can add or modify executables_

This permission is required wherever executable files are to be added or modified.
It applies to both the {CMK} site and hosts in monitoring and therefore affects:

* The installation of xref:mkps#[{CMK} extension packages]
* The configuration xref:active_checks#[active checks] via the rule [.guihint]#Integrate Nagios plugins#
* The configuration of individual programs with the setting [.guihint]#Use a custom check plugin# via the rule [.guihint]#Host check command#
* Deploying legacy Nagios plug-ins in agent packages via xref:agent_linux#e2e_monitoring[MRPE] using the rule [.guihint]#Execute MRPE checks#
* Deploying any files in agent packages using the rule [.guihint]#Deploy custom files with agent#
* The execution of xref:datasource_programs#[data source programs]
* The execution of individual xref:ec#actions[actions in the Event Console]

This permission is also required for the [.guihint]#Bake and sign agents# function to be available.