// -*- coding: utf-8 -*-
// IGNORE
// NONASCII

[#uninstall]
== Uninstalling {CMK}

To uninstall a {CMK} package, it must not currently be in use by any site.
You can delete sites that are no longer needed using xref:omd_basics#omd_rm[`omd rm`].
Even sites that have already been updated to higher {CMK} versions leave unused {CMK} packages behind.

For an uninstallation, `omd` provides a wrapper that xref:omd_basics#cleanup[finds and uninstalls _only_ unused {CMK} packages].

If you want more control over the uninstallation process, you can also use the package manager directly.
In this case, you must first ensure that the package you want to uninstall is no longer being used by any site.
To do this, compare the output of xref:omd_basics#omd_update[`omd sites`] with that of `omd versions`.

Here is how to find out which packages correspond to the installed {CMK} versions:

[{shell}]
----
{c-root} rpm -qa | grep check-mk
{pkg-cee}-{current}-el9-38.x86_64.rpm
{pkg-cre}-{current}-el9-38.x86_64.rpm
check-mk-raw-{oldstable-patch}-el9-38.x86_64.rpm
----

The deletion is performed with `rpm -e`:

[{shell}]
----
{c-root} rpm -e check-mk-raw-{oldstable-patch}-el9-38.x86_64.rpm
----
