// -*- coding: utf-8 -*-
// IGNORE 
include::global_attr.adoc[]
= Schnellstart-Anleitung für {CMK} virt1
:title: Schnellstart-Anleitung für {CMK} virt1
:description: Die Inbetriebnahme der virtuellen {CMK} Appliance umfasst eine Reihe von Schritten. Lesen Sie hier, wie Sie Ihre Appliance für die Nutzung einrichten.
:experimental:

{related-start}
xref:appliance_usage#[Appliance einrichten und nutzen]
xref:install_appliance_cmk#[Installation von {CMK} in der Appliance]
xref:appliance_rack1_quick_start#[Schnellstart-Anleitung für {CMK}-Racks]
{related-end}


Diese Schnellstart-Anleitung führt Sie vom Download der Appliance über eine Minimalkonfiguration bis hin zum Anmeldebildschirm einer laufenden {CMK}-Instanz.

Ausführliche Informationen und Anleitungen finden Sie im xref:appliance_usage#[Hauptartikel zur Appliance.]


== Maschine einrichten (Konsole)

. Laden Sie die {CMK} virt1 als OVA-Datei (Open Virtualization Appliance) von unserer link:https://checkmk.com/de/download[Download-Seite^] herunter und importieren Sie diese Datei in Ihren Hypervisor, wahlweise Hyper-V, Proxmox oder VMware ESXi (für bessere Performance sollten Sie die Netzwerkkarte beim Import in ESXi auf VMXNET 3 ändern). 
xref:appliance_install_virt1#[Mehr ...]

. Starten Sie die importierte virtuelle Maschine.
Sie landen in einer textbasierten Konfigurationsumgebung (Konsole genannt), in der Sie die Grundkonfiguration der Appliance vornehmen.

. Während der Initialisierung beim Erststart werden Sie zur Partitionierung des Datenträgers aufgefordert.
xref:appliance_usage#init_start[Mehr ...] +
Bestätigen Sie.

. Nach der Partitionierung sehen Sie die Statusansicht der Konsole, den Startbildschirm bei allen weiteren Starts.

. Damit die Appliance zum Monitoring genutzt werden kann, müssen Sie nun noch einige Einstellungen vornehmen. 
Drücken Sie die Taste kbd:[F1], um das Konfigurationsmenü aufzurufen und setzen Sie mindestens die folgenden Einstellungen:

.. [.guihint]#Network Configuration:# IP-Adresse, Netzmaske und optional das Standard-Gateway.
xref:appliance_usage#network_config[Mehr ...]

.. [.guihint]#Device Password:# Passwort zur *Aktivierung* der Weboberfläche der Appliance.
xref:appliance_usage#network_access[Mehr ...]

. Starten Sie nun die Weboberfläche der Appliance auf einem beliebigen Rechner im Netzwerk über die oben vergebene IP-Adresse mit `\http://&lt;ipaddress&gt;/`.
Loggen Sie sich mit dem gesetzten Passwort ein.
Ein Benutzername wird nicht benötigt.


== Monitoring einrichten (Web-GUI)

. Laden Sie das {CMK}-Software-Paket für die Appliance von unserer link:https://checkmk.com/de/download[Download-Seite] herunter.

. Navigieren Sie in der Weboberfläche der Appliance zu [.guihint]#Check_MK Versions# und installieren Sie das {CMK}-Paket über den Knopf [.guihint]#Upload & Install.#
xref:appliance_usage#manage_cmk[Mehr ...]

. Navigieren Sie nun zu [.guihint]#Site Management# und legen Sie mit [.guihint]#Create New Site# eine {CMK}-Instanz an.
xref:appliance_usage#create_site[Mehr ...] +
Geben Sie mindestens die folgenden Werte ein:

.. [.guihint]#Unique site ID:# Name der Instanz
.. [.guihint]#Version:# Version von {CMK}
.. [.guihint]#Login for the administrator:# Admin-Benutzername
.. [.guihint]#Password for administrator:# Admin-Passwort

. Nun können Sie sich an der {CMK}-Instanz anmelden -- einfach den Instanznamen an die URL von oben anhängen: `\http://&lt;ipaddress&gt;/&lt;siteid&gt;/`

{CMK} steht nun für Sie bereit!
Erfahren Sie im Artikel xref:intro_gui#[Die Checkmk-Oberfläche,] wie es weiter geht.

Für den produktiven Betrieb sollten Sie freilich weitere Einstellungen vornehmen, beispielsweise für Namensauflösungen, Kommunikation per E-Mail, Verschlüsselung etc.
Alles Weitere erfahren Sie im xref:appliance_usage#[Hauptartikel zur Appliance.]
