// -*- coding: utf-8 -*-
// IGNORE LAN1
// NONASCII
include::global_attr.adoc[]
= Schnellstart-Anleitung für {CMK}-Racks
:title: Schnellstart-Anleitung für {CMK}-Racks
:description: Die Inbetriebnahme der physischen {CMK} Appliance umfasst eine Reihe von Schritten. Lesen Sie hier, wie Sie Ihre Appliance für die Nutzung einrichten.
:experimental:

{related-start}
xref:appliance_usage#[Appliance einrichten und nutzen]
xref:install_appliance_cmk#[Installation von {CMK} in der Appliance]
xref:appliance_virt1_quick_start#[Schnellstart-Anleitung für virt1]
{related-end}


Diese Schnellstart-Anleitung führt Sie vom Aufstellen der Appliance über eine Minimalkonfiguration bis hin zum Anmeldebildschirm einer laufenden {CMK}-Instanz.

Ausführliche Informationen und Anleitungen finden Sie im xref:appliance_usage#[Hauptartikel zur Appliance.]

[IMPORTANT]
====
Beachten Sie, dass das Management-Interface aller {CMK}-Racks *im Auslieferungszustand deaktiviert* ist und bei Bedarf xref:appliance_rack_config#ipmi[manuell über die Weboberfläche aktiviert werden muss.]
Sie *müssen* das unbedingt beachten, wenn Sie das Rack bspw. direkt an einen entfernten Standort liefern und dort aufstellen lassen. xref:appliance_rack_config#ipmi[Mehr ...]
====


[#console]
== Maschine einrichten (Konsole)

. Schließen Sie das Gerät an. Für die Inbetriebnahme benötigen Sie zumindest: Monitor (VGA), USB-Tastatur, Netzwerkverbindung (Anschluss: LAN1) und Stromversorgung (vorzugsweise beide Anschlüsse).

. Während der Initialisierung beim Erststart werden Sie zur Initialisierung des RAIDs aufgefordert, wobei natürlich alle Daten auf den Festplatten gelöscht werden.
xref:appliance_usage#init_start[Mehr ...] +
Bestätigen Sie.

. Nach der Initialisierung sehen Sie die Statusansicht der Konsole, den Startbildschirm bei allen weiteren Starts.

. Damit die Appliance zum Monitoring genutzt werden kann, müssen Sie nun noch einige Einstellungen vornehmen. 
Drücken Sie die Taste kbd:[F1], um das Konfigurationsmenü aufzurufen und setzen Sie mindestens die folgenden Einstellungen:

.. [.guihint]#Network Configuration#: IP-Adresse, Netzmaske und optional das Standard-Gateway.
xref:appliance_usage#network_config[Mehr ...]

.. [.guihint]#Device Password#: Passwort zur *Aktivierung* der Weboberfläche der Appliance.
xref:appliance_usage#network_access[Mehr ...]

. Starten Sie nun die Weboberfläche der Appliance über die oben vergebene IP-Adresse auf einem beliebigen Rechner im Netzwerk mit `\http://&lt;ipaddress&gt;/`.
Loggen Sie sich mit dem gesetzten Passwort ein.
Ein Benutzername wird nicht benötigt.

. Schließen Sie zuletzt noch -- optional, aber dringend empfohlen -- das Management-Interface über ein separates Netzwerk an. xref:appliance_rack_config#ipmi[Mehr ...]


[#web_gui]
== Monitoring einrichten (Web-GUI)

. Laden Sie das {CMK}-Software-Paket für die Appliance von unserer link:https://checkmk.com/de/download[Download-Seite^] herunter.

. Navigieren Sie in der Weboberfläche der Appliance zu [.guihint]#Check_MK Versions# und installieren Sie das {CMK}-Paket über den Knopf [.guihint]#Upload & Install#.
xref:appliance_usage#manage_cmk[Mehr ...]

. Navigieren Sie nun zu [.guihint]#Site Management# und legen Sie mit [.guihint]#Create New Site# eine {CMK}-Instanz an.
xref:appliance_usage#create_site[Mehr ...] +
Geben Sie mindestens die folgenden Werte ein:

.. [.guihint]#Unique site ID#: Name der Instanz
.. [.guihint]#Version#: Version von {CMK}
.. [.guihint]#Login for the administrator#: Admin-Benutzername
.. [.guihint]#Password for administrator#: Admin-Passwort

. Nun können Sie sich an der {CMK}-Instanz anmelden -- einfach den Instanznamen an die URL von oben anhängen: `\http://&lt;ipaddress&gt;/&lt;siteid&gt;/`

{CMK} steht nun für Sie bereit!
Erfahren Sie im Artikel xref:intro_gui#[Die Checkmk-Oberfläche,] wie es weiter geht.

Für den produktiven Betrieb sollten Sie freilich weitere Einstellungen vornehmen, beispielsweise für Namensauflösungen, Kommunikation per E-Mail, Verschlüsselung etc.
Alles Weitere erfahren Sie im xref:appliance_usage#[Hauptartikel zur Appliance.]
