// -*- coding: utf-8 -*-
// IGNORE
// NONASCII
include::global_attr.adoc[]
= {CE-onprem}
:title: {CE-onprem}
:description: {CE-onprem} bietet gegenüber anderen Editionen zusätzliche umfangreiche, Cloud-spezifische Funktionen. Hier erhalten Sie einen Überblick.         

{related-start}
xref:cse#[{SE}]
xref:managed#[{ME}]
xref:intro_setup#[{CMK} aufsetzen]
xref:update#[Updates und Upgrades]
{related-end}


[#intro]
== Einleitung

Die eine perfekte Software-Lösung für jeden Nutzer und jeden Anwendungsfall gibt es nicht.
Was dem einen gefällt, ist dem anderen zu viel oder zu wenig, zu simpel oder zu komplex.
Deshalb ist auch {CMK} in verschiedenen Editionen verfügbar.
Diese unterscheiden sich vor allem im Leistungsumfang und in den Einsatzmöglichkeiten.
Im Folgenden möchten wir Ihnen mit {CCE-onprem} (vormals {CMK} Cloud (Self-hosted)) eine der kommerziellen xref:glossar#edition[Editionen] vorstellen.


[#editions]
== Einordnung von {CE-onprem}

Aufbauend auf xref:cse#[{CSE}] bietet {CCE} vor allem Verbesserungen für die vollständige Überwachung hybrider Umgebungen, in denen Hosts sowohl in Rechenzentren als auch in der Cloud beheimatet sind.

Die Unterstützung bei der Verlagerung von Anwendungen und Prozessen in die Cloud, d.h. in sogenannten _Lift and Shift_-Szenarien, ist bereits in allen Editionen integriert 
-- bei der Überwachung von Amazon Web Services (AWS), Microsoft Azure und Google Cloud Platform (GCP).
Darüber hinaus bietet {CE-onprem} zusätzliche Cloud-spezifische xref:glossar#check_plugin[Check-Plugins] und xref:glossar#dashboard[Dashboards].
Neben der Cloud-Integration punktet {CE} mit erweiterter Sicherheit (wie dem {CMK}-Agenten im xref:glossar#push_mode[Push-Modus]), Automatisierung (durch die Autoregistrierung von Hosts) und umfassender _Observability_ von Anwendungen über den OpenTelemetry-Standard.
// TK: Ich hab mich bei der Positionierung im Google Doc Positioning Doc for Checkmk 2.5_Dec 25 [Work in progress] bedient. Bitte kritisch reviewen.
// ES: Sieht für mich alles richtig aus.

{CE-onprem} ist einerseits die Basis für die _On-Premises_-Edition xref:managed#[{CME}] und andererseits für {CCE-saas}, die {CMK} als _Software as a Service (SaaS)_ in der Cloud zur Verfügung stellt.
Eine Übersicht der Funktionen von link:https://docs.checkmk.com/saas/de/cce.html[{CE-saas}^] finden Sie im {CE-saas}-Handbuch.

Ergänzend zum link:https://checkmk.com/de/preise[Editionsvergleich^] und zur Präsentation der link:https://checkmk.com/de/produkt/checkmk-cloud[{CE}^] auf unserer Website zeigt dieser Artikel die Unterschiede auf technischer Ebene und versucht so, eine komplementäre Entscheidungshilfe bei der Wahl der Edition zu sein.


[#functions]
== Zusätzliche Funktionen

Die wesentlichen Funktionen von {CE-onprem}, die diese von anderen Editionen unterscheiden:

* Nur {CE-onprem} ist über die Marketplaces von xref:install_azure#[Microsoft Azure] und xref:install_aws#[AWS] verfügbar.

* Fortgeschrittene Check-Plugins: +
Bei der Überwachung von xref:monitoring_aws#[Amazon Web Services (AWS),] xref:monitoring_azure#[Microsoft Azure] und xref:monitoring_gcp#[Google Cloud Platform (GCP)] gibt es in {CE} zusätzliche, Cloud-spezifische Check-Plugins.

* Cloud-spezifische Dashboards: +
In {CE} gibt es für AWS, Microsoft Azure und GCP spezifische Dashboards.

* Konfiguration eines Push-Agenten: +
In allen On-Premises-Editionen initiiert der {CMK}-Server die Kommunikation mit einem Host und fragt die Daten vom {CMK}-Agenten ab -- im sogenannten xref:glossar#pull_mode[Pull-Modus.]
Mit {CE-onprem} können Sie zusätzlich den xref:glossar#push_mode[Push-Modus] nutzen.

* Autoregistrierung von Hosts: +
In {CE-onprem} können Sie xref:hosts_autoregister#[Hosts automatisch erstellen lassen], auf denen ein {CMK}-Agent installiert ist.
Dies beinhaltet die Registrierung des Agenten beim {CMK}-Server, den Aufbau einer TLS-verschlüsselte Verbindung, die Erstellung des Hosts, die Durchführung einer Service-Erkennung und die Aktivierung der Änderungen,
so dass der Host in die Monitoring-Umgebung aufgenommen wird — alles vollautomatisch.
Die Autoregistrierung funktioniert für Pull- und Push-Agenten.
// TK: Hier müsste noch OpenTelemetry ergänzt werden oder (besser) die wichtigsten Features wie in cse gruppiert werden nach Cloud, Sicherheit, Automatisierung, Observability oder so ähnlich.


[#upgrade]
== Upgrade zu {CE-onprem}

Sie können {CE-onprem} unverbindlich testen, denn diese Edition ist in den ersten 30 Tagen nicht limitiert.
Durch Eingabe eines Lizenzschlüssels nach spätestens 30 Tagen können Sie {CE-onprem} dann ohne Beschränkungen einsetzen.

Für den Wechsel von einer der anderen Editionen zu {CE-onprem} folgen Sie der xref:update#upgrade[Upgrade-Beschreibung.]


[#details]
== Unterschiede der Komponenten im Detail

[#ui]
=== Monitoring-Oberfläche

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen

|Cloud-Dashboards |Im Monitoring finden Sie die spezifischen Dashboards für xref:monitoring_aws#dashboards[AWS,] xref:monitoring_azure#dashboards[Azure] und xref:monitoring_gcp#dashboards[GCP.]
|===


[#agents]
=== Monitoring-Agenten

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen

|Push-Modus |Der xref:wato_monitoringagents#agents[{CMK}-Agent] für Linux und für Windows kann im xref:glossar#push_mode[Push-Modus] konfiguriert und genutzt werden.
Den Modus (Push oder xref:glossar#pull_mode[Pull]) konfigurieren Sie in den Eigenschaften eines Hosts oder Ordners, im Abschnitt zu den xref:hosts_setup#monitoring_agents[Monitoring-Agenten.]
Der Push-Modus ist auf den Agent Controller angewiesen und daher im Legacy-Modus des Agenten nicht verfügbar.

|Autoregistrierung |Sie haben die Möglichkeit, Hosts automatisch bei der Registrierung anzulegen mit der sogenannten xref:hosts_autoregister#[Autoregistrierung.]
Zur Konfiguration der {CMK}-Instanz dient der Regelsatz xref:hosts_autoregister#rule_autoregister_site[[.guihint]#Agent registration.#]
Auch die Autoregistrierung setzt den Agent Controller voraus.

|Agentenbäckerei (_Agent Bakery_) |Sie können die Agentenbäckerei zusätzlich nutzen, um Agentenpakete mit einer Konfiguration für die Autoregistrierung zu versehen.
Die Regel für die Agentenbäckerei heißt xref:hosts_autoregister.html#rule_autoregister_bakery[[.guihint]#Agent controller auto-registration.#]
Diese Pakete führen die Registrierung automatisch nach der Installation durch.

|Berechtigung zur Agentenregistrierung |Die xref:wato_user#predefined_roles[vordefinierte Rolle] `agent_registration` enthält zusätzliche Berechtigungen, um Hosts automatisch zu erstellen.
|===


[#connections]
=== Anbindungen

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen
|Grafana |Das xref:grafana#[Grafana-Plugin] können Sie direkt aus dem link:https://grafana.com/grafana/plugins/checkmk-cloud-datasource[Grafana-Katalog^] installieren, so dass sich die Integration einfach in Ihre Cloud-Umgebung einbetten lässt.
|===


[#provision]
=== Bereitstellung

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen

|Verfügbarkeit in den Azure und AWS Marketplaces |{CE-onprem} steht in den Marketplaces von link:https://azuremarketplace.microsoft.com/de-de/marketplace/apps/tribe29gmbh1665582614827.checkmk003?tab=Overview[Microsoft Azure^] und link:https://aws.amazon.com/marketplace/pp/prodview-gddkal2hfn7yo[AWS^] zur Installation bereit.
Die Artikel zu den Images von xref:install_azure#[Azure] und xref:install_aws#[AWS] führen Sie in die Einrichtung ein.

|Test der Edition |Sie können {CE-onprem} 30 Tage lang in vollem Funktionsumfang unverbindlich testen.
In kleinem Rahmen, d.h. mit einer Instanz und bis zu 750 Services, können Sie {CMK} mit {CE-onprem} auch dauerhaft ohne Subskription betreiben.
|===


[#other]
=== Weitere Funktionen

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen

|Check-Plugins für AWS |Es gibt zusätzliche Check-Plugins für die AWS Cloud-Produkte
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_lambda[AWS Lambda,^]
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_ecs[Elastic Container Service (ECS),^]
link:https://checkmk.com/de/integrations/aws_route53[Route 53,^]
link:https://checkmk.com/de/integrations/aws_cloudfront[CloudFront,^]
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=elasticache[ElastiCache for Redis^] und
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_sns[Simple Notification Service (SNS).^]

|Check-Plugins für Azure |Es gibt zusätzliche Check-Plugins für die Azure-Produkte
link:https://checkmk.com/de/integrations/azure_app_gateway[Application Gateway^] und 
link:https://checkmk.com/de/integrations/azure_vault_backup_containers[Recovery Services vaults.^]

|Check-Plugins für GCP |Es gibt zusätzliche Check-Plugins für die Goggle Cloud-Produkte
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_function[Cloud Functions,^]
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_run[Cloud Run^] und
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_redis[Memorystore for Redis.^]

|OpenTelemetry |Sie können xref:opentelemetry#[OpenTelemetry-Metriken] empfangen und im Monitoring verarbeiten.
In der dynamischen Host-Verwaltung gibt es einen eigenen Verbindungstyp zur Einrichtung einer xref:dcd#connection_opentelemetry[OpenTelemetry-Verbindung.]
|===
