// -*- coding: utf-8 -*-
// IGNORE
include::global_attr.adoc[]
= {CE} (Self-hosted)
:revdate: 2024-12-19
:title: Checkmk Cloud (Self-hosted)
:description: Was Checkmk Cloud (Self-hosted) ausmacht, vor allem auch im Vergleich zu den anderen {CMK}-Editionen, erfahren Sie hier.

{related-start}
xref:cse#[{SE}]
xref:managed#[{ME}]
xref:intro_setup#[{CMK} aufsetzen]
xref:update#[Updates und Upgrades]
{related-end}


[#intro]
== Einleitung

Die eine perfekte Software-Lösung für jeden Nutzer und jeden Anwendungsfall gibt es nicht.
Was dem einen gefällt, ist dem anderen zu viel oder zu wenig, zu simpel oder zu komplex.
Deshalb ist auch {CMK} in verschiedenen Editionen verfügbar.
Diese unterscheiden sich vor allem im Leistungsumfang und in den Einsatzmöglichkeiten.
Im Folgenden möchten wir Ihnen mit {CCE} (Self-hosted) eine der kommerziellen xref:glossar#edition[Editionen] vorstellen.


[#editions]
== Einordnung von {CE} (Self-hosted)

{CE} gibt in in zwei Varianten: als {CE} (SaaS) und {CE} (Self-hosted).
Während {CE} (Self-hosted) eine der _On-Premises_-Editionen von {CMK} ist, die alle das Aufsetzen eines eigenen {CMK}-Servers voraussetzen, läuft bei {CE} (SaaS) der {CMK}-Server bereits in der AWS Cloud.

Die Software von {CE} (SaaS) basiert auf der von {CE} (Self-hosted).
Daher bieten beide prinzipiell den gleichen Funktionsumfang.
Eine Übersicht der Funktionen von link:https://docs.checkmk.com/saas/de/cce.html[{CE} (SaaS)^] finden Sie im {CE}-Handbuch.

Als On-Premises-Edition baut {CE} (Self-hosted) inhaltlich auf xref:cse#[{CSE}] auf, bietet aber zusätzlich umfangreiche Cloud-Funktionen.
Damit ist sie vor allem für die Nutzer von Wert, deren Hosts in einer Cloud beheimatet sind und die auch ihr gesamtes Monitoring in einer Cloud aufsetzen wollen.

Die Unterstützung bei der Verlagerung von Anwendungen und Prozessen in die Cloud, d.h. in sogenannten _Lift and Shift_-Szenarien, ist bereits in allen Editionen integriert 
-- bei der Überwachung von Amazon Web Services (AWS), Microsoft Azure und Google Cloud Platform (GCP).
Darüber hinaus bietet {CE} (Self-hosted) auch Cloud-spezifische xref:glossar#check_plugin[Check-Plugins.]
So können Sie beim Übergang aus dem Rechenzentrum in eine Cloud weiter {SE} nutzen.
Möchten Sie danach auch SaaS und PaaS Produkte, die eine Cloud Ihnen bietet, nutzen, können Sie auf {CE} (Self-hosted) upgraden.

Auf {CE} (Self-hosted) baut dann xref:managed#[{CME}] auf.

[TIP]
====
Immer dann, wenn eine Verwechslung mit {CE} (SaaS) ausgeschlossen ist -- wie in den anderen Artikeln dieses {CMK} Handbuchs -- nennen wir {CE} (Self-hosted) einfach {CE}.
====


[#functions]
== Zusätzliche Funktionen

Die wesentlichen Funktionen von {CE} (Self-hosted), die diese von anderen Editionen unterscheiden:

* Nur {CE} (Self-hosted) ist über die Marketplaces von xref:install_azure#[Microsoft Azure] und xref:install_aws#[AWS] verfügbar.

* Fortgeschrittene Check-Plugins: +
Bei der Überwachung von xref:monitoring_aws#[Amazon Web Services (AWS),] xref:monitoring_azure#[Microsoft Azure] und xref:monitoring_gcp#[Google Cloud Platform (GCP)] gibt es in {CE} zusätzliche, Cloud-spezifische Check-Plugins.

* Cloud-spezifische Dashboards: +
In {CE} gibt es für AWS, Microsoft Azure und GCP spezifische Dashboards.

* Konfiguration eines Push-Agenten: +
In allen On-Premises-Editionen initiiert der {CMK}-Server die Kommunikation mit einem Host und fragt die Daten vom {CMK}-Agenten ab - im sogenannten xref:glossar#pull_mode[Pull-Modus.]
Mit {CE} (Self-hosted) können Sie zusätzlich den xref:glossar#push_mode[Push-Modus] nutzen.

* Autoregistrierung von Hosts: +
In {CE} (Self-hosted) können Sie xref:hosts_autoregister#[Hosts automatisch erstellen lassen], auf denen ein {CMK}-Agent installiert ist.
Dies beinhaltet die Registrierung des Agenten beim {CMK}-Server, den Aufbau einer TLS-verschlüsselte Verbindung, die Erstellung des Hosts, die Durchführung einer Service-Erkennung und die Aktivierung der Änderungen,
so dass der Host in die Monitoring-Umgebung aufgenommen wird — alles vollautomatisch.
Die Autoregistrierung funktioniert für Pull- und Push-Agenten.

[TIP]
====
Im Setup der {CMK}-Benutzeroberfläche werden Elemente, die es nur ab {CE} gibt, durch den Zusatz [.guihint]#(Managed Services Edition, Cloud Edition)# gekennzeichnet, z. B. Regeln oder Parameterwerte, 
====


[#upgrade]
== Upgrade zu {CE} (Self-hosted)

Sie können {CE} (Self-hosted) unverbindlich testen, denn diese Edition ist in den ersten 30 Tagen nicht limitiert.
Durch Eingabe eines Lizenzschlüssels nach spätestens 30 Tagen können Sie {CE} (Self-hosted) dann ohne Beschränkungen einsetzen.

Für den Wechsel von einer der anderen Editionen zu {CE} (Self-hosted) folgen Sie der xref:update#upgrade[Upgrade-Beschreibung.]


[#details]
== Unterschiede der Komponenten im Detail

[#ui]
=== Monitoring-Oberfläche

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen

|Cloud-Dashboards |Im Monitoring finden Sie die spezifischen Dashboards für xref:monitoring_aws#dashboards[AWS,] xref:monitoring_azure#dashboards[Azure] und xref:monitoring_gcp#dashboards[GCP.]
|===


[#agents]
=== Monitoring-Agenten

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen

|Push-Modus |Der xref:wato_monitoringagents#agents[{CMK}-Agent] für Linux und für Windows kann im xref:glossar#push_mode[Push-Modus] konfiguriert und genutzt werden.
Den Modus (Push oder xref:glossar#pull_mode[Pull]) konfigurieren Sie in den Eigenschaften eines Hosts oder Ordners, im Abschnitt zu den xref:hosts_setup#monitoring_agents[Monitoring-Agenten.]
Der Push-Modus ist auf den Agent Controller angewiesen und daher im Legacy-Modus des Agenten nicht verfügbar.

|Autoregistrierung |Sie haben die Möglichkeit, Hosts automatisch bei der Registrierung anzulegen mit der sogenannten xref:hosts_autoregister#[Autoregistrierung.]
Zur Konfiguration der {CMK}-Instanz dient der Regelsatz xref:hosts_autoregister#rule_autoregister_site[[.guihint]#Agent registration.#]
Auch die Autoregistrierung setzt den Agent Controller voraus.

|Agentenbäckerei (_Agent Bakery_) |Sie können die Agentenbäckerei zusätzlich nutzen, um Agentenpakete mit einer Konfiguration für die Autoregistrierung zu versehen.
Die Regel für die Agentenbäckerei heißt xref:hosts_autoregister.html#rule_autoregister_bakery[[.guihint]#Agent controller auto-registration.#]
Diese Pakete führen die Registrierung automatisch nach der Installation durch.

|Berechtigung zur Agentenregistrierung |Die xref:wato_user#predefined_roles[vordefinierte Rolle] `agent_registration` enthält zusätzliche Berechtigungen, um Hosts automatisch zu erstellen.
|===


[#connections]
=== Anbindungen

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen
|Grafana |Das xref:grafana#[Grafana-Plugin] können Sie direkt aus dem link:https://grafana.com/grafana/plugins/checkmk-cloud-datasource[Grafana-Katalog^] installieren, so dass sich die Integration einfach in Ihre Cloud-Umgebung einbetten lässt.
|===


[#provision]
=== Bereitstellung

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen

|Verfügbarkeit in den Azure und AWS Marketplaces |{CE} (Self-hosted) steht in den Marketplaces von link:https://azuremarketplace.microsoft.com/de-de/marketplace/apps/tribe29gmbh1665582614827.checkmk003?tab=Overview[Microsoft Azure^] und link:https://aws.amazon.com/marketplace/pp/prodview-gddkal2hfn7yo[AWS^] zur Installation bereit.
Die Artikel zu den Images von xref:install_azure#[Azure] und xref:install_aws#[AWS] führen Sie in die Einrichtung ein.

|Test der Edition |Sie können {CE} (Self-hosted) 30 Tage lang in vollem Funktionsumfang unverbindlich testen.
In kleinem Rahmen, d.h. mit einer Instanz und bis zu 750 Services, können Sie {CMK} mit {CE} (Self-hosted) auch dauerhaft ohne Subskription betreiben.
|===


[#other]
=== Weitere Funktionen

[cols="20,~",options="header"]
|===
|Funktion |Ergänzende Informationen

|Check-Plugins für AWS |Es gibt zusätzliche Check-Plugins für die AWS Cloud-Produkte
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_lambda[AWS Lambda,^]
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_ecs[Elastic Container Service (ECS),^]
link:https://checkmk.com/de/integrations/aws_route53[Route 53,^]
link:https://checkmk.com/de/integrations/aws_cloudfront[CloudFront,^]
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=elasticache[ElastiCache for Redis^] und
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_sns[Simple Notification Service (SNS).^]

|Check-Plugins für Azure |Es gibt zusätzliche Check-Plugins für die Azure-Produkte
link:https://checkmk.com/de/integrations/azure_app_gateway[Application Gateway^] und 
link:https://checkmk.com/de/integrations/azure_vault_backup_containers[Recovery Services vaults.^]

|Check-Plugins für GCP |Es gibt zusätzliche Check-Plugins für die Goggle Cloud-Produkte
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_function[Cloud Functions,^]
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_run[Cloud Run^] und
link:https://checkmk.com/de/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_redis[Memorystore for Redis.^]
|===
