// -*- coding: utf-8 -*-
// IGNORE crontab liveproxyd npcd ui Addons
// SKIPCOMMITS
include::global_attr.adoc[]
= Instanzdienste
:revdate: draft
:title: Checkmk unter der Haube - Dienste einer {CMK}-Instanz im Überblick
:description: Für den Betrieb einer {CMK}-Instanz werden viele einzelne Dienste/Prozesse benötigt, die wir hier kurz vorstellen.


{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:omd_basics#[Instanzen mit OMD verwalten]
xref:wato_rules#[Regeln]
{related-end}

[IMPORTANT]
====
Dies ist ein früher Artikelentwurf -- Work in Progress! 
====

[#intro]
== Einleitung
Eine {CMK}-Instanz benötigt allerlei Dienste, allem voran den {CMK} Monitoring Core (CMC), aber genauso einen Apache-Webserver für die Web-Oberfläche, Cron für die Planung von Aufgaben und so weiter.
All diese Dienste sehen Sie beim Start einer Instanz mittels `omd start` im Terminal -- einige in allen Editionen und standardmäßig, andere nur in bestimmten Editionen und/oder wenn entsprechende Funktionen aktiviert sind.
Der Befehl `omd status` auf eine kommerzielle Edition könnte etwa zu folgender Ausgabe führen:

[{shell}]
----
{c-omd} omd status

jaeger:             [green]#running#
agent-receiver:     [green]#running#
mkeventd:           [green]#running#
liveproxyd:         [green]#running#
mknotifyd:          [green]#running#
rrdcached:          [green]#running#
redis:              [green]#running#
automation-helper:  [green]#running#
ui-job-scheduler:   [green]#running#
cmc:                [green]#running#
apache:             [green]#running#
dcd:                [green]#running#
stunnel:            [green]#running#
xinetd:             [green]#running#
crontab:            [green]#running#
rabbitmq:           [green]#running#
---------------------------
Overall state:      [green]#running#
----

[#siteservices]
== Instanzdienste - Tabelle

Die folgende Tabelle gibt einen kurzen Überblick und zeigt zu jedem Dienst

- den angezeigten Prozessnamen,
- ob er in der Open-Source-Edition und/oder in den kommerziellen existiert,
- ob er standardmäßig, ohne explizite Konfiguration existiert sowie
- eine kurze Beschreibung, was der Dienst überhaupt erledigt.

Die meisten Dienste werden in den zugehörigen verlinkten Artikeln genauer erklärt, andere sind weitgehend selbsterklärend (etwa der Apache-Dienst).
Auf einige weitere Dienste, die lediglich im Hintergrund ihre Arbeit verrichten, gehen wir separat ein.

[cols="~,~,~,~,40",options="header"]
|===
|Dienst |{CRE} |kommerzielle Editionen |Standardmäßig aktiv |Beschreibung
|agent-receiver |Ja |Ja |Ja |Endpunkt für die xref:wato_monitoringagents#agents[Kommunikation mit dem Agenten]
|apache |Ja |Ja |Ja |Webserver
|automation-helper |Ja |Ja |Ja |Hilfsdienst zur Performance-Steigerung bei GUI- und Rest-API-Anfragen
|cmc |Nein |Ja |Ja |xref:cmc#[{CMK} Micro Core] -- Monitoring-Kern in den kommerziellen Editionen
|crontab |Ja |Ja |Ja |crontab-Datei für interne Aufgabenplanung
|dcd |Nein |Ja |Ja |xref:dcd#[Dynamic Configuration Daemon] zur automatischen Verwaltung flüchtiger Hosts (etwa Container)
|jaeger  |Nein |Ja |Nein |Analyse-Werkzeug für Traces, empfangen via OpenTelemetry -- für internes Bug-Fixing , xref:#jaeger[siehe unten]
|liveproxyd |Ja |Ja |Ja |Schnittstelle für xref:livestatus#[Statusdaten]
|mkeventd |Ja |Ja |Ja |Dienst zur Verarbeitung von xref:ec#[Ereignissen]
|mknotifyd |Nein |Ja |Nein |xref:notifications#[Benachrichtigungs-Spooler] für asynchrone Zustellung und verteilte Umgebungen
|nagios |Ja |Nein |Ja |Monitoring-Kern der {CRE} und alter Installationen kommerzieller Editionen (kann xref:cmc_migration#[umgestellt] werden)
|npcd |Ja |Nein |Ja |link:https://linux.die.net/man/8/npcd[Nagios Performance C Daemon] zur Verarbeitung von Nagios-Performance-Daten in der {CRE}
|RabbitMQ |Nein |Ja |Nein |Message-Broker, xref:#rabbitmq[siehe unten]
|redis |Ja |Ja |Ja |Im-Memory-Datenbank als Zwischenspeicher (liefert beispielsweise den Index für die Suche)
|rrdcached |Ja |Ja |Ja |xref:graphing#rrds[RRD-Cache-Daemon] für die Zwischenspeicherung von Messwerten
|stunnel |Ja |Ja |Nein |Baut einen xref:livestatus#[Tunnel] von einem lokalen, unverschlüsselten Livestatus-Port zu einem entfernten verschlüsselten auf
|ui-job-scheduler |Nein |Ja |Nein |Scheduler für asynchrone Aufgaben der Web-Oberfläche
|xinetd |Ja |Ja |Nein |Dienst zur Bereitstellung der Agentenausgabe
|===

[#siteservicesdetails]
== Dienste im Detail
[#jaeger]
=== Jaeger
link:https://www.jaegertracing.io[Jaeger^] ist ein Analyse-Werkzeug, um Anfragen in einem komplexen System zu verfolgen, zu analysieren und zu visualisieren.
In {CMK} könnten das etwa die einzelnen Teile eines Netzwerkscans sein, sprich Anfragen an die interne Datenbank, Pings, Dateioperationen und so weiter.
All diese kleinen Segmente benötigen Zeit und Jaeger kann hier dabei helfen, Performance-Probleme zu verstehen und Flaschenhälse aufzuspüren.
Jaeger wurde primär für die Entwicklung von {CMK} eingefügt und ist nur aktiv, wenn das Senden und Empfangen von Traces in der Instanzkonfiguration (`omd config`) explizit unter [.guihint]#Addons > Trace# aktiviert wurde.
Wenn aktiviert, erreichen Sie die Jaeger-Web-Oberfläche über `/mycmkserver/mysite/jaeger`.
Weitere Informationen finden Sie im zugehörigen link:https://checkmk.com/werk/16565[Werk 16565].
Im Regelbetrieb sollte Jaeger deaktiviert sein.

[#rabbitmq]
=== RabbitMQ
link:https://www.rabbitmq.com[RabbitMQ^] ist ein Message-Broker, grundsätzlich geeignet, um jegliche Form von Nachrichten mit Hilfe von Warteschlangen (Queues) zu versenden.
In {CMK} wird RabbitMQ derzeit als Funktion im Zusammenspiel mit dem Piggyback-Hub eingesetzt.
Ganz kurz erklärt: Wenn im verteilten Monitoring Piggyback-Daten anfallen, sorgt RabbitMQ dafür, dass diese von den Instanzen, auf denen sie anfallen, an die Instanzen weitergeleitet werden, auf denen sie benötigt/ausgewertet werden.
Eine ausführliche, technische Erklärung der Funktionsweise zeigt Ihnen der Vortrag link:https://www.youtube.com/watch?v=WQ-3rFQub6U[Piggyback unleashed - a new way for intersite communication^] von der 11. {CMK}-Konferenz.

=== cmk-ui-job-scheduler
Der `cmk-ui-job-scheduler`-Dienst organisiert asynchrone Aufgaben, die in der Web-Oberfläche anfallen.
Das wohl prominenteste Beispiel: Die Aktivierung von Änderungen.
Dabei wird die Web-Oberfläche aktualisiert, ein animierte Fortschrittsanzeige wird eingeblendet, Änderungen werden angewendet und schlussendlich wird die Ansicht wieder aktualisiert, etwaige Statusmeldungen werden ausgegeben -- während dieser Aktivitäten erscheinen und verschwinden weitere Kind-Prozesse und die Prozessorlast geht kurzzeitig nach oben.

=== automation-helper
Der Dienst `automation-helper` beschleunigt einige UI-Interaktionen, beispielsweise die Service-Erkennung und die Aktivierung von Änderungen, insbesondere in kleinen bis mittleren Installationen (siehe auch link:https://checkmk.com/werk/17678[Werk 17678]).
Der Dienst lässt sich in der OMD-Konfiguration im Terminal deaktivieren.

// ML: to be validated ... ; zudem gibt es in den globalen Einstellungen unter [.guihint]#Debugging of {CMK} helpers# die Möglichkeit, Fehlermeldungen für alle Hilfsdienste zu aktivieren.

Die meisten der hier aufgeführten Prozesse werden übrigens im Rahmen von {CMK}s xref:self_monitoring#[Selbstüberwachung] nebst einigen weiteren automatisch ins Monitoring übernommen.
Sollten Sie Performance-Probleme bemerken, kann es sich lohnen, das Monitoring des {CMK}-Servers selbst weiter auszubauen.