// -*- coding: utf-8 -*-
// IGNORE Addons Crontab
// NONASCII
include::global_attr.adoc[]
= Instanzdienste
:title: Instanzdienste - {CMK} unter der Haube
:description: Für den Betrieb einer {CMK}-Instanz werden viele einzelne Dienste/Prozesse benötigt. Diese werden hier kurz vorgestellt.

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:omd_basics#[Instanzen (Sites) mit omd verwalten]
xref:wato_rules#[Regeln]
{related-end}


[TIP]
====
Dieser Artikel entsteht gerade und ist daher _Work in Progress_.
====


[#intro]
== Einleitung

Eine {CMK}-xref:glossar#site[Instanz] benötigt allerlei Dienste, allem voran den Monitoring-Kern, aber genauso einen Apache-Webserver für die Web-Oberfläche, Cron für die Planung von Aufgaben und viele andere mehr.
All diese Dienste sehen Sie beim Start einer Instanz mittels `omd start` im Terminal -- einige in allen xref:glossar#edition[Editionen] und standardmäßig, andere nur in bestimmten Editionen und/oder wenn entsprechende Funktionen aktiviert sind.

Der Befehl `omd status` könnte in einer kommerziellen Edition etwa zu folgender Ausgabe führen:

[{shell}]
----
{c-omd} omd status
jaeger:             [green]#running#
agent-receiver:     [green]#running#
mkeventd:           [green]#running#
liveproxyd:         [green]#running#
mknotifyd:          [green]#running#
rrdcached:          [green]#running#
redis:              [green]#running#
automation-helper:  [green]#running#
ui-job-scheduler:   [green]#running#
cmc:                [green]#running#
apache:             [green]#running#
dcd:                [green]#running#
stunnel:            [green]#running#
xinetd:             [green]#running#
crontab:            [green]#running#
rabbitmq:           [green]#running#
---------------------------
Overall state:      [green]#running#
----


[#siteservices]
== Dienste im Überblick

Die folgende Tabelle gibt einen kurzen Überblick und zeigt zu jedem Dienst

* den angezeigten Prozessnamen,
* ob er in {CRE} und/oder in den kommerziellen Editionen existiert,
* ob er standardmäßig, ohne explizite Konfiguration existiert sowie
* eine kurze Beschreibung, was der Dienst überhaupt erledigt.

Die meisten Dienste werden in den zugehörigen verlinkten Artikeln genauer erklärt, andere sind weitgehend selbsterklärend (etwa der Apache-Dienst).
Auf einige weitere Dienste, die lediglich im Hintergrund ihre Arbeit verrichten, gehen wir im xref:siteservicesdetails[folgenden Kapitel] ein.

[cols="20,~,~,~,40",options="header"]
|===
|Dienst |{CRE} |kommerzielle Editionen |Standardmäßig aktiv |Beschreibung
|`agent-receiver` |Ja |Ja |Ja |Endpunkt für die xref:wato_monitoringagents#agents[Kommunikation mit dem {CMK}-Agenten]
|`apache` |Ja |Ja |Ja |Webserver
|`automation-helper` |Ja |Ja |Ja |Hilfsdienst zur Performance-Steigerung bei GUI- und REST-API-Anfragen, mehr Details xref:automation-helper[weiter unten]
|`cmc` |Nein |Ja |Ja |xref:cmc#[{CMK} Micro Core] -- Monitoring-Kern in den kommerziellen Editionen
|`crontab` |Ja |Ja |Ja |Crontab-Datei für interne Aufgabenplanung
|`dcd` |Nein |Ja |Ja |Dynamic Configuration Daemon für die xref:dcd#[dynamische Host-Verwaltung] flüchtiger Hosts (etwa Container)
|`jaeger` |Nein |Ja |Nein |Analyse-Werkzeug für Traces, empfangen via xref:opentelemetry#[OpenTelemetry] -- für internes Bug-Fixing, mehr Details xref:jaeger[weiter unten]
|`liveproxyd` |Ja |Ja |Ja |Schnittstelle zum Abruf von Statusdaten über xref:glossar#livestatus[Livestatus]
|`mkeventd` |Ja |Ja |Ja |Dienst zur Verarbeitung von Ereignissen mit der xref:glossar.html#ec[Event Console]
|`mknotifyd` |Nein |Ja |Nein |xref:notifications#async[Benachrichtigungs-Spooler] für asynchrone Zustellung und verteilte Umgebungen
|`nagios` |Ja |Nein |Ja |Monitoring-Kern der {RE} und alter Installationen kommerzieller Editionen (kann dort auf den CMC xref:cmc_migration#[migriert] werden)
|`npcd` |Ja |Nein |Ja |link:https://linux.die.net/man/8/npcd[Nagios Performance C Daemon] zur Verarbeitung von Nagios-Performance-Daten in {RE}
|`piggyback-hub` |Ja |Ja |Nein |Piggyback-Hub im xref:glossar#distributed_monitoring[verteilten Monitoring], mehr Details xref:rabbitmq[weiter unten]
// TK: piggyback-hub hab ich ergänzt, auch unten im RabbitMQ-Abschnitt
|`rabbitmq` |Nein |Ja |Nein |Message Broker RabbitMQ, mehr Details xref:rabbitmq[weiter unten]
|`redis` |Ja |Ja |Ja |Im-Memory-Datenbank als Zwischenspeicher (liefert beispielsweise den Index für die Suche)
|`rrdcached` |Ja |Ja |Ja |xref:graphing#rrds[RRD-Cache-Daemon] für die Zwischenspeicherung von Messwerten
|`stunnel` |Ja |Ja |Nein |Baut im verteilten Monitoring einen xref:distributed_monitoring#livestatus_tls[Tunnel] von einem lokalen, unverschlüsselten Livestatus-Port zu einem entfernten verschlüsselten auf
|`ui-job-scheduler` |Nein |Ja |Nein |Planer für asynchrone Aufgaben der Weboberfläche, mehr Details xref:ui-job-scheduler[weiter unten]
|`xinetd` |Ja |Ja |Nein |Dienst zur Bereitstellung der Agentenausgabe
// TK: zur Bereitstellung der Agentenausgabe? Das klingt sehr allgemein. xinetd ist doch nur ein Notnagel, falls systemd nicht läuft und dann unverschlüsselt ohne Agent Controller übertragen werden muss.
// TK: also vielleicht besser so: Dienst zur Bereitstellung der Agentenausgabe für Linux im Legacy-Modus?
// TK: Ich hab xinetd noch nie gesehen. Wann erscheint der denn in der Liste? Wenn ich das hier gemacht habe? https://docs.checkmk.com/master/de/agent_linux_legacy.html#xinetd
|===

Die meisten der hier aufgeführten Dienste werden übrigens im Rahmen der {CMK}-xref:self_monitoring#[Selbstüberwachung] nebst einigen weiteren automatisch ins Monitoring übernommen.
Sollten Sie Performance-Probleme bemerken, kann es sich lohnen, das Monitoring des {CMK}-Servers selbst weiter auszubauen.


[#siteservicesdetails]
== Dienste im Detail

[#jaeger]
=== Jaeger

link:https://www.jaegertracing.io[Jaeger^] ist ein Analyse-Werkzeug, um Anfragen in einem komplexen System zu verfolgen, zu analysieren und zu visualisieren.
In {CMK} könnten das etwa die einzelnen Teile eines Netzwerkscans sein, sprich Anfragen an die interne Datenbank, Pings, Dateioperationen und so weiter.
All diese kleinen Segmente benötigen Zeit und Jaeger kann hier dabei helfen, Performance-Probleme zu verstehen und Flaschenhälse aufzuspüren.

Jaeger wurde primär für die Entwicklung von {CMK} eingefügt und ist nur aktiv, wenn das Senden und Empfangen von Traces in der Instanzkonfiguration per xref:omd_basics#omd_config[`omd config`] explizit im Menü [.guihint]#Addons > TRACE RECEIVE# bzw. [.guihint]#TRACE SEND# aktiviert wurde.
Wenn aktiviert, erreichen Sie die Jaeger-Weboberfläche über `\http://mycmkserver/mysite/jaeger`.
// TK: Dann muss man sich aber noch Anmelden, ohne das einem gesagt wird, womit. cmkadmin hat dann funktioniert.
Weitere Informationen finden Sie im zugehörigen link:https://checkmk.com/werk/16565[Werk 16565^].

Im Regelbetrieb sollte Jaeger deaktiviert sein.


[#rabbitmq]
=== RabbitMQ und Piggyback-Hub

link:https://www.rabbitmq.com[RabbitMQ^] ist ein Message Broker, grundsätzlich geeignet, um jegliche Form von Nachrichten mit Hilfe von Warteschlangen (_queues_) zu versenden.
In {CMK} wird RabbitMQ derzeit als Funktion im Zusammenspiel mit dem Piggyback-Hub eingesetzt.
Ganz kurz erklärt: Wenn im verteilten Monitoring xref:glossar#piggyback[Piggyback]-Daten anfallen, sorgt RabbitMQ dafür, dass diese von den Instanzen, auf denen sie anfallen, an die Instanzen weitergeleitet werden, auf denen sie benötigt/ausgewertet werden.
Eine ausführliche, technische Erklärung der Funktionsweise zeigt Ihnen der Vortrag link:https://www.youtube.com/watch?v=WQ-3rFQub6U[Piggyback unleashed - a new way for intersite communication^] von der 11. {CMK}-Konferenz.

Wie Sie Piggyback-Hub und damit auch RabbitMQ aktivieren, steht im Artikel zum xref:distributed_monitoring#central_setup_config[verteilten Monitoring].


[#ui-job-scheduler]
=== `ui-job-scheduler`

Der Dienst `ui-job-scheduler` organisiert asynchrone Aufgaben, die in der Weboberfläche anfallen.
Das wohl prominenteste Beispiel: Die xref:glossar#activate_changes[Aktivierung von Änderungen].
Dabei wird die Weboberfläche aktualisiert, ein animierte Fortschrittsanzeige wird eingeblendet, Änderungen werden angewendet und schlussendlich wird die Ansicht wieder aktualisiert, etwaige Statusmeldungen werden ausgegeben
-- während dieser Aktivitäten erscheinen und verschwinden weitere Kind-Prozesse und die Prozessorlast geht kurzzeitig nach oben.


[#automation-helper]
=== `automation-helper`

Der Dienst `automation-helper` beschleunigt einige GUI-Interaktionen, beispielsweise die Service-Erkennung und die Aktivierung von Änderungen,
insbesondere in kleinen bis mittleren Installationen (siehe auch link:https://checkmk.com/werk/17678[Werk 17678^]).

Der Dienst lässt sich per `omd config` im Menü [.guihint]#Basic > AUTOMATION HELPER# deaktivieren.
// ML: to be validated ... ; zudem gibt es in den globalen Einstellungen unter [.guihint]#Debugging of {CMK} helpers# die Möglichkeit, Fehlermeldungen für alle Hilfsdienste zu aktivieren.
