// -*- coding: utf-8 -*-
// IGNORE testhost
// NONASCII
include::global_attr.adoc[]
= Password Store für Entwickelnde
:title: Password Store für Entwickelnde
:description: Der Password Store erlaubt die sichere Speicherung von Passwörtern. In diesem Artikel erfahren Sie, wie der Zugriff aus Spezialagenten möglich ist. 

{related-start}
xref:special_agents#[Spezialagenten]
xref:devel_special_agents#[Spezialagenten entwickeln]
// xref:dcd#[Dynamische Host-Verwaltung]
{related-end}

// ES: Nicht vergessen, den Artikel auch ins ToC einzuhängen.

// ES: Das Dictionary und der verlinkte Artikel verwenden auf Deutsch bevorzugt "Passwortspeicher". Hier bitte auch im ganzen Artikel anpassen, damit es einheitlich ist.

[#intro]
== Einleitung

Mit dem xref:password_store#[Password Store] kann {CMK} die Verwaltung von Passwörtern von ihrem Einsatz trennen.
Vor Version {v25} konnten dort gespeicherte Passwörter im Klartext an Spezialagenten oder aktive Checks weitergegeben werden.
Zudem stand eine nicht-öffentliche API zur Verfügung.
Diese wird nun durch einen ersten Entwurf (`v1_unstable`) einer öffentlichen API ergänzt.
Damit steht die Möglichkeit, dass ein Spezialagent oder aktiver Check selbst Passwörter aus dem Store ausliest, allen Entwickelnden von Erweiterungen zur Verfügung.

Der Password Store kommt übrigens auch im Hintergrund zum Einsatz, wenn Sie ein Passwort als [.guihint]#Explicit# markieren.
Sie können demnach mit denselben Programmierschnittstellen arbeiten, ohne wissen zu müssen, wie das verwendete Passwort verwaltet wird.

[TIP]
====
Einige der hier vorgestellten Programmierschnittstellen sind gegenwärtig als `unstable` markiert.
Derzeit planen wir, die Programmierschnittstellen in {CMK} {v30} als stabil zu veröffentlichen.
Hierfür wird es erforderlich sein, Erweiterungen des Funktionsumfangs vorzunehmen.
Möglicherweise sind für einige APIs auch kleinere, die Kompatibilität betreffende Änderungen nötig.
Rechnen Sie mit einem weitgehend reibungslosen Wechsel auf die stabile Version, aber dennoch mit der Notwendigkeit von Tests.
====

[#example_scope]
=== Scope der gezeigten Beispiele
// ES: Die Überschrift lieber ohne Anglizismus

In diesem Artikel lernen Sie anhand von zwei Beispielen die Verwendung von im Password Store gespeicherten Geheimnissen:

* Im Idealfall entwickeln Sie selbst Spezialagenten oder aktive Checks, für welche die Performance von Python 3 ausreicht und die unter {CMK} ab Version {v25} ausgeführt werden.
In diesem Fall verwenden Sie im Spezialagenten/aktiven Check die in `cmk.password_store.v1_unstable` definierten Programmierschnittstellen.
// ES: gerne direkt einen Link zur Referenz-Doku hier bei der ersten Erwähnung einfügen
Mit diesen wird eine Referenz auf den Password Store und die UUID des nachzuschlagenden Passwortes übergeben.

* In manchen Fällen ist es nicht möglich, Python 3 zu verwenden.
Oder ein Spezialagent oder aktiver Check muss unter anderen Monitoring-Systemen oder älteren Versionen von {CMK} ausführbar sein 
Oder aber, ein aktiver Check ist bereits vorhanden und soll lediglich mit einer Aufrufkonfiguration versehen werden.
In solchen Fällen können Sie das Passwort im Klartext als Kommandozeilenargument übergeben.
Hier sind gegebenenfalls weitere Maßnahmen erforderlich, um zu verhindern, dass das Passwort aus der Prozessliste ausgelesen wird.

// ES: Die Auflistung der zwei Szenarien ist für mich erst auf den zweiten Blick als Beschreibung der zwei im folgenden gezeigten Beispiele erkennbar. Evtl. leicht zu beheben, indem du die jeweils relevanten Abschnitte direkt von hier verlinkst.

Beide Beispiele verwenden zur Veranschaulichung einen simplen lokalen Check, der in der Service-Beschreibung das übergebene Passwort ausgibt.
Der lokale Check hat den Vorteil, dass nicht noch ein Check-Plugin geschrieben werden muss.
Beide Beispiele kommen so mit drei Dateien aus.

Auf eine detaillierte Beschreibung, wie nach welchen Anpassungen {CMK}-Dienste neu gestartet werden müssen, verzichten wir in diesem Artikel.
Schlagen Sie diese im Artikel zur xref:devel_special_agents#[Entwicklung von Spezialagenten] nach.


[#secure]
== Sichere Übergabe von Referenzen

Die sichere Übergabe einer Referenz auf ein Objekt im Password Store ist möglich, wenn Ihr Spezialagent oder aktiver Check ausschließlich unter {CMK} ab {v25} funktionieren muss.
Dann stehen Ihrem Programm die in `cmk.password_store.v1_unstable` definierten Programmierschnittstellen zur Verfügung.
// ES: Hier (wieder) direkt zu dieser Stelle der API-Doku verlinken
Mit der Referenz auf das Objekt im Password Store kann das Passwort dann von Ihrem Programm ausgelesen werden.

In diesem Beispiel zeigen wir einen minimalen Spezialagenten, der drei Beispieldateien benötigt.
Wenn Sie das Beispiel nachspielen wollen, legen Sie zunächst drei Ordner an:

[{shell}]
----
{c-omd} mkdir -p ~/local/lib/python3/cmk_addons/plugins/hellopassword/libexec
{c-omd} mkdir -p ~/local/lib/python3/cmk_addons/plugins/hellopassword/rulesets
{c-omd} mkdir -p ~/local/lib/python3/cmk_addons/plugins/hellopassword/server_side_calls
----

[#secure_special_agent]
=== Spezialagent

Im Spezialagenten importieren Sie die folgenden drei Dinge:

* eine Erweiterung für `argparse`, nämlich `parser_add_secret_option`,
* die Funktion `resolve_secret_option`, welche zum Auslesen des Passwortes dient,
* und schließlich die Klasse `Secret`, welche als Container für die vertraulichen Daten dient.

// ES: Der Hinweis "Shebang needed this time" ist eher verwirrend, da das hier das erste Beispiel im Artikel ist
.~/local/lib/python3/cmk_addons/plugins/hellopassword/libexec/agent_hellopassword
[{python}]
----
#!/usr/bin/env python3
# Shebang needed this time to find the interpreter!

import argparse
from cmk.password_store.v1_unstable import Secret, parser_add_secret_option, resolve_secret_option

SECRETOPT = "secret"

parser = argparse.ArgumentParser()
parser_add_secret_option(
    parser,
    long=f"--{SECRETOPT}",
    help="Specify the password to use.",
    required=True
)
args = parser.parse_args()

secret = resolve_secret_option(args, SECRETOPT)
print('<<<local>>>')
print('0 "Hello password" - The password you passed: ' + secret.reveal())
----
// ES: Wäre es hilfreich, einzelne Zeilen hier gelb hervorzuheben, um die Aufmerksamkeit der Lesenden auf die wichtigsten Stellen zu lenken?

Hier erstellen Sie zunächst den Parser für Befehlszeilenargumente.
Mit `parser_add_secret_option` fügen Sie die {CMK}-spezifische Erweiterung für die Übergabe der Referenz zum Password Store hinzu.
Der Clou:
Diese erstellt _zwei_ mögliche Argumente, nämlich nicht nur das erwartete -- hier `--secret` zur Übergabe eines Passworts -- , sondern auch ein zweites mit Bezug auf die Referenz.
// ES: Ungeduldige Leserinnen sind ab hier zwei Absätze lang verwirrt, ob sie schon hätten verstehen müssen, wie dieses geheimnisvolle zweite Argument heißt oder wie es funktioniert. Ich würde hier auf den Spannungsaufbau verzichten und die Information, was es mit dem zweiten Argument auf sich hat, entweder ganz oder gar nicht preisgeben.

[TIP]
====
Für die beiden folgenden Tests ist es wichtig, dass Sie mit `omd su mysite` zum Instanzbenutzer gewechselt haben.
Nur so ist sichergestellt, dass die Ausführungsumgebung der entspricht, unter der das Programm später von {CMK} ausgeführt wird.
====

Der Aufruf auf der Befehlszeile zeigt die „unerwartete“ zweite Option `--secret-id`:

[{shell}]
----
{c-omd} ~/local/lib/python3/cmk_addons/plugins/hellopassword/libexec/agent_hellopassword --help
usage: agent_hellopassword [-h] (--secret SECRET | --secret-id SECRET_ID)

options:
  -h, --help            show this help message and exit
  --secret SECRET       Specify the password to use.
  --secret-id SECRET_ID
                        Same as "--secret", but containing the reference to the password store rather than the actual secret.
----

Für Tests auf der Befehlszeile verwenden Sie die Option `--secret` und übergeben das Passwort im Klartext:

[{shell-raw}]
----
{c-omd} ~/local/lib/python3/cmk_addons/plugins/hellopassword/libexec/agent_hellopassword --secret 7op53cre7
<<<local>>>
0 "Hello password" - The password you passed: 7op53cre7
----

In den nächsten beiden Abschnitten zeigen wir die Übergabe von Referenzen.

[#secure_rulespec]
=== Formular und Regeln zur Konfiguration

Via `cmk.rulesets.v1.form_specs` und `cmk.rulesets.v1.rule_specs` definieren Sie das im Setup sichtbare Formular und die dazu passende Regelkonfiguration.
// ES: Direktlink zur API-Doku
Nachdem Sie diese Datei abgelegt und {CMK} neu gestartet haben, können Sie die Regel für [.guihint]#Hello password!# mit genau einem Feld konfigurieren: entweder einem im Password Store hinterlegten Passwort oder einem explizit angegebenen Passwort.
// ES: Überall im Artikel einheitliche Namen für die Elemente im Beispiel verwenden, entweder immer mit Ausrufezeichen oder immer ohne
Für diesen Artikel ist die Unterscheidung irrelevant, der Weg der später gezeigten Übergabe ist immer derselbe.

.~/local/lib/python3/cmk_addons/plugins/hellopassword/rulesets/special_agent.py
[{python}]
----
#!/usr/bin/env python3
# Shebang needed only for editors

from cmk.rulesets.v1.form_specs import Dictionary, DictElement, Password, migrate_to_password
from cmk.rulesets.v1.rule_specs import SpecialAgent, Topic, Help, Title

def _formspec():
    return Dictionary(
        title=Title("Hello password!"),
        help_text=Help("This rule is to demonstrate accessing the password store from a special agent."),
        elements={
            "password": DictElement(
                required=True,
                parameter_form=Password(
                    title=Title("Password for this user"),
                    migrate=migrate_to_password,
                ),
            ),
        }
    )

rule_spec_hellospecial = SpecialAgent(
    topic=Topic.GENERAL,
    name="hellopassword",
    title=Title("Hello password!"),
    parameter_form=_formspec
)
----
// ES: Was hat es mit migrate=migrate_to_password auf sich? Was migrieren wir da und warum und von wo nach wo?

Für die weiteren Tests sollten Sie einen eigenen Host anlegen, dem Sie nur den [.guihint]#Hello password!#-Spezialagenten zuordnen und sonst nichts.


[#secure_invocation]
=== Aufrufkonfiguration

Mit der Aufrufkonfiguration kommt alles zusammen.
Bei der Erzeugung der Parameter für die Befehlszeile wird `--secret-id` verwendet.
Der Parameter `params['password']` wird dabei implizit zu einer Referenz auf den Password Store umgewandelt:

.~/local/lib/python3/cmk_addons/plugins/hellopassword/server_side_calls/special_agent.py
[{python}]
----
#!/usr/bin/env python3
# Shebang needed only for editors

from cmk.server_side_calls.v1 import noop_parser, SpecialAgentConfig, SpecialAgentCommand

def _agent_arguments(params, host_config):
    yield SpecialAgentCommand(command_arguments=[ "--secret-id", params['password'] ])

special_agent_hellospecial = SpecialAgentConfig(
    name="hellopassword",
    parameter_parser=noop_parser,
    commands_function=_agent_arguments
)
----

Wenn Sie sehen wollen, wie die Übergabe der Referenz vonstatten geht, verwenden Sie doch einfach einmal `cmk -v -D testhost`:
// ES: Das hier ist die erste Erwähnung von `testhost` im Artikel, aber bevor wir das aufrufen können, muss die Voraussetzung explizit gemacht werden, dass wir einen so benannten Host überhaupt haben

[{shell}]
----
{c-omd} cmk -v -D testhost

testhost                                                                       
Addresses:              No IP
Tags:                   [address_family:no-ip], [agent:special-agents], [criticality:prod], [networking:lan], [piggyback:auto-piggyback], [site:mysite], [snmp_ds:no-snmp], [tcp:tcp]
Labels:                 [cmk/site:mysite]
Host groups:            check_mk
Contact groups:         all
Agent mode:             No Checkmk agent, all configured special agents
Type of agent:          
  Program: /omd/sites/mysite/local/lib/python3/cmk_addons/plugins/hellopassword/libexec/agent_hellopassword --secret-id uuid37481a65-579f-4779-ba50-f303decafbad:/omd/sites/mysite/var/check_mk/passwords_merged
  Process piggyback data
Services:
  checktype item           params description    groups
  --------- -------------- ------ -------------- ------
  local     Hello password {}     Hello password
----

In der Aufrufzeile sehen Sie die durch Doppelpunkt getrennte Referenz.
// ES: Was ist die Aufrufzeile? ggf. den relevanten Teil der Ausgabe highlighten?
Der erste Parameter ist die UUID des auszulesenden Passwortes, der zweite der Pfad zum zu verwendenden Password Store.
Wenn Sie schließlich die Servicedetails des Dienstes [.guihint]#Hello password# Ihres Hosts [.guihint]#testhost# ansehen, sehen Sie das im Password Store gespeicherte und mit `secret.reveal()` offengelegte Passwort.

[#insecure]
== Unsichere Übergabe von Passwörtern

Wählen Sie diesen Weg nur, wenn Sie beispielsweise andere Monitoring-Systeme oder ältere Versionen von {CMK} unterstützen müssen.

[IMPORTANT]
====
Im Klartext übergebene Passwörter sind in der Prozesstabelle sichtbar!
Unter Linux kann jedes Programm die Funktion link:https://manpages.debian.org/testing/libbsd-dev/setproctitle.3bsd.en.html[`setproctitle()`^] aus der `libbsd` verwenden, um Passwörter aus dem Prozessnamen zu entfernen.
Wrapper für diese Funktion existieren für praktisch alle Programmiersprachen.
*Aber:* Selbst wenn Sie `setproctitle()` verwenden, ist das Passwort für einen kurzen Moment zwischen Start des Programms und erfolgreichem Aufruf von `setproctitle()` sichtbar.
====

Auch in diesem Beispiel zeigen wir einen minimalen Spezialagenten, der drei Beispieldateien benötigt.
Wenn Sie das Beispiel nachspielen wollen, legen Sie zunächst drei Ordner an:

[{shell}]
----
{c-omd} mkdir -p ~/local/lib/python3/cmk_addons/plugins/hellopassword_insecure/libexec
{c-omd} mkdir -p ~/local/lib/python3/cmk_addons/plugins/hellopassword_insecure/rulesets
{c-omd} mkdir -p ~/local/lib/python3/cmk_addons/plugins/hellopassword_insecure/server_side_calls
----

[#insecure_special_agent]
=== Spezialagent

Für dieses Beispiel haben wir einen Spezialagenten als simples Shell-Skript erstellt.
Es zeigt einfach alle übergebenen Aufrufparameter an:

.~/local/lib/python3/cmk_addons/plugins/hellopassword_insecure/libexec/agent_hellopassword_insecure
[{shell-raw}]
----
#!/bin/bash

echo '<<<local>>>'
echo '0 "Hello password insecure" - You called me with: '"$@"
----

[#insecure_rulespec]
=== Formular und Regeln zur Konfiguration

Formular und Regeln entsprechen bis auf den geänderten Namen der Plugin-Familie dem Beispiel oben:

.~/local/lib/python3/cmk_addons/plugins/hellopassword_insecure/rulesets/special_agent.py
[{python}]
----
#!/usr/bin/env python3
# Shebang needed only for editors

from cmk.rulesets.v1.form_specs import Dictionary, DictElement, Password, migrate_to_password
from cmk.rulesets.v1.rule_specs import SpecialAgent, Topic, Help, Title

def _formspec():
    return Dictionary(
        title=Title("Hello password (insecure)!"),
        help_text=Help("This rule is to demonstrate insecurely accessing the password store from a special agent."),
        elements={
            "password": DictElement(
                required=True,
                parameter_form=Password(
                    title=Title("Password for this user"),
                    migrate=migrate_to_password,
                ),
            ),
        }
    )

rule_spec_hellospecial = SpecialAgent(
    topic=Topic.GENERAL,
    name="hellopassword_insecure",
    title=Title("Hello password (insecure)!"),
    parameter_form=_formspec
)
----

[#insecure_invocation]
=== Aufrufkonfiguration

Die Aufrufkonfiguration unterscheidet sich in einigen wichtigen Details vom oben gezeigten Beispiel.
Gemäß Konvention wird bei der Erzeugung der Parameter für die Befehlszeile `--secret` (oder `--password`, jedenfalls ohne angehängtes `id`) verwendet.
Die Funktion `unsafe()` des `Secret`-Objekts (in `params['password'].unsafe()`) sorgt jetzt dafür, dass das Passwort bereits für den Programmaufruf im Klartext ausgelesen wird:

.~/local/lib/python3/cmk_addons/plugins/hellopassword_insecure/server_side_calls/special_agent.py
[{python}]
----
#!/usr/bin/env python3
# Shebang needed only for editors

from cmk.server_side_calls.v1 import noop_parser, SpecialAgentConfig, SpecialAgentCommand

def _agent_arguments(params, host_config):
    yield SpecialAgentCommand(command_arguments=[ "--secret", params['password'].unsafe() ])

special_agent_hellospecial = SpecialAgentConfig(
    name="hellopassword_insecure",
    parameter_parser=noop_parser,
    commands_function=_agent_arguments
)
----

In der Ausgabe von `cmk -v -D testhost` maskiert {CMK} das im Klartext übergebene Passwort:

[{shell}]
----
{c-omd} cmk -v -D testhost

testhost                                                                       
Addresses:              No IP
Tags:                   [address_family:no-ip], [agent:special-agents], [criticality:prod], [networking:lan], [piggyback:auto-piggyback], [site:mysite], [snmp_ds:no-snmp], [tcp:tcp]
Labels:                 [cmk/site:mysite]
Host groups:            check_mk
Contact groups:         all
Agent mode:             No Checkmk agent, all configured special agents
Type of agent:          
  Program: /omd/sites/mysite/local/lib/python3/cmk_addons/plugins/hellopassword_insecure/libexec/agent_hellopassword_insecure --secret '****'
  Process piggyback data
Services:
  checktype item                    params description             groups
  --------- ----------------------- ------ ----------------------- ------
  local     Hello password insecure {}     Hello password insecure
----

// ES: Ein abschließender Absatz fehlt hier. Artikel, die mit Code-Blöcken enden, lassen mich immer ein bisschen ratlos zurück. Was ist denn jetzt als nächstes zu tun?