// -*- coding: utf-8 -*-
// IGNORE 
// NONASCII
include::global_attr.adoc[]
= Installation unter Red Hat Enterprise Linux
:title: Installation unter Red Hat Enterprise Linux
:description: Sie können {CMK} unter Red Hat Enterprise Linux (RHEL) und binärkompatiblen Distributionen betreiben. Lesen Sie hier, wie Sie {CMK} dort installieren.    

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:appliance_install_virt1#[Virtuelle Appliance installieren]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
{related-end}


== Einrichten der Paketquellen

{CMK} benötigt etliche Software-Pakete Ihrer Linux-Distribution.
Software aus Drittquellen wird nicht benötigt.
Damit alle benötigten Pakete fehlerfrei nachinstalliert werden können, benötigen Sie eine korrekte Konfiguration der Software-Quellen.

Bei Red Hat Enterprise Linux (RHEL) und allen binärkompatiblen Distributionen wie CentOS, AlmaLinux oder Rocky Linux muss das _EPEL (Extra Packages for Enterprise Linux)_-Repository als Paketquelle eingerichtet werden.

include::include_centos_clarification.asciidoc[]

Das Einrichten als Paketquelle geschieht mit Hilfe eines RPM-Pakets, welches mit dem Befehl `dnf` installiert wird.

[cols="10,~",options="header"]
|===
|Version |Paketlink 
|10 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm`
|9 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm`
|8 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`
|===

Hier ein Beispiel für die Installation der EPEL-Paketquelle für die Version 10:

[{shell-raw}]
----
{c-root} dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm
----

Damit Sie EPEL auf RHEL und binärkompatiblen Distributionen nutzen können, benötigen Sie noch die Paketquelle für optionale RPMs, sofern diese nicht bereits bei der Installation des Betriebssystems eingerichtet worden ist.
Ohne diese Quelle werden Ihnen die Pakete `freeradius-utils`, `graphviz-gd` und `php-mbstring` fehlen.

Seit Version 8.x genügt hier die Aktivierung der sogenannten PowerTools mithilfe des Dandified YUM (`dnf`) in den freien binärkompatiblen Distributionen bzw. dem `subscription-manager` in RHEL.
Ab Version 9.x verwenden RHEL und die binärkompatiblen Betriebssysteme stattdessen den CodeReady Linux Builder (CRB).
Dies geht z.B. mit folgenden Befehlen:

CentOS ab 8.4, AlmaLinux 8.x und Rocky Linux 8.x verwenden die PowerTools:

[{shell}]
----
{c-root} dnf config-manager --set-enabled powertools
----

Ab Version 9.x benötigen AlmaLinux und Rocky Linux stattdessen den CodeReady Linux Builder (CRB): 

[{shell}]
----
{c-root} dnf config-manager --set-enabled crb
----
// TK: crb wird im Einleitungstext nicht erwähnt: Was mache ich hier?
// SH: Ich erwähne es nun oben im Text und erkläre es genauer in einer Admonition, die ich unter dem Text platziert habe von der Logik her. 
// SH: Die Admonition steht unter dem Text, damit der Fokus beim Wesentlichen bleibt - der Anleitung mit den Befehlen.

// TK: Unklar, ob ich für AlmaLinux und Rocky Linux beide dnf config-manager Befehle absetzen muss oder nur den zweiten.
// SH: Das hängt davon ab, welche Version der Betriebssysteme man im Einsatz hat. 
// SH: RHEL 9.x, AlmaLinux 9.x, Rocky 9.x und alles in 10.x verwenden den CodeReady Linux Builder.
// SH: Das ist ein Repository mit zusätzlichen Paketen für Entwickler und löst die PowerTools ab.

// SH: Hintergründe zum crb-Repo: https://discussion.fedoraproject.org/t/what-does-dnf-config-manager-set-enabled-crb-perform/74397/5
// SH: Notes on CRB bei Rocky Linux: https://wiki.rockylinux.org/rocky/repo/ --> Das ersetzt dort die PowerTools. 
// SH: RHEL und die binärkompatiblen Distros (Alma, Rocky) verwenden seit Version 9.x CRB, das CodeReady Linux Builder-Repositoy. 
// SH: Ein Fachartikel zum Thema sitzt bei Red Hat hinter der Paywall: https://access.redhat.com/articles/4348511#enable
// SH: PowerTools und CRB sind äquivalent. Es kommt einfach drauf an, welche Version des Betriebssystems man (noch) verwendet.
// SH: Rocky, Alma, RHEL setzen seit 9.x und für die Zukunft auf CRB. PowerTools sind ein Überbleibsel ("Carryover") von CentOS, steht in den Notes on CRB. 

RHEL setzt seit Version 9 ebenfalls auf ein CRB-Repository. Für RHEL 10.x ist es installierbar mit folgendem Befehl:

[{shell}]
----
{c-root} subscription-manager repos --enable "codeready-builder-for-rhel-10-x86_64-rpms"
----

[TIP]
====
Der CodeReady Linux Builder (CRB) ist ein Repository, das zusätzliche Pakete für Entwickler enthält – es löst die älteren PowerTools ab. 
Die PowerTools waren ein Überbleibsel aus dem CentOS-Projekt, CRB ist das modernere Äquivalent dazu. 
Seit Version 9.x und für die Zukunft setzen RHEL und seine binärkompatiblen Enterprise-Linux-Betriebssysteme ausschließlich auf CRB.
====

== Einrichten von SELinux und Firewall

Da RHEL und damit auch die binärkompatiblen Distributionen standardmäßig Security-Enhanced Linux (SELinux) und eine lokale Firewall mitliefern, müssen hier gegebenenfalls noch Anpassungen vorgenommen werden.
Erlauben Sie zunächst, dass der Webserver auf die Netzwerkschnittstellen zugreifen darf:

[{shell}]
----
{c-root} setsebool -P httpd_can_network_connect 1
----

Falls Sie `firewalld` benutzen, geben Sie den Webserver frei und aktivieren die Änderung:

[{shell}]
----
{c-root} firewall-cmd --zone=public --add-service=http --permanent
success
{c-root} firewall-cmd --reload
success
----

== Herunterladen des passenden Pakets

// Die folgenden 3 Absätze sind identisch in install_packages_debian, install_packages_redhat und install_packages_sles
Wählen Sie zunächst die für Ihre Bedürfnisse passende xref:intro_setup#editions[{CMK}-Edition.]
Auf der link:https://checkmk.com/de/download[Download-Seite^] finden Sie {RE}, welche Open Source ist, und die bis 750 Services gratis nutzbare {CE}. 
Wenn Sie eine Subskription besitzen, dann finden Sie die Installationspakete im link:https://portal.checkmk.com/de/[Kundenportal.^]

Wir empfehlen den Einsatz der _letzten stabilen {CMK}-Version._
Falls Sie (beispielsweise als Basis für die Wiederherstellung eines Backups) eine ältere Version benötigen, finden Sie diese im link:https://checkmk.com/de/download/archive[Download-Archiv.^]
Achten Sie darauf, dass das ausgewählte Paket exakt zur installierten Linux-Distribution und deren Version passt.

Nachdem Sie das Paket heruntergeladen haben, bringen Sie es auf das Linux-System, auf dem {CMK} installiert werden soll.
Das kann zum Beispiel über das Befehlszeilentool `scp` geschehen, welches jedes moderne System mitbringt – und auch seit Windows 10 in der PowerShell verfügbar ist.
Zusätzliche Programme wie _WinSCP_ sind meist nicht erforderlich.

Das Beispiel zeigt die Übertragung eines {CRE} Pakets auf RHEL 8.x:

[{shell-raw}]
----
{c-root} scp check-mk-raw-{current}-el8-38.x86_64.rpm root@mymonitoring.mydomain.org:/tmp
----


[#signed]
== Installation des signierten Pakets

Alle Pakete werden mittels link:https://gnupg.org[GnuPG^] signiert.
Durch diese Signatur können Sie zum einen prüfen, ob das Paket auch wirklich von uns stammt, und zum anderen, ob es insgesamt vollständig ist.

Damit diese signierten Pakete wie gewohnt installiert werden können, müssen Sie einmalig unseren öffentlichen Schlüssel importieren, damit der Signatur vertraut wird.
Laden Sie dazu zuerst den Schlüssel direkt von unserer Website:

[{shell-raw}]
----
{c-root} wget https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

Danach importieren Sie den Schlüssel in die Liste der vertrauenswürdigen Signaturen.
Unter RHEL und allen binärkompatiblen Distributionen ist dafür das Tool `rpm` zuständig:

[{shell}]
----
{c-root} rpm --import Check_MK-pubkey.gpg
----

Sobald Sie den Schlüssel importiert haben, können Sie das Paket noch einmal verifizieren und anschließend wie gewohnt mit `dnf install` installieren:

[{shell}]
----
{c-root} rpm -K check-mk-raw-{current}-el8-38.x86_64.rpm
check-mk-raw-{current}-el8-38.x86_64.rpm: digests signatures OK
{c-root} dnf install check-mk-raw-{current}-el8-38.x86_64.rpm
----

== Abschlusstest

Nach der erfolgreichen Installation von {CMK} und allen Abhängigkeiten steht Ihnen der Befehl `omd` zur Verfügung,
mit dem Sie xref:omd_basics#[Monitoring-Instanzen] anlegen und verwalten können.
Zur Kontrolle können Sie die installierte Version ausgeben lassen:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version {current}.cre
----
