// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Installation unter Red Hat Enterprise Linux
:revdate: 2025-05-07
:title: Installation unter Red Hat Enterprise Linux
:description: Hier erfahren Sie, wie Sie {CMK} unter der Linux-Distribution Red Hat Enterprise Linux (RHEL) und binärkompatiblen Distributionen installieren.

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:appliance_install_virt1#[Virtuelle Appliance installieren]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
{related-end}


== Einrichten der Paketquellen

{CMK} benötigt etliche Software-Pakete Ihrer Linux-Distribution.
Software aus Drittquellen wird nicht benötigt.
Damit alle benötigten Pakete fehlerfrei nachinstalliert werden können, benötigen Sie eine korrekte Konfiguration der Software-Quellen.

Bei Red Hat Enterprise Linux (RHEL) und allen binärkompatiblen Distributionen wie CentOS, AlmaLinux oder Rocky Linux muss das _EPEL (Extra Packages for Enterprise Linux)_-Repository als Paketquelle eingerichtet werden.

Dies geschieht mit Hilfe eines RPM-Pakets, welches mit dem Befehl `yum` installiert wird.

[cols="10,~",options="header"]
|===
|Version |Paketlink 
|8 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`
|9 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm`
|===

Hier ein Beispiel für die Installation der EPEL-Paketquelle für die Version 8:

[{shell-raw}]
----
{c-root} yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----

Damit Sie EPEL auf RHEL und binärkompatiblen Distributionen nutzen können, benötigen Sie noch die Paketquelle für optionale RPMs, sofern diese nicht bereits bei der Installation des Betriebssystems eingerichtet worden ist.
Ohne diese Quelle werden Ihnen die Pakete `freeradius-utils`, `graphviz-gd` und `php-mbstring` fehlen.

Seit Version 8.x genügt hier die Aktivierung der sogenannten PowerTools mithilfe des Dandified YUM in den freien binärkompatiblen Distributionen bzw. dem `subscription-manager` in RHEL.
Dies geht z.B. mit folgenden Befehlen:

CentOS ab 8.4, AlmaLinux und Rocky Linux:

[{shell}]
----
{c-root} dnf config-manager --set-enabled powertools
----

RHEL 8.x:

[{shell}]
----
{c-root} subscription-manager repos --enable "codeready-builder-for-rhel-8-x86_64-rpms"
----
// TK: Das subscription-manager Kommando fehlt für RHEL9.x. Hab das hier gefunden: https://www.tecmint.com/install-epel-repo-rhel-9/
// TK: Dort steht das Kommando: subscription-manager repos --enable codeready-builder-for-rhel-9-$(arch)-rpms
// TK: Allerdings steht da auch noch ein weiteres Kommando zum Installieren: dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y


== Einrichten von SELinux und Firewall

Da RHEL und damit auch die binärkompatiblen Distributionen standardmäßig Security-Enhanced Linux (SELinux) und eine lokale Firewall mitliefern, müssen hier gegebenenfalls noch Anpassungen vorgenommen werden.
Erlauben Sie zunächst, dass der Webserver auf die Netzwerkschnittstellen zugreifen darf:

[{shell}]
----
{c-root} setsebool -P httpd_can_network_connect 1
----

Als Zweites geben Sie den Webserver frei und aktivieren die Änderung:

[{shell}]
----
{c-root} firewall-cmd --zone=public --add-service=http --permanent
success
{c-root} firewall-cmd --reload
success
----


== Herunterladen des passenden Pakets

// Die folgenden 3 Absätze sind identisch in install_packages_debian, install_packages_redhat und install_packages_sles
Wählen Sie zunächst die für Ihre Bedürfnisse passende xref:intro_setup#editions[{CMK}-Edition.]
Auf der link:https://checkmk.com/de/download[Download-Seite^] finden Sie {RE}, welche Open Source ist, und die bis 750 Services gratis nutzbare {CE}. 
Wenn Sie eine Subskription besitzen, dann finden Sie die Installationspakete im link:https://portal.checkmk.com/de/[Kundenportal.^]

Wir empfehlen den Einsatz der _letzten stabilen {CMK}-Version._
Falls Sie (beispielsweise als Basis für die Wiederherstellung eines Backups) eine ältere Version benötigen, finden Sie diese im link:https://checkmk.com/de/download/archive[Download-Archiv.^]
Achten Sie darauf, dass das ausgewählte Paket exakt zur installierten Linux-Distribution und deren Version passt.

Nachdem Sie das Paket heruntergeladen haben, bringen Sie es auf das Linux-System, auf dem {CMK} installiert werden soll.
Das kann zum Beispiel über das Kommandozeilentool `scp` geschehen, welches jedes moderne System mitbringt – und auch seit Windows 10 in der PowerShell verfügbar ist.
Zusätzliche Programme wie _WinSCP_ sind meist nicht erforderlich.

Das Beispiel zeigt die Übertragung eines {CRE} Pakets auf RHEL 8.x:

[{shell-raw}]
----
{c-root} scp check-mk-raw-{current}-el8-38.x86_64.rpm root@mymonitoring.mydomain.org:/tmp
----


[#signed]
== Installation des signierten Pakets

Alle Pakete werden mittels link:https://gnupg.org[GnuPG^] signiert.
Durch diese Signatur können Sie zum einen prüfen, ob das Paket auch wirklich von uns stammt, und zum anderen, ob es insgesamt vollständig ist.

Damit diese signierten Pakete wie gewohnt installiert werden können, müssen Sie einmalig unseren öffentlichen Schlüssel importieren, damit der Signatur vertraut wird.
Laden Sie dazu zuerst den Schlüssel direkt von unserer Website:

[{shell-raw}]
----
{c-root} wget https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

////
Alternativ können Sie den Schlüssel aber auch über link:http://keys.gnupg.net[gnupg.net^] beziehen:

[{shell}]
----
{c-root} gpg --keyserver keys.gnupg.net --recv-keys 434DAC48C4503261
{c-root} gpg --armor --export 434DAC48C4503261 > Check_MK-pubkey.gpg
----
////

Danach importieren Sie den Schlüssel in die Liste der vertrauenswürdigen Signaturen.
Unter RHEL und allen binärkompatiblen Distributionen ist dafür das Tool `rpm` zuständig:

[{shell}]
----
{c-root} rpm --import Check_MK-pubkey.gpg
----

Sobald Sie den Schlüssel importiert haben, können Sie das Paket noch einmal verifizieren und anschließend wie gewohnt mit `yum install` installieren:

[{shell}]
----
{c-root} rpm -K check-mk-raw-{current}-el8-38.x86_64.rpm
check-mk-raw-{current}-el8-38.x86_64.rpm: digests signatures OK
{c-root} yum install check-mk-raw-{current}-el8-38.x86_64.rpm
----


== Abschlusstest

Nach der erfolgreichen Installation von {CMK} und allen Abhängigkeiten steht Ihnen der Befehl `omd` zur Verfügung,
mit dem Sie xref:omd_basics#[Monitoring-Instanzen] anlegen und verwalten können.
Zur Kontrolle können Sie die installierte Version ausgeben lassen:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version {current}.cre
----
