// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Installation unter SUSE Linux Enterprise Server
:revdate: 2023-05-08
:title: Installation unter SUSE Linux Enterprise Server
:description: Hier erfahren Sie, wie Sie {CMK} unter der Linux-Distribution von SUSE Linux Enterprise Server (SLES) installieren.

{related-start}
xref:intro_setup#[{CMK} aufsetzen]
xref:appliance_install_virt1#[Virtuelle Appliance installieren]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
{related-end}


== Einrichten der Paketquellen

{CMK} benötigt etliche Software-Pakete Ihrer Linux-Distribution.
Software aus Drittquellen wird nicht benötigt.
Damit alle benötigten Pakete korrekt nachinstalliert werden können, benötigen Sie eine korrekte Konfiguration der Software-Quellen.

Das Vorgehen zum Einrichten unterscheidet sich je nach verwendeter Version von SUSE Linux Enterprise Server (SLES) ein wenig.


[#sles12]
=== SLES 12

Mit SLES 12 wurden einige Software-Komponenten, wie z.B. PHP, das von OMD benötigt wird, in sogenannte Module ausgelagert.
Damit Sie Zugriff auf die PHP-Pakete von SLES 12 bekommen, müssen Sie folgende Schritte ausführen:

. link:https://documentation.suse.com/de-de/sles/12-SP4/html/SLES-all/cha-planning.html#sec-planning-registering[Registrieren von SLES 12^]
. link:https://documentation.suse.com/de-de/sles/12-SP4/html/SLES-all/cha-add-ons.html#sec-add-ons-installation[Installieren des Moduls „Web and Scripting“^]


[#sles15]
=== SLES 15

Unter SLES 15 müssen Sie zusätzlich zum Modul „Web and Scripting“ noch die Module „Development Tools“ und „SUSE Package Hub 15“ installieren:

* link:https://documentation.suse.com/de-de/sles/15-SP1/html/SLES-all/cha-register-sle.html[Registrieren von SLES 15 und Verwalten von Modulen^]


== Herunterladen des passenden Pakets

// Die folgenden 3 Absätze sind identisch in install_packages_debian, install_packages_redhat und install_packages_sles
Wählen Sie zunächst die für Ihre Bedürfnisse passende xref:intro_setup#editions[{CMK}-Edition.]
Auf der link:https://checkmk.com/de/download[Download-Seite^] finden Sie die {RE}, welche Open Source ist, und die bis 750 Services gratis nutzbare {CE}. 
Wenn Sie eine Subskription besitzen, dann finden Sie die Installationspakete im link:https://portal.checkmk.com/de/[Kundenportal.^]

Wir empfehlen den Einsatz der _letzten stabilen {CMK}-Version._
Falls Sie (beispielsweise als Basis für die Wiederherstellung eines Backups) eine ältere Version benötigen, finden Sie diese im link:https://checkmk.com/de/download/archive[Download-Archiv.^]
Achten Sie darauf, dass das ausgewählte Paket exakt zur installierten Linux-Distribution und deren Version passt.

Nachdem Sie das Paket heruntergeladen haben, bringen Sie es auf das Linux-System, auf dem {CMK} installiert werden soll.
Das kann zum Beispiel über das Kommandozeilentool `scp` geschehen, welches jedes moderne System mitbringt – und auch bei Windows 10 in der PowerShell verfügbar ist.
Zusätzliche Programme wie _WinSCP_ sind meist nicht erforderlich.

Das Beispiel zeigt die Übertragung eines {CRE} Pakets auf SLES 15:

[{shell-raw}]
----
{c-root} scp check-mk-raw-2.2.0p1-sles15-38.x86_64.rpm root@mymonitoring.mydomain.org:
----


[#signed]
== Installation des signierten Pakets

Alle Pakete werden mittels link:https://gnupg.org[GnuPG^] signiert.
Durch diese Signatur können Sie zum einen prüfen, ob das Paket auch wirklich von uns stammt, und zum anderen, ob es insgesamt vollständig ist.

Damit diese signierten Pakete wie gewohnt installiert werden können, müssen Sie einmalig unseren öffentlichen Schlüssel importieren, damit der Signatur vertraut wird.
Laden Sie dazu zuerst den Schlüssel direkt von unserer Website:

[{shell-raw}]
----
{c-root} wget https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

////
Alternativ können Sie den Schlüssel aber auch über link:http://keys.gnupg.net[gnupg.net^] beziehen:

[{shell}]
----
{c-root} gpg --keyserver keys.gnupg.net --recv-keys 434DAC48C4503261
{c-root} gpg --armor --export 434DAC48C4503261 > Check_MK-pubkey.gpg
----
////

Danach importieren Sie den Schlüssel in die Liste der vertrauenswürdigen Signaturen.
Unter SLES ist dafür das Tool `rpm` zuständig:

[{shell}]
----
{c-root} rpm --import Check_MK-pubkey.gpg
----

Sobald Sie den Schlüssel importiert haben, können Sie das {CMK}-Paket nun noch einmal verifizieren und anschließend mit `zypper install` installieren:

[{shell}]
----
{c-root} rpm -K check-mk-raw-2.2.0p1-sles15-38.x86_64.rpm
check-mk-raw-2.2.0p1-sles15-38.x86_64.rpm: digests signatures OK
{c-root} zypper install check-mk-raw-2.2.0p1-sles15-38.x86_64.rpm
----


== Abschlusstest

Nach der erfolgreichen Installation von {CMK} und allen Abhängigkeiten steht Ihnen der Befehl `omd` zur Verfügung,
mit dem Sie xref:omd_basics#[Monitoring-Instanzen] anlegen und verwalten können.
Zur Kontrolle können Sie die installierte Version ausgeben lassen:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version 2.2.0p1.cre
----
