// -*- coding: utf-8 -*-
// IGNORE versionen LTSS
include::global_attr.adoc[]
= Release notes
:revdate: 2024-01-23
:title: Release notes - Versionshinweise für {CMK} {v22}
:description: Checkmk 2.2.0 funktioniert mit einer Reihe von Plattformen und Integrationen, die während der aktiven Pflege im Produkt-Lifecycle unterstützt werden.

{related-start}
xref:update_major#[Update auf Version 2.2.0]
xref:update_matrix#[Update-Matrix für Version 2.2.0]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
xref:agent_linux#[Linux überwachen]
xref:agent_windows#[Windows überwachen]
{related-end}


== Einleitung

Dieses Dokument listet die unterstützten Plattformen und Integrationen von {CMK} {v22} auf.
Sofern keine besonderen Gründe vorliegen (z. B. Sicherheit), werden diese Plattformen während der aktiven Pflege im {CMK} {v22} Produkt-Lifecycle einschließlich aller Patch-Versionen unterstützt.


[#os]
== OS für den Server

{CMK} kann auf den folgenden Linux-Server-Betriebssystemdistributionen und -versionen installiert werden, die auf x86_64-Hardware laufen. Dazu geben wir eine Liste der unterstützen Versionen heraus. Einträge können folgende Zusätze enthalten:

* _Deprecated:_ So gekennzeichnete LTS/LTSS Versionen werden noch während des gesamten Lebenszyklus von Version {v22} unterstützt und fallen danach aus dem Support heraus. Bei den Ubuntu STS Versionen endet die Bereitstellung von {CMK} {v22} Paketen bereits xref:update_matrix#ossupport[kurz nach Einstellung der Unterstützung mit Updates] durch Ubuntu.
* _Once released:_ Die Unterstützung für diese Versionen ist geplant. Die Bereitstellung von {CMK} {v22} Paketen erfolgt zeitnah nach Erscheinen der neuen Distributionsversion.

Wir werden auch neue Versionen dieser Distributionen für die Unterstützung evaluieren.
Diese entnehmen Sie bitte der xref:update_matrix#[Update-Matrix].

*Wichtig*: Ab {CMK} {v23} werden STS-Versionen von Ubuntu generell nicht mehr unterstützt.

[cols="33,~",options=header]
|===
|Betriebssystem |Unterstützte Versionen
|*Debian* |10 Buster
| |11 Bullseye
| |12 Bookworm (once released)
|*RedHat Enterprise Linux* |7 (deprecated)
| |8
| |9
|*SUSE Linux Enterprise Server* |12 SP5
| |15 SP1 (deprecated)
| |15 SP2 (deprecated)
| |15 SP3
| |15 SP4
| |15 SP5 (once released)
|*Ubuntu* |20.04 LTS Focal Fossa
| |22.04 LTS Jammy Jellyfish
| |22.10 STS Kinetic Kudu (deprecated)
| |23.04 STS Lunar Lobster (deprecated)
| |23.10 STS Mantic Minotaur (deprecated)
| |24.04 LTS Noble Numbat (once released)
|===


[#browser]
== Browser

Die {CMK}-Benutzeroberfläche ist für die folgenden Desktop-Browser und Mindestversionen geprüft:

* Google Chrome >= 100 unter Windows, Linux und macOS
* Firefox >= 100 unter Windows, Linux und macOS
* Microsoft Edge >= 100 unter Windows
* Safari >= 15.6.1 unter macOS

Die mobile {CMK}-Benutzeroberfläche ist für die folgenden mobilen Browser geprüft:

* Safari unter iOS (aktuelle und letzte Hauptversion des Betriebssystems)
* Google Chrome unter Android (aktuelle und letzte Hauptversion des Betriebssystems)

[#agent]
== OS für den {CMK}-Agenten

Der {CMK}-Agent kann auf den folgenden Betriebssystemen installiert und betrieben werden, wenn grundlegende Anforderungen erfüllt sind.

=== Linux/Unix

Alle Linux- und Unix-Betriebssysteme werden unterstützt, sofern sie mindestens die folgenden technischen Komponenten in der minimalen Version mitbringen:

* Bash >= 4.2
* ksh >= 93
* Perl >= 5.14.0

Zusätzlich muss eine der folgenden Komponenten vorhanden sein:

* systemd >= 219
* xinetd >= alle Versionen

Bitte beachten Sie: Es kann sein, dass Plugins für ihre Funktion zusätzliche Komponenten benötigen.
Python-Plugins erfordern die Version 2.7 oder > 3.5.

=== Windows

Alle folgenden 64-bit-Versionen der Windows Betriebssysteme werden unterstützt:

* 2012
* 2012 R2
* 2016
* 2019
* 2022

Für ältere Systeme stellen wir einen link:https://download.checkmk.com/legacy-agents/[Legacy Agenten^] bereit. Dieser hat ein geringeres Feature-Set und wird nicht offiziell unterstützt.


[#grafana]
== Grafana Plugin

{CMK} {v22} unterstützt die folgenden Grafana Plugin Versionen:

* >= 3.0.0


[#appliance]
== {CMK} Appliance

{CMK} {v22} kann auf den folgenden Versionen der {CMK} Appliance ausgeführt werden:

* >= 1.6.3


[#ldap]
== LDAP-Server

{CMK} {v22} unterstützt die Synchronisierung mit LDAP der folgenden LDAP-Server:

* Microsoft Active Directory
* OpenLDAP
* 389 Directory Server


[#saml]
== SAML IdP

Die SAML-Integration unterstützt die folgenden Identity Provider (IdPs):

* Microsoft Azure Active Directory
* Google Cloud
* Okta

{CMK} arbeitet möglicherweise auch mit anderen SAML-Integrationen zusammen, aber für diese kann keine Unterstützung gegeben werden.


[#ntopng]
== ntopng

Die ntopng-Integration unterstützt die folgenden Versionen von ntopng Professional und Enterprise:

* >= 5.6


[#nagvis]
== Nagvis

Nagvis hängt von PHP ab und benötigt eine Mindestversion, um zu laufen.
Stellen Sie sicher, dass Sie eine passende PHP-Version in Ihrer Installation haben, um Nagvis auszuführen:

* >= 7.2


[#influxdb]
== InfluxDB

{CMK} unterstützt den Export von Daten an die folgenden Versionen der InfluxDB API:

* >= 2.0

