// -*- coding: utf-8 -*-
// IGNORE versionen LTSS
include::global_attr.adoc[]
:current: pass:q[[.new]#2.3.0#]
= Release notes
:revdate: 2024-04-16
:title: Release notes - Versionshinweise für {CMK} {current}
:description: Checkmk 2.3.0 funktioniert mit einer Reihe von Plattformen und Integrationen, die während der aktiven Pflege im Produkt-Lifecycle unterstützt werden.


{related-start}
xref:update_major#[Update auf Version 2.3.0]
xref:update_matrix#[Update-Matrix für Version 2.3.0]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
xref:agent_linux#[Linux überwachen]
xref:agent_windows#[Windows überwachen]
{related-end}


== Einleitung

Dieses Dokument listet die unterstützten Plattformen und Integrationen von {CMK} {current} auf.
Sofern keine besonderen Gründe vorliegen (z. B. Sicherheit), werden diese Plattformen während der aktiven Pflege im {CMK} {current} Produkt-Lifecycle einschließlich aller Patch-Versionen unterstützt.


[#os]
== OS für den Server

{CMK} kann auf den folgenden Linux-Server-Betriebssystemdistributionen und -versionen installiert werden,
die auf x86_64-Hardware laufen.
Dazu geben wir eine Liste der unterstützen Versionen heraus.
Einträge können folgende Zusätze enthalten:

* _Deprecated:_ So gekennzeichnete LTS/LTSS Versionen werden noch während des gesamten Lebenszyklus von Version {current} unterstützt und
fallen danach aus dem Support heraus.
* _Once released:_ Die Unterstützung für diese Versionen ist geplant. Die Bereitstellung von {CMK} {current} Paketen erfolgt zeitnah nach Erscheinen der neuen Distributionsversion.

Wir werden auch neue Versionen dieser Distributionen für die Unterstützung evaluieren.
Diese entnehmen Sie bitte der xref:update_matrix#[Update-Matrix].

[cols="33,~",options=header]
|===
|Betriebssystem |Unterstützte Versionen
|*Debian* |10 Buster (deprecated)
| |11 Bullseye
| |12 Bookworm
|*RedHat Enterprise Linux* |8
| |9
| |10 (once released)
|*SUSE Linux Enterprise Server* |12 SP5 (deprecated)
| |15 SP3
| |15 SP4
| |15 SP5
| |15 SP6 (once released)
|*Ubuntu* |20.04 LTS Focal Fossa (deprecated)
| |22.04 LTS Jammy Jellyfish
| |24.04 LTS Noble Numbat (once released)
|===

Ubuntu STS-Versionen werden ab {CMK} {v23} nicht mehr unterstützt, Nutzer von Ubuntu 23.10 müssen unter {CMK} {v22} xref:release_upgrade#[auf Ubuntu 24.04 aktualisieren], bevor sie zu {CMK} {v23} wechseln können.

[#browser]
== Browser

Die {CMK}-Benutzeroberfläche ist für die folgenden Desktop-Browser und Mindestversionen geprüft:

* Google Chrome >= 121 unter Windows, Linux und macOS
* Firefox >= 122 unter Windows, Linux und macOS
* Microsoft Edge >= 121 unter Windows
* Safari >= 17.2 unter macOS

Die mobile {CMK}-Benutzeroberfläche ist für die folgenden mobilen Browser geprüft:

* Safari unter iPadOS/iPhoneOS (aktuelle und letzte Hauptversion des Betriebssystems)
* Google Chrome unter Android (aktuelle und letzte Hauptversion des Betriebssystems)

[#agent]
== OS für den {CMK}-Agenten

Der {CMK}-Agent kann auf den folgenden Betriebssystemen installiert und betrieben werden, wenn grundlegende Anforderungen erfüllt sind.

=== Linux/Unix

Alle Linux-Distributionen und diverse Unix-Betriebssysteme wie _Solaris_ und _AIX_ werden unterstützt, sofern sie mindestens die folgenden technischen Komponenten in der minimalen Version mitbringen:

* Bash >= 4.2
* ksh >= 93
* Perl >= 5.14.0

Zusätzlich muss eine der folgenden Komponenten vorhanden sein:

* systemd >= 219
* xinetd (keine Mindestversion)

Bitte beachten Sie: Es kann sein, dass Plugins für ihre Funktion zusätzliche Komponenten benötigen.
Python-Plugins erfordern Version 2.7 oder > 3.5.

=== Windows

Alle folgenden 64-bit-Versionen der Windows Betriebssysteme werden unterstützt:

* 2012
* 2012 R2
* 2016
* 2019
* 2022

Für ältere Systeme stellen wir einen link:https://download.checkmk.com/legacy-agents/[Legacy Agenten^] bereit. Dieser hat ein geringeres Feature-Set und wird nicht offiziell unterstützt.


[#grafana]
== Grafana Plugin

{CMK} {current} unterstützt die folgenden Grafana Plugin Versionen:

* >= 3.0.0


[#appliance]
== {CMK} Appliance

{CMK} {current} kann auf den folgenden Versionen der {CMK} Appliance ausgeführt werden:

// MFS: Check back with devs 
* >= 1.6.8


[#ldap]
== LDAP-Server

{CMK} {current} unterstützt die Synchronisierung mit LDAP der folgenden LDAP-Server:

* Microsoft Active Directory
* OpenLDAP
* 389 Directory Server


[#saml]
== SAML IdP

Die SAML-Integration unterstützt die folgenden Identity Provider (IdPs):

* Microsoft Azure Active Directory
* Google Cloud
* Okta

{CMK} arbeitet möglicherweise auch mit anderen SAML-Integrationen zusammen, aber für diese kann keine Unterstützung gegeben werden.


[#ntopng]
== ntopng

Die ntopng-Integration unterstützt die folgenden Versionen von ntopng Professional und Enterprise:

* 5.6 (deprecated)
* >= 6.0


[#nagvis]
== Nagvis

Nagvis hängt von PHP ab und benötigt eine Mindestversion, um zu laufen.
Stellen Sie sicher, dass Sie eine passende PHP-Version in Ihrer Installation haben, um Nagvis auszuführen:

* >= 7.2

Je nach verwendeter Linux-Distribution kann die als Abhängigkeit des {CMK}-Installationspaketes definierte Version höher sein.

[#influxdb]
== InfluxDB

{CMK} unterstützt den Export von Daten an die folgenden Versionen der InfluxDB API:

// MFS: Check back with devs 
* >= 2.0

