// -*- coding: utf-8 -*-
// IGNORE Entwicklungs Kompatibilitäts p1 zeilen
include::global_attr.adoc[]
= Update-Matrix für Version {current-major}
:revdate: draft
:title: Update-Matrix für Version {current-major}
:description: Dieser Artikel zeigt die von {CMK} unterstützten Linux-Distributionsversionen. So können Sie die Reihenfolge ermitteln, um {CMK} auf Ihrem Linux-Server zu aktualisieren.

{related-start}
xref:update#[Updates und Upgrades]
xref:update_major#[Update auf Version {current-major}]
xref:release_upgrade#[Linux-Upgrade auf dem {CMK}-Server]
xref:install_packages#[Grundsätzliches zur Installation von {CMK}]
{related-end}


[#intro]
== Einleitung

Mit jeder Version von {CMK} fallen bislang unterstützte Linux-Versionen weg und neue kommen hinzu.
Dies kann es erforderlich machen, vor einem Update von {CMK} ein oder mehrere xref:release_upgrade#[Upgrades Ihrer Linux-Distribution] vorzunehmen.
Die Grafiken in diesem Artikel helfen Ihnen bei der Ermittlung der geeigneten Reihenfolge.
Studieren Sie diese aufmerksam, bevor Sie im link:https://checkmk.com/download/archive[Download-Archiv^] suchen oder Anfragen nach alten Paketen stellen.
Sollten Sie auf eine ältere {CMK}-Version als {current-major} aktualisieren wollen, lesen Sie diesen Artikel bitte für die {CMK}-Version, die _Ziel_ der Aktualisierung ist.

[#steps]
== Ermittlung der Update-Schritte

Die Aufgabe ist es nun, in der xref:matrix[Kompatibilitäts-Matrix] für Ihre Linux-Distribution tendenziell von links oben nach rechts unten zu gelangen.
Dabei sind die Vorgaben für das xref:update#[Update von {CMK}] zu berücksichtigen:

* Es darf keine Major-Version ausgelassen werden.

* Vor dem Update der Major-Version muss auf die höchste verfügbare Patch-Version aktualisiert werden.
Die Mindestanforderungen sind im xref:update_major#update_patch[Artikel zum Update auf {current-major}] beschrieben.

* Beim Upgrade der Linux-Distribution muss auf der neuen Distributionsversion exakt dieselbe {CMK}-Version installiert werden, die auf der alten vorhanden war.

Auch Linux-Distributoren machen in der Regel eine Vorgabe:

* Upgrades dürfen keine Version auslassen.

Aus diesen Anforderungen ergibt sich, dass Sie sich in der Grafik für Ihre Linux-Distribution nur zeilen- oder spaltenweise bewegen dürfen – jedoch niemals diagonal – und, dass Sprünge nur dann zulässig sind, wenn sie nicht gegen die oben genannten Vorgaben verstoßen.

////
Für ein Update von Debian 9 mit {CMK} {v22}p1 auf Debian 12 mit {CMK} {v23} ergibt sich so die folgende Update-Reihenfolge:

. Unter Debian 9 führen Sie das Update von {CMK} {v22}p1 xref:update#[auf die aktuelle Patch-Version] von {v22} durch.

. Führen Sie das Upgrade von Debian 9 auf 10, 11 und schließlich auf 12 durch, so wie es im Artikel zum xref:release_upgrade#[Linux-Upgrade auf dem {CMK}-Server] beschrieben ist.

. Unter Debian 12 aktualisieren Sie die aktuelle Patch-Version von {CMK} {v22} auf die xref:update_major#[aktuelle Patch-Version von {v23}].
////

[#matrix]
== Kompatibilitäts-Matrix

// Die komplette Kompatibilitäts-Matrix steht erst einige Stunden nach Release von Checkmk {current-major} zur Verfügung.

Die {CMK}-Versionsnummern am oberen Rand der Grafiken in den folgenden Abschnitten zeigen immer diejenigen an, _ab_ der eine Veränderung vorgenommen wurde, also eine Linux-Version neu unterstützt oder nicht mehr unterstützt wird.
Eine Pfeilspitze am Ende eines Balkens bedeutet, dass diese {CMK}-Version im Support ist, also weitere Patch-Versionen folgen werden.
Ein stumpfes Ende kennzeichnet dagegen eine Kombination aus {CMK}-Version und Distributionsversion, die Ihr Support-Ende erreicht hat.
Das kann an einer abgekündigten {CMK}-Version (alle Balken sind stumpf) oder vom Distributor nicht mehr unterstützten Distribution liegen (einzelne Balken gehen mit Pfeilspitze weiter).
Erstellt werden die Grafiken automatisch aus täglich aktualisierten Daten zu den verfügbaren Downloads, das Änderungsdatum dieses Artikels gibt folglich nicht die Aktualität der angezeigten Daten wieder.


[#debian]
=== Debian

Die Support-Zeiträume der Debian-Versionen entnehmen Sie dem link:https://wiki.debian.org/LTS[Debian-Wiki^] oder der Übersicht bei link:https://endoflife.date/debian[endoflife.date.^]

[#matrix_debian]
Aktivieren Sie JavaScript, um an dieser Stelle die Kompatibilitätsmatrix für Debian angezeigt zu bekommen.
Im Entwicklungs-Branch wird hier aufgrund fehlender Versionsdaten nichts angezeigt.


[#redhat]
=== Red Hat Enterprise Linux

Red Hat stellt eine ausführliche Übersicht der link:https://access.redhat.com/support/policy/updates/errata[geplanten Support-Zeiträume^] bereit.
Bei endoflife.date finden Sie Informationen zu binärkompatiblen Distributionen link:https://endoflife.date/almalinux[AlmaLinux^], link:https://endoflife.date/centos[CentOS^], link:https://endoflife.date/oracle-linux[Oracle Linux^] und link:https://endoflife.date/rocky-linux[Rocky Linux^].

[#matrix_redhat]
Aktivieren Sie JavaScript, um an dieser Stelle die Kompatibilitätsmatrix für Red Hat Enterprise Linux angezeigt zu bekommen.
Im Entwicklungs-Branch wird hier aufgrund fehlender Versionsdaten nichts angezeigt.

[#sles]
=== SUSE Linux Enterprise Server

Auf der Seite von SUSE finden Sie die link:https://www.suse.com/lifecycle/#product-suse-linux-enterprise-server[Lifecycle-Übersicht^].
Alternativ steht eine Übersicht bei link:https://endoflife.date/sles[endoflife.date^] zur Verfügung.

[#matrix_sles]
Aktivieren Sie JavaScript, um an dieser Stelle die Kompatibilitätsmatrix für SUSE Linux Enterprise Server angezeigt zu bekommen.
Im Entwicklungs-Branch wird hier aufgrund fehlender Versionsdaten nichts angezeigt.

[#ubuntu]
=== Ubuntu

Beachten Sie, dass STS-Versionen von Ubuntu bereits seit {v23} von {CMK} nicht mehr unterstützt werden.
Wir achten jedoch immer darauf, dass von jeder {CMK}-Version, die für eine STS-Version bereitgestellt wurde, ein Update bis zur nächsten LTS-Version möglich ist.
Seit {v22} schafft die xref:ossupport[OS Support Policy] klare Regeln.

Ubuntu selbst pflegt eine nach noch im Support befindlichen und abgekündigten Versionen sortierte link:https://wiki.ubuntu.com/Releases[Liste^].
Nach Erscheinungsdatum sortiert ist die Liste bei link:https://endoflife.date/ubuntu[endoflife.date.^]

[#matrix_ubuntu]
Aktivieren Sie JavaScript, um an dieser Stelle die Kompatibilitätsmatrix für Ubuntu angezeigt zu bekommen.
Im Entwicklungs-Branch wird hier aufgrund fehlender Versionsdaten nichts angezeigt.

[#ossupport]
== Richtlinie zur Betriebssystemunterstützung (_OS Support Policy_) in {CMK} 

Um einen Ausblick auf die Unterstützung durch künftige {CMK}-Versionen zu ermöglichen und Updates von Distributionen und {CMK} besser planen zu können, hat die {comfull} sich einige Regeln gegeben:

* _Enterprise-Distributionen_ (SLES, Red Hat Enterprise Linux) werden bis 10 Jahre nach deren Erscheinungsdatum oder bis zum offiziellen Support-Ende durch den Distributor unterstützt.
* _Community-Distributionen_ (Debian, Ubuntu) werden bis 5 Jahre nach deren Erscheinungsdatum oder bis zum offiziellen Support-Ende durch den Distributor unterstützt, sofern es sich um LTS-Releases handelt.

In beiden Fällen ist der frühere Zeitpunkt entscheidend.

Wir streben dabei an, jede beim Erscheinen einer neuen {CMK}-Version unterstützte Distributionsversion über den gesamten Produkt-Lifecycle dieser {CMK}-Version zu unterstützen, sofern dem nicht technische Gründe entgegenstehen oder die Zahl der gleichzeitig unterstützten Versionen einer Distribution vier übersteigt.
Ist dies der Fall, behalten wir uns vor, die Distributionsversion mit dem kürzesten Rest-Support nicht mehr zu unterstützen.
Bekanntgegeben wird dies beim Erscheinen einer neuer {CMK}-Version.
// TK: Evtl. in der 2.3.0 hier release_notes verlinken?

// Ubuntu STS-Versionen werden bereits seit {CMK} {v23} gar nicht mehr unterstützt.
// Konkret bedeutet das: Nutzer von {CMK} {v22} unter Ubuntu 23.10 müssen zunächst  noch unter {CMK} {v22} das xref:release_upgrade#[Betriebssystem-Upgrade] auf Ubuntu 24.04 durchführen, bevor sie {CMK} auf {v23} aktualisieren können.
