// -*- coding: utf-8 -*-
// IGNORE
// NONASCII
include::global_attr.adoc[]
= Upgrades
:title: Upgrades
:description: {CMK} erlaubt den Wechsel der Edition zu einer mit größerem oder kleinerem Funktionsumfang. Lesen Sie hier, wie Sie dafür vorgehen.
:experimental:

{related-start}
xref:omd_basics#[Instanzen (Sites) mit omd verwalten]
xref:update#[Updates]
xref:license#[Lizenzen verwalten]
xref:cmc#[Der {CMK} Micro Core]
xref:cmc_migration#[Migration auf den CMC]
{related-end}

[#intro]
== Einleitung

Während Updates zum täglichen Geschäft gehören – Patch-Versionen erscheinen in den ersten Monaten nach Erscheinen einer neuen Major-Version wöchentlich, später monatlich – , sind Upgrades der Edition deutlich seltenere Ereignisse.
Meist gehen sie mit Budgetbewilligungen einher, die entweder überhaupt den Wechsel von {RE} zu einer kommerziellen Edition ermöglichen oder erlauben, künftig den größeren Funktionsumfang von {UE} verglichen mit {SE} wahrzunehmen.

Aber auch der umgekehrte Weg ist manchmal notwendig:
Da kratzt die im Homelab betriebene {UE} am Limit der Service-Zahl im Lizenzstatus _Free_ und erfordert zur kostenlosen Weiternutzung von {CMK} den Wechsel zu {RE}.
Oder das neue Management streicht Budgets zusammen.
Hierfür erlaubt {CMK} auch Downgrades, die natürlich etwas mehr Vor- und Nachbereitung erfordern.

[TIP]
====
Dieser Artikel behandelt das _Upgrade_ der {CMK}-Edition, also den Wechsel zu einer Edition mit größerem Funktionsumfang, beispielsweise von {CRE} auf eine der kommerziellen Editionen oder von {CSE} nach {CUE}.
Das _Update_ der {CMK}-Version sowie die Verwendung des in beiden Fällen benutzten Befehls `omd update` behandelt der separate xref:update#[Artikel zu Updates].
Weitere Informationen zur Instanzverwaltung (wozu auch das Aufräumen nicht mehr benötigter {CMK}-Pakete gehört) finden Sie im xref:omd_basics#[Artikel zu den Grundlagen des `omd`-Werkzeugs].
====
// ES: Hier bitte Downgrades schon mit aufzählen, oder wenigstens durch allgemeinere Formulierung andeuten


[#preparation]
== Vor dem Upgrade

// ES: Angepasst, damit wir weiter unten "Nach dem Upgrade" schreiben können

Editions-Upgrades können mit Updates der {CMK}-Major-Version kombiniert werden, also beispielsweise von {RE} {oldstable-patch} auf {SE} {current}.
Wir empfehlen jedoch, _dieselbe_ {CMK}-Version und dort dasselbe Patchlevel zu verwenden.
In der Praxis bedeutet dies, dass Sie Ihre Instanz auf das letzte verfügbare xref:update#update_major_version[Patch-Release der bisher genutzten Edition aktualisieren] sollten, bevor Sie das Upgrade angehen.
Spätestens dieses Update vor dem Upgrade ist die Möglichkeit, sich mit dem `omd`-Befehl vertraut zu machen. 

Bei einem Upgrade wird der _Lizenzstatus_ zurückgesetzt.
Dies gilt auch, wenn Sie aus organisatorischen Gründen zunächst beispielsweise {SE} mit einer Lizenz für {UE} betrieben haben.
Im Idealfall haben Sie daher die Lizenzinformationen zur Hand, um sie gleich nach dem Upgrade eintragen zu können.


[#execution]
== Durchführung des Upgrades

// ES: Hier muss unbedingt ein Abschnitt hin, der analog zu update#install_new_versions darüber informiert, dass die Ziel-Edition installiert sein muss, bevor wir die Instanz upgraden können. Dort ist die Installation der erste Schritt nach den Vorbereitungen, das fände ich auch hier passend. Möglicherweise hilft es, mit Includes zu arbeiten und den Text neutral zu formulieren. Aber aus meiner Sicht spricht auch nichts dagegen, hier ein paar konkrete Sätze extra für Upgrader zu spendieren, auch wenn es dann teilweise inhaltliche Überschneidungen gibt.

Das eigentliche Upgrade geschieht mit dem `omd`-Befehl:

[{shell}]
----
{c-omd} omd update
----

In der angezeigten Dialogbox macht `omd` keinen Unterschied zwischen Update und Upgrade.
Die im Hintergrund arbeitenden Mechanismen sind dieselben.

// In der XML-Datei wird eine Patch-Version hardkodiert, während in den vorhergehenden und folgenden Befehlsausgaben mit {oldstable-patch} die aktuellste Patch-Version gezeigt wird.
++++
include::update_omd-update-upgrade.xml[]
++++
// ES: Datei ist nicht vorhanden

[#after_upgrade]
== Nach dem Upgrade

Sobald Sie Ihre Instanz wieder starten, arbeitet diese wie gewohnt.
Allerdings ist es sinnvoll, einige Einstellungen vorzunehmen, um vom gestiegenen Funktionsumfang und höherer Performance zu profitieren.
Diese erläutern wir in den folgenden Kapiteln.

[#updateraw]
=== Upgrade {RE} auf eine der kommerziellen Editionen

Dieses Kapitel deckt primär das Upgrade zu {CSE} ab.
Sie können in einem Schritt auch zu {CE} upgraden, beachten Sie in diesem Fall jedoch auch die Hinweise im xref:cee2cce[folgenden Abschnitt].

Da die kommerziellen Editionen etliche zusätzliche Module und Features haben, gibt es nach der Umstellung ein paar Dinge zu beachten.
Der entscheidende Punkt ist, dass beim Anlegen von _neuen_ Instanzen der {RE} bzw. der kommerziellen Editionen _unterschiedliche Standardeinstellungen_ gesetzt werden.


==== Nagios vs. CMC

Da {RE} nur Nagios als Kern unterstützt, ist dieser bei Instanzen voreingestellt, die mit {RE} erstellt wurden.
Diese Einstellung bleibt beim Upgrade auf {SE} erhalten.
Das bedeutet, dass Sie nach einem Upgrade zunächst weiterhin mit Nagios als Kern fahren.
Eine Umstellung auf den CMC erfolgt auf der Befehlszeile mit `omd config` und wird in dem Artikel zur xref:cmc_migration#[Migration auf den CMC] beschrieben.

==== RRD-Format

Die kommerziellen Editionen unterstützen ein alternatives Format für die Speicherung historischer Messdaten, welches deutlich weniger Platten-I/O erzeugt.
Bei neuen Instanzen der kommerziellen Editionen ist dies automatisch voreingestellt.
Instanzen von {RE} werden auch hier beim Upgrade nicht automatisch umgestellt.
Wie das Umstellen geht, beschreibt ein eigener xref:graphing#rrdformat[Abschnitt] im Artikel über Messwerte und Graphen.


==== Weitere Unterschiede

Um vollen Nutzen aus {SE} ziehen zu können, beachten Sie die Übersicht der Unterschiede zwischen {RE} und xref:cse#[{SE}].


[#cee2cce]
=== Upgrade von {SE} auf {CE}

Am Monitoring-Kern und dem Benachrichtigungssystem gibt es keine Unterschiede zwischen {SE} und {CE}.
Je nach Schwerpunkt des Einsatzes werden Sie den größeren Funktionsumfang oft erst beim Hinzufügen neuer Hosts nutzen.
An einigen Stellen ist dennoch die Überprüfung der vorhandenen Einstellungen angeraten.

Eine vollständige Übersicht der zusätzlichen Funktionalität bietet der Artikel zu xref:cce#[{CE-onprem}].


==== Check-Plugins für Cloud-Services

Wenn Sie xref:monitoring_aws#[Amazon Web Services (AWS),] xref:monitoring_azure#[Microsoft Azure] oder xref:monitoring_gcp#[Google Cloud Platform (GCP)] überwachen, sind die {CE} vorbehaltenen Services bestehender Hosts zunächst nicht aktiviert.
Sie können diese in der Regel [.guihint]#XYZ services to monitor# (wobei XYZ für den Namen der Cloud-Plattform steht) aktivieren.
Führen Sie anschließend eine xref:glossar#service_discovery[Service-Erkennung] bei diesen Hosts durch, um die nun verfügbaren Services zu finden.


==== Agent Controller im Push-Modus

Mit der Möglichkeit, Hosts direkt zu überwachen, welche zwar den {CMK}-Server erreichen können, aber nicht von diesem erreichbar sind, fällt in vielen Fällen die Notwendigkeit selbst gestrickter Lösungen mit xref:datasource_programs#[Datenquellprogrammen] weg.
Sie können diese Hosts xref:agent_linux#changepush[auf Push-Modus umstellen] und so direktes Monitoring ermöglichen.


[#editiondistributed]
== Editions-Upgrades in verteilten Umgebungen

Beachten Sie, dass in verteilten Umgebungen immer zuerst das Update der Version durchgeführt werden _muss_, bevor das Upgrade der Edition folgen kann.
Eine andere Reihenfolge oder ein _Crossgrade_ (Update der Version und Upgrade der Edition in einem Schritt) ist nicht vorgesehen.
Als generelles Vorgehen empfehlen wir das Offline-Upgrade, bei dem von einer beliebigen niedrigeren Edition auf eine beliebige höhere Edition gesprungen werden kann.

// Bei zwei häufig nachgefragten Upgrade-Szenarien (xref:cre2cee_distributed[{RE} nach {SE}] und xref:cee2cce_distributed[{SE} nach {CE}]) ist ein Mischbetrieb für einen eingeschränkten Zeitraum möglich.
Bei allen Upgrade-Szenarien außer denen zu {ME} ist ein Mischbetrieb für einen eingeschränkten Zeitraum möglich.


[#offline_distributed]
=== Offline-Upgrade

Da das Mischen von Editionen nur in wenigen Kombinationen möglich ist, empfehlen wir grundsätzlich, das Upgrade der Edition _offline_ durchzuführen.
Gehen Sie dafür wie folgt vor:

. Stoppen Sie alle Instanzen.
. Führen Sie das Upgrade der Zentralinstanz durch.
. Wenn Sie möchten (und eine Fülle von Benachrichtigungen kein Problem darstellt), können Sie die Zentralinstanz sofort wieder starten.
. Nun steht das Upgrade der Remote-Instanzen an. Dieses können Sie parallel durchführen und einzelne Remote-Instanzen nach dem Upgrade sofort wieder starten.

Selbstverständlich können Sie mit dem Start warten, bis alle Instanzen das Upgrade erhalten haben, was die Zahl von Benachrichtigungen etwas reduziert.

[#online_distributed]
=== Online-Upgrade

{CMK} erlaubt den Mischbetrieb einer Zentralinstanz mit größerem Funktionsumfang mit Remote-Instanzen mit kleinerem Funktionsumfang.
Für das Upgrade bedeutet dies, dass die Zentralinstanz das Upgrade _zuerst_ erhält.
Während des Mischbetriebes sollte keine Übertragung der Konfiguration von der Zentralinstanz zu den Remote-Instanzen durchgeführt werden, die noch kein Upgrade erhalten haben.
Daher empfehlen wir, für die Dauer des Mischbetriebes auf der Zentralinstanz via [.guihint]#Setup > General > Read only mode# die Änderung der Konfiguration zu unterbinden.
Theoretisch kann solch ein Mischbetrieb beliebig lange währen – in der Praxis werden jedoch nach einiger Zeit Konfigurationsänderungen notwendig sein, die einen homogenen Editions-Stand erfordern.

Für das Upgrade ergibt sich daraus folgende Reihenfolge:

. Führen Sie das Upgrade der Zentralinstanz durch.
. Geben Sie die Subskriptionsdaten ein und übermitteln Sie diese, wie im Artikel zur xref:license#[Lizenzierung] beschrieben.
Die von allen Remote-Instanzen bereitgestellten Services werden bei der Berechnung der Subskription gleich behandelt,
das heißt, während des Mischbetriebes werden Services von {RE} Remote-Instanzen bereits als {SE} oder {UE} abgerechnet.
. Aktualisieren Sie nach und nach die Remote-Instanzen.
. Falls Sie die Übertragung der Konfiguration nicht global, sondern für jede Remote-Instanz separat deaktiviert haben, können Sie die Übertragung der Konfiguration für jede Remote-Instanz, welche das Upgrade erhalten hat, wieder aktivieren.
. Im verteilten Monitoring ohne xref:glossar#central_setup[zentrales Setup] müssen auch die Remote-Instanzen gleich nach dem Upgrade lizenziert werden.

Nach dem Upgrade aller Instanzen können Sie die spezifischen Features der neuen Edition aktivieren.

////
[#cre2cee_distributed]
=== {RE} nach {SE} (online)

{CMK} erlaubt nur den Mischbetrieb von {SE} als Zentralinstanz mit {RE} oder {CE} als Remote-Instanzen.
Für das Upgrade nach {SE} bedeutet dies, dass die Zentralinstanz das Upgrade _zuerst_ erhält.
Während des Mischbetriebes sollte keine Übertragung der Konfiguration von der Zentralinstanz zu den Remote-Instanzen durchgeführt werden, die noch kein Upgrade erhalten haben.
Daher empfehlen wir, für die Dauer des Mischbetriebes auf der Zentralinstanz via [.guihint]#Setup > General > Read only mode# die Änderung der Konfiguration zu unterbinden.
Theoretisch kann dieser Mischbetrieb von {SE} als Zentralinstanz mit {RE} als Remote-Instanz beliebig lange währen.

Für das Upgrade ergibt sich daraus folgende Reihenfolge:

. Führen Sie das Upgrade der Zentralinstanz auf {SE} durch.
. Geben Sie die Subskriptionsdaten ein und übermitteln Sie diese, wie im Artikel zur xref:license#[Lizenzierung] beschrieben.
Die von allen Remote-Instanzen bereitgestellten Services werden bei der Berechnung der Subskription gleich behandelt,
das heißt, während des Mischbetriebes werden Services von {RE} Remote-Instanzen bereits als {SE} abgerechnet.
. Aktualisieren Sie nach und nach die Remote-Instanzen.
. Falls Sie die Übertragung der Konfiguration nicht global, sondern für jede Remote-Instanz separat deaktiviert haben, können Sie die Übertragung der Konfiguration für jede Remote-Instanz, welche das Upgrade erhalten hat, wieder aktivieren.
. Im verteilten Monitoring ohne xref:glossar#central_setup[zentrales Setup] müssen auch die Remote-Instanzen gleich nach dem Upgrade lizenziert werden.

Nach dem Upgrade aller Instanzen können Sie die spezifischen Features von {SE} aktivieren.
////

.Warum empfehlen wir, während des Upgrades auf die Synchronisation der Konfiguration zu verzichten?
[%collapsible]
====
Tatsächlich verwerfen Remote-Instanzen Einstellungen, mit denen sie „nichts anfangen“ können.
Dadurch geht zwar nichts kaputt, aber es kann einiges durcheinander kommen.
Nehmen wir an, Sie aktivieren eine spezifische Einstellung von {SE} – beispielsweise xref:basics_downtimes#scheduled[regelmäßige Wartungszeiten] –, bevor alle Remote-Instanzen das Upgrade erhalten haben.
In diesem Fall verwerfen {RE}-Instanzen die Einstellung, woraus folgt, dass diese auch nach dem Upgrade nicht zur Verfügung steht.
Erst nach erneuter Änderung der betroffenen Einstellung nach dem Upgrade steht diese zur Verfügung.

Sollte es unvermeidbar sein, während des Upgrades auf die Synchronisation der Konfiguration zu verzichten, prüfen Sie nach dem vollständigen Upgrade die Konsistenz der spezifischen Einstellungen von {SE}.
====

////
[#cee2cce_distributed]
=== {SE} nach {CE} (online)

Wie bereits erwähnt, erlaubt {CMK} nur den Mischbetrieb von {SE} als Zentralinstanz mit {RE} oder {CE} als Remote-Instanzen.
Für das Upgrade nach {CE} bedeutet dies, dass die Zentralinstanz das Update _zuletzt_ erhält.
Das Upgrade der gesamten Umgebung muss in 30 Tagen abgeschlossen sein.
Während des Mischbetriebes kann die Übertragung der Konfiguration von der Zentralinstanz zu den Remote-Instanzen durchgeführt werden.

Daraus resultiert folgende Reihenfolge für das Upgrade:

. Führen Sie das Upgrade der Remote-Instanzen auf {CE} durch.
*Wichtig:* Nur im 30 Tage währenden Lizenzstatus „Trial“ ist der Mischbetrieb mit {SE} als Zentralinstanz möglich.
Hinterlegen Sie also noch keine {CE}-Subskriptionsdaten!
. Hinterlegen Sie in der Zentralinstanz noch unter {SE} die Subskriptionsdaten für {CE}.
. Führen Sie das Upgrade der Zentralinstanz auf {CE} durch.
. Im verteilten Monitoring ohne xref:glossar#central_setup[zentrales Setup] müssen auch die Remote-Instanzen gleich nach dem Upgrade lizenziert werden.

Soll ein Upgrade direkt von {RE} auf {CE} erfolgen, müssen Sie die Zentralinstanz als Zwischenschritt auf {SE} bringen:
Zuerst führen Sie das Upgrade der Zentralinstanz von {RE} nach {SE} durch, es folgt das Upgrade der Remote-Instanzen direkt von {RE} nach {CE}.
Zuletzt führen Sie noch das Upgrade der Zentralinstanz von {SE} nach {CE} durch.
////


[#down2cee]
== Downgrades

// ES: Bitte nicht zuerst den Befehl zeigen und danach erwähnen, dass irgendwas *davor* passieren muss.
// ES: Vorschlag:
////
Auch Downgrades zwischen den Editionen sind vorgesehen.
Ein Downgrade ist eine komplexere und damit zeitaufwendigere Aktion, da einige Funktionen in der Zielversion möglicherweise nicht funktionieren und manuell deaktiviert und durch eine möglicherweise weniger effiziente oder weniger komfortable Alternative ersetzt werden müssen.

Informieren Sie sich im Folgenden unbedingt, was *vor* einem Downgrade zu erledigen ist.

Andere Downgrades als die im Folgenden beschriebenen sind nicht vorgesehen und werden von uns nicht unterstützt, beispielsweise ein Downgrade von {ME}.
Stattdessen empfehlen wir, in einem solchen Fall mit einer frischen Instanz zu beginnen.


[#cce2cee]
=== Downgrade von {CE} nach {SE}

Als Vorbereitung für das Downgrade von {CE} nach {SE} müssen Sie mindestens die folgenden Änderungen vornehmen:

* Stellen Sie Hosts, die im Push-Modus arbeiten, auf xref:agent_linux#changepush[Pull-Modus] um.
Andernfalls empfängt {CMK} von diesen keine Monitoring-Daten und betroffene Hosts werden im Regelfall xref:monitoring_basics#stale[_stale_].

* Konfigurieren Sie die Agentenpakete für Ordner so um, dass keine xref:hosts_autoregister#[Autoregistrierung] mehr vorgenommen wird.
Backen Sie anschließend die Agentenpakete neu.

Ferner stehen nicht mehr alle Cloud-Services und weniger Dashboards zur Verfügung.
Als Folge werden Sie im Anschluss an das Downgrade xref:wato_services#vanished[verschwundene Services] aufräumen müssen.

// MFS: Has been changed for the latest Grafana plug-in, not necessary anymore
// Falls Sie unter {CE} das xref:grafana#[Grafana-Plugin] aus dem „Grafana Store“ genutzt haben, müssen Sie dieses durch ein aus dem Zip-Archiv installiertes ersetzen.

Eine Übersicht der Unterschiede zwischen {CE} und {SE} liefert der Artikel zu xref:cce#[{CE-onprem}].


[#cee2cre]
=== Downgrade von {SE} nach {RE}

Als Vorbereitung für das Downgrade von {SE} nach {RE} müssen Sie mindestens die folgenden Änderungen vornehmen:

* Änderung des RRD-Datenbankformats mit der Regel [.guihint]#Configuration of RRD databases of hosts# auf [.guihint]#Multiple RRDs per host/service#.
Neben leichten Performance-Nachteilen ist hier anzumerken, dass eine Konvertierung nicht vorgesehen ist und demnach historische Monitoring-Daten nicht mehr sichtbar sind.

* Umschalten des Monitoring-Kerns von CMC auf Nagios – von dieser Änderung sind in erster Linie Performance-Nachteile zu erwarten.

Daneben sind nicht mehr alle Dashboards, Graphen-Einstellungen, Benachrichtigungs-Plugins und Spezialagenten verfügbar.
Im xref:cse#[Artikel zu {SE}] können Sie ermitteln, wie viel {SE}-Funktionalität im Falle des Downgrades nach {RE} wegfällt und wo Sie gegebenenfalls weitere Anpassungen vornehmen müssen.


[#editiondistributed_down]
=== Editions-Downgrades in verteilten Umgebungen

Die in den beiden vorherigen Abschnitten vorgestellten Downgrade-Szenarien können auch in verteilten Umgebungen durchgeführt werden.
Beachten Sie, dass in verteilten Umgebungen immer zuerst das Update der Version durchgeführt werden muss, bevor das Downgrade der Edition folgen kann.
Eine andere Reihenfolge oder ein _Crossgrade_ (Update der Version und Downgrade der Edition in einem Schritt) ist nicht vorgesehen.

In keinem Downgrade-Szenario unterstützt {CMK} den Mischbetrieb zwischen unterschiedlichen Editionen.
Aus diesem Grund empfehlen wir dringend, das Downgrade der Edition _offline_ durchzuführen.
Gehen Sie dafür wie folgt vor:

. Stoppen Sie alle Instanzen.
. Nun müssen Sie zuerst das Downgrade der Zentralinstanz xref:execute_downgrade[durchführen].
. Wenn Sie möchten (und eine Fülle von Benachrichtigungen kein Problem darstellt), können Sie die Zentralinstanz sofort wieder starten.
. Nun steht das Downgrade der Remote-Instanzen an.
Dieses können Sie parallel durchführen und Remote-Instanzen nach dem Downgrade sofort wieder starten.

Selbstverständlich können Sie mit dem Start warten, bis alle Instanzen das Downgrade erhalten haben, was die Zahl von Benachrichtigungen etwas reduziert.

[#execute_downgrade]
=== Downgrade starten

Das eigentliche Downgrade *muss* -- genau wie beim Update oder Upgrade -- mit dem Befehl `omd update` durchgeführt werden.
Die Details dazu finden Sie im Abschnitt xref:update#execute[Durchführen des Updates].

Wenn Sie nun beispielsweise von der {CE} auf die {SE} downgraden wollen, überzeugt sich {CMK}, ob das tatsächlich Ihre Intention ist:

++++
include::update_downgrade_ce_se.xml[]
++++

Sobald Sie diese Abfrage mit [.guihint]#yes# bestätigen, geht das Downgrade unmittelbar los.



////

Auch Downgrades zwischen den Editionen sind vorgesehen.
Ein Downgrade ist eine komplexere und damit zeitaufwendigere Aktion, da einige Funktionen in der Zielversion möglicherweise nicht funktionieren und manuell deaktiviert und durch eine möglicherweise weniger effiziente oder weniger komfortable Alternative ersetzt werden müssen.

Das eigentliche Downgrade *muss* -- genau wie beim Update oder Upgrade -- mit dem Befehl `omd update` durchgeführt werden.
Die Details dazu finden Sie im Abschnitt xref:update#execute[Durchführen des Updates].

Wenn Sie nun beispielsweise von der {CE} auf die {SE} downgraden wollen, überzeugt sich {CMK}, ob das tatsächlich Ihre Intention ist:

++++
include::update_downgrade_ce_se.xml[]
++++

Sobald Sie diese Abfrage mit [.guihint]#yes# bestätigen, geht das Downgrade unmittelbar los.
Informieren Sie sich im Folgenden unbedingt, was *vor* diesem Downgrade zu erledigen ist.

Andere Downgrades als die im Folgenden beschriebenen sind nicht vorgesehen und werden von uns nicht unterstützt, beispielsweise ein Downgrade von {ME}.
Stattdessen empfehlen wir, in einem solchen Fall mit einer frischen Instanz zu beginnen.


[#cce2cee]
=== Downgrade von {CE} nach {SE}

Als Vorbereitung für das Downgrade von {CE} nach {SE} müssen Sie mindestens die folgenden Änderungen vornehmen:

* Stellen Sie Hosts, die im Push-Modus arbeiten, auf xref:agent_linux#changepush[Pull-Modus] um.
Andernfalls empfängt {CMK} von diesen keine Monitoring-Daten und betroffene Hosts werden im Regelfall xref:monitoring_basics#stale[_stale_].

* Konfigurieren Sie die Agentenpakete für Ordner so um, dass keine xref:hosts_autoregister#[Autoregistrierung] mehr vorgenommen wird.
Backen Sie anschließend die Agentenpakete neu.

Ferner stehen nicht mehr alle Cloud-Services und weniger Dashboards zur Verfügung.
Als Folge werden Sie xref:wato_services#vanished[verschwundene Services] aufräumen müssen.

// MFS: Has been changed for the latest Grafana plug-in, not necessary anymore
// Falls Sie unter {CE} das xref:grafana#[Grafana-Plugin] aus dem „Grafana Store“ genutzt haben, müssen Sie dieses durch ein aus dem Zip-Archiv installiertes ersetzen.

Eine Übersicht der Unterschiede zwischen {CE} und {SE} liefert der Artikel zu xref:cce#[{CE-onprem}].


[#cee2cre]
=== Downgrade von {SE} nach {RE}

Als Vorbereitung für das Downgrade von {SE} nach {RE} müssen Sie mindestens die folgenden Änderungen vornehmen:

* Änderung des RRD-Datenbankformats mit der Regel [.guihint]#Configuration of RRD databases of hosts# auf [.guihint]#Multiple RRDs per host/service#.
Neben leichten Performance-Nachteilen ist hier anzumerken, dass eine Konvertierung nicht vorgesehen ist und demnach historische Monitoring-Daten nicht mehr sichtbar sind.

* Umschalten des Monitoring-Kerns von CMC auf Nagios – von dieser Änderung sind in erster Linie Performance-Nachteile zu erwarten.

Daneben sind nicht mehr alle Dashboards, Graphen-Einstellungen, Benachrichtigungs-Plugins und Spezialagenten verfügbar.
Im xref:cse#[Artikel zu {SE}] können Sie ermitteln, wie viel {SE}-Funktionalität im Falle des Downgrades nach {RE} wegfällt und wo Sie gegebenenfalls weitere Anpassungen vornehmen müssen.


[#editiondistributed_down]
=== Editions-Downgrades in verteilten Umgebungen

Die in den beiden vorherigen Abschnitten vorgestellten Downgrade-Szenarien können auch in verteilten Umgebungen durchgeführt werden.
Beachten Sie, dass in verteilten Umgebungen immer zuerst das Update der Version durchgeführt werden muss, bevor das Downgrade der Edition folgen kann.
Eine andere Reihenfolge oder ein _Crossgrade_ (Update der Version und Downgrade der Edition in einem Schritt) ist nicht vorgesehen.

In keinem Downgrade-Szenario unterstützt {CMK} den Mischbetrieb zwischen unterschiedlichen Editionen.
Aus diesem Grund empfehlen wir dringend, das Downgrade der Edition _offline_ durchzuführen.
Gehen Sie dafür wie folgt vor:

. Stoppen Sie alle Instanzen.
. Führen Sie das Downgrade der Zentralinstanz durch.
. Wenn Sie möchten (und eine Fülle von Benachrichtigungen kein Problem darstellt), können Sie die Zentralinstanz sofort wieder starten.
. Nun steht das Downgrade der Remote-Instanzen an.
Dieses können Sie parallel durchführen und Remote-Instanzen nach dem Downgrade sofort wieder starten.

Selbstverständlich können Sie mit dem Start warten, bis alle Instanzen das Downgrade erhalten haben, was die Zahl von Benachrichtigungen etwas reduziert.
