// -*- coding: utf-8 -*-
// IGNORE %
include::global_attr.adoc[]
= {CE} (SaaS)
:revdate: 07-Jan-2025
:title: {CE} (SaaS)
:description: Here you can find out what distinguishes {CE} (SaaS), especially in comparison to its {CE} (Self-hosted) sister.

{related-start}
xref:intro_setup#[Getting {CE}]
{related-end}


[#intro]
== Introduction

{CE} (SaaS) provides you with {CMK} as _Software as a Service (SaaS)_ in the cloud.
The SaaS platform from {CMK} is designed and optimized for small to medium-sized, hybrid IT infrastructures, i.e. for monitoring services in the cloud and on-premises.

By using a _hosted_ {CMK} instead of doing it yourself, you will not need to worry about installing and updating a {CMK} server.
Providing {CMK} in the cloud enables low-maintenance operation and high availability.
{CE} (SaaS) is hosted on Amazon Web Services (AWS) in Europe and North America.

To help you to set up your infrastructure quickly, {CE} (SaaS) provides you with an onboarding guide and preconfigured agent packages, which with only a few minutes work enable you to create your hosts with standard settings and add these to your monitoring.
You can therefore concentrate on IT monitoring right away -- and not on operating {CMK}.

In this article you will learn what {CE} (SaaS) has to offer -- compared to its sister {CE} (Self-hosted).


[#editions]
== Overview of {CE} (SaaS)

{CE} is available in two variants: as {CE} (SaaS) and {CE} (Self-hosted).
{CE} (Self-hosted) is one of the _on-premises_ editions of {CMK}, all of which require you to set up your own {CMK} server.
The {CE} (SaaS) differs in that the {CMK} server is already running in the cloud and is just waiting to be used by you.

The {CE} (SaaS) software is based on that of {CE} (Self-hosted).
Thus, in principle, both offer close to the same range of functions.
An overview of the functions of link:https://docs.checkmk.com/master/en/cce.html[{CE} (Self-hosted)^] can be found in the {CMK} User Guide.

The 'in principle' in the previous paragraph indicates that there are actually some differences between the two cloud siblings.
These result from the technical requirements to be met for providing the software in the cloud and the implementation of security guidelines, but also the prioritization of functions into those that are absolutely necessary for the first release of {CE} (SaaS) and those that can wait for the next release.
These differences are described in detail in the following chapters.

[TIP]
====
Whenever there is no possibility of confusion with {CE} (Self-hosted) -- as in the other articles in this {CE} User Guide -- we simply call {CE} (SaaS) the {CE}.
====


[#functions_new]
== Additional functions

The following table shows the main functions provided by {CE} (SaaS) in addition to those offered by {CE} (Self-hosted):

[cols="25,~,~",options="header"]
|===
|Function
|Status
|Additional information

|Onboarding guide 
|With the green [.guihint]#Getting started# button on the right side of the user interface you have direct access to helpful information in the xref:intro_setup#onboarding_guide[onboarding guide]. |

|Admin panel
|The xref:admin_panel#[admin panel] is the central point for managing {CE} (SaaS), e.g. users and {CMK}-xref:glossar#site[sites]. | 

|{CMK} agent
|{CE} (SaaS) is delivered with preconfigured agent packages for the automatic registration of the agent and the creation of its associated xref:glossar#host[host].
|The xref:intro_setup_monitor#first[Beginner's Guide] shows how a new host can be added to the monitoring with one of these agent packages.

|Update
|The operating system, the underlying infrastructure and the {CE} (SaaS) software are kept up to date. |

|Backup
|Backups are performed automatically for each site on a regular basis -- at least daily. |

|Availability
|An availability of 99.5 % is guaranteed for {CE} (SaaS). | 

|===


[#functions_different]
== Functions implemented differently

The following table shows the main functions of {CE} (SaaS) that are implemented differently compared to {CE} (Self-hosted):

[cols="25,~,~",options="header"]
|===
|Function
|Status
|Additional information

|Site management
|Sites are not managed using the `omd` command, but instead via the admin panel.
|Access to the site via the command line is disabled for security reasons.

|Backup and restore
|Backups are not created and managed via the {CMK} interface, but rather in the admin panel's site management. | 

|User management
|The basic user management -- i.e. the creation and deletion of users as well as the assignment of one of two available roles -- is not carried out via the {CMK} interface, it is instead done in the admin panel.
The definition of user-defined roles and the granular assignment of permissions is currently not possible.
|For user management, {CE} (SaaS) uses Amazon Cognito as the identity provider (IdP).

|License management
|Licenses are not managed via the {CMK} interface, but rather via the admin panel. |

|{CMK} agent
|The agent only works in xref:glossar#push_mode[push mode], not in xref:glossar#pull_mode[pull mode].
|Push mode is the default in a cloud environment.

|Notifications
|The notification methods `SMS (using smstools)`, `Spectrum Server` and `Forward notifications to Event Console` are not available.
|Only the notification methods that can be addressed from a cloud environment are provided.

|REST API, rules, global settings
|REST API endpoints, rules and global settings for differently implemented and unavailable functions are adapted to the actually existing range of functions.
|Examples: Site management, user management, roles, Event Console.

|===


[#functions_restrictions]
== Restrictions

The following table shows the main functions of {CE} (Self-hosted) that are not available in {CE} (SaaS):

[cols="25,~,~",options="header"]
|===
|Function
|Status
|Additional information

.2+|{CMK} agent
|It is not possible to monitor operating systems with a {CMK} agent _without_ an Agent Controller.
This applies to the monitoring of Solaris, AIX, FreeBSD and Linux in legacy mode.
|The push mode requires a {CMK} agent with an Agent Controller.
The Agent Controller is only available in the Linux and Windows agents. +
|Real-time checks cannot be executed.
|Deactivated for performance reasons.

|SNMP
|Monitoring via SNMP is currently not supported.
SNMP-based checks are not available.
There are no SNMP parameters in the host properties.
|SNMP data cannot be transferred in push mode and not sufficiently encrypted to a {CMK} site in the cloud.

|Site management
|Currently only one site can be created.
|Increased load due to a large number of services is compensated by increasing CPU performance and RAM.

|Distributed monitoring
|Currently not supported. |

|User management
|Two-factor authentication is currently not supported. |

|SAML, LDAP 
|The connection of external IdPs with Secure Assertion Markup Language (SAML) and LDAP-based connections is currently not supported. |

|Command line
|There is no access to the site via the command line.
It is therefore not possible to use the Livestatus interface.
|Disabled for security reasons.

|Site directory
|There is no access to the subdirectories and files contained in the site directory.
This also means that it is not possible to customize and extend the functionality provided by {CMK} in the local part of the site directory structure. +
No files can be stored in the site directory.
This applies, for example, to Checkmk extension packages (MKP) including MKPs for GUI extensions, NagVis, custom icon files, custom notes, self-written datasource programs and check plug-ins.
|Disabled for security reasons.

|Event Console
|Currently not available.
|Disabled to avoid (inbound) ingress traffic generated by messages.

|Alert handler
|Not available.
|Disabled for security reasons.

|{CMK} Synthetic Monitoring with Robotmk
|Not available.
|Disabled to avoid inbound traffic from log files, screenshots etc. +

|ntopng, Grafana
|These integrations are not available.
|Disabled Grafana to avoid outbound traffic.

|InfluxDB, Graphite
|Currently no connection to these external metrics databases.
|Disabled to avoid outbound traffic.

|===

