// -*- coding: utf-8 -*-
// IGNORE
// NONASCII
include::global_attr.adoc[]
= The AI system _Explain with AI_
:title: The AI system Explain with AI
:description: The AI system _Explain with AI_  is an AI-powered analysis feature, that help you better understand your cloud infrastructure monitoring.

{related-start}
xref:user_interface#[The user interface]
{related-end}


[#intro]
== Introduction

In {CE}, the built-in AI system [.guihint]#Explain with AI# allows you to obtain additional information about hosts and services.
This AI-powered analysis feature helps you get to the root of issues in your cloud infrastructure and provides you with general knowledge on how to use {CE}.


=== Technical basis

This AI system is based on a Large Language Model (LLM).
The exact version and generation of the LLM used is displayed in the [.guihint]#Explain with AI# function in the {CE} user interface.
The LLM is connected to {CE} via a secure application programming interface (API).

The current version of the associated _Data Manifest_ is available at any time at link:https://checkmk.com/explain-with-ai/manifest[https://checkmk.com/explain-with-ai/manifest].


=== Objective

This AI system [.guihint]#Explain with AI# focuses on the following goals:

* To provide an easy-to-understand overview of the status of your hosts and services
* To give a helping hand for newcomers to Checkmk
* To create a summary of incidents for non-technical users


=== Overview of the feature

The AI-powered analysis feature [.guihint]#Explain with AI# requires no manual user input.
This AI system specifically extracts technical metadata (e.g., log entries, alert metadata) directly from your {CE} environment.


=== Restriction of use

This AI system is designed exclusively for the analysis and interpretation of monitoring data (e.g., by assisting with the creation of dashboards, explaining alerts, summarizing logs, or identifying relevant user manuals).
The use of this AI system for direct intervention in critical processes or the autonomous control of critical infrastructure is prohibited, as the system is not certified for these high-risk applications. 


[IMPORTANT]
====
*{Checkmk} AI feature usage notice*

The [.guihint]#Explain with AI# feature uses a large language model (LLM) to generate content.
Generated content (output) may contain errors or inaccuracies.
Ensure all output generated is carefully reviewed and checked by a human for factual correctness before being used in any way.
For further information visit our link:https://checkmk.com/privacy-policy[Privacy Policy^].
====


== Using _Explain with AI_

In every [.guihint]#Services of host# view, you will find the following icon in the [.guihints]#Icons# column: icon:icon_sparkle[alt=“Icon for the AI system _Explain with AI_.”]

As soon as you click this icon, [.guihint]#Explain with AI# will launch.
You will also find a button for [.guihint]#Explain with AI# in the action bar of every view that displays a single service.

After clickingthis, [.guihint]#Explain with AI# appears on the right side of the screen in a slideout.

When you open the AI system [.guihint]#Explain with AI# for the first time, you must first confirm that you have read and accept the “{CMK} AI feature usage notice.”
Once you have done this, an explanation of the current status of the respective service will be generated immediately.
At the top, you will see a list of the contextual information that was passed to the AI system [.guihint]#Explain with AI#.

After a few seconds, you will receive the requested information.
You can use this information to try to resolve the cause of an undesirable condition.
The AI system [.guihint]#Explain with AI# itself will not make any changes to monitoring or configuration.