#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2021 Mattias Schlenker <ms@mattiasschlenker.de> for tribe29 GmbH
# License: GNU General Public License v2
#
# Reference for details:
# https://docs.checkmk.com/latest/en/devel_check_plugins.html
#
#
# This is the agent/client side script for a "Hello World!" Plugin for CheckMK 2.0
#
# /usr/lib/check_mk_agent/plugins/helloworld.py

from random import random

# The section should just use 7bit lowercase characters and underscores. They must 
# match the name set in register.check_plugin(). Make sure to choose a unique name
# to avoid having two plugins with the same name.

print("<<<hello_world>>>")

# Just print a (fairly) random number between 0.0 and 100.0, interpreted as
# percentage. The output will be space separated which will be split into tokens
# as CheckMK receives the output. 
#
# hello_world 98.41417513129443

print("hello_world", random() * 100.0) 

