// -*- coding: utf-8 -*-
// IGNORE Proxmox VMware
include::global_attr.adoc[]
= Quick start guide for {CMK} virt1
:revdate: 2023-02-07
:title: Quick start guide for {CMK} virt1
:description: Quick start guide for the {CMK} virtual appliance setup.

{related-start}
xref:appliance_usage#[Configuring and using the appliance]
xref:install_appliance_cmk#[Installation of {CMK} in the appliance]
xref:appliance_rack1_quick_start#[Quick start guide for {CMK} racks]
{related-end}


This quick start guide takes you from setting up the appliance using a minimal configuration, to the login screen of a functioning {CMK} site.

For more detailed information and instructions, see the xref:appliance_usage#[main appliance article].


== Setting up the appliance (Console)

. Download the {CMK} virt1 as an OVA (Open Virtualization Appliance) file from our link:https://checkmk.com/download[download page^] and import this file into your hypervisor, optionally VirtualBox, Proxmox or VMware ESXi (for better performance you should change the network card to VMXNET 3 when importing into ESXi). 
xref:appliance_install_virt1#[More ...]

. Start the imported virtual machine.
You will land in a text-based configuration environment (called the console) where you can perform the basic configuration of the appliance.

. During initialization, at the first boot you will be prompted to partition the disk.
xref:appliance_usage#init_start[More ...] +
If you agree, confirm the prompt. 

. After partitioning you will see the console status view, the home screen on all subsequent startups.

. In order to use the appliance for monitoring, you must now make some settings. 
Press the `F1` key to call up the configuration menu and edit at least the following settings:

.. [.guihint]#Network Configuration:# IP address, net mask and optionally the default gateway.
xref:appliance_usage#network_config[More ...]

.. [.guihint]#Device Password:# Password to *activate* the appliance web interface.
xref:appliance_usage#network_access[More ...]

. Now start the appliance web interface on any computer in the network via the IP address assigned above using `\http://&lt;ipaddress&gt;/`.
Log in with the defined password.
A user name is not required.


== Setting up monitoring (Web GUI)

. Download the {CMK} software package for the appliance from our link:https://checkmk.com/download[download page^].

. In the appliance web interface, navigate to [.guihint]#Check_MK Versions# and install the {CMK} package via the [.guihint]#Upload & Install# button.
xref:appliance_usage#manage_cmk[More ...]

. Now navigate to [.guihint]#Site Management# and create a {CMK} site with [.guihint]#Create New Site#.
xref:appliance_usage#create_site[More ...] +
Enter at least the following values:

.. [.guihint]#Unique site ID:# Name of the site
.. [.guihint]#Version:# Version of {CMK}
.. [.guihint]#Login for the administrator:# Admin user name
.. [.guihint]#Password for the administrator:# Admin password

. Now you can log in to the {CMK} site -- simply append the site's name to the URL as shown above: `\http://&lt;ipaddress&gt;/&lt;siteid&gt;/`

{CMK} is now ready for you!
Find out how to proceed from this point in the xref:intro_gui#[The Checkmk user interface] article.

For a production system, you should of course make further settings, for example for name resolutions, communication via email, encryption, etc.
Everything else you could need can be found in the xref:appliance_usage#[main appliance article].
