// -*- coding: utf-8 -*-
// IGNORE LAN1
// SKIPCOMMITS 2025-09-19
include::global_attr.adoc[]
= Quick start guide for {CMK} racks
:revdate: 2023-11-06
:title: Quick start guide for {CMK} racks
:description: Setting up the physical {CMK} Appliance involves a series of steps. Read here how to prepare your physical appliance for use.
:experimental:

{related-start}
xref:appliance_usage#[Configuring and using the appliance]
xref:install_appliance_cmk#[Installation of {CMK} in the appliance]
xref:appliance_virt1_quick_start#[Quick start guide for {CMK} virt1 ]
{related-end}

This quick start guide takes you from setting up the appliance using a minimal configuration, to the login screen of a functioning {CMK} site.

For more detailed information and instructions, see the xref:appliance_usage#[main appliance article].

[IMPORTANT]
====
Please take note that, ex-factory, the management interface supplied with all Checkmk racks is *initially deactivated* and needs to be xref:appliance_rack_config#ipmi[enabled manually in the web interface].
You must take this into consideration *before* delivering a rack to a remote location, for example. xref:appliance_rack_config#ipmi[More ...]
====


== Setting up the appliance (Console)

. Connect the device. For commissioning, as a minimum you will need: a monitor (VGA), a USB keyboard, a network connection (port: LAN1) and a power supply (preferably both ports).

. During initialization, at the first boot you will be prompted to initialize the RAID, which will of course erase all existing data on the disks.
xref:appliance_usage#init_start[More ...]. +
If you agree, confirm the prompt.

. After initialization you will see the console status view, the home screen on all subsequent startups.

. In order to use the appliance for monitoring, you must now make some settings. 
Press the kbd:[F1] key to enter the configuration menu and edit at least the following settings:

.. [.guihint]#Network Configuration:# IP address, net mask, and optionally the default gateway.
xref:appliance_usage#network_config[More ...]

.. [.guihint]#Device Password:# Password to *activate* the appliance web interface.
xref:appliance_usage#network_access[More ...]

. Now start the appliance web interface on any computer in the network via the IP address assigned above using `\http://&lt;ipaddress&gt;/`.
Log in with the defined password.
A username is not required.

. Finally -- optionally, but strongly recommended -- connect the management interface via a separate network. xref:appliance_rack_config#ipmi[More ...]


== Setting up monitoring (Web GUI)

. Download the {CMK} software package for the appliance from our link:https://checkmk.com/download[download page^].

. In the appliance web interface, navigate to [.guihint]#Check_MK Versions# and install the {CMK} package via the [.guihint]#Upload & Install# button.
xref:appliance_usage#manage_cmk[More ...]

. Now navigate to [.guihint]#Site Management# and create a {CMK} site with [.guihint]#Create New Site#.
xref:appliance_usage#create_site[More ...] +
Enter at least the following values:

.. [.guihint]#Unique site ID:# Name of the site
.. [.guihint]#Version:# Version of {CMK}
.. [.guihint]#Login for the administrator:# Admin username
.. [.guihint]#Password for the administrator:# Admin password

. Now you can log in to the {CMK} site -- simply append the site's name to the URL as shown above: `\http://&lt;ipaddress&gt;/&lt;siteid&gt;/`

{CMK} is now ready for you!
Find out how to proceed from this point in the xref:intro_gui#[The Checkmk user interface] article.

For a production system, you should of course make further settings, for example for name resolutions, communication via email, encryption, etc.
Everything else you could need can be found in the xref:appliance_usage#[main appliance article].
