// -*- coding: utf-8 -*-
// IGNORE
include::global_attr.adoc[]
= {CE}
:revdate: 2024-06-06
:title: Checkmk Cloud
:description: What makes Checkmk Cloud special, especially in comparison to the other {CMK} editions, can be found here.

{related-start}
xref:cse#[{SE}]
xref:managed#[{ME}]
xref:intro_setup#[Setting up {CMK}]
xref:update#[Updates and Upgrades]
{related-end}


[#intro]
== Introduction

There is no perfect software solution for every user and every application.
What works for one person may be too much or too little, too simple or too complex for another.
That is why {CMK} is available in a number of different editions.
These differ above all in their range of features and suitability for specific areas of application.
In the following short article we would like to introduce {CCE}, one of the commercial xref:intro_setup#editions[editions].


[#editions]
== Overview of {CE}

In terms of content, {CE} is based on xref:cse#[{CSE}], but it additionally provides extensive cloud functions.
This makes {CE} particularly valuable for users whose hosts are located in a cloud and who also want to set up their entire monitoring in a cloud.

Support when moving applications and processes to the cloud, i.e. in so-called _lift and shift_ scenarios, has already been integrated into all {CMK} editions 
-- which simplifies the implementation of a monitoring of Amazon Web Services (AWS), Microsoft Azure and the Google Cloud Platform (GCP).
In addition, {CE} also provides cloud-specific xref:glossar#check_plugin[check plug-ins].
In this way you can continue to use {SE} when transitioning from a data center to a cloud.
If you would subsequently also like to use the SaaS and PaaS products that a cloud can additionally provide, you can upgrade to {CE}.


[#functions]
== Additional functions with {CE}

The key features of {CE} that differentiate it from other editions:

* {CE} is available through the xref:install_azure#[Microsoft Azure] and xref:install_aws#[AWS] marketplaces.

* Advanced check plug-ins: +
{CE} includes additional cloud-specific check plug-ins for monitoring xref:monitoring_aws#[Amazon Web Services (AWS)], xref:monitoring_azure#[Microsoft Azure] and the xref:monitoring_gcp#[Google Cloud Platform (GCP)].

* Cloud-specific dashboards: +
In {CE}, there are specific dashboards for AWS, Microsoft Azure and GCP.

* Configuration of a push agent: +
In all {CMK} editions, the {CMK} server initiates communication with a host and requests the data from the {CMK} agent -- in the so-called xref:glossar.html#pull_mode[pull mode].
With {CE} you can additionally use the xref:glossar.html#push_mode[push mode].
You configure the push mode in the properties of a host, in the section on xref:hosts_setup#monitoring_agents[monitoring agents].

* Auto-registration of hosts: +
In {CE}, you can have xref:hosts_autoregister#[hosts created automatically] that have a {CMK} agent installed.
This includes registering the agent with the {CMK} server, establishing a TLS-encrypted connection, creating the host, performing a service discovery and activating the changes,
so that the host is added to the monitoring environment -- all fully automatically.
Auto-registration works for pull and push agents.

*Note:* In the {CMK} user interface, elements that only exist in {CE} are indicated by the [.guihint]#(Cloud Edition)# suffix, e.g. rules, dashboards or parameter values.


[#upgrade]
== Upgrading to {CE}

You can test {CE} without obligation, because it is not limited in the first 30 days.
By entering a license key after 30 days at the latest, you can then use {CE} without limitations.

To upgrade from one of the other editions to {CE}, follow the xref:update#upgrade[upgrade description].


[#details]
== Differences of the components in detail

[#ui]
=== The monitoring interface

[cols="20,~",options="header"]
|===
|Function |Description

|Cloud dashboards |In the Checkmk Cloud Edition, there are dedicated dashboards for xref:monitoring_aws#dashboards[AWS,] xref:monitoring_azure#dashboards[Azure] and xref:monitoring_gcp#dashboards[GCP].
|===


[#agents]
=== The monitoring agents

[cols="20,~",options="header"]
|===
|Function |Description

|Push mode |Only in {CE} the xref:wato_monitoringagents#agents[{CMK} agent] for Linux and for Windows can be configured and used in xref:glossar#push_mode[push mode].
You configure the mode (push or xref:glossar#pull_mode[pull]) in the xref:hosts_setup#monitoring_agents[Monitoring agents] section in the  host or folder properties.
Push mode relies on the Agent Controller and is therefore not available in the agent's legacy mode.

|Auto-registration |{CE} provides the ability to create hosts automatically during registration with the so-called xref:hosts_autoregister#[auto-registration].
The xref:hosts_autoregister#rule_autoregister_site[[.guihint]#Agent registration#] rule set is used to configure the {CMK} site.
The auto-registration also requires the Agent Controller.

|Agent Bakery |In {CE} you can additionally use the Agent Bakery to provide agent packages with a configuration for auto-registration.
The rule for the Agent Bakery is named xref:hosts_autoregister.html#rule_autoregister_bakery[[.guihint]#Agent controller auto-registration (Cloud Edition)#].
These packages perform registration automatically after installation.

|Agent registration permissions | In {CE} the xref:wato_user#predefined_roles[predefined role] `agent_registration` contains additional permissions for creating hosts automatically.
|===


[#connectors]
=== Connectors

[cols="20,~",options="header"]
|===
|Function |Description
|Grafana |You can install the xref:grafana#[Grafana plug-in] directly from the link:https://grafana.com/grafana/plugins/checkmk-cloud-datasource[Grafana catalog], making it easy to embed the integration into your cloud environment.
|===


[#provision]
=== Deployment

[cols="20,~",options="header"]
|===
|Feature |Description

|Availability in the Azure and AWS Marketplaces |{CE} is available for installation in the marketplaces of link:https://azuremarketplace.microsoft.com/en-us/marketplace/apps/tribe29gmbh1665582614827.checkmk003?tab=Overview[Microsoft Azure^] and link:https://aws.amazon.com/marketplace/pp/prodview-gddkal2hfn7yo[AWS^].
The xref:install_azure#[Azure] and xref:install_aws#[AWS] articles will guide you through the image setup.

|Testing the Edition |With the available xref:intro_setup#editions[commercial editions], i.e. {SE}, {CE} and {ME}, you can test {CE} in full functionality for 30 days without obligation.
On a small scale, i.e. with one site and up to 750 services, you can also run {CMK} with {CE} on a permanent basis without requiring a subscription.
|===


[#other]
=== Additional functions

[cols="20,~",options="header"]
|===
|Function |Description

|Check plug-ins for AWS |In {CE} there are additional check plug-ins for the AWS Cloud products
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_lambda[AWS Lambda^],
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_ecs[Elastic Container Service (ECS)^],
link:https://checkmk.com/integrations/aws_route53[Route 53^],
link:https://checkmk.com/integrations/aws_cloudfront[CloudFront^],
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=elasticache[ElastiCache for Redis^] and
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_sns[Simple Notification Service (SNS)^].

|Check plug-ins for Azure |In {CE} there are additional check plug-ins for the Azure products
link:https://checkmk.com/integrations/azure_app_gateway[Application Gateway^] and 
link:https://checkmk.com/integrations/azure_vault_backup_containers[Recovery Services vaults^].

|Check plug-ins for GCP |In {CE} there are additional check plug-ins for the Google Cloud products
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_function[Cloud Functions^],
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_run[Cloud Run^] and
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_redis[Memorystore for Redis^].
|===
