// -*- coding: utf-8 -*-
// IGNORE
include::global_attr.adoc[]
= {CE} (Self-hosted)
:revdate: 2025-05-19
:title: Checkmk Cloud (Self-hosted)
:description: {CE} (Self-hosted), in comparison with other editions, offers additional extensive cloud-specific functions. An overview is given here.         

{related-start}
xref:cse#[{SE}]
xref:managed#[{ME}]
xref:intro_setup#[Setting up {CMK}]
xref:update#[Updates and Upgrades]
{related-end}


[#intro]
== Introduction

There is no perfect software solution for every user and every application.
What works for one person may be too much or too little, too simple or too complex for another.
That is why {CMK} is available in a number of different editions.
These differ above all in their range of features and suitability for specific areas of application.
In the following short article we would like to introduce {CCE} (Self-hosted), one of the commercial xref:glossar#edition[editions].


[#editions]
== Overview of {CE} (Self-hosted)

{CE} is available in two variants: as {CE} (SaaS) and {CE} (Self-hosted).
While {CE} (Self-hosted) is one of the _on-premises_ editions of {CMK}, all of which require you to set up your own {CMK} server, with {CE} (SaaS) the {CMK} server is already running in the AWS Cloud.

The {CE} (SaaS) software is based on that of {CE} (Self-hosted).
Thus, in principle, both offer close to the same range of functions.
An overview of the functions of link:https://docs.checkmk.com/saas/en/cce.html[{CE} (SaaS)^] can be found in the {CE} User Guide.

As an on-premises edition, {CE} (self-hosted) is based on xref:cse#[{CSE}] in terms of content, but additionally offers extensive cloud functions.
This makes {CE} particularly valuable for users whose hosts are located in a cloud and who also want to set up their entire monitoring in a cloud.

Support when moving applications and processes to the cloud, i.e. in so-called _lift and shift_ scenarios, has already been integrated into all {CMK} editions 
-- which simplifies the implementation of a monitoring of Amazon Web Services (AWS), Microsoft Azure and the Google Cloud Platform (GCP).
In addition, {CE} (Self-hosted) also provides cloud-specific xref:glossar#check_plugin[check plug-ins].
In this way you can continue to use {SE} when transitioning from a data center to a cloud.
If you would subsequently also like to use the SaaS and PaaS products that a cloud can additionally provide, you can upgrade to {CE} (Self-hosted).

xref:managed#[{CME}] is then based on {CE} (Self-hosted).

Complementing the link:https://checkmk.com/pricing[edition comparison^] and the presentation of link:https://checkmk.com/product/checkmk-cloud[{CE}^] on our website, this article explains the differences on a technical level and thus tries to be a complementary support for decision making when choosing a {CMK} edition.

[TIP]
====
Whenever there is no possibility of confusion with {CE} (SaaS) -- as in the other articles in this {CMK} User Guide -- we simply call {CE} (Self-hosted) the {CE}.
====


[#functions]
== Additional functions

The key features of {CE} (Self-hosted) that differentiate it from other editions:

* Only {CE} (Self-hosted) is available through the xref:install_azure#[Microsoft Azure] and xref:install_aws#[AWS] marketplaces.

* Advanced check plug-ins: +
{CE} includes additional cloud-specific check plug-ins for monitoring xref:monitoring_aws#[Amazon Web Services (AWS)], xref:monitoring_azure#[Microsoft Azure] and the xref:monitoring_gcp#[Google Cloud Platform (GCP)].

* Cloud-specific dashboards: +
In {CE}, there are specific dashboards for AWS, Microsoft Azure and GCP.

* Configuration of a push agent: +
In all on-premises editions, the {CMK} server initiates communication with a host and requests the data from the {CMK} agent -- in the so-called xref:glossar.html#pull_mode[pull mode].
With {CE} (Self-hosted)  you can additionally use the xref:glossar.html#push_mode[push mode].

* Auto-registration of hosts: +
In {CE} (Self-hosted), you can have xref:hosts_autoregister#[hosts created automatically] that have a {CMK} agent installed.
This includes registering the agent with the {CMK} server, establishing a TLS-encrypted connection, creating the host, performing a service discovery and activating the changes,
so that the host is added to the monitoring environment -- all fully automatically.
Auto-registration works for pull and push agents.

[TIP]
====
In the Setup of the {CMK} user interface, elements that only exist from {CE} onwards are indicated by the [.guihint]#(Managed Services Edition, Cloud Edition)# suffix, e.g. rules or parameter values.
====


[#upgrade]
== Upgrading to {CE} (Self-hosted)

You can test {CE} (Self-hosted) without obligation, because it is not limited in the first 30 days.
By entering a license key after 30 days at the latest, you can then use {CE} (Self-hosted) without limitations.

To upgrade from one of the other editions to {CE} (Self-hosted), follow the xref:update#upgrade[upgrade description].


[#details]
== Differences of the components in detail

[#ui]
=== The monitoring interface

[cols="20,~",options="header"]
|===
|Function |Description

|Cloud dashboards |In monitoring, you will find the dedicated dashboards for xref:monitoring_aws#dashboards[AWS,] xref:monitoring_azure#dashboards[Azure] and xref:monitoring_gcp#dashboards[GCP].
|===


[#agents]
=== The monitoring agents

[cols="20,~",options="header"]
|===
|Function |Description

|Push mode |The xref:wato_monitoringagents#agents[{CMK} agent] for Linux and for Windows can be configured and used in xref:glossar#push_mode[push mode].
You configure the mode (push or xref:glossar#pull_mode[pull]) in the xref:hosts_setup#monitoring_agents[Monitoring agents] section in the  host or folder properties.
Push mode relies on the Agent Controller and is therefore not available in the agent's legacy mode.

|Auto-registration |You have the option to create hosts automatically during registration with the so-called xref:hosts_autoregister#[auto-registration].
The xref:hosts_autoregister#rule_autoregister_site[[.guihint]#Agent registration#] rule set is used to configure the {CMK} site.
The auto-registration also requires the Agent Controller.

|Agent Bakery |You can additionally use the Agent Bakery to provide agent packages with a configuration for auto-registration.
The rule for the Agent Bakery is named xref:hosts_autoregister.html#rule_autoregister_bakery[[.guihint]#Agent controller auto-registration#].
These packages perform registration automatically after installation.

|Agent registration permissions |The xref:wato_user#predefined_roles[predefined role] `agent_registration` contains additional permissions for creating hosts automatically.
|===


[#connections]
=== Connections

[cols="20,~",options="header"]
|===
|Function |Description
|Grafana |You can install the xref:grafana#[Grafana plug-in] directly from the link:https://grafana.com/grafana/plugins/checkmk-cloud-datasource[Grafana catalog], making it easy to embed the integration into your cloud environment.
|===


[#provision]
=== Deployment

[cols="20,~",options="header"]
|===
|Feature |Description

|Availability in the Azure and AWS Marketplaces |{CE} (Self-hosted) is available for installation in the marketplaces of link:https://azuremarketplace.microsoft.com/en-us/marketplace/apps/tribe29gmbh1665582614827.checkmk003?tab=Overview[Microsoft Azure^] and link:https://aws.amazon.com/marketplace/pp/prodview-gddkal2hfn7yo[AWS^].
The xref:install_azure#[Azure] and xref:install_aws#[AWS] articles will guide you through the image setup.

|Testing the edition |You can test {CE} (Self-hosted) in full functionality for 30 days without obligation.
On a small scale, i.e. with one site and up to 750 services, you can also run {CMK} with {CE} (Self-hosted) on a permanent basis without requiring a subscription.
|===


[#other]
=== Additional functions

[cols="20,~",options="header"]
|===
|Function |Description

|Check plug-ins for AWS |There are additional check plug-ins for the AWS Cloud products
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_lambda[AWS Lambda^],
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_ecs[Elastic Container Service (ECS)^],
link:https://checkmk.com/integrations/aws_route53[Route 53^],
link:https://checkmk.com/integrations/aws_cloudfront[CloudFront^],
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=elasticache[ElastiCache for Redis^] and
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=aws_sns[Simple Notification Service (SNS)^].

|Check plug-ins for Azure |There are additional check plug-ins for the Azure products
link:https://checkmk.com/integrations/azure_app_gateway[Application Gateway^] and 
link:https://checkmk.com/integrations/azure_vault_backup_containers[Recovery Services vaults^].

|Check plug-ins for GCP |There are additional check plug-ins for the Google Cloud products
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_function[Cloud Functions^],
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_run[Cloud Run^] and
link:https://checkmk.com/integrations?distributions%5B%5D=check_mk&distributions%5B%5D=check_mk_cloud&search=gcp_redis[Memorystore for Redis^].

|OpenTelemetry |You can receive xref:opentelemetry#[OpenTelemetry metrics] and process them in the monitoring.
In the dynamic host management, there is a separate connection type for setting up an xref:dcd#connection_opentelemetry[OpenTelemetry connection].
|===

