// -*- coding: utf-8 -*-
// IGNORE 
// NONASCII
include::global_attr.adoc[]
= MKPs for developers
:title: MKPs for developers
:description: You can make extensions for {CMK} available to others as a package. Read here to learn how to modify and publish MKPs.

{related-start}
xref:mkps#[{CMK} extension packages (MKPs)]
xref:localchecks#[Local checks]
xref:devel_intro#[Developing extensions for {CMK}]
xref:bakery_api#[The Bakery-API]
{related-end}


[#intro]
== Introduction

In the other articles on the programming of extensions, you will have already learned how to develop extensions even with just a basic knowledge of Python.
And you will surely have already downloaded and installed extensions as xref:mkps#[MKP] from the link:https://exchange.checkmk.com/[{CMK} Exchange^].
In this article, you will learn everything you need to know about customizing {CMK} extension packages or creating them from extensions you have developed yourself.


[#testenvironment]
=== The working environment

To create and customize MKPs, use a separate xref:glossar#site[site] for testing, and once the tests have been satisfactory, copy the MKPs to the production site for deployment.
This will primarily save you from two potential problems that arise when modified files are not packaged into MKPs in a timely manner:

* During a {CMK} update, xref:update#local_files[locally modified files] are overwritten by the latest version of the MKP (this is exactly what happened to the author of this sentence).
* In a xref:glossar#central_setup[distributed monitoring with central setup], you will be puzzled because plug-ins behave differently on remote sites than on the central site, since the remote sites continue to receive the most recently packaged version.

In addition, the risk of accidentally overwriting something that already exists is much lower if a site is used primarily to test in-house developments and does not use any production-grade extensions from other sources.


[#tools]
=== Tools for MKPs

There are two tools for managing MKPs:

* The `mkp` xref:mkps#commandline[command]
* In the commercial editions, you also have the Setup menu item [.guihint]#Maintenance > Extension Packages#

Both methods are compatible, and changes made using one method are immediately visible in the other.
*However:* additional options are available on the command line, which will be further expanded in the future.
It can also be used in scripts.

For development work, we therefore recommend using the command line.


[#workflow]
== The workflow

In this chapter, we will show you how to modify an existing package by following these steps: disassemble, modify, rearrange, and repackage.
Our example uses the sample MKP https://exchange.checkmk.com/p/hello-world[Hello world!^] available in the {CMK} Exchange.
If you would prefer to build your own MKP from files you have created yourself, simply skip the first steps and go directly to xref:find_unpackaged_cli[search for unpackaged files].


[#release_mkp_cli]
=== Disassembling an MKP

For a package to be disassembled, it must first have the status [.guihint]#Enabled (active on this site)#.
This can be checked using the following command:

[{shell}]
----
{c-omd} mkp list
Name        Version Title        Author             Req. Version Until Version Files State                          
----------- ------- ------------ ------------------ ------------ ------------- ----- -----------------------------
hello_world 0.2.5   Hello world! Mattias Schlenker  2.3.0b1      2.5.99        8     Enabled (active on this site)  
----

If the package is not _active_, activate it:

[{shell}]
----
{c-omd} mkp enable hello_world
----

If a package is incompatible with your {CMK} version but you still want to activate it—specifically to update it to the newer {CMK} version—use the additional parameter `--force-install`.

You can then disassemble the package with the following command:

[{shell}]
----
{c-omd} mkp release hello_world
----

In the Setup of the commercial editions, an icon representing a block (icon:icon_release_mkp[]) is also available.


[#make_modifications]
=== Making modifications

Now you can modify existing files or add new ones.
If your work is not based on an existing MKP but 'starts from scratch', so to speak, you will first need to create a directory structure and populate it, for example, as described in the articles on programming xref:devel_check_plugins#[agent-based check plug-ins], xref:devel_special_agents#[special agents], or xref:devel_check_plugins_snmp#[SNMP plug-ins].


[#find_unpackaged_cli]
=== Finding unpackaged files

Once your development work has reached a stage you are satisfied with, prepare to repackage it.
The first step is to get an overview of which unpackaged files are located in the site directory.
With this information, you can decide whether to delete files or to first package earlier experiments.

The command used for this is `mkp find`:

[{shell}]
----
{c-omd} mkp find
File                                                  Package Version Part                                         Mode      
----------------------------------------------------- ------- ------- -------------------------------------------- ----------
hello_world/rulesets/ruleset_hello_world.py                           Additional Checkmk plug-ins by third parties -rw-------
hello_world/agent_based/hello_world.py                                Additional Checkmk plug-ins by third parties -rw-------
hello_world/rulesets/ruleset_hello_world_bakery.py                    Additional Checkmk plug-ins by third parties -rw-------
hello_world/graphing/helloworld_perfometer_graphing.py                Additional Checkmk plug-ins by third parties -rw-------
hello_world/checkman/hello_world                                      Additional Checkmk plug-ins by third parties -rw-------
windows/plugins/hello_world.cmd                                       Agents                                       -rwx------
plugins/hello_world                                                   Agents                                       -rwx------
python3/cmk/base/cee/plugins/bakery/hello_world.py                    Libraries                                    -rw-------
----

The list displayed is for informational purposes only.
In the commercial editions, you can use the [.guihint]#List unpackaged files# button on the [.guihint]#Extension packages# page.
On the page that appears, you can easily delete files you no longer need.


[#create_template]
=== Creating the package configuration

Use the `mkp template` command to create a template for a package configuration.
You must specify the package name as an additional parameter.
Since this command writes to standard output, you must either redirect the output or simply copy it from the terminal:

[{shell-raw}]
----
{c-omd} mkp template hello_world > ~/tmp/hello_world.info
{c-omd} cat ~/tmp/hello_world.info
{'author': 'Add your name here',
 'description': 'Please add a description here',
 'download_url': 'https://example.com/hello_world/',
 'files': {'agents': ['plugins/hello_world', 'windows/plugins/hello_world.cmd'],
           'cmk_addons_plugins': ['hello_world/agent_based/hello_world.py',
                                  'hello_world/checkman/hello_world',
                                  'hello_world/graphing/helloworld_perfometer_graphing.py',
                                  'hello_world/rulesets/ruleset_hello_world.py',
                                  'hello_world/rulesets/ruleset_hello_world_bakery.py'],
           'lib': ['python3/cmk/base/cee/plugins/bakery/hello_world.py']},
 'name': 'hello_world',
 'title': 'Title of hello_world',
 'version': '1.0.0',
 'version.min_required': '2.5.0p4',
 'version.packaged': 'cmk-mkp-tool 3.0.0',
 'version.usable_until': None}
----

If you would rather use the package configuration from a previously unpacked package, simply extract it from the original package: 

[{shell-raw}]
----
{c-omd} tar -Ox info -f ~/var/check_mk/packages_local/hello_world-0.2.5.mkp \
    > ~/tmp/hello_world.info
----

Now customize the package configuration using your favorite editor.
As with many other configuration files in {CMK}, this is a Python file.
Therefore, make sure to use correct Python syntax.

Under the `files` key, you can remove files that should not be included in the package.
Under `version.min_required`, enter the minimum version of {CMK} required to use the package.
Under `version.usable_until`, you can specify the highest {CMK} version for which the package is usable.
If you use only the stable public plug-in APIs, your package will cover the entire range from {v23} to 3.0.99.
The version number used (`version` key) must comply with the conventions of _Semantic Versioning_.
For minor changes such as bug fixes, increment only the last digit.

If you are using a commercial edition, you will find the [.guihint]#Create package# button on the [.guihint]#Setup > Maintenance > Extension packages# page.
This button takes you to a form where you can enter all of the parameters contained in the package configuration template—without having to worry about correct Python syntax.


[#package_mkp_cli]
=== Creating the package

Once you have finished editing the configuration file, build the package by running `mkp package` followed by the name of the configuration file:

[{shell-raw}]
----
{c-omd} mkp package ~/tmp/hello_world.info
----

This process not only generates the MKP, which you can then find in `~/var/check_mk/packages_local/` or download via the package manager in the commercial editions.
The package is also activated immediately (meaning it has the status [.guihint]#Enabled (active on this site)#), which corresponds exactly to its behavior before packaging.

Note that when packaging on a production site with a central setup enabled, the new package will be  automatically distributed directly to the remote sites.
This fact should be another reason to use dedicated test sites.


[#exchange]
== Publishing on the {CMK} Exchange

If you would like to share your newly created MKP, you can upload it to the link:https://exchange.checkmk.com/[{CMK} Exchange^].
There are a few things to keep in mind before uploading:

* Be aware that your extension uses programming interfaces licensed under GPL v2 and is therefore also subject to the GPL v2 license.

* {com} performs a security check on the extension prior to publication to identify any potential risks.
Packages that read from or write to directories outside a site directory, or that use APIs not provided by {CMK}, will be rejected.

* When extending existing (possibly orphaned) packages, point out potential conflicts due to the use of the same directory structure.
Users should be aware that they must disable the original package before installing your version.


[#package_format]
== The MKP package format

If you just want to take a look inside an MKP or extract individual files without installing the entire package, it is helpful to understand the package format. 
Looking inside a package is quite simple, because the MKP format is simply a `.tar.gz` file, which in turn contains `.tar` files and manifest files.

Examining the downloaded file `hello_world-0.2.5.mkp` reveals the first level of the structure:


[{shell}]
----
{c-user} tar -tvf hello_world-0.2.5.mkp 
-rw-r--r-- 0/0            1715 2025-03-07 16:19 info
-rw-r--r-- 0/0            1311 2025-03-07 16:19 info.json
-rw-r--r-- 0/0           10240 2025-03-07 16:19 agents.tar
-rw-r--r-- 0/0           20480 2025-03-07 16:19 cmk_addons_plugins.tar
-rw-r--r-- 0/0           10240 2025-03-07 16:19 lib.tar
----

Using a pipeline consisting of two `tar` commands, you will be able to view the contents of `cmk_addons_plugins.tar`:

[{shell}]
----
{c-user} tar -Ox cmk_addons_plugins.tar -f hello_world-0.2.5.mkp | tar -tvf -
-rw------- mysite/mysite 3711 2025-03-07 10:59 hello_world/agent_based/hello_world.py
-rw------- mysite/mysite 1079 2025-03-07 10:59 hello_world/checkman/hello_world
-rw------- mysite/mysite 1179 2025-03-07 10:59 hello_world/graphing/helloworld_perfometer_graphing.py
-rw------- mysite/mysite 3373 2025-03-07 10:59 hello_world/rulesets/ruleset_hello_world.py
-rw------- mysite/mysite 2634 2025-03-07 10:59 hello_world/rulesets/ruleset_hello_world_bakery.py
----

And what about the two manifest files, `info` and `info.json`?
You learned about the `info` file and its fields—which are in the Python dictionary format—earlier xref:package_mkp_cli[above].
The JSON equivalent, `info.json`, contains exactly the same fields and values, but has been serialized in JSON format.


[#command_reference]
== Command reference

Commands for management and for updates can be found in the xref:mkps#command_reference[article on managing MKPs].


[#reference_development]
=== Development

[cols="18,~,~",options="header"]
|===
|Subcommand |Parameter |Function
|`release` |Package name |Resolves an active package.
|`find` |_none_ |Lists all files that do not belong to any package.
|`template` |Name of the new package to be created |Creates a manifest file as the basis for a new package.
|`package` |Path to the manifest file |Creates an MKP based on the contents of a manifest file.
|===
