// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Installation on SUSE Linux Enterprise Server
:revdate: 2023-05-11
:title: Installation on SUSE Linux Enterprise Server
:description: Learn how to install {CMK} on the Linux distribution of SUSE Linux Enterprise Server (SLES).

{related-start}
xref:intro_setup#[Setting up {CMK}]
xref:appliance_install_virt1#[Installation of the virtual appliance]
xref:install_packages#[Basic information on the installation of {CMK}]
{related-end}


== Setting up the package sources

{CMK} requires a number of software packages from your Linux distribution.
Third-party software is not required.
In order that all necessary packages can be subsequently installed, a correct configuration of the software sources is necessary.

The setup procedure varies depending on the version of SUSE Linux Enterprise Server (SLES) being used.


[#sles12]
=== SLES 12

With SLES 12 some software components, e.g. PHP, which is required by OMD, are stored in so-called modules.
In order to be able to access SLES 12's PHP packages, the following steps need to be taken:

. link:https://documentation.suse.com/sles/12-SP5/html/SLES-all/cha-planning.html#sec-planning-registering[Registering SLES 12^]
. link:https://documentation.suse.com/sles/12-SP5/html/SLES-all/cha-add-ons.html#sec-add-ons-installation[Installing the 'Web and Scripting' module^]


[#sles15]
=== SLES 15

With SLES 15, in addition to the 'Web and Scripting' module, you also have to install the 'Development Tools' and the 'SUSE Package Hub 15' modules:

* link:https://documentation.suse.com/sles/15-SP5/html/SLES-all/cha-register-sle.html[Registering SLES 15 and Managing Modules^]


== Download the appropriate packages

First choose the xref:intro_setup#editions[{CMK} edition] that suits your needs.
On the link:https://checkmk.com/download[download page^] you will find {RE}, which is Open Source, and {CE}, which is free to use for up to 750 services.
If you have a subscription, then you will find the installation packages in the link:https://portal.checkmk.com/[customer portal^].

We recommend the use of the _latest stable {CMK} version_.
If you need an older version (for example, as the basis for restoring a backup), you can find it in the link:https://checkmk.com/download/archive[download archive^].
Make sure that the package you select exactly matches the installed Linux distribution and its version.

After you have downloaded the package, bring it to the Linux system on which {CMK} is to be installed.
This can be done, for example, via the `scp` command line tool, which comes with every modern system -- and which is also available in PowerShell on Windows 10.
Additional programs such as _WinSCP_ are usually not required.

The example shows the transfer of a {CRE} package on SLES 15:

[{shell-raw}]
----
{c-root} scp check-mk-raw-2.3.0p1-sles15-38.x86_64.rpm root@mymonitoring.mydomain.org:
----


[#signed]
== Signed-package installation

All packages are signed using link:https://gnupg.org[GnuPG^].
Through the use of this signature, on the one hand it can be verified whether the package really is from {CMK}, and on the other hand it can be verified that the package is complete.

So that these signed packages can be installed in the usual way, one time only you will need to import our public key so that the signature will be trusted.
First, load the key directly from our website:

[{shell-raw}]
----
{c-root} wget https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

Then import the key to the list of trusted signatures.
For SLES the `rpm` tool is required:

[{shell}]
----
{c-root} rpm --import Check_MK-pubkey.gpg
----

Once the key has been imported, you can verify the package and install it the usual way using `zypper install` afterwards:

[{shell}]
----
{c-root} rpm -K check-mk-raw-2.3.0p1-sles15-38.x86_64.rpm
check-mk-raw-2.3.0p1-sles15-38.x86_64.rpm: digests signatures OK
{c-root} zypper install check-mk-raw-2.3.0p1-sles15-38.x86_64.rpm
----


== Final test

After the successful installation of {CMK}, and all dependencies, you will have access to the `omd` command.
With this command you are able to create and manage xref:omd_basics#[monitoring sites].
You can request the installed version to verify your installation:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version 2.3.0p1.cre
----
