// -*- coding: utf-8 -*-
include::global_attr.adoc[]
= Installation on Red Hat Enterprise Linux
:revdate: 2024-03-14
:title: Installation on Red Hat Enterprise Linux
:description: Learn how to install {CMK} on the Linux distribution of Red Hat Enterprise Linux (RHEL) and binary compatible distributions.

{related-start}
xref:intro_setup#[Setting up {CMK}]
xref:appliance_install_virt1#[Installation of the virtual appliance]
xref:install_packages#[Basic information on the installation of {CMK}]
{related-end}


== Setting up the package sources

{CMK} requires a number of software packages from your Linux distribution.
Third-party software is not required.
In order that all necessary packages can be subsequently installed, a correct configuration of the software sources is necessary.

With Red Hat Enterprise Linux (RHEL) and all binary compatible distributions such as CentOS, AlmaLinux or Rocky Linux, the _EPEL (Extra Packages for Enterprise Linux)_ repository must be set up as a package source.

You can do this with the help of an RPM package, which can be installed with the `yum` command.

[cols="10,~",options="header"]
|===
|Version |Package link
|8 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`
|9 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm`
|===

Here is an example of the installation of the EPEL package on version 8:

[{shell-raw}]
----
{c-root} yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----

In order to be able to use EPEL on RedHat and derivatives, the package sources for optional RPMs are required if these haven’t already been installed during the operating system installation.
Without these sources the `freeradius-utils`, `graphviz-gd`, and `php-mbstring` packages will be missing.

As of version 8.x it will suffice to activate the so-called PowerTools with the help of Dandified YUM in the free derivatives or the `subscription-manager` in RHEL respectively.
This can be done, e.g., with the following commands:

CentOS from 8.4, AlmaLinux and Rocky Linux:

[{shell}]
----
{c-root} dnf config-manager --set-enabled powertools
----

RHEL 8.x:

[{shell}]
----
{c-root} subscription-manager repos --enable "codeready-builder-for-rhel-8-x86_64-rpms"
----


== Setup SELinux and Firewall

Since RHEL and thus also the derivatives also deliver Security-Enhanced Linux (SELinux) and a local firewall by default, adjustments may still have to be made here.
As the first step you will need to allow your web server to access the network interfaces:

[{shell}]
----
{c-root} setsebool -P httpd_can_network_connect 1
----

Secondly, you release the web server and activate the change:

[{shell}]
----
{c-root} firewall-cmd --zone=public --add-service=http --permanent
success
{c-root} firewall-cmd --reload
success
----


== Download the appropriate packages

First choose the xref:intro_setup#editions[{CMK} edition] that suits your needs.
On the link:https://checkmk.com/download[download page^] you will find {RE}, which is Open Source, and {CE}, which is free to use for up to 750 services. 
If you have a subscription, then you will find the installation packages in the link:https://portal.checkmk.com/[customer portal^].

We recommend the use of the _latest stable {CMK} version_.
If you need an older version (for example, as the basis for restoring a backup), you can find it in the link:https://checkmk.com/download/archive[download archive^].
Make sure that the package you select exactly matches the installed Linux distribution and its version.

After you have downloaded the package, bring it to the Linux system on which {CMK} is to be installed.
This can be done, for example, via the `scp` command line tool, which comes with every modern system -- and which is also available in PowerShell on Windows 10.
Additional programs such as _WinSCP_ are usually not required.

The example shows the transfer of a {CRE} package on AlmaLinux 8.x:

[{shell-raw}]
----
{c-root} scp check-mk-raw-2.2.0p1-el8-38.x86_64.rpm root@mymonitoring.mydomain.org:
----


[#signed]
== Signed-package installation

All packages are signed using link:https://gnupg.org[GnuPG^].
Through the use of this signature, on the one hand it can be verified whether the package really is from {CMK}, and on the other hand it can be verified that the package is complete.

So that these signed packages can be installed in the usual way, one time only you will need to import our public key so that the signature will be trusted.
First, load the key directly from our website:

[{shell-raw}]
----
{c-root} wget https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

Then import the key to the list of trusted signatures.
On RHEL and all derivatives this is yet another job for `rpm`:

[{shell}]
----
{c-root} rpm --import Check_MK-pubkey.gpg
----

Once the key has been imported, you can verify the package and install it the usual way with `yum install` afterwards:

[{shell}]
----
{c-root} rpm -K check-mk-raw-2.2.0p1-el8-38.x86_64.rpm
check-mk-raw-2.2.0p1-el8-38.x86_64.rpm: digests signatures OK
{c-root} yum install check-mk-raw-2.2.0p1-el8-38.x86_64.rpm
----


== Final test

After the successful installation of {CMK}, and all dependencies, you will have access to the `omd` command.
With this command you are able to create and manage xref:omd_basics#[monitoring sites].
You can request the installed version to verify your installation:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version 2.2.0p1.cre
----
