// -*- coding: utf-8 -*-
// IGNORE
// NONASCII
include::global_attr.adoc[]
= Installation on Red Hat Enterprise Linux
:title: Installation on Red Hat Enterprise Linux
:description: You can run {CMK} under Red Hat Enterprise Linux (RHEL) and binary compatible distributions. Read here how to install {CMK} in such environments.    

{related-start}
xref:intro_setup#[Setting up {CMK}]
xref:appliance_install_virt1#[Installation of the virtual appliance]
xref:install_packages#[Basic information on the installation of {CMK}]
{related-end}


[#setup_pkg_source]
== Setting up the package sources

{CMK} requires a number of software packages from your Linux distribution.
Third-party software is not required.
In order that all necessary packages can be subsequently installed, a correct configuration of the software sources is necessary.

With Red Hat Enterprise Linux (RHEL) and all binary compatible distributions such as CentOS, AlmaLinux or Rocky Linux, the _EPEL (Extra Packages for Enterprise Linux)_ repository must be set up as a package source.

include::include_centos_clarification.asciidoc[]

The setup as a package source is done with the help of an RPM package, which can be installed with the `dnf` command.

[cols="10,~",options="header"]
|===
|Version |Package link
|10 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm`
|9 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm`
|8 |`\https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`
|===

Here is an example of the installation of the EPEL package on version 10:

[{shell-raw}]
----
{c-root} dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm
----

In order to be able to use EPEL on Red Hat and binary compatible distributions, the package sources for optional RPMs are required if these haven’t already been installed during the operating system installation.
Without these sources the `freeradius-utils`, `graphviz-gd`, and `php-mbstring` packages will be missing.

All supported versions of Red Hat Enterprise Linux use the CodeReady Linux Builder (CRB):
You can activate them using the `subscription-manager`.
For RHEL 10.x, for example, it can be installed with the following command:

[{shell}]
----
{c-root} subscription-manager repos --enable "codeready-builder-for-rhel-10-x86_64-rpms"
----

AlmaLinux 8.x and Rocky Linux 8.x use PowerTools, which are activated using Dandified YUM (`dnf`):

[{shell}]
----
{c-root} dnf config-manager --set-enabled powertools
----

Starting with version 9.x, the free binary compatible distributions such as AlmaLinux and Rocky Linux also use CRB instead of PowerTools:

[{shell}]
----
{c-root} dnf config-manager --set-enabled crb
----

.The difference between PowerTools and CRB
[%collapsible]
====
CodeReady Linux Builder (CRB) is a repository that contains additional packages for developers – it replaces the older PowerTools. 
PowerTools was a remnant of the CentOS project, CRB is the more modern equivalent.
RHEL has been using CRB since version 8.
The binary compatible Linux distributions followed suit with version 9 and have been using CRB exclusively ever since.
====


[#setup_selinux_firewall]
== Setup SELinux and Firewall

Since RHEL and thus also the binary compatible distributions also deliver Security-Enhanced Linux (SELinux) and a local firewall by default, adjustments may still have to be made here.
As the first step you will need to allow your web server to access the network interfaces:

[{shell}]
----
{c-root} setsebool -P httpd_can_network_connect 1
----

If you are using `firewalld`, enable the web server and activate the change:

[{shell}]
----
{c-root} firewall-cmd --zone=public --add-service=http --permanent
success
{c-root} firewall-cmd --reload
success
----


[#download]
== Download the appropriate packages

First choose the xref:intro_setup#editions[{CMK} edition] that suits your needs.
On the link:https://checkmk.com/download[download page^] you will find {RE}, which is Open Source, and {CE}, which is free to use for up to 750 services. 
If you have a subscription, then you will find the installation packages in the link:https://portal.checkmk.com/[customer portal^].

We recommend the use of the _latest stable {CMK} version_.
If you need an older version (for example, as the basis for restoring a backup), you can find it in the link:https://checkmk.com/download/archive[download archive^].
Make sure that the package you select exactly matches the installed Linux distribution and its version.

After you have downloaded the package, bring it to the Linux system on which {CMK} is to be installed.
This can be done, for example, with the `scp` command line tool, which comes with every modern system -- and which is also available in PowerShell since Windows 10.
Additional programs such as _WinSCP_ are usually not required.

The example shows the transfer of a {CRE} package to a system running RHEL 8.x:

[{shell-raw}]
----
{c-root} scp {pkg-cre}-{current}-el8-38.x86_64.rpm root@mymonitoring.mydomain.org:/tmp
----


[#signed]
== Signed-package installation

All packages are signed using link:https://gnupg.org[GnuPG^].
Through the use of this signature, on the one hand it can be verified whether the package really is from {CMK}, and on the other hand it can be verified that the package is complete.

So that these signed packages can be installed in the usual way, one time only you will need to import our public key so that the signature will be trusted.
First, load the key directly from our website:

[{shell-raw}]
----
{c-root} wget https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

As next step, import the key to the list of trusted signatures.
On RHEL and all binary compatible distributions this is a job for the `rpm` tool:

[{shell}]
----
{c-root} rpm --import Check_MK-pubkey.gpg
----

Once you have imported the key, you can verify the package and install it the usual way with `dnf install` afterwards:

[{shell}]
----
{c-root} rpm -K {pkg-cre}-{current}-el8-38.x86_64.rpm
{pkg-cre}-{current}-el8-38.x86_64.rpm: digests signatures OK
{c-root} dnf install {pkg-cre}-{current}-el8-38.x86_64.rpm
----


[#test]
== Final test

After the successful installation of {CMK}, and all dependencies, you will have access to the `omd` command.
With this command you are able to create and manage xref:omd_basics#[monitoring sites].
You can request the installed version to verify your installation:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version {current}.community
----
