// -*- coding: utf-8 -*-
// IGNORE % p2 pre
include::global_attr.adoc[]
= Installation from Azure Marketplace
:title: Installation from Azure Marketplace
:description: You can run {CMK} as a VM image in Microsoft Azure. Read here how to set up, configure and use your {CMK} site in the Azure VM.

{related-start}
xref:intro_setup#[Setting up {CMK}]
xref:install_packages#[Basic information on the installation of {CMK}]
xref:update#[Updates and Upgrades]
{related-end}


[#welcome]
== Welcome to {CMK} for Azure

Whether you are a long-time user of {CMK}, or have only recently found us with the availability of ready-made images in the Microsoft Azure Marketplace, in this article you will find all of the resources required to configure the prepared VM image into a monitoring that suits your needs.

If you are new to {CMK}, we recommend reading our xref:intro_setup#[Beginner's Guide] in preparation.
Preconfigured VM images may shortcut many tasks during an installation, but some knowledge of fundamental concepts, such as xref:glossar#site[sites], will help during the setup process.

[#basics]
=== The basics

If you are an Azure user, you have always had the option of adding {CMK} to an link:https://learn.microsoft.com/en-us/azure/virtual-machines/linux/quick-create-portal?tabs=ubuntu[existing Ubuntu image^] available in the Marketplace, in order to set up a 'monitoring in the cloud'.
Meanwhile we take this a step further and provide link:https://azuremarketplace.microsoft.com/en-us/marketplace/apps/tribe29gmbh1665582614827.checkmk003?tab=Overview[a pre-installed image^], based on Ubuntu 22.04 _(Jammy Jellyfish)_ with all of the required dependencies already included.
Only the xref:cce#[{CE-onprem}] is used in such a scenario. 
This will be in a 30-day 'Trial' license state with no restrictions when the first site is set up.
After the trial period expires, {CMK} can continue to be used as a single site with up to 750 monitored services without requiring a subscription.
If more services need to be monitored, or more sites are required, you will need a xref:license#license_cce[license key].

In general, the setup is a bit more involved than, for example, xref:introduction_docker#[Docker image], after all, the image provided must cover various deployment scenarios:

* A _single site setup_ on a server at various scales
* Central site in a distributed monitoring
* Remote site in a distributed monitoring
* Mixed operations consisting of a production site and site(s) for running tests on a host

For this reason, the Azure image does not include a ready-to-run site, an email or a firewall configuration.

In this article we will guide you through the complete setup.
Where additional background information would be useful, we link to detailed articles in our User Guide.


[#preparation]
== Preparation

As well as the dimensioning of RAM, processor and virtual hard drives, you should also think about the location for the storage of backups.
{CMK} natively supports Azure's object stores, but backups can also be stored in file system paths, which allows backups to SMB or WebDAV mounts or regular transfers via `rsync`.


[#ssh_keys]
=== Creating SSH keys

Since Azure link:https://learn.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys[does not currently support ED25519 or ECDSA keys^], you will create an RSA key pair for the first login to the virtual machine, whose _public key_ you upload when you create the VM.
Alternatively, you can let Azure create the key pair.
In this case, do not forget to download the private key during the ordering process.


[#ports]
=== Determining the required ports

In a {CMK} configuration with a single site setup, in which hosts also send data to the {CMK} site in the push mode, the following {CMK} server ports must be accessible:

* From the hosts in monitoring: Port 80/443 (HTTP/HTTPS, during agent registration) and Port 8000 (the Agent Receiver, permanently).
* For management via the browser and the REST API: Port 80/443 (HTTP/HTTPS)

The sharing of these ports is predefined in our [.guihint]#Inbound port rules#.
For the best possible security, you should further restrict access in the [.guihint]#Networking# tab.

Consult our xref:ports#[overview of all ports used] if you want to set up a distributed monitoring or, for example, make status queries via the xref:glossar#livestatus[Livestatus] interface.


[#book_vm]
=== Booking an image in the Marketplace

The following VM instances are a recommendation for the dimensioning of the number of services to be monitored.
When ordering the instance, deactivate the [.guihint]#burstable# option.

[cols="17,17,17,17,~",options="header"]
|===
|Type |CPU cores |RAM (GB) |SSD (GB) |{CMK} services
|`B4MS` |4 |16 |32 |12 000
|`B8MS` |8 |32 |64 |30 000
|`B12MS`  |12 |48 |96 |60 000
|===

The basis for such calculations of dimensioning is approximately 15{nbsp}% of services by xref:glossar#special_agent[special agents] and xref:glossar#active_check[active checks], as well as 25 or more services per regular host delivered via an agent in xref:glossar#push_mode[push mode].
Under certain circumstances, significantly more services are possible in a purely synthetic monitoring (in which data is primarily delivered by special agents).
When using agents in xref:glossar#pull_mode[pull mode], the specified number of services may only be achievable through consistent optimization.

The dimensioning of the hard disk space is based on the experience of typical Windows and Linux server environments.
If there are many services producing a large volume of metrics, a larger amount of storage space may be required.


[#book_backup]
=== Booking backup storage

Because of the favorable traffic costs, we advise the use of _Azure Blob Storage_.
For the calculation of the required storage space, read the xref:graphing#rrds[notes on the RRD data format].
As a rule of thumb for calculating a full backup, _Round Robin Databases_ will have reached just over a third of their maximum capacity after 10 days.
This means that after this time it makes sense to again review the size of the backup storage that has been booked.


// Common part 
include::include_common_aws_azure.asciidoc[]


[#aftermath]
== Post-processing

[#backup]
=== Configuring the backups

{CMK} features a convenient xref:backup#[backup function], which is configured under [.guihint]#Setup > Maintenance > Backups > Backup targets#.
With [.guihint]#Add backup target# you add a storage location.
Here it is advisable to select [.guihint]#Azure Blob Storage# as the [.guihint]#Destination# because of its fast and cheap data transfer.

In addition to the credentials, you must also specify a folder path where the archive is temporarily stored before it is copied to the object store.
This can be under `/tmp`.
If your Azure VM provides a volatile _(ephemeral)_ drive under `/mnt`, here you can also create a directory as a cache:

[{shell}]
----
{c-ubuntu} sudo mkdir -p /mnt/backup/mysite
----

In order for the site user to be able to write to this directory, you must transfer it to them:

[{shell}]
----
{c-ubuntu} sudo chown mysite:mysite /mnt/backup/mysite
----

[#restore]
==== Procedure for a restore

The xref:backup#backup_restore[restore of a backup] must always be performed on exactly the same version of {CMK} as was used to create it.
If a backup is to be used to move to another type of virtual machine, to another cloud provider or from an _on premise installation_ to the cloud (or vice versa), always first upgrade to the highest available patch level of {CMK} _before_ the final backup and migration.

The following points apply to the restore of a backup:

. On the target system, install exactly the version of {CMK} that was used to create the backup.
. Create a monitoring site with `omd create` that uses the same site name as the source system.
. Specify the backup destination and upload the backup key.
. Perform the actual restore.


[#monitoring_azure]
== Monitoring Azure

{CMK} not only provides availability as an Azure image, but also a comprehensive xref:monitoring_azure#[monitoring of your Azure infrastructure].
Even if {CMK} should be your first or only Azure project, it is already worth monitoring the performance of the virtual machine, the state of the backup vaults and the level of costs incurred.
