// -*- coding: utf-8 -*-
// IGNORE 
// NONASCII
include::global_attr.adoc[]
= Installation on SUSE Linux Enterprise Server
:title: Installation on SUSE Linux Enterprise Server
:description: You can run {CMK} under the Linux distribution of SUSE Linux Enterprise Server (SLES). Read here how to install {CMK} in such environments.    

{related-start}
xref:intro_setup#[Setting up {CMK}]
xref:appliance_install_virt1#[Installation of the virtual appliance]
xref:install_packages#[Basic information on the installation of {CMK}]
{related-end}


[#setup_pkg_source]
== Setting up the package sources

{CMK} requires a number of software packages from your Linux distribution.
Third-party software is not required.
In order that all necessary packages can be subsequently installed, a correct configuration of the software sources is necessary.

For SLES 12 and 15 you have to install the 'Web and Scripting' module, for SLES 15 additionally the 'Development Tools' and the 'SUSE Package Hub 15' modules.
To do this, follow the instructions in link:https://documentation.suse.com/sles/15-SP6/html/SLES-all/cha-register-sle.html[Registering SLES and managing modules^].


[#download]
== Download the appropriate packages

First choose the xref:intro_setup#editions[{CMK} edition] that suits your needs.
On the link:https://checkmk.com/download[download page^] you will find {RE}, which is Open Source, and {CE}, which is free to use for up to 750 services. 
If you have a subscription, then you will find the installation packages in the link:https://portal.checkmk.com/[customer portal^].

We recommend the use of the _latest stable {CMK} version_.
If you need an older version (for example, as the basis for restoring a backup), you can find it in the link:https://checkmk.com/download/archive[download archive^].
Make sure that the package you select exactly matches the installed Linux distribution and its version.

After you have downloaded the package, bring it to the Linux system on which {CMK} is to be installed.
This can be done, for example, with the `scp` command line tool, which comes with every modern system -- and which is also available in PowerShell since Windows 10.
Additional programs such as _WinSCP_ are usually not required.

The example shows the transfer of a {CRE} package to a system running SLES 15:

[{shell-raw}]
----
{c-root} scp {pkg-cre}-{current}-sles15-38.x86_64.rpm root@mymonitoring.mydomain.org:/tmp
----


[#signed]
== Signed-package installation

All packages are signed using link:https://gnupg.org[GnuPG^].
Through the use of this signature, on the one hand it can be verified whether the package really is from {CMK}, and on the other hand it can be verified that the package is complete.

So that these signed packages can be installed in the usual way, one time only you will need to import our public key so that the signature will be trusted.
First, load the key directly from our website:

[{shell-raw}]
----
{c-root} wget https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

Then import the key to the list of trusted signatures.
For SLES this is a job for `rpm`:

[{shell}]
----
{c-root} rpm --import Check_MK-pubkey.gpg
----

Once you have imported the key, you can verify the package and install it the usual way using `zypper install` afterwards:

[{shell}]
----
{c-root} rpm -K {pkg-cre}-{current}-sles15-38.x86_64.rpm
{pkg-cre}-{current}-sles15-38.x86_64.rpm: digests signatures OK
{c-root} zypper install {pkg-cre}-{current}-sles15-38.x86_64.rpm
----


[#test]
== Final test

After the successful installation of {CMK}, and all dependencies, you will have access to the `omd` command.
With this command you are able to create and manage xref:omd_basics#[monitoring sites].
You can request the installed version to verify your installation:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version {current}.cre
----
