// -*- coding: utf-8 -*-
// IGNORE 
// NONASCII
include::global_attr.adoc[]
= Installation on SUSE Linux Enterprise Server
:title: Installation on SUSE Linux Enterprise Server
:description: You can run {CMK} under the Linux distribution of SUSE Linux Enterprise Server (SLES). Read here how to install {CMK} in such environments.    

{related-start}
xref:intro_setup#[Setting up {CMK}]
xref:appliance_install_virt1#[Installation of the virtual appliance]
xref:install_packages#[Basic information on the installation of {CMK}]
{related-end}


[#setup_pkg_source]
== Setting up the package sources

{CMK} requires a number of software packages from your Linux distribution.
Third-party software is not required.
In order that all necessary packages can be subsequently installed, a correct configuration of the software sources is necessary.

To provide this, the modules 'Web and Scripting', 'Development Tools' and 'SUSE Package Hub' have to be selected.
Follow the instructions in link:https://documentation.suse.com/sles/15-SP6/html/SLES-all/cha-register-sle.html[Registering SLES and managing modules^] to achieve this.


[#setup_selinux_firewall]
== Setup SELinux and Firewall

Depending on the SLES version used and the installation media chosen, Security-Enhanced Linux (SELinux) and a local firewall might be active.
Adjustments may be necessary to those.
As the first step you will need to allow your web server setup outgoing connections:

[{shell}]
----
{c-root} setsebool -P httpd_can_network_connect 1
----

.Why does the web server need to setup outgoing connections?
[%collapsible]
====
Checkmk allows xref:omd_basics#[multiple sites] to run in parallel on a single server.
To achieve this, an Apache web server is used for each instance, running on a high port under the instance user.
The system Apache, running on the standard ports 80/443 (when xref:omd_https#[HTTPS is enabled]), acts as a reverse proxy to access the site Apaches.
To make this work, the system Apache must be allowed to establish connections itself.
====

If you are using `firewalld`, enable the web server and activate the change:

[{shell}]
----
{c-root} firewall-cmd --zone=public --add-service=http --permanent
success
{c-root} firewall-cmd --reload
success
----


[#download]
== Download the appropriate packages

First choose the {CMK} xref:glossar#edition[edition] that suits your needs.
On the link:https://checkmk.com/download[download page^] you will find {RE}, which is Open Source, and the commercial editions, which you can try out in license state 'Trial'.
If you have a subscription, then you will find the installation packages in the link:https://portal.checkmk.com/[customer portal^].

We recommend the use of the _latest stable {CMK} version_.
If you need an older version (for example, as the basis for restoring a backup), you can find it in the link:https://checkmk.com/download/archive[download archive^].
Make sure that the package you select exactly matches the installed Linux distribution and its version.

After you have downloaded the package, bring it to the Linux system on which {CMK} is to be installed.
This can be done, for example, with the `scp` command line tool, which comes with every modern system -- and which is also available in PowerShell since Windows 10.
Additional programs such as _WinSCP_ are usually not required.

The example shows the transfer of a {CRE} package to a system running SLES 15:

[{shell-raw}]
----
{c-root} scp {pkg-cre}-{current}-sles15-38.x86_64.rpm root@mymonitoring.mydomain.org:/tmp
----


[#signed]
== Signed-package installation

All packages are signed using link:https://gnupg.org[GnuPG^].
Through the use of this signature, on the one hand it can be verified whether the package really is from {CMK}, and on the other hand it can be verified that the package is complete.

So that these signed packages can be installed in the usual way, one time only you will need to import our public key so that the signature will be trusted.
First, load the key directly from our website:

[{shell-raw}]
----
{c-root} wget https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
----

Then import the key to the list of trusted signatures.
For SLES this is a job for `rpm`:

[{shell}]
----
{c-root} rpm --import Check_MK-pubkey.gpg
----

Once you have imported the key, you can verify the package and install it the usual way using `zypper install` afterwards:

[{shell}]
----
{c-root} rpm -K {pkg-cre}-{current}-sles15-38.x86_64.rpm
{pkg-cre}-{current}-sles15-38.x86_64.rpm: digests signatures OK
{c-root} zypper install ./{pkg-cre}-{current}-sles15-38.x86_64.rpm
----


[#enable_apache]
== Activation of the Apache web server

SLES does not automatically activate the Apache web server, which is installed as a dependency.
Use YaST or the `systemctl` command to enable and start Apache:

[{shell}]
----
{c-root} systemctl enable apache2
Created symlink '/etc/systemd/system/httpd.service' → '/usr/lib/systemd/system/apache2.service'.
Created symlink '/etc/systemd/system/apache.service' → '/usr/lib/systemd/system/apache2.service'.
Created symlink '/etc/systemd/system/multi-user.target.wants/apache2.service' → '/usr/lib/systemd/system/apache2.service'.
{c-root} systemctl start apache2
----


[#test]
== Final test

After the successful installation of {CMK}, and all dependencies, you will have access to the `omd` command.
With this command you are able to create and manage xref:omd_basics#[monitoring sites].
You can request the installed version to verify your installation:

[{shell}]
----
{c-root} omd version
OMD - Open Monitoring Distribution Version {current}.community
----
