// -*- coding: utf-8 -*-
// IGNORE ons
include::global_attr.adoc[]
= {CMK} server in a Docker container
:revdate: 2021-04-22
:title: {CMK} server in a Docker container
:description: Following the start of a Docker container is its ongoing maintenance. This article describes what peculiarities should be noted.

{related-start}
xref:introduction_docker#[Installation as a Docker container]
xref:appliance_install_virt1#[Installation of the virtual appliance]
xref:update#[Updates and Upgrades]
{related-end}


== {CMK} in a Docker container

In our xref:introduction_docker#[installation guide for {CMK} in Docker] we have
already shown you how to set up {CMK} in a Docker container. This article takes
a closer look at more of the details.


== Optional parameters during the setup

All of the following parameters are specified additionally when setting up a
{CMK} site as a container and are therefore not available separately.


[#https]
=== Using HTTPS

If {CMK} is the only web server on your Docker node, you can also bind the
port to the standard (`80`) HTTP port. As soon as you you have multiple
web servers on a Docker node however, you will probably use a reverse-proxy
like Nginx - this directs the inquiries to the correct container. With this
technology you can also use (possibly preexisting) HTTPS. The reverse proxy
will then be addressed via HTTPS, while communicating with the container
continues via HTTP.


=== Setting an initial password

In {CMK}, you choose a password for the default user `cmkadmin` when xref:intro_setup#create_site[creating a site].
When creating a {CMK} container, you can provide this password as a parameter for the container.
Simply add the `-e CMK_PASSWORD=mypassword` option during the creation process.


=== Setting your own site ID

With the default command to create a {CMK} container, the ID of the site created in the container will be `cmk`.
This is important to be able to access the site via HTTP(S) and it must therefore be explicit.
If you have multiple containers of {CMK} on the same Docker node, you will have to set the ID manually to ensure this uniqueness.
You can do that by including the `-e CMK_SITE_ID=mysite` option.
The full command could look like this:

[{shell}]
----
{c-root} docker container run -e CMK_SITE_ID="mysite" -dit -p 8080:5000 -p 8000:8000 --tmpfs /opt/omd/sites/mysite/tmp:uid=1000,gid=1000 -v monitoring:/omd/sites --name monitoring -v /etc/localtime:/etc/localtime:ro --restart always checkmk/check-mk-raw:2.1.0-latest
----

Please pay attention to also state the ID of your site in the path of the option `--tmpfs` (in this example `mysite`).


=== Sending notifications

An important feature of {CMK} is the sending of
xref:monitoring_basics#notifications[notifications] per email. {CMK} uses
Postfix as its MTA (Mail Transfer Agent) for outgoing mails. This postfix instance
is configured not to deliver mails directly to the recipient, but basically
tries to forward to an additional mail server (SMTP Relay Server, smarthost) which
you need to provide outside of the container. Such a relay server is available
in almost every organization.

When implementing, specify the relay mail server that will forward the notifications.
In the `-e` option,
use the `MAIL_RELAY_HOST` variable -- e.g., `-e MAIL_RELAY_HOST='mailrelay.mydomain.com'`. If the mail server expects a specific host name, add the following
option: `--hostname 'mymonitoring.mydomain.com'`.

{CMK} containers currently do not support the configuration of access data for a smart host.
You can bind a postfix configuration or configuration folder from the Docker node
if you need them.

{cee-only}
If you use one of the commercial editions, you are able to bypass postfix completely so that {CMK} forwards notifications directly to a smarthost.
This is done by the synchronous SMTP, which is described in detail in the article about xref:notifications#syncsmtp[notifications].
Here an authentication over SMTP is also possible.


=== Access to Livestatus via TCP

As soon you connect multiple {CMK} containers/sites together
in a distributed environment you will need a special TCP port for the
Livestatus interface. This interface allows communication between the
sites. Bind this port – likewise the port for HTTP – to one of the
Docker nodes, and enable this TCP port in the Livestatus site: `-e
CMK_LIVESTATUS_TCP=on -p 6557:6557`.


[#bash]
=== Access via the command line

In some cases you might want to execute commands on the command line.
Because commands for a site are always executed via a special user, you must specify this when logging in.
In {CMK} the user always has the same name as the site it manages.
Specify the user `cmk` with the `-u cmk` option:

[{shell}]
----
{c-root} docker container exec -it -u cmk monitoring bash
----

You can then pass your xref:cmk_commandline#[commands] to the site.


=== Using the Event Console

{CMK} is able to receive SNMP traps and syslog messages.
To be able to use this feature in a {CMK} container, the standardized ports must be forwarded to the Checkmk container using the following command line parameters:
`-p 162:162/udp -p 514:514/udp -p 514:514/tcp`.
In order for the site to honor these ports, activate the appropriate add-ons in the site using the command xref:omd_basics#omd_config[`omd config`].
You can find these in the `Addons` submenu:

[{shell}]
----
{c-root} docker container exec -it -u cmk monitoring bash
{c-omd} omd config
----

////
SK: I removed this paragraph for the time being. Currently this does not work.
== Creating your own container-images

With the help of our our repository you can also
create your own images with one of the commercial editions. Clone the current
link:https://github.com/Checkmk/checkmk[{CMK}-Git], and navigate to the
`docker` directory. With the help of your customer data you can now
create your own image:

[{shell}]
----
myuser@myhost:~/git/check_mk/docker$ docker build \
    --build-arg CMK_VERSION=1.5.0p5 \
    --build-arg CMK_EDITION=enterprise \
    --build-arg CMK_DL_CREDENTIALS='myusername:mypassword' \
    -t mycompany/check-mk-enterprise:1.5.0p5
----

During the build process you will need two external files which -- using your customer login data -- will be automatically downloaded from our download server. To prevent this you can also
first load the necessary files manually and place them in the `docker`
directory:

* The {CMK} installation package for Debian Stretch
* The public GPG-Key for the installation packet
////

[#commands]
== Useful commands

[cols=2]
|===
|Command |Function

|`docker inspect myContainer` |With this command you can get all sorts of information about a running container with the name `myContainer`. Among other things, here you will also find which data storage devices (volumes) are integrated. This is especially useful if you haven’t given the volume a human-readable name and want to xref:update#updatedocker[update your container] .
|===
 

