// -*- coding: utf-8 -*-
// IGNORE 
// NONASCII …​
include::global_attr.adoc[]
= Securing the web interface with HTTPS
:title: Securing the web interface with HTTPS
:description: You can secure your {CMK} sites with HTTPS. Read here how to acquire the necessary certificates and how to configure HTTPS access to your sites.

{related-start}
xref:kerberos#[Single sign-on with Kerberos]
xref:ldap#[User management with LDAP/Active Directory]
{related-end}


[#intro]
== Introduction

The main reason for securing the {CMK} web interface is usually security:
Monitoring can generate a large volume of data that reveals to potential attackers which targets are worthwhile and which attack vectors are likely to succeed.
Third parties should not be able to view or manipulate this transmitted data.
For this reason, it should go without saying that at least those monitoring sites accessible via public networks should be secured with HTTPS.

[TIP]
====
Even when used within trusted environments, consistent use of HTTPS contributes to a smooth {CMK} experience.

The default security settings of all modern browsers block the unencrypted component in many combinations of HTTP and HTTPS, or force the connection to be upgraded to HTTPS.
For example, you cannot embed dashboards loaded via HTTP in _inline frames_ on pages that were loaded via HTTPS (link:https://developer.mozilla.org/en-US/docs/Web/Security/Defenses/Mixed_content[_Mixed content_^]).
Additionally, redirection from HTTPS to HTTP is not possible, which is relevant when external authentication is used.
Furthermore, most browsers block access to the clipboard via JavaScript, which renders copy buttons unusable.
====

If you want to use the {CMK} web interface via HTTPS, you must meet the following requirements on your monitoring server—regardless of your sites:

* You must have a valid server certificate.
* The Apache module `mod_ssl` is installed and enabled.
* The Apache modules `mod_rewrite` and `mod_headers` are present and also enabled.
* The server is accessible via HTTPS.

This article explains how to do this.


[#certificates]
== Obtaining certificates

Since many distributions have non-standard paths to certificates, certificate chains, and keys configured by default, it makes sense to first obtain the certificates and then tackle the configuration of the Apache web server.

Essentially, the following methods are available for obtaining a server certificate:

* Use xref:letsencrypt[free certificates from _Let's Encrypt_].
This method only allows for domain-level validation.
To request certificates, the server you want to secure must be accessible from the outside, or you must be able to create (automated) entries in the public DNS for the domain in question.

* You use an external service provider for xref:oldschoolcsr[certificate issuance via CSR] (_Certificate Signing Request_), whose root certificate is trusted by browser and operating system vendors.
With this method, certificates can be validated not only at the link:https://en.wikipedia.org/wiki/Public_key_certificate#Web_PKI[level^] of a domain, but also at the organizational level (Organization Validation) and higher (Extended Validation), as is mandatory in some industries for regulatory reasons.

* You will set up your xref:becomeca[own _Certificate Authority_ (CA)] and generate your own certificates.
The root certificate of your own CA must be installed on all computers that communicate with servers using certificates signed with the CA key.
When managing your own CA, high security standards must be maintained, as this CA can be used to issue certificates for any domain.


[#letsencrypt]
=== Let's Encrypt

If a server is accessible from the outside or if you have access to the name server, you can automatically generate certificates through the non-profit service provider link:https://letsencrypt.org/#[Let's Encrypt^], which is part of the Electronic Frontier Foundation (EFF).
There are no costs involved.
Certificates validated via DNS require a few minutes of attention every 90 days, while certificates validated via a server directory can be automatically renewed for years.

For Let's Encrypt certificates, the EFF provides the Python program _Certbot_ in many different package formats.
Certbot handles the generation of the key, the submission of the CSR, the verification of server or domain ownership, and finally downloads the certificate.
To do this, it communicates with the EFF's servers via the link:https://en.wikipedia.org/wiki/Automatic_Certificate_Management_Environment[Automatic Certificate Management Environment (ACME)^] protocol.


[#letsencrypt_install_certbot]
==== Installing the Certbot script

There are three ways to install Certbot.
Which one you choose will depend primarily on the age of your distribution and your organization's policies regarding installation from third-party package sources:

* If your Linux distribution's package manager provides Certbot version 1.10 or higher, you can use that version of Certbot.

* The EFF recommends installing from a Snap image on its link:https://certbot.eff.org/instructions#[Certbot documentation page^].
The well-known advantages and disadvantages of the Snap package format apply.

* Certbot can be installed via the Python package installation tool `pip` from the link:https://pypi.org/project/certbot/#[Python Package Index^].
First, create a link:https://docs.python.org/3/library/venv.html[Python virtual environment (`venv`)] to ensure that no Python modules provided by the distribution are corrupted.
In the virtual environment, run `pip install certbot` to install Certbot and all required Python modules.


[#letsencrypt_fully_automated]
==== Fully automated configurations

If the {CMK} server is accessible from the Internet and you have not made any changes to the system-wide Apache web server configuration since installing {CMK}, you can use Certbot's 'Apache Automation' feature.
This feature allows you to generate keys, request certificates, automatically adjust the Apache configuration, and finally set up a cron job to regularly renew the certificates, which are valid for 90 days.

[{shell}]
----
{c-root} certbot --apache
----

The script will now interactively prompt you for some information regarding contact details (email address for additional information such as necessary certificate revocations) and installation paths.
The result is a fully functional SSL configuration.
You do not need to modify the configuration file for `mod_ssl`; Certbot will have already taken care of that.


[#letsencrypt_partially_automated]
==== Partially automated configurations

If, as described in the previous section, you want to request certificates but customize the Apache configuration yourself, use the following command:

[{shell}]
----
{c-root} certbot certonly --apache
----

You can then complete the configuration xref:configsample[as described below] in the configuration file for `mod_ssl`.


[#letsencrypt_others]
==== Additional options

For example, if the {CMK} server is only accessible from the intranet or via VPN, but the DNS server is public, you can perform validation using a _DNS challenge_.
In this case, domain ownership is not verified by the ability to place files on the web server, but rather by the ability to add entries to the DNS.
This does not involve records that resolve a hostname to an IP address, but rather so-called TXT records, which can contain any string of characters.
TXT records are also used, for example, to specify which servers are authorized to send emails on behalf of a domain.

DNS challenges can be performed manually, which—given their 90-day validity period—is usually only practical for individual test systems.
If your DNS provider offers an API supported by Let's Encrypt, automatic renewal is also possible.
For more information, see the link:https://letsencrypt.org/docs/challenge-types/[Overview of Challenge Types^] on the Let's Encrypt website.


[#oldschoolcsr]
=== Using an external CA

For a long time, having certificates signed by a commercial Certificate Authority was the only way to obtain certificates accepted by all browsers and operating systems.
This procedure is still common today, particularly when validation on organization level rather than domain level is required.

The process is as follows: First, you generate the private server key, then create a _Certificate Signing Request_ (CSR) for it, which you submit to the selected provider.
The provider then verifies ownership of the domain, signs the CSR with its key, and sends you the resulting server certificate.

Please note—regardless of the examples below—that you must also follow the guidelines provided by your chosen Certificate Authority and modify the commands accordingly when required.


[#createcsr]
==== Generating keys and CSRs

First, generate the private server key.
You can perform this step directly on the server running the {CMK} site you want to secure.

The folder `/etc/certs` used here is the default for many distributions.
However, you can use any folder that the Apache process has read access to.
Naming the key after the primary domain name for which it will be used (in this case, `checkmk.mydomain.com`) helps to maintain a clear overview.
This naming convention makes it easier to identify the key, especially if additional server names are added later that require their own keys and certificates.

The private key will later be used to encrypt data traffic and should therefore be handled with care (for example, regarding access permissions).
To ensure that the Apache server can be restarted automatically, most administrators do not set a passphrase.

[{shell}]
----
{c-root} openssl genrsa -out /etc/certs/checkmk.mydomain.com.key 2048
Generating RSA private key, 2048 bit long modulus (2 primes)
.....+++++
...............................................................+++++
e is 65537 (0x010001)
----

In the next step, you'll create the Certificate Signing Request (CSR)—a digital request to generate an identity certificate (in this case, a public-key certificate):

[{shell}]
----
{c-root} openssl req -new -key checkmk.mydomain.com.key -out checkmk.mydomain.com.csr
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
---
Country Name (2 letter code) [AU]: *DE*
State or Province Name (full name) [Some-State]: *Bavaria*
Locality Name (eg, city) []: *Munich*
Organization Name (eg, company) [Internet Widgits Pty Ltd]: *Yoyodyne Inc.*
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []: *checkmk.mydomain.com*
Email Address []: pass:[webmaster@mydomain.com]

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
----

Be sure to enter the company information correctly, and enter the server name as the `Common Name`.
The `Email Address` should be within the same domain and belong to an existing email account that is actively monitored.


[#create_extension]
==== Create an extension file

Modern browsers require certificates that use the extension for _alternative host names_, even if the certificates are issued for only a single host name.
This requires an extension file, which some providers automatically create and integrate.
If this is not the case or if you are unsure, create such a file.
If a certificate is to be valid for multiple host names, add additional lines under `[alt_names]`, such as `DNS.2 =` and so on:

./tmp/checkmk.mydomain.com.ext
[{file}]
----
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = checkmk.mydomain.com
----


[#file_documents]
==== Submitting documents

Depending on the desired validation level, it may be necessary to compile additional documents, such as extracts from the commercial register or bank information.
Since the required documents, submission methods, and verification procedures vary from provider to provider, no general guidelines can be provided here.
For example, Extended Validation may also involve sending a code via certified mail to a managing director or authorized signatory, which must then be entered via a web-based form.

In the simplest case of domain-level validation, the CSR file and, if applicable, the EXT file are uploaded via a web interface.
You will then be given the option to select an email address: either from those on file for the domain's Admin-C (owner) or Tech-C (technical contact), or a generic email address such as `webmaster@domain.com`.
A confirmation link will then be sent to this address.


[#receive_cert]
==== Receive a certificate

The verification process itself usually takes a few minutes at most for domain-level validation, but can sometimes take several days for an extended validation.
Once this is complete, you will receive the certificate associated with your key via email or download.
In addition to the certificate, you will also receive a download link for the _certificate chain_ (_Certificate Chain File_).
Be sure to save this as well.


[#becomeca]
=== Using an internal CA

You can assume the role of a Certificate Authority (CA) and issue certificates for any domains (your own domains, third-party domains, and fictional domains).
Using your own CA is particularly useful for test environments or isolated {CMK} servers with a manageable number of users.
This is also the only way to obtain certificates if you are using one of the five reserved top-level domains (TLDs)—`.example`, `.invalid`, `.local`, `.localhost`, or `.test`—internally.
There are no registrars for these domains, so ownership cannot be verified.

This chapter explains how to issue certificates using such an internal CA.
It is assumed that you already have the private CA root or CA intermediate key and will now use it to issue certificates to secure a {CMK} server.

Creating the CA keys, the CA certificate, and the associated configuration file is not covered in this guide.
The {CMK} blog contains link:https://checkmk.com/blog/how-become-your-own-certificate-authority[detailed instructions^] on how to set up your own CA infrastructure with IM certificates.


[#create_keys_csr]
==== Generating keys and CSRs

To generate the server key, Certificate Signing Request (CSR), and extension file, follow the procedure described in the section on xref:createcsr[Certificate Issuance via a Commercial CA].
The procedure and the required files are identical.


[#signyourself]
==== Signing the CSR

To sign certificates yourself, you need at least one private key (here, `intermediate.key.pem`) and the corresponding intermediate certificate `intermediate.pem`.
If you also have a configuration file, specify the file path using the `--config` parameter.

You can then sign the CSR file `checkmk.mydomain.com.csr`, the extension file `checkmk.mydomain.com.ext`, and the output file `checkmk.mydomain.com.crt` using the following command:

[{shell}]
----
{c-user} openssl x509 -CAcreateserial -req \
    -in checkmk.mydomain.com.csr \
    -CA intermediate.pem -CAkey intermediate.key.pem \
    -out checkmk.mydomain.com.crt -days 365 \
    -sha256 -extfile checkmk.mydomain.com.ext
----

In addition to the server certificate `checkmk.mydomain.com.crt` created here, you must provide your CA certificate `intermediate.pem`.
If you are not a root CA, you must also provide the root certificate (referred to as `ca_certificate_intern.pem` in the text below).


[#import_cert]
==== Importing a certificate

The steps for importing a CA certificate as trusted vary from browser to browser.
In most cases, it is sufficient to add the certificate `ca_certificate_intern.pem` under [.guihint]#Settings > Privacy# and [.guihint]#Security > Certificates > Import#.

To ensure that certificate management does not pose an obstacle to automatic agent updates in the commercial editions, in the xref:glossar#agent_bakery[Agent Bakery] we have provided the option to specify a xref:agent_deployment#certificates_for_https[custom CA certificate] that is used exclusively for agent updates.
The system certificates remain unaffected, and agent updates are still possible.

[TIP]
====
If you are working with intermediate CAs, you must provide the Agent Updater with the complete certificate chain via the Agent Bakery!
====

If scripts that access the REST API, for example, are supposed to trust your own certificates, copy the file `ca_certificate_intern.pem` to `/usr/local/share/ca-certificates/`.
Then regenerate the cache:

[{shell}]
----
{c-root} update-ca-certificates
----

In Windows, you can manage system certificates using the 'Certificates' MMC snap-in.
This is necessary, for example, if you want to use a Microsoft browser to access a {CMK} secured with your own CA.
You can find the exact procedure in the link:https://docs.microsoft.com/en-us/troubleshoot/windows-server/windows-security/import-third-party-ca-to-enterprise-ntauth-store#method-1---import-a-certificate-by-using-the-pki-health-tool[Microsoft Knowledge Base article PKI^].
Alternatively, you can distribute certificates via link:https://docs.microsoft.com/en-us/mem/intune/protect/certificates-configure[Intune^].


[#apache]
== Configuring the Apache Web Server

In this section, you will enable SSL configuration and assign the certificates.
Once the {CMK} server is accessible via HTTPS, you will add redirection from HTTP to HTTPS.

[TIP]
====
If you have used the xref:letsencrypt_fully_automated[fully automated mode of Let's Encrypt], the required xref:apache_modules[Apache modules] will be active, and a xref:configsample[_Vhost_] configuration will have been created.
After verifying that your {CMK} server is accessible via HTTPS, you can proceed with xref:httpsredirect[setting up HTTPS redirection].
====


[#firewall]
=== Allow Port 443 in the firewall

Make sure your firewall allows incoming traffic on port 443 (HTTPS).
If you are using `firewalld`, authorize the web server and apply the change using the following two commands:

[{shell}]
----
{c-root} firewall-cmd --zone=public --add-service=https --permanent
success
{c-root} firewall-cmd --reload
success
----


[#apache_modules]
=== Enabling modules

HTTPS security for the {CMK} interface requires the Apache module `mod_ssl`.
In the rest of the setup process, we will also assume that incoming connections on the unencrypted port 80 should be redirected to the SSL-encrypted port 443.
This requires the `mod_rewrite` module.
Finally, `mod_headers` is needed so that the externally accessible Apache server, configured as a link:https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html[reverse proxy^], can forward the request headers to the xref:ports#loopback[Apache server].

Depending on the distribution, the required Apache modules may be compiled into the web server, included but disabled, or available as separate packages to be installed.

[.tabs]
====
[#tab_debian]#Debian/Ubuntu#::
+
--

You can use the `apachectl` command to view the loaded Apache modules.
Use `grep` to check immediately whether all three required modules are present:

[{shell}]
----
{c-root} apachectl -M | grep -E 'headers|rewrite|ssl'
 rewrite_module (shared)
----

You can enable missing modules using the `a2enmod` script.
This creates symbolic links in the `/etc/apache2/mods-enabled` directory.
The file with the `.load` extension contains instructions for loading the module, and the `.conf` file contains the module's actual configuration:

[{shell}]
----
{c-root} a2enmod ssl
Enabling module ssl.
To activate the new configuration, you need to run:
  systemctl restart apache2
{c-root} a2enmod headers
Enabling module headers.
To activate the new configuration, you need to run:
  systemctl restart apache2
----
--
[#tab_rhel]#Red Hat#::
+
--

On Red Hat Enterprise Linux and distributions based on it, `mod_ssl` is a separate package that you must install on its own:

[{shell}]
----
{c-root} dnf install httpd mod_ssl
----

--
[#tab_sles]#SUSE#::
+
--

SLES and openSUSE Leap include the required modules pre-compiled into the Apache binary.
These are enabled via startup parameters, which must be specified in the `/etc/sysconfig/apache2` file:

[{file}]
----
APACHE_SERVER_FLAGS="SSL"
----

In contrast, `mod_headers`, which is required for forwarding headers, is a dynamically loaded module; it is enabled using `a2enmod`.

[{shell}]
----
{c-root} a2enmod headers
Enabling module headers.
To activate the new configuration, you need to run:
  systemctl restart apache2
----

--
====

Do not restart Apache yet.
In many cases, the configuration now contains paths to nonexistent files, which will prevent Apache from starting.
You will modify the configuration in the next section.


[#configsample]
=== Configuring an HTTPS connection for a site

Once the modules have been set up, you must specify the correct file paths to the key, certificate, and intermediate certificate in the SSL configuration file.
Here, we will show you the simplest configuration with one certificate per server, which is specified in the default configuration file.
Since Apache supports _Server Name Indication_, different _virtual hosts_ can use different certificates, which are defined on a per-_vhost_ basis.
This is beyond the scope of this article.

In the following examples, `SSLCertificateKeyFile` refers to the private key generated earlier for this server.
`SSLCertificateChainFile` contains the intermediate certificate or, if applicable, a chain of intermediate certificates.
This is omitted only in the case of an internal CA, where the CA key is used to sign directly.

Our example also adds two lines: `RequestHeader set X-Forwarded...`.
These ensure that the xref:ports#loopback[Apache site on port 5000] is informed that the request was made via SSL, meaning security rules were followed.
As a result, [.guihint]#Analyze configuration# will recognize the configuration for [.guihint]#Secure GUI (HTTP)# as {OK}.

[.tabs]
====
[#tab_debian2]#Debian/Ubuntu#::
+
--

First, you must enable the configuration for the default SSL site:

[{shell}]
----
{c-root} a2ensite default-ssl
Enabling site default-ssl.
To activate the new configuration, you need to run:
  systemctl reload apache2
----

Now modify the configuration:

./etc/apache2/sites-available/default-ssl.conf
[{apache}]
----
SSLCertificateKeyFile /etc/certs/checkmk.mydomain.com.key
SSLCertificateChainFile /etc/certs/ca_bundle.crt
SSLCertificateFile /etc/certs/certificate.crt
----

...or with Let's Encrypt:

./etc/apache2/sites-available/default-ssl.conf
[{apache}]
----
SSLCertificateKeyFile /etc/letsencrypt/live/checkmk.mydomain.com/privkey.pem
SSLCertificateChainFile /etc/letsencrypt/live/checkmk.mydomain.com/chain.pem
SSLCertificateFile /etc/letsencrypt/live/checkmk.mydomain.com/cert.pem
----

Insert the following lines immediately before the closing `</VirtualHost>` tag:

./etc/apache2/sites-available/default-ssl.conf
[{apache}]
----
<IfModule headers_module>
    RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
    RequestHeader set X-Forwarded-SSL expr=%{HTTPS}
</IfModule>
----

Then restart the Apache process:

[{shell}]
----
{c-root} systemctl restart apache2
----

--
[#tab_rhel2]#Red Hat#::
+
--
Edit the file `/etc/httpd/conf.d/ssl.conf`:

./etc/httpd/conf.d/ssl.conf
[{apache}]
----
SSLCertificateKeyFile /etc/certs/checkmk.mydomain.com.key
SSLCertificateChainFile /etc/certs/ca_bundle.crt
SSLCertificateFile /etc/certs/certificate.crt
----

...or with Let's Encrypt:

./etc/httpd/conf.d/ssl.conf
[{apache}]
----
SSLCertificateKeyFile /etc/letsencrypt/live/checkmk.mydomain.com/privkey.pem
SSLCertificateChainFile /etc/letsencrypt/live/checkmk.mydomain.com/chain.pem
SSLCertificateFile /etc/letsencrypt/live/checkmk.mydomain.com/cert.pem
----

Insert the following lines immediately before the closing `</VirtualHost>` tag:

./etc/httpd/conf.d/ssl.conf
[{apache}]
----
<IfModule headers_module>
    RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
    RequestHeader set X-Forwarded-SSL expr=%{HTTPS}
</IfModule>
----
Then restart the Apache process:

[{shell}]
----
{c-root} systemctl restart httpd
----

--
[#tab_sles2]#SUSE#::
+
--

SLES and openSUSE Leap include a sample SSL configuration file.
This must be copied to a file with the `.conf` extension so that it can be read:

[{shell}]
----
{c-root} cp -v /etc/apache2/vhosts.d/vhost-ssl.template /etc/apache2/vhosts.d/vhost-ssl-default.conf
'/etc/apache2/vhosts.d/vhost-ssl.template' -> '/etc/apache2/vhosts.d/vhost-ssl-default.conf'
----

In the target file, you only need to modify the two or three lines for the key, the certificate, and, if necessary, the chain:

./etc/apache2/vhosts.d/vhost-ssl-default.conf
[{apache}]
----
SSLCertificateKeyFile /etc/certs/checkmk.mydomain.com.key
SSLCertificateChainFile /etc/certs/ca_bundle.crt
SSLCertificateFile /etc/certs/certificate.crt
----

...or with Let's Encrypt:

./etc/apache2/vhosts.d/vhost-ssl-default.conf
[{apache}]
----
SSLCertificateKeyFile /etc/letsencrypt/live/checkmk.mydomain.com/privkey.pem
SSLCertificateChainFile /etc/letsencrypt/live/checkmk.mydomain.com/chain.pem
SSLCertificateFile /etc/letsencrypt/live/checkmk.mydomain.com/cert.pem
----

Insert the following lines immediately before the closing `</VirtualHost>` tag:

./etc/apache2/sites-available/default-ssl.conf
[{apache}]
----
<IfModule headers_module>
    RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
    RequestHeader set X-Forwarded-SSL expr=%{HTTPS}
</IfModule>
----

Then restart the Apache process:

[{shell}]
----
{c-root} systemctl restart apache2
----

--
====


[#httpsredirect]
=== Adding an HTTPS redirect

Apache uses virtual hosts to deliver different content under a single IP address.
Since a dedicated {CMK} server typically uses only one virtual host with a server name, make the settings only in the _default vhost_ or in the global Apache configuration.

[.tabs]
====
[#tab_debian3]#Debian/Ubuntu#::
+
--
Debian and Ubuntu use a separate configuration file for the _default virtual host_ on port 80.
Insert the following lines there immediately before the closing `</VirtualHost>` tag:

./etc/apache2/sites-enabled/000-default
[{apache}]
----
RewriteEngine On
# Never forward requests for .well-known (important when using Let's Encrypt)
RewriteCond %{REQUEST_URI} !^/.well-known
RewriteRule (.*) https://%{HTTP_HOST}$1 [L]
----

Then restart the Apache process:

[{shell}]
----
{c-root} systemctl restart apache2
----
--
[#tab_rhel3]#Red Hat#::
+
--
Red Hat does not use the `VirtualHost` directive; instead, it defines the behavior for port 80 in the rather confusing file `/etc/httpd/conf/httpd.conf`.
This file does, however, read files with the `.conf` extension in the `/etc/httpd/conf.d/` directory.
Create a new file `/etc/httpd/conf.d/redirect_to_https.conf` with the following content:

./etc/httpd/conf.d/redirect_to_https.conf
[{apache}]
----
RewriteEngine On
# Never redirect requests for .well-known (important when using Let's Encrypt)
RewriteCond %{REQUEST_URI} !^/.well-known
# The next 2 lines: Only enforce the redirect if the incoming request is not coming through port 443
RewriteCond %{SERVER_PORT} !^443$
RewriteRule (.*) https://%{HTTP_HOST}$1 [L]
----

Then restart the Apache process:

[{shell}]
----
{c-root} systemctl restart httpd
----
--
[#tab_sles3]#SUSE#::
+
--
Like Red Hat, SUSE does not use a `VirtualHost` directive for the default behavior on port 80.
You can either create a virtual host by copying the configuration file `/etc/apache2/vhosts.d/vhost.template` to `/etc/apache2/vhosts.d/vhost-default.conf` and customizing that file—this solution is very flexible, but somewhat more involved than the following alternative.
Or you can take the easier route and create a global configuration file `/etc/apache2/conf.d/redirect_to_https.conf` with the following content:

./etc/apache2/conf.d/redirect_to_https.conf
[{apache}]
----
RewriteEngine On
# Never forward request for .well-known (important when using Let's Encrypt)
RewriteCond %{REQUEST_URI} !^/.well-known
# Next 2 lines: Force redirection only if incoming request is not on 443
RewriteCond %{SERVER_PORT} !^443$
RewriteRule (.*) https://%{HTTP_HOST}$1 [L]
----

Then restart the Apache process:

[{shell}]
----
{c-root} systemctl restart apache2
----
--
====


[#activate_hsts]
=== Setting Up HSTS

Making the {CMK} server accessible only via HTTPS is the first and most important step in securing connections to the monitoring system.
However, you can further enhance security with additional, optional settings.
This allows the web server to instruct the browser to access it only via HTTPS in the future and to always reject unsecured connections via HTTP.

This technique is called HTTP Strict Transport Security (HSTS) and is set for a specific duration in seconds.
Once this limit has expired, the browser checks again to see if the HSTS restriction is still valid.


[#hsts_specifics]
==== Special Considerations

Configuring HSTS has the advantage of ensuring that only secure connections are used.
Its implementation also involves certain special considerations that you must be aware of _before_ making the switch:

* Once the HSTS entry has been created by the user's browser, it can—at least before it expires—only be removed with detailed knowledge of that specific browser. Note that many users do not have this knowledge.

* The connection will be rejected, among other reasons, if the certificate has expired or been replaced by a self-signed certificate.
Such sites also cannot be accessed by temporarily trusting a certificate via an exception.

* Conversely, HSTS is only taken into account if the certificate is *trusted* when the connection is first established.
If not, the browser will not create an HSTS entry, meaning that the additional protection mechanism will not be utilized.


==== Enabling HSTS in the SSL Configuration

HSTS is enabled via an additional header line.
You must enter this in the xref:configsample[configuration file for your SSL settings] within the `<VirtualHost> ... </VirtualHost>` block:

[{apache}]
----
Header always set Strict-Transport-Security 'max-age=43200'
----


[TIP]
====
Start by setting a short time period—e.g., 300 seconds—to test the setting, since otherwise the connection might be rejected for a very long time if an error occurs!
For more information, see also xref:hsts_specifics[Specifics].
====

To see if the new setting works, you can use the `curl` program to query the server.
Here are just the first 4 lines of the output:

[{shell}]
----
{c-root} curl -I pass:q[https://mycmkserver/mysite/check_mk/login.py]
HTTP/1.1 200 OK
pass:q[*Date*]: Fri, 12 Jun 2026 08:34:57 GMT
pass:q[*Server*]: Apache
pass:q[*Strict-Transport-Security*]: max-age=43200
----
