// -*- coding: utf-8 -*-
// IGNORE 
include::global_attr.adoc[]
:current: pass:q[[.new]#2.3.0#]
= Release notes
:revdate: 2025-02-17
:title: Release notes - for {CMK} {current}
:description: Checkmk 2.3.0 works with a range of platforms and integrations supported during the product lifecycle's active maintenance.

{related-start}
xref:update_major#[Update to version 2.3.0]
xref:update_matrix#[Update matrix for version 2.3.0]
xref:install_packages#[Basic information on the installation of {CMK}]
xref:agent_linux#[Monitoring Linux]
xref:agent_windows#[Monitoring Windows]
{related-end}


== Introduction

This document lists the platforms and integrations supported by {CMK} {current}.
Except for very specific reasons (e.g. security), these platforms, including all patch versions will remain supported through active maintenance during the {CMK} {current} product lifecycle.


[#os]
== Server OS

{CMK} can be installed on the following Linux server operating system distributions and versions, that run on x86_64 hardware.
We provide a list of supported versions.
Entries may contain the following additions:

* _Deprecated:_ LTS/LTSS versions marked in this way are still supported for the entire life cycle of version {current}. Support will be ceased afterwards.
* _Once released:_ Support for these versions is planned. {CMK} {current} packages will be made available shortly after the release of the new distribution version.

We will additionally evaluate any new versions of these distributions as a part of our ongoing support process.
These will be covered in the xref:update_matrix#[update matrix].

[cols="33,~,~",options=header]
|===
|Operating system |Supported versions | Supported since {CMK} version
|Debian |10 Buster (deprecated) | {v23}
| | 11 Bullseye | {v23}
| | 12 Bookworm| {v23}
|Red Hat Enterprise Linux |8 | {v23}
| |9 | {v23}
| |10 | 2.3.0p41
|SUSE Linux Enterprise Server |12 SP5 (deprecated) | {v23}
| |15 SP3 | {v23}
| |15 SP4 | {v23}
| |15 SP5 | {v23}
| |15 SP6 | {v23}p14
|Ubuntu |20.04 LTS Focal Fossa (deprecated) | {v23}
| | 22.04 LTS Jammy Jellyfish | {v23}
| | 24.04 LTS Noble Numbat | {v23}p4
|===

Ubuntu STS versions are no longer supported as of {CMK} {v23}, users of Ubuntu 23.10 must xref:release_upgrade#[upgrade to Ubuntu 24.04] under {CMK} {v22} before they can switch to {CMK} {v23}.


[#browser]
== Browser

The {CMK} user interface has been verified as able to be run on the following desktop browsers and minimum versions:

* Google Chrome >= 121 on Windows, Linux and macOS
* Firefox >= 122 on Windows, Linux and macOS
* Microsoft Edge >= 121 on Windows
* Safari >= 17.2 on macOS

The {CMK} mobile user interface has been verified to run on the following mobile browsers:

* Safari on iPadOS/iPhoneOS (current and last major OS release)
* Google Chrome on Android (current and last major OS release)

[#agent]
== OS for the {CMK} agent

The {CMK} agent can be installed and run on the following operating systems if the OS meets some basic requirements.

=== Linux/Unix

All Linux distributions and various Unix operating systems such as _Solaris_ and _AIX_ are supported, provided they have at least the following technical components in the minimum version:

* Bash >= 4.2
* ksh >= 93
* Perl >= 5.14.0

Additionally, one of the following components needs to be present:

* systemd >= 219
* xinetd (no minimal version)

Be aware: Plug-ins may require a specific version of additional components to be functional.
Python plug-ins require version 2.7 or > 3.5.

[#windows]
=== Windows

All 64-bit versions of the following Windows operating system releases are supported:

* 2016
* 2019
* 2022
* 2025

For older releases, we provide a link:https://download.checkmk.com/legacy-agents/[legacy agent^] with a limited feature set and without official support.


[#grafana]
== Grafana plug-in

{CMK} {current} supports the following Grafana plug-in versions:

* >= 3.0.0


[#appliance]
== {CMK} Appliance

// MFS: Check back with devs 
{CMK} {current} can run on the following versions of the {CMK} Appliance:

* >= 1.6.8


[#ldap]
== LDAP server

With LDAP {CMK} {current} supports synchronization of the following LDAP servers:

* Microsoft Active Directory
* OpenLDAP
* 389 Directory Server


[#saml]
== SAML IdP

The SAML integration supports the following Identity Providers (IdPs):

* Microsoft Entra ID (called Azure Active Directory until 2023)
* Google Cloud
* Okta

{CMK} may work with other SAML integrations as well, but no support can be given for these.


[#ntopng]
== ntopng

The ntopng integration supports the following versions of ntopng Professional and Enterprise:

* 5.6 (deprecated)
* >= 6.0


[#nagvis]
== Nagvis

Nagvis depends on PHP and requires a minimum version to run.
To run Nagvis, make sure to have a matching version of PHP in your installation:

* >= 7.2

Depending on the Linux distribution used, the version defined as a dependency of the {CMK} installation package may be higher.

[#influxdb]
== InfluxDB

{CMK} supports the export of data to the following versions of the InfluxDB API:

// MFS: Check back with devs 
* >= 2.0

== Change log

=== Corrections

==== 12-Jul-2024

* Windows 2012 & Windows 2012 R2 have been removed from the list of supported operating systems for agents as they are incompatible with Python 3.12.
A partial function of the current agent is possible, but cannot be guaranteed or officially supported.

==== 17-Feb-2025 

* After testing, Windows 2025 was added to the list of supported operating systems for agents.

==== 26-Nov-2025

* The list of supported Linux distributions got updated: 

* Ubuntu 24.04 LTS Noble Numbat is supported since {CMK} version {v23}p4.

* SUSE Linux Enterprise Server (SLES) 15 SP6 is supported since {CMK} version {v23}p14. 

* SUSE Linux Enterprise Server (SLES) 15 SP7 is supported since {CMK} version {v23}p41.

* Red Hat Enterprise Linux 10 (RHEL 10) is supported since {CMK} version {v23}p41.
