// -*- coding: utf-8 -*-
// IGNORE 
include::global_attr.adoc[]
= Release notes
:revdate: 2023-06-07
:title: Release notes - for {CMK} {v22}
:description: Checkmk 2.2.0 works with a range of platforms and integrations supported during the product lifecycle's active maintenance.

{related-start}
xref:update_major#[Update to version 2.2.0]
xref:update_matrix#[Update matrix for version 2.2.0]
xref:install_packages#[Basic information on the installation of {CMK}]
xref:agent_linux#[Monitoring Linux]
xref:agent_windows#[Monitoring Windows]
{related-end}


== Introduction

This document lists the platforms and integrations supported by {CMK} {v22}.
Except for very specific reasons (e.g. security), these platforms, including all patch versions will remain supported through active maintenance during the {CMK} {v22} product lifecycle.


[#os]
== Server OS

{CMK} can be installed on the following Linux server OS distributions and versions running on x86_64 hardware.
We will additionally evaluate any new versions of these distributions as a part of our ongoing support process.
These will be covered in the xref:update_matrix#[update matrix].

[cols="20,~",options=header]
|===
|Operating system |Supported versions
|*Ubuntu* |20.04
| |22.04
|*Debian* |10
| |11
|*RHEL* |7
| |8
| |9
|*SLES* | 12 SP5
| |15 SP1
| |15 SP2
| |15 SP3
| |15 SP4
|===


[#browser]
== Browser

The {CMK} user interface has been verified as able to be run on the following desktop browsers and minimum versions:

* Google Chrome >= 100 on Windows, Linux and macOS
* Firefox >= 100 on Windows, Linux and macOS
* Microsoft Edge >= 100 on Windows
* Safari >= 15.6.1 on macOS

The {CMK} mobile user interface has been verified to run on the following mobile browsers:

* Safari on iOS (current and last major OS release)
* Google Chrome on Android (current and last major OS release)

[#agent]
== OS for the {CMK} agent

The {CMK} agent can be installed and run on the following operating systems if the OS meets some basic requirements.

=== Linux/Unix

All Linux and Unix operating system releases are supported, if at least the minimal version of these technical components as listed below is installed:

* Bash >= 4.2
* ksh >= 93
* Perl >= 5.14.0

Additionally, one of the following components needs to be present:

* systemd >= 219
* xinetd >= all versions

Please be aware: Plug-ins may require a specific version of additional components to be functional.
Python plug-ins require version 2.7 or > 3.5.

=== Windows

All 64-bit versions of the following Windows operating system releases are supported:

* 2012
* 2012 R2
* 2016
* 2019
* 2022

For older releases, we provide a link:https://download.checkmk.com/legacy-agents/[legacy agent^] with a limited feature set and without official support.


[#grafana]
== Grafana plug-in

{CMK} {v22} supports the following Grafana plug-in versions:

* >= 3.0.0


[#appliance]
== {CMK} Appliance

{CMK} {v22} can run on the following versions of the {CMK} Appliance:

* >= 1.6.3


[#ldap]
== LDAP server

With LDAP {CMK} {v22} supports synchronization of the following LDAP servers:

* Microsoft Active Directory
* OpenLDAP
* 389 Directory Server


[#saml]
== SAML IdP

The SAML integration supports the following Identity Providers (IdPs):

* Microsoft Azure Active Directory
* Google Cloud
* Okta

{CMK} may work with other SAML integrations as well, but no support can be given for these.


[#ntopng]
== ntopng

The ntopng integration supports the following versions of ntopng Professional and Enterprise:

* >= 5.6


[#nagvis]
== Nagvis

Nagvis depends on PHP and requires a minimum version to run.
To run Nagvis, please make sure to have a matching version of PHP in your installation:

* >= 7.2


[#influxdb]
== InfluxDB

{CMK} supports the export of data to the following versions of the InfluxDB API:

* >= 2.0
