// -*- coding: utf-8 -*-
// IGNORE
// NONASCII
include::global_attr.adoc[]
= Upgrades
:title: Upgrades
:description: {CMK} allows changing the edition to one with a greater or lesser range of functionality. Read here how to achieve edition changes.
:experimental:

{related-start}
xref:omd_basics#[Site administration with omd]
xref:update#[Updates]
xref:license#[Managing licenses]
xref:cmc#[The {CMK} Micro Core]
xref:cmc_migration#[Migration to the CMC]
{related-end}

[#intro]
== Introduction

TBD.

// MFS: New, needs to be translated
////
Während Updates zum täglichen Geschäft gehören – Patch-Versionen erscheinen in den ersten Monaten nach Erscheinen einer neuen Major-Version wöchentlich, später monatlich – sind Upgrades der Edition deutlich seltenere Ereignisse.
Meist gehen sie mit Budgetbewilligungen einher, die entweder überhaupt den Wechsel von {RE} zu einer kommerziellen Edition ermöglichen oder erlauben, künftig den größeren Funktionsumfang von {UE} verglichen mit {SE} wahrzunehmen.

Aber auch der umgekehrte Weg ist manchmal notwendig:
Da kratzt die im Homelab betriebene {UE} am Limit der Service-Zahl im Lizenzstatus _Free_ und erfordert zur kostenlosen Weiternutzung von {CMK} den Wechsel zu {RE}.
Oder das neue Management streicht Budgets zusammen.
Hierfür erlaubt {CMK} auch Downgrades, die natürlich etwas mehr Vor- und Nachbereitung erfordern.

[TIP]
====
Dieser Artikel behandelt das _Upgrade_ der {CMK}-Edition, also den Wechsel zu einer Edition mit größerem Funktionsumfang, beispielsweise von {CRE} auf eine der kommerziellen Editionen oder von {CSE} nach {CUE}.
Das _Update_ der {CMK}-Version, sowie die Verwendung des in beiden Fällen benutzten Befehls `omd update` behandelt der separate xref:update#[Artikel zu Updates].
Weitere Informationen zur Instanzverwaltung (wozu auch das Aufräumen nicht mehr benötigter {CMK}-Pakete gehört) finden Sie im xref:omd_basics#[Artikel zu den Grundlagen des `omd`-Werkzeugs].
====
////


[#preparation]
== Preparing the upgrade

TBD.

// MFS: New, needs to be translated
////
Editions-Upgrades können mit Updates der {CMK}-Major-Version kombiniert werden, also beispielsweise von {RE} {oldstable-patch} auf {SE} {current}.
Wir empfehlen jedoch, _dieselbe_ {CMK}-Version und dort dasselbe Patchlevel zu verwenden.
In der Praxis bedeutet dies, dass Sie vor dem Update auf das letzte verfügbare xref:update#[Patch-Release aktualisieren] sollten, bevor Sie das Upgrade angehen.
Spätestens dieses Update vor dem Upgrade ist die Möglichkeit, sich mit dem `omd`-Befehl vertraut zu machen. 

Bei einem Upgrade wird der _Lizenzstatus_ zurückgesetzt.
Dies gilt auch, wenn Sie aus organisatorischen Gründen zunächst beispielsweise {SE} mit einer Lizenz für {UE} betrieben haben.
Im Idealfall haben Sie daher die Lizenzinformationen zur Hand, um sie gleich nach dem Upgrade eintragen zu können.
////

[#execution]
== Executing the upgrade

TBD.

// MFS: New, needs to be translated
////
Das eigentliche Upgrade geschieht ebenfalls mit dem `omd`-Befehl:

[{shell}]
----
{c-omd} omd update
----

In der angezeigten Dialogbox macht `omd` keinen Unterschied zwischen Update und Upgrade.
Die im Hintergrund arbeitenden Mechanismen sind dieselben.

// In der XML-Datei wird eine Patch-Version hardkodiert, während in den vorhergehenden und folgenden Befehlsausgaben mit {oldstable-patch} die aktuellste Patch-Version gezeigt wird.
++++
include::update_omd-update-upgrade.xml[]
++++

Sobald Sie Ihre Instanz wieder starten, arbeitet diese wie gewohnt.
Allerdings ist es sinnvoll, einige Einstellungen vorzunehmen, um vom gestiegenen Funktionsumfang und höherer Performance zu profitieren.
Diese erläutern wir in den folgenden Kapiteln.
////


// MFS: Moved over from update.asciidoc
[#updateraw]
=== Upgrading {RE} to one of the commercial editions

This chapter primarily covers an upgrade to {CSE}.
You can also upgrade to {CE} in one step, but in this case, also refer to the notes in the xref:cee2cce[following section].

Since the commercial editions have quite a few additional modules and features, there are a few things to keep in mind following any upgrade.
The crucial point is that when creating _new_ sites in {RE} or one of the commercial editions, _different default settings_ are set.


// MFS: Moved over from update.asciidoc
==== Nagios vs. the CMC

Since {RE} only supports Nagios as its core, this is the default setting for sites created with {RE}.
This setup will be preserved when upgrading to {SE}.
This means that after an upgrade you will initially continue to run with Nagios as the core.
A migration to the CMC is done with `omd config` and is described in its own article xref:cmc_migration#[Migration to the CMC].


// MFS: Moved over from update.asciidoc
==== The RRD format

The commercial editions support an alternative format for storing historical measurement data, which generates significantly less disk I/O.
This format is automatically preset for new commercial edition sites.
Again, {RE} sites are not automatically converted during an upgrade.
How to switch the data formats is described in a separate xref:graphing#rrdformat[section] in the article on measured values and graphing.


// MFS: Moved over from update.asciidoc
==== Further differences

To take full advantage of {SE}, refer to the overview of differences between {RE} and xref:cse#[{SE}].


// MFS: Moved over from update.asciidoc
[#cee2cce]
=== Upgrading from {SE} to {CE}

When it comes to the monitoring core and the notification system, there are no differences between {SE} and {CE}.
Depending on the focus of the deployment, you will often use the larger feature set only when adding new hosts.
In some places, however, it is still advisable to review the existing settings.

For a complete overview of the additional functionality, see the article on xref:cce#[{CE-onprem}].


// MFS: Moved over from update.asciidoc
==== Check plug-ins for cloud services

When you monitor xref:monitoring_aws#[Amazon Web Services (AWS)], xref:monitoring_azure#[Microsoft Azure], or xref:monitoring_gcp#[Google Cloud Platform (GCP)], the services in existing hosts reserved for {CE} will initially not be enabled.
You can enable these services in the [.guihint]#XYZ services to monitor# rule (where XYZ is the name of the cloud platform).
Then perform a xref:glossar#service_discovery[service discovery] on these hosts to find the services that will now be available.


// MFS: Moved over from update.asciidoc
==== Agent Controller in push mode

With the ability to directly monitor hosts that can reach the {CMK} server but are not accessible from it, the need for homegrown solutions with xref:datasource_programs#[data source programs] is eliminated in many cases.
You can xref:agent_linux#changepush[switch these hosts to push mode] to enable a direct monitoring.


// MFS: Moved over from update.asciidoc, headings levels changed
[#editiondistributed]
== Upgrading editions in distributed environments

Note that in distributed environments, the version update must always be performed first _before_ the edition upgrade can follow.
A different sequence or a _crossgrade_ (update of the version and upgrade of the edition in a single action) is not supported.
As a general procedure, we recommend the offline upgrade, where you can jump from any lower edition to any higher edition.

For all upgrade scenarios except those targetting {ME}, mixed operation is possible for a limited period of time.


// MFS: Moved over from update.asciidoc
[#offline_distributed]
=== Offline upgrade

As mixing editions is only possible in a few combinations, we generally recommend upgrading the edition _offline_.
To do this, proceed as follows:

. Stop all sites.
. Perform the upgrade of the central site.
. If it is desired (and an abundance of notifications is not a problem), the central site can be restarted immediately.
. Now it's time to upgrade the remote sites. You can do this in parallel and restart the remote sites immediately following their upgrading.

Of course, you can wait until all sites have been upgraded before restarting them, which will somewhat reduce the number of notifications generated.


[#online_distributed]
=== Online upgrade

TBD.

// MFS: Has been completely rewritten to reflect the changes in compatibility
// MFS: Needs to be translated
////
{CMK} erlaubt den Mischbetrieb einer Zentralinstanz mit größerem Funktionsumfang mit Remote-Instanzen mit kleinerem Funktionsumfang.
Für das Upgrade bedeutet dies, dass die Zentralinstanz das Upgrade _zuerst_ erhält.
Während des Mischbetriebes sollte keine Übertragung der Konfiguration von der Zentralinstanz zu den Remote-Instanzen durchgeführt werden, die noch kein Upgrade erhalten haben.
Daher empfehlen wir, für die Dauer des Mischbetriebes auf der Zentralinstanz via [.guihint]#Setup > General > Read only mode# die Änderung der Konfiguration zu unterbinden.
Theoretisch kann solch ein Mischbetrieb beliebig lange währen – in der Praxis werden jedoch nach einiger Zeit Konfigurationsänderungen notwendig sein, die einen homogenen Editionsstand erfordern.

Für das Upgrade ergibt sich daraus folgende Reihenfolge:

. Führen Sie das Upgrade der Zentralinstanz durch.
. Geben Sie die Subskriptionsdaten ein und übermitteln Sie diese, wie im Artikel zur xref:license#[Lizenzierung] beschrieben.
Die von allen Remote-Instanzen bereitgestellten Services werden bei der Berechnung der Subskription gleich behandelt,
das heißt, während des Mischbetriebes werden Services von {RE} Remote-Instanzen bereits als {SE} oder {UE} abgerechnet.
. Aktualisieren Sie nach und nach die Remote-Instanzen.
. Falls Sie die Übertragung der Konfiguration nicht global, sondern für jede Remote-Instanz separat deaktiviert haben, können Sie die Übertragung der Konfiguration für jede Remote-Instanz, welche das Upgrade erhalten hat, wieder aktivieren.
. Im verteilten Monitoring ohne xref:glossar#central_setup[zentrales Setup] müssen auch die Remote-Instanzen gleich nach dem Upgrade lizenziert werden.

Nach dem Upgrade aller Instanzen können Sie die spezifischen Features der neuen Edition aktivieren.
////

.Why do we recommend not to synchronize the configuration during the upgrade?
[%collapsible]
====
Remote sites actually discard settings that they 'can't do anything with'.
This does not break anything, but it can mess things up.
Let's say you activate a {SE} specific setting -- for example xref:basics_downtimes#scheduled[regular scheduled downtimes] -- before all remote sites have received the upgrade.
In this case, {RE} sites will discard the setting, which means that it will not be available even after the upgrade.
The setting will only be available once it has been changed again after the upgrade.

If it is unavoidable not to synchronize the configuration during the upgrade, check the consistency of {SE} specific settings after the complete upgrade.
====


// MFS: Moved over from update.asciidoc
[#down2cee]
== Downgrades

Downgrades between editions are also possible.
A downgrade is a more complex and thus time-consuming action, since some features may not work in the target edition,
and will need to be manually deactivated and replaced by a possibly less efficient or less convenient alternative.

The actual downgrade *must* be carried out with the command `omd update` - just like an update or upgrade.
The details can be found in the section xref:update#execute[Performing the update].

If you try to downgrade from {CE} to {SE}, for example, {CMK} will verify whether this is actually your intention:

++++
include::update_downgrade_ce_se.xml[]
++++

As soon as you confirm this dialog with [.guihint]#yes#, the downgrade starts immediately.
Please find out below what you need to do *before* this downgrade.

Downgrades other than those described below are not intended and are not supported by us, for example a downgrade of {ME}.
Instead, we recommend starting with a fresh site in such a case.


// MFS: Moved over from update.asciidoc
[#cce2cee]
=== Downgrading from {CE} to {SE}

In preparation for the downgrade from {CE} to {SE}, you must make at least the following changes:

* Set hosts that operate in push mode to xref:agent_linux#changepush[pull mode].
Otherwise {CMK} will not receive monitoring data from them and their associated hosts will usually become xref:monitoring_basics#stale[_stale_].

* Reconfigure the agent packages for folders to stop xref:hosts_autoregister#[auto-registration].
Then rebake the agent packages.

Furthermore, some cloud services and dashboards will no longer be available.
As a result, you will need to clean up xref:wato_services#vanished[vanished services].

// MFS: Has been changed for the latest Grafana plug-in, not necessary anymore
// If under {CE} you used the xref:grafana#[Grafana plug-in] from the 'Grafana Store', you will need to replace it with one installed from the zip archive.

An overview of the differences between {CE} and {SE} is provided by the article on xref:cce#[{CE-onprem}].


// MFS: Moved over from update.asciidoc
[#cee2cre]
=== Downgrading from {SE} to {RE}

In preparation for downgrading from {SE} to {RE}, you will need to make at least the following changes:

* Change the RRD database format with the [.guihint]#Configuration of RRD databases of hosts# rule to [.guihint]#Multiple RRDs per host/service#.
Besides slight performance disadvantages, it should be noted here that conversion of existing data is not included, so historical monitoring data will no longer be visible.

* Switch the monitoring core from CMC to Nagios -- in the first place this change is likely to result in performance disadvantages.

In addition, some dashboards, graph settings, notification plug-ins and special agents are no longer available.
With the xref:cse#[{SE} article] you can determine how much {SE} functionality will be lost in the event of a downgrade to {RE} and where you may need to make further adjustments.

// MFS: Moved over from update.asciidoc
[#editiondistributed_down]
=== Edition downgrades in distributed environments

The downgrade scenarios presented in the two previous sections can also be carried out in distributed environments.
Note that in distributed environments, the version update must always be performed first _before_ the edition downgrade can follow.
A different sequence or a _crossgrade_ (update of the version and downgrade of the edition in a single action) is not supported.

There is no downgrade scenario in which {CMK} supports a mixed operation between differing editions.
For this reason, we strongly recommend that you perform the edition downgrade _offline_.
To do this, proceed as follows:

. Stop all sites.
. Perform the downgrade of the central site.
. If it is desired (and an abundance of notifications is not a problem), the central site can be restarted immediately.
. Now it's time to downgrade the remote sites.
You can do this in parallel and restart the remote sites immediately following their downgrading.

Of course, you can wait until all sites have been downgraded before restarting them, which will somewhat reduce the number of notifications generated.
