// -*- coding: utf-8 -*-
// IGNORE
// NONASCII
include::global_attr.adoc[]
= Upgrades
:title: Upgrades
:description: {CMK} allows changing the edition to one with a greater or lesser range of functionality. Read here how to achieve edition changes.
:experimental:

{related-start}
xref:omd_basics#[Site administration with omd]
xref:update#[Updates]
xref:license#[Managing licenses]
xref:cmc#[The {CMK} Micro Core]
xref:cmc_migration#[Migration to the CMC]
{related-end}


[#intro]
== Introduction

While updates are part of day-to-day operations--patch versions are released weekly in the first few months after a new major version is released, and monthly thereafter--upgrades of the xref:glossar#edition[edition] are much less frequent.
These are usually accompanied by budget approvals that either make the switch from {RE} to a commercial edition possible in the first place or allow users to take advantage of the broader feature set of {UE} compared to {SE} in the future.

However the reverse action is sometimes necessary as well:
For example, the {UE} running in the home lab may be reaching the service limit under the license state "Free" and require a switch to {RE} in order to continue using {CMK} for free.
Or new management may be cutting budgets.
For this purpose, {CMK} also supports downgrades, which of course require a bit more preparation and follow-up work.

[TIP]
====
This article covers the _upgrade_ and the _downgrade_ of a {CMK} edition--that is, switching to an edition with a different feature set, such as from {RE} to one of the commercial editions or back.
An _update_ of the {CMK} version and using the `omd update` command, which is used in both situations, are covered in the separate article on xref:update#[Updates].
For more information on site management (which includes cleaning up {CMK} packages that are no longer needed), see the xref:omd_basics#[article on the basics of the `omd` tool].
====


[#preparation]
== Preparations

Edition upgrades can be combined with updates to the {CMK} major version—for example, switching from {RE} {oldstable-patch} to {SE} {current}.
However, we recommend performing an upgrade only with _the same_ {CMK} version, i.e., with identical major and patch versions.
In practice, this means that you should update your site to the latest available xref:update#update_path[patch version of the edition] you have been using before proceeding with the upgrade.
This update, at the very latest, is your opportunity to familiarize yourself with the `omd` command. 

During an upgrade, the _license state_ is reset.
This also applies if, for organizational reasons, you initially ran {SE} with a license for {UE}, for example.
Ideally, you should therefore have the xref:license#[licensing data] on hand so you can enter it immediately after the upgrade.


[#execution]
== Performing the upgrade

As with the update, the upgrade essentially consists of two steps:

. First, use the Linux distribution's package manager to install the xref:install_package[{CMK} package for the target edition].
. Next, for the site receiving the upgrade perform the xref:upgrade[activation of the new {CMK} edition] using `omd update`.


[#install_package]
=== Installing the target edition

For an upgrade, the first step is also the xref:install_packages#[installation] of the desired new {CMK} xref:cmk_versions.html#[version].
This is done exactly as in the initial installation.
In the following example, a package for Ubuntu 24.04 (Noble Numbat) is being installed:

[{shell}]
----
{c-root} apt install /tmp/{pkg-cce}-{current}_0.noble_amd64.deb
----

You can view the list of installed {CMK} versions at any time using the `omd versions` command:

[{shell}]
----
{c-root} omd versions
{current}.ultimate (default)
{current}.community
----

For details on the `omd versions` command, see the article on xref:update#install_new_versions[Updates].


[#upgrade]
=== Performing the site upgrade

The actual upgrade is performed using the `omd` command:

[{shell}]
----
{c-omd} omd update
----

In the dialog box that appears, `omd` does not distinguish between an update and an upgrade.
The mechanisms working in the background are the same.

++++
include::update_omd-update-upgrade.xml[]
++++


[#follow-up]
== Follow-ups

Once you have restarted your site, it will work as usual.
However, it is a good idea to adjust a few settings to take advantage of the expanded functionality and improved performance.
We explain these in the following sections in this article.


[#updateraw]
=== Upgrading {RE} to a commercial edition

This section primarily covers an upgrade to {CSE}.
You can also upgrade to {CE} in one step, but in this case, also refer to the notes in the xref:cee2cce[following section].

Since the commercial editions have quite a few additional modules and features, there are a few things to keep in mind following any upgrade.
The crucial point is that when creating _new_ sites in {RE} or one of the commercial editions, _different default settings_ are set.


==== Nagios vs. the CMC

Since {RE} only supports Nagios as its core, this is the default setting for sites created with {RE}.
This setup will be preserved when upgrading to {SE}.
This means that after an upgrade you will initially continue to run with Nagios as the core.
A migration to the CMC is done with `omd config` and is described in its own article xref:cmc_migration#[Migration to the CMC].


==== The RRD format

The commercial editions support an alternative format for storing historical measurement data, which generates significantly less disk I/O.
This format is automatically preset for new commercial edition sites.
Again, {RE} sites are not automatically converted during an upgrade.
How to switch the data formats is described in a separate xref:graphing#rrdformat[section] in the article on measured values and graphing.


==== Further differences

To take full advantage of {SE}, refer to the overview of differences between {RE} and xref:cse#[{SE}].


[#cee2cce]
=== Upgrading {SE} to {CE}

When it comes to the monitoring core and the notification system, there are no differences between {SE} and {CE}.
Depending on the focus of the deployment, you will often use the larger feature set only when adding new hosts.
In some places, however, it is still advisable to review the existing settings.

For a complete overview of the additional functionality, see the article on xref:cce#[{CE-onprem}].


==== Check plug-ins for cloud services

When you monitor xref:monitoring_aws#[Amazon Web Services (AWS)], xref:monitoring_azure#[Microsoft Azure], or xref:monitoring_gcp#[Google Cloud Platform (GCP)], the services in existing hosts reserved for {CE} will initially not be enabled.
You can enable these services in the [.guihint]#XYZ services to monitor# rule (where XYZ is the name of the cloud platform).
Then perform a xref:glossar#service_discovery[service discovery] on these hosts to find the services that will now be available.


==== Agent Controller in push mode

With the ability to directly monitor hosts that can reach the {CMK} server but are not accessible from it, the need for homegrown solutions with xref:datasource_programs#[data source programs] is eliminated in many cases.
You can xref:agent_linux#changepush[switch these hosts to push mode] to enable a direct monitoring.


[#editiondistributed]
== Upgrades in distributed environments

Note that in distributed environments, the version update must always be performed first _before_ the edition upgrade can follow.
A different sequence or a _crossgrade_ (update of the version and upgrade of the edition in a single action) is not supported.
As a general procedure, we recommend the offline upgrade, where you can jump from any lower edition to any higher edition.

In all upgrade scenarios except those targeting {ME}, xref:distributed_monitoring#mixed_editions[mixed operation with different editions] is possible if the following conditions are met:

* The central site runs on an edition with a broader feature set than the remote sites.
* The remote sites are integrated without configuration replication; that is, access is read-only.


[#offline_distributed]
=== Offline upgrade

As mixing editions is only possible in a few combinations, we generally recommend upgrading the edition _offline_.
To do this, proceed as follows:

. Stop all sites.
. Perform the upgrade of the central site.
. If it is desired (and an abundance of notifications is not a problem), the central site can be restarted immediately.
. Now it's time to upgrade the remote sites. You can do this in parallel and restart the remote sites immediately following their upgrading.

Of course, you can wait until all sites have been upgraded before restarting them, which will somewhat reduce the number of notifications generated.


[#online_distributed]
=== Online upgrade

{CMK} allows for xref:distributed_monitoring#mixed_editions[mixed operation] between a central site with a broader range of features, and remote sites with a more limited set of features.
For the upgrade, this means that the central site receives the upgrade _first_.
During mixed operation, the configuration should not be transferred from the central site to remote sites that have not yet received the upgrade.
Therefore, we recommend disabling configuration changes on the central site via [.guihint]#Setup > General > Read-only mode# for the duration of mixed operation.
Theoretically, such mixed operations can last indefinitely--in practice, however, configuration changes will become necessary after some time, requiring uniform editions across all sites.

This results in the following processing sequence for the upgrade:

. Perform the upgrade of the central site.

. Enter the licensing data and submit it as described in the article on xref:license#[licensing].
The services provided by all remote sites are treated equally when calculating the subscription,
meaning that during mixed operations, services from {RE} remote sites will already be billed as {SE} or {UE}.

. Update the remote sites one by one.

. If you have not globally disabled configuration transfer, but instead separately for each remote site, you can re-enable configuration transfer for each remote site that has received the upgrade.

. In xref:glossar#distributed_monitoring[distributed monitoring] without a central setup, the remote sites must also be licensed immediately after the upgrade.

After upgrading all sites, you can enable the specific features of the new edition.


.Why do we recommend not to synchronize the configuration during the upgrade?
[%collapsible]
====
Remote sites actually discard settings that they 'cannot do anything with'.
This does not break anything, but it can mess things up.
Let's say you activate a {SE} specific setting--for example xref:basics_downtimes#scheduled[regular scheduled downtimes]--before all remote sites have received the upgrade.
In this case, {RE} sites will discard the setting, which means that it will not be available even after the upgrade.
The setting will only be available once it has been changed again after the upgrade.

If it is impossible not to synchronize the configuration during the upgrade, check the consistency of {SE} specific settings after the complete upgrade.
====


[#down2cee]
== Downgrades

Downgrades between editions are also supported.
A downgrade is a more complex and therefore more time-consuming process, as some features may not work in the target edition and must be manually disabled and replaced with an alternative that may be less efficient or less user-friendly.

Be sure to carefully read the following to find out what needs to be done *before* proceeding with a downgrade.

Downgrades other than those described below are not intended and are not supported by us; for example, a downgrade from {ME}.
Instead, we recommend starting with a fresh site in such cases.


[#cce2cee]
=== Downgrading {CE} to {SE}

In preparation for the downgrade from {CE} to {SE}, you must make at least the following changes:

* Set hosts that operate in push mode to xref:agent_linux#changepush[pull mode].
Otherwise {CMK} will not receive monitoring data from these hosts, and the hosts will usually become xref:monitoring_basics#stale[_stale_].

* Reconfigure the agent packages for folders to stop xref:hosts_autoregister#[auto-registration].
Then re-bake the agent packages.

Furthermore, some cloud services and dashboards will no longer be available.
As a result, you will need to clean up xref:wato_services#vanished[vanished services].

An overview of the differences between {CE} and {SE} is provided by the article on xref:cce#[{CE-onprem}].


[#cee2cre]
=== Downgrading {SE} to {RE}

In preparation for downgrading from {SE} to {RE}, you will need to make at least the following changes:

* Change the RRD database format with the [.guihint]#Configuration of RRD databases of hosts# rule to [.guihint]#Multiple RRDs per host/service#.
Besides slight performance disadvantages, it should be noted here that conversion of existing data is not included, so historical monitoring data will no longer be visible.

* Switch the monitoring core from CMC to Nagios--in the first place this change is likely to result in performance disadvantages.

In addition, some dashboards, graph settings, notification plug-ins and special agents are no longer available.
With the xref:cse#[{SE} article] you can determine how much {SE} functionality will be lost in the event of a downgrade to {RE} and where you may need to make further adjustments.


[#editiondistributed_down]
=== Downgrade in distributed environments

The downgrade scenarios presented in the two previous sections can also be carried out in distributed environments.
Note that in distributed environments, the version update must always be performed first _before_ the edition downgrade can follow.
A different sequence or a _crossgrade_ (update of the version and downgrade of the edition in a single action) is not supported.

There is no downgrade scenario in which {CMK} supports a mixed operation between differing editions.
For this reason, we strongly recommend that you perform the edition downgrade _offline_.
To do this, proceed as follows:

. Stop all sites.
. Perform the downgrade of the central site.
. If it is desired (and an abundance of notifications is not a problem), the central site can be restarted immediately.
. Now it's time to downgrade the remote sites.
You can do this in parallel and restart the remote sites immediately following their downgrading.

Of course, you can wait until all sites have been downgraded before restarting them, which will somewhat reduce the number of notifications generated.


[#execute_downgrade]
=== Performing the downgrade

The actual downgrade *must*—just like an update or upgrade—be performed using the `omd update` command.
For details, see the article on xref:update#execute[Updates].

For example, if you want to downgrade from {CE} to {SE}, {CMK} will prompt you to confirm that this is indeed your intention:

++++
include::update_downgrade_ce_se.xml[]
++++

As soon as you confirm this prompt with [.guihint]#yes#, the downgrade will begin.